microsoft/accessibility-insights-web

src/electron/common/unified-feature-flags.ts
src/tests/unit/tests/electron/common/unified-feature-flags.test.ts

added a feature flag for the new setup/installation experience, set its default value to false and added a reference to the flag to the existing united-feature-flag.test file
- [N/A ] (UI changes only) Verified usability with NVDA/JAWS

feat(android-setup): adb setup experience flag

---

src/DetailsView/Styles/detailsview.scss

Add styling to highlight the expanded part of the nav to match the figma:

feat(nav-bar-functionality): Highlight expanded part of nav

---

src/DetailsView/components/details-view-content.tsx
src/DetailsView/details-view-container.tsx
src/tests/unit/tests/DetailsView/__snapshots__/details-view-container.test.tsx.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/DetailsView/details-view-container.test.tsx
src/tests/unit/tests/DetailsView/details-view-content.test.tsx

To unblock the nav feature I need to do some refactoring to avoid putting any more logic into details view container.

refactor: move some rendering logic out of details-view-container

---

src/electron/platform/android/setup/state-machine/state-machine-action-callback.ts
src/electron/platform/android/setup/state-machine/state-machine-step.ts
src/electron/platform/android/setup/state-machine/state-machine-steps-factory.ts
src/electron/platform/android/setup/state-machine/state-machine-steps.ts
src/electron/platform/android/setup/state-machine/state-machine.ts
src/tests/unit/tests/electron/platform/android/setup/state-machine/state-machine.test.ts

Given a set of steps (states), the job of the state machine is to link a step to a set of actions. When an action is invoked on the state machine, the action is invoked for the current step. The step itself may fire a callback to transition to another step and the process repeats.
This implementation is designed to link specific Action<> invocations to the actions contained in the steps. In this way, a store which uses the state machine can forward action calls, and consistency with the standard actions mechanism can be maintained.

feat(android-setup): Add core state machine logic

---

src/DetailsView/components/left-nav/details-view-left-nav.scss
src/common/styles/colors.scss
src/common/styles/root-level-only/color-definitions.scss

Change the hover color for the reflow UI to a transparent gray so we have sufficient contrast with both the default white background and the blue blackground for the expanded links:

feat(nav-bar-functionality): change hover colors for reflow ui

---

src/injected/visualization/base-drawer.ts
src/injected/visualization/svg-drawer.ts
src/tests/unit/tests/injected/visualization/drawer.test.ts

A couple changes I looked into here:
1. Re-drawing more frequently on scroll/re-size (60fps).
2. Using throttle instead of manually creating/managing timeouts. Throttle effectively can handle that for us making this simpler and ensuring that we're not calling this method too frequently.
Notes: I'm very interested to see how this performs on other people's machines and hence added the second review required label. I think we can safely make the 2nd change but I'm open to increasing the throttle time for a less perf heavy task. In my experience, resizing manually did yield some noticeable lag however scrolling was indistinguishable. I also noticed some lag in resizing regardless of the visualization or not so ... 🤷 
Here's the difference:
Before:
After:
- [.] Addresses an existing issue: …

fix: use throttle instead of timeout for scroll/resize re-drawing

---

src/common/feature-flags.ts
src/tests/unit/tests/background/feature-flags.test.ts

Added a feature flag for the "needs review" feature.  The "Needs review" feature flag now appears in the (not publicly visible) list of feature flags. 
(Image of the "Preview Features" Pane, which now includes the "Needs review" feature flag at the bottom.)

feat: Add feature flag for "needs review" feature

---

src/common/fabric-icons.ts
src/electron/views/device-connect-view/components/android-setup/android-setup-prompt-layout.scss
src/electron/views/device-connect-view/components/android-setup/android-setup-prompt-layout.tsx
src/electron/views/device-connect-view/components/android-setup/default-android-setup-components.ts
src/electron/views/device-connect-view/components/android-setup/folder-picker.scss
src/electron/views/device-connect-view/components/android-setup/folder-picker.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-locate-adb-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/android-setup-prompt-layout.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/folder-picker.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-locate-adb-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/android-setup-prompt-layout.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/folder-picker.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-locate-adb-step.test.tsx

This PR adds in the UI layout for the `prompt-locate-adb`. It's focused on getting the UI to look right per the mock.
Out of scope until later PRs:
* Hooking up the "Browse" button to the OS file browser via `Electron.dialog"
* Hooking up buttons to their corresponding actions (deferring until #2806 merges with the action definitions)
To visually test the new UI, I temporarily updated `android-setup-step-container.tsx` L13 to `'prompt-locate-adb'`.
Known visual differences:
* Padding between logo and window title differs in mock; out of scope for this PR
* Link style uses our standard styling rather than the nonstandard styling suggested by the mock, per discussion with Fer
* With OK from Fer, folder icon in text field is on right instead of left, since that's what fluent's TextField …

feat(android-setup): create UI layout for prompt-locate-adb step

---

src/electron/views/device-connect-view/components/android-setup/android-setup-prompt-layout.scss
src/electron/views/device-connect-view/components/android-setup/android-setup-prompt-layout.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/android-setup-prompt-layout.test.tsx.snap

Per discussion in feature chat, we think the footer buttons don't actually belong in a footer landmark; this PR moves them out of their own separate landmark into the `<main>` element.
No visual change, verified reading in NVDA
- [n/a, no visual change] (UI changes only) Added screenshots/GIFs to description above

feat(android-setup): move android setup nav buttons into main landmark

---

src/electron/flux/action/android-setup-actions.ts
src/electron/flux/store/android-setup-store.ts
src/electron/flux/types/android-setup-state-machine-types.ts
src/electron/platform/android/setup/android-setup-state-machine-factory.ts
src/electron/platform/android/setup/android-setup-step-deps.ts
src/electron/platform/android/setup/android-setup-steps-factory.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/flux/store/android-setup-store.test.ts
src/tests/unit/tests/electron/platform/android/setup/android-setup-steps-factory.test.ts

The store now takes a factory which will build the state machine and call a provided callback (AndroidSetupStore.stepTransition) which updates the store data.
There is a factory function (createAndroidSetupSteps) which generates steps using dependencies.

feat(android-setup): Modify AndroidSetupStore to use the state machine as it's engine

---

src/electron/views/device-connect-view/components/android-setup/default-android-setup-components.ts
src/electron/views/device-connect-view/components/android-setup/prompt-connect-to-device-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-connect-to-device-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-connect-to-device-step.test.tsx

Add the "detect my device" dialog as called out in story 1724337. This is a very simple dialog that does nothing until the user presses a button or the link.
Screenshot (grey border is just background, not part of the dialog):

feat(android-setup): Add "detect my device" dialog

---

src/views/content/content.scss

Currently, our guidance pages have columns that do not reflow well. This PR updates those columns to stack when width is reduced.
In action:

feat(text-reflow): Reflow guidance pages columns

---

src/DetailsView/components/base-left-nav.tsx
src/DetailsView/components/left-nav/assessment-left-nav.tsx
src/DetailsView/components/left-nav/details-view-left-nav.tsx
src/DetailsView/components/left-nav/fast-pass-left-nav.tsx
src/DetailsView/components/left-nav/fluent-side-nav.tsx
src/DetailsView/components/left-nav/visualization-based-left-nav.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/base-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/fluent-side-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/base-left-nav.test.tsx
src/tests/unit/tests/DetailsView/components/fluent-side-nav.test.tsx
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/assessment-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/details-view-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/fast-pass-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/visualization-based-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/assessment-left-nav.test.tsx
src/tests/unit/tests/DetailsView/components/left-nav/details-view-left-nav.test.tsx
src/tests/unit/tests/DetailsView/components/left-nav/fast-pass-left-nav.test.tsx
src/tests/unit/tests/DetailsView/components/left-nav/visualization-based-left-nav.test.tsx

When user have side nav open and make the window wider, the panel will convert to the nav bar, and we will set the focus to the first focusable element in the nav.

feat(nav-bar-functionality): set focus back to the first focusable element in nav bar

---

src/DetailsView/components/left-nav/fluent-side-nav.scss

Change side-nav-container min-width from 200px to 250px to fit the text of all the requirements in the nav bar at 100% zoom.
Before
After

fix: change side nav container min width to 250px

---

src/electron/flux/action-creator/android-setup-action-creator.ts
src/electron/views/device-connect-view/components/android-setup/prompt-locate-adb-step.tsx
src/tests/unit/tests/electron/flux/action-creator/android-setup-action-creator.test.ts
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-locate-adb-step.test.tsx

Wires up the "Next" button in the `prompt-locate-adb` step's UI to invoke the `saveAdbPath` setup action using the current value of the folder picker.
Needed to wire up action creator to do this, so did so with simple pass-throughs for now; may need to update later if we need to coordinate actions with other stores/etc
No visual changes (since the state machine isn't yet doing anything with the action)

feat(android-setup): wire up prompt-locate-adb UI to setup actions

---

src/electron/views/device-connect-view/components/android-setup/default-android-setup-components.ts
src/electron/views/device-connect-view/components/android-setup/prompt-install-failed-step.scss
src/electron/views/device-connect-view/components/android-setup/prompt-install-failed-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-install-failed-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-install-failed-step.test.tsx

Add the dialog to display if the attempt to install the service to the device failed. 
Screenshot displaying an emulator:
Screenshot displaying a device:

feat(android-setup): Add prompt install failed step

---

src/electron/views/device-connect-view/components/android-setup/default-android-setup-components.ts
src/electron/views/device-connect-view/components/android-setup/prompt-grant-permissions-step.scss
src/electron/views/device-connect-view/components/android-setup/prompt-grant-permissions-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-grant-permissions-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-grant-permissions-step.test.tsx

This adds the dialog to display in the prompt-grant-permissions step
Screenshot displaying an emulator:
Screenshot displaying a device:

feat(android-setup): Add PromptGrantPermissionsStep

---

src/DetailsView/components/interactive-header.tsx
src/DetailsView/details-view-container.tsx
src/common/components/header.tsx
src/debug-tools/components/debug-tools-view.tsx
src/tests/unit/tests/DetailsView/__snapshots__/details-view-container.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/interactive-header.test.tsx.snap
src/tests/unit/tests/DetailsView/details-view-container.test.tsx
src/tests/unit/tests/common/components/__snapshots__/header.test.tsx.snap
src/tests/unit/tests/common/components/header.test.tsx
src/tests/unit/tests/debug-tools/components/__snapshots__/debug-tools-view.test.tsx.snap
src/tests/unit/tests/debug-tools/components/debug-tools-view.test.tsx

Hide the "Accessibility Insights for Web" header text when the window is less than 600 px wide

feat(nav-bar-functionality): Hide header text in narrow mode

---

src/electron/views/device-connect-view/components/android-setup/device-description.scss
src/electron/views/device-connect-view/components/android-setup/device-description.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/device-description.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/device-description.test.tsx

The DeviceDescription control doesn't yet know how to display the current application. This change adds this ability. The change intentionally leaves the existing behavior completely unchanged.
Screenshot: First row is device, without and with application. Second row is emulator, without and with application.
Comment: The lighter color in specified in the figma as an opacity, so that's how I've implemented it here. The numbers are slightly different from the figma, based on tuning with eyeball 1.0.

feat(android-setup): Add support to display the current application

---

deploy/Gruntfile.js

As discussed offline: we currently fail builds when the extension is deployed and it is pending review. Since we want to easily be able to ignore those kind of failures, we will now mark these as partially successful.
Please review the latest builds/releases for the playground extension in ADO to validate.

chore: treat 'already updating extension' failures as partially successful

---

src/electron/flux/store/android-setup-store.ts
src/electron/flux/types/android-setup-state-machine-types.ts
src/electron/platform/android/setup/android-setup-deps.ts
src/electron/platform/android/setup/android-setup-state-machine-factory.ts
src/electron/platform/android/setup/android-setup-step-deps.ts
src/electron/platform/android/setup/android-setup-steps-configs.ts
src/electron/platform/android/setup/steps/detect.adb.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/flux/store/android-setup-store.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/detect-adb.test.ts

This change defines all the android setup dependencies. This will allow us to parallelize the work of createing the remaining setup steps in the state machine with the code for calling ADB, installation, device detection, etc.
- Renamed the function detectAdb to hasAdbPath -- better represents the client's perspective
- Removed the stepTransition function from AndroidSetupDeps because it does not need to be exposed to the calling code which creates the deps
- Created an AndroidSetupStoreCallbacks type because we will soon need to update store data from the steps themselves

feat(android-setup): Add all functions to AndroidSetupDeps

---

src/electron/platform/android/appium-adb-creator.ts
src/electron/platform/android/appium-service-configurator-factory.ts
src/electron/platform/android/live-appium-adb-creator.ts
src/tests/unit/tests/electron/platform/android/appium-service-configurator-factory.test.ts

As discussed in today's engineering discussion, the current approach of constructing the AppiumServiceConfiguratorFactory has some downsides, especially if we want to decorate the call to `ADB.createADB` in some way. This change enables decoration and will bring the initializer more into line with what we do elsewhere. The initializer code will have no direct references to ADB, and the changes will look something like:
```
import AndroidServiceConfiguratorFactory from './android-service-configurator-factory';
import AppiumServiceConfiguratorFactory from './appium-service-configurator-factory';
import LiveAppiumAdbCreator from './live-appium-adb-creator';
// existing code
this.androidServiceConfiguratorFactory = new AppiumServiceConfiguratorFactory (
new LiveAppiumAdbCreator()
);
```
Unit …

(chore): Refactor injection of AppiumServiceConfiguratorFactory

---

src/DetailsView/components/interactive-header.tsx
src/DetailsView/components/no-content-available/no-content-available-view.tsx
src/debug-tools/components/debug-tools-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/interactive-header.test.tsx.snap
src/tests/unit/tests/DetailsView/components/no-content-available/__snapshots__/no-content-available-view.test.tsx.snap
src/tests/unit/tests/debug-tools/components/__snapshots__/debug-tools-view.test.tsx.snap
src/tests/unit/tests/views/page/__snapshots__/page.test.tsx.snap
src/views/page/page.tsx

Use NarrowModeDetector wherever we use the Header component, including content pages and the NoContentAvailable view and fix a few bugs with adding narrow mode detection to the header in other places.

feat(nav-bar-functionality): Use NarrowModeDetector for all instances of Headers

---

src/content/test/landmarks/landmark-table.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
src/views/content/content.scss

The table for landmark guidance was not properly reflowing. This PR fixes that.

feat(text-reflow): Landmark guidance table reflow

---

src/electron/views/device-connect-view/components/android-setup/android-setup-types.ts
src/electron/views/device-connect-view/components/android-setup/default-android-setup-components.ts
src/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.scss
src/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.tsx
src/electron/views/renderer-initializer.ts
src/tests/unit/common/android-setup-step-props-builder.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/android-setup-step-container.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/detect-devices-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/detect-service-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/installing-service-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-connected-start-testing-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.test.tsx

Created the dialog for the prompt-connected-start-testing step, with Cancel and Start Testing functionality. Have the "rescan devices" button, per the spec, but the functionality of the onClick will be updated in later feature work (per comment in `prompt-choose-device-step.tsx` line 26
Image of the UI

feat(android-setup): prompt-connected-start-testing step UI

---

src/electron/flux/store/android-setup-store.ts
src/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.scss
src/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-choose-device-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.test.tsx

This PR adds the device-description component and selection behavior to the prompt-choose-device screen. Linking the next button's enabled/disabled behavior to the selected state required overwriting the selection model of DetailsList. 
suggestions appreciated on / potential upcoming PR improvements:
- whether the Selection should be handled differently (would a separately tested and injected selection-provider make more sense?)
- when the dialog is full screen, the max-height still affects the details list. It would be nice to avoid this
- if the device description text is too long, text ellipses might be nice

feat(android-setup): add selection & device descriptions to prompt-choose-device dialog 

---

src/electron/platform/android/android-service-configurator.ts
src/electron/platform/android/appium-service-configurator.ts
src/tests/unit/tests/electron/platform/android/appium-service-configurator.test.ts

The unified client will configure the TCP port forwarding during setup, and it was called out that we ought to remove that port forwarding when the client exits. This change adds the appropriate wrapper around appium-adb.

feat(android-setup): Add support to remove port forwarding

---

src/DetailsView/components/left-nav/details-view-left-nav.scss

Currently, the thick blue line on the left border of the selected nav link is missing when the nav bar is in a panel. This will add it back in:

feat(nav-bar-functionality): add left border to nav in panel

---

src/electron/flux/types/android-setup-store-data.ts
src/electron/flux/types/device-metadata.ts
src/electron/views/device-connect-view/components/android-setup/device-description.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-choose-device-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-connected-start-testing-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-grant-permissions-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-install-failed-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-install-service-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/device-description.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-grant-permissions-step.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-install-failed-step.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-install-service-step.test.tsx

This PR should have no functional behavior differences. The DeviceMetadata class is removed and replaced with DeviceInfo so we can consolidate. The currentApplication field has been moved out into a prop for now. Because the current application info will come from a different place (the /config API call) than the other ADB information, it makes sense to separate things out. This also allows us to use the device ID in the UI, which will be helpful for sending the appropriate action back to the store.

feat(android-setup): replace DeviceMetadata with DeviceInfo

---

src/electron/platform/android/setup/android-setup-steps-configs.ts
src/electron/platform/android/setup/steps/detect-permissions.ts
src/electron/platform/android/setup/steps/detect-service.ts
src/electron/platform/android/setup/steps/installing-service.ts
src/electron/platform/android/setup/steps/prompt-connected-start-testing.ts
src/electron/platform/android/setup/steps/prompt-grant-permissions.ts
src/electron/platform/android/setup/steps/prompt-install-service.ts
src/tests/unit/tests/electron/platform/android/setup/steps/detect-permissions.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/detect-service.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/installing-service.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/prompt-connected-start-testing.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/prompt-grant-permissions.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/prompt-install-service.test.ts

Adding
- detect-devices
- detect-permissions
- detect-service
- installing-service
- prompt-connect-to-device
- prompt-connected-start-testing
-prompt-grant-permissions
- prompt-install-service
Note: The steps 'prompt-install-service' and 'prompt-install-failed' both use the same config -- promptInstallService -- because they have the exact same behavior. The UI can still be different because the step id is different.
Note: Still need to add the config for prompt-choose-device'.

feat(android-setup): Add most of the remaining state machine steps

---

src/DetailsView/components/left-nav/details-view-left-nav.scss
src/DetailsView/components/left-nav/left-nav-link-builder.tsx
src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx

Render expandable links in the left nav as buttons instead of anchor links. This will fix an issue where pressing spacebar while an expandable link is in focus scrolls the nav instead of expanding the link.

feat(nav-bar-functionality): render expandable nav links as buttons

---

src/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-choose-device-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.test.tsx

This PR links button invocations to their associated actions for the prompt-choose-device step.

feat(android-setup): add actions to prompt-choose-device-step

---

src/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.test.tsx

This PR adds actions for the prompt-connected-start-testing step. This is part of a series of PRs that links up actions for each android setup step.

feat(android-setup): add actions to prompt-connected-start-testing-step

---

src/electron/views/device-connect-view/components/android-setup/prompt-connect-to-device-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-connect-to-device-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-connect-to-device-step.test.tsx

This PR links button invocations to their associated actions for the prompt-connect-to-device step.

feat(android-setup): add actions to prompt-connect-to-device-step

---

src/debug-tools/components/debug-tools-view.tsx
src/tests/unit/tests/debug-tools/components/__snapshots__/debug-tools-view.test.tsx.snap
src/tests/unit/tests/debug-tools/components/debug-tools-view.test.tsx

I notice the debug tools view got broken:
```
Uncaught TypeError: Cannot read property 'reflowUI' of undefined
at DebugToolsView (webpack-internal:///./src/debug-tools/components/debug-tools-view.tsx:8)
at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14803)
at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17482)
at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:18596)
at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:188)
at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:237)
at invokeGuardedCallback …
```

tools: fix broken debug tools view

---

src/electron/views/device-connect-view/components/android-setup/prompt-grant-permissions-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-grant-permissions-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-grant-permissions-step.test.tsx

One of several PRs to link button selection to actions in the android-setup steps.

feat(android-setup): add actions to prompt-grant-permissions-step

---

src/electron/views/device-connect-view/components/android-setup/prompt-install-failed-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-install-failed-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-install-failed-step.test.tsx

One of several PRs linking button selection to actions

feat(android-setup): add actions to prompt-install-failed-step

---

src/electron/views/device-connect-view/components/android-setup/prompt-install-service-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-install-service-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-install-service-step.test.tsx

Linking up actions to button invoking in install-service dialog step

feat(android-setup): add actions to install-service step

---

src/electron/flux/action-creator/android-setup-action-creator.ts
src/electron/flux/action/android-setup-actions.ts
src/electron/flux/store/android-setup-store.ts
src/electron/flux/types/android-setup-state-machine-types.ts
src/electron/flux/types/android-setup-store-data.ts
src/electron/platform/android/setup/steps/detect-devices.ts
src/electron/platform/android/setup/steps/prompt-choose-device.ts
src/tests/unit/tests/electron/flux/action-creator/android-setup-action-creator.test.ts
src/tests/unit/tests/electron/flux/store/android-setup-store.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/detect-devices.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/prompt-choose-device.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/prompt-connected-start-testing.test.ts

- Add functions to set the current device and available devices in the Android setup store
- Modify setSelectionDevice action to take a DeviceInfo structure
- Update detect-devices step to set available devices in store

feat(android-setup): Add prompt-choose-device state machine step

---

src/DetailsView/components/left-nav/details-view-left-nav.scss
src/DetailsView/components/requirement-link.scss
src/DetailsView/components/requirement-link.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-link.test.tsx.snap

1. removes usages of class we don't control from office fabric in the left nav (ms-compositel link or something)
2. refactors requirement-link styles to separate file. button-flex-container is a class that is being used in a few places and I wanted to ensure that future changes (for status-icon) will not be impacted because of this.
After is left and before is right (sorry):

refactor: clean up css in left nav + requirement link scss

---

src/electron/views/device-connect-view/components/android-setup/android-setup-types.ts
src/electron/views/device-connect-view/components/android-setup/default-android-setup-components.ts
src/electron/views/device-connect-view/components/android-setup/detect-permissions-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/detect-permissions-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/android-setup-step-container.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/detect-permissions-step.test.tsx

This PR adds a spinner UI component for the state machine step 'detect-permissions', which was missing. We don't expect to stay on steps like these for long, but are adding spinner UIs for now. This allows the workflow to continue to the start-testing dialog.
out of scope - it might make sense to further consolidate the spinner dialogs into a single component so we don't need to write new classes / tests when the only change is the spinner label. Will revisit in a separate PR if spinners stay

feat(android-setup): add android setup UI component for detect-permissions

---

src/electron/views/device-connect-view/components/android-setup/detect-devices-step.tsx
src/electron/views/device-connect-view/components/android-setup/detect-permissions-step.tsx
src/electron/views/device-connect-view/components/android-setup/detect-service-step.tsx
src/electron/views/device-connect-view/components/android-setup/installing-service-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/detect-devices-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/detect-permissions-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/detect-service-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/installing-service-step.test.tsx.snap

Several of the steps that are based on `AndroidSetupSpinnerStep` were wrapping it in a `<main>` element, but it already is based on `AndroidSetupStepLayout` which provides a `<main>` element. This removes the extra landmark.
No visual change.

fix(android-setup): remove extra main elements in AndroidSetupSpinnerStep UIs

---

src/electron/flux/store/device-store.ts
src/electron/platform/android/appium-service-configurator.ts

We currently support two parallel experiences for setting up Android devices. The first is the original 'manual-port-selection' experience in master today. The second is an in-progress automatic setup process that assumes the port 62442 for now. Our UI is shared amongst both experiences and uses the port number set in the device-store. Until we deprecate the old experience / remove the old store, we need a way to use 62442 in cases where the auto-setup feature flag is on. Out of the options:
- update the device-store from an adb step
- consume different ports in the UI (deviceStoreData.port referenced in >= 3 places)
- 'update the store data' in a higher UI component when the new experience is on
- set the default value in the store data to match
This PR uses the final approach for now.

feat(android-setup): set default device connect port to 62442 

---

src/electron/platform/android/setup/android-setup-step-id.ts
src/electron/platform/android/setup/android-setup-steps-configs.ts
src/electron/views/device-connect-view/components/android-setup/configuring-port-forwarding-step.tsx
src/electron/views/device-connect-view/components/android-setup/default-android-setup-components.ts
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/configuring-port-forwarding-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/configuring-port-forwarding-step.test.tsx

Adds a new loading spinner screen UI for the step where we configure port forwarding in ADB.

feat(android-setup): add UI for configuring-port-forwarding step

---

src/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-connected-start-testing-step.test.tsx.snap

Fixes this warning in the dev console when hitting the prompt-connected-start-testing-step:
`warn.js:13 The Button component has been deprecated. Use specific variants instead. (PrimaryButton, DefaultButton, IconButton, ActionButton, etc.)`

chore: address deprecated button warning in unified dev console

---

src/electron/platform/android/setup/android-setup-step-id.ts
src/electron/platform/android/setup/android-setup-steps-configs.ts
src/electron/views/device-connect-view/components/android-setup/default-android-setup-components.ts
src/electron/views/device-connect-view/components/android-setup/prompt-configuring-port-forwarding-failed-step.scss
src/electron/views/device-connect-view/components/android-setup/prompt-configuring-port-forwarding-failed-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-configuring-port-forwarding-failed-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-configuring-port-forwarding-failed-step.test.tsx

Adds a new UI for when setting up port forwarding fails based on the similar UI for when installing the service fails.
screenshot of proposed UI for error screen (in actual use there will be a device name to the right of the icon, it's missing here because I skipped directly to the new step for testing):

feat(android-setup): UI for prompt-configuring-port-forwarding-failed-step

---

src/electron/platform/android/setup/steps/detect-adb.ts
src/tests/unit/tests/electron/platform/android/setup/steps/detect-adb.test.ts

Our "golden path" is when a user has exactly 1 device detected, and we're able to install and configure everything without any user input. In the current code, though, once we detect ADB, we go to prompt-connect-to-device, which interrupts that flow. This simply changes the step that comes after detect-adb. Once we detect devices, detect-devices will route as follows:
No devices found => prompt-connect-to-device
1 device found => detect-service
> 1 device found => prompt-choose-device
I tested this (in combination with #2908), and the golden path is just that--if the service is already installed and has permissions, you start the app, see the spinner for a few seconds, and then you're ready to test.  …

feat(android-setup): Scan for devices without prompting (golden path)

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/details-view-body.scss
src/DetailsView/details-view-body.tsx
src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap

Setting the height to 100% for the containers allow them to take the entire space necessary for the background to extend.
Before:
After:

fix: background color should extend for entire right panel

---

src/ad-hoc-visualizations/color/visualization.tsx
src/ad-hoc-visualizations/headings/visualization.tsx
src/ad-hoc-visualizations/issues/visualization.tsx
src/ad-hoc-visualizations/landmarks/visualization.tsx
src/ad-hoc-visualizations/tab-stops/visualization.tsx
src/assessments/assessment-builder.tsx
src/common/configs/assessment-visualization-configuration.ts
src/tests/unit/tests/assessments/assessment-builder.test.tsx

1. Moves inline rule analyzer configurations to private variables making them easier to parse.
2. Removes result processor at visualization configuration level as it is not used.
Validated by doing a quick pass through assessment tests and visualizations.

chore: clean up visualization configurations

---

src/electron/flux/store/android-setup-store.ts
src/electron/flux/types/android-setup-state-machine-types.ts
src/electron/flux/types/android-setup-store-data.ts
src/electron/platform/android/setup/android-setup-deps.ts
src/electron/platform/android/setup/live-android-setup-deps.ts
src/electron/platform/android/setup/steps/configuring-port-forwarding.ts
src/electron/platform/android/setup/steps/detect-permissions.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/flux/store/android-setup-store.test.ts
src/tests/unit/tests/electron/platform/android/setup/live-android-setup-deps.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/configuring-port-forwarding.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/detect-permissions.test.ts

The app name is required for the start testing screen, and it can't be set until after the permissions have been granted. It also can't be set in the onEnter function for the start testing step because the onEnter method is asynchronous, and the UI will therefore be visible possibly before the app name is set.

feat(android-setup): Add code to set the app name from the device in the setup store

---

src/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-connected-start-testing-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.test.tsx

The "connected" dialog is supposed to display the current application, but the data wasn't being initialized from the store. This adds the data from the store so that it gets displayed in the UI.
UI before the change (no application name):
UI after the change (has application name):

fix(android-setup): Display the current application in the "connected" dialog

---

.prettierignore
copyright-header.config.json

I often use the branching tools in Visual Studio, but fastpass complains because it tries to scan the files in the .vs folder. This change simply excludes the .vs folder from prettier and linting checks, so that fastpass and Visual Studio can play nicely together.

(chore): Exclude .vs folder from fastpass scans

---

package.json

The addition of `yarn null:check` to `yarn fastpass` means that fastpass now relies on `yarn scss:build` having happened first; since that step is relatively quick to execute anyway, this PR adds it to `yarn fastpass` to avoid users having to remember to do it manually.

chore: add scss:build step to yarn fastpass

---

src/electron/platform/android/setup/android-setup-steps-configs.ts
src/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.test.tsx

The cancel buttons were connected, but the step they connected to was never enabled. The UX for that step was only displaying test data instead of real data. This PR enables the step with real data. The test for it could potentially be refactored to use the builder, if we want. 
Screenshot using my tethered device:

fix(android-setup): Enable "choose device" dialog on cancel, use real data

---

src/electron/platform/android/setup/steps/prompt-connected-start-testing.ts
src/tests/unit/tests/electron/platform/android/setup/steps/prompt-connected-start-testing.test.ts

The cancel button in the "start testing" dialog wasn't hooked up inside the step. This hooks it up, following the same pattern of #2929 

fix(android-setup): Connect cancel button in "start testing" step

---

src/electron/platform/android/setup/android-setup-steps-configs.ts
src/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.test.tsx

The "choose device" dialog had some issues:
1. Due to a mapping error, any steps entering the `prompt-choose-device` state pointed to the wrong dialog (I set this incorrectly earlier today).
2. The dialog was calling the `next` action, when the step was expecting the `setSelectedDevice` action. 
Between these issues, the user couldn't choose between multiple connected devices.
Fixes were updating the dialog mapping and ensuring that we called `setSelectedDevice` correctly after the user selected a dialog. Tested by running with multiple attached devices and ensuring that the E2E workflow works as expected.

fix(android-setup): Enable selection from multiple devices

---

src/electron/views/device-connect-view/components/android-setup/android-setup-step-layout.scss
src/electron/views/device-connect-view/components/android-setup/prompt-configuring-port-forwarding-failed-step.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-connect-to-device-step.scss
src/electron/views/device-connect-view/components/android-setup/prompt-connect-to-device-step.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-grant-permissions-step.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-install-failed-step.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-install-service-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-configuring-port-forwarding-failed-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-connect-to-device-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-connected-start-testing-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-grant-permissions-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-install-failed-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-install-service-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.test.tsx

This PR adjusts the padding in the prompt-connected-start-testing step to match the figma.
It involves updates to a bunch of other components because previously, everything used a 24px margin between step layout header and content, but this particular fix requires a 16px margin. Oops.
I considered pushing back and just accepting a 24px margin, but it wasn't *that* big a deal to have it match the figma, and it does look a little nicer this way imo.
Verified no visual change on any other steps. Before and after of the impacted prompt-connected-start-testing step:
**Before**
**After**

fix(android-setup): fix padding in prompt-connected-start-testing

---

src/common/extension-telemetry-events.ts
tsconfig.strictNullChecks.json

Refactors the import from action-payloads so that extension-telemetry-events no longer fails the strict-null-check step.

refactor: add extension-telemetry-events to strict null checks config

---

src/electron/platform/android/setup/steps/detect-devices.ts
src/tests/unit/tests/electron/platform/android/setup/steps/detect-devices.test.ts

`getDevices` can fail, eg, if the device falls asleep or is disconnected during the call. If that happens, we don't want the step to spin forever; it should make *some* state transition. I think the ideal would be some sort of generic error step, but for now, the best one available is probably the one with the link about device connection troubleshooting, prompt-connect-to-device (same as the no-devices-connected case)

fix(android-setup): avoid detect-devices spinning forever on getDevices failure

---

src/electron/views/device-connect-view/components/android-setup/folder-picker.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/folder-picker.test.tsx.snap

Fluent UI has its own `ariaLabel` prop for `TextField`s, but not its own `aria-describedby`, so the casing has to be different for applying them (oops). React does provide an `aria-label` (which is why this wasn't a compile error), but Fluent ignores it in favor of its own property.
NVDA now reads the control (when empty) as "Enter a path  edit  Select the folder containing adb. We'll use it to connect to your device.  Enter a path...  blank" - that is, it repeats the label and placeholder text. Would like confirmation from @ferBonnin / @RobGallo on whether this feels reasonable or if it's too redundant

fix(android-setup): fix aria-label on adb path text field

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/assessment-instance-selected-button.scss
src/DetailsView/components/test-status-choice-group.scss

before: the font color and icon color inside the selected row are all black, which is very hard to see inside a purple background. 
after:

feat(trusted-tester-bugs): fix instance table content color on focus

---

src/DetailsView/components/details-view-content.tsx
src/DetailsView/components/interactive-header.tsx
src/DetailsView/components/left-nav/fluent-side-nav.tsx
src/DetailsView/components/narrow-mode-detector.tsx
src/DetailsView/details-view-body.tsx
src/DetailsView/details-view-container.tsx
src/common/components/header.tsx
src/debug-tools/components/debug-tools-view.tsx
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/fluent-side-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/interactive-header.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/narrow-mode-detector.test.tsx.snap
src/tests/unit/tests/DetailsView/components/fluent-side-nav.test.tsx
src/tests/unit/tests/DetailsView/components/interactive-header.test.tsx
src/tests/unit/tests/DetailsView/components/narrow-mode-detector.test.tsx
src/tests/unit/tests/DetailsView/details-view-content.test.tsx
src/tests/unit/tests/common/components/header.test.tsx

Refactor NarrowModeDetector to report status with an object instead of a single boolean stating whether or not we are in narrow mode. This will enable us to detect different window widths which will affect different components.

feat(reflow-command-bar): Refactor NarrowModeDetector

---

src/electron/views/device-connect-view/components/android-setup/android-setup-step-layout.scss
src/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.scss
src/electron/views/device-connect-view/components/device-connect-body.scss
src/electron/views/device-connect-view/components/device-connect-view-container.scss
src/electron/views/device-connect-view/components/device-connect-view-container.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-view-container.test.tsx.snap

This PR implements the scrollbar behavior from the figma (also addresses a related bug bash onenote issue). Specifically, it:
* prevents the "choose device" list from showing its own scrollbar, in favor of a whole-dialog one
* fixes bottom buttons getting cut off when scrollbar is visible
* fixes outer scrollbar not being interactable (because it was rendering for a `-webkit-app-region: drag` component)
This PR is impacted by an issue where, in general, if a component inside a scrollable container is set to `-webkit-app-region: drag`, the scrollable container won't respond to mousewheel/middle-mouse scrolling when the mouse is over that inner component (instead, the window itself intercepts those events for drag handling). That means we had to choose whether to make the static background …

fix(android-setup): fix scroll behavior with many devices/small size/high text zoom

---

src/electron/views/device-connect-view/components/android-setup/device-description.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/device-description.test.tsx.snap

Adds `role=img` to the icon-font images we use to distinguish devices vs emulators, per the "Images > Image function" requirement's guidance.
No visual change. NVDA previously announced a physical device named "foo" as "device foo", and now announces "graphic device *pause* foo" instead.

fix(android-setup): use img role for meaningful icon-font images in device descriptors

---

src/DetailsView/components/switcher.scss

This is an issue from OF: there is no diffference between a focused item and a non-focused item in the dropdown component. 
As a workaround I added a border to the focused item under windows high contrast mode.
before:
after:

feat(trusted-tester-bugs): Add focus indicator to selected dropdown menu item

---

src/DetailsView/components/details-view-command-bar.scss
src/DetailsView/components/details-view-command-bar.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap

Makes sure the target page is shortened using ellipsis when there is not enough room.

feat(reflow-command-bar): ellipsis for target page link

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/target-change-dialog.scss
src/DetailsView/components/target-change-dialog.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/target-change-dialog.test.tsx.snap

Just cleaning up some css from details view for this dialog.
Above gif shows unchanged css.

chore: cleaning up css for target page changed dialog

---

src/DetailsView/components/command-bar-buttons-menu.tsx
src/common/fabric-icons.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/command-bar-buttons-menu.test.tsx.snap
src/tests/unit/tests/DetailsView/components/command-bar-buttons-menu.test.tsx

Create component for ... button (not currently used) with menu that currently renders the command bar buttons as-is:

feat(command-bar-reflow): create CommandBarButtonsMenu component

---

src/ad-hoc-visualizations/needs-review/visualization.tsx
src/popup/components/ad-hoc-tools-panel.tsx
src/tests/unit/tests/popup/components/__snapshots__/ad-hoc-tools-panel.test.tsx.snap
src/tests/unit/tests/popup/components/ad-hoc-tools-panel.test.tsx

Adding subtitle to Needs review page in details view.  
Also, fixing divider issue in ad hoc tools panel (previously, second to last divider was missing when needs review was enabled).  Now dividers are generated as expected irrespective of whether there are five or six items in the panel.

feat(needs-review): Adding subtitle, fixing dividers in ad hoc panel

---

src/DetailsView/components/command-bar-buttons-menu.scss
src/DetailsView/components/command-bar-buttons-menu.tsx
src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/start-over-component-factory.tsx
src/DetailsView/components/start-over-dropdown.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/command-bar-buttons-menu.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-component-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-dropdown.test.tsx.snap
src/tests/unit/tests/DetailsView/components/command-bar-buttons-menu.test.tsx
src/tests/unit/tests/DetailsView/components/start-over-component-factory.test.tsx
src/tests/unit/tests/DetailsView/components/start-over-dropdown.test.tsx

- Add a dropdownDirection property to StartOverDropdown so we can render the dropdown either below or to the left of the button
- Render below if the button is in the command bar
- Render to the left if the button is in the ... menu
- Fix some styling issues in the command bar ... menu
CommandBarMenuButton is still not in use yet, but here's a demonstration of the component with the existing command buttons for comparison:

feat(command-bar-reflow): Render start over dropdown on the left in ... menu

---

src/electron/views/device-connect-view/components/android-setup/android-setup-step-layout.tsx
src/tests/electron/common/view-controllers/app-controller.ts
src/tests/electron/tests/automatic-android-setup.test.ts
src/tests/electron/tests/device-connection-dialog.test.ts
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/android-setup-step-layout.test.tsx.snap

This is a placeholder e2e test that has the feature flag on for adb. One approach we can follow is to add new e2e tests here before we turn the feature flag off entirely. The test assumes that the app will get to prompt-locate-adb or prompt-connect-to-device, which are reasonable assumptions for a dev machine without an emulator running. This assumption/test can be removed once we have more of the adb mock in.

feat(android-setup): placeholder e2e test with adb feature flag on

---

src/DetailsView/components/command-bar-buttons-menu.scss
src/DetailsView/components/command-bar-buttons-menu.tsx
src/DetailsView/components/details-view-command-bar.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/command-bar-buttons-menu.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap
src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx

At 960px, hide the command bar buttons and show the "..." menu button instead

feat(command-bar-reflow): Collapse command bar at 960px

---

src/electron/views/device-connect-view/components/android-setup/android-setup-step-container.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/android-setup-step-container.test.tsx.snap

In preparation for e2e tests it would be helpful to know what dialog is visible. This adds automation ids around the android setup content. I originally added individual ids to each component leveraging AndroidSetupStepLayout as a new prop but this seemed simpler. Once this PR is in e2e tests can use the id to wait for a particular dialog and then target elements using native tag selectors and/or explicit ids depending on what the test writer prefers.

feat(android-setup): add automation ids around android content

---

src/DetailsView/components/assessment-view.scss

The issue was that there is no focus inicator on the focused req link. This PR add a outline on the focused link.
before: 
after:

feat(trusted-tester-bugs): Add outline to requirement link on focus

---

src/DetailsView/Styles/detailsview.scss

Fix the issue: when using arrow key to navigate inside nav panel, there is no focus indicator.
before:
after:

feat(trusted-tester-bugs): Add outline on focused test link

---

src/background/browser-message-broadcaster-factory.ts
src/background/extension-details-view-controller.ts
src/common/message.ts
tsconfig.strictNullChecks.json

__browser-message-broadcaster-factory.ts__
Since it does seem valid that tab.id may be null, simply add a null check guard around the code which uses it.
__interpreter.ts __
The change to message.ts fixes a possible null assignment in interpreter.ts on line 18.

Chore: Add null checks

---

src/electron/platform/android/setup/steps/prompt-connected-start-testing.ts
src/tests/unit/tests/electron/platform/android/setup/steps/prompt-connected-start-testing.test.ts

When the user clicks "Rescan" in the "start testing" dialog, the current code goes all the way back to detect-adb, which forces us to create a new ADB object, etc. The correct action is to go back to the detect-devices step and to keep using the existing ADB object.

fix(android-setup): Rescan should use the existing ADB, not make a new one

---

src/electron/platform/android/adb-wrapper.ts
src/electron/platform/android/appium-adb-wrapper.ts
src/electron/platform/android/setup/android-service-configurator.ts
src/electron/platform/android/setup/port-cleaning-service-configurator.ts
src/tests/unit/tests/electron/platform/android/appium-adb-wrapper.test.ts
src/tests/unit/tests/electron/platform/android/setup/android-service-configurator.test.ts
src/tests/unit/tests/electron/platform/android/setup/port-cleaning-service-configurator.test.ts

The `SreviceConfigurator.listForwardedPorts` method was recently added as an attempt to fix a timing issue. The actual issue was fixed (and the call to this method removed) in #3005, so this code adds no value and should be removed. 

chore(android-setup): Remove unneeded API: listForwardedPorts

---

src/tests/miscellaneous/mock-adb/app/bin.js
src/tests/miscellaneous/mock-adb/app/port-forward-server.js
src/tests/miscellaneous/mock-service-for-android/mock-service.js

@karanbirsingh noted an issue with mock-adb where tests were getting confused by `adb forward` returning before the test server it initializes was fully set up and listening.
This PR addresses that by adding an IPC "ready" message that the test server process sends after express.js is initialized and setting up `adb forward`'s handler to wait for that message before it returns.

test(android-setup): fix mock-adb forward exiting before server is set up

---

src/tests/miscellaneous/mock-adb/app/bin.js
src/tests/miscellaneous/mock-adb/common-adb-configs.js
src/tests/miscellaneous/mock-adb/setup-mock-adb.d.ts

I wanted to get screenshots of loading spinners in the new android setup flow for filing a bug, so I added a `slow-single-device` config to make that easier. This PR enables:
* `yarn mock-adb slow-single-device`: same as `single-device`, but every adb command is delayed by 5 seconds
* `yarn mock-adb multiple-devices`: fakes having 3 devices (2 physical, 1 emulator) instead of just 1

chore: add multiple-devices and slow-single-device mock-adb configs

---

README.md

The APK is bundled with the application now so we can remove this sentence.

docs: remove old APK info from readme

---

tools/strict-null-checks/find.js

This makes it easier to copy file paths directly into tsconfig.strictNullChecks.json.
- Remove the '- [ ]' prefix
- Remove '`' chars from output
- add 'src/' to the relative path to match the addition of '/src' to the search path earlier in the code
- Add commas at the end of lines for json formatting
- Remove the suffix with the dependency count (I only saw the dependency count ever be 0)

Chore: Change output format for tools\strict-null-checks\find.js

---

src/DetailsView/components/command-bar-buttons-menu.scss
src/DetailsView/components/command-bar-buttons-menu.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/command-bar-buttons-menu.test.tsx.snap
src/tests/unit/tests/DetailsView/components/command-bar-buttons-menu.test.tsx

- Simplify CommandBarButtonsMenu by only rendering the "..." button without using an OverflowSet
- NVDA now reads "More items submenu" instead of "More items submenu 1 of 1"
- Shorten the menu to remove white space to the right of the buttons
Before:
After:

feat(command-bar-reflow): Simplify CommandBarButtonsMenu

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/export-dialog.scss
src/DetailsView/components/target-change-dialog.scss

gif of behavior:
Before and After of the target page changed dialog in assessment:

feat(command-bar-reflow): dialogs resizing when zoomed in

---

package.json
tools/strict-null-checks/eligible-file-finder.js
tools/strict-null-checks/progress.js

This implements a new script that generates a progress message for use with our standup dashboard. `yarn null:progress` emits stdout like this:
```markdown
**29%** complete (**387**/1328 non-test files)
*Contribute at [#2869](https://github.com/microsoft/accessibility-insights-web/issues/2869). Last update: Mon Jul 06 2020*
```
...which renders in the dashboard widget like this:

chore(null): add yarn null:progress

---

src/DetailsView/components/left-nav/details-view-left-nav.scss
src/common/styles/colors.scss
src/common/styles/root-level-only/color-definitions.scss

Fixes #2914 color contrast issues in high contrast mode.
- Expanding a test group in high contrast mode does not change the background color of the test group (same as in Production Version 2.18.2)
- Hovering a selected test/requirement does not change the background color in both regular and high contrast modes (same as in Production Version 2.18.2)
- Selected test/requirement in high contrast mode is the same color as in Production Version 2.18.2 for both FastPass and Assessment
Gifs of expanding, selecting, and hovering tests and requirements in regular and high contrast modes
Gifs of selecting and hovering FastPass tests in regular and high contrast modes
- [n/a] Verified code coverage for the changes made. Check …

feat(command-bar-reflow): navigation bar colors in high contrast mode

---

src/reports/components/outcome-summary-bar.scss
src/reports/components/outcome-summary-bar.tsx
src/tests/unit/tests/reports/components/__snapshots__/outcome-summary-bar.test.tsx.snap
src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap

This will fix some inconsistent margins between sections and rounded corners on the wrong side in the outcome summary bar:

fix: clean up outcome summary bar styles

---

src/DetailsView/components/command-bar-buttons-menu.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/command-bar-buttons-menu.test.tsx.snap
src/tests/unit/tests/DetailsView/components/command-bar-buttons-menu.test.tsx

The '...' menu should be treated as a menu since the items inside need to be menuitems. This does that for both.

feat(command-bar-reflow): fix a11y issue for the '...' dropdown

---

src/tests/unit/tests/views/content/__snapshots__/content-panel-button.test.tsx.snap
src/views/content/content-panel-button.tsx

In the reflow UI, the content button has no visible text label like it does in the old UI, so it needs an aria-Label

fix: add ariaLabel for content button

---

src/DetailsView/components/getting-started-view.tsx
src/DetailsView/components/next-requirement-button.tsx
src/DetailsView/components/reflow-assessment-view.tsx
src/DetailsView/components/requirement-view.scss
src/DetailsView/components/requirement-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/getting-started-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/next-requirement-button.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/reflow-assessment-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/getting-started-view.test.tsx
src/tests/unit/tests/DetailsView/components/next-requirement-button.test.tsx
src/tests/unit/tests/DetailsView/components/reflow-assessment-view.test.tsx
src/tests/unit/tests/DetailsView/components/requirement-view.test.tsx

Note: the button is gone for the last requirement in the test.
Example of what it looks like:

feat(command-bar-reflow): requirement view navigation button

---

src/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.scss
src/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.scss
src/tests/electron/tests/android-setup-multiple-devices.test.ts
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-choose-device-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.test.tsx

Nate pointed out some minor variations between the figma and the implementation of the android setup:
1. The intent of the "choose device" step was to auto-select the first item in the list when we enter the dialog. Actual implementation requires the user to choose a device, which makes the initial list of devices see to be offset far more than is expected.
2. Vertical spacing in the "choose device step looks slightly larger than other steps
3. Vertical spacing in the "start testing" step looks slightly larger than other steps
The changes are:
1. In the "start testing step", reduce the vertical spacing between the header and the body by 2 logical pixels.
2. In the choose-device step, the vertical space above the device count is set to 24px by the `margin-top` property of the …

fix(android-setup): Address UI feedback from Nate

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/left-nav/details-view-left-nav.scss
src/DetailsView/components/left-nav/left-nav-icon.tsx
src/DetailsView/components/left-nav/overview-left-nav-link.tsx
src/common/styles/colors.scss
src/common/styles/root-level-only/color-definitions.scss
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/left-nav-icon.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/overview-left-nav-link.test.tsx.snap

Fixes insufficient color contrast with gray text on the new darker background for selected nav items.
Before:
After:
This does not change high contrast mode or the text color when overview is not selected in the nav.

fix: make overview percent text black when selected

---

src/reports/components/outcome-summary-bar.tsx
src/tests/unit/tests/reports/components/__snapshots__/outcome-summary-bar.test.tsx.snap
src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap

Currently, NVDA reads this summary bar (in the overview page of assessment and in reports) as "4% 96% 0%."
After this PR, it will read as "graphic 4% passed, 96% incomplete, 0% failed."

fix: Add aria-label to outcome summary bar

---

src/tests/electron/tests/android-setup-prompt-connect-to-device.test.ts
src/tests/electron/tests/android-setup-prompt-install-service.test.ts
src/tests/miscellaneous/mock-adb/common-adb-configs.js
src/tests/miscellaneous/mock-adb/setup-mock-adb.d.ts
src/tests/miscellaneous/mock-adb/setup-mock-adb.js

To test the "installation failed" step, we need to be able to simulate a failed installation. This PR adds this functionality. It also adds to test to exercise it, and it introduces a refactor into common-adb-configs.js to bring a little more structure into building mock-adb-config.json. I validated the common-adb-configs.js changes by running all supported flavors of **yarn mock-adb** both with and without the changes and performing file comparisons of the output files. The results were identical.

feat(android-setup-e2e): Simulate failed service install

---

src/DetailsView/components/base-left-nav.tsx
src/DetailsView/components/left-nav/details-view-left-nav.scss
src/DetailsView/components/left-nav/left-nav-link-builder.tsx
src/DetailsView/components/nav-link-button.scss
src/DetailsView/components/nav-link-button.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/base-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/nav-link-button.test.tsx.snap
src/tests/unit/tests/DetailsView/components/base-left-nav.test.tsx
src/tests/unit/tests/DetailsView/components/nav-link-button.test.tsx

Due to #3100, we have to render the link component ourselves in the nav. 
Here is a gif of the resulting work (with NVDA).
Left is Insider, right is local build.

fix: tests in assessments show collapsed/expanded state for ATs

---

src/electron/views/device-connect-view/components/android-setup/detect-service-step.tsx
src/tests/electron/tests/android-setup-prompt-install-service.test.ts
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/detect-service-step.test.tsx.snap

This PR updates outdated text in the step. It had the wrong text from the detect devices step.

fix: update detect service dialog text

---

src/tests/electron/tests/android-setup-prompt-connect-to-device.test.ts

Add an E2E test to validate the contrast in the detect-devices spinner

feat(android-setup-e2e): Add contrast tests for detect-devices spinner

---

src/tests/electron/tests/android-setup-detect-service-spinner.test.ts

This checks a11y / HC on the detect-service spinner.

feat(android-setup-e2e): add a11y test for detect-service spinner

---

src/tests/electron/tests/android-setup-prompt-install-failed.test.ts
src/tests/electron/tests/automated-checks-view.test.ts
src/tests/electron/tests/first-time-dialog.test.ts
src/tests/electron/tests/unified-settings-panel.test.ts

Add E2E tests to cover the `prompt-install-failed` and `installing-service` steps.

feat(android-setup-e2e): Add tests for prompt-install-failed

---

package.json
yarn.lock

The PR build for the dependabot PR failed to report its results to GitHub and there was no way to get the build to rerun from GitHub.
I updated the package by running
$yarn upgrade ts-loader
I modified package.json by hand.

Bump ts-loader to 8.0.1 by hand

---

src/DetailsView/components/nav-link-button.scss

The left nav, when in panel form, adds a padding to the right of links. This removes it so we don't see the horizontal scroll bar. 
Before:
After:

fix: fixes horizontal scroll bar issue when in panel for left nav

---

src/tests/electron/common/view-controllers/app-controller.ts
src/tests/electron/tests/android-setup-prompt-connected-start-testing.test.ts

Tests for the prompt-connected-start-testing dialog. Does not include checks to validate that the expected device is selected (I've created https://mseng.visualstudio.com/1ES/_workitems/edit/1742770 to track this)

feat(android-setup-e2e): Add tests for prompt-connected-start-testing

---

src/electron/views/device-connect-view/components/android-setup/android-setup-step-layout.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-configuring-port-forwarding-failed-step.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-connect-to-device-step.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-grant-permissions-step.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-install-failed-step.tsx
src/electron/views/device-connect-view/components/automation-ids.ts
src/tests/electron/common/view-controllers/android-setup-view-controller.ts
src/tests/electron/tests/android-setup-detect-service-spinner.test.ts
src/tests/electron/tests/android-setup-locate-adb.test.ts
src/tests/electron/tests/android-setup-port-forwarding.test.ts
src/tests/electron/tests/android-setup-prompt-choose-device.test.ts
src/tests/electron/tests/android-setup-prompt-connect-to-device.test.ts
src/tests/electron/tests/android-setup-prompt-connected-start-testing.test.ts
src/tests/electron/tests/android-setup-prompt-grant-permissions.test.ts
src/tests/electron/tests/android-setup-prompt-install-failed.test.ts
src/tests/electron/tests/android-setup-prompt-install-service.test.ts
src/tests/electron/tests/automated-checks-view.test.ts
src/tests/electron/tests/first-time-dialog.test.ts
src/tests/electron/tests/unified-settings-panel.test.ts
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-connected-start-testing-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-configuring-port-forwarding-failed-step.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-connect-to-device-step.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-grant-permissions-step.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-install-failed-step.test.tsx

This standardize some practices that have sort of evolved as we've developed the tests. This includes:
- Use `dialog.click()` instead of `dialog.client.click()`. This gives us snapshots on failures
- Refer to "all contrast modes" instead of "both contrast modes"
- Use aliases for leftFooterButtonAutomationId and rightFooterButtonAutomationId in tests
- Centralize the automation id's for android setup into a single file and update all usages
The one customer-facing change in this PR is the automation ID for the rescan button in the prompt-connected-start-testing dialog. The old automation id was `prompt-connected-start-testing-rescan-button`, while the new automation ID is just `rescan`

feat(android-setup-e2e): Standardize test practices

---

docs/building-unified.md
src/tests/miscellaneous/mock-adb/setup-mock-adb-command.js

PR #3120 regressed the behavior of `yarn mock-adb multiple-devices` (or other configs). This PR restores the behavior by adding the missing parameter for the expected log folder.

fix: restore correct behavior of yarn mock-adb * command

---

src/DetailsView/components/nav-link-button.tsx
src/background/extension-details-view-controller.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/nav-link-button.test.tsx.snap
src/tests/unit/tests/background/extension-details-view-controller.test.ts

Using href="#" is preferred over javascript void as the latter violates our content security policy in manifest, which could potentially cause issues with publishing as well. Using '#' by itself broke our navigation in details view and this fixes that as well.

fix: use # instead of javascript void in nav button

---

src/DetailsView/Styles/detailsview.scss
src/reports/components/assessment-summary-details.scss

fix: assessment summary resize fix

---

src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/end-to-end/common/page-controllers/details-view-page.ts
src/tests/end-to-end/common/page-controllers/page.ts
src/tests/end-to-end/tests/details-view/headings.test.ts
src/tests/end-to-end/tests/details-view/reflow-ui.test.ts

Add E2E test cases to run the A11ySelfValidator on new reflow UI components, including:
- Hamburger button and panel
- Command bar "..." button and menu
- Getting started pages
We found several A11y bugs in these components during feature validation that these E2E tests would have caught, so this will prevent regressions for those fixes.

test: E2E tests for reflow components

---

src/reports/components/outcome-summary-bar.scss

The outcome summary bar was using `flex-basis: 100%`, which is intended to imply that child elements should use the height of the containing element by default. This is wrong; we don't want the summary bar to be the height of the whole overview panel. Firefox was doing the right thing (by respecting this incorrect `flex-basis` value), where Chromium for some reason ignores the bogus value.
No visual impact in Chromium.
In Firefox, before (all the content is there if you scroll way down):
after:

fix(firefox): excessive spacing around overview summary bar

---

src/background/extension-details-view-controller.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/webextension-browser-adapter.ts
src/tests/unit/tests/background/extension-details-view-controller.test.ts

Previously, in Firefox, selecting "Settings" or "Preview Features" from the gear menu in the details page would always launch an extra new details view window, in addition to opening the panel it's supposed to.
The root cause is that the actions that handle those menu item presses are the same actions that handle the similar item presses in the popup page's gear menu; they choose whether to launch a new details view window or not as part of responding to the request by checking whether the ExtensionDetailsViewController already knows about a details view tab being open for a given target tab ID, and opening a new details view tab if not. However, the tracking mechanism the control uses for detecting those details view tabs being open is based on looking for tab-update events with URL …

fix(firefox): fix details view gear menu options launching extra windows

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/overview-content/overview-content-container.scss
src/DetailsView/components/overview-content/overview-content-container.tsx
src/DetailsView/components/overview-content/overview-heading.scss
src/DetailsView/components/overview-content/overview-help-section.scss
src/DetailsView/components/requirement-view.scss
src/common/styles/common.scss
src/reports/assessment-report.scss
src/reports/components/assessment-report-summary.scss
src/reports/components/assessment-report-summary.tsx
src/reports/components/assessment-summary-details.scss
src/reports/components/assessment-summary-details.tsx
src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/unit/tests/DetailsView/components/overview-content/__snapshots__/overview-content-container.test.tsx.snap
src/tests/unit/tests/reports/components/__snapshots__/assessment-report-summary.test.tsx.snap
src/tests/unit/tests/reports/components/__snapshots__/assessment-summary-details.test.tsx.snap

Cleans up css pertaining to overview. Required some refactoring around styles in details view generally (which is good since I got to remove some general styles there).
I **did** validate other h2 and h3 elements that would be impacted by the details view changes and things seemed good. This is also why I added the font-size change to the collapsible h2 element.
Before:
After **(note: help text)**:
Before:
After **(note: instances header)**:
Before:
After:

refactor: clean up css pertaining to overview

---

src/electron/views/device-connect-view/components/android-setup/folder-picker.tsx
src/electron/views/renderer-initializer.ts
src/tests/unit/common/android-setup-step-props-builder.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/android-setup-step-container.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/configuring-port-forwarding-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/detect-adb-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/detect-devices-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/detect-permissions-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/detect-service-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/installing-service-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-locate-adb-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/folder-picker.test.tsx
src/tests/unit/tests/injected/visualization/drawer.test.ts

(extracted out of #3185)
Updating to the latest Jest version hits legitimate unit test errors of the form "don't use jest.runAllTimers() without first using jest.useFakeTimers()". These were the results of folder-picker.test.ts mis-using jest.runAllTimers(); the tests wanted to use that to clear the PromiseJob queue, but that's not what that function actually does. This corrects the tests to:
* Consistently use await tick() to clear the PromiseJob queue
* Avoid leaking an unhandled promise rejection in a legitimate case by adding a logger dep to the FolderPicker and reporting the error there instead of leaking it (the behavior of not invoking onChange when the error occurs is already correct and tested)
* It also updates drawer.ts, which legitimately uses jest.useFakeTimers(), clean up …

test: fix jest timer usage

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/common-dialog-styles.scss
src/DetailsView/components/generic-dialog.tsx
src/DetailsView/components/issue-filing-dialog.tsx
src/DetailsView/components/target-change-dialog.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/generic-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/target-change-dialog.test.tsx.snap

Validated the three dialogs that are impacted by this change in details view: start over dialogs, issue filing dialog, and target page changed dialog. No changes were found.

refactor: clean up generic details view dialog styles

---

src/ad-hoc-visualizations/needs-review/visualization.tsx
src/common/components/cards/how-to-check-text.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/how-to-check-text.test.tsx.snap

This PR changes the html tag used to surround hyperlinks in Needs review from a to the NewTabLink component that we have.  This is better because now links will not appear pre-emptively visited, and when clicked, they open in a new tab.  
Gif of the details view page for Needs review, with blue links visible in the subtitle and how to check resolution help.  When a link in the how to check field is clicked, the link is opened in a new tab. When a link in the subtitle is clicked, the link is opened in a new tab. Both links remain blue.

feat(needs-review): Changing links to NewTabLinks

---

src/issue-filing/services/azure-boards/azure-boards-settings-form.tsx
src/tests/unit/tests/issue-filing/services/azure-boards/__snapshots__/azure-boards-settings-form.test.tsx.snap

As described in #3186, minor text change from "File issue details in:" to "Select a field for issue details"
Screenshot of Azure Boards filing in Settings (same for Accessibility Insights for Web and Accessibility Insights for Android)

fix: text change in Settings Issue filing for Azure Boards

---

src/common/feature-flags.ts
src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap

This PR makes the Needs review feature flag visible to the general public!
Image of the Preview Features panel now with both More export options and Needs review appearing as feature flags.

feat(needs-review): Making Needs review feature flag public

---

src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/details-view-switcher-nav.ts
src/DetailsView/components/report-export-dialog-factory.tsx
src/DetailsView/components/should-show-report-export-button.ts
src/assessments/assessment-builder.tsx
src/common/configs/assessment-visualization-configuration.ts
src/common/configs/visualization-configuration-factory.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap
src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
src/tests/unit/tests/DetailsView/components/report-export-dialog-factory.test.tsx
src/tests/unit/tests/DetailsView/components/should-show-report-export-button.test.ts
src/tests/unit/tests/assessments/assessment-builder.test.tsx

In a previous commit, I did not realize that the logic I was using for subjective omission of the 'export report' button in Fastpass was causing that button to always be omitted in assessments.  This PR fixes that, and returns to the previous design where a separate function is used to determine if the button should show in Fastpass and assessments.  The new logic to exclude the button sometimes is still used, but now only applies to Fastpass.  
[The previous PR that introduced the issue](https://github.com/microsoft/accessibility-insights-web/pull/3203)
Gif of a user navigating to Needs review from Automated checks and running a Needs review scan, showing that the 'Export result' button does not appear in Needs review.  The user navigates back to Automated checks, where the button does …

feat(needs-review): Un-breaking the export report button in assessments

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/static-content-common.scss
src/DetailsView/components/static-content-details-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/static-content-details-view.test.tsx.snap

refactor: move details view toggle style to module

---

src/electron/platform/android/rule-information-provider.ts
src/tests/electron/tests/automated-checks-view.test.ts
src/tests/unit/tests/common/components/cards/__snapshots__/rule-resources.test.tsx.snap
src/tests/unit/tests/electron/platform/android/rule-information-provider.test.ts

We've had reports of false positives in the color contrasts test, so we're temporarily excluding the results from the output. This is intended to be a short-term change that will be reverted after we are able to improve the error rate of the results being returned from axe-android.

fix: Exclude color contrast test results (false positives)

---

src/tests/unit/tests/views/content/__snapshots__/content-link.test.tsx.snap
src/views/content/content-link.tsx

I accidentally pushed commit 0e5ccaec125c68297618a2b7d9ffb87dba96a641 directly to master. This reverts it.

fix: Revert 0e5ccae

---

pipeline/unified/build-unsigned-release-packages.yaml

Follows the example from Web's build.yaml to cause the "build" part of unified's release build to generate a NOTICE file using the usual OSPO task as part of the release build.
Out of scope for this PR:
* Updating the electron build process to consume the NOTICE file as part of the electron build output (doing this in a separate PR, since it's feasible to test that part locally using the placeholder NOTICE.html)
* Using the hidden `newExperience` version of the notice generator (it would require extra work to revert that later, and it'll become the default in 1-3 weeks anyway) …

feat(web-compliance): generate NOTICE file as part of Unified release build

---

src/DetailsView/components/command-bar-buttons-menu.tsx
src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/details-view-switcher-nav.ts
src/DetailsView/components/start-over-component-factory.tsx
src/DetailsView/components/start-over-menu-item.scss
src/common/styles/colors.scss
src/common/styles/root-level-only/color-definitions.scss
src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/command-bar-buttons-menu.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-component-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/command-bar-buttons-menu.test.tsx
src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
src/tests/unit/tests/DetailsView/components/start-over-component-factory.test.tsx
src/tests/unit/tests/DetailsView/details-view-body.test.tsx

This completes a fix started in #3165 and continued in #3214 to make sure the "..." menu closes when the buttons are clicked. This PR fixes the issue for the Start Over button in fastpass.
Refactors:
- Refactor startOverComponentFactory into an object containing two separate methods, one to create a component to render in the command bar and one to create a menu item to be shown in the "..." menu
- Instead of using IContextualMenuItem's onRender prop to render the Start Over fastpass button in "..." menu, pass all button props directly to the IContextualMenuItem
- Add styling for the Start Over menu item, since it doesn't get the default OF button stylings
- Also add unit tests for focusing buttons after closing dialogs in DetailsViewCommandBar
UI changes:
- Clicking the "start over" …

fix: close "..." menu when clicking start over fastpass button

---

pipeline/unified/unified-e2e-test-interactive.yaml

We recently doubled the number of e2e tests in the unified product. We've also noticed mac agents seem to timeout more often recently. The current unified-e2e-test timeout is at 10 minutes & they (particularly on Windows and Mac) often aren't complete in this time. This PR updates the timeout to 20 minutes for Windows & Mac machines. A test of [unified-e2e-reliability](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=12829&view=results) shows a recent pass with mac agents finishing in 19 minutes.

chore: update unified e2e test timeout to twenty minutes

---

build.yaml
pipeline/build-package.template.yaml

In the last month or two we've seen disproportionately many timeout and performance issues on Mac agents vs other platforms. This PR experiments with moving platform-agnostic build steps (most notably, web E2Es and the unit_tests_and_lints PR build job) from mac agents to linux ones.
This sacrifices some best-casse PR build performance (~11min to ~14min) to gain reliability

chore: move platform-agnostic build tasks from mac to linux

---

Gruntfile.js
LICENSE
src/electron/electron-builder/electron-builder.template.yaml

This PR ensures that all of our platform distributions bundle all of the following LICENSE/NOTICE files:
* `LICENSE` (our own LICENSE, identical to the text that is bundled into each platform installer already)
* `NOTICE.html` (our NOTICE file, generated by Component Governance as of #3249)
* `LICENSE.electron.txt` (Electron's LICENSE, from the electron package; kept as-is per CELA guidance)
* `LICENSES.chromium.txt` (Chromium's LICENSES, from the electron package; kept as-is per CELA guidance)
* `resources/android-service/NOTICE.txt` ([Accessibility Insights for Android Service](https://github.com/microsoft/accessibility-insights-for-android-service)'s NOTICE file, to cover its transitive gradle dependencies)
On all platforms, our electron packages are missing our NOTICE.html file. This …

feat(web-compliance): bundle LICENSE and NOTICE into unified packages

---

src/tests/unit/tests/scanner/axe-utils.test.ts
src/tests/unit/tests/scanner/custom-rules/css-content-rule.test.ts
src/tests/unit/tests/scanner/custom-rules/css-positioning-rule.test.ts
src/tests/unit/tests/scanner/custom-rules/custom-widget-check.test.ts
src/tests/unit/tests/scanner/custom-rules/unique-landmark-check.test.ts
src/tests/unit/tests/scanner/custom-rules/unique-landmark.test.ts
src/tests/unit/tests/scanner/mock-axe-utils.ts

Between axe 3 and 4, several modules in axe.commons.* [were refactored](https://github.com/dequelabs/axe-core/pull/2147). See below for details. This PR updates the way we mock axe.commons and test axe functionality so that:
- we add a utility function that can be used to mock axe.commons.* types*
- in some cases, we add missing usage of `getFlattenedTree` to ensure axe.commons.* works correctly in contexts outside of `axe.run`. 
These changes should pass in both axe 3 and axe 4. The current tests in master fail in axe 4.0.1.
details:
*The resulting axe.js we consume in 4.0.1 introduces (via webpack + es modules) `Object.defineProperty` with its default `configurable = false` behavior to populate the module's transitive imports. (See definition of `__webpack_require__.d` …

feat(axe-core-4.0.1): update approach for testing axe.commons

---

build.yaml

We've recently been seeing some timeouts in CI/PR build unit test steps, occasionally on the mac agents and more consistently on the linux agents we recently switched to. There doesn't seem to be any evidence that they're getting stuck, it seems that we've just added more tests since we established the timeout.
- [n/a] Addresses an existing issue: n/a

chore: increase PR build unit test timeout

---

src/tests/unit/tests/background/actions/injection-action-creator.test.ts

There was a stray `it.only` that was causing a unit test to be unintentionally skipped. The test already passed, no change to it required.
(As part of the web-compliance feature, we'll be migrating from TSLint to ESLint, which will finally allow us to start using [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/no-focused-tests.md) and prevent this class of issue from occurring again)

chore: remove stray it.only in injection-action-creator tests

---

src/reports/package/root/package.json

As part of the update to axe-core 4.0, we've removed several deprecated rules in #3262. Since a consumer of the report package can no longer rely on the current source to properly display those deprecated rules, we've designated this as a major update to the package. Users using axe 3.0 will want to remain on the 1.x version of the accessibility-insights-reporter package.

feat(axe-core-4.0.1): bump version of accessibility-insights-report

---

.eslintrc.js
src/common/components/fix-instruction-processor.tsx
src/common/configuration/file-system-configuration.ts
src/issue-filing/common/http-query-builder.ts
src/popup/handlers/launch-panel-header-click-handler.ts
src/tests/unit/tests/common/configuration/file-system-configuration.test.ts

Enabled security eslint rules for production code. Maintained disabling the below security eslint rules for code which is not released to production because of the extremely high false positive rate for the security rule set.
- (2) security/detect-non-literal-regexp
- (3) security/detect-non-literal-fs-filename
- (0) security/detect-unsafe-regex
- (0) security/detect-child-process
- (0) security/detect-eval-with-expression
Maintained the disabled rule 'security/detect-object-injection' because there are 295 warnings. Those will be addressed in another PR.

feat(compliance-web): Address security warnings

---

package.json
yarn.lock

Running yarn lint:check:ci will run eslint and generate a sarif file containing the result of the run. This will be run in our CI pipelines for policy compliance.

feat(compliance-web): Add eslint CI option to generate sarif output

---

package.json
yarn.lock

This reverts commit bb27177d3300773407e84e753fc56446de26aa93.
It turns out this commit wasn't necessary because we could run the eslint Azure pipeline task in its default config and it would run only the compliance rules, without running all our eslint rules, which is acceptable since we run all our eslint rules as part of our regular CI pipeline anyway.

Chore: Revert "feat(compliance-web): Add eslint CI option to generate sarif output (#3295)"

---

src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/switcher.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/switcher.test.tsx.snap

Make sure the command bar and switcher are in a landmark (styling looks weird because I downloaded the page to use the visualizer on it, the actual extension page looks the same):

fix: add landmarks for command bar and switcher

---

src/scanner/axe-extension.d.ts
src/scanner/axe-utils.ts
src/scanner/custom-rules/text-contrast.ts
src/tests/unit/tests/scanner/axe-utils.test.ts
src/tests/unit/tests/scanner/custom-rules/custom-widget-check.test.ts
src/tests/unit/tests/scanner/custom-rules/unique-landmark-check.test.ts
src/tests/unit/tests/scanner/rule-to-links-mappings.test.ts

In Axe 4.0, the structure of check configurations changed so that the `evaluate` property could be set as either a function or as a string key that references an internal axe function. In `Axe._audit.defaultConfig.checks`, checks may still have a string in place of the evaluate function. We use `defaultConfig` to access the color-contrast evaluate function in our custom text-contrast check, but since that value is now a string instead of a function, the check was failing silently and causing a false negative for the Adaptable content > contrast requirement.
This PR removes uses of `defaultConfig` and instead uses `Axe._audit.checks` or `Axe._audit.rules`, since the checks found here do have the real evaluate function, instead of just a string. This fixes the false negative.
- [n/a] (UI …

fix: remove use of defaultConfig from Axe._audit

---

src/reports/components/report-sections/report-body.tsx
src/reports/components/report-sections/report-section-factory.tsx
src/reports/components/report-sections/summary-report-section-factory.tsx
src/reports/package/accessibilityInsightsReport.d.ts
src/reports/package/reporter-factory.ts
src/reports/package/reporter.ts
src/reports/package/root/package.json
src/reports/package/summary-results-report.ts
src/reports/summary-report-html-generator.tsx
src/tests/unit/tests/reports/__snapshots__/summary-report-html-generator.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/report-body.test.tsx.snap
src/tests/unit/tests/reports/package/reporter.test.ts
src/tests/unit/tests/reports/package/summary-results-report.test.ts
src/tests/unit/tests/reports/summary-report-html-generator.test.tsx

Creates the necessary classes and factories to generate an empty summary report. Also refactors ReportBody and ReportSectionFactory to accept section components with a props type besides SectionProps.
Currently, this creates an empty report with title and footer:

feat(cli-summary-report): Generate an empty summary report

---

package.json
src/tests/unit/tests/electron/platform/android/__snapshots__/mock-adb.test.ts.snap
yarn.lock

Main difference is updated `NOTICE.html` replacing `NOTICE.txt` for the web-compliance feature

chore(deps): bump accessibility-insights-for-android-service-bin from 1.2.0 to 1.2.1

---

src/electron/views/report/unified-header-section.tsx
src/reports/components/header-bar.scss
src/reports/components/header-bar.tsx
src/reports/components/report-sections/header-section.scss
src/reports/components/report-sections/header-section.tsx
src/reports/components/report-sections/summary-report-header-section.tsx
src/reports/components/report-sections/summary-report-section-factory.tsx
src/tests/unit/tests/electron/report/__snapshots__/unified-header-section.test.tsx.snap
src/tests/unit/tests/reports/components/__snapshots__/header-bar.test.tsx.snap
src/tests/unit/tests/reports/components/header-bar.test.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/header-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/summary-report-header-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/summary-report-header-section.test.tsx

Extract the blue header bar from ReportHeader as a seperate component and add it to the summary report:

feat(cli-summary-report): add summary report header bar

---

src/reports/components/outcome-summary-bar.scss
src/reports/components/outcome-summary-bar.tsx
src/reports/components/outcome-type.tsx
src/reports/components/report-sections/summary-report-section-factory.tsx
src/reports/components/report-sections/summary-report-summary-section.scss
src/reports/components/report-sections/summary-report-summary-section.tsx
src/reports/components/summary-report-head.tsx
src/reports/components/url-outcome-type.ts
src/reports/summary-report.scss
src/reports/summary-report.styles.ts
src/tests/unit/tests/reports/components/__snapshots__/outcome-summary-bar.test.tsx.snap
src/tests/unit/tests/reports/components/__snapshots__/summary-report-head.test.tsx.snap
src/tests/unit/tests/reports/components/outcome-summary-bar.test.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/summary-report-summary-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/summary-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/summary-report-summary-section.test.tsx
src/tests/unit/tests/reports/components/report-sections/summary-section.test.tsx
src/tests/unit/tests/reports/components/summary-report-head.test.tsx

Create summary section for summary report to match the figma:
- Added a new bundled stylesheet for summary report and a ReportHead component to use it in the report
- Some refactoring in OutcomeSummaryBar to add the text labels for each section
- Fix an existing typo in SummarySection unit test

feat(cli-summary-report): Summary report summary section

---

tools/strict-null-checks/auto-add.js
tools/strict-null-checks/eligible-file-finder.js
tools/strict-null-checks/find.js
tools/strict-null-checks/import-finder.js
tools/strict-null-checks/progress.js

The primary impact/motivation here was to fix an issue where `yarn null:find` wasn't outputting all the files it was supposed to (as it turns out, this was windows-specific). The fix for this is on line 39 of `import-finder.js` (different parts of the tool weren't in agreement about normalizing slashes, which was breaking some of the filtering logic).
As part of fixing/debugging this, I did a fair amount of refactoring/cleanup to null:find. I didn't separate out the cleanup into a separate PR like I normally would because this is a short-lived dev-only tool that doesn't require as thorough review as most of the repo's code. …

chore(null): fix yarn null:find on windows

---

src/assessments/assessment-builder.tsx
src/assessments/types/requirement.ts
src/common/configs/assessment-visualization-configuration.ts
src/injected/drawing-initiator.ts
src/injected/frameCommunicators/html-element-axe-results-helper.ts
src/injected/visualization-instance-processor.ts
src/tests/unit/tests/injected/drawing-initiator.test.ts
src/tests/unit/tests/injected/visualization-instance-processor.test.ts

Assessment visualizers are able to configure an `VisualizationInstanceProcessorCallback` to post-process visualization data after it's generated and before it's used for displaying things. This callback generally involves data from the visualization instances' `propertyBag`s, which are `any`-typed.
Previously, the `VisualizationInstanceProcessorCallback` was generic with type parameters representing the "true" `propertyBag` types the individual processor expected. However, the use sites for the processor never actually took this into account; they always blindly assumed that the processor's type parameter was "the union of all the property bag types understood by any existing processor" (`PropertyBags`), and always blindly passed in visualization instances regardless of whether their …

refactor: remove illusion of type safety from visual instance processor

---

src/DetailsView/components/getting-started-view.tsx
src/DetailsView/components/left-nav/getting-started-nav-link.tsx
src/DetailsView/components/left-nav/left-nav-link-builder.tsx
src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/end-to-end/common/page-controllers/details-view-page.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/getting-started-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/getting-started-nav-link.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx

Changed the text case for all instances of "Getting Started" navigation links and page titles to be in sentence case instead of title case to address issue: #3310   
This helps to make these text elements more consistent with other similar elements.

fix: updated text case for "Getting started" titles and nav links

---

src/common/components/cards/cards-visualization-modifier-buttons.scss
src/common/components/cards/instance-details-footer.scss
src/common/components/cards/rule-resources.scss
src/electron/main/main-window-config.ts

The PR addresses a few reflow issues with the unified cards UI at 320px effective width (the bug was reported at 1280x1024 in 400% zoom; per discussion with @ferBonnin, this PR enables the app to resize down to the equivalent 320x256@100%, since we need to support that anyway for 400% users and since it makes testing reflow changes much easier).
Particularly:
* The "expand/collapse" toggle and "visual helper" toggle can now be reflowed onto separate lines, rather than forcing a horizontal scrollbar in the "automated checks" panel
* The "rule resources" card text will now break across lines within words if a word cannot fit in the view (particularly notable for long rule names)
* The highlight status text in the card footer will now break across multiple lines if necessary to avoid the …

fix: unified cards view reflow at 320px width

---

src/reports/components/report-sections/summary-report-section-factory.tsx
src/reports/package/reporter-factory.ts
src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap

It was noticed that we're not using the correct text for the service report, so this fixes that.

fix(cli-summary-report): use correct footer text in reporter factory

---

src/assessments/adaptable-content/test-steps/contrast.tsx
src/common/components/cards/how-to-check-text.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/how-to-check-text.test.tsx.snap

Updated the text for the assessment's adaptable content contrast test and fastpass to address issue #3337.

fix: add corrected text for color contrast tests

---

src/common/stores/store-names.ts
src/electron/data/left-nav-store-data.ts
src/electron/platform/android/types/left-nav-item-key.ts
src/electron/platform/android/types/test-key.ts
src/electron/props/left-nav-props.ts
src/electron/stores/left-nav-store.ts
src/electron/types/left-nav-item.ts

Add basic types to support the left nav bar infrastructure.
The general idea is that the nav bar is designed using a generic value for the keys of its items so that different nav bars can be created for android and hopefully web eventually.
An assumption inherent in this model is that the contents of the (soon to be added) content pane will always be in sync with the selection in the nav bar, so they can both be driven from the same store (LeftNavStore).
And TestKey and LeftNavKey are different because not all items in the left nav bar will necessarily activate tests.

feat(android-left-nav): Introduce basic left nav types

---

src/electron/data/left-nav-store-data.ts
src/electron/platform/android/types/left-nav-item-key.ts
src/electron/props/left-nav-props.ts
src/electron/stores/left-nav-store.ts
src/electron/types/content-page-key.ts
src/electron/types/left-nav-item-key.ts
src/electron/types/left-nav-item.ts
src/electron/types/test-key.ts

The genericity won't be necessary because it only adds complexity to have different stores and actions based on a key type. Instead, we will have one store that handles all the left nav actions and data, and only specific left nav items will be instantiated based on the need at the time.

feat(android-left-nav): Remove generic key parameter from left nav types

---

package.json
src/reports/package/root/package.json
src/tests/end-to-end/tests/details-view/headings.test.ts
src/tests/end-to-end/tests/details-view/reflow-ui.test.ts
src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
yarn.lock

This PR updates our axe-core dependencies to 4.0.2 ([release notes here](https://github.com/dequelabs/axe-core/releases/tag/v4.0.2)).
Out of scope / upcoming in future PRs:
- updating/understanding this reference to axe-core: https://github.com/microsoft/accessibility-insights-web/blob/5711dddefc0da424604f6ca74404c91272cd4ad7/src/packages/accessibility-insights-ui/root/package.json#L11 I'm not sure the UI package should need axe-core, need to explore
- updating the [usage section](https://github.com/microsoft/accessibility-insights-web/blob/master/src/reports/package/root/README.md#usage) of the reporter's README. The package references are easy to change but the usage script is broken (see #3410)
- re-introducing the `link-name` rule now that it's fixed in axe-core

feat(axe-core-4.0.2): update extension and reporter axe-dependency to 4.0.2

---

src/reports/package/root/README.md

This PR updates references to axe-core integration packages (the old packages are being deprecated). We also amend the usage script to catch up with some changes to reporter package (the current script is broken).
I was able to run a node script like this one locally using jest, but the example wasn't self-contained. I had to pick a longer timeout and include some module remapping to commonjs modules (similar to [web file here](https://github.com/microsoft/accessibility-insights-web/blob/5711dddefc0da424604f6ca74404c91272cd4ad7/src/tests/jest.common.config.js#L6)). This produced the reporter file so everything plumbs through. However, locally the produced HTML had some syntax errors; checking if I'm missing something. The report looks correct when I use it from …

docs(axe-core-4.0.2): update reporter README

---

src/electron/flux/store/left-nav-store.ts
src/tests/unit/tests/electron/flux/store/__snapshots__/left-nav-store.test.ts.snap
src/tests/unit/tests/electron/flux/store/left-nav-store.test.ts

This change resulted from a comment in a previous PR. Also fixed unit tests which were not properly initializing the snapshot.

feat(android-left-nav): Set 'automated-checks' as default page for the left nav store

---

src/reports/components/report-sections/summary-results-table.scss
src/reports/components/report-sections/summary-results-table.tsx
src/reports/components/report-sections/url-errors-table.tsx
src/reports/components/report-sections/url-scan-results-table.tsx
src/reports/package/root/package.json
src/tests/unit/tests/reports/components/report-sections/__snapshots__/summary-results-table.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/url-errors-table.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/url-scan-results-table.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/summary-results-table.test.tsx

Currently, when we have long URLs in the summary report, they stretch out the results table and can make it longer than everything else on the page:
This PR will cause long URLs to wrap even if they can't be broken up "by word":

fix: wrap urls in summary report

---

src/DetailsView/components/left-nav/details-view-left-nav.scss
src/DetailsView/components/left-nav/left-nav-icon.scss
src/DetailsView/components/left-nav/left-nav-icon.tsx
src/DetailsView/components/left-nav/test-view-left-nav-link.scss
src/DetailsView/components/left-nav/test-view-left-nav-link.tsx
src/electron/views/automated-checks/automated-checks-view.scss
src/electron/views/left-nav/left-nav.scss
src/electron/views/left-nav/left-nav.tsx
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/left-nav-icon.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/test-view-left-nav-link.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/test-view-left-nav-link.test.tsx
src/tests/unit/tests/electron/views/left-nav/__snapshots__/left-nav.test.tsx.snap

1. Improve heading styles.
2. Improve styles of list component by using css-modules and sharing css.
Not in this PR: fixing the selection CSS.
Result:
This impacts web as well, and it looks the same after the changes:

feat(android-left-nav): improve styling of left nav component

---

src/DetailsView/components/base-left-nav.scss
src/DetailsView/components/left-nav/details-view-left-nav.scss

Some of the details view (i.e. web) specific left nav css should not be so. This brings that css into the basic left nav css. Note: the naming is not great here, since we refer to the basic left nav css as `details-view-test-nav-area` which should be more generic.
I **did** validate that my web extension behaved the same as what we have in staging.
Screen-caps (after adding needs review locally):

feat(android-left-nav): fix up selection css in left nav

---

src/electron/common/content-page-info-factory.ts
src/electron/platform/android/test-configs/android-test-configs.ts
src/electron/platform/android/test-configs/automated-checks/test-config.tsx
src/electron/platform/android/test-configs/needs-review/test-config.tsx
src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/automated-checks/components/header-section.tsx
src/electron/views/automated-checks/test-view.tsx
src/electron/views/root-container/root-container-renderer.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/test-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/header-section.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/header-section.test.tsx
src/tests/unit/tests/electron/views/automated-checks/test-view.test.tsx

- `HeaderSection` refactored to use contentPageInfo from `HeaderSectionProps`
- `TestView` updated to include `ContentPageInfo` in props
- `AutomatedChecksView` updated to get contentPageInfo from `ContentPanelDeps` based on the selected `LeftNavItemKey`
- Created `needsReviewTestConfig` and added it to `androidTestConfigs`
Gif of TestView header section changing when 'Automated checks' or 'Needs review' is selected

feat(android-left-nav): change test view based on selected left nav key

---

src/DetailsView/components/left-nav/test-view-left-nav-link.tsx
src/electron/views/left-nav/left-nav.tsx
src/tests/electron/common/element-identifiers/automated-checks-view-selectors.ts
src/tests/electron/tests/automated-checks-view.test.ts
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/test-view-left-nav-link.test.tsx.snap
src/tests/unit/tests/electron/views/left-nav/__snapshots__/left-nav.test.tsx.snap

Adds two kinds of e2e tests:
- Scan for a11y issues with left nav showing
- Change selected test using left nav.
Not in this PR but should be done: re-naming automated checks view to a more generic name and resulting tests/e2e tests as well.

feat(android-left-nav): added e2e test for android left nav

---

src/electron/views/automated-checks/components/command-bar.scss
src/electron/views/left-nav/left-nav.scss

fix(android-left-nav): change background to white for left nav/command bar

---

src/DetailsView/components/issues-table.scss

Fixes #3446, where the background color previously tore halfway down the automated checks content panel from gray to white.
Screenshot showing prod on left and local build with fix on right:
Verified locally no impact on fastpass report or unified.

fix: avoid background color tearing in fast pass automated checks

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/adhoc-issues-test-view.scss
src/DetailsView/components/adhoc-issues-test-view.tsx
src/DetailsView/components/issue-filing-dialog.scss
src/DetailsView/components/issue-filing-dialog.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-issues-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap

This cleans up css in details view (removing dead unused css and refactors to use css-modules) while also fixing a couple css issues in our fastpass details views.
The issues:
- In a recent change, the gray background behind the cards view was fixed such that it extended through the entire cards view. However, this introduces the problem when the cards view takes up less space than the full details view, we get another issue of mismatching backgrounds. The changes here fix that.
- The background for when the target page was changed was white instead of grey.
Before:
After:
Before:
After:

fix: fastpass background css and refactor details view css

---

src/DetailsView/components/test-status-choice-group.scss

This PR addresses #3435, where in Windows high contrast mode, pass/fail radio buttons that were selected vs not were indistinguishable.
Per discussion with @ferBonnin, this intentionally causes the buttons to use the system-provided colors for selected buttons, which means they do not use different colors for pass vs fail like they do in our app-specific HC mode and in the default theme. Respecting the system theme is more important.
This makes use of some relatively new Edge features around forced-color mode (specifically, the `forced-color-adjust: none;` property). See discussion in #3435 for references.
Screenshots showing before on left and after on right in assorted HC setting modes:
**App HC off, Windows HC off (intentionally no change):**
**App HC on, Windows HC off (intentionally …

fix: use distinguishable colors for test status choice groups in OS high-contrast modes

---

src/DetailsView/components/narrow-mode-detector.tsx
src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/root-container/components/root-container.tsx
src/tests/unit/tests/electron/views/root-container/components/__snapshots__/root-container.test.tsx.snap

- Added this above AutomatedChecksView.
- Changed the NarrowModeDetectorProps.component property so that it would accomodate AutomatedChecksView.

feat(android-nav-reflow): Add NarrowModeDetector into the react component hierarchy

---

src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap
src/tests/unit/tests/reports/package/example-input/axe-results-with-issues.ts
src/tests/unit/tests/reports/package/example-input/axe-results-without-issues.ts
src/tests/unit/tests/reports/package/example-input/summary-scan-with-issues.ts
src/tests/unit/tests/reports/package/example-input/summary-scan-without-issues.ts
src/tests/unit/tests/reports/package/integration.test.ts

This PR adds missing integration tests for the report package's `fromSummaryResults` API.
Out of scope but planned for future PRs in this feature:
* Moving these to act more like E2E tests (using the "real" built package, including CSS bundles)
* Writing pinned files to `/test-results/` for manual verification
* Adding tests for the upcoming `fromCombinedResults` API

chore(combined-report-ui): integration tests for summary report

---

src/reports/package/root/README.md

The usage example in the accessibility-insights-report package readme was missing a closing parenthesis and semicolon. This PR adds them. 

chore: Add missing parenthesis to report package readme example

---

packages/README.md

This adds a `/packages/` directory containing a README documenting monorepoization discussion from the last engineering discussion. I thought this would be more durable (and easier to ask clarifying review comments on) than just leaving it in notes from the meeting.

chore: add /packages/README.md describing planned monorepo layout

---

src/DetailsView/components/interactive-header.scss
src/DetailsView/components/interactive-header.tsx
src/common/components/expand-collapse-left-nav-hamburger-button.tsx
src/common/components/left-nav-hamburger-button.scss
src/common/components/left-nav-hamburger-button.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/interactive-header.test.tsx.snap
src/tests/unit/tests/common/components/__snapshots__/expand-collapse-left-nav-hamburger-button.test.tsx.snap
src/tests/unit/tests/common/components/__snapshots__/left-nav-hamburger-button.test.tsx.snap
src/tests/unit/tests/common/components/expand-collapse-left-nav-hamburger-button.test.tsx
src/tests/unit/tests/common/components/left-nav-hamburger-button.test.tsx

There are no visible changes. We will use this component in the android app and at that time it will have a white background (meaning the color should be different). Since the color of the hamburger menu changes based on the context, it made sense to give that power to the parent rather than the component.

refactor(android-nav-reflow): refactor hamburger button to take css from parent

---

.gitignore
.prettierignore
Gruntfile.js
copyright-header.config.json
pipeline/build-package.template.yaml
src/reports/bundled-reporter-styles.ts
src/tests/unit/tests/reports/components/__snapshots__/report-head.test.tsx.snap
src/tests/unit/tests/reports/components/__snapshots__/summary-report-head.test.tsx.snap
src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap
webpack.config.js

This migrates the webpack/grunt output for the 2 npm packages in the repo from `/package/package-name/*` to `/packages/package-name/*` (package -> packages) to match where the output will start living with the future migration to a monorepo layout.
I verified with a directory diff that `/package/report/drop` before this change and `/packages/report/drop` after this change have identical contents after `yarn build:package:report`.

chore: move yarn build:package:* output to match future monorepo layout

---

src/electron/views/automated-checks/components/command-bar.scss
src/electron/views/automated-checks/components/reflow-command-bar.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/reflow-command-bar.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/reflow-command-bar.test.tsx

This creates a new command bar component which is a copy of the existing command bar component but with significant changes. It made sense to create a duplicate component that will be specified once in automated-checks-view instead of having multiple flagged component changes in combination with the narrow mode status detector conditional changes.
Note: since the command bar still uses the ReportExportComponent, it has an issue where the dropdown menu does not disappear after you select export report. This was an issue in web as well but has been resolved. I will look into getting the same result in a future PR (will likely need some further refactoring work).
Screenshot of how it looks:
Dropdown screenshot:

feat(android-nav-reflow): add a reflow command bar for android

---

.vscode/settings.json

A few of us were noting that VS Code's "format-on-save" seemed to not be working recently. I suspect this is because VS Code added a new non-prettier js/ts formatter, so when we weren't explicitly setting a default formatter to use, VS Code didn't know which one to use and chose to give up rather than guessing.

chore: fix format-on-save by setting default vscode formatter to prettier

---

src/electron/flux/action-creator/left-nav-action-creator.ts
src/electron/flux/action/left-nav-actions.ts
src/electron/flux/store/left-nav-store.ts
src/electron/flux/types/left-nav-store-data.ts
src/tests/unit/tests/electron/flux/action-creator/left-nav-action-creator.test.ts
src/tests/unit/tests/electron/flux/store/__snapshots__/left-nav-store.test.ts.snap
src/tests/unit/tests/electron/flux/store/left-nav-store.test.ts
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx

This is the state which will be set when narrow mode is enabled and the hamburger button has shown or hidden the left nav pane.

feat(android-nav-reflow): Add left nav visible state to LeftNavStore

---

src/electron/views/left-nav/fluent-left-nav.scss
src/electron/views/left-nav/fluent-left-nav.tsx
src/electron/views/left-nav/left-nav.scss
src/tests/unit/tests/electron/views/left-nav/__snapshots__/fluent-left-nav.test.tsx.snap
src/tests/unit/tests/electron/views/left-nav/fluent-left-nav.test.tsx

feat(android-nav-reflow): add hamburger button to fluent left nav

---

src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx

This change makes it so that when the window width is less than the narrow mode threshold for the command bar, the ReflowCommandBar component will be rendered instead of the standard CommandBar component.
The change only applies of course in the case where the feature flag is active.

feat(android-nav-reflow): Use ReflowCommandBar when narrow mode is enabled

---

src/electron/views/automated-checks/automated-checks-view.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap

This change inserts the use of the FluentLeftNav component where the LefNav component was previously used. This should allow the left nav bar to be hidden and made visible by the hamburger button when the app window shrinks sufficiently.

feat(android-nav-reflow): Use FluentLeftNav component instead of LeftNav

---

src/common/types/store-data/card-view-model.ts
src/reports/combined-report-html-generator.tsx
src/reports/components/report-sections/combined-report-section-factory.ts
src/reports/package/accessibilityInsightsReport.d.ts
src/reports/package/combined-results-report.ts
src/reports/package/combined-results-to-cards-model-converter.ts
src/reports/package/reporter-factory.ts
src/scanner/rule-to-links-mappings.ts
src/tests/unit/tests/reports/combined-report-html-generator.test.tsx
src/tests/unit/tests/reports/package/__snapshots__/combined-results-to-cards-model-converter.test.ts.snap
src/tests/unit/tests/reports/package/combined-results-report.test.ts
src/tests/unit/tests/reports/package/combined-results-to-cards-model-converter.test.ts
src/tests/unit/tests/reports/package/example-input/combined-results-with-issues.ts
src/tests/unit/tests/reports/package/example-input/combined-results-without-issues.ts

- Convert the combined/deduplicated results we take as input into CardsViewModel and add cards data to CombinedReportSectionProps
- Small change to report package interface to fix structuring of passed and inapplicable rules
- Add instance failure urls to CardResult
- Add mock testing data for combined report

feat(combined-report-ui): convert combined results to cards data

---

src/common/types/store-data/card-view-model.ts
src/reports/combined-report-html-generator.tsx
src/reports/components/report-sections/combined-report-section-factory.ts
src/reports/components/report-sections/combined-report-summary-section.tsx
src/reports/package/accessibilityInsightsReport.d.ts
src/reports/package/combined-results-report.ts
src/reports/package/combined-results-to-cards-model-converter.ts
src/tests/unit/tests/reports/combined-report-html-generator.test.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/combined-report-summary-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/combined-report-summary-section.test.tsx
src/tests/unit/tests/reports/package/__snapshots__/combined-results-to-cards-model-converter.test.ts.snap
src/tests/unit/tests/reports/package/combined-results-report.test.ts
src/tests/unit/tests/reports/package/example-input/combined-results-with-issues.ts
src/tests/unit/tests/reports/package/example-input/combined-results-without-issues.ts

Created combined report summary section, which is visually identical to the summary section of the summary report, but accepts combined results as props:
Also added a field to the report package interface to accept counts of passed/failed/unscannable URLs

feat(combined-report-ui): Combined report summary section

---

package.json
yarn.lock

Web's dependency graph involves several transitive dependencies on weakly-specified `@types/node` versions (eg, `@types/node@*` and `@types/node@>= 8`. Practically speaking, these end up getting set to whatever `@types/node` version had the "latest" tag at the time of the last dependabot PR that updated one of the dependency chains including it.
Since our builds pin to using LTS node (12.x), what we actually should be doing is resolving these explictly to 12.x typings. Previously, we happened to gotten lucky and ended up with `12.x` versions for most past cases, but today, a few dependabot PRs (#3509, #3525) that involve relevant updates happen to be picking up a 14.x types resolution, which is causing build breaks that aren't particularly related to the actual dependency updates in those …

chore(deps-dev): pin @types/node to match engine

---

src/DetailsView/components/report-export-component.tsx
src/electron/views/automated-checks/components/reflow-command-bar.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-component.test.tsx.snap
src/tests/unit/tests/DetailsView/components/report-export-component.test.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/reflow-command-bar.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/reflow-command-bar.test.tsx

Currently:
The dropdown menu does not disappear when the user leaves the export report dialog.
Now:
The dropdown menu disappears and the dropdown button is focused.

feat(android-nav-reflow): fix command bar '...' dropdown menu behavior

---

src/tests/electron/common/view-controllers/automated-checks-view-controller.ts
src/tests/electron/common/view-controllers/view-controller.ts
src/tests/electron/tests/automated-checks-view.test.ts

Some of the unified automated-checks-view tests had cases where they were starting out by **querying** for an expected UI state rather than **waiting** for an expected UI state. This updates them to work consistently with other tests by allowing for a timeout to get to the expected state.
Examples of motivating failures:
* [for "highlight box count" case](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=15135&view=logs&j=b652ef49-bd3c-5349-02df-b4a91dc35ba0&t=271e4398-bdf4-5bea-5b16-6aa3306d6007)
* [for "rule groups count" case](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=15136&view=logs&j=c5567cdb-c930-534d-6489-7c2dcf7ac8ee&t=fe6db478-348c-54d0-bafe-001288e28283)
- [n/a] Addresses an …

test(e2e-flakiness): improve reliability of automated-checks-view tests

---

src/tests/end-to-end/common/page-controllers/page.ts

This suppresses the pageerrors tracked by #3529 which are a big source of flaky e2e behavior

test(e2e-flakiness): suppress flaky e2e failure of form pageerror with message 'Object'

---

src/tests/end-to-end/common/browser.ts
src/tests/end-to-end/tests/common/settings-drop-down.test.ts
src/tests/end-to-end/tests/content/guidance-content.test.ts
src/tests/end-to-end/tests/details-view/cross-origin-iframe.test.ts
src/tests/end-to-end/tests/details-view/headings.test.ts
src/tests/end-to-end/tests/details-view/landmarks.test.ts
src/tests/end-to-end/tests/details-view/overview.test.ts
src/tests/end-to-end/tests/details-view/preview-features.test.ts
src/tests/end-to-end/tests/details-view/reflow-ui.test.ts
src/tests/end-to-end/tests/details-view/settings-panel.test.ts
src/tests/end-to-end/tests/popup/adhoc-panel.test.ts
src/tests/end-to-end/tests/popup/first-time-dialog.test.ts
src/tests/end-to-end/tests/popup/hamburger-menu.test.ts
src/tests/end-to-end/tests/popup/launchpad.test.ts
src/tests/end-to-end/tests/target-page/issue-dialog.test.ts
src/tests/end-to-end/tests/target-page/tabstop.test.ts
src/tests/end-to-end/tests/target-page/visualization-boxes.test.ts

This was originally motivated by wanting to audit all the `browser.close` instances to see if we were ever closing a browser while there might still be an unawaited page.close in progress, which per [this puppeteer issue](https://github.com/puppeteer/puppeteer/issues/1947) might explain [failures like what we're seeing in the e2e windows jobs here](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=15197&view=results).
I didn't find anything to suggest that that's an accurate root cause for our issue, but I thought this update made stuff more readable regardless.
- [n/a] Verified code coverage for the changes made. Check coverage report …

test(e2e-flakiness): simplify browser.close calls in test fixtures

---

src/electron/flux/store/left-nav-store.ts
src/tests/unit/tests/electron/flux/store/left-nav-store.test.ts

feat(android-nav-reflow): left nav panel closed after test select

---

packages/report-e2e-tests/src/examples/combined-results-with-issues.input.ts
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.input.ts
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/from-combined-results.test.ts
src/tests/unit/tests/reports/package/__snapshots__/combined-results-to-cards-model-converter.test.ts.snap
src/tests/unit/tests/reports/package/combined-results-to-cards-model-converter.test.ts

Adds a pinning E2E test for the combined report (currently pinning its existing unfinished behavior).
I reused the full inputs @pownkel already made for the unit tests by moving them to the E2Es and updating the unit tests to use more test-specific input data

test(combined-report-ui): implement E2E pinning test for combined report

---

src/common/components/left-nav-hamburger-button.tsx
src/electron/views/left-nav/fluent-left-nav.tsx
src/tests/electron/common/element-identifiers/automated-checks-view-selectors.ts
src/tests/electron/tests/automated-checks-view.test.ts
src/tests/unit/tests/common/components/__snapshots__/left-nav-hamburger-button.test.tsx.snap
src/tests/unit/tests/electron/views/left-nav/__snapshots__/fluent-left-nav.test.tsx.snap

Added tests to check the following scenarios
- When the window width is greater than the narrow mode threshold for unified, the hamburger button is not shown in the command bar
- When the window width is less than the narrow mode threshold for unified,
- the hamburger button is shown in the command bar
- the left nav bar is not initially visible
- when the hamburger button is clicked, the left nav pane becomes visible
- if the hamburger button is clicked again, the left nav pane disappears
- if a link in the left nav pane is clicked, the left nav pane disappears

feat(android-nav-reflow): Add e2e tests

---

packages/report-e2e-tests/src/examples/combined-results-with-issues.input.ts
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
src/common/components/cards/urls-card-row.tsx
src/injected/adapters/resolution-creator.ts
src/reports/package/accessibilityInsightsReport.d.ts
src/reports/package/combined-results-to-cards-model-converter.ts
src/reports/package/reporter-factory.ts
src/tests/unit/tests/common/components/cards/__snapshots__/urls-card-row.test.tsx.snap
src/tests/unit/tests/injected/adapters/resolution-creator.test.ts
src/tests/unit/tests/reports/package/__snapshots__/combined-results-to-cards-model-converter.test.ts.snap
src/tests/unit/tests/reports/package/combined-results-to-cards-model-converter.test.ts

Add missing "how to fix" card row to combined report. This involves changing the input interface to accept the resolution data that we get from axe-core.

feat(combined-report-ui): add "How to fix" card row

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
src/reports/components/report-sections/summary-report-details-section.scss
src/reports/components/report-sections/summary-report-details-section.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/summary-report-details-section.test.tsx.snap

Fixes font weight and spacing on scan details report section's content.
Out of scope: fixing the font weight on the `<h2>Scan details</h2>` (will look at this in concert with all the other similarly too-heavy `<h2>`s on the page)
Figma:
Before:
After:

feat(combined-report-ui): fit and finish for scan details

---

src/tests/common/retry.ts
src/tests/common/serialize-error.ts
src/tests/electron/common/create-application.ts
src/tests/electron/setup/timeouts.ts
src/tests/end-to-end/common/page-controllers/page.ts

This is an attempt to improve one of the more common forms of unified e2e flakiness, where arbitrary tests will fail with an error like ([example](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=15160&view=logs&j=d8690f4f-0e2c-53bd-8425-d38de88bbdbc&t=9af9e376-ae64-51a0-7cc0-a01a37a7a200)):
```
ChromeDriver did not start within 5000ms
at node_modules/spectron/lib/chrome-driver.js:63:25
at Request._callback (node_modules/spectron/lib/chrome-driver.js:121:23)
at self.callback (node_modules/request/request.js:185:22)
at Request.Object.<anonymous>.Request.onRequestError (node_modules/request/request.js:881:8)
```
I initially tried just increasing the timeout from 5s to 10s, but was still seeing the same class of failure. This PR now attempts to …

test(e2e-flakiness): add retries around unified e2e app.start

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.input.ts
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
packages/report-e2e-tests/src/from-axe-result.test.ts
packages/report-e2e-tests/src/from-combined-results.test.ts
packages/report-e2e-tests/src/from-summary-results.test.ts

In the current combined report snapshots, the WCAG links are missing for failed rules because the mock data uses fake rule names that we do not have a guidance link mapping for. This PR updates the data to use real axe rule data, which makes WCAG links appear in the snapshots:
Updating the combined-results-with-issues snapshot also caused the combined-results-without-issues snapshot to change, because the link component used for guidance links uses a getId function from Office Fabric to generate ids, and the id counter is not reset after every test. This PR also adds a resetId call before every report e2e test, so we don't have unexpected snapshot changes like this in the future. This is the reason for the id changes in the other report testing snapshots.

test(combined-report-ui): use real axe rule ids in testing data

---

src/tests/end-to-end/common/page-controllers/page.ts

It looks like #3530 wasn't actually effective in practice; we're still seeing [build failures](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=15339&view=logs&j=68a299b9-62d0-5a30-ce8c-dfe0a5cc8669&t=a830d86d-93e7-5957-11a0-b663859dbe26&l=34) of the form:
```
Received: "Playwright.Page 'chrome-extension://eheeiipehjcbehnicfejeidgbhffnikc/background/background.html' emitted 'pageerror' (console.error): [Error]{
[Error: Object]
}"
```
I haven't been able to reproduce this locally, so it's not clear to me exactly why the current filtering isn't working; this attempts to filter based on the serialized error based on its real properties, since presumably the real message property is some actual object that won't serialize well rather than the …

test(e2e-flakiness): attempt 2 at suppressing Error: Object e2e issue

---

packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
src/common/components/cards/rules-with-instances.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/rules-with-instances.test.tsx.snap
src/tests/unit/tests/common/components/cards/rules-with-instances.test.tsx

Currently, the accessible label for the rules header still reports the count of cards, not the value on the chip, which takes the number of URLs into account in the combined report:
This PR will use the outcomeCounter in the accessible label, like it is already being used to calculate the number on the chip, so that the two counts match. This will not affect the automated checks or summary reports.

feat(combined-report-ui): fix failure count in rule header aria-label

---

build.yaml

Recently, about 30-40% of PR builds have started failing in unit test timeouts. These cases don't appear to be getting stuck; they seem to make progress and generally time out when they are about 80-95% done.
I picked the new timeout value by extrapolating from the worst-case in these timeouts (`15min * (80%)^(-1) ~= 19min`), adding 25% for future tests' fudge factor (~23.4min), and rounding to the nearest roundish number (25min).
I looked back over history and wasn't able to find any particular change that seemed related to causing the regression (there wasn't a specific suspicious jest update that I saw, in particular). I would like to try to work on improving the perf of these tests (15min is excessive), but I want to get PR builds unblocked in the meantime.
- [n/a] Addresses an …

chore(build): extend unit test timeout

---

jest.config.base.js

A recent ts-jest update started showing this warning when running web unit tests:
```
ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
```
This resolves the warning.

chore(build): fix ts-jest warning

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
src/common/components/cards/instance-details-group.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/instance-details-group.test.tsx.snap

The existing aria label for the instance details group refers specifically to the path, snippet, and how to fix rows. The combined report has added a potential URL row. This PR updates the label to be accurate for both the combined report and existing scenarios.

feat(combined-report-ui): Update InstanceDetailsGroup aria-label for combined report

---

src/tests/electron/common/view-controllers/app-controller.ts
src/tests/electron/tests/automated-checks-view.test.ts

Swaps out `getTitle()` based test for a `waitForTitle()` instead

test(e2e-flakiness): update automated checks title test to wait

---

src/common/html-element-utils.ts
src/injected/analyzers/rule-analyzer.ts
src/injected/element-finder-by-path.ts
src/injected/frameCommunicators/frame-communicator.ts
src/injected/frameCommunicators/scrolling-controller.ts
src/injected/frameCommunicators/window-message-handler.ts
src/tests/unit/tests/common/html-element-utils.test.ts
src/tests/unit/tests/injected/element-finder-by-path.test.ts
src/tests/unit/tests/injected/scrolling-controller.test.ts
tsconfig.strictNullChecks.json

This PR resolves all `yarn null:find` results. Unfortunately, that still leaves about half the non-test files in the repo outside of strictNullChecks, so it implies that there's still a bug happening somewhere in `yarn null:find` preventing it from listing all the files it should; fixing that is for a separate PR.
`yarn null:progress` as of this PR:
```markdown
**49%** complete (**682**/1382 non-test files)
*Contribute at [#2869](https://github.com/microsoft/accessibility-insights-web/issues/2869). Last update: Wed Nov 04 2020*
```

chore(null): fix all remaining null:find results

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
src/common/components/cards/rules-with-instances.scss
src/common/styles/colors.scss
src/common/styles/root-level-only/color-definitions.scss
src/reports/components/report-sections/footer-section.scss

Change WCAG links and tool link in the report to our usual blue link color so the links are distinguishable from the rest of the text. Also make the footer text darker to have 3:1 contrast with the link color.
Before:
After:

fix: change text color for report WCAG links and footer text

---

src/background/injector-controller.ts
src/background/stores/visualization-store.ts
src/common/types/store-data/visualization-store-data.ts
src/injected/analyzer-state-update-handler.ts
src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/background/injector-controller.test.ts
src/tests/unit/tests/background/stores/visualization-store.test.ts
src/tests/unit/tests/injected/analyzer-state-update-handler.test.ts

I was doing some work in the InjectionController and got confused trying to remember the difference between the VisualizationStoreData properties `injectionStarted` and `injectionInProgress`. This PR:
* Renames `injectionInProgress` to `injectionRequested`, to better reflect its usage
* Extracts the complex if clause in `InjectionController` to give names to individual subparts
No behavior change.

refactor: clarify naming/usage of visualization store injectionInProgress

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/details-view-switcher-nav.ts
src/DetailsView/components/save-assessment-button.tsx
src/DetailsView/components/save-assessment-factory.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/save-assessment-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
src/tests/unit/tests/DetailsView/components/save-assessment-factory.test.tsx

This PR adds the save assessment factory and removes the save assessment button from rendering in FastPass. 
FastPass:
Assessments:

feat(save-and-load-assessment): add save assessment factory

---

src/DetailsView/details-view-initializer.ts
src/electron/views/renderer-initializer.ts
src/reports/components/report-sections/no-failed-instances-congrats.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/no-failed-instances-congrats.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/no-failed-instances-congrats.test.tsx

Updates the unified path for forming the "congrats!" message when no instances are found to be cognizant of the automated checks vs needs review difference.

feat(android-needs-review): use android Continue Investigating text in needs review congrats message

---

src/DetailsView/components/report-export-component.tsx
src/electron/platform/android/test-configs/automated-checks/test-config.tsx
src/electron/platform/android/test-configs/needs-review/test-config.tsx
src/electron/types/content-page-info.ts
src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/automated-checks/components/reflow-command-bar.tsx
src/tests/electron/common/element-identifiers/automated-checks-view-selectors.ts
src/tests/electron/tests/automated-checks-view.test.ts
src/tests/electron/tests/needs-review-view.test.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-component.test.tsx.snap
src/tests/unit/tests/electron/common/content-page-info-factory.test.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/reflow-command-bar.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/reflow-command-bar.test.tsx

- Add `allowsExportReport` property to `ContentPageInfo` so whether or not the export report button is shown can be specified as part of a test config
- Modify `ReflowCommandBar` to respect the `allowsExportReport`  setting
- Add e2e tests to confirm the export report button is shown for automated checks, but not for needs review

feat:(android-needs-review): Don't show the export report button when needs review is selected

---

src/tests/unit/tests/views/content/markup.test.tsx
src/views/content/content-page.tsx
src/views/content/markup.tsx

This PR breaks a cyclic dependency between `src/views/content/content-page.tsx` and `src/views/content/markup.tsx` by updating `Markup.Include` to work in terms of props types that `markup.tsx` defines rather than the types `content-page.tsx` defines, then updating the related `content-page` types to be defined in terms of `markup`'s definitions.

chore: break circular dependency between markup and content-page

---

src/common/get-card-selection-view-data.ts
src/tests/unit/tests/common/get-card-selection-view-data.test.ts

PR #3633 introduced the concept of a `ResultsFilter` and used it to ensure that the proper elements are highlighted in Automated Checks and Needs Review when all cards are collapsed. Unfortunately, it failed to address the scenario where some cards are expanded or selected. This PR addresses those scenarios by ensuring that we always limit our `resultsHighlightStatus` data to reflect the currently selected tab's results.

feat(android-needs-review): Fix Android Needs Review screenshot highlighting behavior

---

src/electron/views/screenshot/highlight-box.tsx
src/electron/views/screenshot/screenshot-view-model-provider.ts
src/electron/views/screenshot/screenshot-view-model.ts
src/tests/unit/tests/common/components/cards/sample-view-model-data.ts
src/tests/unit/tests/electron/views/screenshot/__snapshots__/highlight-box.test.tsx.snap
src/tests/unit/tests/electron/views/screenshot/__snapshots__/screenshot-container.test.tsx.snap
src/tests/unit/tests/electron/views/screenshot/highlight-box.test.tsx
src/tests/unit/tests/electron/views/screenshot/screenshot-container.test.tsx
src/tests/unit/tests/electron/views/screenshot/screenshot-view-model-provider.test.ts

This removes the ! labels from needs review highlight boxes by making the view model provider determine the label according to result status.
Needs review omitting "!" labels:
Automated checks still showing same "!" labels:

feat(android-needs-review): remove ! label from needs review screenshot highlights

---

src/DetailsView/components/save-assessment-button.tsx
src/DetailsView/components/save-assessment-factory.tsx
src/DetailsView/details-view-initializer.ts
src/common/assessment-data-formatter.ts
src/tests/unit/common/__snapshots__/assessment-data-formatter.test.tsx.snap
src/tests/unit/common/assessment-data-formatter.test.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/save-assessment-button.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/save-assessment-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
src/tests/unit/tests/DetailsView/components/save-assessment-button.test.tsx
src/tests/unit/tests/DetailsView/components/save-assessment-factory.test.tsx

This PR adds the download functionality to the save assessment button and updates relevant tests. 
- [n/a ] (UI changes only) Added screenshots/GIFs to description above
- [ n/a] (UI changes only) Verified usability with NVDA/JAWS

feat(save-and-load-assessment): get assessment data for save button

---

src/common/extension-telemetry-events.ts
src/electron/views/renderer-initializer.ts
src/tests/electron/common/element-identifiers/automated-checks-view-selectors.ts
src/tests/electron/common/element-identifiers/results-view-selectors.ts
src/tests/electron/common/element-identifiers/screenshot-view-selectors.ts
src/tests/electron/common/view-controllers/app-controller.ts
src/tests/electron/common/view-controllers/automated-checks-view-controller.ts
src/tests/electron/common/view-controllers/results-view-controller.ts
src/tests/electron/tests/android-setup-prompt-connected-start-testing.test.ts
src/tests/electron/tests/automated-checks-view.test.ts
src/tests/electron/tests/needs-review-view.test.ts
src/tests/electron/tests/results-view.test.ts
src/tests/electron/tests/unified-settings-panel.test.ts

The idea is to separate test code for the results view -- which covers the overall content of the app such as the command bar, left nav bar, and page content -- into its own file, while keeping the test code for the automated checks view -- the automated test results -- in its own file.
- Rename `ElectronAutomatedChecksView` to `ElectronResultsView` in `TelemetryEventSource`
- Extract code having to do with results view from `AutomatedChecksViewController` into `ResultsViewController` (likewise with selectors)
- Extract tests having to do with results view into a separate e2e test file
- Both sets of tests should still test for accessibility

feat(android-needs-review): Rename AutomatedChecks* to Results* in e2e tests

---

src/tests/electron/common/view-controllers/automated-checks-view-controller.ts
src/tests/electron/tests/automated-checks-view.test.ts
src/tests/electron/tests/needs-review-view.test.ts

Validate there should be one rule and one failure instance for color contrast in needs review.
The next step will be to rename `AutomatedChecksViewController` to `CardsViewController` because the latter is more descriptive of the classes current purpose. The rename will be done separately to keep the diff in this change targeted.

feat(android-needs-review): Add e2e test to validate expected cards in needs review view

---

src/electron/views/device-connect-view/components/android-setup/prompt-connect-to-device-step.tsx
src/electron/views/device-connect-view/components/android-setup/prompt-grant-permissions-step.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-connect-to-device-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-grant-permissions-step.test.tsx.snap

This makes the text changes called out in #3542. Here are the before and after images:
Screen | Before | After
Connect Device | ![image](https://user-images.githubusercontent.com/45672944/99452738-d2d2a800-28d8-11eb-9a3d-c5f28d5c4a90.png) | ![image](https://user-images.githubusercontent.com/45672944/99452795-e3831e00-28d8-11eb-9a62-680a24f4cb03.png)
Grant Permissions | ![image](https://user-images.githubusercontent.com/45672944/99452880-fbf33880-28d8-11eb-91ff-ac2a76b44115.png) | ![image](https://user-images.githubusercontent.com/45672944/99452904-07466400-28d9-11eb-9bdf-b5026032d0d6.png)

fix: Improve user messages when connecting Android device

---

src/tests/electron/common/view-controllers/cards-view-controller.ts
src/tests/electron/common/view-controllers/results-view-controller.ts
src/tests/electron/tests/automated-checks-view.test.ts
src/tests/electron/tests/needs-review-view.test.ts

The rename represents that testing cards is not exclusive to the automated checks page of the results view.

feat(android-needs-review): Rename AutomatedChecksViewController to CardsViewController

---

src/common/components/cards/expand-collapse-all-button.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/expand-collapse-all-button.test.tsx.snap

Issue #3539 suggests an improvement to the Expand all/Collapse all button when read via a screen reader. Specifically, set the aria-label property to a more descriptive value when the button is in the collapsed state. The issue says nothing about modifying the aria-label property in the expanded state. Change has been validated with NVDA in both Web and Unified clients.
HTML of the button in the collapsed state (aria-label property is new)
```
<button type="button" aria-expanded="false" aria-label="Expand all rules to show failed instances." class="ms-Button ms-Button--action ms-Button--command expand-collapse-all-button--3fwBF root-113" data-is-focusable="true"><span class="ms-Button-flexContainer flexContainer-108" data-automationid="splitbuttonprimary"><i data-icon-name="ChevronRight" …
```

fix: Make "Expand all" button more screen-reader friendly

---

src/electron/views/device-connect-view/components/electron-external-link.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/electron-external-link.test.tsx

Before this PR, when you click on a link that appears in the body of a card in unified's results view (eg, Color Contrast results as of the needs review feature), the click event bubbles up out of the link component, so in addition to opening the link, it also select/deselects the card. This PR prevents the event from propagating.
Note that the same basic issue affects web and this PR does *not* fix that case; the link components are product specific so they need separate fixes.
Before:
After:

fix(android-needs-review): make links in unified cards not also select the cards when clicked

---

src/assessments/prerecorded-multimedia/test-steps/audio-description.tsx
src/content/link.tsx

added WCAG link to the links list and requirement for WCAG 1.2.3 that was missing in the report.
- [x ] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [x ] (UI changes only) Added screenshots/GIFs to description above

fix: added WCAG link to the links list and requirement

---

src/electron/views/left-nav/fluent-left-nav.tsx
src/tests/unit/tests/electron/views/left-nav/__snapshots__/fluent-left-nav.test.tsx.snap
src/tests/unit/tests/electron/views/left-nav/fluent-left-nav.test.tsx

fix(android-needs-review): make left nav panel dismiss on escape and on click out of menu

---

src/DetailsView/components/adhoc-issues-test-view.tsx
src/DetailsView/components/adhoc-static-test-view.tsx
src/DetailsView/components/details-list-issues-view.tsx
src/DetailsView/components/inline-start-over-button.scss
src/DetailsView/components/inline-start-over-button.tsx
src/DetailsView/components/issues-table.scss
src/DetailsView/components/issues-table.tsx
src/DetailsView/components/target-page-changed-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-issues-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-static-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/details-list-issues-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/inline-start-over-button.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-changed-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/adhoc-issues-test-view.test.tsx
src/tests/unit/tests/DetailsView/components/inline-start-over-button.test.tsx
src/tests/unit/tests/DetailsView/components/issues-table.test.tsx
src/tests/unit/tests/DetailsView/components/target-page-changed-view.test.tsx

Replace the "Start over" text in "use the start over button to scan the target page" with an inline button, as described in #3229:
This affects the "target changed" view in all fastpass pages, and the view before scanning for "automated checks" and "needs review."

fix: inline start over button

---

package.json

This changes the --colors flag to --color on any webpack scripts in package.json to fix an error that occurs when those scripts are run on newer versions of webpack.
The --color flag without the 's' is the official flag in the [Webpack CLI API](https://webpack.js.org/api/cli/)

fix: change --colors flag to --color to fix webpack CLI build

---

src/common/types/analyzer-telemetry-callbacks.ts
src/common/types/axe-analyzer-result.ts
src/injected/analyzers/analyzer.ts
src/injected/analyzers/base-analyzer.ts
src/injected/analyzers/batched-rule-analyzer.ts
src/injected/analyzers/rule-analyzer.ts
src/injected/analyzers/tab-stops-analyzer.ts
src/injected/analyzers/unified-result-sender.ts
src/tests/unit/tests/common/telemetry-data-factory.test.ts
src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts

This PR fixes one of the big reasons `yarn null:find-cycles` finds so many results; specifically, it breaks a dependency from `common/types/analyzer-telemetry-callbacks.ts` to `injected/analyzers/analyzer.ts` by moving the `AxeAnalyzerResult` type out of `analyzer.ts` into its own file under `common/types`.
Previously, this dependency was creating *tons* of cycles (essentially, any code that touched anything telemetry related transitively included the telemetry callbacks, which then ended up going through analyzers implementation, which involves some telemetry).
Line counts of `yarn null:find-cycles` (reduced by 38% with this PR):
Before:
```
C:\repos\accessibility-insights-web [master ≡] | 59 | 14:34:24 12/04
> yarn null:find-cycles | measure
Count             : 15839
```
After:
``` …
```

refactor: break common to non-common dep in analyzer-telemetry-callbacks

---

.eslintrc.js
src/ad-hoc-visualizations/issues/visualization.tsx
src/background/completed-test-step-telemetry-creator.ts
src/electron/platform/android/rule-information-provider.ts
src/injected/frameCommunicators/html-element-axe-results-helper.ts
src/reports/assessment-report-model-builder.ts
src/reports/package/combined-results-to-cards-model-converter.ts
src/tests/end-to-end/common/browser.ts
src/tests/end-to-end/common/page-controllers/background-page.ts
src/tests/miscellaneous/mock-adb/app/bin.js
src/tests/miscellaneous/mock-adb/setup-mock-adb-command.js
src/tests/unit/tests/common/get-card-selection-view-data.test.ts

This PR adds a lint rule enforcing the usage of `===` vs `==` that we've historically encouraged:
* `==`/`!=` is allowed when comparing against `null` or ` undefined` to mean `is null OR undefined`
* `==`/`!=` are banned in favor of `===`/`!==` in all other cases
The eslint `eqeqeq` rule is a little more strict than our historical guidance (it only allows `== null`, not `== undefined`), but there weren't that many cases using the latter, so I just updated them all as part of turning on the rule (having the rule catch dangerous cases is more important than keeping the `== undefined` cases as is for readability's sake).
Thanks @madalynrose for pointing out that we should be enabling this! I hadn't realized it wasn't part of eslint's default recommended set.
- [n/a] Addresses an existing …

chore: enable eslint rule enforcing === except for null checks

---

src/common/feature-flags.ts
src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
src/tests/unit/tests/background/feature-flags.test.ts

changed the Needs Review test feature flag to on by default.
- [ x] Addresses an existing issue: #3710
- [ x] Ran `yarn fastpass`
- [ N/A] Added/updated relevant unit test(s) (and ran `yarn test`)

fix: needs review feature flag ON by default

---

src/issue-filing/services/azure-boards/create-azure-boards-issue-filing-url.ts
src/tests/unit/tests/issue-filing/services/azure-boards/create-azure-boards-issue-filing-url.test.ts

Addresses issue #3438- Accessibility Insights for Android bugs are filed with Web tags in ADO.
Currently, the global title string ("Accessibility Insights for Web") is used for all Azure Boards issue filing tags. This PR updates `createAzureBoardsIssueFilingUrlProvider` to use the current app name from `ToolData`. This has no impact on the Web product and causes the unified issue filing tag to be "Accessibility Insights for Android".

fix: Use current app name in Azure Boards issue tag

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.input.ts
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.input.ts
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.input.ts
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.input.ts
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
packages/report/package.json
src/common/application-properties-provider.ts
src/common/types/store-data/unified-data-interface.ts
src/reports/components/report-sections/combined-report-failed-section.tsx
src/reports/components/report-sections/combined-report-rules-only-sections.tsx
src/reports/components/report-sections/combined-report-section-factory.ts
src/reports/package/accessibilityInsightsReport.d.ts
src/reports/package/footer-text-for-service.tsx
src/reports/package/reporter-factory.ts
src/tests/unit/common/application-properties-provider.test.ts
src/tests/unit/tests/electron/common/application-properties-provider.test.ts
src/tests/unit/tests/reports/components/report-sections/__snapshots__/combined-report-failed-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/combined-report-rules-only-sections.test.tsx.snap
src/tests/unit/tests/reports/package/__snapshots__/footer-text-for-service.test.tsx.snap
src/tests/unit/tests/reports/package/combined-results-report.test.ts
src/tests/unit/tests/reports/package/footer-text-for-service.test.tsx
src/tests/unit/tests/reports/package/summary-results-report.test.ts

Addresses the combined report changes requested in #3729
- Add "rules" to the result section title names (i.e. "failed rules" instead of just "failed")
- Reorder result sections (failed, passed, then not applicable)
- Add browser resolution as a package parameter
- Update service report footer text (affects all service reports)
- Bump package version from 3.1.0 to 4.1.0 (major update b/c of the breaking change to the interface to include browser resolution)

fix: Combined report UI changes

---

src/assessments/common/instructions-and-labels-note.tsx
src/assessments/custom-widgets/test-steps/instructions.tsx
src/assessments/native-widgets/test-steps/instructions.tsx
src/content/test/custom-widgets/instructions.tsx
src/content/test/native-widgets/instructions.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
src/tests/unit/tests/assessments/common/__snapshots__/instructions-and-labels-note.test.tsx.snap

These text changes address #3752, making the instructions better align with WCAG SC 2.5.3 Label in Name.
**Screenshot of Native widgets > Instructions**
**Screenshot of Native widgets > Instructions > more info icon**
**Screenshot of Custom widgets > Instructions**
**Screenshot of Custom widgets > Instructions > more info icon**

fix: text changes in native and custom widgets instructions

---

src/common/telemetry-data-factory.ts
src/common/types/analyzer-telemetry-callbacks.ts
src/injected/analyzers/analyzer-provider.ts
src/injected/analyzers/batched-rule-analyzer.ts
src/injected/analyzers/rule-analyzer.ts
src/injected/main-window-initializer.ts
src/tests/unit/tests/common/telemetry-data-factory.test.ts
src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts
src/tests/unit/tests/injected/analyzers/batched-rule-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts

This PR breaks a cyclic dependency which is transitively included by a wide variety of components:
* analyzer-provider.ts
* visualization-configuration-factory.ts
* visualization-configuration.ts
* assessment-visualization-configuration.ts
* analyzer-provider.ts
It does so by recognizing that `analyzer-provider`'s dep on `visualization-configuration-factory` is unnecessary; it is only used to map from a `VisualizationType` to a string injected into telemetry, but most of the similar telemetry already uses `VisualizationType[theVisualizationType]` for this rather than going through the configuration factory; making this particular telemetry consistent with the rest eliminates the need for the dependency.
@ferBonnin / @juchampa as an FYI: there is no user-facing impact for this change. The …

chore: remove VisualizationConfigurationFactory dep from rule analyzers

---

.eslintrc.js
src/DetailsView/components/export-dialog-with-local-state.tsx
src/DetailsView/components/failure-instance-panel-control.tsx
src/DetailsView/components/report-export-component.tsx
src/common/components/collapsible-component.tsx
src/debug-tools/components/telemetry-viewer/telemetry-viewer.tsx

Ensures the current (soon to be previous) state of a react component is accessed from within the `setState` callback in order to protect against the possibility of the state being set by out-of-date data when calls to setState are batched.

Chore: Add eslint rule react/no-access-state-in-setstate

---

src/tests/end-to-end/test-resources/shadow-doms.html

I created a small test page for verifying shadow DOM compat when we were discussing #3768; this adds that page to the repo so other can use it for future manual testing/verification.

test: add manual test page for shadow DOMs

---

.eslintrc.js
src/injected/components/details-dialog.tsx
src/popup/components/launch-panel-header.tsx
src/popup/handlers/launch-panel-header-click-handler.ts
src/tests/unit/tests/popup/components/__snapshots__/launch-panel-header.test.tsx.snap
src/tests/unit/tests/popup/handlers/launch-panel-header-click-handler.test.ts

This is one of the warnings found by lgtm.com.
While `isContextMenuVisible` was set, it's value was never read. Therefore, it could be removed.
There are two instances where the rule is disabled because it is finding false positives.
In launch-panel-header-click-handler.test.ts, I chose to leave `setStateMock` when it could also have been removed because this ensures that calling `openAdhocToolsPanel` has no unexpected side-effects related to the header object's state.

Chore: Add eslint rule react/no-unused-state

---

src/electron/common/left-nav-item-factory.ts
src/electron/types/test-config.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/common/left-nav-item-factory.test.ts

Now that we're adding more left nav items to ai-unified, we'd like an easy way to hide them with feature flags.
To accomplish this, this PR:
- introduces a `featureFlag` property to `TestConfig` 
- modifies left nav item creation such that if a given `TestConfig` has a `featureFlag` value that refers to a disabled feature flag, no left nav item is created
- if `featureFlag` is undefined, behavior is unchanged.
Because no test configs are currently behind feature flags, this PR has no user impact.

feat(focus-mvp-client): Introduce and use unified TestConfig feature flags

---

src/electron/common/unified-feature-flags.ts
src/electron/platform/android/test-configs/android-test-configs.ts
src/electron/platform/android/test-configs/tab-stops/test-config.tsx
src/electron/types/test-key.ts
src/tests/electron/tests/results-view.test.ts
src/tests/unit/tests/electron/common/unified-feature-flags.test.ts

We need a new test config to add the Tab Stops test to AI-Android.
This PR adds such a config with the proper title and description. Because new components are not yet ready, it uses existing components for `instancesSectionComponent` and `visualHelperSection`. To avoid showing the new test, it introduces a tab stops feature flag as well.
This PR does not attempt to update how test configs are displayed to match the Tab Stops UI spec, so the screenshot will not look like the final product.
Screenshot of Tab Stops:

feat(focus-mvp-client): Add new test config for Tab Stops

---

src/electron/platform/android/adb-wrapper.ts
src/electron/platform/android/appium-adb-wrapper.ts
src/electron/platform/android/device-focus-command-sender.ts
src/electron/platform/android/device-focus-controller-factory.ts
src/electron/platform/android/device-focus-controller.ts
src/electron/platform/android/send-focus-command.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/platform/android/appium-adb-wrapper.test.ts
src/tests/unit/tests/electron/platform/android/device-focus-comand-sender.test.ts
src/tests/unit/tests/electron/platform/android/device-focus-controller-factory.test.ts
src/tests/unit/tests/electron/platform/android/device-focus-controller.test.ts

Adds code to communicate with the Android client for the focus order feature. It uses ADB to send keystrokes to the device, and calls new service endpoints (which will be implemented in the service in the next feature) to control the service state. 
The intended use is to add the `DeviceFocusControllerFactory` to the deps that get passed into the TabStops page. When loading, the TabStop page will need to call the factory with the port and the ADB location (both in the store, and both determined during device connection, which is why the TabStops page needs to use the factory to generate a `DeviceFocusController` object). It then uses the `DeviceFocusController` object to send commands to the device. Errors are bubbled up to the caller for error handling.
Part of the Android focus order …

feat(focus-mvp-client): Add code to send commands to device

---

src/tests/miscellaneous/mock-adb/common-adb-configs.js
src/tests/miscellaneous/mock-adb/setup-mock-adb.d.ts
src/tests/miscellaneous/mock-adb/setup-mock-adb.js
src/tests/unit/tests/electron/platform/android/__snapshots__/mock-adb.test.ts.snap
src/tests/unit/tests/electron/platform/android/mock-adb.test.ts

Teach mock-adb how to handle ADB's `shell input keyevent` commands for keyevent codes of 19, 20, 21, 22, 61, and 66 (these are the codes that we intend to use for this feature, and are added in #3873).
We're using these commands as part of the android focus feature. In order to validate these in E2E tests, we need to make sure that mock-adb is able to handle these commands.
The spec calls for Shift+Tab, but we believe that to be infeasible at the moment, so we're doing only the 4 arrow keys (codes 19-22), Tab (code 61), and Enter (code 66). It would have been nice to pull these from the TypeScript enum, but I couldn't find a clean way to do that with the configurator being in straight JavaScript.
- [n/a] (UI changes only) Added screenshots/GIFs …

feat(focus-mvp-client): Add shell input keyevent commands to mock-adb

---

src/electron/common/left-nav-item-factory.ts
src/electron/types/left-nav-item.ts
src/electron/views/left-nav/fluent-left-nav.tsx
src/electron/views/left-nav/left-nav.tsx
src/electron/views/renderer-initializer.ts
src/electron/views/results/results-view.tsx
src/tests/unit/tests/electron/common/left-nav-item-factory.test.ts
src/tests/unit/tests/electron/views/left-nav/__snapshots__/fluent-left-nav.test.tsx.snap
src/tests/unit/tests/electron/views/left-nav/__snapshots__/left-nav.test.tsx.snap
src/tests/unit/tests/electron/views/left-nav/fluent-left-nav.test.tsx
src/tests/unit/tests/electron/views/left-nav/left-nav.test.tsx

A previous PR (#3861) added feature flags to TestConfig to allow easily hiding feature left nav items. This PR moves the filtering of left nav items out of the initialization logic into the rendering logic. This allows the feature flag to be toggled without restarting the app.
The primary motivation for this PR is to make the Tab Stops feature flag easier to enable during e2e tests. 
The only user impact of this PR is that toggling a left nav related feature flag will now take immediate effect instead of requiring an app restart.

refactor(focus-mvp-client): Move LeftNavItem feature flag filtering from initialization to rendering

---

docs/building-web.md

`yarn install` is failing on my Mac because Spectron assumes that Xcode is present on the system. This isn't currently documented.
Make it easier to get a new machine to a usable state.

chore: Add mac instructions to install Xcode

---

src/tests/electron/tests/tab-stops-view.test.ts

This PR adds an initial E2E test for AI-Android's Tab Stops. Since Tab Stops' functionality is not yet implemented, this just runs some basic validation on the Tab Stops view.
Adds E2E coverage for Tab Stops.
Future PRs will enhance this test to validate more Tab Stops functionality.

feat(focus-mvp-client): Add initial AI-Android Tab Stops E2E test

---

src/DetailsView/components/save-assessment-factory.tsx
src/tests/unit/tests/DetailsView/components/save-assessment-factory.test.tsx

This PR addresses a bug and updates the save assessment functionality from using `persistedTabInfo` to `tabStoreData` to get the assessment title. 
When running AI for the first time, `persistedTabInfo` is null and currently breaks the extension. 
Using `scanMetadata` is also an alternative. 

feat(save-and-load-assessment): update persistedTabInfo to tabStoreData

---

src/common/extension-telemetry-events.ts
src/electron/common/electron-telemetry-events.ts
src/electron/platform/android/device-focus-controller-factory.ts
src/electron/platform/android/device-focus-controller.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/platform/android/device-focus-controller-factory.test.ts
src/tests/unit/tests/electron/platform/android/device-focus-controller.test.ts

This adds telemetry to the DeviceFocusController, per the requirements in the spec
Spec requirement
I had to add the Android-specific telemetry payload (the KeyEventCode value) in a file called extension-telemetry-events. That seems odd since there's also a file called electron-telemetry-events, but I noticed that we have other Android-specific stuff in that file, so I didn't try to fix it in this PR. 

feat(focus-mvp-client): Add telemetry to DeviceFocusController

---

src/electron/platform/android/device-focus-controller.ts
src/electron/platform/android/test-configs/tab-stops/test-config.tsx
src/electron/types/visual-helper-section.ts
src/electron/views/results/results-view.tsx
src/electron/views/virtual-keyboard/virtual-keyboard-buttons.scss
src/electron/views/virtual-keyboard/virtual-keyboard-buttons.tsx
src/electron/views/virtual-keyboard/virtual-keyboard-view.tsx
src/tests/unit/tests/electron/views/results/__snapshots__/results-view.test.tsx.snap
src/tests/unit/tests/electron/views/results/results-view.test.tsx
src/tests/unit/tests/electron/views/virtual-keyboard/__snapshots__/virtual-keyboard-buttons.test.tsx.snap
src/tests/unit/tests/electron/views/virtual-keyboard/__snapshots__/virtual-keyboard-view.test.tsx.snap
src/tests/unit/tests/electron/views/virtual-keyboard/virtual-keyboard-buttons.test.tsx
src/tests/unit/tests/electron/views/virtual-keyboard/virtual-keyboard-view.test.tsx

Uses the device focus controller and adb wrapper holder to allow the virtual keyboard view to work.
Allows us to control devices in focus order test.
Licecap is broken on Mac so I cannot share a gif 😭

feat(focus-mvp-client): wire up virtual keyboard view

---

src/electron/platform/android/device-focus-controller.ts
src/electron/views/virtual-keyboard/virtual-keyboard-buttons.tsx
src/tests/unit/tests/electron/platform/android/device-focus-controller.test.ts

I followed the wrong casing conventions for method names in a recent commit. This changes the function names
Follow style guidelines

chore(focus-mvp-client): Correct casing of method names

---

src/tests/electron/common/view-controllers/app-controller.ts
src/tests/electron/common/view-controllers/log-controller.ts
src/tests/miscellaneous/mock-adb/app/bin.js
src/tests/miscellaneous/mock-adb/app/port-forward-server.js
src/tests/miscellaneous/mock-adb/generate-log-paths.d.ts
src/tests/miscellaneous/mock-adb/generate-log-paths.js
src/tests/miscellaneous/mock-service-for-android/mock-service.js

This PR updates mock adb and the mock service for Android to log their received commands. These logs can then be referenced in E2E tests to confirm that the proper adb and service commands occurred. This PR has no other impact on current E2E tests and does not impact preexisting logging behavior.
Currently, our E2E tests implicitly validate that adb and service commands occurred because the UI updates based on the results of the commands. The new Tab stops UI will allow users to send adb and service commands without displaying UI feedback for those commands. This creates a new testing requirement--we need to explicitly validate that the proper commands were sent.
This PR does not add or modify any E2E tests. Instead, it adds the backing infrastructure to support future E2E tests. New …

feat(focus-mvp-client): Add mock adb + android service command logging for future E2E tests

---

src/content/test/contrast/state-changes.tsx

This PR adds information to the Contrast > State changes"  assessment requirement, per issue #3778. The 'i' icon has been added and on click opens with additional information.

fix: add info to contrast's state changes requirement 

---

src/electron/views/device-disconnected-popup/device-disconnected-popup.tsx
src/tests/unit/tests/electron/views/device-disconnected-popup/__snapshots__/device-disconnected-popup.test.tsx.snap
src/tests/unit/tests/electron/views/device-disconnected-popup/device-disconnected-popup.test.tsx

- Updated Device Disconnected dialog to be more generic
The dialog had specific language surrounding scanning.  With the addition of tab stops, they may not be scanning at all when the device disconnects, so we've made the dialog more generic to accommodate a wider variety of scenarios.

feat(focus-mvp-client): Update Device Disconnected dialog to be more generic

---

src/electron/flux/action/tab-stops-action-creator.ts
src/electron/flux/action/tab-stops-actions.ts
src/tests/unit/tests/electron/flux/action-creator/tab-stops-action-creator.test.ts

Simply adding actions/action creator to be used in other PRs.
For tab stops feature.

feat(focus-mvp-client): add tab stops actions/creator

---

src/tests/electron/common/view-controllers/log-controller.ts
src/tests/electron/setup/timeouts.ts
src/tests/electron/tests/__snapshots__/tab-stops-view.test.ts.snap
src/tests/electron/tests/tab-stops-view.test.ts

Currently, the tab stops e2e tests click all the virtual keyboard keys, wait for the last one to have a result, and then validate the results. This PR updates the tab stops e2e tests to click, wait for a result, and validate each virtual keyboard key individually.
Timing issues cause the existing test to be flaky. 
A refactor to `LogController` is included.

fix(focus-mvp-client): Improve e2e reliability by testing each virtual keyboard key separately

---

src/electron/views/tab-stops/tab-stops-testing-content.tsx
src/tests/unit/tests/electron/views/tab-stops/__snapshots__/tab-stops-testing-content.test.tsx.snap

This updates the instructions for testing tab stops on unified. These are suggestions from Lisa Louise.
Updated copy to better communicate how to test.

feat(focus-mvp-client): updated tab stops testing text

---

src/common/stores/store-names.ts
src/electron/flux/action/tab-stops-action-creator.ts
src/electron/flux/store/tab-stops-store.ts
src/electron/flux/types/tab-stops-store-data.ts
src/electron/platform/android/device-focus-controller.ts
src/electron/views/renderer-initializer.ts
src/electron/views/tab-stops/virtual-keyboard-buttons.tsx
src/tests/unit/tests/electron/flux/action-creator/tab-stops-action-creator.test.ts
src/tests/unit/tests/electron/flux/store/__snapshots__/tab-stops-store.test.ts.snap
src/tests/unit/tests/electron/flux/store/tab-stops-store.test.ts
src/tests/unit/tests/electron/platform/android/device-focus-controller.test.ts
src/tests/unit/tests/electron/views/tab-stops/__snapshots__/virtual-keyboard-view.test.tsx.snap
src/tests/unit/tests/electron/views/tab-stops/virtual-keyboard-buttons.test.tsx
src/tests/unit/tests/electron/views/tab-stops/virtual-keyboard-view.test.tsx

Adds a store for tracking tab stops state. Also updates the action creator to use the device focus controller (and adds functionality).
Feature work.
The alternative approach to the action creator changes: we could instead listen to the tab stops store and then act accordingly. However, that would require a lot of state management and make the action creator complicated. What that would require:
- We would need to listen to the store update in device focus controller, compare past state, and then choose accordingly to either enable/disable focus tracking.
- Either inconsistency with how we send keyboard commands (direct device focus controller invocation) vs. enabling/disabling focus tracking (on store update) OR do store related infra work that will contain the virtual keyboard commands …

feat(focus-mvp-client): add tab stops store and update tab stops action creator

---

src/electron/platform/android/test-configs/tab-stops/start-over-button-settings.ts
src/electron/types/content-page-info.ts
src/electron/views/results/components/reflow-command-bar.tsx
src/electron/views/results/results-view.tsx
src/electron/views/results/test-view.tsx
src/electron/views/root-container/components/root-container.tsx
src/electron/views/tab-stops/tab-stops-testing-content.tsx
src/tests/unit/tests/electron/platform/android/test-configs/tab-stops/start-over-button-settings.test.ts
src/tests/unit/tests/electron/views/results/__snapshots__/results-view.test.tsx.snap
src/tests/unit/tests/electron/views/results/__snapshots__/test-view.test.tsx.snap
src/tests/unit/tests/electron/views/results/results-view.test.tsx
src/tests/unit/tests/electron/views/results/test-view.test.tsx
src/tests/unit/tests/electron/views/tab-stops/__snapshots__/tab-stops-testing-content.test.tsx.snap
src/tests/unit/tests/electron/views/tab-stops/tab-stops-testing-content.test.tsx

wires up the tab stops test with the store/action creators recently created.

feat(focus-mvp-client): wire up tabstops

---

src/electron/flux/action/tab-stops-action-creator.ts
src/electron/platform/android/device-focus-controller.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/flux/action-creator/tab-stops-action-creator.test.ts
src/tests/unit/tests/electron/platform/android/device-focus-controller.test.ts

Moves telemetry to a sole location in the action creator.
Keeps telemetry in one place.
From a previous PR comment.

refactor(focus-mvp-client): telemetry moved to action creator for tab stops

---

src/electron/common/left-nav-item-factory.ts
src/electron/flux/action/tab-stops-action-creator.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/common/left-nav-item-factory.test.ts
src/tests/unit/tests/electron/flux/action-creator/tab-stops-action-creator.test.ts

Left nav items disable/reset tests (like tab stops) on select.
feature work.
In the web product, we also reset all tests when left nav items are changed (and then enable the selected one). This does the same, except we do not currently have a method to "disable all tests". However, I suspect in the future we will specifically remove the dependency on tabstops action creator and add something that can do that for us.
Important to note:
1. For UX reasons, this will NOT trigger the device disconnected dialog if there is an error thrown (unlike other interactions).
2. This will also not publish telemetry in this scenario for resetting the tab stops state (outside of the telemetry that would otherwise be published for left nav item switching).

feat(focus-mvp-client): reset tab stops to default state on left nav item select

---

src/tests/electron/common/element-identifiers/results-view-selectors.ts
src/tests/electron/common/view-controllers/results-view-controller.ts
src/tests/electron/tests/__snapshots__/tab-stops-view.test.ts.snap
src/tests/electron/tests/tab-stops-view.test.ts

This PR adds an e2e test to validate that the start over button on the tab stops test sends the reset command to the service.
Feature spec
Looks a lot like #3961 

feat(focus-mvp-client): Add start over button e2e test

---

src/tests/electron/tests/__snapshots__/tab-stops-view.test.ts.snap
src/tests/electron/tests/tab-stops-view.test.ts

Leaving Tab Stops in unified sends a reset command to the service for Android. This PR adds an e2e test to validate that scenario.
Feature spec
n/a
- [n/a] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.

feat(focus-mvp-client): Add e2e test for the leaving Tab Stops scenario

---

src/electron/platform/android/setup/android-browser-close-cleanup-tasks.ts
src/electron/platform/android/setup/android-port-cleaner.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/platform/android/setup/android-browser-close-cleanup-tasks.test.ts
src/tests/unit/tests/electron/platform/android/setup/android-port-cleaner.test.ts

- Adds android browser close cleanup tasks
- Disables visualizations on device when the client is closed.
To handle all browser close cleanup tasks in one place. Also improved UX, focus tracking visualizations will be turned off when the client is closed.

feat(focus-mvp-client): Add browser close cleanup tasks and turnoff visualizations on close

---

src/tests/electron/tests/tab-stops-view.test.ts

The e2e tests for the tab stops reset command should have waited for the server log to contain the command before moving forward. This PR corrects that absence. 
This can cause unexpected build failures ([example](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=18754&view=logs&j=f648b298-ed87-530e-70f6-09f20704007e))
We're already doing this in the rest of the tab stops e2e tests.

fix(focus-mvp-client): Wait for server logs to exist in tab stops e2e tests

---

src/electron/platform/android/setup/android-browser-close-cleanup-tasks.ts
src/tests/electron/tests/__snapshots__/tab-stops-view.test.ts.snap
src/tests/electron/tests/tab-stops-view.test.ts
src/tests/unit/tests/electron/platform/android/setup/android-browser-close-cleanup-tasks.test.ts

This is the final E2E test for this feature. It gets the app into the state where focus tracking is enabled, then it exits the app and confirms that we have sent the command to disable focus tracking. It also corrects a small error in the cleanup code, which was sending the Disable command instead of the Reset command. Eventually, the difference between them will be that Disable will retain a list of Views that have received the focus, while Reset will clear that list. 
Part of the feature

feat(focus-mvp-client): Add E2E test for exit scenario

---

src/electron/platform/android/setup/android-browser-close-cleanup-tasks.ts
src/tests/unit/tests/electron/platform/android/setup/android-browser-close-cleanup-tasks.test.ts

- Ensures all cleanup tasks are run in the correct order as disconnectDevice must be the last cleanup task to run.
To ensure calls are executed in the proper order

feat(focus-mvp-client): add unit test to verify call order of browser cleanup tasks

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/DetailsView/components/next-requirement-button.tsx
src/background/actions/assessment-action-creator.ts
src/common/extension-telemetry-events.ts
src/common/messages.ts
src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
src/tests/unit/tests/DetailsView/components/next-requirement-button.test.tsx
src/tests/unit/tests/background/actions/assessment-action-creator.test.ts

Creates new methods on action-creator/message-action-creator side to fire telemetry specifically for next requirement button.
We currently don't have telemetry specifically for this scenario so it is hard to know when users are using this next requirement button vs. normally selecting a requirement.

fix: add telemetry for next requirement button specifically

---

src/electron/views/tab-stops/tab-stops-testing-content.scss
src/electron/views/tab-stops/tab-stops-testing-content.tsx
src/tests/unit/tests/electron/views/tab-stops/__snapshots__/tab-stops-testing-content.test.tsx.snap

Some of the testing text was accidentally omitted in a previous commit, this restores it. This also bolds mentions of the "Tab" key and makes the sublists type of "disc" to bring it more in-line with Web's appearance for the tab stops test.

fix: adding in missing 4a step and unifying tab stops testing content with web

---

src/electron/platform/android/adb-wrapper.ts
src/electron/platform/android/appium-adb-wrapper.ts
src/electron/platform/android/setup/android-service-configurator.ts
src/electron/platform/android/setup/android-setup-deps.ts
src/electron/platform/android/setup/android-setup-step-id.ts
src/electron/platform/android/setup/android-setup-steps-configs.ts
src/electron/platform/android/setup/live-android-setup-deps.ts
src/electron/platform/android/setup/port-cleaning-service-configurator.ts
src/electron/platform/android/setup/steps/grant-overlay-permission.ts
src/electron/views/device-connect-view/components/android-setup/default-android-setup-components.ts
src/electron/views/device-connect-view/components/android-setup/grant-overlay-permission-step.tsx
src/tests/miscellaneous/mock-adb/common-adb-configs.js
src/tests/unit/tests/electron/platform/android/__snapshots__/mock-adb.test.ts.snap
src/tests/unit/tests/electron/platform/android/appium-adb-wrapper.test.ts
src/tests/unit/tests/electron/platform/android/setup/android-service-configurator.test.ts
src/tests/unit/tests/electron/platform/android/setup/live-android-setup-deps.test.ts
src/tests/unit/tests/electron/platform/android/setup/port-cleaning-service-configurator.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/grant-overlay-permission.test.ts
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/grant-overlay-permission-step.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/grant-overlay-permission-step.test.tsx

Add a step to the Android setup state machine which automatically grants the overlay permission required to display tabstops indicators on the Android device screen.
Part of the tabstops feature
The reason for automatically granting the permission is that in Android SDK version 30, the overlay permission is silently granted by the system when the media projection permission (`SYSTEM_ALERT_WINDOW`) is granted. If the user has a device running SDK version 29 or lower, since the user must grant the media projection permission, we believe it is acceptable to automatically grant the overlay permission as Google has chosen to do in SDK 30. If there is any objection to granting the overlay permission silently, we can of course add UX later to inform the user the permission is being granted on …

feat(focus-mvp-android-device) Grant overlay permission

---

pipeline/e2e-test-from-docker.yaml
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

Add missing e2e snapshot and pass --ci to linux e2e tests in pipeline
- Fix currently failing Windows and mac E2E tests
- Make sure Linux pipelines are running with the right settings so missing snapshots are not generated in the pipeline

fix: guidance content e2e snapshot

---

src/DetailsView/components/target-page-changed-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-changed-view.test.tsx.snap

Remove errant quotes on one of our messages in the UI
Screenshots below (ignore dark mode difference)
Before:
After:

fix: update target-page-changed-view to remove quotes

---

src/background/actions/action-creator.ts
src/background/actions/action-hub.ts
src/background/actions/details-view-action-creator.ts
src/background/actions/preview-features-actions.ts
src/background/stores/details-view-store.ts
src/background/stores/tab-context-store-hub.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/common/details-view-store-data-builder.ts
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/actions/action-hub.test.ts
src/tests/unit/tests/background/actions/details-view-action-creator.test.ts
src/tests/unit/tests/background/stores/details-view-store.test.ts
tsconfig.strictNullChecks.json

This PR replaces the special handling for `onClosePreviewFeaturesPanel` with reuse of a common "close side panel" path already used to close the settings and scoping side panels. This was the only path that used `preview-features-actions`, so that file got removed as part of the PR.
This finishes a collection of `refactor(side-panel)` PRs that @smoralesd did most of last year. I noticed it when trying to add `details-view-action-creator.ts` to the `strictNullChecks` list, where L88 hit an error due to this unfinished refactor; I decided that it seemed cleaner (net -83 LOC) to finish the refactor rather than update the types to work around the issue.
Late followup to #2313, #2420, #2424
Verified manually that closing the preview features panel still appears to work as expected.
- [n/a] (UI …

refactor(side-panel): make closePreviewFeatures handling consistent with other side panels

---

src/electron/views/tab-stops/tab-stops-testing-content.tsx
src/tests/unit/tests/electron/views/tab-stops/__snapshots__/tab-stops-testing-content.test.tsx.snap

This PR fixes a skipped heading level on the tab stops test in AI-Android that was discovered during the accessibility pass.
To ensure that AI-Android meets all accessibility guidelines.

fix: aria heading level for android tab stops test

---

src/electron/common/unified-feature-flags.ts
src/electron/platform/android/test-configs/tab-stops/test-config.tsx
src/tests/unit/tests/electron/common/unified-feature-flags.test.ts

Set the default value of the tabstops visualization for Android to true in preparation for release.

feat(focus-mvp-android-device): Set default value of feature flag to true

---

src/electron/views/results/results-view.scss

Sets a min-width for the results area, basing it on the left nav width.
Bug fix.
This only happens in Tab Stops/Needs Review because those tests don't have the appropriate length in their instructions/description. That content was implicitly setting the width that we wanted (because it filled the required area).
Before:
After:

fix: fixes spacing issue in AI Android when some tests are selected

---

src/DetailsView/components/report-export-dialog-factory.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-dialog-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/report-export-dialog-factory.test.tsx

Update scanDate to return current date for the date stamp populated as part of the exported results file title.
Addresses the bug in issue  #3995.
- [/] (UI changes only) Added screenshots/GIFs to description above
- [/] (UI changes only) Verified usability with NVDA/JAWS

fix: update scanDate to get current date

---

src/electron/flux/action/tab-stops-action-creator.ts
src/electron/types/content-page-info.ts
src/electron/views/renderer-initializer.ts
src/electron/views/tab-stops/tab-stops-testing-content.tsx
src/tests/unit/tests/electron/flux/action-creator/tab-stops-action-creator.test.ts
src/tests/unit/tests/electron/platform/android/test-configs/shared-scan-results/start-over-button-settings.test.ts
src/tests/unit/tests/electron/views/results/components/reflow-command-bar.test.tsx
src/tests/unit/tests/electron/views/tab-stops/tab-stops-testing-content.test.tsx

Passes through telemetry for publishing unlike before.
Need telemetry on tab stop usage.
The main "fix" is around the fact that the payload for publish telemetry cannot be null. If it is, nothing is published. This is why key event telemetry already works.
Passed through events from UI so I can use the telemetry data factory. Seemed appropriate considering that's how we usually do things.

fix: fix telemetry for tab stops in android

---

src/electron/electron-builder/electron-builder.template.yaml

By default, electron-builder includes elevate.exe to allow the installer to make per-machine changes. Since we install only per-user changes, this functionality is not necessary, and by removing elevate.exe, we remove a potential attack surface. [Electron-builder docs](https://www.electron.build/generated/nsisoptions)
Reduce attack surface.

chore: Remove elevate.exe from Unified packages

---

yarn.lock

xmldom versions 0.4.0 and older do not correctly preserve system identifiers, FPIs or namespaces when repeatedly parsing and serializing maliciously crafted documents.
This may lead to unexpected syntactic changes during XML processing in some downstream applications.
Avoid vulnerability issues in our code.

chore (deps): Update xmldom to a non vulnerable version

---

src/injected/drawing-initiator.ts
src/injected/element-based-view-model-creator.ts
src/injected/selector-map-helper.ts
src/injected/selector-to-visualization-map.ts
src/injected/target-page-visualization-updater.ts
src/injected/visualization-needs-update.ts
src/tests/unit/tests/common/configs/web-visualization-configuration-factory.test.ts
src/tests/unit/tests/injected/drawing-initiator.test.ts
src/tests/unit/tests/injected/target-page-visualization-updater.test.ts
src/tests/unit/tests/injected/visualization-needs-update.test.ts

`TargetPageVisualizationUpdater` is responsible for tracking the current state of visualizers in a specific target page and responding to changes to the visualization store by checking whether a new store state mismatches a tracked visualizer state, triggering the appropriate `drawerInitiator` methods if any drawer needs to be updated to a new state.
The `previousVisualizationSelectorMapStates` it maintains is a mapping from `VisualizationType` to a `SelectorMap`, where ~a `SelectorMap` is a mapping from a particular step/requirement's `configId` to an `AssessmentVisualizationInstance` with information about which selector(s) are relevant to that requirement.~ edit: see comment below
The point where this map is *read* (L84, where it's passed it to `visualizationNeedsUpdate`) correctly …

fix(performance): avoid unnecessary drawer updates

---

src/ad-hoc-visualizations/needs-review/visualization.tsx
src/common/feature-flags.ts
src/fast-pass/fast-pass-provider.ts
src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-static-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/details-list-issues-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/fast-pass-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/fast-pass-left-nav.test.tsx
src/tests/unit/tests/background/feature-flags.test.ts

* Remove Needs review feature flag to always show Needs review FastPass test
* Pop-up text has already been updated to say "three [FastPass] tests" in #4123 
Addresses WI # 1835283
Screenshot of FastPass details view page with Needs review as the third FastPass step and no Needs review feature flag present in the Preview features panel

feat(fastpass-step-text-mvp): remove needs review feature flag

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/DetailsView/components/load-assessment-helper.ts
src/DetailsView/details-view-initializer.ts
src/background/actions/action-payloads.ts
src/background/stores/assessment-store.ts
src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
src/tests/unit/tests/DetailsView/components/load-assessment-helper.test.tsx
src/tests/unit/tests/background/stores/assessment-store.test.ts

Wires up the load assessment button, passing through data back into store.
Feature work.
TabId is included in the data for the payload so we can set the tab that sent the request as the current tab for the assessment after we load the data in. Also navigates to Overview, like resetting an assessment does.

feat(complete-save-load-assessment): wire up load assessment

---

Gruntfile.js
package.json
pipeline/unified/build-unsigned-release-packages.yaml

Currently, our `build-unified-<channel>` grunt commands build the unified product and then run electron-builder to create packed installers. This PR creates a new `pack-unified-<channel>` grunt command and shifts responsibility as follows:
- `build-unified-<channel>` builds the unified product and runs electron-builder to prepare the unpacked files in the drop folder
- `pack-unified-<channel>` runs electron-builder to pack the unpacked files from the drop folder into installers
With this PR, running `build-unified-<channel>` and then `pack-unified-<channel>` is equivalent to running the previous `build-unified-<channel>` command. As such, there is no net impact on our unsigned build pipeline.
We currently only sign the packed installers. Now that we want to sign the contents of those …

feat(android-signing-binskim): Separate unified installer creation from grunt build command

---

src/electron/main/main.ts
src/electron/window-management/platform-info.ts
src/tests/unit/tests/electron/window-management/platform-info.test.ts

Disable hardware acceleration when running on Linux as a workaround for an issue in the Parallels VM software.
Address issue #4140  
This is an unfortunately broad change, impacting all linux installations, including those not running in a VM. I'd love to scope it down to apply only when running in a Parallels VM (or even only in a VM), but found no javascript-friendly to make that determination. It might be possible to exec **systemd-detect-virt**, but that felt "heavy". Our graphics are very limited (display a screenshot with highlights), so disabling hardware acceleration doesn't seem to have a discernible impact on the product.
These are taken on the same machine running Ubuntu 20.04 in a Parallels VM:
Before | After
--- | --- …

fix: Add display workaround for linux in Parallels VM's

---

pipeline/unified/build-unsigned-release-packages.yaml

The unified pack command in the unsigned build currently has a condition to not run on Windows. The condition should have included `succeeded()`, as well. This PR corrects that.
If a previous build step fails, `pack:unified:all` shouldn't run.
n/a

chore: Add succeeded condition to pack:unified:all build step

---

pipeline/unified/channel/sign-release-package-windows.yaml

Now that we are signing all Windows files, we are ready to run the Codesign Validation task on them.
Validates that our EXEs and DLLs are signed.
[I validated that the task succeeds here](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=21710&view=results) (different branch; same yaml). 

feat(android-signing-binskim): Add codesign validation to Windows signing job

---

pipeline/unified/channel/sign-release-package-linux.yaml
pipeline/unified/channel/sign-release-package-mac.yaml
pipeline/unified/channel/sign-release-package-windows.yaml
pipeline/unified/channel/sign-release-package.yaml

A previous PR (#4160) removed the use of sign-release-package.yaml. Now that the build process has settled, this PR brings it back with a few fewer steps. This time, the Linux signed build uses sign-release-package.yaml, too!
Consolidate redundant build steps into a template.
[Test signed build with this update here.](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=21736&view=results) …

chore: Refactor signed build to use sign-release-package.yaml template (again)

---

src/electron/flux/action/android-setup-actions.ts
src/electron/platform/android/setup/steps/configuring-port-forwarding.ts
src/electron/platform/android/setup/steps/prompt-connected-start-testing.ts
src/electron/views/device-connect-view/components/android-setup/prompt-connected-start-testing-step.tsx
src/electron/views/device-disconnected-popup/device-disconnected-popup.tsx
src/electron/views/results/results-view.tsx
src/tests/unit/tests/electron/platform/android/setup/steps/configuring-port-forwarding.test.ts
src/tests/unit/tests/electron/platform/android/setup/steps/prompt-connected-start-testing.test.ts
src/tests/unit/tests/electron/views/device-disconnected-popup/__snapshots__/device-disconnected-popup.test.tsx.snap
src/tests/unit/tests/electron/views/device-disconnected-popup/device-disconnected-popup.test.tsx
src/tests/unit/tests/electron/views/results/__snapshots__/results-view.test.tsx.snap
src/tests/unit/tests/electron/views/results/results-view.test.tsx

Improve our disconnected device scenario. As called out in #3938, when the device connection is removed, ADB automatically removes port forwarding, which breaks assumptions in the reconnect code (which pre-dates the auto-configuration of port forwarding).
The PR basically consists of 3 pieces:
1. We already try to remove previously configured port forwarding, but we don't account for the error that gets thrown if we're removing a non-existent port. Fix this.
2. The notion of the "Start over" button is doomed to fail if we've really lost the connection, because we've lost our port forwarding and can only restore it by going through the device setup steps. I've updated the disconnected dialog to remove the "Start over" button.
3. When the user clicks the "Connect a new device" button, we …

fix: Improve disconnected device experience

---

docs/building-unified.md
src/content/test/custom-widgets/keyboard-interaction.tsx
src/content/test/repetitive-content/consistent-identification.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

Fixed a few typos after successful build relative to issue 4148.
* Assessment > Custom Widgets > Keyboard Interaction > Info and Examples > Why It Matters (keybord is missing an a)
* Assessment > Repetitive Content > Consistent identification > Info & Examples > Sufficent techniques (Sufficent is missing an i)
* Accessiblity is misspelled in \docs\building-unified.md
Milestone 1 - Project Checklist
No typos

chore: Fixed the typos in issue#4148

---

build.yaml

This PR limits the mac and windows unified e2e jobs to only run on the CI build, not the PR build.
We're having some unified e2e test unreliability issues which will be investigated in an upcoming feature. In the meantime. this should help PR velocity without losing all of the benefits of our e2e tests.
As discussed in the team retrospective.

chore: Limit mac and windows unified e2e jobs to CI build

---

.github/workflows/codeql.yml

This PR cleans up our CodeQL workflow to avoid errors/warnings we're seeing currently:
* Avoids triggering on non-main pushes (resolves errors we're seeing with new dependabot PRs)
* Runs on merge commit rather than HEAD^2 (fixes a warning in current build output)
* Removes unnecessary comments and unnecessary autobuild step (is a no-op for ts/js projects)
Fixes build errors with new dependabot PRs
n/a

chore(build): clean up errors/warnings in codeql workflow

---

.prettierignore

The save/load feature recently added some `.a11ywebassessment` files to our end to end tests. Prettier doesn't understand this file extension, so it throws some spurious errors during `yarn format:check`. This PR updates `.prettierignore` to ignore these files (they aren't intended to be human-readable).
I also sorted the list of ignored file extensions while I was here.
Before:
```
> yarn format:check
yarn run v1.22.10
$ prettier --config prettier.config.js --check "**/*"
Checking formatting...
src\tests\end-to-end\test-resources\saved-assessment-files\web@2.25.0-valid-mixed-results.a11ywebassessment[error] No parser could be inferred for file: src\tests\end-to-end\test-resources\saved-assessment-files\web@2.25.0-valid-mixed-results.a11ywebassessment …
```

chore: fix spurious prettier errors with .a11ywebassessment files

---

pipeline/unified/channel/sign-release-package-linux.yaml

This PR undoes the linux signing change from #4167 with slight organizational changes. A successful signed build [can be found here.](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=22344&view=results)
We found some issues with the ClearSign signed AppImage in release validation. This unblocks release.
Further investigation is required to determine if we can use ClearSign signing in the future.
I verified an AppImage from the signed build locally. …

fix: Revert linux signing to use detached signature

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/assessment-instance-details-column.scss
src/DetailsView/components/assessment-instance-edit-and-remove-control.scss
src/DetailsView/components/assessment-instance-selected-button.scss
src/DetailsView/components/base-left-nav.scss
src/DetailsView/components/failure-instance-panel.scss
src/common/components/cards/card-kebab-menu-button.scss
src/common/styles/high-contrast-override.scss
src/injected/styles/injected.scss
src/popup/Styles/popup.scss

#3272 calls out some issues in Edge in system HC modes. Upon further investigation, the same problems are also appearing in current production builds of Chrome (detailed status of the change in Chrome can be found [here](https://www.chromestatus.com/feature/5757293075365888#:~:text=Chrome%20Platform%20Status%20Feature%3A%20Forced%20colors%20mode%20Adds,a%20user-chosen%20limited%20color%20palette%20on%20the%20page.)). This PR fixes the specific issues that are called out in Edge, and updates the checks from the Edge-specific flag of `-ms-high-contrast` to the [new standard](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors) of `forced-colors`
Accessibility matters
The old and new results are identical to both Chrome and Edge
Highlights (images are slightly different …

fix: Respond to system HC modes

---

src/popup/Styles/popup.scss

The checkmark in the telemetry checkbox was not rendering properly in Edge (worked fine in Chrome) with black-themed Windows HC modes. Explicitly set the checkmark color to the CanvasText color to force proper rendering
HC Mode | Prod Chrome | Updated Chrome | Prod Edge | Updated Edge
--- | --- | --- | --- | ---
None | ![image](https://user-images.githubusercontent.com/45672944/119536534-0a198a00-bd3e-11eb-9de1-cad9180ef9aa.png) | ![image](https://user-images.githubusercontent.com/45672944/119536481-fa01aa80-bd3d-11eb-8cd9-21e4b510e6e9.png) | ![image](https://user-images.githubusercontent.com/45672944/119536412-ea826180-bd3d-11eb-9820-0cb1e9758299.png) | ![image](https://user-images.githubusercontent.com/45672944/119536359-d9d1eb80-bd3d-11eb-9bc5-ec99da6fdb82.png)
HC 1 | …

fix: Explicitly use CanvasText for HC checkbox check

---

src/DetailsView/components/details-view-command-bar.tsx

an extra prop was being passed to renderLoadAssessmentButton in the DetailsViewCommandBar.  This made the code more confusing to follow.
Cleaning up the code.

fix: remove unnecessary prop from renderLoadAssessmentButton

---

.github/dependabot.yml
package.json
yarn.lock

This PR undoes the electron-builder upgrade from #4237 and returns us to 22.9.1.
Our signed Mac builds are failing with electron-builder 22.10.5. This PR unblocks that build while we continue to investigate.
[You can find a successful signed build here](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=22653&view=results).

fix: Undo electron-builder upgrade to fix signed Mac build

---

src/injected/styles/injected.scss

The changes in #4253 weren't quite correct. They omitted a bit of scoping for the styles, and they introduced some inconsistency in how icons (especially the file bug icon) were represented in HC White mode. This corrects those errors.
Note how the fill in the "Before" column of HC White is inconsistent with other HC modes, making the icons kind of "splotchy". In the "After" column, the fill is the same color as the button, so the icon appearance is cleaner and consistent across all HC modes.
HC Mode | Before | After
None | ![image](https://user-images.githubusercontent.com/45672944/119560585-f6c7e800-bd58-11eb-9ba3-e04924f11ebf.png) | ![image](https://user-images.githubusercontent.com/45672944/119561312-dd736b80-bd59-11eb-89db-c216240fc3a0.png)
HC 1 | …

chore: Tweak HC icons and scoping

---

src/tests/end-to-end/tests/details-view/overview.test.ts

This is holding up some additional PRs due to the E2E tests failing in a scenario that wasn't accounted for in the initial PR.
Fix failing PR builds
The click selector for the LoadAssessmentDialog was a leftover from a previous test that we had copied from and we neglected to remove it, which was an oversight.  Because the validation piece was not complete the load assessment dialog was still rendered so the click selector worked properly.  Now that we're implementing the validation piece, the load assessment dialog doesn't exist when this test runs, causing the test to fail.

fix: E2E test for invalid data validation looking for element that doesn't exist

---

src/DetailsView/components/invalid-load-assessment-dialog.tsx
src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/end-to-end/tests/details-view/overview.test.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/invalid-load-assessment-dialog.test.tsx.snap

This incorporates the invalid data dialog into the E2E tests for the save and load assessment.
feature work

feat(save-load-validation): update E2E test to account for invalid data dialog

---

src/common/icons/icon.scss

The sass engine we use recently deprecated the use of `/` as a division operator in favor of `math.div`, and started spewing a bunch of deprecation warnings for our usages of `/` division in `icon.scss`.
[Documentation about the deprecation](https://sass-lang.com/documentation/breaking-changes/slash-div)
This PR fixes the deprecation warnings.
Fixes warning spam during `yarn build`
n/a

chore: migrate sass from slashes to math.div

---

src/tests/unit/tests/injected/visualization/svg-shape-factory.test.ts

`svg-shape-factory.test.ts` is written in terms of a `@uifabric/utilities` `IPoint` class, but the `svg-shape-factory.ts` implementation under test doesn't use fabric's `IPoint`, it uses our own `Point` type. This is a benign issue right now but will be broken in a future update to `@uifabric/utilities`.
Preempt a future build break
Noticed this during an overzealous lockfile regeneration while working on #4320

chore: fix Point vs IPoint type confusion in svg-shape-factory.test.ts

---

src/ad-hoc-visualizations/headings/visualization.tsx

This PR updates the rule used to gather heading instances in our ad-hoc visualization. There are two reasons to do this:
- the current implementation hangs in scenarios described in #4311 
- our assessment headings visualization is [already using a minimal custom rule](https://github.com/microsoft/accessibility-insights-web/blob/2988c8588d15b90bf5e30a0ec3cd5b6d6b5d5e4e/src/assessments/headings/test-steps/heading-function.tsx#L78). It feels like a good idea to use the same implementation for both visualizations.
validation: run against https://karanbirsingh.github.io/temp-snippets/microsoft/accessibility-insights-web/4311/single-level/
This PR addresses https://github.com/microsoft/accessibility-insights-web/issues/4311 
One alternative approach is to do nothing until a new release of …

fix: stop ad-hoc headings from crashing by reusing custom axe rule

---

src/scanner/axe-utils.ts
src/scanner/custom-rules/cues-rule.ts
src/scanner/custom-rules/custom-widget.ts
src/scanner/custom-rules/image-rule.ts
src/scanner/custom-rules/link-function.ts
src/scanner/custom-rules/link-purpose.ts
src/scanner/custom-rules/native-widgets-default.ts
src/scanner/custom-rules/text-alternative.ts
src/scanner/custom-rules/widget-function.ts
src/tests/unit/tests/scanner/axe-utils.test.ts
src/tests/unit/tests/scanner/custom-rules/cues-rule.test.ts
src/tests/unit/tests/scanner/custom-rules/link-function.test.ts
src/tests/unit/tests/scanner/custom-rules/link-purpose.test.ts
src/tests/unit/tests/scanner/custom-rules/native-widgets-default.test.ts
src/tests/unit/tests/scanner/custom-rules/widget-function.test.ts

Our `AxeUtils.getAccessibleText` accepted a `isLabelledByContext` boolean parameter which we always pass as `false` in our usage. We pass this as-is to `axe-core`'s `axe.commons.text.accessibleText`.
Unfortunately, `axe-core` changed the signature of `accessibleText` [two years ago](https://github.com/dequelabs/axe-core/pull/1163) to use an options object rather than a boolean second parameter, and our tests never caught it. Thankfully, by complete luck, passing `false` happens to be interpreted the same as an object which includes the property as false, and that's the only way we use it (because you'd get the `false` behavior if we were to ever pass `true`!)
This PR removes our support for the options entirely, since we don't use it, and adds an integration test similar to other …

chore: avoid benign call-signature-mismatch in axe.commons.text.accessibleText usage

---

Dockerfile
pipeline/e2e-test-from-docker.yaml

Our PR builds started failing with the Playwright 1.12.0 release and the corresponding release of a new `mcr.microsoft.com/playwright:bionic` image, which we use for docker/e2e tests in PR builds.
@karanbirsingh and I have done some root cause analysis but haven't narrowed down an exact cause yet. To work around the issue in the meantime, this PR reverts our builds to use a v1.11.0 docker image, which seems to prevent the issue.
Fix build breaks
n/a
- [n/a] (UI changes only) Verified usability …

chore(build): fix PR build failures with docker e2e false exit codes

---

packages/report/package.json

As per the instructions for validating the npmjs secret rotation, this bumps the patch version for the report so that we can release a new version of accessibility-insights-report to test that the rotation succeeded.
Compliance Feature Work

feat(web-compliance-21h1): bump report version to validate npmjs secret rotation

---

src/electron/common/unified-feature-flags.ts
src/tests/unit/tests/electron/common/unified-feature-flags.test.ts

Add feature flag for work on adding ATFAResults to Unified
Address WI 1853272
All the work for adding ATFAResults to Unified client will be done under a feature flag

feat(google-rules-mvp): add atfaResults feature flag in unified

---

docs/building-unified.md

* Minor updates to outdated text/references to Getting Started doc
* Added instructions for how to run dev version of Unified app with a modified version of [Accessibility Insights for Android Service](https://github.com/microsoft/accessibility-insights-for-android-service)
It was not immediately clear how to develop on the Unified app when working with a different or modified version of the Android Service.

docs: add instructions for running Unified app with modified Android Service

---

src/electron/platform/android/fetch-scan-results.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/platform/android/fetch-scan-results.test.ts

Updated fetch-scan-results.ts to determine which Accessibility Insights for Android Service API to call, based on the status of the atfaResults feature flag. 
* When the feature flag is enabled, it calls the v2 API.
* When the feature flag is disabled, it calls the original API (no version number).
Partially addresses WI 1853273
This is a follow-up to #4394, which handled reading the axe results from both v1 and v2 results formats. This PR updates the ScanResultsFetcher to call either of the two APIs in the Android Service, depending on whether the atfaResults feature flag has been enabled or disabled. The Android Service returns the proper data (v1 or v2) based on the API that is called.
- [n/a] (UI changes only) …

feat(google-rules-mvp): call Android Service API based on atfaResults feature flag

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
src/common/components/fix-instruction-processor.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/how-to-fix-card-row.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/rules-with-instances.test.tsx.snap
src/tests/unit/tests/injected/__snapshots__/fix-instruction-processor.test.tsx.snap
src/tests/unit/tests/injected/fix-instruction-processor.test.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/report-body.test.tsx.snap

This PR updates the list structure of the color contrast suggestions added in FixInstructionProcessor. Previously, the list structure looked something like:
- \<ul>
- \<li>
- The original CC message
- \<ul>
- \<li>
- The first CC suggestion
- \<ul>
- \<li>
- The second CC suggestion
Now, it looks more like:
- \<ul>
- \<li>
- The original CC message
- \<ul>
- \<li>
- The first CC suggestion
- \<li>
- The second CC suggestion
The change should have no visual impact, just AT impact. 
With the previous list structure, NVDA read,
>...list  with 1 items  •   Element has insufficient color contrast of 4.21 (foreground color: #0074d9, background color: #fff4c2, font size: 10.5pt (14px), font weight: normal). Expected contrast ratio of 4.5:1 Use foreground color: #006ece and the original …

fix: Improve list structure of color contrast suggestions to fix NVDA output

---

src/electron/platform/android/atfa-data-types.ts
src/electron/platform/android/atfa-scan-results-to-unified-results.ts
src/electron/platform/android/atfa-scan-results-to-unified-rules.ts
src/tests/unit/tests/electron/platform/android/scan-results-helpers.ts

#4406 added new fields for ATFA rules, but 2 of those fields were incorrect. The mistakes were
Field | Incorrect value | Correct value
checkClass (identifies test) | `AccessibilityHierarchyCheckResult.checkClass` | `AccessibilityCheckResult.checkClass`
type (identifies test status) | `AccessibilityHierarchyCheckResult.type` | `AccessibilityCheckResult.type`
Here's a result from the service, redacted to just the fields that we use--the checkClass and type are at the very end of the object:
```
{
"AccessibilityHierarchyCheckResult.element": {
"ViewHierarchyElement.accessibilityClassName": "android.widget.TextView",
"ViewHierarchyElement.boundsInScreen": {
"Rect.bottom": 505,
"Rect.left": 439,
"Rect.right": 641,
"Rect.top": 252
},
"ViewHierarchyElement.className": …
```

feat(google-rules-mvp): Correct incorrect field names

---

.github/dependabot.yml

This PR removes electron-builder from the dependabot ignore list.
Now that issue #4290 has been addressed, we want to keep electron-builder up to date.
PR #4284 downgraded electron-builder and paused future upgrades. Now that PR #4421 has fixed the underlying issue, we're fine to keep current with electron-builder again. 
[Example successful signed build with electron-builder 22.11.7](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=24021&view=results). …

chore: Stop ignoring new versions of electron-builder

---

src/common/components/cards/rich-resolution-content.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/rich-resolution-content.test.tsx.snap

Items in NeedsReview should use HowToCheck instructions instead of HowToFix instructions. Some of these instructions just settled today. 
Part of MVP feature
These screenshots show what gets displayed in the UI. The results were synthesized by manually changing the returned rules to demonstrate all of the HowToCheck options, so please ignore the Class name, Content description, and Text options:
Rule | Screenshot
--- | ---
ClassNameCheck | ![image](https://user-images.githubusercontent.com/45672944/124046832-b0a11c80-d9c7-11eb-9b16-dcf528c82e47.png)
ClickableSpanCheck | ![image](https://user-images.githubusercontent.com/45672944/124046924-e0e8bb00-d9c7-11eb-98e4-0504eb9b6cf4.png)
DuplicateClickableBoundsCheck | ![image](https://user-images.githubusercontent.com/45672944/124046947-f65de500- …

feat(google-rules-mvp): Use latest HowToCheck text

---

Dockerfile

Node 14.17.1 is no longer available for the docker installation. Bump to 14.17.2 (which contains 2 security patches)
Unblock the PR buid

chore: Update Docker node version to 14.17.2 (security fix) to unblock PR build

---

src/electron/platform/android/atfa-scan-results-to-unified-results.ts
src/electron/platform/android/axe-scan-results-to-unified-results.ts
src/electron/platform/android/rule-information-provider-type.ts
src/electron/platform/android/rule-information-provider.ts
src/electron/platform/android/unified-result-builder.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/platform/android/rule-information-provider.test.ts

Exclude Axe ColorContrast rules from NeedsReview tab if ATFA rules are enabled, as ATFA has its own color contrast rule that we believe to be less noisy. Also includes some strict null checks that were necessary to get `yarn fastpass` to work as expected. These are called out individually in the review.
Requirement from the spec

feat(google-rules-mvp): Hide axe color contrast when ATFA rules are enabled

---

Dockerfile

Letting Docker use any version of nodejs created a breaking change in nodejs 16.3.0, but pinning to 14.17.1 broke the build pipeline when 14.17.1 was deprecated and replaced by 14.17.2. This PR represents a "middle ground" option--we pin the major version at 14, but let the minor and patch versions float.
(Hopefully) make the build pipeline more resilient to new releases of nodejs
Local docker image sets up successfully with this change.
- [n/a] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, …

chore: Pin docker to nodejs version 14.* instead of 14.17.2

---

.github/workflows/ci.yml

This updates the trigger configuration for our new GitHub Actions CI/PR build to avoid double-triggering for pushes to PRs that originate from in-upstream branches.
The main impact of this is that we'll stop double-triggering PR builds for each push to a dependabot PR. This will also fix the spurious failures in the codeql job on some Dependabot PRs ([example](https://github.com/microsoft/accessibility-insights-web/pull/4419/checks?check_run_id=2945121676))
The two alternatives I considered were what this PR does (`push: { branches: main }`) vs `push: { branches-ignore: dependabot/* }`.
Both solve the issue with the spurious dependabot PR codeql failures.
The differences are:
* The latter would still involve double-triggering the PR build for any PRs whose base branch is pushed to …

chore: fix codeql GitHub Action failures in dependabot PRs

---

src/ad-hoc-visualizations/color/visualization.tsx
src/assessments/color/test-steps/use-of-color.tsx
src/injected/styles/injected.scss

All docs/resources have the word "grayscale" spelled with an "a", but the visual toast notification in AI-web had it spelled using an "e".  For consistency, I have updated that visualization as well as a couple of variables in the code that had it spelled differently.
Spelling consistency in our product.
I looked into the docs and also the assessment instructions to see what spelling was most commonly used.  This visualization was the only public place in the repo that used the "e" spelling, so I changed it to match the rest.

fix: spelling consistency of "grayscale"

---

package.json
src/injected/analyzers/analyzer-provider.ts
src/injected/analyzers/base-analyzer.ts
src/injected/analyzers/rule-analyzer.ts
src/injected/analyzers/tab-stops-analyzer.ts
src/tests/unit/common/debounce-faker.ts
src/tests/unit/stubs/q-stub.ts
src/tests/unit/tests/background/injector-controller.test.ts
src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
tsconfig.strictNullChecks.json
yarn.lock

`q` is a library that provides a standalone implementation of Promises. We've been gradually switching from it to native Promises for some time now. This PR finishes that work and removes the dependency on `q`.
Most of the interesting dependencies on Q were removed as part of #4155. The remaining interesting dependency was in `tab-stops-analyzer`, which used `Q.Promise`'s `progress()` callback in a way which isn't supported by native promises.
The only actual callback passed to the progress callback was the tab stops analyzer's own `onProgress` handler, which then calls out to `window.setTimeout` to implement some custom debouncing logic. This PR ripped out the `onProgress` implementation based on Q and replaced it with a more direct use of callbacks. While I was having to redo some of …

chore: remove dependency on q

---

src/tests/end-to-end/common/browser.ts

This wraps the `close` method in the browser class with catch statement which will suppress failures.
Seeing transient issues in our E2E due to recent playwright updates with this specific function.
I chose this approach because it touches the least amount of files; I could create a new method called `closeSafely` but all signatures would need to change. Figured, renaming to unsafeClose for the function details with a comment would be a better approach.

fix: suppress failures on browser close for E2E tests

---

package.json
src/tests/unit/tests/electron/platform/android/__snapshots__/mock-adb.test.ts.snap
yarn.lock

This incorporates version 1.4.0 of the Android service into the Unified client. As long as the `atfaResults` feature flag is false, the client will continue to receive and display the same results as before.
Feature requirement
I'm not really sure if we want to lock this version, since the releases are infrequent and tightly controlled. I kept the existing pattern for now...

feat(google-rules-mvp): Pick up latest version of Android service

---

package.json
yarn.lock

#4447 removed our dependency on `q` but missed the corresponding dependency on `@types/q`. This drops the obsolete types package.
Remove unnecessary dependency
n/a

chore: remove @types/q

---

src/electron/common/unified-feature-flags.ts
src/tests/unit/tests/electron/common/unified-feature-flags.test.ts

Enable ATFA rules by default
Feature requirement

feat(google-rules-mvp): Enable ATFA results by default

---

.github/workflows/ci.yml

The artifact names our GitHub Actions CI builds were using for uploads in the chunked e2e jobs were using an outdated value for the chunk index as part of the name, so in practice, they were showing up with names like `e2e-unified-tests--results.zip` instead of the intended `e2e-unified-tests-1-results.zip`.
This has the particularly nasty side effect that only one of the chunks' logs/results actually got uploaded at all, since each chunk gets the same name.
This PR fixes them to be consistent with how the job titles are formed.
Be able to get results from each chunk of e2e tests
n/a …

chore: fix CI build artifact names from chunked jobs

---

.swcrc
.vscode/launch.json

`swc` omits source map information by default, which meant that our test output was giving wrong information whenever Jest wanted to emit a stack or a source snippet for debugging purposes, and also meant that VS Code had trouble with interpreting breakpoints accurately.
This PR enables inline source maps in our `.swcrc`. This has a substantial negative impact on test runtime (on my machine, it bumps the time for a full `yarn test` from 3m05s to 4m15s), but I think being able to debug failures accurately is more important and this doesn't impact PR build time - even chunked, both the unified and web e2e tests are still long poles in comparison).
I also included a minor fix to `.vscode/launch.json` to explicitly specify a `cwd` property in node/launch configs. Previously, if your VS Code …

chore(test): fix inaccurate line/source info in test output

---

src/injected/styles/injected.scss

Specify HC overrides of SVG color in dialog title bar, so that the dialog's close button gets displayed correctly in system HC modes.
Addresses #4281 
HC Mode | Dialog Caption
--- | ---
None | ![image](https://user-images.githubusercontent.com/45672944/126408906-ec0cfacd-06c5-43a2-82b3-a4e97b722d9c.png)
HC 1 | ![image](https://user-images.githubusercontent.com/45672944/126408866-7fcd0caa-d554-4ae5-9428-61dc5119b351.png)
HC 2 | ![image](https://user-images.githubusercontent.com/45672944/126408834-68577eac-7d06-4786-a89a-7b253696c292.png)
HC Black | ![image](https://user-images.githubusercontent.com/45672944/126408786-a94e4611-53af-4328-9867-65ce32e77d54.png)
HC White | ![image](https://user-images.githubusercontent.com/45672944/126408806-6e18953b-cdcd-4503-bbd7-cd5fc48f39f7.png)
Extension …

fix: Show dialog cancel buttons in system HC modes

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
src/common/components/cards/card-kebab-menu-button.scss
src/common/components/cards/instance-details-footer.scss

Fix a couple of HC problems in card footer. Root problem is that we aren't specifying HC stroke and fill colors, so the browser is choosing unfortunate values on our behalf. Prior to this change, none of the SVG's on this page would be visible in any Windows HC modes.
Addresses issue #4326 
HC Mode | Highlight Hidden | Highlight Visible | More Actions
--- | --- | --- | ---
None | ![image](https://user-images.githubusercontent.com/45672944/126401909-95f8b1f9-bdc2-4545-807e-bd3f2bdd56e5.png) | ![image](https://user-images.githubusercontent.com/45672944/126401932-28ba312e-599c-4495-929c-4b6fd56c0a19.png) | ![image](https://user-images.githubusercontent.com/45672944/126401957-81398068-7f03-4a7c-9e1a-e1adba18ff5b.png)
Extension HC mode | …

fix: Specify stroke color for SVG's in HC modes

---

src/injected/styles/injected.scss

This is a reworking of #4509, which failed to fix #4281. My best theory is that I had some file caching issue when testing #4509 locally. #4509 scoped SVG's in forced-color mode to the inspect dialog title bar; this expands it to all of the SVG's inside the inspect dialog. It might be possible to optimize out some override steps.
Address #4281 
Screenshots include the entire inspect dialog, to minimize the risk of unintended side effects
HC Mode | Dialog
--- | ---
None | ![image](https://user-images.githubusercontent.com/45672944/127412205-440fc0a1-1b56-4188-8546-e63699886782.png)
App in HC | ![image](https://user-images.githubusercontent.com/45672944/127412248-cff79ea0-6a36-4fc3-bffc-d4bb101b39f5.png)
OS in HC 1 | ![image](https://user-images.githubusercontent.com/45672944/127411931-65806 …

fix: Fix cancel button in inspect dialog in HC modes (2nd attempt)

---

yarn.lock

This updates to use the latest version of plist, which removes the dependency on xmldom that was causing a security alert.
Security fix.

chore: xmldom vulnerability fix

---

src/common/feature-flags.ts
src/tests/unit/tests/background/feature-flags.test.ts

This PR adds the `exportReportJSON` feature flag. It is not yet used.
To support future PRs for this feature
A subsequent PR will put this feature flag to use

feat(download-report-json): Add exportReportJSON feature flag

---

pipeline/scripts/zip-mac-folder.js

Update the shell command that zips the mac folder during release to use passed `args` instead of dynamically generating the entire command to be interpreted by the shell. 
Identified by CodeQL, ruleID `js/shell-command-injection-from-environment`
Dynamically constructing a shell command with values from the local environment, such as file paths, may inadvertently change the meaning of the shell command. Such changes can occur when an environment value contains characters that the shell interprets in a special way, for instance quotes and spaces. This can result in the shell command misbehaving, or even allowing a malicious user to execute arbitrary commands on the system.

fix: update mac folder zip command to use passed arguments for paths

---

Dockerfile

This is a workaround for `deb.nodesource` certificates being expired on Linux machines.  This updates the certs on the machine before installing other dependencies.
workaround for https://github.com/nodesource/distributions/issues/1266 so our linux builds will run successfully

fix: update Dockerfile so it can access nodesource

---

src/DetailsView/components/export-dialog.tsx
src/DetailsView/components/export-dropdown.tsx
src/report-export/report-export-service-provider-impl.ts
src/report-export/services/code-pen-report-export-service.tsx
src/report-export/services/html-report-export-service.ts
src/report-export/services/json-report-export-service.ts
src/report-export/types/report-export-service.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/export-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/export-dropdown.test.tsx.snap
src/tests/unit/tests/DetailsView/components/export-dialog.test.tsx
src/tests/unit/tests/DetailsView/components/export-dropdown.test.tsx

In order to add the export to JSON option, this PR introduces `ExportDropdown` and uses it in the `ExportDialog`. When multiple export options are available, `ExportDropdown` replaces the ordinary Export button and provides a menu with a list of export options on click. Some other notes:
- To address an accessibility concern, `ExportDropdown` replaces the split button in the current export to Codepen preview feature
- `ExportDropdown` is modelled after `StartOverDropdown`
- `ReportExportService` is refactored to apply to all forms of exporting--HTML, Codepen, and now JSON--rather than just Codepen. As such, `HtmlReportExportService` and `JsonReportExportService` are introduced and `CodepenReportExportService` is updated
- The "to JSON" option does not yet do anything
- All uses of the …

feat(download-report-json): Introduce ExportDropdown with toJSON option and use it in ExportDialog

---

src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/export-dialog-with-local-state.tsx
src/DetailsView/components/export-dialog.tsx
src/DetailsView/components/export-dropdown.tsx
src/DetailsView/components/report-export-component.tsx
src/DetailsView/components/report-export-dialog-factory.tsx
src/electron/views/results/components/reflow-command-bar.tsx
src/report-export/report-export-service-provider.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/export-dialog-with-local-state.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/export-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/export-dropdown.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-component.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-dialog-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/export-dialog-with-local-state.test.tsx
src/tests/unit/tests/DetailsView/components/export-dialog.test.tsx
src/tests/unit/tests/DetailsView/components/export-dropdown.test.tsx
src/tests/unit/tests/DetailsView/components/report-export-component.test.tsx
src/tests/unit/tests/DetailsView/components/report-export-dialog-factory.test.tsx
src/tests/unit/tests/electron/views/results/components/__snapshots__/reflow-command-bar.test.tsx.snap
src/tests/unit/tests/electron/views/results/components/reflow-command-bar.test.tsx
src/tests/unit/tests/report-export/report-export-service-provider.test.tsx

This PR follows up on #4754 to only show the new to JSON export option in assessment, not fastpass. To accomplish this, `ExportDropdown` was refactored to expect a list of currently applicable `ReportExportServices` rather than a `ReportExportServiceProvider`. `ReportExportServiceProvider` was updated to provide lists of `ReportExportServices` for FastPass and Assessment. Props/deps were updated such that `ReportExportServiceProvider` is now passed down only until the point at which `ExportDialog` diverges for FastPass and Assessment (specifically in `ReportExportDialogFactory` for web and `ReportExportComponent` for unified). At this point, it is used to generate the appropriate list of `ReportExportServices`, which is then passed through until it is used in `ExportDialog` and …

feat(download-report-json): Only show to JSON export option in assessment

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/DetailsView/components/export-dialog.tsx
src/common/extension-telemetry-events.ts
src/common/telemetry-data-factory.ts
src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
src/tests/unit/tests/DetailsView/components/export-dialog.test.tsx
src/tests/unit/tests/common/telemetry-data-factory.test.ts

This PR updates the telemetry logged on report export click in two ways:
1. `exportResultsService` is added to the event with potential values of `html`, `json`, and `codepen`
2. `exportResultsData` is removed from the event (read more in Context)
Telemetry updates for the json export feature
In theory, `exportResultsData` was recording the length of the downloaded html string. In reality, it had a bug which caused it to record the length of the _previously downloaded_ html string from that session, which was usually 0. This PR fixes that bug by removing the value entirely (per discussion with @ferBonnin, we don't need that data).
- [n/a] (UI changes only) Verified usability …

feat(download-report-json): Modify export telemetry to include export service

---

src/DetailsView/components/adhoc-tab-stops-test-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-tab-stops-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/adhoc-tab-stops-test-view.test.tsx

This adds additional static content to the Adhoc Tabstop. Visual helper toggle will be added in a later PR.

feat(tab-stops-details-view): add static tabstops content 

---

src/background/telemetry/app-insights-telemetry-client.ts
src/tests/unit/tests/background/telemetry/app-insights-telemetry-client.test.ts

I noticed that we had a typo where we dropped the final 'e' from "ExtendedEnvelope". This PR simply adds the missing character to the type and its uses in the code.
Spellling thingz write maiks cohd easyer two reed

chore: Fix spelling error

---

src/DetailsView/tab-stops-requirement-instances-collapsible-content.tsx
src/DetailsView/tab-stops-requirements-with-instances.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/tab-stops-requirement-instances-collapsible-content.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/tab-stops-requirements-with-instances.test.tsx.snap
src/tests/unit/tests/DetailsView/components/tab-stops-requirement-instances-collapsible-content.test.tsx
src/tests/unit/tests/DetailsView/components/tab-stops-requirements-with-instances.test.tsx

This wires up the remove instance icon to the store. It also ensure that if no failure instances exist for a requirement that the requirement doesn't render.
Feature work

feat(tab-stops-details-view): Wire up remove instance button

---

src/DetailsView/components/adhoc-tab-stops-test-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-tab-stops-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/adhoc-tab-stops-test-view.test.tsx

This shows the target page changed view when the target page is navigated away from. This brings the AdhocTabStopsTestView to parity with the other adhoc test views.
feature work

feat(tab-stops-details-view): add TargetPageChangedView to AdhocTabStopsTestView

---

src/DetailsView/components/next-requirement-button.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/next-requirement-button.test.tsx.snap

This PR adds an aria label to the chevron icon on the next requirement button.  This adds the word "next" to what screen readers say aloud when describing the next requirement button. For example, screen readers now say "xyz next button" instead of "xyz button." This allows users who use a screen reader to become apprised of the same information as visual users; the word "next" provides the same indication as the chevron visually does. 
Addresses issue #4811 
Adding the aria label to the chevron was preferable over adding an aria label to the button itself because of varying NVDA behavior.  If the aria label was on the button, upon clicking the button, NVDA would then read aloud the aria label of the new next requirement button that was loaded on the following page.  JAWS, however, would …

fix: Add aria label to chevron on next requirement button, so next is read aloud

---

src/assessments/semantics/test-steps/headers-attribute.tsx
src/injected/visualization/table-headers-formatter.ts
src/tests/unit/tests/injected/visualization/__snapshots__/table-headers-formatter.test.ts.snap

This PR de-crowds the labeling in the target page. Now, only the text "th" or "td" is displayed by the visual helper. This makes the visual helper still useful with tightly-spaced data tables. This PR also removes the "element" line of this section of the report, since it was duplicating the exact information already listed under "snippet."
Addresses issue #4027 
Considered the suggestion to add all <th> elements to the instances list.  Modified the instructions instead, which achieves the same effect with less clutter on the page. 
Image showing table with smaller labels highlighting two of the table elements; labels are all fully legible and at most, cover the element they are labeling, not the surrounding elements any more.  
Image showing same story as previous image, but with three …

fix: Make table headers labels smaller, reword instructions

---

src/DetailsView/components/assessment-instance-edit-and-remove-control.tsx
src/DetailsView/components/failure-instance-panel-control.tsx
src/DetailsView/components/manual-test-step-view.tsx
src/DetailsView/components/tab-stops/tab-stops-test-view-controller.ts
src/DetailsView/components/tab-stops/tab-stops-view-actions.ts
src/DetailsView/components/tab-stops/tab-stops-view-store-data.ts
src/DetailsView/components/tab-stops/tab-stops-view-store.ts
src/common/stores/store-names.ts
src/common/types/captured-instance-action-type.tsx
src/tests/unit/tests/DetailsView/components/assessment-instance-edit-and-remove-control.test.tsx
src/tests/unit/tests/DetailsView/components/failure-instance-panel-control.test.tsx
src/tests/unit/tests/DetailsView/components/manual-test-step-view.test.tsx
src/tests/unit/tests/DetailsView/components/tab-stops/tab-stops-test-view-controller.test.tsx
src/tests/unit/tests/DetailsView/components/tab-stops/tab-stops-view-store.test.ts

Creates a store to be used in details view to manage state of the tab stops view.
feature work.
This is a new approach to a kind of problem where we usually have stateful components that pass state-management functions down to children. This would be complicated and messy in this case (although possible) since there are multiple places that the failed instance panel could open from (not included in this PR).
In this case, we create a store that only exists in details view and thus our components can be simpler and not do any state management themselves.
The controller is a more palatable approach than interacting with actions directly (don't want to create confusion with our usage of action-message-creators).
The usage of this in UI components will be in a future PR.

feat(tab-stops-details-view): create tab stops view store, actions, and controller

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/assessment-instance-details-column.scss

This PR adds the white-space: normal style to information displayed in the details view in tables during an assessment.  This makes it so that at a high zoom level, instead of being truncated with "..." like before, information in a table cell that extends past one line will now wrap and continue in the same cell on the next line.  This makes that content visible to users who are using a high zoom level. 
Addresses ADO Trusted Tester bug #1883866.
Assessment test steps that render instances in a table either do so through generating an AssessmentInstanceDetailsColumn or by using the PropertyBagColumnRendererFactory.  So, styling here needed to be updated in two spots to account for the two different places we generate content. 
Pic above: The issue mentioned in the trusted tester bug, …

fix: Adjust styling so text is visible at high zoom level

---

src/DetailsView/components/tab-stops/failed-instance-panel.tsx
src/DetailsView/components/tab-stops/tab-stops-failed-instance-panel.tsx
src/DetailsView/components/tab-stops/tab-stops-view-actions.ts
src/DetailsView/components/tab-stops/tab-stops-view-store.ts
src/tests/unit/tests/DetailsView/components/tab-stops/__snapshots__/failed-instance-panel.test.tsx.snap
src/tests/unit/tests/DetailsView/components/tab-stops/__snapshots__/tab-stops-failed-instance-panel.test.tsx.snap
src/tests/unit/tests/DetailsView/components/tab-stops/failed-instance-panel.test.tsx
src/tests/unit/tests/DetailsView/components/tab-stops/tab-stops-failed-instance-panel.test.tsx
src/tests/unit/tests/DetailsView/components/tab-stops/tab-stops-view-store.test.ts

Creates the failed instance panel for tab stops view.
Feature work
Does not include wiring this up (future PR). Screen caps below of what it looks like when wired up.

feat(tab-stops-details-view): added failed instance panel

---

src/DetailsView/components/adhoc-tab-stops-test-view.tsx
src/DetailsView/components/details-view-content.tsx
src/DetailsView/components/tab-stops/tab-stops-requirements-table.tsx
src/DetailsView/components/test-view-container.tsx
src/DetailsView/details-view-body.tsx
src/DetailsView/details-view-container.tsx
src/DetailsView/details-view-initializer.ts
src/DetailsView/tab-stops-requirement-instances-collapsible-content.tsx
src/DetailsView/tab-stops-requirements-with-instances.tsx
src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-tab-stops-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/tab-stops-requirements-with-instances.test.tsx.snap
src/tests/unit/tests/DetailsView/components/adhoc-tab-stops-test-view.test.tsx
src/tests/unit/tests/DetailsView/components/tab-stops-requirement-instances-collapsible-content.test.tsx
src/tests/unit/tests/DetailsView/components/tab-stops-requirements-with-instances.test.tsx
src/tests/unit/tests/DetailsView/components/tab-stops/tab-stops-requirements-table.test.tsx
src/tests/unit/tests/DetailsView/details-view-body.test.tsx
src/tests/unit/tests/DetailsView/details-view-content.test.tsx
src/tests/unit/tests/DetailsView/store-mocks.ts

Wires up the tab stops failed instance panel.
Feature work.
This uses the work in my previous two PRs and actually uses them.

feat(tab-stops-details-view): wiring up failed instance panel

---

src/DetailsView/components/tab-stops-failed-instance-section.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/tab-stops-failed-instance-section.test.tsx.snap
src/tests/unit/tests/DetailsView/components/tab-stops-failed-instance-section.test.tsx

This fixes an issue that was causing the failure instance panel to show up when a requirement was failed but no instances were added.
feature work

feat(tab-stops-details-view): fix failure instance panel displaying header when it shouldn't

---

src/DetailsView/components/action-and-cancel-buttons-component.tsx
src/DetailsView/components/tab-stops/failed-instance-panel.tsx
src/DetailsView/components/tab-stops/tab-stops-choice-group.tsx
src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/end-to-end/tests/details-view/tabstops.test.ts
src/tests/unit/tests/DetailsView/components/tab-stops/__snapshots__/failed-instance-panel.test.tsx.snap
src/tests/unit/tests/DetailsView/components/tab-stops/__snapshots__/tab-stops-choice-group.test.tsx.snap

This adds an E2E test to add, edit, and remove a failure instance in tab stops.
Feature work
I considered breaking the single test into multiple tests. I decided to leave it as one large test because the flow made sense and reduced the need for a lot of duplicate (and very slow) setup steps. As such it first adds, then edits, then removes the same failure instance within a single test.

feat(tab-stops-details-view): E2E tests to add, edit, and remove a failure instance

---

src/DetailsView/components/adhoc-tab-stops-test-view.scss
src/DetailsView/components/adhoc-tab-stops-test-view.tsx
src/DetailsView/components/static-content-common.scss
src/DetailsView/components/tab-stops/tab-stops-requirement-table.scss
src/DetailsView/components/tab-stops/tab-stops-requirements-table.tsx
src/DetailsView/tab-stops-requirement-instances-collapsible-content.scss
src/DetailsView/tab-stops-requirement-instances-collapsible-content.tsx
src/common/components/collapsible-component.scss
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-tab-stops-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/tab-stops-requirement-instances-collapsible-content.test.tsx.snap
src/tests/unit/tests/DetailsView/components/tab-stops/__snapshots__/tab-stops-requirements-table.test.tsx.snap

fit and finish for the new tab stops details view.
feature work.
Left is before and right is after changes for the screen grab below.

feat(tab-stops-details-view): fit and finish of UI

---

src/DetailsView/components/nav-link-button.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/nav-link-button.test.tsx.snap
src/tests/unit/tests/DetailsView/components/nav-link-button.test.tsx

Currently, we set aria-current="page" on the left nav bar button for the currently selected page. This is right and proper. Unfortunately, the Orca screen reader ignores this setting in both the Web and Android products. To improve the user's experience, this PR replaces the use of aria-current with an aria-label to simulate the proper reading behavior. 
Addresses accessibility bug in Linux.
I considered leaving the aria-current value as-is, but that results in a double reading of current page from non-Orca screen readers.

fix: Use aria-label on NavLinkButton to improve Orca reading behavior

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-baseline-aware-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
src/common/components/cards/fix-instruction-color-box.scss
src/common/components/fix-instruction-panel.scss
src/reports/components/outcome.scss
src/reports/components/report-sections/details-section.scss

Currently, we use a screen-reader-only class that makes elements offscreen and 1px x 1px. Unfortunately, shortening the element's width to 1px causes the Orca screen reader to behave in an undesirable manner wherein it reads one word at a time and re-reads the element type with each word. To fix this, this PR removes width: 1px from the screen-reader-only class. Instead, clip-path is used to ensure the element is not visible.
Addresses accessibility issue in AI-Android (and AI-Web) on Linux.
I considered simply eliminating width since the class already sets left:-10000px, but decided to add the clip-path as a redundancy. 
This should have no visible impact and no impact to other screen readers' behavior.

fix: Modify screen-reader-only class to improve Orca's reading behavior

---

src/background/actions/action-creator.ts
src/background/actions/visualization-actions.ts
src/background/actions/visualization-scan-result-actions.ts
src/background/stores/tab-context-store-hub.ts
src/background/stores/visualization-scan-result-store.ts
src/common/types/store-data/visualization-scan-result-data.ts
src/tests/unit/common/visualization-scan-result-store-data-builder.ts
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts

This will cause data to be removed when a test in fastpass is started over.
Feature work.
Did some smoke testing for a bunch of tests to ensure this doesn't break anything.
Also included is removing an action is not being used.

feat(tab-stops-details-view): start over removes data from scan result store

---

src/assessments/adaptable-content/test-steps/resize-text.tsx

This fix updates the display resolution sizes in the instructions for Adaptable Content > Resize Text. 
Outdated display resolution text.
Updated text, changed for testing consistency.

fix: change resize text display resolution

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-baseline-aware-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
src/DetailsView/components/details-view-overlay/settings-panel/settings-panel.scss
src/DetailsView/components/issue-filing-dialog.scss
src/issue-filing/services/azure-boards/azure-boards-settings-form.tsx
src/issue-filing/services/github/github-issue-filing-service.tsx
src/tests/unit/tests/issue-filing/services/azure-boards/__snapshots__/azure-boards-settings-form.test.tsx.snap
src/tests/unit/tests/issue-filing/services/github/__snapshots__/github-issue-filing-service.test.tsx.snap

Currently, we set the placeholder value of our azure boards and github issue filing TextFields to be an example URL. Unfortunately, the Orca screen reader ignores these placeholder values. To improve the experience for Linux screen reader users, this PR removes the placeholder values and replaces them with "example: \<url>" text beneath the TextFields. 
GitHub in the issue filing popup:
Azure Boards in the settings panel:
Addresses accessibility issue.
- I considered leaving the placeholder and just adding on the URL as an aria-description. This worked alright with Orca, but then caused other platforms' screen readers to read both the placeholder and the aria-description.
- I considered not setting the TextField's aria-describedby to be the new span, and honestly I'm still on the fence …

fix: Replace issue filing URL placeholders with separate label to improve Orca behavior

---

src/DetailsView/components/generic-toggle.scss
src/popup/Styles/popup.scss

Change text colors from `secondary-text` to `primary-text` to meet the minimum contrast ratio of 3:1 when links are found in text blocks. Using `primary-text` provides a contrast ratio of 3.345:1 between the surrounding text and link text colors.
Fixes #4928 
Changed the text color for descriptions of `GenericToggle`. This additionally affects the description text in "Enable high contrast" under the settings panel, as well as any descriptions for the toggles under preview features. I decided to go with this, rather than selectively changing the text in the areas with accessibility issues, so the UI looks more consistent (same text color for toggle descriptions throughout) and prevents similar accessibility issues in the future.
Screenshots of changes in affected areas:
| Before changes  | …

fix: link-in-text-block accessibility issue

---

src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/report-export-dialog-factory.tsx
src/DetailsView/components/should-show-report-export-button.ts
src/ad-hoc-visualizations/issues/visualization.tsx
src/ad-hoc-visualizations/tab-stops/visualization.tsx
src/common/configs/visualization-configuration.ts
src/tests/unit/tests/DetailsView/components/report-export-dialog-factory.test.tsx
src/tests/unit/tests/DetailsView/components/should-show-report-export-button.test.ts

This PR adds the `export result` button to the tab stops view as well as persisting the button in automated checks.
Feature 1872889.
a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.

feat(tabstops-report): add export button to tab stops

---

src/background/actions/action-hub.ts
src/background/actions/needs-review-card-selection-action-creator.ts
src/background/actions/needs-review-card-selection-actions.ts
src/background/actions/needs-review-scan-result-action-creator.ts
src/background/actions/needs-review-scan-result-actions.ts
src/background/stores/needs-review-card-selection-store.ts
src/background/stores/needs-review-scan-result-store.ts
src/background/stores/tab-context-store-hub.ts
src/background/tab-context-factory.ts
src/common/messages.ts
src/common/stores/store-names.ts
src/common/types/store-data/needs-review-card-selection-store-data.ts
src/common/types/store-data/needs-review-scan-result-data.ts
src/injected/main-window-initializer.ts
src/tests/unit/tests/background/actions/action-hub.test.ts
src/tests/unit/tests/background/actions/needs-review-card-selection-action-creator.test.ts
src/tests/unit/tests/background/actions/needs-review-scan-result-action-creator.test.ts
src/tests/unit/tests/background/stores/needs-review-card-selection-store.test.ts
src/tests/unit/tests/background/stores/needs-review-scan-result-store.test.ts
src/tests/unit/tests/background/stores/tab-context-store-hub.test.ts
src/tests/unit/tests/background/tab-context-factory.test.ts

This adds two stores, NeedsReviewScanResultStore and NeedsReviewCardSelectionStore. These will be used to independently store information for Needs Review, rather than reusing the UnifiedScanResultStore and CardSelectionStore that is being shared with Automated Checks.
Feature work, we need this data persistence to be separate to enable the report to always be able to export Automated Checks data, without it being overwritten by Needs Review data.
There is a lot of context that went into this decision. We considered going the route of turning the existing UnifiedScanResultStore into a dictionary with keys for each test type. We also considered having multiple instances of the UnifiedScanResultStore. Due to a number of technical and time constraints, we decided ultimately that our best …

feat(tabstops-report) add NeedsReviewScanResultStore and NeedsReviewCardSelectionStore

---

src/DetailsView/components/adhoc-tab-stops-test-view.tsx
src/DetailsView/components/tab-stops-failed-instance-section.tsx
src/DetailsView/details-view-initializer.ts
src/reports/components/fast-pass-report.tsx
src/reports/components/report-sections/fast-pass-results-title-section.tsx
src/reports/fast-pass-report-html-generator.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-tab-stops-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/tab-stops-failed-instance-section.test.tsx
src/tests/unit/tests/reports/components/__snapshots__/fast-pass-report.test.tsx.snap
src/tests/unit/tests/reports/components/fast-pass-report.test.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/fast-pass-results-title-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/fast-pass-results-title-section.test.tsx
src/tests/unit/tests/reports/fast-pass-report-html-generator.test.tsx

This PR makes a few pieces of incremental progress building out the FastPassReport. It:
- Adds headers for the Automated checks and Tab stops sections
- Adds tab stops failures to the report
- Fixes the expand/collapse behavior of the automated checks instances
Some minor refactoring was required to achieve this.
Screenshot:
Tab stops report feature
This is just incremental progress. Things out of scope:
- All unmentioned aspects of the FastPassReport
- Expand/collapse behavior not fully functional for tab stops failures
- Only tab stops failures with failed instances are displayed

feat(tabstops-report): Add tab stops failures to FastPassReport

---

src/ad-hoc-visualizations/issues/visualization.tsx
src/ad-hoc-visualizations/needs-review/visualization.tsx
src/background/actions/action-creator.ts
src/background/actions/needs-review-scan-result-actions.ts
src/background/actions/unified-scan-result-actions.ts
src/background/stores/needs-review-scan-result-store.ts
src/background/stores/unified-scan-result-store.ts
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/stores/needs-review-scan-result-store.test.ts
src/tests/unit/tests/background/stores/unified-scan-result-store.test.ts

This removes behavior that was clearing the automated checks results on any visualization toggle or rescan of any test.
feature work
the UnifiedScanResultActions.startScan action was created to fix issues that stemmed from automated checks and needs review being in the same store. It's only purpose was to clear the current results data in the UnifiedScanResultStore to avoid premature flashing of previous visualizations due to data from a different test being populated in the store.
I also removed the NeedsReviewScanResultActions.startScan. It was initially copied over from the UnifiedScanResultActions but was never used. …

feat(tabstops-report): fix automated checks data clearing on rescan of needs review

---

src/reports/components/fast-pass-outcome-summary-bar.tsx
src/reports/components/fast-pass-report-summary.tsx
src/reports/components/fast-pass-report.tsx
src/tests/unit/tests/reports/components/__snapshots__/fast-pass-outcome-summary-bar.test.tsx.snap
src/tests/unit/tests/reports/components/__snapshots__/fast-pass-report-summary.test.tsx.snap
src/tests/unit/tests/reports/components/__snapshots__/fast-pass-report.test.tsx.snap
src/tests/unit/tests/reports/components/fast-pass-outcome-summary-bar.test.tsx
src/tests/unit/tests/reports/components/fast-pass-report-summary.test.tsx

This PR adds `FastPassReportSummary` and `FastPassOutcomeSummaryBar` (empty) components. 
Feature 1872889.
The contents of the components will be included in a separate PR. 
There already exists an `OutcomeSummaryBar` for the exported assessment report. The functionality will differ, which is why I created a FastPass specific outcome bar. I think `OutcomeSummaryBar` should be re-named to `AssessmentOutcomeSummaryBar` or something similar to differentiate the two clearly.

feat(tabstops-report): add combined fastpass summary components 

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-baseline-aware-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
src/common/components/fix-instruction-processor.tsx
src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/end-to-end/test-resources/color-contrast/poor-color-contrast.html
src/tests/end-to-end/tests/details-view/__snapshots__/color-contrast.test.ts.snap
src/tests/end-to-end/tests/details-view/color-contrast.test.ts
src/tests/end-to-end/tests/target-page/color-contrast.test.ts
src/tests/unit/tests/injected/__snapshots__/fix-instruction-processor.test.tsx.snap

Add end to end tests for color contrast recommendations. For this PR, just adding simple test that recommendation is displayed for a failing page. 
Addresses issue #4379
#4360 added color contrast recommendations but no end to end tests were added. This PR adds e2e tests for this feature.

chore: Add color contrast recommendations end to end tests

---

src/common/feature-flags.ts
src/tests/unit/tests/background/feature-flags.test.ts

This PR adds the `tabStopsAutomation` feature flag (not yet used).
To support future PRs for this feature
A subsequent PR will put this feature flag to use

feat(tabstops-auto-impl): Add tabStopsAutomation feature flag

---

build.yaml

This PR disables the PR trigger for our ADO CI build in favor of running just the GitHub Actions CI build in PRs, per engineering discussion earlier today. I've left the ADO build in place to run with pushes to main, since that's what our release infrastructure uses as its starting point.
Note that it's expected that the ADO build is still being triggered for this PR itself; ADO's determines which pipelines to trigger based on the pipeline's definition in main, not the one in the target branch.
I have already updated the repo's branch protection rules to start requiring the GitHub Actions and stop requiring the ADO build (you can see this in the checks for this PR).
Per engineering discussion
n/a
- [n/a] Added/updated relevant unit test(s) (and …

chore: disable PR trigger for ADO CI build

---

Gruntfile.js
package.json
src/background/service-worker-init.ts
src/manifest.json
targets.config.js
tsconfig.json
webpack.config.js

This PR updates the build system to create both a `dev` and a `dev-mv3` build. The `dev-mv3` build will eventually replace the `dev` build, but only after we complete the work needed to migrate from manifest version 2 (MV2) to manifest version 3 (MV3). Since the Chrome team chose to change the schema between MV2 and MV3, some extra work is needed to create a version-specific manifest.json file. MV3 doesn't support `eval`, so we had to change the webpack's [devtool](https://webpack.js.org/configuration/devtool/) option from `eval-source-map` to an option that doesn't use `eval`. I experimented with both `inline-cheap-source-map` and `inline-source-map`, which is slightly faster. I opted for the slower option because the difference was only about 5 seconds per build.
The `dev-mv3` build …

feat(manifest-v3): Create dev-mv3 build as a sandbox for MV3 conversion

---

src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/report-export-dialog-factory.tsx
src/DetailsView/components/should-show-report-export-button.ts
src/ad-hoc-visualizations/issues/visualization.tsx
src/ad-hoc-visualizations/tab-stops/visualization.tsx
src/common/configs/visualization-configuration.ts
src/tests/unit/tests/DetailsView/components/report-export-dialog-factory.test.tsx
src/tests/unit/tests/DetailsView/components/should-show-report-export-button.test.ts

This adjusts the logic for when the export report button shows. Here are the before and after scenarios for when it shows in each test:
1. Automated Checks
- Before: Shows whenever visualization is enabled.
- After: Shows whenever target page changed view is not visible, which equates to whenever the visualization is enabled with the new navigation flow.
2.  Tab Stops:
- Before: Always shows
- After: Shows whenever target page changed view is not visible.
3. Needs Review: 
- Before: incorrectly shows when test is enabled.
- After: Never shows.
feature work
This passes in `featureFlagStoreData` as a second parameter. The `featureFlagStoreData` parameter will be removed before release, at which point `shouldShowExportReport` in `tab-stops/visualization.tsx` will also need to be updated to …

feat(tabstops-report): Fix logic for when to show export button

---

src/injected/all-frame-runner.ts

This PR pulls out the interface from https://github.com/microsoft/accessibility-insights-web/pull/5036 so that we can enable work in parallel.
Here are comments copied over from that PR describing upcoming the `AllFrameRunner` class.
---
This class ('runner' below) runs methods in AllFrameRunnerTargets ('target' below) in all child
frames. Runner manages communication between child frames and the top-level window so that the
target can produce results without explicit frame-communication code. 
It follows these semantics:
- runner.initialize() should be called & runner.topWindowCallback should be set 
before calling runner.start() / runner.stop()
- runner.start() will run target.start() in the current frame, and then in any child frames
- runner.stop() will run target.stop() in the …

feat(tabstops-auto-impl): add AllFrameRunnerTarget interface

---

src/common/html-element-utils.ts
src/injected/tab-stops-requirement-evaluator.ts
src/tests/unit/tests/common/html-element-utils.test.ts
src/tests/unit/tests/injected/tab-stops-requirement-evaluator.test.ts

Add `TabStopsRequirementEvaluator` and unit tests. This class will be leveraged by automated tab stops analyzer added in future PRs. 
Support future PRs for this feature.
A subsequent PR will add logic to call into this evaluator and use it to generate tab stops results automatically. 

feat(tabstops-auto-impl): Add tab stops requirement evaluator

---

src/reports/components/fast-pass-report-summary.tsx
src/tests/unit/tests/reports/components/__snapshots__/fast-pass-report-summary.test.tsx.snap
src/tests/unit/tests/reports/components/fast-pass-report-summary.test.tsx
src/tests/unit/tests/reports/components/fast-pass-report.test.tsx

This PR adds the results data to the `OutcomeSummaryBar` in `FastPassReportSummary`.
Feature 1872889.
Incomplete automated checks data will be added after the completion of 1906107.

feat(tabstops-report): add results data to outcome summary bar

---

src/DetailsView/components/report-export-dialog-factory.tsx
src/common/extension-telemetry-events.ts
src/electron/views/results/components/reflow-command-bar.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-dialog-factory.test.tsx.snap
src/tests/unit/tests/common/telemetry-data-factory.test.ts
src/tests/unit/tests/electron/views/results/components/__snapshots__/reflow-command-bar.test.tsx.snap

This updates the basename of the filename for the FastPass report from `AutomatedChecks` to `FastPass`.
feature work

feat(tabstops-report): update report filename to use FastPass instead of AutomatedChecks

---

src/DetailsView/components/tab-stops/tab-stops-instance-section-props-factory.tsx
src/DetailsView/details-view-initializer.ts
src/DetailsView/tab-stops-failed-counter.ts
src/DetailsView/tab-stops-minimal-requirement-header.tsx
src/DetailsView/tab-stops-requirements-with-instances.scss
src/DetailsView/tab-stops-requirements-with-instances.tsx
src/tests/unit/tests/DetailsView/components/tab-stops-failed-counter.test.ts
src/tests/unit/tests/DetailsView/components/tab-stops-failed-instance-section.test.tsx
src/tests/unit/tests/DetailsView/components/tab-stops-minimal-requirement-header.test.tsx
src/tests/unit/tests/DetailsView/components/tab-stops-requirements-with-instances.test.tsx
src/tests/unit/tests/DetailsView/components/tab-stops/__snapshots__/tab-stops-instance-section-props-factory.test.tsx.snap
src/tests/unit/tests/reports/components/fast-pass-report-summary.test.tsx
src/tests/unit/tests/reports/fast-pass-report-html-generator.test.tsx

This PR makes two updates to the FastPassReport:
1. It updates the failed instance count for tab stops to count each failed requirement with no user comments as 1 towards the requirement and overall section count
2. It italicizes the "This requirement has failed but no comment has been added" message for failed requirements with no instances
To accomplish 1, `TabStopsFailedCounter` has been split into two implementations: one for the extension details view that maintains existing behavior and one for the report that counts no instance requirements as described above. This PR has no impact on the behavior of the extension details view.
Screenshot showing both changes:
Bringing report closer to spec
I considered breaking the no comment message out into its own component, but it seemed to …

feat(tabstops-report) Update failed counter on fastpass report

---

src/reports/components/fast-pass-report-summary.tsx
src/tests/unit/tests/reports/components/__snapshots__/fast-pass-report-summary.test.tsx.snap
src/tests/unit/tests/reports/components/fast-pass-report-summary.test.tsx

This updates the summary bar counts to handle the scenario when `results.automatedChecks` is null. This happens when a user is on the tab stops test, navigates to a new target page, restarts the tab stops test then exports without ever running automated checks.
feature work

feat(tabstops-report): fix summary count when automated checks is null

---

src/injected/analyzers/tab-stops-orchestrator.ts
src/injected/tab-stops-requirement-evaluator.ts
src/injected/tabbable-element-getter.ts
src/tests/unit/tests/injected/analyzers/tab-stops-orchestrator.test.ts
src/tests/unit/tests/injected/tab-stops-requirement-evaluator.test.ts
src/tests/unit/tests/injected/tabbable-element-getter.test.ts

Creates tab stops orchestrator which should be used in all frames via all frame runner in a future PR.
feature work.
This is **definitely** making an assumption that when the orchestrator is stopped is equivalent to when the user is done testing. If that assumption ends up being not true, we'll have to expose a different API where we get the keyboard navigation results.

feat(tabstops-auto-impl): Create tab stops orchestrator

---

yarn.lock

This PR updates us to the latest `browserslist` database, using the following command:
`npx browserslist@latest --update-db`.
Resolves a build warning.
n/a

chore(deps): update browserslist database

---

yarn.lock

This PR updates transitive dep jsprim to 1.4.2 to enable a resolution-free update of json-schema to 0.4.0, which contains a fix for https://github.com/advisories/GHSA-566m-qj78-rww5
This is just for noise reduction; the dependency in question is only used by web during development, not at runtime, so there's no security impact on users.
Reduce alert noise
n/a

chore(deps): update jsprim to 1.4.2

---

src/injected/all-frame-runner.ts
src/injected/analyzers/tab-stops-orchestrator.ts
src/injected/single-frame-tab-stop-listener.ts
src/tests/unit/tests/injected/all-frame-runner.test.ts

This PR applies some changes based on comments in #5036 - we decided to merge that in early and address follow-up comments in a separate PR:
- change `AllFrameRunnerTarget.name` to `AllFrameRunnerTarget.commandSuffix` to better illustrate its usage
- change `AllFrameRunner.start()` and `AllFrameRunner.stop()`  to `void` functions. While the frame-messenger has support for responses from child frames, we weren't making use of it for start/stop. The frame-messenger listener expects an explicit return type of `CommandMessageResponse | null`, but this didn't make sense for clients of `AllFrameRunner` who need to just fire-and-forget start and stop. When registering commands to the frame messenger, we wrap the public-facing void methods and explicitly return `null`. If we need response data …

chore(tabstops-auto-impl): small refactors to all-frame-runner

---

src/background/stores/visualization-scan-result-store.ts
src/common/self-fast-pass.ts
src/injected/analyzers/analyzer-provider.ts
src/injected/analyzers/tab-stops-analyzer.ts
src/injected/main-window-initializer.ts
src/injected/window-initializer.ts
src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts

Wires up the tab stops orchestrator with tab stops analyzer via an all frame runner.
feature work.
Probably need to refine the tests a bit more and potentially debounce calls but that will be in the future.

feat(tabstops-auto-impl): wire up new tab stops automation behind feature flag

---

src/DetailsView/actions/tab-stop-requirement-action-message-creator.ts
src/DetailsView/components/adhoc-tab-stops-test-view.tsx
src/background/actions/action-payloads.ts
src/background/actions/tab-stop-requirement-action-creator.ts
src/background/actions/tab-stop-requirement-actions.ts
src/background/stores/visualization-scan-result-store.ts
src/common/components/focus-component.tsx
src/common/messages.ts
src/common/types/store-data/visualization-scan-result-data.ts
src/injected/analyzer-controller.ts
src/injected/main-window-initializer.ts
src/injected/selector-map-helper.ts
src/tests/unit/common/visualization-scan-result-store-data-builder.ts
src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/DetailsView/actions/tab-stop-requirement-action-message-creator.test.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-tab-stops-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/tab-stops/__snapshots__/tab-stops-instance-section-props-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/tab-stops/focus-component.test.tsx
src/tests/unit/tests/background/actions/tab-stop-requirement-action-creator.test.ts
src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
src/tests/unit/tests/injected/analyzer-controller.test.ts

Adds `tabbingCompleted` field to store data to keep track of if the tab stop analyzer is listening for user tabs or not. Tabbing is marked as complete when focus shifts from the target page to the details page. 
Feature work
A future PR will add another criteria for tabbing 'done-ness'- the tabbingCompleted field will also be set to true if we reach the same element multiple times in our tabbing. 

feat(tabstops-auto-impl): Trigger tabbing completed based on details view focus

---

src/DetailsView/components/tab-stops/tab-stops-requirement-table.scss

Currently, in the Details View for FastPass > Tab stops, the rows of the Requirements table shift bob up and down when they transition from an "unknown" state to a "pass" or "fail" state. This happens because in the pass/fail states, the "Undo" button is unhidden, and it has the greatest interior height of the elements within that row (25px).
This fix adjusts the cell containing the buttons to ensure that it has enough `min-height` to account for the undo button, even when the undo button is hidden.
Before:
After:
Partially addresses #5099 
n/a

fix(tabstops-report): prevent tab stops requirement rows from bobbing

---

src/injected/analyzers/tab-stops-analyzer.ts
src/injected/analyzers/tab-stops-orchestrator.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-orchestrator.test.ts

This PR addresses two issues in the current automated tab-stops implementation:
- duplicate results are not ignored. The impact is that users can be presented with unnecessary results they must manually delete. Our focus-order test implementation will produce duplicate results often (by design), so we need to filter those out.
- orchestrator-held state (in the target page) is not reset between consecutive start()/stop() calls. The impact is that hitting "start over" will act as a continuation of the last test (for example, the test will ignore any tab stops it found the first time)
Fix behavior, unblock correct e2e tests
I expect this code to change again in the upcoming visualization feature. The current feature is mainly scoped to gathering automated tab stops instances in /background. …

feat(tabstops-auto-impl): remove duplicate results & reset state between consecutive tab-stop-analyzer invocations

---

src/DetailsView/actions/tab-stop-requirement-action-message-creator.ts
src/background/actions/action-payloads.ts
src/background/actions/tab-stop-requirement-action-creator.ts
src/background/actions/tab-stop-requirement-actions.ts
src/background/stores/visualization-scan-result-store.ts
src/common/messages.ts
src/common/types/store-data/visualization-scan-result-data.ts
src/injected/analyzer-controller.ts
src/injected/main-window-initializer.ts
src/tests/unit/common/visualization-scan-result-store-data-builder.ts
src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/DetailsView/actions/tab-stop-requirement-action-message-creator.test.ts
src/tests/unit/tests/DetailsView/components/tab-stops/__snapshots__/tab-stops-instance-section-props-factory.test.tsx.snap
src/tests/unit/tests/background/actions/tab-stop-requirement-action-creator.test.ts
src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
src/tests/unit/tests/injected/analyzer-controller.test.ts

Fix bug introduced in latest tabstops-auto-impl feature work. If a user does not finish tabbing through the target page then the analyzer-controller enters a loop in which it sends automatic tabbing results to the store over and over, causing a crash. This PR fixes this bug and adds test coverage. 
Bug fix for feature work.
This fix adds an additional field to tab stops store data which allows us to track both if the user is finished tabbing (`tabbingCompleted`) as well as if results have not been reported and need to be updated (`needToCollectTabbingResults`). The second field is necessary because we only want to report results once, the very first time tabbing is completed. We considered fixing this bug by marking `tabbingCompleted = false` in `analyzer-controller`'s …

feat(tabstops-auto-impl): Fix results reporting loop bug

---

src/common/self-fast-pass.ts
src/injected/analyzers/analyzer-provider.ts
src/injected/analyzers/tab-stops-analyzer.ts
src/injected/analyzers/tab-stops-done-analyzing-tracker.ts
src/injected/main-window-initializer.ts
src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-done-analyzing-tracker.test.ts
tsconfig.strictNullChecks.json

This PR follows https://github.com/microsoft/accessibility-insights-web/pull/5087 - the second way automated tab stops "completes" is if the user completes a global cycle when tabbing in the target page.
Similar to #5112 we put this in `tab-stops-analyzer` to co-locate with the duplicate-filtering. Alternatives include `background` (since we're working with transformed `TabStopEvent` objects directly) or in `tab-stops-orchestrator`, which felt less ideal. This code needs to run in the top frame.
In the video below note that the "keyboard navigation" results (computed only after tabbing completes) show up when we revisit the first node.
https://user-images.githubusercontent.com/7775527/151274007-9632ffa1-fe87-43a2-8854-3d22c839ac69.mp4
feature behavior, stop tab stops test if the user …

feat(tabstops-auto-impl): end tab stops test if the user re-encounters the first tabbed element

---

src/injected/analyzers/tab-stops-orchestrator.ts
src/injected/tab-stops-requirement-evaluator.ts
src/tests/end-to-end/tests/details-view/automated-tabstops.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-orchestrator.test.ts
src/tests/unit/tests/injected/tab-stops-requirement-evaluator.test.ts

Fixes 2 bugs discovered in smoke testing: focus order result description was unclear and tabbing through a page with no elements returned a false positive. 
Fix bugs introduced by feature work.
- Description wording for focus order results comment was misleading, updating language.
- When tabbing on a page with no tabbable elements, automated tests returned a false positive focus trap result, because our tests detect that the focus remains on the body. Fixing this by ignoring the body in the focus trap test.

feat(tabstops-auto-impl):Fix tab stops description and body bugs

---

.github/workflows/ci.yml
docs/building-web.md
pipeline/install-node-prerequisites.yaml

This PR bumps the version of Node we use in CI builds on both GitHub Actions and Azure DevOps to the latest v14 (`14.19.0`).
This is primarily in the hopes of resolving an issue we've seen in a few recent PR builds for dependabot PRs where builds fail in webpack with an error that looks like this:
```
Running "concurrent:webpack-all" (concurrent) task
Running "exec:webpack-prod" (exec) task
>> internal/child_process/serialization.js:70
>>       yield deserializer.readValue();
>>                          ^
>> 
>> Error: Unable to deserialize cloned data.
>>     at parseChannelMessages (internal/child_process/serialization.js:70:26)
>>     at parseChannelMessages.next (<anonymous>)
>>     at Pipe.channel.onread (internal/child_process.js:599:18)
>> Exited with code: 1.
>> Error executing …
```

chore(deps): update node in CI builds to 14.19.0

---

src/DetailsView/actions/tab-stop-requirement-action-message-creator.ts
src/background/actions/tab-stop-requirement-action-creator.ts
src/background/actions/tab-stop-requirement-actions.ts
src/common/extension-telemetry-events.ts
src/common/messages.ts
src/common/telemetry-data-factory.ts
src/injected/analyzers/tab-stops-analyzer.ts
src/injected/tab-stops-requirement-evaluator.ts
src/tests/unit/tests/DetailsView/actions/tab-stop-requirement-action-message-creator.test.ts
src/tests/unit/tests/DetailsView/components/tab-stops/__snapshots__/tab-stops-instance-section-props-factory.test.tsx.snap
src/tests/unit/tests/background/actions/tab-stop-requirement-action-creator.test.ts
src/tests/unit/tests/common/telemetry-data-factory.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts

Add telemetry for automated tab stops results. Telemetry event includes the number of issues by requirement when results are found. When results are not found, no telemetry is sent.
Feature work.
Ideally we wouldn't have to add another message for adding telemetry. I considered reusing the `NeedToCollectTabbingResults` message for this but at the moment it only keeps track of if tabbing results need to be collected or not (a boolean) and doesn't know what the results actually are. Further, we only want to send the telemetry event once so we would have to add telemetry only when the payload is false (that is, we have finished collecting tabbing results, which should only happen once). We could update this message to take in the results as well and handle the telemetry, but I opted to …

feat(tabstops-auto-target-page-vis): Add telemetry for automated tab stops results

---

packages/report/package.json
src/reports/combined-report-html-generator.tsx
src/reports/components/report-sections/combined-report-failed-section.tsx
src/reports/components/report-sections/summary-report-details-section.tsx
src/reports/package/accessibilityInsightsReport.d.ts
src/reports/package/combined-results-report.ts
src/reports/package/reporter-factory.ts
src/tests/unit/tests/reports/combined-report-html-generator.test.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/combined-report-failed-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/combined-report-failed-section.test.tsx
src/tests/unit/tests/reports/package/combined-results-report.test.ts

In this PR we:
1. fix the React warning in the report package: `Each child in a list should have a unique "key" prop` so that consumers of the package don't see unnecessary output logs
2. unblock releasing the report package by removing an unnecessary parameter
I plan to release the report package after this PR is merged.
`SummaryReportDetailsSection` was missing `key` values for sibling listitems. This leads to a React warning not only for us, but also for consumers of the report package. The text below comes from an ADO extension run (copied from https://github.com/microsoft/accessibility-insights-action/issues/950):
```
2021-11-02T19:50:21.6436274Z Warning: Each child in a list should have a unique "key" prop.
2021-11-02T19:50:21.6437698Z 
2021-11-02T19:50:21.6439176Z Check the …
```

feat(ado-improvements-1): fix React warning in report & simplify combined report parameters

---

src/DetailsView/actions/tab-stop-requirement-action-message-creator.ts
src/common/telemetry-data-factory.ts
src/injected/analyzers/analyzer-provider.ts
src/injected/analyzers/tab-stops-analyzer.ts
src/injected/analyzers/tab-stops-orchestrator.ts
src/injected/tab-stop-requirement-result.ts
src/injected/tab-stops-requirement-evaluator.ts
src/injected/window-initializer.ts
src/tests/unit/tests/DetailsView/actions/tab-stop-requirement-action-message-creator.test.ts
src/tests/unit/tests/common/telemetry-data-factory.test.ts
src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-orchestrator.test.ts
src/tests/unit/tests/injected/tab-stops-requirement-evaluator.test.ts

Just a rename PR so future PRs are easier to review.
feature work.
Will be differentiating instances where we are given an aligning element's information and where we are not (i.e. automated vs manual instances).

refactor(tabstops-auto-target-page-vis): TabStopRequirementResult to AutomatedTabStopRequirementResult rename

---

src/DetailsView/components/adhoc-tab-stops-test-view.tsx
src/DetailsView/components/auto-detected-failures-dialog.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-tab-stops-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/auto-detected-failures-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/auto-detected-failures-dialog.test.tsx

Add pop up to tab stops page when automatic failures are detected.
(screenshot of tab stops details view page with popup in front. Popup text is: 'Possible failures auto-detected. Review each finding to be sure it's valid. Add any more failures you discovered manually')
Feature work.
Pop up is behind `tabStopsAutomation` feature flag and only displays when failures have been auto detected. Ideally we will add a `Don't show again` checkbox later in this feature, but this is a stretch goal.

feat(tabstops-auto-target-page-vis): Add tab stops auto detected failures pop up dialog

---

src/background/stores/visualization-scan-result-store.ts
src/common/types/store-data/visualization-scan-result-data.ts
src/injected/main-window-initializer.ts
src/injected/selector-map-helper.ts
src/injected/visualization/get-visualization-instances-for-tab-stops.ts
src/injected/visualization/svg-shape-factory.ts
src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
src/tests/unit/tests/injected/selector-map-helper.test.ts
src/tests/unit/tests/injected/visualization/get-visualization-for-tab-stops.test.ts
src/tests/unit/tests/injected/visualization/get-visualization-instances-for-tab-stops.test.ts
src/tests/unit/tests/injected/visualization/svg-shape-factory.test.ts

The data from the store needs to be normalized to minimize changes to the drawer layer. This PR does that.
Feature work.
Problems not solved in this PR:
- What about automated instances that share selectors? We don't have a way to represent that information currently.
- We need to include information about type of failure in these instances to visualize them differently.

feat(tabstops-auto-target-page-vis): process both tabbed elements and requirement instances before data is visualized.

---

src/ad-hoc-visualizations/tab-stops/visualization.tsx
src/injected/analyzers/analyzer-provider.ts
src/injected/analyzers/tab-stops-analyzer.ts
src/injected/tab-stops-requirement-evaluator.ts
src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
src/tests/unit/tests/injected/tab-stops-requirement-evaluator.test.ts

Fixes bug in which automatic tab stops requirement checks are run for any test that uses the FocusTrackingAnalyzer (for example, Keyboard Navigation requirement under Assessment). As a result, extra failure instances will be collected, stored, and displayed when the user switches to the tabstops report. 
Fix bug introduced by feature work.
Added an extra method to `analyzer-provider` to avoid having to condition based on `VisualizationType` in the TabStopsAnalyzer. 

feat(tabstops-auto-target-page-vis): Fix FocusTrackingAnalyzer bug

---

src/injected/visualization/svg-drawer.ts
src/tests/unit/tests/injected/visualization/svg-drawer.test.ts

Currently `svg-drawer` accepts the data type `TabbedElementData`, which does not contain any of the requirement failure data that will be necessary to show automatic failure visualizations. This PR switches to using the `TabStopVisualizationInstance` data type, which will eventually be populated with automatically failed requirement results. 
Feature work.
At the moment the `requirementResults` property of `TabStopVisualizationInstance` is never populated so failure visualizations are still not shown correctly. This will be fixed in following PRs. 

feat(tabstops-auto-target-page-vis): Convert svg drawer to use TabStopVisualizationInstance

---

src/injected/frameCommunicators/html-element-axe-results-helper.ts
src/injected/selector-to-visualization-map.ts
src/injected/visualization/get-visualization-instances-for-tab-stops.ts
src/tests/unit/tests/injected/visualization/get-visualization-instances-for-tab-stops.test.ts

Allows us to have multiple failures attributed to one element.
feature work

feat(tabstops-auto-target-page-vis): introduce TabStopVisualizationInstance for multiple failures on one element

---

src/injected/visualization/focus-indicator.ts
src/injected/visualization/formatter.ts
src/injected/visualization/svg-shape-factory.ts
src/injected/visualization/tab-stops-formatter.ts
src/tests/unit/tests/injected/visualization/svg-drawer.test.ts
src/tests/unit/tests/injected/visualization/svg-shape-factory.test.ts
src/tests/unit/tests/injected/visualization/tab-stops-formatter.test.ts

Add visualization elements that will be leveraged for automated tab stops failure visualization in target page. Note that screenshots below were generated during tested and do not show up in any real visualizations. 
Missing element visualization: dotted red circle with red '!' in right upper corner. Once logic is added to differentiate between types of tabstops visualization elements, the tab order number will be replaced with a red 'X'. 
(screenshot of missing element visualization described above)
Failed element visualization: solid red circle with red '!' in right upper corner. This visualization will represent any automatically detected tab stop failure besides a missing element. Once logic is added to differentiate between types of tabstops visualization elements, the tab order text …

feat(tabstops-auto-target-page-vis): Add automatically failed tab stops target page visualization elements

---

src/injected/visualization/svg-drawer.ts

Realized we were using the OR operator a few times where we could simplify the code.
feature work
Tested with feature flag off and on to make sure it was consistent (note: with feature flag on, it is broken still ... but in the same way).

refactor(tabstops-auto-target-page-vis): only use TabStopVisualizationInstance in SVG drawer

---

src/injected/frameCommunicators/html-element-axe-results-helper.ts
src/injected/visualization/get-visualization-instances-for-tab-stops.ts
src/injected/visualization/tabbed-item.ts
src/tests/unit/tests/injected/visualization/get-visualization-instances-for-tab-stops.test.ts

Add the `itemType` property to `TabStopVisualizationInstance` and `TabbedItem`. This property differentiates between the different types of elements/failures that are passed to the svg-drawer to visualize and is populated based off the content of the `requirementResults`. 
Feature work.
A future PR will take advantage of the new itemType property in the svg-drawer for tab stops failure visualization. 

feat(tabstops-auto-target-page-vis): Add and populate tabbed item type for automated tabbing results

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-baseline-aware-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
src/reports/components/report-sections/header-section.scss

This PR fixes the focus on the target link in the FastPass and Assessment report. The focus was getting clipped due to the parent's `overflow: hidden`. 
- Replace `@include ellipsedText();` on parent element (`.target-page`) with `white-space: nowrap;`. This will keep the content on one line, but not clip the overflow. The CSS already sets the ellipsed text include on the anchor element and that's the only content we want to be truncated.
- Replace `display: inherit` with `display: flex`, while these values are the same, from a readability perspective, it may be helpful to be explicit with this value and help make the code modular. Using flex is important here so that only the link is truncated.
- Set `min-width: 0` on `.target-page`. I found this to be the best option to avoid using …

fix: Show full focus on target page link

---

src/injected/visualization/get-visualization-instances-for-tab-stops.ts
src/tests/unit/tests/injected/visualization/get-visualization-instances-for-tab-stops.test.ts

Fixing a bug in which target page visualization does not display for tab stop/focus tracking requirements in assessment when 
`TabStopsAutomation` feature flag is enabled.
Fix bug introduced by feature work.
For some assessments we call `GetVisualizationInstancesForTabStops` with `tabbedElements` null, which prior to this change results in an error.

fix(tabstops-auto-target-page-vis): Fix bug in assessment tab stops visualization

---

src/DetailsView/components/auto-detected-failures-dialog.tsx
src/tests/unit/tests/DetailsView/components/auto-detected-failures-dialog.test.tsx

Fix bug in which the tab stops auto detected failures dialog did not pop up when the only failures were missing item failures. 
Fix bug introduced by feature work.
Prior to this change, the dialog appeared when `tabbingCompleted` was changed from `false` to `true` and there were requirement results in the data store. This did not work when the only failures were missing elements, because missing element failures are added to the store after `tabbingCompleted` is true. To fix this, we switched to checking for requirement results when `needToCollectTabbingResults` changes from `true` to `false`, as this marks when all results have been collected and are in the data store. 
- …

fix(tabstops-auto-target-page-vis): Fix auto detected failures dialog update logic

---

src/background/stores/visualization-scan-result-store.ts
src/injected/analyzers/tab-stops-requirement-result-processor.ts
src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-requirement-result-processor.test.ts

Changes the tab stop requirement result processor to not start when tab results are already collected.
feature work.
Previously, we were depending on the store check to see if we already have completed collecting results for tab stops and then not doing anything if we had. This is an alternative to that: no results are created (since the requirement runner is never started) if that's the case.

feat(tabstops-auto-target-page-vis): fix start over tab stops issue

---

pipeline/unified/channel/sign-release-package-mac.yaml

This PR fixes the failed canary build. The build was failing for mac signing because [.NET core 2.1 has reached end of life](https://github.com/actions/virtual-environments/issues/4871) but [ESRP requires the mac signing task to use 2.1](https://marketplace.visualstudio.com/items?itemName=SFP.build-tasks&targetId=465e99f0-a0f9-4257-95e0-04c716327b00). This installs the 2.1.x version for mac. 
This fix was validated by introducing the fix on a separate branch, running the pipeline against the new branch and confirming the build passed.

fix: update .NET core version for mac ESRP signing

---

src/injected/visualization/tab-stops-formatter.ts
src/tests/end-to-end/tests/details-view/automated-tabstops.test.ts
src/tests/unit/tests/injected/visualization/tab-stops-formatter.test.ts

Makes error circles for tab stop requirements transparent, allowing for tab index underneath to be shown.
feature work
Due to how visualizations work, this can result in the line drawn to be visible in the circle if there is an overlap between elements and where the user has tabbed from. We are moving forward with this bug in mind.
Example:

feat(tabstops-auto-target-page-vis): error circles are transparent

---

src/DetailsView/components/auto-detected-failures-dialog.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/auto-detected-failures-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/auto-detected-failures-dialog.test.tsx

Uses the default fluent UI dialog to allow us to light dismiss (escape/click away) from the auto-detected failures dialog.
feature work
N/A

feat(tabstops-auto-target-page-vis): dismiss tabstops dialog via escape

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-baseline-aware-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
src/DetailsView/tab-stops-minimal-requirement-header.scss
src/DetailsView/tab-stops-minimal-requirement-header.tsx
src/common/components/cards/rules-with-instances.scss
src/reports/components/report-sections/minimal-rule-header.tsx
src/tests/end-to-end/tests/details-view/cross-origin-iframe.test.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/tab-stops-minimal-requirement-header.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/minimal-rule-header.test.tsx.snap

Fix emphasis bug found in latest accessibility pass. Requirement names listed in details view requirement failures list appears to be visually bolded but is not surrounded by emphasis tags. 
Addresses issue #5247.
No visual changes, changes only to backing html. 
[Screenshot of details view requirement failure results with requirement name bolded followed by failure details which are not bolded.]

fix: Add emphasis tags to bolded requirement ids in details view results

---

src/common/feature-flags.ts
src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
src/tests/unit/tests/background/feature-flags.test.ts

Enable Tab Stops Automation feature flag by default and show it as a preview feature for release.
Turn on new tab stops automation feature for users.
(Screenshot of Preview features panel, with Tab Stops Automation toggled on)
This feature flag will be removed in a future release.

feat(tabstops-auto-target-page-vis): enable tab stops automation feature flag

---

jest.config.base.js
src/tests/common/typemoq-snapshot-serializer.ts
src/tests/unit/tests/DetailsView/__snapshots__/details-view-container.test.tsx.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-issues-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/load-assessment-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-dialog-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/save-assessment-button-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/target-change-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/details-view-overlay/preview-features-panel/__snapshots__/preview-features-container.test.tsx.snap
src/tests/unit/tests/DetailsView/components/details-view-overlay/settings-panel/settings/issue-filing/__snapshots__/issue-filing-settings.test.tsx.snap
src/tests/unit/tests/DetailsView/components/tab-stops/__snapshots__/tab-stops-instance-section-props-factory.test.tsx.snap
src/tests/unit/tests/common/components/__snapshots__/theme.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/how-to-fix-card-row.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/instance-details-footer.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/rules-with-instances.test.tsx.snap
src/tests/unit/tests/debug-tools/components/__snapshots__/debug-tools-view.test.tsx.snap
src/tests/unit/tests/debug-tools/components/telemetry-viewer/__snapshots__/telemetry-viewer.test.tsx.snap
src/tests/unit/tests/electron/views/results/__snapshots__/results-view.test.tsx.snap
src/tests/unit/tests/electron/views/results/components/__snapshots__/title-bar.test.tsx.snap
src/tests/unit/tests/electron/views/root-container/components/__snapshots__/platform-body-class-modifier.test.tsx.snap
src/tests/unit/tests/electron/views/root-container/components/__snapshots__/root-container.test.tsx.snap
src/tests/unit/tests/injected/components/__snapshots__/command-bar.test.tsx.snap
src/tests/unit/tests/issue-filing/components/__snapshots__/issue-filing-settings-container.test.tsx.snap
src/tests/unit/tests/popup/components/__snapshots__/popup-view.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/report-body.test.tsx.snap

This PR implements and configures a new `typemoq-snapshot-serializer`, a Jest Snapshot Serializer which causes typemoq mock objects that get captured by test snapshots to be serialized as `[typemoq mock object]` instead of as a big blob of all the objects' properties.
Example before:
```
Object {
"deps": Object {
"storesHub": proxy {
"___id": "BCDF5CE5-F0DF-40B7-8BA0-69DF395033C8",
"stores": undefined,
},
},
}
```
Same example after:
```
Object {
"deps": Object {
"storesHub": [typemoq mock object],
},
}
```
1. This makes tests less brittle. In general, we don't want to pin the individual properties of mocked objects in snapshots; from the perspective of the test performing the snapshot, they're implementation details (otherwise it wouldn't be mocked!), so we shouldn't be validating them …

chore: make snapshots of typemoq mocks less brittle

---

docs/building-web.md

I recently learned (thanks @dbjorge!) that you may need to run `yarn jest --clearCache` to clear out the Jest cache when testing locally. The result of not clearing the cache can mean that your local environment is out of sync with what would show up on CI, which can make local testing difficult. 
This PR adds a small note to `docs/building-web.md` to include this suggestion.
Documentation on `clearCache`: https://jestjs.io/docs/cli#--clearcache
Documentation to improve developer experience. …

chore: Add documentation about `jest --clearCache`

---

eslintrc.base.js
src/tests/unit/tests/scanner/custom-rules-configuration-stub.ts

This is a followup from a PR comment several weeks ago where I suggested to someone that it would be preferable to use `throw new Error('message');` instead of `throw 'message';`, since the former gives a stack trace. This is something that eslint can catch automatically; this PR configures it to do so (and fixes the one existing hit for the rule in a test file).
Automatically catches an issue that previously required manual review.
n/a

chore(lint): enable no-throw-literal eslint rule

---

src/injected/tabbable-element-getter.ts
src/injected/window-initializer.ts
src/tests/unit/tests/injected/tabbable-element-getter.test.ts

Fix automated tab stops bug so that elements behind an open modal are not marked as missing failures. 
[Screenshot of site with modal open and no missing tab stops marked in background]
Addresses issue #5305.
Tabbable does not take `aria-hidden` or `aria-modal` into account when determining which elements are tabbable, meaning before this change we were marking them as missing since the user can't tab to them. This PR adds logic to filter out these elements from the tabbable results so they are not considered when determining missing elements.

fix: Ignore hidden elements when determining tabbable elements

---

pipeline/scripts/zip-mac-folder.js

Uses ditto to create zip for auto-update.
Attempted fix for #3942.
The error I'm getting upon trying to update seems to imply that this could be a zipping issue.
The error:
```
Error: Error: ditto: Accessibility Insights for Android - Canary.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libswiftshader_libGLESv2.dylib: No such file or directory
ditto: Couldn't read pkzip signature.
```

refactor: use ditto to compress auto-update zip

---

src/electron/resources/entitlements.plist

Adds entitlement for allowing DYLD environment variables.
More info: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-dyld-environment-variables
Fixing #3942.
The error that I'm seeing suggests that we're having trouble accessing the dylib ... so I'm wondering if this is necessary to fix problem (underlying update method could be using these environment variables to access these files). This was a common entitlement for electron projects I found when working on notarization.
The error:
```
Error: ditto: Accessibility Insights for Android - Canary.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libswiftshader_libGLESv2.dylib: No such file or directory
ditto: Couldn't read pkzip signature
```

fix: allow dyld environment variables for potential fix auto-update on Mac

---

src/electron/electron-builder/electron-builder.template.yaml

Only builds dmg file.
See if this fixes/produces different error than the "cannot read pkzip signature" issue.
There's a comment suggesting errors that I'm seeing are similar to what happens when we produce a zip from electron-builder (https://github.com/microsoft/accessibility-insights-web/blob/9c25a2d1d4817b71cb7a5f3eb3e814543d2ea5ce/Gruntfile.js#L722-L725) ... and so I want to see whether that remains the case or we see a different error or this fixes the issue last seen for #3942.

fix: undo electron builder target for mac changes

---

pipeline/scripts/zip-mac-folder.js
src/electron/electron-builder/electron-builder.template.yaml
src/electron/resources/entitlements.plist

Auto-update is now functional per my last PR #5336. I'm removing changes that are not necessary for it to function + adding comments.
Clean up.
Decided to keep using ditto even though that change was made as an (unsuccessful) attempt to fix auto-update, since documentation around notarization on Mac suggests to use ditto.
https://developer.apple.com/forums/thread/701514#701514021

fix: remove unnecessary changes for auto-update and add comments

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-baseline-aware-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
src/common/components/heading-element-for-level.scss
src/common/components/heading-element-for-level.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/heading-element-for-level.test.tsx.snap

unset the margin for the new heading element.
Fix for visual bug.
Many components/products use this component so it made sense to make this a default behavior as this is what was previously expected. In the future we can manage this by passing through CSS classes if we wish to get these margins again.
Verified the fix worked in: automated checks (unified, web), needs review (unified, web) and tab stops (web).
Example of difference below.
Before:
After:

fix: unset heading margin under heading element for level component

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.input.ts
packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.input.ts

Addressing TSA bugs; changing language in our test cases to be in line with Policheck requirements. 
More specifically, for the report end to end tests, our example cases of axe results with and without issues used the word "country" and it is recommended to use "country/region" instead. 
Compliance/bug fix. 
Since this is not user-facing, priority of this change is low; however, making this change could prevent TSA from catching this and flagging it as a bug again in the future, which will save us engineering time. 
- [n/a] (UI changes only) Added screenshots/GIFs …

fix: Changing country to country/region, as per TSA Policheck guidance

---

src/background/IndexedDBDataKeys.ts
src/background/background-init.ts
src/background/extension-details-view-controller.ts
src/background/get-persisted-data.ts
src/background/target-page-controller.ts
src/tests/unit/tests/background/extension-details-view-controller.test.ts
src/tests/unit/tests/background/target-page-controller.test.ts

Adding logic to persist target page and details view controller backing data. This change has no effect on the manifest v2 version of the extension but will be necessary for the manifest v3 version.
Feature work.
The target page controller actually deals with a map from known tab IDs to tab context objects, which could not be saved in the indexed database as is. As a result, this PR adds logic to save a list of the known tab IDs so that, when the service worker restarts, it knows to only instantiate a new context object to replace the lost one and not to broadcast a `ExistingTabUpdated` message when the url remains the same. …

feat(mv3-part-2): Persist target page and details view controllers data

---

src/background/get-persisted-data.ts
src/tests/unit/tests/background/get-persisted-data.test.ts

Follow up to https://github.com/microsoft/accessibility-insights-web/pull/5370, which added logic to persist controllers data. That PR missed updating `keyToPersistedDataMappingOverrides` with the new keys introduced by those changes. Without this change, the controllers will always be initialized with empty objects, instead of persisted data, if any exists. 
Feature work.
This change does not have an effect on the manifest v2 extension because it will always be initialized with empty objects anyways. This change is necessary for the manifest v3 extension, which will need to be initialized with persisted data after a service worker restarts. 
- [n/a] (UI changes only) Verified …

feat(mv3-part-2): Add missing key to persisted data mapping overrides

---

src/background/background-init.ts
src/background/stores/assessment-store.ts
src/background/stores/global/user-configuration-store.ts
src/common/flux/persistent-store.ts
src/tests/unit/tests/background/stores/persistent-store.test.ts

Fix bug discovered in canary caused by https://github.com/microsoft/accessibility-insights-web/pull/5363.
Fixes bug in canary.
The issue in canary seems to be caused with an underlying bug in the way details view store data is persisted. This PR does not address that issue, but instead it stops initializing stores/ controllers with persisted data for the manifest v2 extension. This will allow us to unblock canary but leave the persisting logic in so that it can be fixed and called from the manifest v3 extension.

fix: Do not initialize with persisted data for manifest v2 extension

---

package.json
packages/report/package.json
packages/ui/package.json
src/content/guideline-metadata.ts
src/injected/frameCommunicators/axe-frame-messenger.ts
src/scanner/axe-configurator.ts
src/scanner/get-rule-inclusions.ts
src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
src/tests/unit/tests/scanner/__snapshots__/get-rule-inclusions.test.ts.snap
src/tests/unit/tests/scanner/axe-configurator.test.ts
src/tests/unit/tests/scanner/get-rule-inclusions.test.ts
src/tests/unit/tests/scanner/map-axe-tags-to-guidance-links.test.ts
webpack.config.js
yarn.lock

This PR will update axe-core to 4.4.1. This new version includes bug fixes, 17 false-positive fixes, 1 rule change, and 1 general improvement.
- Omit [color-contrast-enhanced, wcag146](https://github.com/dequelabs/axe-core/blob/f583c70b191513f5bd116a3ed091e937ea2cd65d/lib/rules/color-contrast-enhanced.json) in tests. Being AAA, this rule is out of scope.
- Update axe config to replace `branding` property value to be a string.
- Remove webpack configuration for fallback of the "crypto" import, the dependency was removed in axe-core.
- Remove manual typings that are now in axe-core.
- Exclude all rules tagged with `wcag2aaa`. The product does not include AAA rules and by filtering them out it will prevent `identical-links-same-purpose` from being included. In 4.4, some [rules were …

feat(axe-core-4.4): Update axe-core@4.4.1

---

.github/workflows/ci.yml

Recently we've seen a few timeouts in e2e CI jobs which have failed (usually with a test timing out), then additionally failed to upload debug logs (also in a timeout). This PR bumps up the latter timeout to make diagnosing the former timeouts more feasible.
Improve test debugability
Attempt 1 of e2e job 0 in #5386 is an example of the timeouts in question

chore: increase the timeout for CI builds to upload e2e test debug logs

---

src/background/target-page-controller.ts
src/tests/unit/tests/background/target-page-controller.test.ts

Ensure that storage is cleaned up for any tabs removed when the service worker is down by checking that all `knownTabIds` still exist upon the service worker restarting and, for any tab that no longer exists, tearing down its storage.
Feature work.
These changes will not have any effect on the mv2 extension, since `knownTabIds` is always an empty list. 

feat(mv3-part-2): Remove tab IDs that were closed when service worker is down

---

src/background/background-init.ts
src/background/message-distributor.ts
src/background/post-message-content-handler.ts
src/background/service-worker-init.ts
src/common/types/backchannel-message-type.ts
src/tests/unit/tests/background/message-distributor.test.ts
src/tests/unit/tests/background/post-message-content-handler.test.ts

Currently, we register separate onMessage event handlers in MessageDistributor and PostMessageContentHandler. This PR combines these into one onMessage handler in MessageDistributor.
As noted in #5396, BrowserAdapterEventManager only allows one event handler per event, so we will need to combine message distribution logic into one ApplicationHandler. Most of it is already consolidated into MessageDistributor, so this PR moves the remaining onMessage registrations in the background context into MessageDistributor.
Multiple onMessage handlers are also registered by StoreProxies. However, StoreProxies are only created in contexts that don't have a MessageDistributor (i.e. non-background contexts), so those event handlers will be consolidated in a different class and a different PR.

(feat: mv3-part-2): Consolidate background message distribution logic

---

src/background/extension-details-view-controller.ts
src/background/target-page-controller.ts
src/common/flux/persistent-store.ts
src/tests/unit/tests/background/extension-details-view-controller.test.ts
src/tests/unit/tests/background/stores/persistent-store.test.ts
src/tests/unit/tests/background/target-page-controller.test.ts

Previous PRs added logic to persist store/controller data, which will be necessary for the mv3 extension. Those PRs made it so that the mv2 extension also persists data but does not read from the persisted data. @dbjorge suggested that we do not persist data at all in the mv2 extension to avoid backward compat issues in the future, so this PR turns data persist-ing off by default. I will follow up in a future PR to turn data persisting on only for the mv3 extension.
Feature work.
Confirmed by running dev mv2 extension locally that we no longer persist data (other than assessment, user config, etc- which were already persisted prior to this change).
Note that test file diffs look big primarily because of whitespace changes, might be easier to review that code locally. 
- [n/a] Addresses an …

feat(mv3-part-2): Do not persist data for mv2 extension

---

README.md

Dependabot's README badges broke when the old non-GitHub Dependabot migrated to GitHub. This PR removes the broken badge.
Fixes broken link/image at top of README
There isn't currently a replacement for the badge feature in the native GitHub Dependabot. https://github.com/dependabot/dependabot-core/issues/1912 tracks the request to add it, but hasn't seen activity in some time.

chore: remove obsolete Dependabot badge from README

---

package.json
yarn.lock

web's `axios` dependency was originally introduced in #1077 as part of our implementation to have AI4Android communicate with the android service's webserver. We removed all usages of it when we replaced the android service's webserver with its ContentProvider-based implementation, but missed removing the `axios` dependency.
This doesn't have a huge impact since `appium-adb` still has a transitive dependency on `axios`, but at least it reduces some dependabot noise.
Remove obsolete code, reduce dependabot noise
n/a …

chore: remove obsolete dependency on axios

---

src/DetailsView/details-view-initializer.ts
src/Devtools/dev-tool-init.ts
src/Devtools/dev-tool-initializer.ts
src/common/constants/generic-store-messages-types.ts
src/common/state-dispatcher.ts
src/common/store-proxy.ts
src/common/store-update-message-distributor.ts
src/common/types/store-update-message.ts
src/debug-tools/initializer/debug-tools-init.tsx
src/injected/main-window-initializer.ts
src/popup/popup-initializer.ts
src/tests/unit/tests/common/state-dispatcher.test.ts
src/tests/unit/tests/common/store-proxy.test.ts
src/tests/unit/tests/common/store-update-message-distributor.test.ts
src/views/insights/dependencies.ts

Creates StoreUpdateMesssageDistributor to distribute update messages to the appropriate StoreProxy, if one is registered.
As mentioned in #5396 and #5407, we will eventually need to combine message handling into one event listener (per context) that distributes messages to their respective handlers. Currently, each StoreProxy registers its own separate onMessage handler. This change creates one central message listener that distributes store update messages to the appropriate StoreProxy.
This continues a change from #5407. After this PR, all contexts will have only one registered onMessage listener at the browser level.

feat(mv3-part-2): Consolidate store proxy message handling

---

src/background/IndexedDBDataKeys.ts
src/background/background-init.ts
src/background/get-persisted-data.ts
src/background/service-worker-init.ts
src/background/target-page-controller.ts
src/tests/unit/tests/background/get-persisted-data.test.ts
src/tests/unit/tests/background/target-page-controller.test.ts

Adds logic to determine if a tab url has changed between service worker shut down and restart. This ensures that we correctly handle url changes even if they happen with the service worker was down.
Feature work.
This change required us to restructure knownTabIds such that it now stores and persists both the tab ID and url. This allows us to check that the urls haven't changed between service worker shut down and restart.
This change does not effect the mv2 extension because it does not persist any data and therefore it never has any known tabs on target page controller initialization.

feat(mv3-part-2): Only use persisted tab info if tabs are still valid after service worker restart

---

src/background/stores/assessment-store.ts
src/tests/unit/tests/background/stores/__snapshots__/assessment-store.test.ts.snap
src/tests/unit/tests/background/stores/assessment-store.test.ts

Fix a bug in the way the assessment store handles resetting data when the user starts over. 
Feature work.
Moving to use the PersistentStore introduced a bug where we use the persisted data to calculate the default store data all the time. This PR makes it so that we don't use the persisted data when resetting the assessment store data.
Note that this bug only repros in the mv3 extension because the mv2 extension does not persist data at the moment.

feat(mv3-part-3): Fix assessment store start over logic

---

src/background/background-init.ts
src/background/dev-tools-listener.ts
src/background/keyboard-shortcut-handler.ts
src/background/message-distributor.ts
src/background/service-worker-init.ts
src/background/tab-context-factory.ts
src/background/tab-context-manager.ts
src/background/target-page-controller.ts
src/tests/unit/common/simulated-browser-adapter.ts
src/tests/unit/tests/background/dev-tools-listener.test.ts
src/tests/unit/tests/background/keyboard-shortcut-handler.test.ts
src/tests/unit/tests/background/message-distributor.test.ts
src/tests/unit/tests/background/tab-context-factory.test.ts
src/tests/unit/tests/background/tab-context-manager.test.ts
src/tests/unit/tests/background/target-page-controller.test.ts

Moves tabIdToContextMap out of TargetPageController and into a new TabContextManager object
This is part of a larger refactor of TargetPageController and ExtensionDetailsViewController, with the goal of simplifying the tangled dependency between them and removing duplicate tab event listeners that are registered in both.
Currently, TargetPageController depends on ExtensionDetailsViewController for the sole purpose of passing ExtensionDetailsViewController a callback function, onDetailsViewTabRemoved. This function is only called from and used by ExtensionDetailsViewController, so it's strange for it to live in TargetPageController as a private method. It's there because it needs access to the TabContext to send a message the target page, and tabIdToContextMap lives in …

feat(mv3-part-3): Move tabIdToContextMap out of TargetPageController

---

src/background/background-init.ts
src/background/details-view-controller.ts
src/background/extension-details-view-controller.ts
src/background/service-worker-init.ts
src/background/tab-context-manager.ts
src/background/target-page-controller.ts
src/electron/adapters/null-details-view-controller.ts
src/tests/unit/tests/background/extension-details-view-controller.test.ts
src/tests/unit/tests/background/target-page-controller.test.ts

A continuation of the refactor started in #5436. This PR removes the callback that TargetPageController passes to ExtensionDetailsViewController and performs the functionality of the callback function itself.
Cleans up the tangled dependency between TargetPageController and ExtensionDetailsViewController.
See #5436

feat(mv3-part-3): Refactor ExtensionDetailsViewController and TargetPageController

---

src/background/background-init.ts
src/background/extension-details-view-controller.ts
src/background/service-worker-init.ts
src/background/tab-event-distributor.ts
src/background/target-page-controller.ts
src/tests/unit/common/simulated-browser-adapter.ts
src/tests/unit/tests/background/extension-details-view-controller.test.ts
src/tests/unit/tests/background/tab-event-distributor.test.ts
src/tests/unit/tests/background/target-page-controller.test.ts

Move tab event listeners in TargetPageController and ExtensionDetailsViewController into a new TabEventDistributor object, which will be the central handler for tab-related events.
This continues work in #5407, and #5415 to combine event handling into one event listener per event per context. Currently, TargetPageController and ExtensionDetailsViewController both register listeners for some of the same tab events. This PR moves those registrations into a central listener that distributes events to the appropriate functions in those controllers, similar to MessageDistributor.
After this PR, all browser events will have only one registered listener except for onConnect, which we plan to replace with onMessage as part of the move to Manifest V3.
The need for this change was identified in a …

feat(mv3-part-3): TabEventDistributor

---

targets.config.js

Add config for manifest version 3 canary release.
Feature work.
At the moment the only manifest version 3 extension we are producing is a dev build. Now that we have a working prototype of the mv3 extension, we want to create a canary release pipeline so we can start publishing to the extension store. This change adds the config so that there will be a mv3 canary version built in the drop, but note that there is not yet an accompanying release pipeline so for now the build will not be published anywhere. …

feat(mv3-part-3): Add mv3 canary drop config

---

src/background/background-init.ts
src/background/extension-details-view-controller.ts
src/background/target-page-controller.ts

This PR turns on data persistence in the stores and controllers for the manifest version 2 extension. This behavior is already turned on in the manifest v3 extension. 
Feature work.
In previous PRs we turned data persistence off to ensure that we wouldn't have backwards compat issues/ unnecessary logic in the latest release. Now that the release is finished, we want to turn persistence back on in canary to keep as close to parity as possible between mv2 and mv3 extensions. 
Note that this PR adds a persistData boolean to background-init that controls if this behavior is on or not. For future releases we will likely want to turn this behavior off again by setting persistData to false to avoid future backwards compat issues.  …

feat(mv3-part-3): Persist mv2 store and controller data

---

src/DetailsView/details-view-initializer.ts
src/Devtools/dev-tool-initializer.ts
src/background/background-init.ts
src/background/background-message-distributor.ts
src/background/service-worker-init.ts
src/background/telemetry/debug-tools-telemetry-client.ts
src/common/constants/connection-names.ts
src/common/messages.ts
src/common/store-proxy.ts
src/common/store-update-message-hub.ts
src/debug-tools/controllers/telemetry-listener.ts
src/debug-tools/debug-tools-message-distributor.ts
src/debug-tools/initializer/debug-tools-init.tsx
src/injected/main-window-initializer.ts
src/popup/popup-initializer.ts
src/tests/unit/tests/background/background-message-distributor.test.ts
src/tests/unit/tests/background/telemetry/debug-tools-telemetry-client.test.ts
src/tests/unit/tests/common/store-proxy.test.ts
src/tests/unit/tests/common/store-update-message-hub.test.ts
src/tests/unit/tests/debug-tools/controllers/telemetry-listener.test.ts
src/tests/unit/tests/debug-tools/debug-tools-message-distributor.test.ts
src/views/insights/dependencies.ts
tsconfig.strictNullChecks.json

Remove the use of connect() for telemetry in debug tools and use messages instead.
Related, minor refactors in this PR:
- Rename MessageDistributor to BackgroundMessageDistributor (to distinguish it from DebugToolsMessageDistributor)
- Rename StoreUpdateMessageDistributor to StoreUpdateMessageHub and don't have it register its own message listener (because some contexts only use the StoreUpdateMessageHub message listener, but the debug tools context needs to listen for store update messages as well as telemetry messages, and we need to keep one listener per event)
When we update to MV3, open connections are likely to trigger a watchdog timeout that will kill our service workers after five minutes. Replacing these open connections with messaging will avoid this.
Other uses of connect() …

feat(mv3-part-3): Replace debug tools telemetry connection with messages

---

pipeline/scripts/download-electron-mirror-binaries.js
pipeline/scripts/download-electron-mirror-core.js

Our build is failing because our "download custom electron binaries" step is failing. The failure occurs because we're trying to replace the default version of electron-chromedriver with an internal version. We haven't used electron-chromedriver ourselves since #4673, and it must have recently disappeared as a transitive dependency. This PR does 2 things:
1. Since we don't install the basic electron-chromedriver, don't try to replace it.
2. When extracting a zip file, be resilient if the target folder doesn't already exist. This addresses [this build failure](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=33482&view=logs&j=f0eeb669-1911-5f7c-38db-4be22817cbf3&t=d82a6554-0045-5a6d-be8e-f336c8b7f784&l=19)
Validation build …

fix: Unblock unified build failures

---

src/Devtools/dev-tool-initializer.ts
src/Devtools/dev-tool-message-distributor.ts
src/Devtools/inspect-handler.ts
src/background/actions/action-payloads.ts
src/background/actions/dev-tools-action-creator.ts
src/background/actions/dev-tools-actions.ts
src/background/background-init.ts
src/background/dev-tools-listener.ts
src/background/dev-tools-monitor.ts
src/background/service-worker-init.ts
src/background/stores/dev-tools-store.ts
src/common/message-creators/dev-tool-action-message-creator.ts
src/common/messages.ts
src/common/promises/promise-factory.ts
src/common/types/dev-tools-messages.ts
src/tests/unit/tests/DevTools/dev-tool-message-distributor.test.ts
src/tests/unit/tests/background/actions/dev-tools-action-creator.test.ts
src/tests/unit/tests/background/dev-tools-listener.test.ts
src/tests/unit/tests/background/dev-tools-monitor.test.ts
src/tests/unit/tests/common/message-creators/dev-tool-action-message-creator.test.ts

Creates DevToolsMonitor to poll active devtools for their status every 500ms until they close. It will only poll if there are active devtools. With this PR, DevToolsMonitor will poll alongside the browser connection that we currently use to detect devtools opening and closing, but the plan is for it to eventually replace that connection.
Because of the switch to MV3, we will need to replace uses of browser.connect() with message passing. However, since we use the devtools connection to detect when a devtool has closed in addition to when it opened, there isn't an easy 1:1 replacement and we'll need to implement another mechanism to detect when a devtool is no longer open. This PR implements a polling system for that purpose.
Future PRs will:
- Persist the list of active devtools in …

feat(mv3-part-3): DevToolsMonitor

---

src/background/background-init.ts
src/background/extension-details-view-controller.ts
src/background/service-worker-init.ts
src/tests/unit/tests/background/extension-details-view-controller.test.ts

After ExtensionDetailsViewController is created, make sure tabIdToDetailsViewMap only contains valid tab ids.
Fixes a bug currently in canary. Currently, if the extension is reloaded while a details view tab is open, that tab closes, but the persisted tabIdToDetailsViewMap in ExtensionDetailsViewController still contains the closed details view tab id. After a reload, if the user tries to open a details view against the same tab, the extension tries to switch to the nonexistant tab and throws an error. This PR ensures that tabIdToDetailsViewMap only contains valid tab ids after a reload.

fix: synchronize ExtensionDetailsViewController tabs with browser tabs

---

src/common/components/with-store-subscription.tsx
src/common/stores/base-client-stores-hub.ts
src/common/stores/client-stores-hub.ts
src/injected/client-store-listener.ts
src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts
src/tests/unit/tests/injected/client-store-listener.test.ts

- In injected scripts, handle a scenario where the storeHub contains stores, but not all stores have their state initialized
- Change the signature of getAllStoreData() to return a Partial instead of assuming all storeData are present
This fixes frequent error messages in the MV3 extension when a scan is started. The same error occurs silently in the MV2 extension, but does not affect the functionality of the extension.
The cause of this bug is that the injected content scripts register some store update listeners that assume the store's state already exists, which isn't the case when the scripts are first initialized, so the initial store update message throws an error. This PR assumes that none of the listeners registered by ClientStoreListener need to be called before the store state …

feat(mv3-part-4): Fix tab message errors

---

src/Devtools/dev-tool-message-distributor.ts
src/common/store-update-message-hub.ts
src/debug-tools/debug-tools-message-distributor.ts
src/tests/unit/tests/DevTools/dev-tool-message-distributor.test.ts
src/tests/unit/tests/common/store-update-message-hub.test.ts

- Allow StoreUpdateMessageHub to register async listeners
- Return a promise from StoreUpdateMessageHub if a listener is registered for that message
Feature work for MV3 migration

feat(mv3-part-4): Return a promise from StoreUpdateMessageHub

---

eslintrc.base.js
src/Devtools/dev-tool-init.ts
src/Devtools/dev-tool-initializer.ts
src/Devtools/inspect-handler.ts
src/common/components/cards/card-kebab-menu-button.tsx
src/electron/common/left-nav-item-factory.ts
src/electron/views/device-connect-view/components/electron-external-link.tsx
src/electron/views/tab-stops/tab-stops-testing-content.tsx
src/tests/electron/tests/needs-review-view.test.ts
src/tests/electron/tests/results-view.test.ts
src/tests/electron/tests/tab-stops-view.test.ts
src/tests/miscellaneous/codecs/codecs-test.js
src/tests/unit/tests/DevTools/inspect-handler.test.ts
src/tests/unit/tests/electron/views/device-connect-view/components/electron-external-link.test.tsx
src/tests/unit/tests/injected/all-frame-runner.test.ts
src/tests/unit/tests/injected/dialog-renderer.test.tsx
src/tests/unit/tests/injected/drawing-controller.test.ts
src/tests/unit/tests/injected/frameCommunicators/browser-backchannel-window-message-poster.test.ts
src/tests/unit/tests/injected/scrolling-controller.test.ts
src/tests/unit/tests/injected/visualization/null-drawer.test.ts
tools/strict-null-checks/progress.js

Turns on the [no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md) eslint rule for all directories except background/ and injected/, and fixes the errors that were caught.
This PR fixes 26 issues caught by this rule out of 48 in total. The issues fixed in this PR are fairly minor, and the remaining issues in background/ and injected/ are more complex and involve changes that propagate more to other files. Those issues will be addressed in future PRs.
The no-floating-promises rule was turned off when we migrated from tslint to eslint due to a large number of failures, and was never reenabled. This would be an extremely useful rule to have, especially with the ongoing migration to Manifest V3, to …

chore: turn on no-floating-promises for most directories

---

src/DetailsView/details-view-initializer.ts
src/Devtools/dev-tool-init.ts
src/background/background-init.ts
src/common/browser-adapters/browser-adapter-factory.ts
src/common/is-supported-browser.ts
src/debug-tools/initializer/debug-tools-init.tsx
src/injected/window-initializer.ts
src/popup/popup-init.ts
src/views/insights/initializer.ts

Changes all imports of UAParser to use default style imports.
Necessary for esbuild to function.
Tested dev, prod, and unified to ensure they were still working with these changes.
It seems like this was always an issue that webpack just handled for us; both tsc and esbuild complain about these imports. The esbuild error looks like this:
```Constructing "UAParser" will crash at run-time because it's an import namespace object, not a constructor```
and tsc (with esModuleInterop flag set to true):
```Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.```
Some more info on esbuild and how it imports here: …

feat(esbuild): use default import for UAParser

---

src/common/browser-adapters/browser-event-manager.ts
src/common/promises/promise-factory.ts
src/tests/unit/common/time-simulating-promise-factory.ts
src/tests/unit/tests/common/browser-adapters/browser-event-manager.test.ts
src/tests/unit/tests/common/promises/promise-factory.test.ts

This PR makes 2 improvements to ease debugging of `browser-event-manager` timeouts:
* It reduces the default timeout/fnf delay from 4min/2min to 1min/30s, respectively
* The original timeouts were chosen mostly based on "being slightly less than the browser's 5min timeout". However, these new timeout values are still plenty high enough that anything hitting them in practice is a bug we should fix, while cutting the time required for a human to sit around waiting to trigger an issue by a factor of 4
* It updates `promiseFactory.timeout` to support an `errorContext` parameter to include in `TimeoutError`s, and updates `BrowserEventManager` to use that to inject details of the event that timed out into the message
* Previously, a browser event timeout message only showed that "some event's …

feat(mv3-part-4): Improve browser event timeout debugability

---

src/background/stores/card-selection-store.ts
src/background/stores/needs-review-card-selection-store.ts
src/background/stores/tab-context-store-hub.ts
src/common/get-card-selection-view-data.ts
src/common/types/store-data/card-selection-store-data.ts
src/electron/views/renderer-initializer.ts
src/injected/element-based-view-model-creator.ts
src/tests/unit/tests/DetailsView/store-mocks.ts
src/tests/unit/tests/background/stores/card-selection-store.test.ts
src/tests/unit/tests/background/stores/needs-review-card-selection-store.test.ts
src/tests/unit/tests/common/get-card-selection-view-data.test.ts
src/tests/unit/tests/injected/element-based-view-model-creator.test.ts

- Make CardSelectionStoreData.rules nullable and set it to null by default
- Reset CardSelectionStoreData to the default state when the target tab URL changes
- Do not try to get a selectorMap if CardSelectionStoreData.rules is null
This fixes an issue exposed by #5537. When the Automated checks or Needs review ad hoc visualizers are enabled, the DrawingController receives two requests, one with an empty list, and one with the correct list of elements to highlight. This is caused by two consecutive store updates, one to UnifiedScanResultStore and one to CardSelectionStore, which both trigger a visualization update. Between these two store updates, stale data in CardSelectionStore causes DrawingController to receive an empty list of elements. While working on #5537, we saw these two …

feat(mv3-part-4): Avoid using stale data in CardSelectionStore

---

.stylelintrc.js
src/common/components/header.scss
src/common/icons/icon.scss
src/common/styles/common.scss
src/reports/automated-checks-report.scss
src/reports/components/header-bar.scss
src/reports/components/report-sections/common-mixins.scss
src/reports/components/report-sections/content-container.scss
src/reports/components/report-sections/details-section.scss
src/reports/components/report-sections/footer-section.scss
src/reports/components/report-sections/header-section.scss
src/reports/components/report-sections/summary-report-details-section.scss
src/reports/components/report-sections/urls-summary-section.scss

Enables and makes required fixes for the stylelint rule [`scss/at-mixin-pattern`](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/at-mixin-pattern/README.md). The default pattern is kebab case and this pull request will update mixins that do not follow the pattern.
Part of https://github.com/microsoft/accessibility-insights-web/issues/5187 as an incremental task to enable stylelint rules.

chore: Enable stylelint rule `scss/at-mixin-pattern`

---

src/background/actions/action-creator.ts
src/background/actions/inspect-action-creator.ts
src/background/actions/tab-action-creator.ts
src/background/background-init.ts
src/background/browser-message-broadcaster-factory.ts
src/background/service-worker-init.ts
src/background/telemetry/exception-telemetry-listener.ts
src/common/extension-telemetry-events.ts
src/common/logging/default-logger.ts
src/common/navigator-utils.ts
src/injected/frameCommunicators/axe-frame-messenger.ts
src/injected/frameCommunicators/respondable-command-message-communicator.ts
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/actions/inspect-action-creator.test.ts
src/tests/unit/tests/background/actions/tab-action-creator.test.ts
src/tests/unit/tests/background/browser-message-broadcaster-factory.test.ts
src/tests/unit/tests/background/telemetry/exception-telemetry-listener.test.ts
src/tests/unit/tests/common/navigator-utils.test.ts

Adding `ExceptionTelemetryListener`, which listens to for unhandled exceptions and promise rejections and sends telemetry information.
Feature work.
This PR only adds exception listening for the background, follow up PRs will add logic to also send telemetry information from other contexts. 

feat(mv3-part-4): Add exception telemetry listener

---

eslintrc.base.js
src/injected/frameCommunicators/axe-frame-messenger.ts
src/injected/frameCommunicators/browser-backchannel-window-message-poster.ts
src/injected/frameCommunicators/respondable-command-message-communicator.ts
src/tests/unit/common/linked-respondable-communicator.ts
src/tests/unit/common/linked-window-message-poster.ts
src/tests/unit/tests/injected/frameCommunicators/axe-frame-messenger.test.ts
src/tests/unit/tests/injected/frameCommunicators/browser-backchannel-window-message-poster.test.ts
src/tests/unit/tests/injected/frameCommunicators/respondable-command-message-communicator.test.ts

Fixes the last no-floating-promises issue in BackchannelMessagePoster and FrameMessengers, and enable the no-floating-promises rule everywhere.
Continuing work from #5537, #5517, #5524

feat(mv3-part-4): fix remaining no-floating-promises issue

---

src/Devtools/dev-tool-initializer.ts
src/Devtools/inspect-handler.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/webextension-browser-adapter.ts

Today, if you open a dev tools console against our background page, you 2 lines of spurious warning spew to the console like this:
```
Unable to interpret message -  {messageType: 'insights/devtools/opened', tabId: -1}
```
This happens because our `dev-tools-init` attempts to run in the context of the background page's dev tools. The background page has no associated window/tab, so this confuses the background page itself because there is no tab context to accept the initialization message.
To avoid the spurious warning, this PR makes the dev tools initializer detect the "no inspected tab" case and bail from initialization since there's nothing for our dev tools code to actually do in that case.
Avoid spurious console spew
n/a
- [n/a] …

feat(mv3-part-4): avoid spurious background console spew when opening background devtools

---

Gruntfile.js
esbuild.js
package.json
packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-baseline-aware-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
pipeline/build-package.template.yaml
style-plugin.js

Uses esbuild for report package. Updates the snapshots as well.
esbuild is faster than webpack.
I smoke tested each snapshot to validate that the UI was unchanged compared to main.
Removing the webpack config code is planned for a separate/future PR (would like to make that change altogether, after the ui package is done, _hopefully_)

feat(esbuild): use esbuild for report package

---

src/injected/main-window-initializer.ts
src/injected/window-initializer.ts

Fix bug in which browser event manager errors when content scripts are run in pages with iframes. These errors were caused by registering browser event listeners but never handling events properly. The fix implemented here is to register no browser event listeners in iframes, as iframes don't need them anyways. 
Fix bug introduced by feature work.
Bug repro steps before this change:
- Run checks on a page with iframes (for example all.html test resource)
- Wait ~1 min
- Observe timeout errors from browser event manager. 

feat(mv3-part-4): Fix content script browser event bug

---

src/debug-tools/components/telemetry-viewer/telemetry-viewer.tsx
src/debug-tools/controllers/telemetry-listener.ts
src/tests/unit/tests/debug-tools/components/telemetry-viewer/telemetry-viewer.test.tsx
src/tests/unit/tests/debug-tools/controllers/telemetry-listener.test.ts

Today, when toggling the debug tools UI from the telemetry viewer back to the store viewer, it emits the following error:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
in TelemetryViewer (created by CurrentView)
```
This happens because `TelemetryViewer.componentDidMount` registers a listener that `TelemetryViewer.componentWillUnmount` does not remove.
This PR fixes the warning by ensuring that the listener is removed on unmount of the viewer.
Avoid unnecessary error spew
n/a
- [n/a] (UI …

fix(debug-tools): remove telemetry listener on viewer unmount

---

src/background/telemetry/app-insights-telemetry-client.ts
src/background/telemetry/console-telemetry-client.ts
src/background/telemetry/debug-tools-telemetry-client.ts
src/background/telemetry/multiplexing-telemetry-client.ts
src/background/telemetry/telemetry-client.ts
src/background/telemetry/telemetry-event-handler.ts
src/tests/unit/tests/background/telemetry/app-insights-telemetry-client.test.ts
src/tests/unit/tests/background/telemetry/console-telemetry-client.test.ts
src/tests/unit/tests/background/telemetry/debug-tools-telemetry-client.test.ts
src/tests/unit/tests/background/telemetry/multiplexing-telemetry-client.test.ts
src/tests/unit/tests/background/telemetry/telemetry-event-handler.test.ts

This PR reverts a part of #5524 that involved making our telemetry clients' `trackEvent` async in the interest of propogating the return value of the `browserAdapter.sendRuntimeMessage` call used by `debug-tools-telemetry-client.ts`.
The issue with that strategy is that it doesn't cooperate with the new unhandled promise rejection hook added by #5550 - particularly, the hook ends up entering an infinite loop if that `sendRuntimeMessage` call fails for any reason. You can see this by clean-installing a dev build of the extension, opening the background page devtools from the extension management page, and enabling the console telemetry logging and debug tools feature flags from the background console (never opening any other extension page/popup UI).
Instead, this PR:
* Reverts …

feat(mv3-part-4): revert async-ification of trackEvent

---

src/debug-tools/debug-tools-message-distributor.ts
src/tests/unit/tests/debug-tools/debug-tools-message-distributor.test.ts

This PR fixes an issue that @sfoslund and I discovered while validating #5591. @pownkel and @sfoslund did some outstanding debugging to find the root cause.
The symptom we observed that this fixes is that, with #5591, we would sometimes (~30-60% of the time) see messages get lost between different frames of a target page with iframes. The root cause of this wasn't actually loss of the window messages between the frames, it was the loss of some of the messages used by out background backchannel infrastructure in communication between one of the frames and the background page.
We were very confused in debugging this for a while because it was inconsistent; sometimes it would repro half the time, and sometimes not at all. @sfoslund eventually narrowed down that the issue seemed to only repro …

fix(mv3-part-4): prevent debug tools window from eating other windows' messages

---

src/tests/unit/tests/common/components/cards/card-kebab-menu-button.test.tsx

This PR resolves an issue where running `yarn test -- -- card-kebab-menu-button` passes but emits 2 copies of the following error spew:
```
console.error
Warning: An update to ForwardRef inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
in ForwardRef
in ForwardRef (created by StyledCalloutContentBase)
in StyledCalloutContentBase (created by Callout)
in div (created by FabricBase)
in FabricBase (created by StyledFabricBase)
in StyledFabricBase (created by LayerBase)
in span (created by LayerBase)
in …
```

chore: fix error spew in card-kebab-menu-button unit tests

---

.github/workflows/ci.yml
package.json

Specifies maxWorkers to 2 for our CI build in GH action.
Speeds up CI builds.
I came upon this post: https://bharathvaj.me/blog/speedup-jest-github-actions.
TLDR: Linux VMs on GH Action have two cores (link to GH docs [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)) but jest defaults to only using one. This specifies using both. Our unit-tests were previously the slowest portion of our CI builds in GH action and this makes them see about a 40%-50% decrease in runtime. More importantly, this makes the e2e/unified tests our longest-running tasks (saving roughly 2-3 minutes per PR build, about a 25% decrease, based off looking at the last 10-15 successful builds without this change).

fix: use maxWorkers=2 for GitHub Action CI build

---

src/common/telemetry/exception-telemetry-listener.ts
src/tests/unit/tests/common/telemetry/exception-telemetry-listener.test.ts

Replace `window` in ExceptionTelemetryListener with `globalThis`.
Fixes a bug in the MV3 version of the extension. ExceptionTelemetryListener is referenced by SendingExceptionTelemetryListener, which is used in the service worker. Since `window` doesn't exist in the service worker, attempting to initialize SendingExceptionTelemetryListener crashes the service worker initialization script. Using [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) instead will keep the same functionality in non-background contexts while fixing the error in the service worker.

fix: Use globalThis in ExceptionTelemetryListener instead of window

---

package.json
yarn.lock

Force updates to two transitive dependencies:
- Update got from 9.6.0 to 11.8.5
- Update jpeg-js from 0.4.2 to 0.4.4
Addresses two dependabot security alerts
Smoke tested the electron app to make sure that updating a major version of got (transitive dependency through electron) didn't break anything.

chore(deps): update got and jpeg-js

---

src/DetailsView/components/choice-group-pass-fail.tsx
src/tests/unit/tests/DetailsView/components/choice-group-pass-fail.test.tsx
src/tests/unit/tests/DetailsView/components/test-status-choice-group.test.tsx

Fixes an issue with `ChoiceGroupPassFail` where the undo button appeared when neither Pass/Fail were selected. The expected behavior is for the undo button to appear after the user makes a selection. This bug affects the `TestStatusChoiceGroup` implementation. This pull request will also propose that the labeled variant will also hide the undo button until user makes a selection.
The table below present screenshots for the following environments for `TestStatusChoiceGroup`: On production, the undo button appears after selection when in a row. On Canary, the undo button always appears. With this pull request, the undo button will appear after selection when in a row (to match original state of production). 
Production  | Canary | This pull request
---|---|---
| …

fix: Only show undo button in ChoiceGroupPassFail when an option is selected

---

package.json
src/tests/end-to-end/common/prepare-test-result-file-path.ts
yarn.lock

`yarn test:unified` has functionality to take screenshots when errors occur, but it looks like it was broken at some point. I suspect the issue is that our use of the `make-dir` library to ensure the screenshot directory exists was broken when we switched the tests to use swc for transpilation and we never noticed.
Using a whole library just for this functionality is unnecessary; `fs.promises.mkdir` works just fine for this, so I ripped out the library and replaced it with the builtin verison.
Fix unified e2e error reporting to help debug the issue Tania is seeing today
n/a …

test: fix unified screenshot on error

---

src/popup/components/launch-pad.tsx
src/popup/components/popup-view.tsx
src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
src/tests/unit/tests/popup/components/__snapshots__/popup-view.test.tsx.snap

Removes unnecessary title and label for demo link.
fixes a label-name-content-mismatch true positive failure in needs review.
Title and label aren't needed because the text is self-explanatory for the link.

fix: demo link label-name-content-mismatch failure

---

.github/workflows/ci.yml

This pull request will update CodeQL to v2 and set up dotnet for CodeQL by adding the [autobuild step](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-the-codeql-workflow-for-compiled-languages#about-autobuild-for-codeql).
CodeQL is failing on several builds when attempting to run csharp with:
> Error: No code found during the build. Please see:
>  https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/troubleshooting-code-scanning#no-code-found-during-the-build
We added csharp to this repo in #5720, the codeql build for that pull request did not detect csharp and so the run passed ([passed](https://github.com/microsoft/accessibility-insights-web/runs/7307739514?check_suit …

chore: Upgrade codeql to v2 and enable autobuild to support csharp

---

yarn.lock

This PR updates us to the latest `browserslist` database, using the following command:
`npx browserslist@latest --update-db`.
Ref: https://github.com/browserslist/browserslist#browsers-data-updating
Latest version:     1.0.30001366
Installed version:  1.0.30001299
Stay up-to-date and remove warning message when building this project.

chore(deps): Update browserslist

---

src/background/background-init.ts
src/background/service-worker-init.ts
src/background/stores/tab-context-store-hub.ts
src/background/stores/tab-store.ts
src/background/tab-context-factory.ts
src/common/url-parser.ts
src/tests/unit/common/tab-store-data-builder.ts
src/tests/unit/tests/background/stores/tab-context-store-hub.test.ts
src/tests/unit/tests/background/stores/tab-store.test.ts
src/tests/unit/tests/background/tab-context-factory.test.ts
src/tests/unit/tests/common/url-parser.test.ts

* Moves some URL-origin-parsing logic specific to `TabStore` out into `UrlParser` for ease of testing
* Adds support to the logic to handle invalid URL cases
`UrlParser` has no dependencies and there is no other component in the background that uses `UrlParser` today, so I just initialized it in the `TabStore` directly rather than piping it around everywhere.
Addresses issue #5753
I don't have a good way to test the change locally, since we don't have consistent repro steps, but the root cause seems easy enough to understand and it shows up commonly enough in insider/canary telemetry that we should be able to determine if the fix worked by checking there in a few days. …

fix: avoid crashing when a browser tab has an invalid URL

---

src/common/extension-telemetry-events.ts
src/common/message-creators/dev-tool-action-message-creator.ts
src/common/telemetry-data-factory.ts
src/tests/unit/tests/common/message-creators/dev-tool-action-message-creator.test.ts
src/tests/unit/tests/common/telemetry-data-factory.test.ts

When the 'inspect' button is clicked, we don't want some of the current fields in telemetry. This PR removes the extra properties so that the sent data is limited.
Limit the amount of data in telemetry
Once #5728 is merged, I might explore whether we can restrict `BaseTelemetryData` to exclude properties with the type `Target`. This might help avoid regressing the behavior in the future.

fix: remove extra fields in InspectTelemetryData

---

src/tests/unit/tests/background/actions/assessment-action-creator.test.ts
src/tests/unit/tests/background/actions/card-selection-action-creator.test.ts
src/tests/unit/tests/background/actions/content-action-creator.test.ts
src/tests/unit/tests/background/actions/details-view-action-creator.test.ts
src/tests/unit/tests/background/actions/dev-tools-action-creator.test.ts
src/tests/unit/tests/background/actions/injection-action-creator.test.ts
src/tests/unit/tests/background/actions/inspect-action-creator.test.ts
src/tests/unit/tests/background/actions/needs-review-card-selection-action-creator.test.ts
src/tests/unit/tests/background/actions/needs-review-scan-result-action-creator.test.ts
src/tests/unit/tests/background/actions/path-snippet-action-creator.test.ts
src/tests/unit/tests/background/actions/popup-action-creator.test.ts
src/tests/unit/tests/background/actions/tab-action-creator.test.ts
src/tests/unit/tests/background/actions/tab-stop-requirement-action-creator.test.ts
src/tests/unit/tests/background/actions/unified-scan-result-action-creator.test.ts
src/tests/unit/tests/background/global-action-creators/action-creator-test-helpers.ts
src/tests/unit/tests/background/global-action-creators/mock-interpreter.ts
src/tests/unit/tests/background/global-action-creators/permissions-state-action-creator.test.ts
src/tests/unit/tests/debug-tools/action-creators/debug-tools-action-creator.test.ts

Replace `createInterpreterMock` with a new `MockInterpreter` class in unit tests
Currently, most tests for -ActionCreator classes use `createInterpreterMock`, which calls a callback as it is registered in the interpreter with `registerTypeToPayloadCallback`. This works fine for synchronous callbacks, but there is no way to await an async call back with this strategy, since `registerTypeToPayloadCallback` is synchronous. Currently, the few ActionCreators that register async callbacks just use `awaitSettledPromises()` to ensure that the async callback completes.
This PR creates a mock wrapper class that separates callback registration from actually calling the callback, so async callbacks can be awaited without using `awaitSettledPromises`. This also makes the sequence of events clearer in …

refactor(mv3-part-5): MockInterpreter

---

.github/fabricbot.json

Adding a fabricbot task that will add comments to PRs that touch store data, asking PR authors to consider backwards compatibility. The bot will comment `This PR modifies store data, which is persisted between runs of the web extension. Please consider backwards compatibility when modifying these data types.` (looking for feedback on this wording!).
Feature work.
I'm not very familiar with fabricbot config so I'm not totally sure why the tool removed the existing ids. If anyone is more familiar, please let me know if this is correct or not. For context, I followed these docs to generate this JSON: https://1esdocs.azurewebsites.net/datainsights/merlinbot/extensions/Bot-config-as-code.html and https://portal.fabricbot.ms/bot/
This is part of an effort to ensure that we consider backwards …

feat(mv3-part-5): Add backwards compat PR comment config to fabricbot

---

.github/fabricbot.json

Follow up to https://github.com/microsoft/accessibility-insights-web/pull/5765, ensures that the backwards compat comment is only added once. 
Feature work.
See https://github.com/microsoft/accessibility-insights-web/pull/5765

feat(mv3-part-5): Only add backwards compat comment on PR open

---

.vscode/extensions.json

The original "Debugger for Chrome" https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome is deprecated. Swapping for the recommended replacement https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug
Recommended extension is deprecated.

chore: Change workspace recommendation for debugger extension

---

src/DetailsView/details-view-body.scss
src/tests/end-to-end/tests/details-view/headings.test.ts

* set icon to use `$always-black` rather than `$secondary-text`, so it doesn't end up white on light yellow in high contrast mode
* restyle button/link in message bar to always use underline and to inherit the regular text color of the message bar - avoids yellow button/link on light yellow in high contrast, but also improves visibility of the link in regular contrast mode
Closes https://github.com/microsoft/accessibility-insights-web/issues/5757
In regular contrast mode, any button/link inside the message bar is not very obvious - and the difference between the blue button/link and the adjacent static text is relatively low.
More importantly/critically, when set to high contrast, the little "i" info icon turns white on light yellow, and the button/link uses yellow text on light yellow …

fix: message bar icon in high contrast, and restyle message bar button/link

---

src/common/target-helper.ts
src/tests/unit/tests/common/target-helper.test.ts

Fix bug introduced by https://github.com/microsoft/accessibility-insights-web/pull/5728 in which visualizations would not appear on pages which have nested shadow dom selectors.
Bug fix
See https://github.com/microsoft/accessibility-insights-web/pull/5728.

fix: Fix shadow host visualization bug

---

src/tests/end-to-end/test-resources/nested-shadow-doms.html
src/tests/end-to-end/tests/target-page/__snapshots__/visualization-boxes.test.ts.snap
src/tests/end-to-end/tests/target-page/visualization-boxes.test.ts

Follow up to https://github.com/microsoft/accessibility-insights-web/pull/5783, adding e2e test coverage for this bug fix. 
Expand test coverage
See https://github.com/microsoft/accessibility-insights-web/pull/5783

fix: Add e2e test for nested shadow dom visualizations

---

src/background/actions/launch-panel-state-action.ts
src/background/global-action-creators/global-action-creator.ts
src/background/stores/base-store-impl.ts
src/background/stores/global/launch-panel-store.ts

Convert launch panel state actions from SyncAction to AsyncAction
Feature work
N/a

feat(mv3-part-5): Convert launch panel state actions to async

---

src/background/actions/action-creator.ts
src/background/actions/assessment-action-creator.ts
src/background/actions/assessment-actions.ts
src/background/stores/assessment-store.ts
src/common/flux/scope-mutex.ts
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/actions/assessment-action-creator.test.ts
src/tests/unit/tests/background/stores/assessment-store.test.ts

Convert all SyncActions in AssessmentActions to AsyncActions
Feature work
Some of the messages that AssessmentActionCreator listens for also have other listeners registered in ActionCreator. Messages are interpreted concurrently using both the global context and the tab context, and since some of the messages affected by this change have listeners in both contexts, some of the now-async actions may be invoked concurrently. This shouldn't be a problem, except that the current Action classes have built-in measures to prevent two actions from running at the same time in the same "scope." To avoid spurious exceptions, this PR adds a "scope" parameter to Action.invoke() calls inside listeners that may run concurrently with other listeners (i.e. listeners for messages that have multiple …

feat(mv3-part-5): Convert AssessmentActions to AsyncActions

---

eslintrc.base.js
src/DetailsView/tab-stops-requirements-with-instances.tsx
src/content/test/images/images-of-text.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/tab-stops-requirements-with-instances.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/summary-results-table.test.tsx

When running `yarn test` I noticed a key prop error: `Warning: Each child in a list should have a unique "key" prop.` This pull request will enable (set to `error`) and make the required fixes.
Reduce `console.errors` in test output and make sure [React items have a stable identity](https://reactjs.org/docs/lists-and-keys.html#keys).
In looking back at the history for [react/jsx-key](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-key.md), I believe it was disabled when switching from tslint to eslint https://github.com/microsoft/accessibility-insights-web/pull/3273 as a means to unblock the migration. Please correct me if I'm wrong :) …

chore: Enable react/jsx-key

---

src/background/stores/assessment-store.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/webextension-browser-adapter.ts
src/tests/unit/common/simulated-browser-adapter.ts
src/tests/unit/tests/background/stores/__snapshots__/assessment-store.test.ts.snap
src/tests/unit/tests/background/stores/assessment-store.test.ts

- Replace the last use of getTab with getTabAsync, and remove getTab from BrowserAdapter
- Add unit tests for some uncovered lines/branches in AssessmentStore
getTabAsync was added in #5538, but we were unable to completely remove the synchronous getTab function because AssessmentStore calls it as an action callback, and all action callbacks were synchronous at the time. Now that we have AsyncAction, we can use getTabAsync instead.

refactor(mv3-part-5): Assessment store improvements

---

src/background/actions/needs-review-scan-result-action-creator.ts
src/background/actions/needs-review-scan-result-actions.ts
src/background/stores/needs-review-card-selection-store.ts
src/background/stores/needs-review-scan-result-store.ts
src/tests/unit/tests/background/actions/needs-review-scan-result-action-creator.test.ts

Convert NeedsReviewScanResultActions from SyncAction to AsyncAction
Feature work
N/a

feat(mv3-part-5): Convert NeedsReviewScanResultActions to async

---

src/background/actions/assessment-action-creator.ts
src/background/actions/assessment-actions.ts
src/background/interpreter.ts
src/tests/unit/tests/background/actions/assessment-action-creator.test.ts

Add the key from the payload to the action executing scope for scanCompleted callbacks
This fixes a scope conflict when Automated Checks runs in Assessment, and several scanCompleted messages are sent concurrently.

feat(mv3-part-5): Add key to scope for scanCompleted action

---

src/background/actions/path-snippet-action-creator.ts
src/background/actions/path-snippet-actions.ts
src/background/stores/path-snippet-store.ts
src/tests/unit/tests/background/actions/path-snippet-action-creator.test.ts

Convert PathSnippetActions from SyncAction to AsyncAction
Feature work
N/a

feat(mv3-part-5): Convert PathSnippetActions to async

---

src/assessments/headings/test-steps/no-missing-headings.tsx

Change guidance link for NoMissingHeadings test from WCAG 2.4.1 to WCAG 2.4.6
Addresses #5746 
Tested in dev build when exporting JSON. missingHeadings test is listed under WCAG 2.4.6, where it was previously listed under WCAG 2.4.1

fix: NoMissingHeadings test guidance link

---

package.json
yarn.lock

Address https://github.com/microsoft/accessibility-insights-web/security/dependabot/30 that calls out a potential ReDoS attack in `moment@2.29.2` (and fixed in `moment@2.29.4`). This package is consumed by `appium-support`, which is consumed by `appium-adb`. It's logical to assume that we will eventually no longer need this resolution after some time to allow both of these packages to update.. Comparing the `moment` code between 2.29.2 and 2.29.4, 2.29.3 updated a support link and 2.29.4 changed the vulnerable RegEx. Neither of these should have any potential to break our usage.
Address https://github.com/microsoft/accessibility-insights-web/security/dependabot/30
- [n/a] Verified code coverage for the changes made. Check …

fix: Resolve moment (address ReDoS flaw)

---

src/background/actions/permissions-state-actions.ts
src/background/global-action-creators/permissions-state-action-creator.ts
src/background/stores/global/permissions-state-store.ts
src/tests/unit/tests/background/global-action-creators/permissions-state-action-creator.test.ts

Convert PermissionsStateActions from SyncAction to AsyncAction
Feature work
N/a

feat(mv3-part-5): Convert PermissionsStateActions to async

---

src/background/actions/details-view-action-creator.ts
src/background/actions/details-view-actions.ts
src/background/stores/details-view-store.ts
src/tests/unit/tests/background/actions/details-view-action-creator.test.ts

Convert SyncActions in DetailsViewActions to AsyncActions
Feature work
n/a

feat(mv3-part-5): convert DetailsViewActions to async

---

src/background/actions/action-creator.ts
src/background/actions/visualization-scan-result-actions.ts
src/background/stores/visualization-scan-result-store.ts

Convert VisualizationScanResultActions from SyncAction to AsyncAction
Feature work
N/a

feat(mv3-part-5): Convert VisualizationScanResultActions to async

---

src/DetailsView/components/tab-stops/tab-stops-failed-instance-panel.tsx
src/DetailsView/components/tab-stops/tab-stops-instance-section-props-factory.tsx
src/DetailsView/components/tab-stops/tab-stops-requirements-table.tsx
src/DetailsView/components/tab-stops/tab-stops-test-view-controller.ts
src/DetailsView/components/tab-stops/tab-stops-view-actions.ts
src/DetailsView/components/tab-stops/tab-stops-view-store.ts
src/tests/unit/tests/DetailsView/components/tab-stops/tab-stops-test-view-controller.test.tsx

Convert TabStopsViewActions from SyncAction to AsyncAction
Feature work
N/a

feat(mv3-part-5): Convert TabStopsViewActions to async

---

src/common/types/store-data/unified-data-interface.ts
src/injected/adapters/scan-results-to-unified-results.ts
src/injected/element-based-view-model-creator.ts
src/tests/end-to-end/test-resources/uncommon-characters.html
src/tests/end-to-end/tests/target-page/__snapshots__/visualization-boxes.test.ts.snap
src/tests/end-to-end/tests/target-page/visualization-boxes.test.ts
src/tests/unit/tests/injected/adapters/__snapshots__/scan-results-to-unified-results.test.ts.snap
src/tests/unit/tests/injected/element-based-view-model-creator.test.ts

Fixes visualizations for elements that include special characters in their selectors. This addresses issue #5735 as well as an instance @pownkel was running into in which automated checks visualizations were not showing up on some github PR web pages (for example, https://github.com/microsoft/accessibility-insights-web/pull/5745)
Addresses issue #5735
https://github.com/microsoft/accessibility-insights-web/pull/5728 allowed us to preserve the target in the state that we receive it from axe throughout our logic instead of serializing it into a string as we used to do. This PR removes one more instance of stringifying then converting the target string back into an array. We want to get rid of this logic because it doesn't work with elements that have special characters in their selectors, …

fix: Fix visualizations for elements that include semicolons/commas

---

build.yaml
pipeline/build-all-job-per-environment.yaml
pipeline/e2e-job-per-environment.yaml
pipeline/unified/build-unsigned-release-packages.yaml
pipeline/unified/channel/sign-release-package-mac.yaml
pipeline/unified/unified-e2e-job-per-environment.yaml

MacOS 10.15 is being phased out as a virtual environment. We're getting the following warnings in our builds:
```
The macOS-10.15 environment is deprecated, consider switching to macos-11(macos-latest), macos-12 instead. For more details see https://github.com/actions/virtual-environments/issues/5583
```
This PR simply changes all instances of `macOS-10.15` to `macOS-11`.
We could use `macOS-latest` to avoid having to touch these files in the future, but deprecations are infrequent and having an explicit version makes it easier to identify cases where tests potentially fail after changing OS versions.
We could use `macOS-12`, but that would leave downlevel clients with no testing in our pipeline. Since most of our internal testing will be on macOS 12 (required for security reasons), using …

chore: Update mac environment from 10.15 to 11

---

src/background/actions/unified-scan-result-action-creator.ts
src/background/actions/unified-scan-result-actions.ts
src/background/stores/card-selection-store.ts
src/background/stores/unified-scan-result-store.ts
src/electron/flux/action-creator/scan-action-creator.ts
src/electron/flux/action/scan-actions.ts
src/electron/flux/store/scan-store.ts
src/electron/platform/android/scan-controller.ts
src/electron/views/results/results-view.tsx
src/tests/unit/tests/background/actions/unified-scan-result-action-creator.test.ts
src/tests/unit/tests/electron/flux/action-creator/scan-action-creator.test.ts
src/tests/unit/tests/electron/platform/android/scan-controller.test.ts

- Convert SyncActions in UnifiedScanResultActions to AsyncActions
- Convert ScanActions.scanStarted to an AsyncAction because the listener already contains a floating promise
Feature work
ScanActions is only used in the electron app, so not all actions need to be made async, but it seemed like a good idea to convert the one that was already essentially async. I've verified this change in Unified as well.

feat(mv3-part-5): Convert UnifiedScanResultActions to async

---

src/background/actions/tab-stop-requirement-action-creator.ts
src/background/actions/tab-stop-requirement-actions.ts
src/background/stores/visualization-scan-result-store.ts
src/tests/unit/tests/background/actions/tab-stop-requirement-action-creator.test.ts

Convert TabStopRequirementActions from SyncAction to AsyncAction
Feature work
N/a

feat(mv3-part-5): Convert TabStopRequirementActions to async

---

esbuild.js

While debugging https://github.com/microsoft/accessibility-insights-action/pull/1230, I noticed that the report package is now ESM. I believe this was set during the esbuild switch (ref https://github.com/microsoft/accessibility-insights-web/pull/5528) and that we will want to keep the report package (at least for now) commonjs. This PR switches the format for the report package back to cjs.

fix: Set report package format to cjs

---

src/common/flux/event-handler-list.ts
src/common/flux/store.ts
src/tests/unit/tests/common/flux/event-handler-list.test.ts
src/tests/unit/tests/common/flux/store.test.ts

Allow event handler list and store to support sync or async callbacks. This PR does not change specific stores but it enables us to convert specific stores to accept async callbacks in the future. 
Feature work
We were originally planning on making all stores use async callbacks as part of the mv3 effort, but this would mean having to make a lot of unnecessary changes to both web and unified code. Instead, we're planning to switch to this approach, which will allow us to only add async callback support to stores whose callbacks actually do async work. This will result in fewer unnecessarily async actions as well as fewer changes (and no functional changes) to unified code. 
- …

feat(mv3-part-5): Allow event handler list and store to support async and sync listeners

---

src/background/actions/permissions-state-actions.ts
src/background/global-action-creators/permissions-state-action-creator.ts
src/background/stores/global/permissions-state-store.ts
src/tests/unit/tests/background/global-action-creators/permissions-state-action-creator.test.ts

The changes in https://github.com/microsoft/accessibility-insights-web/pull/5877 allow us keep any actions that don't have any async work in any listeners to remain synchronous. As a result, we want to revert PermissionStateActions to be sync, since they do not do any async work.
Feature work
We considered/ were planning on converting all actions to be async (even if they had no async work) but decided that this caused too many unnecessary changes (particularly to the electron code) so went with this solution instead. 

feat(mv3-part-5): Revert permission state actions to sync

---

src/background/actions/scoping-actions.ts
src/background/global-action-creators/scoping-action-creator.ts
src/background/stores/global/scoping-store.ts
src/tests/unit/tests/background/global-action-creators/scoping-action-creator.test.ts

The changes in https://github.com/microsoft/accessibility-insights-web/pull/5877 allow us keep any actions that don't have any async work in any listeners to remain synchronous. As a result, we want to revert ScopingActions to be sync, since they do not do any async work.
Feature work
We considered/ were planning on converting all actions to be async (even if they had no async work) but decided that this caused too many unnecessary changes (particularly to the electron code) so went with this solution instead. 

feat(mv3-part-5): Revert scoping actions to be sync

---

src/background/actions/action-creator.ts
src/background/actions/content-action-creator.ts
src/background/actions/content-actions.ts
src/background/actions/details-view-action-creator.ts
src/background/actions/details-view-actions.ts
src/background/actions/side-panel-actions.ts
src/background/stores/details-view-store.ts
src/tests/unit/tests/background/actions/content-action-creator.test.ts
src/tests/unit/tests/background/actions/details-view-action-creator.test.ts

The changes in https://github.com/microsoft/accessibility-insights-web/pull/5877 allow us keep any actions that don't have any async work in any listeners to remain synchronous. As a result, we want to revert actions that act on the details view store to be sync, since that store does not have any async work.
Feature work
We considered/ were planning on converting all actions to be async (even if they had no async work) but decided that this caused too many unnecessary changes (particularly to the electron code) so went with this solution instead. 

feat(mv3-part-5): Revert async actions for details view store

---

src/background/actions/user-configuration-actions.ts
src/background/global-action-creators/user-configuration-action-creator.ts
src/background/stores/global/user-configuration-store.ts
src/tests/unit/tests/background/global-action-creators/user-configuration-action-creator.test.ts

The changes in https://github.com/microsoft/accessibility-insights-web/pull/5877 allow us keep any actions that don't have any async work in any listeners to remain synchronous. As a result, we want to revert actions that act on the user configuration store to be sync, since that store does not have any async work.
Feature work
We considered/ were planning on converting all actions to be async (even if they had no async work) but decided that this caused too many unnecessary changes (particularly to the electron code) so went with this solution instead. 

feat(mv3-part6): Revert user config store actions to be sync

---

src/background/actions/action-creator.ts
src/background/actions/card-selection-action-creator.ts
src/background/actions/card-selection-actions.ts
src/background/actions/visualization-scan-result-actions.ts
src/background/stores/card-selection-store.ts
src/background/stores/visualization-scan-result-store.ts
src/electron/common/left-nav-item-factory.ts
src/electron/flux/action-creator/left-nav-action-creator.ts
src/tests/unit/tests/background/actions/card-selection-action-creator.test.ts
src/tests/unit/tests/electron/flux/action-creator/left-nav-action-creator.test.ts

Visualization scan result and card selection stores do not do any async work, therefore reverting actions to be sync. 
Feature work.
See https://github.com/microsoft/accessibility-insights-web/pull/5877

feat(mv3-part6): Revert visualization scan result and card selection actions to sync

---

src/background/actions/action-creator.ts
src/background/actions/card-selection-action-creator.ts
src/background/actions/card-selection-actions.ts
src/background/actions/visualization-scan-result-actions.ts
src/background/stores/card-selection-store.ts
src/background/stores/visualization-scan-result-store.ts
src/electron/common/left-nav-item-factory.ts
src/electron/flux/action-creator/left-nav-action-creator.ts
src/tests/unit/tests/background/actions/card-selection-action-creator.test.ts
src/tests/unit/tests/electron/flux/action-creator/left-nav-action-creator.test.ts

Reverts #5896
Feature work - reverting these actions back to async because they call PersistentStore's emitChanged(), which we realized will need to be async regardless of whether any async listeners are registered to the store.
See above

feat(mv3-part-6): Make visualization scan result and card selection actions async again

---

src/background/actions/permissions-state-actions.ts
src/background/actions/scoping-actions.ts
src/background/global-action-creators/permissions-state-action-creator.ts
src/background/global-action-creators/scoping-action-creator.ts
src/background/stores/global/permissions-state-store.ts
src/background/stores/global/scoping-store.ts
src/tests/unit/tests/background/global-action-creators/permissions-state-action-creator.test.ts
src/tests/unit/tests/background/global-action-creators/scoping-action-creator.test.ts

Reverts #5878 and #5881
Feature work - reverting these actions back to async because they call PersistentStore's emitChanged(), which we realized will need to be async regardless of whether any async listeners are registered to the store.
See above

feat(mv3-part-6): Make scoping and permission state actions async

---

src/background/actions/action-creator.ts
src/background/actions/content-action-creator.ts
src/background/actions/content-actions.ts
src/background/actions/details-view-action-creator.ts
src/background/actions/details-view-actions.ts
src/background/actions/side-panel-actions.ts
src/background/stores/details-view-store.ts
src/tests/unit/tests/background/actions/content-action-creator.test.ts
src/tests/unit/tests/background/actions/details-view-action-creator.test.ts

Reverts #5882
Feature work - reverting these actions back to async because they call PersistentStore's emitChanged(), which we realized will need to be async regardless of whether any async listeners are registered to the store.
See above

feat(mv3-part-6): Make details view store actions async

---

src/ad-hoc-visualizations/accessible-names/visualization.tsx
src/scanner/custom-rules/display-accessible-names.ts
src/tests/end-to-end/test-resources/accessible-names/accessible-names.html
src/tests/unit/tests/scanner/custom-rules/display-accessible-names.test.ts

This PR modifies the list of elements or selectors whose accessible names can be shown on the target page.
Feature request #4864 
This PR is in relation the new ad hoc tool feature that displays accessible names of different UI components. Rather than querying only elements with explicit roles that indicate whether or not those elements should have accessible names, this PR also handles the querying of native elements that require/ can have accessible names. It also handles the case of empty accessible names of elements, by not displaying such empty strings. A later PR will handle redirection to the right page when "How to test accessible names" link is clicked.
Image showing accessible names displayed on target page:
Image showing a situation where a div element has a role:

feat(adhoc-tools-accessible-names): display accessible names of native elements

---

src/ad-hoc-visualizations/accessible-names/visualization.tsx
src/content/adhoc/accessible-names/guidance.tsx
src/content/adhoc/accessible-names/index.ts
src/content/adhoc/index.ts
src/content/link.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

This PR adds the correct link, to which a user is directed to when the "How to test Accessible names" link is clicked.
Feature request #4864 
When the "How to test accessible names" link is clicked, the user is redirected to a new page that has some content on why accessible names are important.

feat(adhoc-tools-accessible-names): Add guidance link

---

src/background/background-init.ts
src/background/injector-controller.ts
src/background/service-worker-init.ts
src/background/tab-context-factory.ts
src/tests/unit/tests/background/injector-controller.test.ts
src/tests/unit/tests/background/tab-context-factory.test.ts

Makes inject async.
Feature work.
This method is async but not explicitly so. Changing it now such that we can make it clear moving forward which stores need to be async and which do not. Did some smoke testing in both mv3 and mv2 version of the extension; no errors were found.

feat(mv3-part6): make injector controller explicitly async

---

src/common/self-fast-pass.ts
src/injected/analyzers/analyzer-provider.ts
src/injected/analyzers/base-analyzer.ts
src/injected/analyzers/tab-stops-analyzer.ts
src/injected/main-window-initializer.ts
src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts

Add a timeout for two method calls that send frame commands for tab stops listener, and continue execution if a timeout is thrown.
Patch for #5931
This is a compromise between the two possible patches mentioned in #5931. We wait 500ms per call in the hopes that the frame message completes in that time, but if it doesn't, we continue execution instead of waiting for the full 30 second frame messaging timeout. Ideally, however, we would be able to tell before messaging the frame whether we expect to get a response.

fix: let tab stops run if frame messaging fails

---

src/tests/end-to-end/tests/details-view/automated-tabstops.test.ts

Fixes some transient issues in e2e tests.
Improves e2e tests

fix: improve e2e tests by waiting for failed instances count in tab stops test

---

src/injected/analyzer-controller.ts
src/injected/main-window-initializer.ts
src/injected/shadow-initializer.ts
src/tests/end-to-end/tests/details-view/color-contrast.test.ts
src/tests/unit/tests/injected/analyzer-controller.test.ts

Addressing color-contrast e2e test flakiness as well as color contrast bug. Repro steps for bug before this change:
1. Open poor-color-contrast.html test resource
2. Run fastpass, see 1 color contrast requirement failed
3. Close details view (do not refresh target page)
4. Re-open details view and re-run fastpass
5. See no failures where there should be 1 color contrast requirement
Bug fix
@pownkel noticed that this bug was [introduced when updating to axe-core 4.4.1](https://github.com/microsoft/accessibility-insights-web/commit/79ff4e19e6a50daa49b60bf3879cbc17fead9267), so we suspect that it has something to do with the color-contrast/ bgOverlap changes they made in that release. It appears that when we run fastpass on the page multiple times we get different axe results because axe …

fix(mv3-part6): Clear old visualizations before rerunning axe scan

---

build.yaml
pipeline/build-all-job-per-environment.yaml
pipeline/build-package.template.yaml
pipeline/e2e-job-per-environment.yaml
pipeline/unified/build-unsigned-release-packages.yaml
pipeline/unified/channel/sign-release-package-linux.yaml
pipeline/unified/unified-e2e-job-per-environment.yaml

Recent CI builds have been producing the following warning for each of the 5 linux-hosted steps:
```
##[warning]The ubuntu-18.04 environment is deprecated, consider switching to
ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see
https://github.com/actions/virtual-environments/issues/6002
```
This PR simply updates the ubuntu version in the `yaml` files. Validation build is [here](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=39524&view=results)
Build environment is deprecating support for ubuntu 18.04. …

chore: Bump Ubuntu version from 18.04 to 20.04

---

src/background/background-init.ts
src/background/service-worker-init.ts
src/background/telemetry/telemetry-event-handler.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/background/telemetry/telemetry-event-handler.test.ts

Right now the way we register the exception telemetry listener in the mv3 extension causes the following warnings:
> exception-telemetry-listener.ts:30 Event handler of 'error' event must be added on the initial evaluation of worker script.
initialize @ exception-telemetry-listener.ts:30
exception-telemetry-listener.ts:48 Event handler of 'unhandledrejection' event must be added on the initial evaluation of worker script.
This is a new warning in mv3 (does not repro with mv2) and is caused because the exception telemetry listener is [initialized in an async function](https://github.com/microsoft/accessibility-insights-web/blob/main/src/background/service-worker-init.ts#L124) and the [initialization adds global event listeners](https://github.com/microsoft/accessibility-insights-web/blob/ma …

fix(mv3-part6): Register exception telemetry listener event handlers synchronously

---

src/ad-hoc-visualizations/accessible-names/visualization.tsx
src/common/feature-flags.ts
src/popup/components/ad-hoc-tools-panel.scss
src/popup/components/ad-hoc-tools-panel.tsx
src/scanner/custom-rules/display-accessible-names.ts
src/tests/unit/tests/background/feature-flags.test.ts
src/tests/unit/tests/popup/components/__snapshots__/ad-hoc-tools-panel.test.tsx.snap
src/tests/unit/tests/popup/components/ad-hoc-tools-panel.test.tsx

This PR removes the feature flag under which development of the accessible names feature took place. Although the main goal of this PR is to remove the feature flag, it also contains very small changes related to the "display-accessible-names" rule; with respect to that, this PR adds another native element attribute (summary, to be specific,) check for elements that get their names from author-provided attributes. The PR also includes the addition of the "section" element to the selectors we query.
The "summary" attribute check was added to this PR because some elements like table can get their accessible name from the summary attribute. For more information, please refer to PR #5960

feat(adhoc-tools-accessible-names): remove feature flag

---

src/tests/unit/common/sample-test-data.ts

This PR allows the user to add a custom shortcut for the accessible names toggle.

feat(adhoc-tools-accessible-names): Allow customizable chrome shortcut for Accessible names

---

src/common/message-creators/remote-action-message-dispatcher.ts
src/common/message-creators/types/dispatcher.ts
src/electron/adapters/direct-action-message-dispatcher.ts
src/electron/ipc/ipc-message-dispatcher.ts
src/popup/actions/popup-action-message-creator.ts
src/tests/unit/tests/common/message-creators/remote-action-message-dispatcher.test.ts
src/tests/unit/tests/popup/actions/popup-action-message-creator.test.ts

Creates a new API on remote action message dispatcher to expose the async nature of dispatch message.
Fixes an issue/race-condition where the popup may close before a message is dispatched, leading to that action never being acted on (i.e. opening FastPass from the launch pad).
A general summary since there are multiple possible approaches for this fix:
- Make dispatchMessage async, which it really is, but is obfuscated (i.e. doesn't cause lint errors) due to the catch statement. This is a high-cost solution as many dependent APIs would then need to become async as well. Technically, this is "correct" but requires lots of changes.
- Make window.close async (via wrapper). This will also work because it will be added to queue after the dispatch async call. But it's unintuitive and …

feat(mv3-part7): fix issue where popup closes before dispatching message

---

.stylelintrc.js
packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-baseline-aware-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
src/DetailsView/components/left-nav/common-left-nav-link.scss
src/DetailsView/components/left-nav/details-view-left-nav.scss
src/DetailsView/components/left-nav/left-nav-icon.scss
src/DetailsView/components/switcher.scss
src/common/components/cards/card-kebab-menu-button.scss
src/common/components/cards/rich-resolution-content.scss
src/common/components/selector-input-list.scss
src/common/styles/common.scss
src/common/styles/root-level-only/global-styles.scss
src/electron/views/common/window-title/window-title.scss
src/electron/views/left-nav/fluent-left-nav.scss
src/electron/views/results/results-view.scss
src/injected/styles/injected.scss
src/popup/Styles/popup.scss
src/reports/automated-checks-report.scss
src/reports/components/report-sections/details-section.scss
src/views/content/content.scss

- Enable and fix [no-descending-specificity/](https://stylelint.io/user-guide/rules/list/no-descending-specificity/) stylelint rule which disallows selectors of lower specificity from coming after overriding selectors of higher specificity.
- Create `is-mac-os` mixin to reduce repeated code when writing styles for iOS and improve readability.
Part of https://github.com/microsoft/accessibility-insights-web/issues/5187 as an incremental task to enable stylelint rules.

chore: Enable and fix `no-descending-specificity` stylelint rule

---

Gruntfile.js
src/tests/end-to-end/common/browser-factory.ts
src/tests/end-to-end/common/browser.ts
src/tests/end-to-end/common/manifest-instance.ts
src/tests/end-to-end/common/mv2-manifest-instance.ts
src/tests/end-to-end/common/mv3-manifest-instance.ts
tools/strict-null-checks/import-finder.js
tsconfig.strictNullChecks.json

Fix 2 mv3 bugs uncovered by running e2e tests on the mv3 extension (added in https://github.com/microsoft/accessibility-insights-web/pull/5965). The 2 bugs are described below and addressed in the 2 commits separately.
Feature work.
Failing cross origins iframe tests:
- This bug can be repro'ed by running mv3 extension manually. Repro steps: (1) Open all-cross-origin-iframe.html test resource (2) Run fastpass (3) See details view seems to be scanning forever, errors in service worker:
```
error injecting /bundle/injected.css: Error: Cannot access contents of url "file:///C:/code/accessibility-insights-web/src/tests/end-to-end/test-resources/all-cross-origin-iframe.html". Extension manifest must request permission to access this host. Error: Cannot access contents of url …
```

feat(mv3-part7): Fix mv3 e2e test failures

---

.github/workflows/ci.yml
Dockerfile
build.yaml
pipeline/e2e-mv3-job-per-environment.yaml
pipeline/e2e-mv3-test-from-agent.yaml
pipeline/e2e-reliability.yaml
pipeline/run-tests-in-docker-linux.yaml

Now that we have e2e tests running on the mv3 extension and passing locally, adding those tests to CI runs.
Feature work
As we have only run mv3 e2e tests locally so far, we are not sure how reliable they will be initially. We won't merge here until they are reasonably reliable but even still it will probably be fair to merge around any mv3 e2e CI failures for now.

feat(mv3-part7): Add e2e mv3 test runs to CI

---

src/background/tab-context-factory.ts
src/background/tab-context-manager.ts
src/background/target-page-controller.ts
src/common/state-dispatcher.ts
src/tests/unit/tests/background/tab-context-factory.test.ts
src/tests/unit/tests/background/tab-context-manager.test.ts
src/tests/unit/tests/common/state-dispatcher.test.ts

Remove await when background sends store update messages.
This fixes a bug in canary which caused the details view UI to be unresponsive for ~30 seconds after the tab stops visualizer was turned on. The user could toggle the visualizer off (with no effect), but could not change details view tabs.
We don't need to wait for a response from this message because it is sent from, instead of to, the background service worker. If the service worker goes idle after sending the store update, the message will still be processed by the context it is sent to.

fix(mv3-part-7): make getDispatchUpdateEvent synchronous

---

src/injected/visualization/center-position-calculator.ts
src/injected/visualization/tabbed-item.ts
src/tests/unit/tests/injected/visualization/center-position-calculator.test.ts

Ignore null elements in tab stops visualizer
Currently, the tab stops visualizer ignores elements that are offscreen at the time of drawing, but does not account for elements dynamically appearing/disappearing depending on what is currently in focus.
For example, the bing.com frontpage contains a button with a tooltip that contains a link:
The link is tabbable, but only exists when the tooltip is visible, so `SVGDrawer` gets a value of `null` for that element after the user tabs out of the tooltip. However, it still tries to get the center position for the null element, which throws an exception. About half the time, this causes all tab stops visualized up to that point to disappear.
This PR fixes the bug by ignoring null elements in the visualizer, the same as we do for offscreen …

fix: ignore null elements in tab stops visualizer

---

src/DetailsView/components/assessment-view-update-handler.ts
src/tests/unit/tests/DetailsView/components/assessment-view-update-handler.test.ts

Fix mv3 bug in which partially automated requirements pages (ex. Landmarks > landmark roles) blink between results and spinner before showing results again. 
Fix mv3 bug
The root cause of this bug was that we were sending too many enable visualization messages. We send these messages in `assessment-view-update-handler` based on if the assessment store data thinks that a step has been scanned or not (`props.assessmentData.testStepStatus[step].isStepScanned`). We were seeing this bug because:
- The `assessment-view-update-handler` is called every time any store data updates
- Multiple stores have listeners for the scanCompleted action
- If any store besides the assessment store completes its updates first, it causes the `assessment-view-update-handler` to run its check against assessment …

fix(mv3-part-7): Fix assessment view updater bug

---

src/background/service-worker-init.ts

With the mv2 extensions we include the insights.js.config script in the head of [background.html ](https://github.com/microsoft/accessibility-insights-web/blob/main/src/background/background.html#L8)so that our global configuration values are set right away. Since there isn't anything analogous in mv3, we were not calling insights.js.config at all prior to this change, meaning (among other things) telemetry was showing the build as unknown instead of devmv3 or canarymv3.
Feature work
N/a

fix(mv3-part-7): Import config script in service worker init

---

src/injected/tab-stops-requirement-evaluator.ts
src/injected/window-initializer.ts
src/scanner/axe-utils.ts
src/tests/unit/tests/injected/tab-stops-requirement-evaluator.test.ts

Creates a new axe-util API that allows us to getSelectors based on an array, meaning setup and teardown of axe is only done once.
Significantly improves perf when many instances are generated by automated tab stops.
Before:
After:
I believed this perf issue existed because, upon stopping, we loop through each tabbable item we didn't see, in this case hundreds of tabbable elements, and send a separate action message to create an instance for each one. Obviously, that wouldn't be performant and we could batch this. This was kind of correct and does improve performance but for scenarios which could take 20-30s, it would only improve that by 1-2s.
In actuality, the main performance culprit is `getUniqueSelector`. Basically, we need to setup axe each time we use that API but the cost of doing …

fix: improve automated tab stops instance generation by batching getUniqueSelector

---

deploy/Gruntfile.js

Update config script to use globalThis instead of window to account for service worker changes. We switched to using globalThis in one of our grunt files [in an early mv3 change](https://github.com/microsoft/accessibility-insights-web/commit/e867127a82090a674059f461241dac8e19f81784) but missed the second grunt file. 
Fix mv3 telemetry
N/a

fix(mv3-part-7): Use globalThis when updating insights config

---

Gruntfile.js
src/manifest.json

Prior to this change there were multiple slots for "Activate the extension" when configuring keyboard shortcut and only one actually worked. This was because we were using a mv2 specific API for that action, switching to the mv3 version fixes things. 
Before:
After:
Fix mv3 issue.
Chrome docs briefly mention this change here: https://developer.chrome.com/docs/extensions/reference/commands/#action-commands.

fix(mv3-part-8): Fix activate extension keyboard shortcut in mv3

---

src/reports/components/fast-pass-report-summary.tsx

Removing an outdated todo note from a previous feature. 
Clean up 🧹
The work the note was referencing has been completed in #5034 and can now be removed.

chore: remove outdated todo note

---

src/common/self-fast-pass.ts
src/injected/analyzers/analyzer-provider.ts
src/injected/analyzers/base-analyzer.ts
src/injected/analyzers/tab-stops-analyzer.ts
src/injected/main-window-initializer.ts
src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts

Revert #5933
After #6028, this patch is no longer needed.
n/a

refactor: revert #5933 tab stops patch

---

src/background/telemetry/app-insights-telemetry-client.ts
src/tests/unit/tests/background/telemetry/app-insights-telemetry-client.test.ts

Bug in sending telemetry for mv3 extensions: 
```
serviceWorker.bundle.js:683 Error while processing browser RuntimeOnMessage event:  TypeError: Cannot set properties of undefined (setting 'name')
```
Fix mv3 bug
It's not clear why `this.applicationInsights.context.telemetryTrace` is undefined in mv3 extensions but not mv2 extensions, but checked with @madalynrose (who added this line) and it appears to be non-vital, so we should be safe to only set the name when telemetryTrace is defined.

fix(mv3-part-8): Check for defined telemetry trace

---

src/injected/all-frame-runner.ts
src/injected/drawing-controller.ts
src/injected/drawing-initiator.ts
src/injected/frameCommunicators/all-frames-messenger.ts
src/injected/target-page-visualization-updater.ts
src/injected/window-initializer.ts
src/tests/end-to-end/tests/target-page/post-message.test.ts
src/tests/unit/tests/injected/__snapshots__/drawing-controller.test.ts.snap
src/tests/unit/tests/injected/all-frame-runner.test.ts
src/tests/unit/tests/injected/drawing-controller.test.ts
src/tests/unit/tests/injected/drawing-initiator.test.ts
src/tests/unit/tests/injected/frameCommunicators/all-frame-messenger.test.ts
src/tests/unit/tests/injected/target-page-visualization-updater.test.ts

- Refactor `DrawingController` to use `AllFramesMessenger`
- Refactor `AllFramesMessenger` to validate ping responses to make sure the script is injected and responding
- distinguish `updateVisualization` from `enableVisualization` in `DrawingInitiator`: `enableVisualization` calls `initialize()` on `AllFramesMessenger` before updating so we don't ping all frames again on every update (such as with the tab stops visualizer that updates frequently)
This fixes an error where DrawingController attempts to message nonresponsive frames to enable or disable the visualizer

refactor: use AllFramesMessenger for visualizers

---

src/background/background-init.ts
src/background/service-worker-init.ts

Move creation of BackgroundMessageListener to the end of background-init.ts and service-worker-init.ts
We've been seeing intermittent store errors that cause the extension to freeze until the target page is refreshed. I believe this is because we're creating and registering the background message listener before everything else is fully initialized, so it's possible for the background to receive a message for a store that has not yet been initialized.
This PR moves that listener registration later in the script code, after all stores have been created and initialized. The BrowserEventManager defers events until a listener is registered, so any messages received before BackgroundMessageListener is registered will still be processed after everything is initialized.
- [n/a] Addresses an …

fix: register message listener after all stores are initialized

---

src/injected/analyzers/tab-stops-analyzer.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts

Discovered a bug in mv3 testing with the following repro steps:
- Open assessment-> focus-> visible focus
- Turn on visual helper and tab through the page a few times
- Either allow service worker to go idle or shut it down manually
- Select start over-> start over Focus
- See unhandled error in target page: 
```
tab-stops-analyzer.ts:76 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'stop')
at TabStopsAnalyzer.teardown (tab-stops-analyzer.ts:76:55)
```
Fix mv3 bug
N/a

fix(mv3-part-8): Only stop tab stops requirement results processor in teardown when defined

---

src/background/stores/assessment-store.ts
src/common/flux/persistent-store.ts
src/tests/unit/tests/background/stores/persistent-store.test.ts

Addressing assessment perf issues caused by MV3 changes to `emitChanged`. During MV3 testing we noticed that perf seems to degrade as you go through an assessment because the assessment data structure is growing and it therefore takes more time to persist data in the indexedDB. This PR mitigates this issue by minimizing the calls to indexedDB. 
Address MV3 perf issue
EmitChanged is often called for stores when no store data was actually changed, which causes us to make unnecessary calls to IndexedBD to persist data that is already saved in the database. This PR adds logic to keep track of the data we last saved to the database and only update the database when that data has changed. 
Testing results:
Scenario: Clean install of extension (nothing saved in stores) -> open new assessment …

fix(mv3-part-8): Only persist store data when changed

---

src/background/background-init.ts
src/background/extension-details-view-controller.ts
src/background/global-context-factory.ts
src/background/service-worker-init.ts
src/background/stores/global/global-store-hub.ts
src/background/stores/tab-context-store-hub.ts
src/background/tab-context-factory.ts
src/background/target-page-controller.ts
src/tests/unit/tests/background/extension-details-view-controller.test.ts
src/tests/unit/tests/background/global-context-factory.test.ts
src/tests/unit/tests/background/stores/global/global-store-hub.test.ts
src/tests/unit/tests/background/stores/tab-context-store-hub.test.ts
src/tests/unit/tests/background/tab-context-factory.test.ts
src/tests/unit/tests/background/target-page-controller.test.ts

Remove mv3 feature work flags that are no longer necessary.
Clean up from feature work.
When we first began persisting store data in the indexedDB API we included a `persistData` flag in background-init in case these changes caused bugs. As we have now had these changes checked in for several months and plan on releasing the mv3 version of the extension soon, it should be safe to remove that flag now. This allows us to remove unnecessary code in several places and quite a bit of test coverage. Unfortunately, we cannot entirely remove the `persistData` flag from persistent stores, since electron reuses some of these stores and does not need to persist data.
In removing unnecessary `persistData` flags, I also noticed that `toolData` is never used in the init files, so I removed that as …

feat(mv3-part-8): Remove unnecessary persist data flag

---

src/DetailsView/actions/tab-stop-requirement-action-message-creator.ts
src/background/actions/action-payloads.ts
src/background/actions/tab-stop-requirement-action-creator.ts
src/background/actions/tab-stop-requirement-actions.ts
src/background/stores/visualization-scan-result-store.ts
src/common/messages.ts
src/injected/analyzers/tab-stops-orchestrator.ts
src/injected/analyzers/tab-stops-requirement-result-processor.ts
src/injected/window-initializer.ts
src/tests/unit/common/visualization-scan-result-store-data-builder.ts
src/tests/unit/tests/DetailsView/actions/tab-stop-requirement-action-message-creator.test.ts
src/tests/unit/tests/background/actions/tab-stop-requirement-action-creator.test.ts
src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-orchestrator.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-requirement-result-processor.test.ts

Optimizations for tab stops results reporting
- Send automated tab stops results to background in batches instead of one at a time (minimizes disk writes for store updates)
- Send results between frames in batches instead of one at a time (minimizes frame messages and calls to getUniqueSelector, which is a time-consuming synchronous operation)
Processing automated tab stops results can take a long time, especially on pages with a lot of iframes and tabbable elements. This can be seen by opening a page with a lot of iframes and tabbed elements (such as cnn.com), enabling the tab stops ad hoc visualizer and tabbing through a few elements, and then disabling it and immediately trying to enable another visualizer. On my surface laptop, on cnn.com, there is a delay of 6-8 seconds between …

fix: send automated tab stops results in batches

---

jest.config.base.js

Cleans up the `moduleNameMapper` option in the Jest config by removing (now unused) fabric references.
Reduce tech debt.

chore: Remove unused moduleNameMapper fabric properties

---

.github/dependabot.yml
.github/workflows/ci.yml

This pull request updates actions as recommended and configures Dependabot to keep github-actions updated for us.
There are several github-actions that are emitting the following warning:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, actions/upload-artifact
For the updated actions, each saw an update to Node 16 in v3 and no other notable breaking changes. The list below contains the changelogs or releases for the updated actions:
- https://github.com/actions/checkout/blob/main/CHANGELOG.md#v300 
- https://github.com/actions/setup-node/releases/tag/v3.0.0
- …

chore: Update core actions and configure Dependabot to update github-actions

---

src/reports/assessment-json-export-json-builder.ts
src/tests/unit/tests/reports/__snapshots__/assessment-json-export-json-builder.test.ts.snap

Our Assessment JSON export mechanism surfaces the rule id and description for each requirement. The description originates as JSX and then gets converted into a string. This works fine for the majority of our requirements, where the JSX `props` contain `children` that mostly include innerText. This is not the case for several requirements that include `Markup.Tag` tags.
For example, the Semantics Assessment's "Header Attribute" Requirement includes two `Markup.Tag` tags for `td` and `th` that do not have `children`. 
```jsx
const headersAttributeDescription: JSX.Element = (
<span>
The <Markup.CodeTerm>headers</Markup.CodeTerm> attribute of a <Markup.Tag tagName="td" />{' '}
element must reference the correct <Markup.Tag tagName="th" /> element(s).
</span>
);
```
When our JSON exporter …

fix: update json export to properly parse tagName elements

---

src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/end-to-end/tests/details-view/reflow-ui.test.ts

Add e2e tests for different reflow states of the card footer kebab button
Automatically detect a11y issues in new reflow components
The new reflow components/states were added in #5966

chore: e2e tests for reflowable card buttons

---

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-baseline-aware-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html
packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html
src/common/components/cards/card-footer-instance-action-buttons.scss
src/common/components/cards/card-footer-instance-action-buttons.tsx
src/common/styles/root-level-only/global-styles.scss
src/tests/unit/tests/common/components/cards/__snapshots__/card-footer-instance-action-buttons.test.tsx.snap

This PR updates our stylesheets to change the color of contextual menu list items on hover for the gear icon contextual menu. Additionally, this PR moves this CSS rule to the global stylesheet to make sure this hover color is applied to all contextual menus and removes the local stylesheet changes for the kebab menu.
New Hover States:
| HC Mode | Screenshot |
|------------|--------------|
| Dusk | ![screenshot of dusk HC theme showing gear menu with a different color for "Settings" text in hover state](https://user-images.githubusercontent.com/3230904/196998091-5a116cc9-228e-4089-828b-c1dea0cff758.jpeg)|
| Aquatic | ![screenshot of aquatic HC theme showing gear menu with a different color for "Settings" text in hover state](https://user-images.githubusercontent.com/3230904/196998343-7c282e …

fix: ensure hover color of contextual menu list items change in Windows High Contrast 

---

src/common/feature-flags.ts
src/tests/unit/tests/background/feature-flags.test.ts

Adds a hidden feature flag for the MediumPass feature.
Feature work 🚀 
This feature creates the feature flag to be used in later features. It will be used in the launch pad and in the DetailsView Pivot to either display or hide the Medium Pass option.

feat(medium-pass-1): add hidden feature flag for MediumPass

---

src/assessments/parsing/test-steps/parsing.tsx

chore: rephrase parsing instructions in assessments
as suggested under https://github.com/microsoft/accessibility-insights-web/issues/6130#issuecomment-1276871238
> Suggestion: maybe "Go to the browser tab containing your target page and, in that browser window, select the first bookmarklet"?
closes #6130 
Instructions shown to user during **Parsing Assessments**
currently;
https://github.com/microsoft/accessibility-insights-web/blob/7ef8ee7aa066968ef0085ab2a72d5505a397a83c/src/assessments/parsing/test-steps/parsing.tsx#L52-L56
- [-] Ran `yarn null:autoadd`
- [-] Ran `yarn fastpass`
- [-] Added/updated relevant unit test(s) (and ran `yarn test`)
- [-] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [-] (UI changes only) Added …

chore: rephrase parsing instructions in assessments

---

deploy/package.json
deploy/yarn.lock
package.json
yarn.lock

Since minimatch is an indirect dependency with multiple versions, I specified the parent dependency to insure that it was only a patch version change for the package.
Security alert.
AFAIK, yarn does not support specifying resolutions of specific versions, which would be nice to have here.

chore(deps): add resolution for minimatch to use patched version

---

src/assessments/custom-widgets/custom-widgets-column-renderer.tsx
src/tests/unit/tests/assessments/custom-widgets/custom-widgets-column-renderer.test.tsx

https://github.com/microsoft/accessibility-insights-web/issues/6116#issuecomment-1293832001
> This is the [landing page link](https://www.w3.org/WAI/ARIA/apg/patterns), we would need to point to the right subpage for each pattern. For example for combobox the current link is: https://www.w3.org/TR/wai-aria-practices-1.1/#combobox the new link should be: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/
closes #6116 
- [-] Ran `yarn null:autoadd`
- [-] Ran `yarn fastpass`
- [-] (UI changes only) Added screenshots/GIFs to description above
- [-] (UI changes only) Verified usability with NVDA/JAWS

chore: update Links to Design Pattern > Assessment

---

src/background/stores/assessment-store.ts
src/background/stores/global/global-store-hub.ts
src/tests/unit/common/assessment-store-data-builder.ts
src/tests/unit/tests/background/stores/assessment-store.test.ts

Name is specified in constructor, such that AssessmentStore can be reused for MediumPass.
feature work
Medium Pass store will be another instance of the assessment store, to share its structure (in a future PR). The name is utilized for message passing/updating appropriate state and as such must be unique amongst instances.

refactor(medium-pass-1): refactor name out of assessment store

---

src/DetailsView/components/left-nav/details-view-left-nav.tsx
src/DetailsView/details-view-initializer.ts
src/background/IndexedDBDataKeys.ts
src/background/actions/global-action-hub.ts
src/background/actions/quick-assess-action-creator.ts
src/background/get-persisted-data.ts
src/background/global-context-factory.ts
src/background/stores/global/global-store-hub.ts
src/common/stores/store-names.ts
src/tests/unit/tests/background/actions/quick-assess-action-creator.test.ts
src/tests/unit/tests/background/get-persisted-data.test.ts
src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts
src/tests/unit/tests/background/stores/global/global-store-hub.test.ts

This PR creates new instances of `AssessmentActionCreator` and `AssessmentStore` to store and update Quick Assess data. 
Feature work 🚀 
The background page/service worker set up stores and actions during initialization. Though the Quick Assess data displayed to the user will have a much smaller list of requirements, data in the backend will include all `Assessment`s and `Requirement`s to ensure that any data requested is available, same as we do for Assessment.
As of now, no data is populated. A later PR will call the actions to update and save the data.

feat(medium-pass-1): Create new instances of data infrastructure used in the extension background for Quick Assess 

---

src/common/telemetry/exception-telemetry-sanitizer.ts

Our `unhandledError` telemetry includes logic that attempts to prevent sending events which would include any data from the page being analyzed, since it could in theory be user-identifiable. 
We noticed while analyzing some of the telemetry that we missed a property (`inspectElement`) that includes an element selector in certain devtools-related telemetry. This PR adds that property to the sanitization list.
Avoid the possibility of including PII accidentally in unhandledError telemetry
n/a
- …

fix: sanitize inspectElement property in unhandledError telemetry

---

src/background/actions/assessment-action-creator.ts
src/background/global-action-creators/global-action-creator.ts
src/tests/unit/tests/background/actions/assessment-action-creator.test.ts
src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts

As a follow-up to #6177, this PR moves the `onDetailsViewInitialized` callback from `AssessmentActionCreator` to `GlobalActionCreator` so it can call `updateDetailsViewId` on both the assessmentActions and quickAssessmentActions. This ensures that the persisted tab info is updated in both the Assessment and Quick Assess stores when the `DetailsViewActionMessageCreator` is initialized in `details-view-initializer.ts`.
From Wahaj's comment in #6177: 
"For context: the initialize message is for making sure we show the dialog for target change (in assessments) when you open assessment from a new details view tab. This started from us mainly looking to make sure that a user would see the continue/start new dialog when they start a new browsing session (but now extends to …

feat(medium-pass-1): move onDetailsViewInitialized to GlobalActionCreator

---

pipeline/install-node-prerequisites.yaml

This PR updates each task in our `install-node-prerequisites.yml` pipeline fragment to retry up to twice each, using the recently-introduced [`retryCountOnTaskFailure`](https://learn.microsoft.com/en-us/azure/devops/release-notes/2021/pipelines/sprint-195-update) pipelines syntax. Failures in these tasks are overwhelmingly the result of network connectivity flakiness, so this should help with a few occasional failures that we see across all builds (eg, the failure in this morning's unified "unsigned stage 1" pipeline)
Avoid noise from flaky failures outside of our control that we'd "resolve" by retrying anyway
n/a
- [n/a] …

chore: allow retries of install-node-prerequisites pipeline tasks

---

eslintrc.base.js
src/common/components/cards/rich-resolution-content.tsx
src/icons/brand/blue/brand-blue.tsx
src/reports/components/assessment-report-footer.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/rich-resolution-content.test.tsx.snap
src/tests/unit/tests/reports/components/__snapshots__/assessment-report-footer.test.tsx.snap

This pull request enables and fixes two eslint rules:  react/no-unknown-property and react/jsx-no-target-blank
- Adds `rel="noreferrer"` to a link with `target=blank`
- Rewrites `mask-type` as a CSS property: https://developer.mozilla.org/en-US/docs/Web/CSS/mask-type
- Removes `list-style-type="disc"`, it's a CSS property but is not needed here as `multiLineTextYesBullet` sets the list style type https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type
Increase eslint coverage.

chore: Enable and fix eslint react/no-unknown-property, react/jsx-no-target-blank

---

.github/workflows/ci.yml

The codeql action has been timing out in our CI consistently since this weekend. It appears that it's the same issue described in the description of https://github.com/github/codeql-action/pull/1373, so since the work around implemented in that PR has not yet been released, I'm working around it here by just temporarily disabling trap caching. 
Work around codeql timeouts

fix: Work around codeql github action timeout

---

package.json
pipeline/scripts/electron-build-id.js
src/tests/electron/tests/framework-no-codecs.test.ts
yarn.lock

Bump electron version from 19.0.7 to 19.1.3.
Unified unsigned release pipeline test run: https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=39898&view=results
Security alert

chore(deps): Bump electron version to 19.1.3

---

src/DetailsView/actions/assessment-action-message-creator.ts
src/DetailsView/details-view-initializer.ts
src/background/actions/quick-assess-action-creator.ts
src/common/messages.ts
src/tests/unit/tests/DetailsView/actions/assessment-action-message-creator.test.ts
src/tests/unit/tests/background/actions/quick-assess-action-creator.test.ts

Refactor message types out of assessment action message creator to be passed in at construction; allows us to pass in quick assess message types instead.
Feature work.

feat(medium-pass-1): refactor messages out of assessment action message creator

---

src/DetailsView/details-view-initializer.ts
src/assessments/assessment-builder.tsx
src/assessments/assessments-requirements-filter.ts
src/assessments/medium-pass-requirements.ts
src/background/service-worker-init.ts
src/background/stores/visualization-store.ts
src/common/configs/assessment-visualization-configuration.ts
src/common/configs/web-visualization-configuration-factory.ts
src/common/types/store-data/visualization-store-data.ts
src/common/types/visualization-type.ts
src/injected/is-visualization-enabled.ts
src/injected/window-initializer.ts
src/popup/popup-initializer.ts
src/tests/unit/common/visualization-store-data-builder.ts
src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/assessments/assessment-builder.test.tsx
src/tests/unit/tests/assessments/assessments-requirements-filter.test.ts
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/is-an-assessment-selected.test.ts
src/tests/unit/tests/background/keyboard-shortcut-handler.test.ts
src/tests/unit/tests/background/stores/visualization-store.test.ts
src/tests/unit/tests/background/tab-context-factory.test.ts
src/tests/unit/tests/common/configs/web-visualization-configuration-factory.test.ts
src/tests/unit/tests/popup/components/diagnostic-view-toggle.test.tsx
src/tests/unit/tests/popup/handlers/diagnostic-view-toggle-click-handler.test.ts
tsconfig.strictNullChecks.json

Adding new visualization types necessitates changes in many places. Generally speaking the changes fall into the following camps:
- VisualizationConfigurationFactory should not throw errors when a new visualization type is used for `getConfiguration`. This requires the medium pass provider be implemented and as such many changes in this PR are signature updates for the creation of the factory.
- `getStoreData` needs to be updated as this is another place where Assessment and QuickAssess will differ. As such, they've been removed from assessment-builder and moved to the config factory.
- Consequently this also means we must update the visualization store to contain mediumPass data.
- The requirement filter is modified to amend the VisualizationType on the configs and now uses a …

feat(medium-pass-1): add visualization types for quick assess/medium pass

---

src/assessments/assessment-builder.tsx
src/assessments/automated-checks/build-test-steps-from-rules.tsx
src/assessments/types/requirement.ts
src/common/configs/assessment-visualization-configuration.ts
src/common/configs/visualization-configuration.ts
src/common/configs/web-visualization-configuration-factory.ts
src/injected/analyzer-controller.ts
src/tests/unit/common/visualization-store-data-builder.ts
src/tests/unit/tests/assessments/assessment-builder.test.tsx
src/tests/unit/tests/assessments/automated-checks/build-test-steps-from-rules.test.tsx
src/tests/unit/tests/common/configs/web-visualization-configuration-factory.test.ts
src/tests/unit/tests/injected/analyzer-controller.test.ts

Our configuration objects statically link analyzers and their communication/lifecycle methods to visualization type, message types, and requirement keys. Since these are used by our communication methods, this effectively amounts to the configuration objects, a place for business logic, containing architectural logic which we should avoid.
As such, this PR changes it such that the analyzer controller is responsible for this duty. This PR does not contain:
1. Modifying the configuration objects to remove mention of visualization type, message types, and requirement keys. This will be done in the next PR.
2. Modifying the analyzers to NOT use the message configuration passed in during `analyze`; it makes sense to re-factor this out with this change but in a future PR.
To summarize, this PR …

feat(medium-pass-1): Create base analyzer configuration in analyzer-controller and pipe into getAnalyzer

---

src/common/components/cards/card-footer-instance-action-buttons.tsx
src/common/components/cards/card-footer-menu-items-builder.ts
src/common/components/cards/collapsible-component-cards.tsx
src/common/components/cards/instance-details-footer.tsx
src/common/components/cards/instance-details-group.tsx
src/common/components/cards/instance-details.tsx
src/common/components/cards/result-section-content.tsx
src/common/components/cards/rule-content.tsx
src/common/components/cards/rules-with-instances.tsx
src/packages/accessibility-insights-ui/ui-factory.tsx
src/reports/components/report-sections/combined-report-failed-section.tsx
src/tests/unit/common/tab-store-data-builder.ts
src/tests/unit/tests/packages/accessibility-insights-ui/__snapshots__/ui-factory.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/combined-report-failed-section.test.tsx
tsconfig.strictNullChecks.json

Adds the UI package's impl directory + its dependants to the strict null check set.
#2869
n/a

chore(null): strict null checks for UI package and deps

---

src/background/actions/action-creator.ts
src/tests/unit/tests/background/actions/action-creator.test.ts

This PR ensures that the MediumPass/QuickAssess equivalents of Assessment callbacks are registered in ActionCreator

feat(medium-pass-1): register MediumPass callbacks in ActionCreator

---

src/background/initial-visualization-store-data-generator.ts
src/background/stores/tab-context-store-hub.ts
src/background/stores/visualization-store.ts
src/tests/unit/common/visualization-store-data-builder.ts
src/tests/unit/tests/background/__snapshots__/initial-visualization-store-data-generator.test.ts.snap
src/tests/unit/tests/background/initial-visualization-store-data-generator.test.ts
src/tests/unit/tests/background/stores/visualization-store.test.ts

When there is persisted data in IndexedDB for the `VisualizationStore` and `storeData.tests` is missing the `mediumPass` key, the `WebConfigurationVisualizationFactory` hits an error. This PR overrides `generateDefaultState` for `VisualizationStore` (called during `initialize()`), allowing us to ensure that default state is generated for test modes not present in `persistedData`. This implementation is based on `AssessmentStore`, which is the only other store that overrides this method. It pulls initial data generation logic into a separate class to facilitate testing. 
This PR addresses an issue seen in Canary where adhoc visualizations are nonfunctional and the service worker logs the following error: 
```Error while processing browser RuntimeOnMessage event:  TypeError: Cannot read …
```

fix: ensure default store data is merged with persisted data during VisualizationStore initialization

---

src/common/flux/scope-mutex.ts
src/common/get-stack-trace.ts
src/tests/unit/common/recording-logger.ts
src/tests/unit/tests/common/flux/scope-mutex.test.ts
src/tests/unit/tests/common/get-stack-trace.test.ts
tsconfig.strictNullChecks.json

While investigating a ScopeMutex error earlier today, I found myself wanting to know the stack of the original scope holder. This PR introduces a new helper for grabbing a current stack trace (extracting some code from `recording-logger`) and implements support for stack-tracking to `ScopeMutex`, augmenting its error messages to include the stack of the original scope-holder.
Improve actionability of this type of error. This isn't super important for reproducible forms of the error since you could just use print breakpoints on `tryLockScope` to achieve the same thing, but it makes inconsistent/racey errors of this form (and `unhandledError` telemetry of this form) much more likely to be actionable
n/a …

chore: include stack of original scope-holder in ScopeMutex errors

---

src/DetailsView/assessment-functionality-switcher.ts
src/DetailsView/components/details-view-switcher-nav.ts
src/DetailsView/details-view-initializer.ts
src/tests/unit/tests/DetailsView/assessment-functionality-switcher.test.ts
src/tests/unit/tests/injected/analyzer-controller.test.ts

This allows an easy way for us to switch different assessment/medium-pass affiliated objects while keeping components agnostic to either scenario while also not having to pass everything down props.
Feature work.
Alternatives explored were:
1. Modify the deps object somewhere before we use any of the assessment/medium-pass specific functionality (like in `details-view-content`). Decided against this since it violates our expected pattern of keeping the deps object the same and not treating it as a normal React prop.
2. Start passing in these objects through props from a component before we use any functionality (details-view-content again). Avoided this because this feels like a lot of unnecessary bloat to add to each component along the UI tree but it did not violate any of our …

feat(medium-pass-1): created AssessmentFunctionalitySwitcher

---

src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/details-view-content.tsx
src/DetailsView/components/report-export-dialog-factory.tsx
src/DetailsView/components/start-over-component-factory.tsx
src/DetailsView/components/start-over-dialog.tsx
src/DetailsView/details-view-body.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-dialog-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/report-export-dialog-factory.test.tsx
src/tests/unit/tests/DetailsView/components/start-over-component-factory.test.tsx
src/tests/unit/tests/DetailsView/components/start-over-dialog.test.tsx

Just a minor clean up to not use assessments provider through props but deps, which is how we usually do it.
Feature work.
This should make the next couple of PRs a bit more simple as we look to normalize how we get assessments provider through a get method.

refactor(medium-pass-1): remove usages of assessmentsProvider through props in details-view-content

---

src/DetailsView/components/details-view-content-with-local-state.tsx
src/DetailsView/components/details-view-content.tsx
src/DetailsView/components/details-view-right-panel.ts
src/DetailsView/details-view-body.tsx
src/DetailsView/details-view-container.tsx
src/DetailsView/details-view-initializer.ts
src/DetailsView/details-view-renderer.tsx
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/DetailsView/details-view-content.test.tsx
src/tests/unit/tests/DetailsView/details-view-renderer.test.tsx

Follow-up to #6236. This moves the usage of assessmentInstanceTableHandler to a getter function.
Feature work.
A couple important notes:
1. There were two types/interfaces named `DetailsViewContentDeps`; I renamed the one to RightPanelDeps which felt appropriate given the usage.
2. A lot of the `assessmentInstanceTableHandler` usage is through props that should actually be deps. Those changes are not in this PR. They are similar in nature to the #6238.

feat(medium-pass-1): get assessmentInstanceTableHandler with getter + typings fix for details-view-content

---

src/DetailsView/components/details-view-content.tsx
src/DetailsView/components/details-view-right-panel.ts
src/DetailsView/components/details-view-switcher-nav.ts
src/DetailsView/components/left-nav/get-selected-assessment-store-data.ts
src/DetailsView/components/left-nav/get-selected-details-view.ts
src/DetailsView/components/left-nav/medium-pass-left-nav.tsx
src/DetailsView/details-view-container.tsx
src/DetailsView/details-view-initializer.ts
src/DetailsView/document-title-updater.ts
src/background/stores/assessment-store.ts
src/background/stores/global/global-store-hub.ts
src/tests/unit/common/assessment-store-data-builder.ts
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/DetailsView/components/details-view-right-panel.test.tsx
src/tests/unit/tests/DetailsView/components/left-nav/get-selected-assessment-store-data.test.ts
src/tests/unit/tests/DetailsView/components/left-nav/get-selected-details-view.test.ts
src/tests/unit/tests/DetailsView/components/left-nav/medium-pass-left-nav.test.tsx
src/tests/unit/tests/DetailsView/details-view-content.test.tsx
src/tests/unit/tests/DetailsView/document-title-updater.test.ts
src/tests/unit/tests/DetailsView/store-mocks.ts
src/tests/unit/tests/background/stores/assessment-store.test.ts
tsconfig.strictNullChecks.json

Lots of small changes to make this happen:
1. `getSelectedAssessmentStoreData` on the switcher nav to allow us to switch between quick assess and assessment store data in the state.
2. `GetDetailsRightPanelConfiguration` had its behavior flipped, where it specifies TestView when it's a fast pass test and otherwise gets the selected one.
3. `MediumPassLeftNavProps` were missing from the left nav props object and as such the getProvider changes didn't get caught there.
4. `getSelectedDetailsView` for quick assess was missing.
5. `AssessmentStore` was hard-coding the index db key. That is now passed in at initialization to allow quick assess to use it.
The rest is just general wiring up/creation/etc.
feature work.
This does not wire up the target page for quick assess but also should not …

feat(medium-pass-1): wiring up details view for quick assess

---

src/injected/analyzers/batched-rule-analyzer.ts
src/tests/unit/tests/injected/analyzers/batched-rule-analyzer.test.ts

This fixes an issue where messages are sent for visualization types that were not scanned in batched analyzer.
Feature work.
Batched Analyzer is a bit messy and probably be refactored but ... not in this PR.

fix(medium-pass-1): filter batched analyzer onResolve on test type

---

src/DetailsView/document-title-updater.ts
src/tests/unit/tests/DetailsView/document-title-updater.test.ts
src/tests/unit/tests/DetailsView/store-mocks.ts

This causes an error when a page is loaded; doesn't break but this should reduce error noisiness.
Feature clean-up.
Also added a test for the assessment store and visualization store.

fix(medium-pass-1): document title updater should wait for quick assess data

---

src/assessments/keyboard-interaction/test-steps/keyboard-navigation.tsx

The keyboard-navigation getAnalyzer call was missed in #6230.
Feature work.
This fixes an issue where the visualization for keyboard-navigation does not show up for quick assess; assessment remained unaffected.

fix(medium-pass-1): fix keyboard navigation getAnalyzer by using the config that was passed in

---

src/injected/client-init.ts

`client-init` contains the following bit of code very early during injected page initialization:
```ts
const { Stylesheet } = await import('@fluentui/merge-styles');
const stylesheet = Stylesheet.getInstance();
stylesheet.setConfig({
defaultPrefix: 'insights',
});
```
This code exists because many `@fluentui/react` components' styling works internally by dynamically generating some CSS and injecting it into a document-level fluentui-managed `<style>` element using [`@fluentui/merge-styles`](https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/README.md). Because this is injecting into a document-level style element within the DOM, it is "visible" to the target page itself, not just our injected content, and that means that if the target page already uses fluentui …

fix: prevent styling conflicts with certain fluentui-based target pages

---

src/background/actions/data-transfer-actions.ts
src/background/actions/global-action-hub.ts
src/background/global-action-creators/global-action-creator.ts
src/background/stores/global/data-transfer-store.ts
src/background/stores/global/global-store-hub.ts
src/common/extension-telemetry-events.ts
src/common/messages.ts
src/common/stores/store-names.ts
src/common/types/store-data/data-transfer-store-data.ts
src/tests/unit/tests/background/actions/global-action-hub.test.ts
src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts
src/tests/unit/tests/background/stores/global/data-transfer-store.test.ts
src/tests/unit/tests/background/stores/global/global-store-hub.test.ts

Adds a store to contain state that will be used for modules transferring data from quick assess to assessment.
Feature work.
Currently, this shouldn't do anything but exist. In future PRs, we will add functionality wiring this to UI and the module that actually transfers the data.

feat(medium-pass-2): add store/wiring for transferring data from quick assess to assessment

---

yarn.lock

Resolve json5 v^2.2.1 to v2.2.2
Fixes a [dependabot alert](https://github.com/microsoft/accessibility-insights-web/security/dependabot/44)
The patched versions of json5 are 1.0.2 and 2.2.2. After this PR, we will be using both patched versions.

chore(deps-dev): use json5 v2.2.2 instead of v2.2.1

---

src/DetailsView/components/tab-stops/data-transfer-view-actions.ts
src/DetailsView/data-transfer-view-store.ts
src/common/stores/store-names.ts
src/tests/unit/tests/DetailsView/data-transfer-view-store.test.ts

A view store for housing the state of the confirmation dialog for transferring data from quick assess to assessment. It's a view store because this leads to simpler components + this dialog can/should exist per tab and is removed on refresh.
feature work.
Is not used in this PR; future PR will implement the dialog.

feat(medium-pass-2): add data transfer view store to house confirm dialog state

---

src/assessments/medium-pass-requirements.ts
src/common/types/visualization-type.ts
src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/background/__snapshots__/initial-visualization-store-data-generator.test.ts.snap

Currently, the requirements list for quick assess lists `Adaptable Content > Contrast` when it should list `Contrast > UI components`. Also, `Native Widgets > Instructions` is missing from the list. This PR corrects this.
Feature work
N/A

fix(medium-pass-2): fix requirements list to contain correct contrast requirement

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/DetailsView/components/quick-assess-to-assessment-dialog.tsx
src/DetailsView/data-transfer-view-controller.ts
src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/quick-assess-to-assessment-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/quick-assess-to-assessment-dialog.test.tsx
src/tests/unit/tests/DetailsView/data-transfer-view-controller.test.ts

Adds a new dialog to confirm transfer from quick assess to assessment.
Feature work.
Not wired up in this PR but this is what it looks like when shown locally:

feat(medium-pass-2): add quick assess to assessment dialog

---

src/DetailsView/components/details-view-content.tsx
src/DetailsView/details-view-body.tsx
src/DetailsView/details-view-container.tsx
src/DetailsView/details-view-initializer.ts
src/tests/end-to-end/tests/details-view/__snapshots__/headings.test.ts.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/DetailsView/details-view-body.test.tsx
src/tests/unit/tests/DetailsView/details-view-content.test.tsx
src/tests/unit/tests/DetailsView/store-mocks.ts

Wires up the dialog that was created in #6329.
Feature work.
There is currently no way to show this through the UI, that will be in a future PR.

feat(medium-pass-2): wired up quick assess to assessment dialog

---

src/DetailsView/components/command-bar-buttons-menu.tsx
src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/details-view-switcher-nav.ts
src/DetailsView/components/transfer-to-assessment-button.tsx
src/common/components/null-component.tsx
src/common/fabric-icons.ts
src/tests/end-to-end/tests/details-view/reflow-ui.test.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/command-bar-buttons-menu.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/transfer-to-assessment-button.test.tsx.snap
src/tests/unit/tests/DetailsView/components/command-bar-buttons-menu.test.tsx
src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
src/tests/unit/tests/DetailsView/components/transfer-to-assessment-button.test.tsx
src/tests/unit/tests/common/components/__snapshots__/null-component.test.tsx.snap
src/tests/unit/tests/common/components/null-component.test.tsx

Adds the transfer to assessment button for the command bar, in quick assess.
Feature work.
Screenshot:
High-contrast screenshot:

feat(medium-pass-2): add transfer to assessment button

---

src/DetailsView/components/manual-test-step-view.tsx
src/tests/unit/tests/DetailsView/components/manual-test-step-view.test.tsx

This PR adds text to the manual test requirement view to clarify that a failure instance is needed to count the requirement as failed.
feature work 🚀 

feat(medium-pass-2): add text to clarify failure instance action

---

src/DetailsView/components/iframe-skipped-warning.tsx
src/DetailsView/components/warning-configuration.tsx
src/common/types/store-data/scan-incomplete-warnings.ts
src/injected/analyzers/base-analyzer.ts
src/injected/analyzers/notification-text-creator.ts
src/injected/analyzers/unified-result-sender.ts
src/injected/scan-incomplete-warning-detector.ts
src/scanner/get-rule-inclusions.ts
src/scanner/iruleresults.d.ts
src/scanner/result-decorator.ts
src/scanner/scan-parameter-generator.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/iframe-skipped-warning.test.tsx.snap
src/tests/unit/tests/DetailsView/components/iframe-skipped-warning.test.tsx
src/tests/unit/tests/DetailsView/components/scan-incomplete-warning.test.tsx
src/tests/unit/tests/injected/analyzers/base-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/batched-rule-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/notification-text-creator.test.ts
src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/unified-result-sender.test.ts
src/tests/unit/tests/injected/scan-incomplete-warning-detector.test.ts
src/tests/unit/tests/scanner/__snapshots__/get-rule-inclusions.test.ts.snap
src/tests/unit/tests/scanner/result-decorator.test.ts
src/tests/unit/tests/scanner/scan-parameter-generator.test.ts

This PR adds logic to detect when iframes have been skipped in an axe scan via that frames-tested rule. When iframes have been skipped, it shows a yellow banner to notify the user. 
Addresses issue [#6128](https://github.com/microsoft/accessibility-insights-web/issues/6128)
Screenshot of banner with fastpass (shows up similarly in assessment UI):
[Screenshot description: Yellow banner across top of details view with text "there are iframes in the target page that are non-responsive. These frames have been skipped and are not included in the result.]

fix: add banner for unresponsive iframes

---

src/DetailsView/components/switcher.tsx
src/popup/launch-pad-row-configuration-factory.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/switcher.test.tsx.snap
src/tests/unit/tests/popup/launch-pad-row-configuration-factory.test.ts

This PR updates the icon shown for Quick Assess in the launch pad and details view pivot. It also adds the Quick Assess blurb text to the launch pad.
Launch Pad:
Pivot:
feature work 🚀 

feat(medium-pass-2): Quick Assess icon and blurb

---

Gruntfile.js

This PR addresses an issue where ESBuild produced CSS sourcemaps (previously, our webpack setup did not), but our Grunt rules were never updated to copy the new CSS sourcemap files from their intermediate build location in `/extension/devBundle/*.css.map` to their final location in `/drop/extension/dev/bundle/*.css.map`.
This PR updates the webpack copy rule to copy the CSS sourcemaps where they exist, similar to how we handle JS sourcemaps already.
* Improves debugability of CSS modules
* Fixes warning spew in the console of dev builds of the form `DevTools failed to load source map: Could not load content for chrome-extension://iifodackleggfpjdngdlihpflphibdak/bundle/injected.css.map: System error: net::ERR_FILE_NOT_FOUND`
n/a
- [n/a] …

chore: fix CSS sourcemaps not being copied correctly in dev builds

---

src/injected/analyzer-state-update-handler.ts
src/tests/unit/tests/injected/analyzer-state-update-handler.test.ts

This PR fixes an issue introduced by #6183 where most events that trigger an axe-core scan will accidentally trigger the scan to start twice instead of once. This causes a few problems:
* It creates a race condition - in pages with iframes, the first scan can begin concurrently with our scripts being injected into child frames, so it can result in spurious `frame-tested` failures
* It creates console error spew of the form `failed to scan with error - Axe is already running. Use `await axe.run()` to wait for the previous run to finish before starting a new run.`
The root cause lies in the `analyzer-state-update-handler` component that was updated as part of that PR. That PR changed how we track whether injecting our scripts into the target page's frames is complete from a series of …

fix: avoid trying to start scan twice due to injectionState confusion

---

src/common/components/controls/insights-command-button.scss

The "Save Assessment" button is a different color than the rest of the command bar buttons when using Windows high contrast themes. This PR fixes the styling to be consistent.
State | Before | After|
-------|--------|-------------|
Default | ![Screenshot showing command bar buttons in white and save assessment in light blue](https://user-images.githubusercontent.com/3230904/213556539-7c3af2d5-e7aa-4a7d-821b-4d60b0122484.jpeg) | ![screenshot showing all command bar buttons in white](https://user-images.githubusercontent.com/3230904/213556727-307a34b4-4829-4cba-8df7-8aba90f95aba.jpeg)
Hover | ![Screenshot showing command bar buttons in white and save assessment in light blue](https://user-images.githubusercontent.com/3230904/213556539-7c3af2d5-e7aa-4a7d-821b-4d60b0122484.jpeg) | …

fix: save assessment button high contrast styling

---

src/DetailsView/components/requirement-context-section.scss

This PR fixes the color for the info and examples button (styled to look like a link) when using the high contrast theme and windows high contrast.
Mode | Before | After |
-------|--------|--------|
High Contrast Theme | ![helpful resources showing blue info and examples and yellow other links](https://user-images.githubusercontent.com/3230904/213511376-7a99c186-a705-489f-92cc-fca416aecd6f.jpeg) | ![helpful resources showing yellow info and examples that matches other links](https://user-images.githubusercontent.com/3230904/213511434-012b003d-b469-4f06-bbd2-569fa6a6375e.jpeg)
Windows High Contrast | ![helpful resources showing yellow info and examples and purple other links](https://user-images.githubusercontent.com/3230904/213511563-963489cc-0327-4236-8189-7a13691aca82.jpeg) | ![helpful …

fix(medium-pass-2): fix high contrast colors for section resources

---

src/background/completed-test-step-telemetry-creator.ts
src/background/global-context-factory.ts
src/background/service-worker-init.ts
src/background/stores/global/global-store-hub.ts
src/common/extension-telemetry-events.ts
src/tests/unit/tests/background/completed-test-step-telemetry-creator.test.ts
src/tests/unit/tests/background/global-context-factory.test.ts
src/tests/unit/tests/background/stores/global/global-store-hub.test.ts

Re-uses the CompletedTestStepTelemetryCreator for assessment for this. The only difference is it uses the quick assess objects (provider, store).
Feature work.
This adds a new event for quick assess specifically not because it is absolutely required (selectedTest would mention QuickAssess) but because we do not necessarily want to rely on that for quick assess, as it is mostly requirements.

feat(medium-pass-2): fire telemetry when a quick assess requirement is completed

---

src/common/constants/displayable-strings.ts
src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/injection-failed-warning.test.tsx.snap
src/tests/unit/tests/DetailsView/components/details-view-overlay/preview-features-panel/__snapshots__/preview-features-container.test.tsx.snap

A recent change added a banner which refers to the Microsoft Edge browser as "Edge". Per branding guidelines, the first reference should be "Microsoft Edge". Checked with PM and confirmed that we should make this change.
While working on this, noticed a typo in the same file (evalution). Corrected this to evaluation. This string appears in the subtitle of the Preview features panel.
Restores us to compliance with branding guidelines and dictionary spelling.

fix: comply with Microsoft Edge branding guidelines, correct spelling

---

src/DetailsView/components/command-bar-buttons-menu.tsx
src/common/components/expand-collapse-left-nav-hamburger-button.tsx
src/common/components/hamburger-menu-button.tsx
src/popup/components/launch-panel-header.tsx
src/tests/end-to-end/tests/popup/__snapshots__/hamburger-menu.test.ts.snap
src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
src/tests/end-to-end/tests/popup/hamburger-menu.test.ts
src/tests/end-to-end/tests/popup/launchpad.test.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/command-bar-buttons-menu.test.tsx.snap
src/tests/unit/tests/common/components/__snapshots__/expand-collapse-left-nav-hamburger-button.test.tsx.snap
src/tests/unit/tests/common/components/expand-collapse-left-nav-hamburger-button.test.tsx
src/tests/unit/tests/common/components/hamburger-menu-button.test.tsx
src/tests/unit/tests/popup/components/__snapshots__/launch-panel-header.test.tsx.snap
src/types/tab-stop-requirement-info.ts

This PR fixes:
* button label text in `QuickAssessLeftNavHamburgerButton` ("QuickAssess"--> "Quick Assess")
* a bug in `CommandBarButtonsMenu` where a menu item is still created for export even though the element is null, causing an `aria-command-name` a11y issue uncovered by e2e tests
* no item for Quick Assess in the launch panel hamburger button menu
feature work 🚀 

feat(medium-pass-2): Quick Assess menu fixes

---

src/DetailsView/components/quick-assess-to-assessment-dialog.tsx
src/DetailsView/components/requirement-view-next-requirement-configuration.tsx
src/DetailsView/components/switcher.tsx
src/DetailsView/components/transfer-to-assessment-button.tsx
src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/end-to-end/tests/details-view/quick-assess.test.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/quick-assess-to-assessment-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-view-next-requirement-configuration.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/switcher.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/transfer-to-assessment-button.test.tsx.snap

Adds e2e tests for the "move to assessment" button/dialog.
Feature work.

feat(quick-assess): add e2e tests for move to assessment

---

src/DetailsView/components/details-view-content.tsx
src/DetailsView/components/details-view-switcher-nav.ts
src/DetailsView/components/overview-content/overview-content-container.tsx
src/common/constants/link-data-sources.ts
src/tests/unit/tests/DetailsView/components/overview-content/__snapshots__/overview-content-container.test.tsx.snap
src/tests/unit/tests/DetailsView/components/overview-content/overview-content-container.test.tsx

Prior to this PR both the assessment and quick assess overview pages shared the same set of links for the right hand side help panel. This PR introduces logic so those links can be changed independently of each other and also updates the quick assess `Getting started` link to a new fwlink. For now, the new fwlink redirects to the same place, but we plan on updating it to point to a new quick assess specific getting started video in the future. 
Ensure quick assess UI points to quick assess specific help links.

feat(quick-assess): Separate assessment and quick assess help links

---

src/background/stores/assessment-store.ts
src/tests/unit/tests/background/stores/assessment-store.test.ts

This is a workaround fix to ensure that Automated Checks is not expanded when another test/requirement is selected in quick assess; assessment does not change.
Feature work.
This issue occurs because, in assessment, for a user to be able to select another requirement, requires expanding another test (which means the previous test that was expanded is no longer so). In Quick Assess, since only Automated Checks expands, selecting a requirement DOES NOT require the user to expand/collapse any other tests. As a result, the expanded test property is either nothing OR automated checks.
This change will make sure the expanded test property is updated on requirement selection. This data is not used by quick assess for non-automated checks views (because there's nothing to expand or collapse/the …

fix(quick-assess): automated checks should collapse when other test selected

---

Gruntfile.js

We believed we were pinning our deployment dependency versions but because the yarn.lock file was not being copied over to the appropriate folders, yarn would find no lock file and proceed without pinning.
Fixes current release errors.
We could've also fixed these release errors by updating the node version used in our releases but will look to do that separately.

fix: copy yarn.lock file to fix deploy dep version pinning

---

src/DetailsView/components/details-view-right-panel.ts
src/DetailsView/components/details-view-switcher-nav.ts
src/DetailsView/components/start-over-component-factory.tsx
src/DetailsView/components/start-over-dialog.tsx
src/DetailsView/components/start-over-dropdown.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-component-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-dropdown.test.tsx.snap
src/tests/unit/tests/DetailsView/components/details-view-right-panel.test.tsx
src/tests/unit/tests/DetailsView/components/start-over-component-factory.test.tsx
src/tests/unit/tests/DetailsView/components/start-over-dropdown.test.tsx

The start over dropdown is specific to assessment; this changes that to be specific to be Quick Assess and generalizes the start over text.
Feature work.
What it looks like now:

feat(quick-assess): start over should be specific to quick assess

---

src/DetailsView/components/details-view-right-panel.ts
src/DetailsView/components/start-over-component-factory.tsx
src/DetailsView/components/start-over-dropdown.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-component-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/details-view-right-panel.test.tsx
src/tests/unit/tests/DetailsView/components/start-over-component-factory.test.tsx
src/tests/unit/tests/DetailsView/components/start-over-dropdown.test.tsx

Removes the possibility of the "Start over Quick Assess" (and Assessment) option from being disabled because we do not need the component to be able to do that. This simplifies tests and the component.
Clean-up refactor.
This is a follow-up to changes in #6399

refactor: remove ability to remove start over assessment/quick assess option in component

---

src/background/assessment-data-converter.ts
src/background/stores/assessment-store.ts
src/scanner/get-rule-inclusions.ts
src/tests/unit/tests/background/assessment-data-converter.test.ts
src/tests/unit/tests/background/stores/assessment-store.test.ts
src/tests/unit/tests/scanner/__snapshots__/get-rule-inclusions.test.ts.snap
src/tests/unit/tests/scanner/get-rule-inclusions.test.ts

Fixes https://github.com/microsoft/accessibility-insights-web/issues/6403. This bug was introduced by https://github.com/microsoft/accessibility-insights-web/commit/2186a7eae1783417a3106a5b37afbe4dbb4c9e1c when we added a `always-included` rule. This PR adds logic to ignore always-included rules when generating the assessment instances map. 
Addresses issue https://github.com/microsoft/accessibility-insights-web/issues/6403

fix: filter always-included rules out of assessment instances map

---

src/DetailsView/components/common-message-bar-styles.scss
src/DetailsView/components/injection-failed-warning.tsx
src/DetailsView/components/scan-incomplete-warning.tsx
src/DetailsView/components/target-page-hidden-bar.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/injection-failed-warning.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/scan-incomplete-warning.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-hidden-bar.test.tsx.snap

Fixes #6406.
Bug fix.
min-height on the message bar component is behaving weirdly: setting the minimum to 32px should not yield the behavior we are seeing but it does. Hence, I wrote that for the overwrite. While "unset" also works here, I used fit-content because it also works and is more appropriate for the desired behavior. But ... 32px being the **min**-height should have also been appropriate for the desired behavior. 🤷 
Before:
After:

fix: warning message bar text overflow/overlap

---

src/injected/scanner-utils.ts
src/tests/unit/tests/injected/scanner-utils.test.ts

Fixing ad hoc color visualizer bug introduced in https://github.com/microsoft/accessibility-insights-web/commit/2186a7eae1783417a3106a5b37afbe4dbb4c9e1c. The results from the always-included rules were causing styling to be applied to iframe elements instead of html elements.
Addresses issue https://github.com/microsoft/accessibility-insights-web/issues/6422
Before this change:
[Screenshot description: ad hoc color visualizer enabled and only part of target page in greyscale]
After this change:
[Screenshot description: ad hoc color visualizer enabled and full target page in greyscale]

fix: filter always-included rule results from ad hoc results

---

src/scanner/axe-options.ts
src/scanner/scan-parameter-generator.ts
src/tests/unit/tests/scanner/launcher.test.ts
src/tests/unit/tests/scanner/scan-parameter-generator.test.ts

`axe-core` removed its `restoreScroll` option in mid-2020, when they updated the only rule that scrolled the page to no longer ever do that in [PR 2388](https://github.com/dequelabs/axe-core/issues/2388).
This PR removes the obsolete option from our axe-config.
* Code cleanup, axe-core doesn't care whether the option is passed or not.
* Preparation for [using the axe-config output in service](https://github.com/microsoft/accessibility-insights-service/pull/2402)
n/a

chore: remove references to obsolete restoreScroll axe-core option

---

src/DetailsView/components/start-over-component-factory.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-component-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/start-over-component-factory.test.tsx

Fixes the issue where navigating to getting started in Automated Checks in Quick Assess would break the application.
Fixes bug.
When the selected test sub view is 'getting-started', the step returned by 'getStep' is null. We must be mindful of this if we are to add the ability to start over specific requirements in quick assess.

fix: quick assess automated checks getting started rendering

---

yarn.lock

Pin to a higher version of http-cache-semantics transitive dependency to ensure we get security fixes (see https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_workitems/edit/310)
Keep dependencies up to date

chore: Bump http-cache-semantics transitive dependency

---

src/DetailsView/components/details-view-content.tsx
src/common/get-card-selection-view-data.ts
src/common/is-result-highlight-unavailable.ts
src/electron/views/results/results-view.tsx
src/injected/element-based-view-model-creator.ts
src/tests/unit/tests/DetailsView/details-view-content.test.tsx
src/tests/unit/tests/common/get-card-selection-view-data.test.ts
src/tests/unit/tests/electron/views/results/results-view.test.tsx
src/tests/unit/tests/injected/element-based-view-model-creator.test.ts

Specifies the exact properties necessary from unified results instead. Allows us to use this for results from assessment.
Feature work
Fixing the null check from #6459 and opening a new PR

refactor(automated-checks): refactor getCardSelectionViewData to not be tied to unified store data

---

src/common/store-data-to-scan-node-result-converter.ts
src/injected/element-based-view-model-creator.ts
src/injected/main-window-initializer.ts
src/tests/unit/tests/common/components/cards/sample-view-model-data.ts
src/tests/unit/tests/common/store-data-to-scan-node-result-converter.test.ts
src/tests/unit/tests/injected/element-based-view-model-creator.test.ts

Add logic to convert assessment store data and card selection store data to element based view model. This logic will be used for visualizing automated checks failures with the new assessment automated checks page/ infrastructure. 
Feature work
Implementation notes:
- Right now assessment store data is never passed into `getElementBasedViewModel`, so the new logic is not being exercised in practice. Eventually we will hook it up similarly to the [issues/ needs review logic in SelectorMapHelper](https://github.com/microsoft/accessibility-insights-web/blob/main/src/injected/selector-map-helper.ts#L96-L107), but this is blocked until https://github.com/microsoft/accessibility-insights-web/pull/6457 is merged as we will need to pass in `AssessmentStoreData` and the new …

feat(automated-checks): add assessment data to element based view model converter

---

src/DetailsView/components/details-view-content.tsx
src/common/rule-based-view-model-provider.ts
src/electron/views/results/results-view.tsx
src/reports/package/axe-results-report.ts
src/tests/unit/common/__snapshots__/rule-based-view-model-provider.test.ts.snap
src/tests/unit/common/rule-based-view-model-provider.test.ts
src/tests/unit/tests/DetailsView/details-view-content.test.tsx
src/tests/unit/tests/electron/views/results/results-view.test.tsx
src/tests/unit/tests/reports/package/axe-results-report.test.ts

Add logic to convert assessment store data to cards view model. This logic will be used for visualizing automated checks failures with the new assessment automated checks page/ infrastructure.
Feature work.
Implementation notes: 
- This implementation built off of @waabid's branch: https://github.com/microsoft/accessibility-insights-web/compare/main...waabid:accessibility-insights-web:assessmentStoreDataTransformer2
- Right now assessment store data is never passed into getCardViewData, so the new logic is not being exercised in practice. Eventually we will hook it up similarly to the [issues/ needs review logic in details-view-content](https://github.com/microsoft/accessibility-insights-web/blob/main/src/DetailsView/components/details-view-content.tsx#L114-L137), but this is blocked …

feat(automated-checks): add assessment data to cards view model converter

---

src/DetailsView/components/default-test-view-container-provider.tsx
src/DetailsView/components/details-list-issues-view.tsx
src/DetailsView/components/issues-table.tsx
src/DetailsView/components/test-view-container-provider.tsx
src/assessments/assessment-builder.tsx
src/assessments/automated-checks/assessment.tsx
src/assessments/types/iassessment.ts
src/common/configs/web-visualization-configuration-factory.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/default-test-view-container-provider.test.tsx.snap
src/tests/unit/tests/DetailsView/components/default-test-view-container-provider.test.tsx
src/tests/unit/tests/assessments/assessment-builder.test.tsx
src/tests/unit/tests/common/configs/web-visualization-configuration-factory.test.ts

Add single page view for assessment automated checks. This implementation adds `createAssessmentAutomatedChecksTestViewContainer` to the test view container provider and reuses existing `AdhocIssuesTestView` and `FailedInstancesSection`. Note that these changes are currently behind the automatedChecks feature flag. 
Feature work
This UI component will eventually need to be hooked up to the AssessmentCardSelection infrastructure being added in https://github.com/microsoft/accessibility-insights-web/pull/6457. For now, it is populated with fastpass automated checks data. 
UI after these changes, with feature flag enabled:
[Screenshot description: Assessment details view with automated checks selected. Automated checks is not collapsible in the left nav bar and the main content UI is …

feat(automated-checks): add test view container for assessment automated checks

---

src/DetailsView/components/left-nav/get-left-nav-selected-key.ts
src/DetailsView/components/left-nav/nav-link-handler.ts
src/tests/unit/tests/DetailsView/components/left-nav/get-left-nav-selected-key.test.ts
src/tests/unit/tests/DetailsView/handlers/nav-link-handler.test.ts

https://github.com/microsoft/accessibility-insights-web/pull/6454 added noncollapsible links and https://github.com/microsoft/accessibility-insights-web/pull/6482 added a single page test view container for the new assessment automated checks. This PR finishes integrating them together by fixing the navigation and left nav link highlighting.
Feature work
Before this change:
[Screenshot description: assessment automated checks left nav link is selected but not highlighted]
After this change:
[Screenshot description: assessment automated checks left nav link is selected and highlighted]
Note that with these changes the status is still not reflected in the left nav bar icon. This is because the assessment store data is not populated (the data being displayed is from the unified results). …

feat(automated-checks): fix selected nav link logic for noncollapsible links

---

src/background/stores/card-selection-store.ts
src/background/stores/needs-review-card-selection-store.ts
src/common/store-data-to-scan-node-result-converter.ts
src/tests/unit/tests/background/stores/card-selection-store.test.ts
src/tests/unit/tests/background/stores/needs-review-card-selection-store.test.ts
src/tests/unit/tests/common/store-data-to-scan-node-result-converter.test.ts

Adding `AssessmentStoreData` to `CardSelectionStoreData` converter. This will be necessary for the `AssessmentCardSelectionStore`'s `OnScanCompleted` callback that @lisli1 will be adding. 
Feature work

feat(automated-checks): add assessment data to card selection store data converter

---

src/background/IndexedDBDataKeys.ts
src/background/actions/global-action-hub.ts
src/background/actions/quick-assess-card-selection-action-creator.ts
src/background/get-persisted-data.ts
src/background/global-context-factory.ts
src/background/stores/assessment-card-selection-store.ts
src/background/stores/global/global-store-hub.ts
src/common/messages.ts
src/common/stores/store-names.ts
src/tests/unit/tests/DetailsView/store-mocks.ts
src/tests/unit/tests/background/actions/quick-assess-card-selection-action-creator.test.ts
src/tests/unit/tests/background/get-persisted-data.test.ts
src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts
src/tests/unit/tests/background/stores/assessment-card-selection-store.test.ts
src/tests/unit/tests/background/stores/global/global-store-hub.test.ts

Breaking off part of https://github.com/microsoft/accessibility-insights-web/pull/6501 to make that PR smaller. This PR does 3 things:
- Makes the assessment card selection store global instead of per tab
- Adds quick assess versions of the card selection store infrastructure
- Initializes the assessment and quick assess card selection stores and their associated infrastructure
Feature work

feat(automated-checks): initialize assessment and quick assess card selection stores

---

src/DetailsView/components/details-view-content.tsx
src/background/stores/card-selection-store.ts
src/background/stores/needs-review-card-selection-store.ts
src/common/rule-based-view-model-provider.ts
src/common/store-data-to-scan-node-result-converter.ts
src/electron/views/results/results-view.tsx
src/injected/element-based-view-model-creator.ts
src/injected/main-window-initializer.ts
src/injected/selector-map-helper.ts
src/reports/package/axe-results-report.ts
src/tests/unit/common/rule-based-view-model-provider.test.ts
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/DetailsView/details-view-content.test.tsx
src/tests/unit/tests/background/stores/card-selection-store.test.ts
src/tests/unit/tests/background/stores/needs-review-card-selection-store.test.ts
src/tests/unit/tests/common/store-data-to-scan-node-result-converter.test.ts
src/tests/unit/tests/electron/views/results/results-view.test.tsx
src/tests/unit/tests/injected/element-based-view-model-creator.test.ts
src/tests/unit/tests/injected/selector-map-helper.test.ts
src/tests/unit/tests/reports/package/axe-results-report.test.ts

In previous PRs for this feature we introduced code that mixes up the assessment's test key and its visualization type. This PR fixes this bug by normalizing all logic to use the assessment test key. 
Feature work
Discovered while debugging/ integrating https://github.com/microsoft/accessibility-insights-web/pull/6510

feat(automated-checks): Fix visualizationType vs test key bug

---

src/assessments/adaptable-content/assessment.tsx
src/assessments/assessment-builder.tsx
src/assessments/automated-checks/assessment.tsx
src/assessments/color/assessment.tsx
src/assessments/contrast/assessment.tsx
src/assessments/custom-widgets/assessment.tsx
src/assessments/headings/assessment.tsx
src/assessments/images/assessment.tsx
src/assessments/keyboard-interaction/assessment.tsx
src/assessments/landmarks/assessment.tsx
src/assessments/links/assessments.tsx
src/assessments/native-widgets/assessment.tsx
src/assessments/page/assessment.tsx
src/assessments/pointer-motion/assessment.tsx
src/assessments/semantics/assessment.tsx
src/assessments/sequence/assessment.tsx
src/assessments/types/iassessment.ts
src/assessments/visible-focus-order/assessment.tsx
src/tests/unit/common/visualization-store-data-builder.ts
src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/assessments/assessment-builder.test.tsx
src/tests/unit/tests/common/configs/web-visualization-configuration-factory.test.ts
src/tests/unit/tests/injected/selector-map-helper.test.ts

This removes the storeDataKey properties from the assessment objects. This is because we want the visualization configuration objects to be consistent with the assessment objects.
Feature work.
There's a lot of context to this, so here's a summary:
First off, reasoning.
The assessment object has two keys before this PR: the `storeDataKey` and the `key`. When an assessment provider looks up a key, it looks for the `key` property. This is used to store data in the `AssessmentStoreData`, which is persisted and utilized for backwards compatibility. The `storeDataKey` is not directly used from the assessment object but instead is transferred to the visualization configuration object as the `key` property and later utilized to store data within the `VisualizationStore` which is only persisted …

feat(automated-checks): remove storeDataKey and make keys consistent across assessment and visualization configuration objects

---

src/background/assessment-data-converter.ts
src/common/store-data-to-scan-node-result-converter.ts
src/common/types/store-data/assessment-result-data.ts
src/injected/adapters/resolution-creator.ts
src/injected/main-window-initializer.ts
src/injected/selector-map-helper.ts
src/tests/unit/tests/background/assessment-data-converter.test.ts
src/tests/unit/tests/common/store-data-to-scan-node-result-converter.test.ts
src/tests/unit/tests/injected/adapters/resolution-creator.test.ts

Prior to these changes, assessment data and was missing some of the metadata that unified data has about rules and rule failures. This meant that the the details view cards for the new assessment automated checks would be missing a lot of the information that the fastpass automated checks cards include (for example, how to fix text and rule descriptions). This PR adds the wiring to pass the relevant data through to the new assessment automated checks view. 
Feature work
This PR also includes two small bug fixes discovered while debugging the new assessment automated checks. These can be separated into separate PRs if needed, but they're so small I figured the might as well be lumped together:
- In `main-window-initializer.ts` the new assessment and quick assess card selection stores were …

feat(automated-checks): populate scan node results data with assessment data

---

src/DetailsView/assessment-functionality-switcher.ts
src/DetailsView/components/test-view-container.tsx
src/DetailsView/details-view-initializer.ts
src/common/message-creators/assessment-card-selection-message-creator-wrapper.ts
src/common/message-creators/assessment-card-selection-message-creator.ts
src/common/message-creators/card-selection-message-creator.ts
src/tests/unit/tests/DetailsView/assessment-functionality-switcher.test.ts
src/tests/unit/tests/DetailsView/components/test-view-container.test.tsx
src/tests/unit/tests/common/message-creators/assessment-card-selection-message-creator-wrapper.test.ts

With the addition of the AssessmentCardSelectionStore and its corresponding infrastructure (https://github.com/microsoft/accessibility-insights-web/pull/6457), we added the testKey parameter to card selection message payloads, but right now the test key is never populated. This PR adds the logic to populate the testKey. 
Feature work

feat(automated-checks): send selected test key with card selection message payloads

---

src/injected/selector-map-helper.ts
src/tests/unit/tests/injected/selector-map-helper.test.ts

We only scan/gather failures in automated checks in fastpass but in assessment/quick assess we gather passing instances as well (shown as 'no failing instances' in the report vs. 'no matching instances'). As such, the selector map helper filters those out for visualization purposes.
Feature work.
Selector map helper could/should definitely be refactored such that the methods live off visualization configurations but felt that may be too large a change for now.

feat(automated-checks): selector map helper only returns failures for automated checks in assessment/quick assess

---

src/DetailsView/components/adhoc-issues-test-view.tsx
src/DetailsView/components/assessment-issues-test-view.tsx
src/DetailsView/components/default-test-view-container-provider.tsx
src/DetailsView/components/test-view-container-provider.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-issues-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/default-test-view-container-provider.test.tsx.snap
src/tests/unit/tests/DetailsView/components/assessment-issues-test-view.test.tsx

Create a new component `AssessmentIssuesTestView` that does not create the target page changed view that is shown in FastPass when refreshing the target page while doing an Assessment. This behavior is consistent with existing Assessment behavior, where refreshing the target page does not affect the ongoing Assessment.
Fixes behavior in Assessment Automated checks

fix(automated-checks): remove target page changed view in assessment automated checks

---

.github/workflows/ci.yml
Gruntfile.js

This PR is a follow-up to #6530 , which partially resolved the build issues in our ADO CI build, but didn't resolve the issue where `yarn build:unified:all` fails in CI due to yarn complaining about lockfile modifications. The mechanism from #6530 is the right idea, but just unsetting the `CI` variable isn't enough - Yarn uses the `ci-info` package to detect CI environments and it also recognizes a few more specific variables that this PR unsets.
I considered instead just passing an empty environment, instead of `process.env` minus the CI vars. That would be more resilient to changes in which variables `ci-info` detects, but would run the risk of causing more subtle issues if there happens to be any other behavior that electron-builder uses Yarn/Node/etc environment variables to detect; I …

build: attempt 2 to fix CI-specific issue with yarn build:unified:all

---

src/DetailsView/components/details-view-content.tsx
src/DetailsView/details-view-initializer.ts
src/background/assessment-data-converter.ts
src/common/store-data-to-scan-node-result-converter.ts
src/common/types/store-data/assessment-result-data.ts
src/common/types/store-data/unified-data-interface.ts
src/scanner/exposed-apis.ts
src/scanner/scanner-rule-info.ts
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/DetailsView/details-view-content.test.tsx
src/tests/unit/tests/background/assessment-data-converter.test.ts
src/tests/unit/tests/common/store-data-to-scan-node-result-converter.test.ts

Uses the default rules to amend rule info to the automated checks. Removes changes to the test step result that was doing this for us because that does not cover the backwards compatibility scenario and would result in a lot of duplicate data.
Feature work.
What if we load an assessment that has a rule that is not included in the default rules? In this case, we simply do not show that info (since we do not have it) in the UI.
A further improvement to this approach would be to start storing rule information onScanCompleted in the AssessmentStore. This could then be used instead to load the data in combination with the default rule information.
Screenshots below of what automated checks looks like when loading an older assessment.
Before:
After:

feat(automated-checks): add rule info to scan node results from default rule map

---

src/DetailsView/components/assessment-issues-test-view.tsx
src/DetailsView/components/banner-warnings.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-issues-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/assessment-issues-test-view.test.tsx

Fix bug where, upon refresh of the target page, the visualizations in Assessment > Automated Checks are not re-enabled. This PR updates that the assessment issues test view to behave similarly to the RequirementView, which is responsible for handling this behavior (via the AssessmentViewUpdateHandler).
Feature work

feat(automated-checks): fix assessment automated checks visualization refresh behavior

---

src/DetailsView/components/assessment-issues-test-view.tsx
src/tests/unit/tests/DetailsView/components/assessment-issues-test-view.test.tsx

Will check assessment to be null before setting the selected test subview.
Feature work/fixes issue where switching between quick assess and assessment would crash.
Ideally, I'd like to make the assessment view update handler less brittle to changes of the step (likely by refactoring how step information is gotten ... maybe to the configuration objects) but unfortunately that would be a larger refactor than what I want to tackle right now.

fix(automated-checks): prevProps causes assessment to be null

---

src/popup/Styles/popup.scss

In Windows HC modes, Launchpad links are sometimes rendered in the same color as other text on the page, making them invisible. This was called out in #3476, which sort of morphed over time. Start at [this comment](https://github.com/microsoft/accessibility-insights-web/issues/3476#issuecomment-1111408632) to capture the problem being addressed by this PR.
The fix is to always render using link colors when HC modes are active. In non-HC modes, launchpad links and external links are assigned different colors. We lose that luxury in HC modes, so these internal links are rendered exactly the same as external links. It would be ideal to be able to tailor to specific HC modes, but that option is not available to us.
These screenshots capture OS Light and Dark modes, as well as  all HC themes …

fix: Launchpad links aren't visible as links in all Windows HC modes

---

deploy/Gruntfile.js

This implements a suggestion from @karanbirsingh to make the names of web releases in ADO more useful by having `/deploy/Gruntfile.js` dynamically update them to match the version of the extension being released (even when the version number is auto-generated for canary builds)
Make releases easier to track backwards from
n/a

chore: use web version numbers as release names

---

src/DetailsView/details-view-initializer.ts
src/background/extension-details-view-controller.ts
src/background/service-worker-init.ts
src/background/stores/assessment-store.ts
src/background/tab-event-distributor.ts
src/background/target-page-controller.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/webextension-browser-adapter.ts
src/popup/target-tab-finder.ts
src/tests/unit/common/simulated-browser-adapter.ts
src/tests/unit/tests/background/stores/assessment-store.test.ts
src/tests/unit/tests/background/tab-event-distributor.test.ts
src/tests/unit/tests/background/target-page-controller.test.ts
src/tests/unit/tests/popup/target-tab-finder.test.ts

This PR removes some spurious error spew from the service worker console along the lines of:
```
Unchecked runtime.lastError: no tab with id: 12345678
sendTabUrlUpdatedAction: tab with ID 12345678 not found, skipping action message
```
The `sendTabUrlUpdatedAction` part happens because `TargetPageController` is printing a message when it sees a browser update/navigate event for a tab that it can't successfully query the browser for information about. However, that case happens commonly in normal operation - for example, the browser sends such a navigation event every time you open a new tab because it sends us a navigation event as it preloads the new tab content in a tab that isn't visible to our extension. The message looks like an error but it isn't; less confusing to omit it.
The …

fix: prevent spurious "no tab with id errors" in console

---

src/background/service-worker-activator.ts
src/background/service-worker-init.ts
src/background/telemetry/telemetry-event-handler.ts
src/tests/unit/tests/background/service-worker-activator.test.ts
src/tests/unit/tests/background/telemetry/telemetry-event-handler.test.ts

This PR addresses an issue that could occur when upgrading the extension (including when rebuilding dev locally without reloading) where you could end up in a state with multiple service worker instances running and store initialization messages getting lost due to not targeting the authoritative one. All the app's UIs would then get stuck in loading spinners waiting for initial store state messages to get sent in reply to messages that are never received.
To achieve this, we add a new component near the beginning of the `service-worker-init` path which detects the case where the initializing service worker is not yet considered "activated" by the browser (because an old worker still exists), and forces the browser to treat the new worker as the "active" one and "claim" the communications …

fix: prevent UI getting stuck loading after service worker upgrades

---

src/assessments/repetitive-content/test-steps/bypass-blocks.tsx

Updates the link for term `skip link` in our Bypass Blocks assessment test per suggestion from #6477
Addresses #6477
n/a

fix: improve skip link definition link in Bypass Blocks assessment test

---

docs/architecture.md
src/injected/extension-disabled-monitor.ts
src/injected/frameCommunicators/browser-backchannel-window-message-poster.ts
src/tests/end-to-end/common/browser-factory.ts
src/tests/end-to-end/common/browser.ts
src/tests/end-to-end/common/page-controllers/page.ts
src/tests/end-to-end/tests/details-view/instructions.test.ts
src/tests/end-to-end/tests/details-view/overview.test.ts
src/tests/end-to-end/tests/details-view/quick-assess.test.ts
src/tests/end-to-end/tests/details-view/reflow-ui.test.ts
src/tests/end-to-end/tests/details-view/reflow.test.ts
src/tests/end-to-end/tests/details-view/settings-panel.test.ts
src/tests/end-to-end/tests/popup/hamburger-menu.test.ts
src/tests/end-to-end/tests/popup/launchpad.test.ts

This PR cleans up the Architecture document and a few lingering references to the term "Background Page" to make it more accessible for new folks learning about the codebase, for whom the current state of the architecture is much more important than the history of changes to the architecture.
Make it easier for folks to learn/onboard to the codebase, remove some old terminology to avoid confusion.
n/a

chore: clean up references to MV2 background page

---

src/assessments/adaptable-content/test-steps/reflow.tsx

This PR fixes the Reflow assessment guidance to clarify if/when 320 x 256 is equivalent to 1280 x 1024 at 400% zoom, per suggestion in our internal docs repo (1554) by @scottaohara.
Make assessment guidance more accurate
n/a

fix: update assessment reflow guidance clarifying use of 400% zoom

---

.github/dependabot.yml

Increase dependabot PR limit from the default of 5. We've seen cases where our updates get blocked behind dependabot PR's that contain breaking changes. Since we're scheduled to run dependabot once per day, we end up accumulating updates without realizing it.
Updates shouldn't hide in the dependabot queue.

chore: Increase dependabot PR limit

---

.github/dependabot.yml

Update `dependabot.yml` to ignore all updates from `@fluentui/react`
Updates to `@fluentui/react` are blocked until we replace `enzyme`.

chore: have dependabot ignore updates from @fluentui/react until we find a solution for enzyme

---

src/common/extension-telemetry-events.ts
src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts
src/tests/unit/tests/reports/components/report-sections/__snapshots__/collapsible-script-provider.test.ts.snap

Deprecating Android support will touch hundreds of files, so we're breaking it up into more manageable units. This removes the telemetry types that were defined for Android. There was an intermediate commit that resulted from noise in generating a snapshot for a unit test. At first I thought it was a platform problem, but it may have been a caching issue. I'll open an issue if I can get a consistent repro, but it seems to be unrelated to this change.
Android deprecation feature
- [n/a] Addresses an existing issue (part of Android deprecation feature)

feat(remove-android): Remove Android telemetry types

---

.github/dependabot.yml
.prettierignore
.vscode/launch.json
copyright-header.config.json
deploy/Gruntfile.js
esbuild.js
jest.config.js
src/reports/components/report-sections/fast-pass-report-automated-checks-results.tsx
targets.config.js
webpack.config.js

This cleans up some odds and ends from removing Android:
- Remove C# file types from various exclusion lists (I intentionally left the `.vs` folder, since it was in the `.gitignore` file before it was added to `.prettierignore`
- Remove some scraps of the old unified building scripts (calls were already removed, but not the guts)
- Remove configs to debug unified app from inside vscode
- Remove dependabot policy for electron
Android deprecation feature (this is potentially the last PR for this step)
There's a weird reference to `playwright` from inside main code. It feels like a bug, but since it's not part of the deprecation, I'll put it into a separate PR

feat(remove-android): Odds and ends

---

src/reports/components/report-sections/fast-pass-report-automated-checks-results.tsx

The reports package contains an odd import that seems out of place because:
- It imports from the `playwright` package, which isn't a product dependency
- The imported variable of `_electron` is never used by the code
- Tests all pass when the import is removed
Code hygiene
I came across this during the Android deprecation. I searched for "electron" and this was the list remaining instance in the code. I kept it out of the Android cleanup PR since it wasn't directly connected. The line was added in #5048, where it seems to have slipped in accidentally. 

chore: Remove odd import

---

src/DetailsView/components/adhoc-tab-stops-test-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-tab-stops-test-view.test.tsx.snap

Issue #6625 was caused by the user interacting with the test in ways that confused the automatic checks. At a future point, we might revisit the automated checks workflow, but that's not currently in scope. Instead, we're updating the instructions to clarify the intended workflow, which is that the user should traverse the entire page with just the keyboard _before returning to the extension window_. The design team also asked us to promote step 2c (review the autodetected failures) to a top-level step.
Addresses #6625
Before Change | After Change
--- | ---

fix: Improve tab stop instructions

---

.prettierignore
tools/clearly-defined/check-clearly-defined.ps1

When running `yarn fastpass`, the following error is printed to the console:
```
[format:check   ] [error] No parser could be inferred for file "C:\Users\billdengler\k4w\tools\clearly-defined\check-clearly-defined.ps1".
```
This PR excludes all `.ps1` files from format checking.
It also fixes a small typo in the clearly defined script.

fix: Exclude .ps1 files from yarn format:check

---

.prettierignore
copyright-header.config.json
tools/clearly-defined/ValidateScript.bat
tools/clearly-defined/check-clearly-defined.ps1

Note: This change is a port of https://github.com/microsoft/accessibility-insights-windows/pull/1672
#954 had 2 bugs about namespaces:
1. Dependabot adds a `/src` component to the branch name of NuGet component. The script didn't take this into account and we ended up with an incorrect url
2. Dependabot omits the `@` from branch names of npm components that include a namespace. The script didn't take this into accoiunt and we ended up with an incorrect url
The fix in both cases is the same--we add a function to adjust the raw namespace that comes from parsing the branch name. 
It also includes a batch script to aid in script validation. If we encounter future branch names that go awry, we can just add additional test cases and have protection against breakage.
Tune the desired friction of …

fix: Correct bug in ClearlyDefined check

---

.github/workflows/ci.yml

#6859 added the check to ClearlyDefined for dependabot PR's, but it used a very vague name for the step that actually calls ClearlyDefined. 
This renames the workflow step from `check-dependencies` to `check-clearly-defined`. It also renames the core task from `Run script` to `Check ClearlyDefined for dependabot PR's`
Make it clearer what this step is in the logs

chore: Make task name more useful

---

src/common/flux/persistent-store.ts
src/tests/unit/tests/background/stores/assessment-card-selection-store.test.ts
src/tests/unit/tests/background/stores/persistent-store.test.ts

This PR updates `PersistantStore.generateDefaultState` to merge in `persistedState` to `defaultState`, rather than just returning `persistedState` as-is.
Addresses #6233.

fix: Merge persisted state into default state by default

---

src/DetailsView/components/adhoc-tab-stops-test-view.tsx
src/content/adhoc/tabstops/how-to-test.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-tab-stops-test-view.test.tsx.snap

This PR fixes a small typo in the tab stop instructions.
Discovered during 2.39.0 release validation.

fix: Fix typo in tab stop instructions

---

src/DetailsView/components/help-links.scss
src/DetailsView/components/requirement-context-section.scss

`RequirementContextView` has two sections:
* Why it matters
*  heading
* paragraph of text
* Help
*  heading
* a button styled to look like a link (Info and Examples)
* 0+ help links
Currently, there is inconsistent spacing between the info and examples button and help links, more spacing between the "Help" heading and Info and Examples button than between the "Why it matters" paragraph and the "Help" heading (between the two sections), and the font size of the help links (15px) is inconsistent with the rest of the extension's text (14px). 
This PR makes the spacing between the button and links consistent, adds additional spacing between the "Why it matters" paragraph and "Help" heading to better distinguish the two sections, and changes the help links font size to match the rest of the …

feat(quick-assess-ux): Adjust styling of RequirementContextView to better align with rest of extension

---

src/DetailsView/components/switcher.tsx
src/common/components/hamburger-menu-button.tsx
src/common/feature-flags.ts
src/popup/components/popup-view.tsx
src/popup/launch-pad-row-configuration-factory.ts
src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
src/tests/end-to-end/tests/popup/__snapshots__/hamburger-menu.test.ts.snap
src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/switcher.test.tsx.snap
src/tests/unit/tests/DetailsView/components/switcher.test.tsx
src/tests/unit/tests/background/feature-flags.test.ts
src/tests/unit/tests/common/components/__snapshots__/hamburger-menu-button.test.tsx.snap
src/tests/unit/tests/common/components/hamburger-menu-button.test.tsx
src/tests/unit/tests/popup/components/popup-view.test.tsx
src/tests/unit/tests/popup/launch-pad-row-configuration-factory.test.ts

This PR makes sure that Quick Assess appears as part of the extension by default!
| | Preview Features | Launch Pad |
|-|-|-|
| Before | ![preview features pane with Quick Assess toggle present](https://github.com/microsoft/accessibility-insights-web/assets/3230904/d52c868c-0771-409d-83df-012c249f7477) | <img width="344" alt="launch pad showing three options: FastPass, Assessment, and Ad hoc tools" src="https://github.com/microsoft/accessibility-insights-web/assets/3230904/0be27482-b2e1-4739-94ad-5dd95ad7861a">
| After | ![preview features pane with no Quick Assess toggle](https://github.com/microsoft/accessibility-insights-web/assets/3230904/26c779e1-60a9-458c-a3d3-9772198d8900) | <img width="344" alt="launch pad showing four options: FastPass, Quick Assess, Assessment, and Ad hoc tools" …

feat(quick-assess-ux): Remove Quick Assess feature flag

---

src/DetailsView/components/left-nav/left-nav-link-builder.tsx
src/DetailsView/components/left-nav/quick-assess-left-nav.tsx
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/left-nav-link-builder.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx
src/tests/unit/tests/DetailsView/components/left-nav/quick-assess-left-nav.test.tsx

The left nav for Assessments renders all Assessments as `button`s because most of them are collapsible and have requirement `link`s under them. Quick Assess' left nav renders all Requirements as `link`s since none are collapsible. The Automated Checks Assessment link used to be collapsible but is non-collapsible since the Automated Checks feature. However, the link is still rendered as a `button` for both Assessment and Quick Assess. This causes it to have noticeably different styling in Windows High Contrast mode. This PR renders the Automated Checks link as a `link` for Quick Assess.
| HC Theme | Quick Assess Before | Quick Assess After | Assessment Before | Assessment After |
-------------|------------------------|----------------------|----------------------|--------------------|
| …

feat(quick-assess-ux): Force Automated Checks nav link to render as a link for Quick Assess

---

src/DetailsView/components/report-export-dialog-factory.tsx
src/DetailsView/components/should-show-report-export-button.ts
src/common/extension-telemetry-events.ts
src/reports/assessment-report-html-generator.tsx
src/reports/components/assessment-report-body.tsx
src/reports/components/assessment-report.tsx
src/reports/components/quick-assess-report-body-header.scss
src/reports/components/quick-assess-report-body-header.tsx
src/reports/report-generator.ts
src/tests/unit/tests/DetailsView/components/report-export-dialog-factory.test.tsx
src/tests/unit/tests/reports/assessment-report-html-generator.test.tsx
src/tests/unit/tests/reports/components/__snapshots__/assessment-report.test.tsx.snap
src/tests/unit/tests/reports/components/assessment-report-body.test.tsx
src/tests/unit/tests/reports/components/assessment-report.test.tsx
src/tests/unit/tests/reports/report-generator.test.ts

This PR enables the "export results" option in a QuickAssess assessment. I've confirmed that an HTML report generates showing a scoped-down list of assessments and expected passing and failing states.
Part of [Feature 2012896](https://mseng.visualstudio.com/1ES/_queries/edit/2012896) (internal access required to view).
- [?] (UI changes only) Added screenshots/GIFs to description above

feat(quick-assess-ux): Enable report export functionality in QuickAssess

---

src/tests/unit/common/__snapshots__/application-properties-provider.test.ts.snap
src/tests/unit/common/application-properties-provider.test.ts
src/tests/unit/tests/background/__snapshots__/background-message-distributor.test.ts.snap
src/tests/unit/tests/background/background-message-distributor.test.ts
src/tests/unit/tests/common/__snapshots__/store-update-message-hub.test.ts.snap
src/tests/unit/tests/common/browser-adapters/__snapshots__/background-browser-event-manager.test.ts.snap
src/tests/unit/tests/common/browser-adapters/__snapshots__/passthrough-browser-event-manager.test.ts.snap
src/tests/unit/tests/common/browser-adapters/background-browser-event-manager.test.ts
src/tests/unit/tests/common/browser-adapters/passthrough-browser-event-manager.test.ts
src/tests/unit/tests/common/promises/__snapshots__/promise-factory.test.ts.snap
src/tests/unit/tests/common/promises/promise-factory.test.ts
src/tests/unit/tests/common/store-update-message-hub.test.ts
src/tests/unit/tests/injected/frameCommunicators/__snapshots__/axe-frame-messenger.test.ts.snap
src/tests/unit/tests/injected/frameCommunicators/__snapshots__/respondable-command-message-communicator.test.ts.snap
src/tests/unit/tests/injected/frameCommunicators/__snapshots__/single-frame-messenger.test.ts.snap
src/tests/unit/tests/injected/frameCommunicators/axe-frame-messenger.test.ts
src/tests/unit/tests/injected/frameCommunicators/respondable-command-message-communicator.test.ts
src/tests/unit/tests/injected/frameCommunicators/single-frame-messenger.test.ts
src/tests/unit/tests/scanner/__snapshots__/axe-utils.test.ts.snap
src/tests/unit/tests/scanner/axe-utils.test.ts

Due to https://github.com/jestjs/jest/issues/14305, our inline snapshots are causing problems when using `yarn test -u`. We discussed this internally and decided that the simplest approach was to convert the inline snapshots to traditional snapshots. For most cases, this was just removing "Inline" from the method name and removing the string that provided the snapshot. A small number of test cases were checking multiple inline snapshots in the same test, so the approach there was to build an array of the things that were previously checked individually, then having a single snapshot for the test case.
I ran `yarn test -u` and `yarn format:fix` after making all of the changes, just to make sure that we're ready for future changes.
It will probably be easiest to review this one commit at a …

chore: Remove inline snapshots

---

tools/clearly-defined/ValidateScript.bat
tools/clearly-defined/check-clearly-defined.ps1

`check-clearly-defined.ps1` doesn't know about GitHub actions. Actions are devDepenencies by definition, so they can all be excluded. This adds a check to filter out dependabot branches that begin with "dependabot/github_actions/", based on the branch name used in #6978. The validation script is similarly updated.
Once this is reviewed and merged, the changes will be mirrored to the versions in the `axe-windows` and `accessibility-insights-windows` repos.
Reduce friction from GitHub actions being updated.

chore: Update ClearlyDefined script to ignore GitHub actions

---

.github/dependabot.yml

* Dependabot for our repos is scheduled to run at fairly different times that are inconvenient for some geographies. This PR moves this repo's dependabot time to 08:30 UTC (14:00 IST, 01:30 PDT, 00:30 PST).
* Web-based projects have many dependencies, and a low Dependabot PR limit causes us to need to run Dependabot manually multiple times to update all dependencies. This PR increases the limit for all dependency receptacles.
Part of [Feature 2083093](https://mseng.visualstudio.com/1ES/_queries/edit/2083093) (internal access required to view). …

feat(oncall-vendor-transition): Increase Dependabot limit and move scheduled runs to 08:30 UTC

---

.vscode/settings.json
tools/clearly-defined/check-clearly-defined.ps1

When porting #7046 to other repos, I noticed some style inconsistencies that had crept into our PowerShell scripts. We already recommend the PowerShell extension for vscode. This PR enables its automatic formatting features for PowerShell scripts. I also ran the script against `./tools/get-chrome-web-store-refresh-token.ps1` and `./tools/clearly-defined/check-clearly-defined.ps1` to ensure consistent formatting. The first script was already well formatted--the second received some minor whitespace tweaks.
Code consistency
- [s] Ran `yarn fastpass` …

chore: Add PowerShell auto-formatting, update scripts

---

src/assessments/pointer-motion/assessment.tsx
src/assessments/pointer-motion/test-steps/target-size.tsx
src/assessments/pointer-motion/test-steps/test-steps.ts
src/content/test/pointer-motion/index.ts
src/content/test/pointer-motion/target-size.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

This PR adds "target size" from WCAG 2.2 to the "pointer motion" assessment.
Part of the WCAG 2.2 feature (accessible internally on Azure DevOps).
This will probably conflict with #7058, I'll rebase whichever goes in second and fix any resulting conflicts.

feat(wcag-2-2): Add "target size" test

---

src/assessments/repetitive-content/assessment.tsx
src/assessments/repetitive-content/test-steps/consistent-help.tsx
src/assessments/repetitive-content/test-steps/test-steps.ts
src/content/test/repetitive-content/consistent-help.tsx
src/content/test/repetitive-content/index.ts
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

This PR adds "consistent help" from WCAG 2.2 to the "repetitive content" assessment.
Part of the WCAG 2.2 feature (accessible to internal engineers on Azure DevOps).

feat(wcag-2-2): add "consistent help" test

---

src/assessments/assessments.ts
src/assessments/cognitive/assessment.tsx
src/assessments/cognitive/test-steps/authentication.tsx
src/assessments/cognitive/test-steps/redundant-entry.tsx
src/assessments/cognitive/test-steps/test-steps.ts
src/common/types/visualization-type.ts
src/content/test/cognitive/authentication.tsx
src/content/test/cognitive/guidance.tsx
src/content/test/cognitive/index.ts
src/content/test/cognitive/redundant-entry.tsx
src/content/test/index.ts
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap
src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
src/tests/unit/tests/background/__snapshots__/initial-visualization-store-data-generator.test.ts.snap

This PR creates the "Cognitive" Assessment category, which includes:
* Getting Started (and guidance page)
* ![screen shot of Getting Started for Cognitive](https://github.com/microsoft/accessibility-insights-web/assets/3230904/93d75f26-e552-4a3f-81ad-2ca2f7a3aca9)
* Redundant Entry (and info/examples content)
* ![screen shot of redundant entry requirement](https://github.com/microsoft/accessibility-insights-web/assets/3230904/f0dad936-e4ab-43a4-93f1-cccb27d4e646)
* Authentication (and info/examples content)
* ![screen shot of authentication requirement](https://github.com/microsoft/accessibility-insights-web/assets/3230904/ee1735b5-0395-465e-b1e4-99d6952ccb9e)
feature work

feat(wcag-2-2): Add Cognitive Assessment and Requirements

---

src/common/constants/link-data-sources.ts

This PR updates the "what's new in WCAG 2.1" links in the extension for WCAG 2.2.
Related to WCAG 2.2 update, but I'd consider it non-blocking and should be checked into the next release.

feat(wcag-2-2): Update what's new links for WCAG 2.2

---

package.json
yarn.lock

[](https://github.com/microsoft/accessibility-insights-web/security/dependabot/59) calls out the fact that semver has a DOS vulnerability in its regex processing 
Address https://github.com/microsoft/accessibility-insights-web/security/dependabot/59

chore: Update semver to avoid RegEx DOS attack

---

pipeline/build-package-report.yaml
pipeline/build-package-ui.yaml
pipeline/build-package.template.yaml

Migrated publish accessibility-insights-report to npm to 1ES templates. Tested the updated pipeline and it running as expected and have verified the artifacts generated with old run. I failed npm published task intentionally in test run as I do not want publish package from my feature branch.
I also updated build-package-ui.yaml because it is also referring the same template which is referred by build-package-report.yaml
[User Story 2126539](https://dev.azure.com/mseng/1ES/_workitems/edit/2126539): [Web] Migrate "publish accessibility-insights-report to npm" to 1ES PT
- [na] Addresses an existing issue: #0000
- [na ] Added/updated relevant unit test(s) (and ran `yarn test`)
- [na] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage` …

feat(1ES pipeline Migration): Migrated "publish accessibility-insights-report to npm" pipeline to 1ES templates

---

src/tests/unit/mock-helpers/mock-module-helpers.tsx

This PR adds the `useOriginalReactElements` function to our mock module helpers. This function can be called in individual tests or in the `beforeEach` method to override any mocking previously done to React components for those tests. This allows us to have clean snapshots while also fully rendering components when we need to interact with them (e.g. button components) for tests in the same file.
feature work
This is part of our migration from Enzyme to React Testing Library …

chore(enzyme-migration): Add override functions for when we need functionality from mocked components

---

src/DetailsView/components/overview-content/overview-heading-intro.tsx
src/DetailsView/components/overview-content/overview-help-section-about.tsx
src/reports/components/assessment-report-body-header.tsx
src/reports/components/quick-assess-report-body-header.tsx
src/tests/unit/tests/reports/components/__snapshots__/assessment-report-body-header.test.tsx.snap

As called out in #7209, when we added WCAG 2.2 tests, we still had a few places in the UX where we referenced "WCAG 2.1 AA success criteria". When we discussed this in triage, the approved updated wording is now "WCAG 2.1 AA and 2.2 AA success criteria". While #7209 was specific to the report, this changes 3 other places in the UX.
The text size of the elements has not changed, but GitHub is scaling the screen grabs that are slightly different sizes, hence the potential for these seeming to be different sizes:
Element | Old | New
Assessment Overview | <img width="405" alt="image" src="https://github.com/microsoft/accessibility-insights-web/assets/45672944/f284af96-13f4-4705-a109-b66c4d6acf3b"> |  <img width="401" alt="image" …

fix: Update WCAG 2.1 AA references to include WCAG 2.2 AA

---

src/DetailsView/components/details-view-overlay/scoping-panel/scoping-container.tsx
src/DetailsView/components/details-view-switcher-nav.ts
src/DetailsView/details-view-body.tsx

As part of Typescript migration added/removed the error causing fields.
1. src/DetailsView/components/details-view-content.tsx  
- For the above file we were getting errors on getOverviewHeadingIntro, linkDataSource, getOverviewHelpSectionAbout these properties.
- These properties are referred in details-view-switcher-nav.ts, overview-content-container.tsx.
- Hence, we are not removing these properties, and added it in details-view-body.tsx.
2. src/DetailsView/components/details-view-overlay/scoping-panel/scoping-panel.tsx
- We were getting error on deps={this.props.deps}.
- In details-view-overlay.tsx class ScopingPanel is used.
- Hence, we are not removing these properties and added it in scoping-container.tsx
3. Details-view-switcher-nav.ts 
- Got error on …

chore: Typescript Cleanup- Part 1 of 3

---

src/DetailsView/components/assessment-instance-selected-button.tsx
src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/quick-assess-to-assessment-dialog.tsx
src/DetailsView/components/transfer-to-assessment-button.tsx
src/DetailsView/details-view-body.tsx
src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-instance-selected-button.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/quick-assess-to-assessment-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/transfer-to-assessment-button.test.tsx.snap
src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
src/tests/unit/tests/DetailsView/components/quick-assess-to-assessment-dialog.test.tsx
src/tests/unit/tests/DetailsView/components/should-show-report-export-button.test.ts
src/tests/unit/tests/DetailsView/details-view-body.test.tsx

This PR fixes two accessibility bugs:
* `QuickAssessToAssessmentDialog` does not redirect focus to the trigger button after it closes
* [before video](https://www.loom.com/share/6c19f10e23044a3a97064d79029b5e30)
* [after video](https://www.loom.com/share/3b1799677d114a80ab54deb140b0e5d6)
* Failure instance visual helper checkbox in issues table does not correctly update `aria-checked`/`checked` when it is toggled
* [before video](https://www.loom.com/share/9ecd18aca30a44dc86697bea37238fde)
* [after video](https://www.loom.com/share/02fdc17ca946461fb2d119c8de759150)
Accessibility Compliance
For the dialog close focus bug, I moved the `QuickAssessToAssessmentDialog` to be inside the `DetailsViewCommandBar` like the other buttons that open dialogs. I managed focus the same way we do for the …

fix: Accessibility Bugs

---

src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx

Unit test case for details-view-command-bar.test is failing due to mismatched dates between saved snapshot and rendered object. Rendered object always takes the current date. Mocked the date in the test case to return specific date instead of current date.

fix: mocked date for command Bar unit test case

---

pipeline/e2e-reliability.yaml

1ES PT adds tags to pipeline runs using the access token provided by ADO. In the case of pipeline runs against forked repos of a GitHub repo, the access token does not have Edit build quality permissions and hence cannot add tags. To unblock those pipelines, skipped tagging by using the option SkipBuildTagsForGitHubPullRequests. This is similar change which we did earlier for other pipelines like https://github.com/microsoft/accessibility-insights-docs/pull/1921
Verified that the only change in the pipeline run is that it do not add "1ES.PT.Unofficial" tag on the Run. In place of that it adds below warning message.
##[warning]1ES PT Warning: Skipping build tags as this build is a pull request form GitHub which does not have permissions to add tags.

fix: Added setting to skip tags for e2e-reliability pipeline

---

build-webCI.yaml
build.yaml

CI pipeline is failing frequently with transient timeout issues in e2e testing. GitHub PR workflow does not fail for the same step. So updating Linux image to ubuntu 20.04 in CI to match image version in GitHub PR workflow.

fix: Changing ubuntu image for CI pipeline to match the image used in github PR workflow

---

packages/report/package.json
packages/ui/package.json

Update package version for accessibility insights report and accessibility insights ui for React 18 upgrade. Please refer #7336
Note : Making as major version update. On local testing we found that it will bring a breaking change as application consuming these packages also needs to update react and react-dom to v18 to avoid type mismatch.
- [na] Addresses an existing issue: #0000
- [na] Added/updated relevant unit test(s) (and ran `yarn test`)
- [na] (UI changes only) Added screenshots/GIFs to description above
- [na] (UI changes only) Verified usability with NVDA/JAWS

chore : Update package version for accessibility insights report and accessibility insights ui

---

src/tests/unit/tests/views/content/markup/__snapshots__/code-example.test.tsx.snap
src/tests/unit/tests/views/content/markup/code-example.test.tsx
src/views/content/markup/code-example.tsx

Adding code to format nextline character (\r\n)
During feature work [Update to React 18 for Docs Repo](https://dev.azure.com/mseng/1ES/_workitems/edit/2189969) analysis and local testing, we found that there are multiple errors when we refresh the info-example pages after the first render of the page
These errors are related to difference in render in server and client side. This error can be reproducible in main branch as well. While debugging we found that a next line character available in server side which was causing difference in render. UI package is used to render info-example content and hence require a fix to avoid those errors in consuming applications as well.

fix: adding code to format nextline character (\r\n)

---

deploy/package.json
deploy/yarn.lock

Bumps [grunt-cli](https://github.com/gruntjs/grunt-cli) from 1.4.3 to 1.5.0.
Manual PR for dependabot PR #7392, as that was failing at check-clearly-defined step but details for this package is present https://api.clearlydefined.io/definitions/npm/npmjs/-/grunt-cli/1.5.0
#7392
- [na] Addresses an existing issue: #0000
- [na] (UI changes only) Added screenshots/GIFs to description above
- [na] (UI changes only) Verified usability with NVDA/JAWS

chore(deps-dev): Bump grunt-cli from 1.4.3 to 1.5.0 in /deploy

---

src/DetailsView/components/command-bar-buttons-menu.tsx
src/DetailsView/components/command-button-styles.tsx
src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/load-assessment-button.tsx
src/DetailsView/components/report-export-button.tsx
src/DetailsView/components/save-assessment-button-factory.tsx
src/DetailsView/components/save-assessment-dialog.tsx
src/common/components/controls/insights-command-button-style.tsx
src/common/components/controls/insights-command-button.tsx

initial changes

---

src/DetailsView/components/issues-table.tsx
src/background/actions/action-creator.ts
src/background/actions/card-selection-action-creator.ts
src/background/actions/needs-review-card-selection-action-creator.ts
src/background/tab-context-factory.ts
src/common/components/cards/visual-helper-toggle.tsx
src/common/message-creators/automated-checks-card-selection-message-creator.ts
src/common/message-creators/card-selection-message-creator.ts
src/common/message-creators/needs-review-card-selection-message-creator.ts
src/tests/unit/tests/DetailsView/components/issues-table.test.tsx
src/tests/unit/tests/background/actions/card-selection-action-creator.test.ts
src/tests/unit/tests/background/actions/needs-review-card-selection-action-creator.test.ts
src/tests/unit/tests/common/components/cards/visual-helper-toggle.test.tsx
src/tests/unit/tests/common/message-creators/card-selection-message-creator.test.ts
src/tests/unit/tests/common/message-creators/needs-review-card-selection-message-creator.test.ts

Two ad-hoc tools (Automated Checks and Needs Review) have the ability to view issues in DetailsView. Unfortunately, if you try to toggle either of them off in ad-hoc tools while their corresponding DetailsView list of issues is open, the DetailsView toggle will overwrite the "off" state and force it to be "on". Additionally, toggling off in DetailsView does not turn the toggle off in ad-hoc tools. 
This PR keeps these toggles in sync by:
* moving the code that determines if a scan needs to be run based on state to `componentDidMount` instead of on render.
* triggering `VisualizationActions.enableVisualization`/`VisualizationActions.disabledVisualization` when `CardSelectionActions.toggleVisualHelper` is triggered, which involves:
* making sure `VisualizationActions` are accessible from …

fix: Can't toggle off from the ad-hoc tools menu if you've toggled on in DetailsView

---

src/background/initial-visualization-store-data-generator.ts

This PR adjusts the logic for setting extension initial state so that the toggles are always off (reflecting reality because the visualizations will never be active on extension start).
Addresses #6256

fix: ad-hoc visualization state becomes inconsistent after toggling extension off and on

---

deploy/yarn.lock

Bumps [micromatch](https://github.com/micromatch/micromatch) from 4.0.4 to 4.0.8.
Manual PR for dependabot https://github.com/microsoft/accessibility-insights-web/pull/7434, as that was failing at check-clearly-defined step but details for this package is present https://clearlydefined.io/definitions/npm/npmjs/-/micromatch/4.0.8
https://github.com/microsoft/accessibility-insights-web/pull/7434

chore(deps): Bump micromatch from 4.0.4 to 4.0.8 in /deploy

---

.github/workflows/ci.yml
pipeline/build-shared.yaml

Skip codecoverage step in pipeline as codecov package is deprecated.

fix: skip codecov publish report step in ci pipeline

---

src/DetailsView/components/base-left-nav.scss
src/DetailsView/components/details-view-command-bar.scss
src/DetailsView/components/left-nav/common-left-nav-link.scss
src/DetailsView/components/left-nav/details-view-left-nav.scss
src/DetailsView/components/left-nav/left-nav-icon.scss
src/DetailsView/components/requirement-context-section.scss
src/common/components/new-tab-link-with-tooltip.scss
src/common/components/new-tab-link-with-tooltip.tsx
src/tests/unit/tests/views/content/__snapshots__/content-link.test.tsx.snap
src/views/content/content-link.tsx

Fixed the Color contrast issue of focus for left nav tab for high contrast theme.
Added underlines for links as per the requirement.
Addresses Issue - https://github.com/microsoft/accessibility-insights-web/issues/4263
Added focus indicators/clear tab on left nav. Screenshots added for reference-
Theme - Desert
Theme - Aquatic
Theme - Dusk
Theme - Night Sky
Screenshots of added underlines upon hover are pasted as below-
Theme - None
Theme - Aquatic
Theme - Desert
Theme - Dusk
Theme - Night Sky
https://github.com/microsoft/accessibility-insights-web/pull/7311

fix: Left nav lacks clear tab or focus indicators with Windows HC modes

---

.github/workflows/ci.yml
build-webCI.yaml
build.yaml
pipeline/build-all-job-per-environment.yaml
pipeline/e2e-job-per-environment.yaml

1. Ubuntu 20.04 LTS runner is removed on 2025-04-15 and causing failure in github action workflow. Changed the runner to ubuntu-22.04 to avoid future failures.
2. Changing macOS-11 to macOS-14 to fix build pipeline issues. https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=58431&view=results
CI failure is unrelated, see https://github.com/microsoft/accessibility-insights-web/issues/7323.

fix: changing ubuntu and macOS image to Latest

---

src/scanner/result-decorator.ts
src/scanner/rule-processor.ts
src/tests/unit/tests/scanner/result-decorator.test.ts
src/tests/unit/tests/scanner/rule-processor.test.ts

This PR adds the function to identity fluent ui false positive for aria-hidden-focus. It exclude the violation result for html containing `data-tabster-dummy` for aria-hidden-focus rule.
addresses issue #7598 

fix: suppress fluent ui tabster false positive
