microsoft/accessibility-insights-web

src/background/background-init.ts
Just added a comment
Needed for testing public repo and build pipeline
=> Public repo test

src/DetailsView/components/assessment-instance-table.tsx, src/DetailsView/components/base-visual-helper-toggle.tsx, src/DetailsView/components/details-view-overlay.tsx, src/DetailsView/components/start-over-dropdown.tsx, src/DetailsView/components/test-step-view.tsx, src/DetailsView/details-view-main-content.tsx, src/DetailsView/document-title-updater.ts, src/DetailsView/extensions/exclude-passing-instances-from-assessment-report.ts, src/DetailsView/extensions/select-first-requirement-after-automated-checks.ts, src/DetailsView/reports/components/assessment-report-instance-list.tsx, src/DetailsView/reports/components/formatted-date.tsx, src/DetailsView/reports/components/outcome-icon-set.tsx, src/DetailsView/reports/components/outcome-math.ts, src/DetailsView/reports/components/report-scan-details.tsx, src/DetailsView/reports/get-assessment-summary-model.ts, src/DetailsView/reports/report-name-generator.ts, src/Devtools/inspect-handler.ts, src/assessments/assessment-default-message-generator.tsx, src/scanner/unique-landmark.ts, src/tests/unit/tests/background/initial-assessment-store-data-generator.test.ts
Part 1 (favoring small PR) to fix `no-typedef` lint errors in the code.
This is part 1 of the changes. Will be creating more PRs in future.
=> [TSLint] Fix no-typedef issues - Part 1

src/content/test/headings/guidance.tsx, src/content/test/headings/heading-function.tsx, src/content/test/headings/heading-level.tsx, src/content/test/headings/no-missing-headings.tsx, src/content/test/landmarks/guidance.tsx, src/content/test/native-widgets/guidance.tsx, src/tests/unit/tests/views/content/__snapshots__/content-page.test.tsx.snap, src/tests/unit/tests/views/content/content-page.test.tsx, src/views/content/content-page.tsx
Add support to `Link` (when creating content with `create(({ Markup, Link }) => ...)` ) to handle children as text (so it override the text on the link's definition).
**Guidance for Headings**
**Code of Guidance for Headings**
Update some Links by creating them under link.tsx instead of using `<Markup.HyperLink>`.
**N/A**
=> Update Content Links

src/tests/unit/tests/background/actions/global-action-creator.test.ts, src/tests/unit/tests/scanner/color-rule.test.ts, src/tests/unit/tests/scanner/custom-widget-check.test.ts, src/tests/unit/tests/scanner/rule-to-links-mappings.test.ts, src/tests/unit/tests/scanner/widget-function.test.ts
Cleaning up more tslint:disable comment, some of them were not even needed anymore.
**N/A**
=> Clean up some tslint:disable comments

src/popup/popup.html
Fix casing for an href on html file.
**N/A**
=> Fix casing

src/DetailsView/detailsView.html
Another casing fix on a html file.
**N/A**
=> Fix casing for details view css

src/DetailsView/components/assessment-instance-table.tsx, src/DetailsView/components/assessment-table-column-config-handler.tsx, src/DetailsView/handlers/assessment-instance-table-handler.tsx, src/assessments/assessment-builder.tsx, src/assessments/automated-checks/build-test-steps-from-rules.tsx, src/assessments/common/property-bag-column-renderer-factory.tsx, src/assessments/common/property-bag-column-renderer.tsx, src/assessments/custom-widgets/custom-widgets-column-renderer-factory.tsx, src/assessments/custom-widgets/custom-widgets-column-renderer.tsx, src/assessments/headings/headings-instance-details-column-renderer.tsx, src/assessments/landmarks/landmarks-instance-details-column-renderer.tsx, src/assessments/page/frametitle-instance-details-column-renderer.tsx, src/assessments/page/pagetitle-instance-details-column-renderer.tsx, src/assessments/types/iinstance-table-column.d.ts, src/assessments/types/test-step.ts, src/tests/unit/tests/DetailsView/components/assessment-instance-table.test.tsx, src/tests/unit/tests/DetailsView/components/assessment-table-column-config-handler.test.tsx, src/tests/unit/tests/DetailsView/handlers/assessment-instance-table-handler.test.tsx, src/tests/unit/tests/assessments/automated-checks/build-test-steps-from-rules.test.tsx, src/tests/unit/tests/assessments/common/property-bag-column-renderer-factory.test.tsx, src/tests/unit/tests/assessments/common/property-bag-column-renderer.test.tsx, src/tests/unit/tests/assessments/custom-widgets/custom-widgets-column-renderer-factory.test.tsx, src/tests/unit/tests/assessments/custom-widgets/custom-widgets-column-renderer.test.tsx, src/tests/unit/tests/assessments/frametitle-instance-details-column-renderer.test.tsx, src/tests/unit/tests/assessments/headings-instance-details-column-renderer.test.tsx, src/tests/unit/tests/assessments/landmarks-instance-details-column-renderer.test.tsx, src/tests/unit/tests/assessments/pagetitle-instance-details-column-renderer.test.tsx
=> Rename some Interface names for tslint rule

src/tests/unit/tests/popup/scripts/handlers/launch-panel-header-click-handler.test.ts
Removes a stray `test.only` that was merged accidentally last week
=> Remove unintentionally merged test.only

src/background/browser-adapter.ts, src/background/stores/visualization-store.ts, src/background/tab-controller.ts, src/common/client-browser-adapter.ts, src/common/components/file-issue-details-dialog.tsx, src/common/components/selector-input-list.tsx, src/common/configs/visualization-configuration-factory.ts, src/common/configuration/index.ts, src/common/document-manipulator.ts, src/common/fabric-icons.ts, src/common/file-issue-details-handler.ts, src/common/flux/event-handler-list.ts, src/common/html-element-utils.ts, src/common/indexedDB/idb.ts, src/common/message-creators/dev-tool-action-message-creator.ts, src/common/state-dispatcher.ts, src/injected/analyzer-controller.ts, src/injected/analyzer-state-update-handler.ts, src/injected/analyzers/base-analyzer.ts, src/injected/analyzers/batched-rule-analyzer.ts, src/injected/client-utils.ts, src/injected/client-view-controller.ts, src/injected/details-dialog-handler.ts, src/injected/element-finder-by-position.ts, src/injected/frameCommunicators/html-element-axe-results-helper.ts, src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
Lint Errros after this PR: **342 ▶️  273**
=> [Lint] Fix no typedef errors

src/DetailsView/components/issues-table.tsx, src/common/feature-flags.ts, src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap, src/tests/unit/tests/DetailsView/components/issues-table.test.tsx, src/tests/unit/tests/background/feature-flags.test.ts
Remove `exportResult` feature flag.
**N/A**
=> Remove feature flag export result

src/common/indexedDB/idb.ts, src/injected/drawing-controller.ts, src/injected/drawing-initiator.ts, src/injected/frameCommunicators/scrolling-controller.ts, src/injected/frameCommunicators/window-message-handler.ts, src/injected/inspect-controller.ts, src/injected/main-window-initializer.ts, src/injected/scoping-listener.ts, src/injected/shadow-initializer.ts, src/injected/tab-stops-listener.ts, src/injected/visualization/base-drawer.ts, src/injected/visualization/drawer-utils.ts, src/injected/visualization/failure-instance-formatter.ts, src/injected/visualization/null-drawer.ts, src/injected/window-initializer.ts, src/scanner/axe-configurator.ts, src/scanner/axe-rule-overrides.ts, src/scanner/color-rule.ts, src/scanner/launcher.ts, src/scanner/page-title.ts, src/scanner/unique-landmark.ts
Continuation of the tslint fix for `no-typedef` rule.
This basically covers all of the `TS` files that are straight forward to fix. Will start working on fixing all the tests after this
=> [Lint] More typedef lint error resolution

src/DetailsView/components/details-view-command-bar.tsx, src/DetailsView/components/details-view-right-panel.tsx, src/DetailsView/components/start-over-dropdown.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-dropdown.test.tsx.snap, src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx, src/tests/unit/tests/DetailsView/components/details-view-right-panel.test.tsx, src/tests/unit/tests/DetailsView/components/start-over-dropdown.test.tsx
=> bugfix: remove start over single test option in overview

src/DetailsView/components/settings-panel.tsx, src/background/actions/global-action-creator.ts, src/background/actions/user-configuration-actions.ts, src/background/stores/global/user-configuration-store.ts, src/common/feature-flags.ts, src/common/messages.ts, src/tests/unit/tests/DetailsView/components/__snapshots__/settings-panel.test.tsx.snap, src/tests/unit/tests/DetailsView/components/settings-panel.test.tsx, src/tests/unit/tests/background/actions/global-action-creator.test.ts, src/tests/unit/tests/background/feature-flags.test.ts, src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts
Removed highContrastMode from FeatureFlags and all references to FeatureFlags.highContrastMode
=> remove feature flag high contrast mode

src/common/configs/inspect-configuration-factory.ts, src/injected/inspect-controller.ts, src/tests/unit/tests/assessments/__snapshots__/manual-test-record-your-results.test.tsx.snap, src/tests/unit/tests/assessments/manual-test-record-your-results.test.tsx, src/tests/unit/tests/background/actions/assessment-action-creator.test.ts, src/tests/unit/tests/common/configs/inspect-configuration-factory.test.ts, src/tests/unit/tests/common/message-creators/dropdown-action-message-creator.test.ts, src/tests/unit/tests/injected/inspect-controller.test.ts
Adding missing tests. Minor improvement
**N/A**
=> Adding some missing tests

src/tests/unit/common/visualization-scan-result-store-data-builder.ts, src/tests/unit/common/visualization-store-data-builder.ts, src/tests/unit/tests/DetailsView/components/issues-details-list.test.tsx, src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts, src/tests/unit/tests/injected/client-view-controller.test.ts, tslint.build-enforced.json, tslint.json
Move switch-default rule to build enforced config
**N/A**
=> [tslint] switch-default

src/DetailsView/components/export-dialog.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/export-dialog.test.tsx.snap, src/tests/unit/tests/DetailsView/components/export-dialog.test.tsx
Refactor ExportDialog:
- Move component to use `NamedSFC`
- Move tests to use `enzyme`, update test that were accessing private function to use `simulate` instead
**N/A**
=> Refactor ExportDialog

src/ad-hoc-visualizations/headings/visualization.tsx, src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts, src/tests/unit/tests/injected/element-finder-by-position.test.ts, src/tests/unit/tests/injected/frameCommunicators/frame-communicator.test.ts, src/tests/unit/tests/injected/visualization/drawer.test.ts, src/tests/unit/tests/injected/visualization/svg-drawer-v2.test.ts, src/tests/unit/tests/popup/scripts/components/launch-pad-item-row.test.tsx, src/tests/unit/tests/scanner/image-rule.test.ts, src/tests/unit/tests/scanner/message-decorator.test.ts, src/tests/unit/tests/scanner/text-contrast.test.ts
Mostly, update names to fix tslint rule isses. In some tests, remove duplicated, unneeded variables. 
**N/A**
=> No shadowed variable part 01

src/tests/unit/tests/background/actions/assessment-action-creator.test.ts, src/tests/unit/tests/background/assessment-scan-policy-runner.test.ts, src/tests/unit/tests/background/content-script-injector.test.ts, src/tests/unit/tests/background/tab-context-broadcaster.test.ts, src/tests/unit/tests/background/tab-controller.test.ts, src/tests/unit/tests/background/telemetry/app-insights-telemetry-client.test.ts, src/tests/unit/tests/common/stores/base-client-stores-hub.test.ts, src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
Mostly, update names to fix tslint rule isses. In some tests, remove duplicated, unneeded variables. 
**N/A**
=> No shadowed variable part 11

src/ad-hoc-visualizations/headings/visualization.tsx, src/ad-hoc-visualizations/issues/visualization.tsx, src/ad-hoc-visualizations/landmarks/visualization.tsx, src/background/stores/assessment-store.ts, src/background/stores/visualization-store.ts, src/injected/frameCommunicators/scrolling-controller.ts, src/injected/visualization/root-container-creator.ts, src/tests/unit/common/store-tester.ts, src/tests/unit/common/visualization-store-data-builder.ts, src/tests/unit/tests/DetailsView/components/left-nav/details-view-left-nav.test.tsx, src/tests/unit/tests/DetailsView/components/static-content-details-view.test.tsx, src/tests/unit/tests/DetailsView/details-view-container.test.tsx
Mostly, update names to fix tslint rule isses. In some tests, remove duplicated, unneeded variables. 
**N/A**
=> No shadowed variable part 10

tslint.build-enforced.json, tslint.json
=> Move no-default-export to enforced

src/content/test/focus/focus-order.tsx
Simple content update. Change double quote for single quote.
**N/A**
=> Change double quote to single quote inside a double quoted text

package-lock.json, package.json
=> fixing vulnerabilities reported by running npm audit fix

src/content/test/repetitive-content/bypass-blocks.tsx
Change double quotes to single quotes to avoid nested double quotes on content
**N/A**
=> Change double to single quotes on content

README.md
Changes the readme to add node and npm version info
=> Adding node and npm versions to the documentation

src/tests/end-to-end/common/force-test-failure.ts, src/tests/end-to-end/common/page.ts
=> capturing request failures & page crash

src/DetailsView/components/overview-content/overview-content-container.tsx, src/DetailsView/extensions/assessment-report-extension-point.ts, src/DetailsView/extensions/exclude-passing-instances-from-assessment-report.ts, src/DetailsView/reports/assessment-report-model-builder.ts, src/DetailsView/reports/assessment-report-model.ts, src/DetailsView/reports/components/assessment-report-assessment-list.tsx, src/DetailsView/reports/components/assessment-report-body.tsx, src/DetailsView/reports/components/assessment-report-instance-list.tsx, src/DetailsView/reports/components/assessment-report-step-header.tsx, src/DetailsView/reports/components/assessment-report-step-list.tsx, src/DetailsView/reports/components/assessment-report-summary.tsx, src/DetailsView/reports/components/assessment-report.tsx, src/DetailsView/reports/components/assessment-scan-details.tsx, src/DetailsView/reports/components/assessment-summary-details.tsx, src/DetailsView/reports/get-assessment-summary-model.ts, src/tests/unit/tests/DetailsView/assessment-report-builder-test-helper.ts, src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx, src/tests/unit/tests/DetailsView/extensions/exclude-passing-instances-from-assessment-report.test.ts, src/tests/unit/tests/DetailsView/reports/assessment-report-html-generator.test.tsx, src/tests/unit/tests/DetailsView/reports/components/assessment-report-assessment-list.test.tsx, src/tests/unit/tests/DetailsView/reports/components/assessment-report-step-header.test.tsx, src/tests/unit/tests/DetailsView/reports/components/assessment-scan-details.test.tsx, src/tests/unit/tests/DetailsView/reports/get-assessment-summary-model.test.ts
Remove more tslint:disable & fix interface-name errors
=> remove more tslint:disable & fix interface-name errors

src/common/components/with-store-subscription.tsx, src/common/message-creators/istore-action-message-creator.d.ts, src/common/message-creators/store-action-message-creator-factory.ts, src/common/message-creators/store-action-message-creator-impl.ts, src/common/message-creators/store-action-message-creator.ts, src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts, src/tests/unit/tests/DetailsView/details-view-container.test.tsx, src/tests/unit/tests/DetailsView/details-view-renderer.test.tsx, src/tests/unit/tests/common/components/with-store-subscription.test.tsx, src/tests/unit/tests/common/message-creators/store-action-message-creator-factory.test.ts, src/tests/unit/tests/common/message-creators/store-action-message-creator.test.ts, src/tests/unit/tests/popup/scripts/components/popup-view.test.tsx
remove TSLint disable comments for store action message creator
=> remove TSLint disable comments for store action message creator

src/assessments/native-widgets/test-steps/instructions.tsx, src/assessments/native-widgets/test-steps/label.tsx, src/common/indexedDB/indexeddb.d.ts, src/common/types/property-bag/default-widget.ts
tslint rule interface-name
**rename:**
- IDefaultWidgetPropertyBag
**remove**
- indexeddb.d.ts
**N/A**
=> tslint rule interface-name: IDefaultWidgetPropertyBag

src/common/components/with-store-subscription.tsx, src/common/stores/base-client-stores-hub.ts, src/common/stores/client-stores-hub.ts, src/tests/unit/tests/common/components/with-store-subscription.test.tsx
Rename IClientStoresHub.
**N/A**
=> tslint rule interface-name: IClientStoresHub

src/content/settings/improve-accessibility-insights.tsx, src/tests/end-to-end/tests/popup/__snapshots__/first-time-dialog.test.ts.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/settings-panel.test.tsx.snap, src/tests/unit/tests/popup/scripts/components/__snapshots__/telemetry-permission-dialog.test.tsx.snap
Update content to include link to our telemetry policy.
**On popup**
**On settings panel**
**In action**
**N/A**
=> Update telemetry warning content and test snapshots

.prettierignore
=> add *.ico to prettierignore

src/tests/unit/tests/popup/scripts/actions/popup-action-message-creator.test.ts
Add missing test for popup action message creator
**N/A**
=> Add missing test

src/popup/scripts/components/popup-view.tsx, src/tests/unit/tests/popup/scripts/components/popup-view.test.tsx
Remove unused store data properties from popup view state.
**N/A**
=> Small clean up on PopupView state

build.yaml, pipeline/e2e-test.yaml, pipeline/prerequisites.yaml
Use templates to reduce duplication on our build pipeline definition.
The end goal should be adding a ubuntu job. I have found issues running unit and e2e test so we need more time to fix those issues. This is preparation work and anything related to running our build under ubuntu is out of scope.
=> Build pipeline improvements

.vscode/launch.json
Using `fileBasename` seems to work (as oppose to `relativeFile`)
It may be worth to test this locally before approving.
=> Fix vscode unit test debugging

src/assessments/types/test-step.ts, src/common/configs/visualization-configuration-factory.ts, src/injected/drawing-controller.ts, src/injected/visualization/base-drawer.ts, src/injected/visualization/drawer-impl.ts, src/injected/visualization/drawer-provider.ts, src/injected/visualization/drawer.ts, src/injected/visualization/highlight-box-drawer.ts, src/injected/visualization/null-drawer.ts, src/injected/visualization/single-target-drawer.ts, src/injected/visualization/svg-drawer-v2.ts, src/tests/unit/tests/injected/drawing-controller.test.ts, src/tests/unit/tests/injected/visualization/drawer-provider.test.ts, src/tests/unit/tests/injected/visualization/drawer.test.ts, src/tests/unit/tests/injected/visualization/single-target-drawer.test.ts, src/tests/unit/tests/injected/visualization/svg-drawer-v2.test.ts
- Rename IDrawer to Drawer
- Rename Drawer to DrawerImpl
- Update imports
- Update filenames (not using `.d.ts` anymore)
**N/A**
=> tslint rule interface-name: IDrawer and related classes

src/DetailsView/components/preview-features-container.tsx, src/DetailsView/components/preview-features-toggle-list.tsx, src/DetailsView/handlers/preview-feature-flags-handler.ts, src/common/types/store-data/displayable-feature-flag.ts, src/tests/unit/tests/DetailsView/components/preview-features-container.test.tsx, src/tests/unit/tests/DetailsView/components/preview-features-toggle-list.test.tsx
Rename file and interface: IDisplayableFeatureFlag
**N/A**
=> tslint rule interface name: IDisplayableFeatureFlag

src/background/stores/global/command-store.ts, src/common/types/store-data/command-store-data.ts, src/popup/scripts/components/diagnostic-view-toggle-factory.tsx, src/popup/scripts/popup-initializer.ts, src/tests/unit/tests/DetailsView/store-mocks.ts, src/tests/unit/tests/background/stores/global/command-store.test.ts, src/tests/unit/tests/popup/scripts/components/popup-view.test.tsx
Rename file and interface: ICommandStoreData
**N/A**
=> tslint rule interface name: ICommandStoreData

src/DetailsView/details-view-initializer.ts, src/background/stores/inspect-store.ts, src/common/types/store-data/inspect-store-data.ts, src/injected/inspect-controller.ts, src/injected/main-window-initializer.ts, src/tests/unit/tests/background/inspect-store.test.ts, src/tests/unit/tests/injected/inspect-controller.test.ts
Rename file and interface IInspectStoreData
**N/A**
=> tslint rule interface name: IInspectStoreData

src/tests/end-to-end/tests/popup/__snapshots__/adhoc-panel.test.ts.snap, src/tests/end-to-end/tests/popup/adhoc-panel.test.ts
Added wait for selector to fix the flaky test
=> fixing build failure

src/injected/dialog-renderer.tsx, src/injected/drawing-controller.ts, src/injected/frame-url-finder.ts, src/injected/frameCommunicators/frame-communicator.ts, src/injected/frameCommunicators/scrolling-controller.ts, src/injected/tab-stops-listener.ts, src/tests/unit/tests/injected/dialog-renderer.test.tsx, src/tests/unit/tests/injected/frame-url-finder.test.ts, src/tests/unit/tests/injected/frameCommunicators/frame-communicator.test.ts, src/tests/unit/tests/injected/scrolling-controller.test.ts, src/tests/unit/tests/injected/tab-stops-listener.test.ts
changed `IMessageRequest<t>` to `MessageRequest<t>`
=> tslint rule interface name change IMessageRequest<t> to MessageRequest<t>

src/injected/client-view-controller.ts, src/injected/drawing-controller.ts, src/injected/drawing-initiator.ts, src/injected/frameCommunicators/html-element-axe-results-helper.ts, src/injected/instance-visibility-checker.ts, src/injected/selector-map-helper.ts, src/injected/visualization-instance-processor.ts, src/injected/visualization/custom-widgets-formatter.ts, src/injected/visualization/failure-instance-formatter.ts, src/injected/visualization/frame-formatter.ts, src/injected/visualization/heading-formatter.ts, src/injected/visualization/highlight-box-formatter.ts, src/injected/visualization/landmark-formatter.ts, src/tests/unit/tests/injected/client-view-controller.test.ts, src/tests/unit/tests/injected/drawing-controller.test.ts, src/tests/unit/tests/injected/drawing-initiator.test.ts, src/tests/unit/tests/injected/instance-visibility-checker.test.ts, src/tests/unit/tests/injected/selector-map-helper.test.ts, src/tests/unit/tests/injected/visualization-instance-processor.test.ts, src/tests/unit/tests/injected/visualization/heading-formatter.test.ts, src/tests/unit/tests/injected/visualization/highlight-box-formatter.test.ts, src/tests/unit/tests/injected/visualization/landmark-formatter.test.ts
Changed IFrameResult to `HTMLIFrameResult` and `IAssessmentVisualizationInstance` to `AssessmentVisualizationInstance`
=> tslint rule interface name IFrameResult & IAssessmentVisualizationInstance

.github/ISSUE_TEMPLATE/bug_report.md, .github/pull_request_template.md
Change Bug and PR template as discussed to be more clear and helpful.
List of changes:
- Ask for CodePen example in Bug template
- Reorder PR template to have description first, then Notes, then PR Checklist
=> change Bug template & PR template

package-lock.json, package.json, src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
Not a major change in axe-core; so really just upping the package.json files.
=> Updated axe to 3.2.2

src/background/background-init.ts, src/background/global-context-factory.ts, src/background/storage-data.ts, src/background/stores/global/feature-flag-store.ts, src/background/stores/global/global-store-hub.ts, src/background/stores/global/launch-panel-store.ts, src/background/telemetry/telemetry-client-provider.ts, src/tests/unit/tests/background/global-context-factory.test.ts, src/tests/unit/tests/background/stores/global/feature-flag-store.test.ts, src/tests/unit/tests/background/stores/global/global-store-hub.test.ts, src/tests/unit/tests/background/stores/global/launch-panel-state-store.test.ts, src/tests/unit/tests/background/telemetry/telemetry-client-provider.test.ts
Update file and interface names.
=> tslint rule interface name: storage-data

src/tests/end-to-end/common/timeouts.ts, src/tests/unit/tests/background/injector-controller.test.ts, src/tests/unit/tests/background/scanner-utility.test.ts, src/tests/unit/tests/common/components/toast.test.tsx, src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts, src/tests/unit/tests/injected/instance-visibility-checker.test.ts, src/tests/unit/tests/injected/scoping-listener.test.ts, src/tests/unit/tests/injected/visualization/drawer.test.ts, src/tests/unit/tests/popup/support-link-handler.test.ts
We have some bugs for tslint no-string-based-set-timeout filed by SDT-TSA. This is an attempt to fix those.
=> SDT tslint fix

src/DetailsView/components/adhoc-issues-test-view.tsx, src/DetailsView/components/test-view-container.tsx, src/DetailsView/details-view-container.tsx, src/DetailsView/details-view-initializer.ts, src/DetailsView/details-view-main-content.tsx, src/background/stores/visualization-scan-result-store.ts, src/common/types/store-data/visualization-scan-result-data.ts, src/injected/client-view-controller.ts, src/injected/main-window-initializer.ts, src/injected/selector-map-helper.ts, src/injected/visualization/svg-drawer-v2.ts, src/tests/unit/common/visualization-scan-result-store-data-builder.ts, src/tests/unit/tests/DetailsView/components/adhoc-issues-test-view.test.tsx, src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts, src/tests/unit/tests/DetailsView/store-mocks.ts, src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts, src/tests/unit/tests/injected/client-view-controller.test.ts, src/tests/unit/tests/injected/selector-map-helper.test.ts, src/tests/unit/tests/injected/visualization/svg-drawer-v2.test.ts
Rename file and interface to remove tslint:disable comment for this rule on this specific interface
=> tslint rule interface name: ivisualization-scan-result-data

src/background/stores/global/user-configuration-store.ts, src/bug-filing/bug-filing-option-provider.ts, src/bug-filing/bug-filing-service-provider.ts, src/bug-filing/components/bug-filing-choice-group.tsx, src/bug-filing/types/bug-filing-service.ts, src/tests/unit/tests/bug-filing/bug-filing-option-provider.test.ts, src/tests/unit/tests/bug-filing/components/__snapshots__/bug-filing-option-choice-group.test.tsx.snap, src/tests/unit/tests/bug-filing/components/bug-filing-option-choice-group.test.tsx
=> Add BugOptionProvider and BugFilingChoiceGroup component

src/DetailsView/components/settings-panel/settings/bug-filing/bug-filing-settings.tsx, src/DetailsView/components/settings-panel/settings/settings-provider-impl.ts, src/DetailsView/components/settings-panel/settings/settings-provider.tsx, src/tests/unit/tests/DetailsView/components/settings-panel/settings-panel.test.tsx
=> Settings panel code clean up

src/tests/unit/tests/common/extensibility/extension-point.test.ts
=> Change test name

src/bug-filing/types/bug-filing-service.ts
Minor design change required to support how we currently file bugs. Using this design for now to move forward.
- [n/a] Ran precheckin (`npm run precheckin`)
=> Update bug filing service interface (fileBug to createBugFilingUrl)

src/DetailsView/Styles/detailsview.scss, src/DetailsView/reports/components/assessment-report-summary.tsx, src/DetailsView/reports/components/outcome.scss, src/tests/unit/tests/DetailsView/reports/components/__snapshots__/assessment-report-summary.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/assessment-report-summary.test.tsx
Fix bug related to Overview finishing and styling. Attached screenshots are from production vs current change.
Production:
Changed/dev:
=> [Bug] Update overview styling and finish

src/DetailsView/Styles/detailsview.scss, src/DetailsView/components/assessment-visualization-enabled-toggle.tsx, src/DetailsView/components/base-visual-helper-toggle.tsx, src/tests/unit/tests/DetailsView/components/assessment-visualization-enabled-toggle.test.tsx, src/tests/unit/tests/DetailsView/components/restart-scan-visual-helper-toggle.test.tsx, src/tests/unit/tests/assessments/automated-checks/automated-checks-visualization-toggle.test.tsx
Change "Visual Helper" text to "Highlight instances on target page".
=> [Bug] Change visual helper text to "Highlight instances on target page"

src/content/test/multimedia/audio-description.tsx
Add missing success criteria link on Multimedia -> Audio Description content
=> Add new success criteria link

src/tests/unit/tests/common/telemetry-data-factory.test.ts, src/tests/unit/tests/injected/dialog-renderer.test.tsx, src/tests/unit/tests/injected/drawing-controller.test.ts, src/tests/unit/tests/injected/frameCommunicators/html-element-axe-results-helper.test.ts, src/tests/unit/tests/injected/frameCommunicators/window-message-handler.test.ts, src/tests/unit/tests/injected/inspect-controller.test.ts, src/tests/unit/tests/injected/layered-details-dialog-component.test.tsx, src/tests/unit/tests/injected/selector-map-helper.test.ts, src/tests/unit/tests/injected/visualization/svg-drawer-v2.test.ts, src/tests/unit/tests/injected/visualization/svg-shape-factory.test.ts, src/tests/unit/tests/injected/visualization/tab-stops-formatter.test.ts, src/tests/unit/tests/popup/components/header-contextual-menu.test.tsx, src/tests/unit/tests/popup/components/popup-view.test.tsx, src/tests/unit/tests/scanner/axe-utils.test.ts, src/tests/unit/tests/scanner/check-message-transformer.test.ts, src/tests/unit/tests/scanner/custom-widget-check.test.ts, src/tests/unit/tests/scanner/processor.test.ts, src/tests/unit/tests/views/content/markup/code-example.test.tsx, src/tests/unit/tests/views/insights/renderer.test.tsx, src/views/insights/dependencies.ts
Clean up unused variables/imports. General idea is finish the clean up and then enable `noUnusedParameters` & `noUnusedLocals`  options on tsconfig.json
=> Clean up unused variables/imports

src/injected/analyzers/analyzer.ts, src/injected/analyzers/base-analyzer.ts, src/injected/analyzers/tab-stops-analyzer.ts, src/tests/unit/tests/injected/analyzers/base-analyzer.test.ts, src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts, src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts, src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
=> BugFix: rename type to messageType

README.md, package.json
Add a comment about the node version being used on our builds.
Use bold font to highlight the versions are **minimum** requirements.
This comes from our engineering discussion.
=> node & npm versions on Readme and package.json

src/common/feature-flags.ts, src/tests/unit/tests/background/feature-flags.test.ts
Add feature flag for new issue filing experience
=> Feature flag for new issue filing experience

src/DetailsView/components/assessment-view.tsx, src/DetailsView/reports/assessment-report-model-builder.ts, src/DetailsView/reports/get-assessment-summary-model.ts, src/assessments/types/iassessment.ts, src/background/completed-test-step-telemetry-creator.ts, src/background/create-initial-assessment-test-data.ts, src/background/initial-assessment-store-data-generator.ts, src/background/scan-unscanned-requirement.ts, src/background/stores/assessment-store.ts, src/common/assessment/assessment-test-result.ts, src/common/configs/visualization-configuration-factory.ts, src/common/types/store-data/assessment-result-data.ts, src/tests/unit/common/assessment-data-builder.ts, src/tests/unit/common/assessment-store-data-builder.ts, src/tests/unit/common/test-assessment-provider.tsx, src/tests/unit/tests/DetailsView/assessment-report-builder-test-helper.ts, src/tests/unit/tests/DetailsView/components/assessment-test-view.test.tsx, src/tests/unit/tests/DetailsView/components/assessment-view.test.tsx, src/tests/unit/tests/DetailsView/components/left-nav/details-view-left-nav.test.tsx, src/tests/unit/tests/DetailsView/details-view-main-content.test.tsx, src/tests/unit/tests/background/assessment-scan-policy-runner.test.ts, src/tests/unit/tests/background/completed-test-step-telemetry-creator.test.ts, src/tests/unit/tests/background/initial-assessment-store-data-generator.test.ts, src/tests/unit/tests/background/scan-unscanned-requirement.test.ts, src/tests/unit/tests/background/stores/assessment-store.test.ts, src/tests/unit/tests/common/assessment/assessment-test-result.test.ts, src/tests/unit/tests/common/configs/visualization-configuration-factory.test.ts
Rename IAssessmentData to AssessmentData. Remove tslint disable comment. Update all references.
=> tslint rule interface-name: IAssessmentData

src/DetailsView/components/issue-filing-dialog.tsx, src/common/components/issue-filing-button.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap, src/tests/unit/tests/common/components/__snapshots__/issue-filing-button.test.tsx.snap
Fix bug where new window is open after user opens issue filing dialog.
=> fix bug where new window is open 

package-lock.json, package.json
Ran `npm audit fix` to fix high severity vulnerabilities.
=> Fix vulnerabilities found by npm audit

src/DetailsView/components/Issues-details-pane.tsx, src/DetailsView/components/settings-panel/settings/bug-filing/bug-filing-settings.tsx, src/common/feature-flags.ts, src/injected/components/details-dialog.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/issues-details-pane.test.tsx.snap, src/tests/unit/tests/DetailsView/components/settings-panel/settings/bug-filing/__snapshots__/bug-filing-settings.test.tsx.snap, src/tests/unit/tests/background/feature-flags.test.ts, src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
Remove old `showBugFiling` feature flag.
=> Remove old bug filing feature flag

src/injected/components/details-dialog.tsx
Remove unused import (we now have a tslint rule to check for this)
=> Fix build failure

src/background/actions/action-payloads.ts, src/background/actions/global-action-creator.ts, src/background/actions/user-configuration-actions.ts, src/background/stores/global/user-configuration-store.ts, src/common/message-creators/user-config-message-creator.ts, src/common/messages.ts, src/tests/unit/tests/background/actions/global-action-creator.test.ts, src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts, src/tests/unit/tests/common/message-creators/user-config-message-creator.test.ts
Background support for save issue filing settings. This will be used in Wahaj's change to fix the cancel button's UX.
No UX changes.
=> background support for save issue filing settings 

src/background/stores/global/user-configuration-store.ts, src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts
Handle new property added in persisted data
=> [bug fix] Handle new property added in persisted data

package-lock.json, package.json
Fix alert raised for a high severity security vulnerability.
=> bug: fix component governance alert for puppeteer

src/common/feature-flags.ts, src/tests/unit/tests/background/feature-flags.test.ts
Turn on Issue filing feature flag. Do not merge until the other two PR(Azure Boards url & cancel button IX change) get in.
=> Turn on Issue filing feature flag

src/DetailsView/details-view-initializer.ts
Fix master broken state.
Remove double variable declaration
=> Remove double variable declaration

src/DetailsView/details-view-initializer.ts
fix details view crash when target page is closed
=> BugFix fix details view crash when target page is closed

.github/pull_request_template.md
Adds a line to our PR checklist for doing screen reader testing of UI changes
=> Suggest SR testing of UI changes in PR template

src/tests/unit/tests/views/content/markup/code-example.test.tsx, src/views/content/markup/code-example.tsx
Fix react key props issue on code-example, and make sure they are all unique.
=> Fix react key props issue on code-example

src/background/browser-adapter.ts
- Remove a couple of function we were not actually using.
- Remove optionality from interface member functions.
=> [Clean up] Browser adapter clean up

src/common/messages.ts
Extract common prefix to decrease duplication.
=> refactor: extract message prefix to const

src/DetailsView/Styles/detailsview.scss, src/ad-hoc-visualizations/issues/visualization.tsx
Update subtitle for automated checks (on FastPass) to match new requirement. Update container size to control text wrapping
**text content**
=> fix: update subtitle text

src/DetailsView/Styles/detailsview.scss, src/DetailsView/components/target-page-changed-view.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-changed-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/target-page-changed-view.test.tsx
- Refactor component test to use snapshot
- Refactor component to be a `NamedSFC`
- Add support to show `subtitle`
=> fix: missing subtitle on target page changed view

src/tests/unit/tests/background/global-context-factory.test.ts, src/tests/unit/tests/background/tab-context-broadcaster.test.ts, src/tests/unit/tests/background/tab-controller.test.ts, src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts, src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts, src/tests/unit/tests/injected/frame-url-finder.test.ts, src/tests/unit/tests/injected/frame-url-search-initiator.test.ts, src/tests/unit/tests/injected/frameCommunicators/window-message-handler.test.ts, src/tests/unit/tests/injected/visualization/drawer.test.ts, src/tests/unit/tests/scanner/scan-parameter-generator.test.ts, src/tests/unit/tests/views/content/markup.test.tsx
Update mock const names to match our naming (unwritten) convention
=> refactor: normalize const names

.github/pull_request_template.md
Changed PR template to suggest running `test` and `precheckin` with yarn instead of npm to match the README
=> fix: update PR template to use yarn instead of npm

src/DetailsView/components/issues-table.tsx, src/tests/unit/tests/DetailsView/components/issues-table.test.tsx
bugfix: issue table broken when scanning
=> bugfix: issue table broken when scanning

src/DetailsView/reports/components/report-body.tsx, src/DetailsView/reports/components/report-sections/footer.tsx, src/tests/unit/tests/DetailsView/reports/components/__snapshots__/report-body.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/footer.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/footer.test.tsx
Extract footer component to reuse it on the new report.
=> refactor: extract footer component

src/DetailsView/reports/components/instance-list-group-header.tsx, src/injected/styles/injected.scss, src/tests/unit/tests/DetailsView/components/__snapshots__/instance-list-group-header.test.tsx.snap, src/tests/unit/tests/DetailsView/components/instance-list-group-header.test.tsx
Add the new group header for instance list
=> Add the new group header for instance list

package.json, yarn.lock
Update some dependencies:
- mini-css-extract-plugin
- q
- tslint-microsoft-contrib
Did smoke test on the extention, covering all our mayor user cases.
- there is no issues but this is a recurrent task
- no actual changes
- no actual changes
=> chore: dependency updates

src/DetailsView/reports/automated-checks-report.scss, src/DetailsView/reports/components/report-sections/automated-checks-report-section-factory.tsx, src/DetailsView/reports/components/report-sections/not-applicable-section.tsx, src/DetailsView/reports/components/report-sections/passed-checks-section.tsx, src/DetailsView/reports/components/report-sections/result-section-title.tsx, src/DetailsView/reports/components/report-sections/result-section.tsx, src/DetailsView/reports/components/report-sections/rule-detail.tsx, src/DetailsView/reports/components/report-sections/rule-details-group.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/not-applicable-checks-sections.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/passed-checks-sections.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/result-section-title.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/result-section.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rule-detail.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rule-details-group.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/not-applicable-checks-sections.test.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/passed-checks-sections.test.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/result-section-title.test.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/result-section.test.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/rule-detail.test.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/rule-details-group.test.tsx
Adding passed and not applicable checks section
**Notes**
There are some missing stylings on this PR (knowingly: centering each rule into its container, not applicable checks icon -which should be part of Haonan's PR, there is something odd about the font colors and/or weight, I already talked to Chelsea about this). I'm planning on tackle those issues on a different PR so we can have this code as a base for the last section: failed instances list!
**passed checks section**
**not applicable checks section**
=> Passed non applicable checks

src/DetailsView/reports/automated-checks-report.scss, src/DetailsView/reports/components/outcome.scss, src/DetailsView/reports/components/report-sections/outcome-summary-bar.tsx, src/common/icons/icon.scss, src/common/icons/inapplicable-icon.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/outcome-summary-bar.test.tsx.snap
Update summary icons to match the mock.
=> Update summary icons

README.md
Changed README file to instruct users to run "yarn build" before trying to run unit tests.
=> Readme instruction clarification

src/DetailsView/reports/automated-checks-report.scss, src/DetailsView/reports/components/instance-list-group-header.tsx, src/DetailsView/reports/components/report-sections/result-section.tsx, src/DetailsView/reports/components/report-sections/rule-detail.tsx, src/DetailsView/reports/components/report-sections/rule-details-group.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/instance-list-group-header.test.tsx.snap, src/tests/unit/tests/DetailsView/components/instance-list-group-header.test.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/result-section.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rule-detail.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rule-details-group.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/rule-detail.test.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/rule-details-group.test.tsx
updating group header using InstanceListGroupHeader
=> updating group header using InstanceListGroupHeader

src/DetailsView/reports/components/report-sections/automated-checks-report-section-factory.tsx, src/DetailsView/reports/components/report-sections/report-body.tsx, src/DetailsView/reports/components/report-sections/report-section-factory.tsx, src/DetailsView/reports/components/report-sections/results-container.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/results-container.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/report-body.test.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/results-container.test.tsx
- add proper results container component
- rename factory properties to better reflect meaning
=> report minor refactor

src/DetailsView/reports/automated-checks-report.scss
add animation to chevron in automated checks report for its expansion and closing.
=> feat: add animation to chevron in automated checks report

src/DetailsView/reports/automated-checks-report.scss, src/DetailsView/reports/components/report-sections/automated-checks-report-section-factory.tsx, src/DetailsView/reports/components/report-sections/report-body.tsx, src/DetailsView/reports/components/report-sections/report-footer.tsx, src/DetailsView/reports/components/report-sections/report-section-factory.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/report-body.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/report-footer.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/report-footer.test.tsx
update footer for the new report:
=> update footer for the new report 

src/common/icons/icon.scss
=> fix n/a icon

src/DetailsView/reports/automated-checks-report.scss
Fixing a bunch of styling issues. This changes came from Chelsea.
=> new report more fit and finish

src/DetailsView/reports/components/report-sections/report-footer.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/report-footer.test.tsx.snap
remove invalid aria-labelledby on the tool link.
=> remove invalid aria attr

src/DetailsView/reports/automated-checks-report.scss, src/DetailsView/reports/components/report-sections/collapsible-result-section.tsx, src/DetailsView/reports/components/report-sections/not-applicable-section.tsx, src/DetailsView/reports/components/report-sections/passed-checks-section.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/collapsible-result-section.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/not-applicable-checks-sections.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/passed-checks-sections.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/collapsible-result-section.test.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/not-applicable-checks-sections.test.tsx
Make both, pass checks and not applicable checks sections, collapsibles
=> feature: collapsible pass/not applicable sections

src/DetailsView/reports/components/instance-details.scss
=> Break html snippet  to fix table width 

src/DetailsView/reports/components/report-sections/details-section.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/details-section.test.tsx.snap
- Remove some code duplication.
- Remove some unneeded aria attributes.
- Update snap shot file
- snapshot file updated
- change doesn't affect UI
- validate information is being announced properly (and same as before)
=> refactor: clean up new report scan details section

src/assessments/custom-widgets/custom-widgets-column-renderer.tsx, src/tests/unit/tests/assessments/custom-widgets/custom-widgets-column-renderer.test.tsx
Fixed dislosure -> disclosure typos throughout codebase (just the one instance from the issue and its test)
=> fix: typo (dislosure -> disclosure)

src/DetailsView/reports/components/report-sections/automated-checks-report-section-factory.tsx, src/DetailsView/reports/components/report-sections/not-applicable-checks-section.tsx, src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/not-applicable-checks-sections.test.tsx.snap, src/tests/unit/tests/DetailsView/reports/components/report-sections/not-applicable-checks-sections.test.tsx
Adding 'checks' to not applicable checks section title.
=> fix: not applicable checks section title

src/injected/visualization/formatter.ts, src/injected/visualization/highlight-box-drawer.ts, src/injected/visualization/landmark-formatter.ts, src/tests/unit/tests/injected/visualization/landmark-formatter.test.ts
Update visualizations for landmark rule.
=> fix: update landmark visualizations

package.json, src/DetailsView/components/start-over-dropdown.tsx, yarn.lock
Update prettier on it's own PR as it forced me to update a file.
- n/a
- n/a
- n/a
- n/a
- n/a
=> chore: update prettier

package.json, yarn.lock
Update react-router-dom
Check all our content is loading properly (mostly guidance links on the assessment and on the ad hoc tools panel). End to end test should cover our content.
- no changes
- no changes
=> chore: update react-router-dom

src/injected/visualization/highlight-box-drawer.ts, src/injected/visualization/highlight-visualization.tsx, src/tests/unit/tests/injected/visualization/__snapshots__/highlight-visualization.test.tsx.snap, src/tests/unit/tests/injected/visualization/highlight-visualization.test.tsx
Replaces a lot of what is happening in highlight-box-drawer.
Link to code here: https://github.com/microsoft/accessibility-insights-web/blob/589e11c3dc6e836f71ea103414504813c05d8dd0/src/injected/visualization/highlight-box-drawer.ts#L146
=> Created a highlight visualization component

package.json
=> chore: make a @type dep a dev dep

README.md, docs/git-branch-setup.md
- README to link to `git-branch-setup.md` to fork the repo before cloning it (moved cloning instructions to `git-branch-setup.md`)
- Formatting of some items in `git-branch-setup.md` for more clarity
=> docs: update readme to include fork instructions

src/background/global-action-creators/feature-flags-action-creator.ts, src/background/global-action-creators/global-action-creator.ts, src/background/global-context-factory.ts, src/tests/unit/tests/background/global-action-creators/feature-flags-action-creator.test.ts, src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts
Extract feature flag related code from global action creator to new feature flag action creator
- no changes
- no changes
=> refactor: extract feature flag action creator

src/injected/visualization/tab-stops-formatter.ts, src/tests/unit/tests/injected/details-dialog-handler.test.ts
This changes will support the update of typescript to version 3.x and they have to do with types.
- no changes
- no changes
=> refactor: small changes to support ts 3.x

deploy/package.json
Updating grunt version. 
We should make note of this, make sure both grunt version are in sync.
=> chore: update grunt version on deploy package deps

Gruntfile.js, build.yaml, package.json, pipeline/e2e-test.yaml
Reverts microsoft/accessibility-insights-web#881
Investigation suggests #910 was introduced by this PR.
=> Revert "building the web extension only"

docs/git-branch-setup.md
These changes make it easier to read the readme - we have added formatting. It is easier to copy-paste the git commands as well.
=> docs: readme improvements for the git setup

pipeline/e2e-reliability.yaml
The image name is repeated throughout the yaml file. Using a variable for each system reduces the duplication to a minimum.
=> test: using variable for the pool image values

src/assessments/assessments.ts, src/assessments/errors/assessment.tsx, src/assessments/errors/test-steps/status-messages.tsx, src/assessments/errors/test-steps/test-steps.ts, src/assessments/keyboard-interaction/assessment.tsx, src/assessments/keyboard-interaction/test-steps/character-key-shortcuts.tsx, src/assessments/keyboard-interaction/test-steps/test-steps.ts, src/assessments/pointer-motion/assessment.tsx, src/assessments/pointer-motion/test-steps/motion-operation.tsx, src/assessments/pointer-motion/test-steps/pointer-cancellation.tsx, src/assessments/pointer-motion/test-steps/pointer-gestures.tsx, src/assessments/pointer-motion/test-steps/test-steps.ts, src/assessments/text-legibility/assessment.tsx, src/assessments/text-legibility/test-steps/hover-focus-content.tsx, src/assessments/text-legibility/test-steps/orientation.tsx, src/assessments/text-legibility/test-steps/reflow.tsx, src/assessments/text-legibility/test-steps/test-step.ts, src/assessments/text-legibility/test-steps/text-spacing.tsx, src/common/types/visualization-type.ts, src/content/link.tsx
This adds all of the requirements and new tests that are completely manual for WCAG 2.1. The content is not included in this PR and will be added/linked later.
=> Added test/requirements for manual wcag 2.1 tests

.vscode/launch.json, webpack.config.js
Referred https://electronjs.org/docs/tutorial/debugging-main-process-vscode
=> adding support to debug electron app

src/ad-hoc-visualizations/color/visualization.tsx, src/ad-hoc-visualizations/headings/visualization.tsx, src/ad-hoc-visualizations/issues/visualization.tsx, src/ad-hoc-visualizations/landmarks/visualization.tsx, src/ad-hoc-visualizations/tab-stops/visualization.tsx
Update all imports on ad-hoc-visualization folder
- no code change
- not affected
- not affected
- not affected
=> refactor: update imports on ad-hoc-visualization folder

src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap
update e2e snapshots after wcag 2.1 content update
=> test: update e2e snapshots after wcag 2.1 content update

src/assessments/text-legibility/assessment.tsx, src/content/test/errors/status-messages.tsx, src/content/test/text-legibility/guidance.tsx, src/content/test/text-legibility/orientation.tsx, src/content/test/text-legibility/text-spacing.tsx, src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap
There were some minor text changes that were missed in earlier PRs and are being added here (largely missing spaces).
=> Fixes minor typos/missing spaces for content for new manual wcag 2.1 tests

README.md
Update README to contain dependabot badge!
=> chore: Update README to contain dependabot badge!

webpack.config.js
Enabling name mangling in our prod minifier settings (causes it to rename variables during minification to be single characters) decreases our prod bundle sizes by ~29% and decreased time to interactive on the details page (measured as "the point where the loading spinner goes away and the main page starts animating in) by ~9% (from 770ms +- 15ms to 710ms +- 20ms).
It's extremely rare for us to have to debug in a prod extension build (even in the worst case, if a customer needs to perform a repro on our behalf, they can do so with a canary/playground build if necessary to get debug bundles).
**without mangling (before this PR):**
```
Asset      Size  Chunks             Chunk Names
background.bundle.js  4.13 MiB       0  [emitted]  background
background.css  5.96 KiB       0  [emitted] …
```
=> perf: improve prod time-to-interactive by ~9% by enabling minifier name mangling

.github/CODEOWNERS
Change code owner group for this repo from accessibility-insights-web-code-owners group to broader accessibility-insights-code-owners group to expand set of possible reviewers.
=> chore: Use broader code owners group

src/assessments/common/instructions-and-labels-note.tsx, src/assessments/custom-widgets/test-steps/instructions.tsx, src/assessments/native-widgets/test-steps/instructions.tsx, src/tests/unit/tests/assessments/common/__snapshots__/instructions-and-labels-note.test.tsx.snap, src/tests/unit/tests/assessments/common/instructions-and-labels-note.test.tsx
Update Instructions requirement content for Native Widgets and Custom Widgets.
**ORIGINAL: native widgets -> instructions**
**UPDATED: native widgets -> instructions**
**ORIGINAL: custom widgets -> instructions**
**UPDATED: custom widgets -> instructions**
=> feat: update requirement content for Native and Custom Widgets, Instructions requirement

src/common/types/store-data/unified-data-interface.ts
- Add 'ruleId' as a first-class citizen of UnifiedResult because all results are expected to have rule ids
- rename 'id' to 'uid' because the latter more clearly describes the fields purpose
=> Update UnifiedResult interface fields

src/assessments/custom-widgets/test-steps/design-pattern.tsx, src/scanner/custom-rules/custom-widget.ts, src/scanner/custom-rules/link-purpose.ts, src/tests/unit/tests/scanner/custom-rules/custom-widget-check.test.ts, src/tests/unit/tests/scanner/custom-rules/link-purpose.test.ts
Edit existing custom rules to include certain properties: element, accessibleName
=> Edit existing custom rules to include certain properties

src/scanner/axe-rule-overrides.ts, src/scanner/exposed-apis.ts, src/scanner/help-url-getter.ts, src/tests/unit/tests/scanner/axe-rule-overrides.test.ts, src/tests/unit/tests/scanner/help-url-getter.test.ts
Refactored some variables that were misspelled
=> refactor: misspelled variables

src/DetailsView/components/cards-view.tsx, src/DetailsView/components/cards/failed-instances-section-v2.tsx, src/DetailsView/components/details-list-issues-view.tsx, src/DetailsView/components/details-view-right-panel.ts, src/DetailsView/components/issues-table.tsx, src/DetailsView/components/test-view-container.tsx, src/DetailsView/details-view-container.tsx, src/DetailsView/details-view-initializer.ts, src/DetailsView/details-view-main-content.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/cards-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/details-list-issues-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap, src/tests/unit/tests/DetailsView/components/cards-view.test.tsx, src/tests/unit/tests/DetailsView/components/cards/__snapshots__/failed-instances-section-v2.test.tsx.snap, src/tests/unit/tests/DetailsView/components/cards/sample-view-model-data.ts, src/tests/unit/tests/DetailsView/components/details-list-issues-view.test.tsx, src/tests/unit/tests/DetailsView/components/issues-table.test.tsx, src/tests/unit/tests/DetailsView/components/test-view-container.test.tsx, src/tests/unit/tests/DetailsView/details-view-container.test.tsx, src/tests/unit/tests/DetailsView/details-view-main-content.test.tsx
All changes are revolving around piping data through.
=> feat: carry rule result by status data to cards view (and beyond)

src/assessments/native-widgets/test-steps/autocomplete.tsx, src/assessments/native-widgets/test-steps/test-steps.ts, src/content/test/native-widgets/autocomplete.tsx, src/content/test/native-widgets/index.ts, src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap
Add new requirement: Native widgets -> Autocomplete
**Note** this PR does not hook up the new requirement just yet. We do want to make that change in at specific time.
**Info & Examples -> Fail and Pass examples**
=> feat: new requirement native widgets -> autocomplete

src/assessments/text-legibility/test-steps/text-spacing.tsx
=> fix link for bookmarklet

src/assessments/contrast/assessment.tsx, src/assessments/native-widgets/assessment.tsx
Enabling new test: contrast by remove the required feature flag (showAllAssessments)
Enabling native widgets new requirement: autocomplete by adding the requirement to the assessment.requirements array
=> feat: enable test: contrast and requirement: autocomplete

src/DetailsView/components/cards/collapsible-component-cards.tsx, src/DetailsView/components/cards/rules-with-instances-v2.tsx, src/tests/unit/tests/DetailsView/components/cards/__snapshots__/rules-with-instances-v2.test.tsx.snap, src/tests/unit/tests/common/components/__snapshots__/collapsible-component-cards.test.tsx.snap, src/tests/unit/tests/common/components/collapsible-component-cards.test.tsx
Added heading div for collapsible component cards around ActionButton
=> Update heading for collapsible component cards

src/tests/end-to-end/tests/target-page/visualization-boxes.test.ts
=> E2e reliability/headings experiment

src/DetailsView/details-view-initializer.ts, src/background/background-init.ts, src/background/telemetry/application-telemetry-data-factory.ts, src/background/telemetry/telemetry-client-provider.ts, src/common/browser-adapters/app-data-adapter.ts, src/common/browser-adapters/browser-adapter.ts, src/common/browser-adapters/chrome-adapter.ts, src/injected/main-window-initializer.ts, src/injected/window-initializer.ts, src/tests/unit/tests/background/telemetry/application-telemetry-data-factory.test.ts, src/tests/unit/tests/background/telemetry/telemetry-client-provider.test.ts
Created the `AppDataAdapter` type to hold the extracted method. Updated telemetry related classes to refer to this new type
- [N/A ] (UI changes only) Added screenshots/GIFs to description above
=> refactor: extracted getVersion from BrowserAdapter

src/electron/device-connect-view/components/device-connect-view-container.tsx, src/electron/device-connect-view/device-connect-view-initializer.ts, src/electron/device-connect-view/device-connect-view-renderer.tsx, src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/device-connect-view-container.test.tsx.snap, src/tests/unit/tests/electron/device-connect-view/components/device-connect-view-container.test.tsx, src/tests/unit/tests/electron/device-connect-view/device-connect-view-renderer.test.tsx
- introduce DeviceConnectViewContainer component
- update renderer to use container component
- move props building to initializer (composition root)
- not affected
- not affected
=> refactor: Introduce device connect view container

src/electron/device-connect-view/device-connect-view-initializer.ts, src/electron/platform/android/fetch-scan-results.ts, src/tests/unit/electron/platform/android/fetch-scan-results.test.ts
Use async/await syntax to simplify `fetchScanResults`.
Add missing tests for `fetchScanResults`
- not affected
- not affected
=> refactor: improve fetch scan results

src/electron/device-connect-view/components/device-connect-body.tsx, src/electron/device-connect-view/components/device-connect-connected-device.tsx, src/electron/device-connect-view/components/device-connect-footer.tsx, src/electron/device-connect-view/components/device-connect-header.scss, src/electron/device-connect-view/components/device-connect-header.tsx, src/electron/device-connect-view/components/device-connect-port-entry.tsx, src/electron/device-connect-view/components/window-title.scss, src/electron/device-connect-view/components/window-title.tsx, src/electron/device-connect-view/device-connect-view.scss, src/electron/device-connect-view/deviceConnectView.html, src/electron/device-disconnected-popup/device-disconnected-popup.scss, src/electron/device-disconnected-popup/device-disconnected-popup.tsx, src/tests/unit/electron/device-disconnected-popup/__snapshots__/device-disconnected-popup.test.tsx.snap, src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/device-connect-body.test.tsx.snap, src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/device-connect-connected-device.test.tsx.snap, src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/device-connect-footer.test.tsx.snap, src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/device-connect-header.test.tsx.snap, src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/device-connect-port-entry.test.tsx.snap, src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/window-title.test.tsx.snap, src/tests/unit/tests/electron/device-connect-view/components/device-connect-footer.test.tsx, src/tests/unit/tests/electron/device-connect-view/components/device-connect-port-entry.test.tsx
Using CSS Module on all AI-Android components.
- not affected
- not affected
=> refactor: css modules on ai android

.gitignore
Add Visual Studio working files to things to ignore in git.
=> Add Visual Studio working files to things to ignore in git

src/electron/views/automated-checks/components/header-section.scss, src/electron/views/automated-checks/components/header-section.tsx, src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/header-section.test.tsx.snap, src/tests/unit/tests/electron/views/automated-checks/components/header-section.test.tsx
Add the "header" section of the automated checks/results view
=> feat: automated checks header section

src/electron/flux/action-creator/window-state-action-creator.ts, src/electron/window-frame-updater.ts, src/tests/electron/window-frame-updater.test.ts, src/tests/unit/tests/electron/flux/action-creator/window-state-action-creator.test.ts
created window state action creator and the appropriate test
=> created window state action creator and appropriate test

src/electron/views/renderer-initializer.ts
Initializing scan controller and unified scan results store and all of their dependencies.
Out of scope for this PR:
- actually trigerring the scan started action so the scan controller runs the scan and send the results to the store will be on a separated PR
=> feat(android-cards-view): create unified results store and scan controller

src/background/actions/action-payloads.ts, src/background/stores/card-selection-store.ts, src/common/components/cards/instance-details.tsx, src/common/message-creators/card-selection-message-creator.ts, src/tests/unit/tests/background/actions/card-selection-action-creator.test.ts, src/tests/unit/tests/background/stores/card-selection-store.test.ts, src/tests/unit/tests/common/components/cards/__snapshots__/card-kebab-menu-button.test.tsx.snap, src/tests/unit/tests/common/components/cards/instance-details.test.tsx, src/tests/unit/tests/common/message-creators/card-selection-message-creator.test.ts
Finished the implementation of CardSelectionStore
=> Implement toggleCardSelection in CardSelectionStore

src/electron/views/device-disconnected-popup/status-caution-icon.tsx, src/icons/brand/blue/brand-blue.tsx
Addressing warnings as shown below:
=> Update svg property name to avoid Error messages in console

src/common/rule-based-view-model-provider.ts
This will be useful in the upcoming change where we need to add cardSelectionViewData into the view model data created in this function.
=> Refactor getUnifiedRuleResults to have only one place where cards results are added to the view

src/background/stores/card-selection-store.ts, src/tests/unit/tests/background/stores/card-selection-store.test.ts
=> Fix an incorrect variable check

src/common/components/toast.tsx, src/tests/unit/tests/common/components/__snapshots__/toast.test.tsx.snap
Fix the a11y issue on toast.
Now, after click, the AT will announce: 
**Failure details copied.
More actions menu button subMenu**
=> fix toast a11y issue 

src/electron/main/main.ts, src/electron/views/automated-checks/automated-checks-view.tsx, src/electron/views/device-connect-view/components/device-connect-view-container.tsx, src/electron/views/device-connect-view/device-connect-view.scss, src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap, src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-view-container.test.tsx.snap
(Ignore the blue line inside the screenshot. I added a div with border to test the scroll bar.)
When you have a child that with min width & cannot be broken, you will see a horizontal scrollbar
=> updating scroll bar styling

src/common/components/cards/rule-resources.tsx, src/common/components/guidance-links.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/cards-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/details-list-issues-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap, src/tests/unit/tests/common/components/cards/__snapshots__/failed-instances-section.test.tsx.snap, src/tests/unit/tests/common/components/cards/__snapshots__/instance-details-group.test.tsx.snap, src/tests/unit/tests/common/components/cards/__snapshots__/result-section-content.test.tsx.snap, src/tests/unit/tests/common/components/cards/__snapshots__/rule-resources.test.tsx.snap, src/tests/unit/tests/common/components/cards/__snapshots__/rules-with-instances.test.tsx.snap, src/tests/unit/tests/common/components/cards/rule-resources.test.tsx, src/tests/unit/tests/common/components/cards/sample-view-model-data.ts, src/tests/unit/tests/reports/components/report-sections/__snapshots__/report-body.test.tsx.snap
Update `RuleResource` component to handle no rule url and no rule guidance links scenarios (basically rendering null in those cases)
=> feat(android-cards-view): no rule resources support

src/common/components/cards/fix-instruction-color-box.scss, src/common/components/cards/how-to-fix-android-card-row.tsx, src/common/configs/unified-result-property-configurations.tsx, src/common/types/store-data/unified-data-interface.ts, src/electron/platform/android/fetch-scan-results.ts, src/electron/platform/android/rule-information-provider.ts, src/electron/platform/android/rule-information.ts, src/electron/platform/android/scan-results-to-unified-results.ts, src/electron/views/device-connect-view/device-connect-view.scss, src/tests/unit/tests/common/components/cards/__snapshots__/how-to-fix-android-card-row.test.tsx.snap, src/tests/unit/tests/common/components/cards/how-to-fix-android-card-row.test.tsx, src/tests/unit/tests/electron/platform/android/__snapshots__/rule-information-provider.test.ts.snap, src/tests/unit/tests/electron/platform/android/rule-information-provider.test.ts, src/tests/unit/tests/electron/platform/android/rule-information.test.ts, src/tests/unit/tests/electron/platform/android/scan-results-helpers.ts, src/tests/unit/tests/injected/__snapshots__/fix-instruction-processor.test.tsx.snap, src/tests/unit/tests/injected/fix-instruction-processor.test.tsx
Sample screenshot with dummy data
=> feat(android-cards-view): add how-to-fix CardRow for android 

src/electron/platform/android/rule-information-provider.ts, src/tests/unit/tests/electron/platform/android/__snapshots__/rule-information-provider.test.ts.snap
=> reducing height, width & color contrast to have precision to 3.

.github/pull_request_template.md, docs/workflow.md
- convert description text to a markdown comment, so as to not have this left over by mistake.
- add a line about tags in pr title.
=> chore: update PR template to add more meta information about a PR

src/views/page/page.scss
Previously, the content page's CSS was set up to treat the Accessibility Insights for Web header bar as a floating always-at-top element and to make the main region below the header be scrollable if content didn't fit on the page.
#1278 notes that, practically speaking, this would cause any content page with no focusable elements on it to not be keyboard-scrollable, which would fail the scrollable-region-focusable axe-core rule. We do not currently have any such content pages, but we want to preempt any issues in future content pages. You can see an approximation of the behavior we'd like to avoid today by opening the guidance link under the "color" ad-hoc toggle and trying to use the up and down arrows to scroll without first tabbing to the link on the page (up and down have no effect). …
=> fix(content-pages): preempt future scrollable-region-focusable issues by moving scroll region to body

.dependabot/config.yml
chore: add axe-core to ignored packages in dependabot config
=> chore: add axe-core to ignored packages in dependabot config

src/tests/unit/tests/common/components/cards/__snapshots__/card-kebab-menu-button.test.tsx.snap, src/tests/unit/tests/common/components/cards/card-kebab-menu-button.test.tsx
test: fix snapshot for a test changed in last PR by passing a string description to better differentiate snapshots in same `test.each` call.
=> test: fix snapshot for a test changed in last PR to be more distinguishable 

src/injected/visualization/element-highlight.tsx, src/injected/visualization/highlight-box.tsx, src/tests/unit/tests/injected/visualization/highlight-box.test.tsx
Just fixing some typos around highlight box component
=> chore: fix a typo on HighlightBox component

src/common/components/cards/instance-details-footer.tsx, src/common/components/cards/instance-details.tsx, src/tests/unit/tests/common/components/cards/__snapshots__/instance-details-footer.test.tsx.snap, src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap, src/tests/unit/tests/common/components/cards/instance-details.test.tsx
add null check to fix electron exception when creating kebab menuaria label
=> fix: card selection message dispatch and aria label based on cardInteractionSupport to fix electron

src/assessments/contrast/test-steps/state-changes.tsx
Update hot to test text according to #1558
=> fix: update Contrast > State changes > how to test text

src/electron/views/automated-checks/automated-checks-view.scss, src/electron/views/automated-checks/automated-checks-view.tsx, src/electron/views/screenshot/screenshot-view.tsx, src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap, src/tests/unit/tests/electron/views/screenshot/__snapshots__/screenshot-view.test.tsx.snap, src/tests/unit/tests/electron/views/screenshot/screenshot-view.test.tsx
**Things out of scope/intentionally not included in the PR:**
- Final CSS styling for the screenshotView, specifically related to resizing and scroll behavior. This will be addressed later in User Story #1628940 
Added a basic ScreenshotView component to the AutomatedChecksView. Updated the AutomatedChecksView test's screenshots to account for this new component. 
=> feat: Screenshot view

src/electron/views/automated-checks/automated-checks-view.scss
With this PR, scrolling capability is now enabled for the ScreenshotView; scrolling is independent of the rest of the AutomatedChecksView. Scrollbars only appear when necessary (e.g. when content is wider than the 30% of the screen that the view occupies)
**Note for these images, the CSS applied to force the scroll is not being checked into master. I just instituted a max-width and max-height to show that the scrollbars would show up as desired if the content required resizing**
Image of the width scrollbar being applied
Image of the height scrollbar being applied
Image of both the width and height scrollbar being applied
=> feat: added scroll capability to the ScreenshotView that applies for resizing

src/background/actions/card-selection-actions.ts, src/background/stores/card-selection-store.ts, src/common/types/store-data/card-selection-store-data.ts, src/tests/unit/tests/background/stores/card-selection-store.test.ts, src/tests/unit/tests/common/get-card-selection-view-data.test.ts
This change includes only the addition of the visualHelperEnabled data member and additions to the CardSelectionStoreActions interface. No logic is intended to change. This should make it easier for others to code to the expected, upcoming changes.
- CardSelectionStore.visualHelperEnabled will be used to indicate whether elements are highlighted in the target page.
- The new actions will be used to toggle the visual helper (highlighting) and to expand all rules.
=> Add actions and data for visual helper

pipeline/electron/product-build.yaml
This PR adds a minimal yaml build file that runs electron-builder. It is not being used yet and serves as a starting point to begin setting up build pipelines separate from the existing CI build. It intentionally omits other platforms for now.
=> chore: add new yaml build file

src/background/stores/card-selection-store.ts, src/tests/unit/tests/background/stores/card-selection-store.test.ts
- Add implementation of expandAllRules
- add stub for toggleVisualHelper
- Add tests for expandAllRules
- add empty test functions for upcoming work
=> Feat: Add new CardSelectionStore actions

src/background/stores/card-selection-store.ts, src/tests/unit/tests/background/stores/card-selection-store.test.ts
Intended effects:
- When visual helper is toggled on
- visual helper is enabled
- nothing else changes
- When visual helper is toggled off
- all selected cards are deselected
- all deselected cards remain deselected
- no rule expansion changes occur
- visual helper is disabled
- When a card is selected and visual helper is disabled
- the given card is selected
- visual helper becomes enabled
=> feat(consistent-cards-UI): Add CardSelectionStore.toggleVisualHelper implementation

.dependabot/config.yml
Our `electron` dependency is based on the update frequency from internal electron build and so it doesn't make sense for dependabot to spam us on update from electron.
Adding `electron` to the ignored list.
=> chore: add electron to dependabot ignore

src/electron/views/device-connect-view/device-connect-view.scss
Noticed a small problem with our electron app. The background color of our app was getting hijacked by the dev tools settings i.e. if the chrome dev tools was set to be in dark mode, the app became dark whenever we toggled dev tools.  Putting a background color `$neutral-0` on the `body` fixed this.
Check out the gif for more details.
**before**
**after**
=> fix: background color of electron app toggle with dev tools theme

src/common/extension-telemetry-events.ts, src/electron/views/renderer-initializer.ts
Fixes build break in master caused by silent merge conflict between PRs #1643 and #1645 that merged in simultaneously
=> fix: prevent build error in electron caused by silent merge conflict around new CardSelectionMessageCreator params

electron-builder.yml
This PR updates the name in our installer to something more appropriate than 'ai-mobile'.
=> feat(releases): better installer name

targets.config.js
Update telemetry name for ai-android.
=> chore: update telemetry name for electron build

package.json, pipeline/electron/distribute-sign-publish-electron-mac.yaml, pipeline/electron/distribute-sign-publish-electron-windows.yaml
chore: instead of `dist:electron` run `pack:electron` command to make sure grunt config is not overrider. Removing `dist:electron` from our scripts to avoid future problems like these.
=> fix: update electron dist:electron to pack:electron

src/common/rule-based-view-model-provider.ts, src/tests/unit/common/__snapshots__/rule-based-view-model-provider.test.ts.snap
This should complete the work to propigate data from the store to the view model.
=> feat(consistent-cards-UI): hook up card selection store data to cards view model for visual helper and allCardsCollapsed

src/background/actions/action-creator.ts, src/background/actions/action-payloads.ts, src/common/extension-telemetry-events.ts, src/common/messages.ts, src/tests/unit/tests/background/actions/action-creator.test.ts
Rescan should be it's own action message. This is the first part of that: handling a message that would be received by the action creator.
- [] Ran `yarn fastpass`
=> feat(consistent-cards-ui): created a rescan action message handler

src/electron/views/automated-checks/automated-checks-view.scss
Instituted a minimum width of the cards panel for the automated checks view. The minimum width is 321 px, per Chelsea's mock. 
Image of the extension minimized so the minimum width requirement is enforced:
=> feat(and-screenshot): added min width for the automated checks panel for the cards

src/electron/views/screenshot/screenshot-view.scss
- Updated screenshot view heading ("Target app screenshot") style to match result section heading ("Failed instances") style to match the Figma mock for `h2`s. The most noticeable differences are font-size and line-height.
Before:
After:
=> feat(and-screenshot): update screenshot view heading style

src/background/details-view-controller.ts, src/tests/unit/tests/background/details-view-controller.test.ts
Minor improvements including:
- direct use of `endsWith` (instead of custom function)
- fix typos
- improve name on mock setup code.
=> refactor: details view controller improvements

src/background/tab-controller.ts, src/tests/unit/tests/background/tab-controller.test.ts
- fix typos
- use mock directly (instead of wrapping it on a stub)
- remove minor duplication
-use parameter properties
- normalize imports
=> refactor: tab controller minor improvements

prettier.config.js, src/popup/actions/popup-action-message-creator.ts, src/popup/components/ad-hoc-tools-panel.tsx, src/popup/components/diagnostic-view-toggle-factory.tsx, src/popup/components/diagnostic-view-toggle.tsx, src/popup/components/file-url-unsupported-message-panel.tsx, src/popup/components/header-contextual-menu.tsx, src/popup/components/header.tsx, src/popup/components/launch-pad-item-row.tsx, src/popup/components/launch-pad.tsx, src/popup/components/launch-panel-header.tsx, src/popup/components/popup-view.tsx, src/popup/handlers/diagnostic-view-toggle-click-handler.ts, src/popup/handlers/launch-panel-header-click-handler.ts, src/popup/handlers/popup-view-controller-handler.ts, src/popup/incompatible-browser-renderer.tsx, src/popup/launch-pad-row-configuration-factory.ts, src/popup/main-renderer.tsx, src/popup/popup-init.ts, src/popup/popup-initializer.ts, src/popup/popup.html, src/popup/support-link-handler.ts, src/popup/target-tab-finder.ts, src/tests/unit/tests/popup/__snapshots__/incompatible-browser-renderer.test.tsx.snap
Change line width to 80 for `src/popup` folder.
=> chore: change line width to 80 for src/popup

src/common/feature-flags.ts, src/tests/unit/tests/background/feature-flags.test.ts
This enables the cards UI by default.
=> feat(consistent-cards-ui): enable cards UI feature flag

Dockerfile
Update cypress docker base to 12.13.0 to fix broken e2e on linux. I missed this file in my last PR #1715
=> chore: update cypress docker base to 12.13.0 to fix broken e2e on linux

prettier.config.js, src/popup/actions/popup-action-message-creator.ts, src/popup/components/ad-hoc-tools-panel.tsx, src/popup/components/diagnostic-view-toggle-factory.tsx, src/popup/components/diagnostic-view-toggle.tsx, src/popup/components/file-url-unsupported-message-panel.tsx, src/popup/components/header-contextual-menu.tsx, src/popup/components/launch-pad-item-row.tsx, src/popup/components/launch-pad.tsx, src/popup/components/launch-panel-header.tsx, src/popup/components/popup-view.tsx, src/popup/handlers/diagnostic-view-toggle-click-handler.ts, src/popup/handlers/launch-panel-header-click-handler.ts, src/popup/handlers/popup-view-controller-handler.ts, src/popup/launch-pad-row-configuration-factory.ts, src/popup/main-renderer.tsx, src/popup/popup-init.ts, src/popup/popup-initializer.ts, src/popup/popup.html, src/popup/support-link-handler.ts, src/popup/target-tab-finder.ts
chore: update line width in `src/popup` to 100 from 80. This was the first iteration and 80 was rejected in favor of 100, so moving the popup folder to 100 as well.
=> chore: update line width in `src/popup` to 100

prettier.config.js, src/ad-hoc-visualizations/color/visualization.tsx, src/ad-hoc-visualizations/headings/visualization.tsx, src/ad-hoc-visualizations/issues/visualization.tsx, src/ad-hoc-visualizations/landmarks/visualization.tsx, src/ad-hoc-visualizations/tab-stops/visualization.tsx
Updating `src/adhoc-visualizations` folder with formatting changes (line-width: 100).
=> chore: change line width in adhoc-visualizations folder to 100

pipeline/build-package-report.yaml
=> feat(report-package) Created yaml for npm package pipeline

src/reports/package/root/README.md
=> feat(report-package) Added README for report package

src/reports/package/root/package.json
Increment version of accessibility-insights-report for releasing README changes.
=> feat(report-package) Update accessibility-insights-report to 0.0.2

src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap, src/tests/unit/tests/reports/package/integration.test.ts
=> feat(report-package) No code change. Just formatted the snapshot.

src/reports/package/root/package.json
Update npm version of accessibility-insights-report to 0.1.0.
This is a breaking change to the new package.
* Removing `browserVersion` and adding `serviceName` for new report footer text.
=> feat(report-package): Update -report to 0.1.0 (breaking change)

.github/ISSUE_TEMPLATE/bug_report.md
Improving the **Extension** section using better names for each of the fields in there.
This comes as a result of seen issues being created with inaccurate information (**version** being the os version when the intention is for this to hold AI-Web version).
=> docs: improve issues template

src/DetailsView/components/assessment-visualization-enabled-toggle.tsx, src/DetailsView/components/base-visual-helper-toggle.tsx, src/assessments/assessment-builder.tsx, src/assessments/assessments-feature-flag-filter.ts, src/background/assessment-data-converter.ts, src/background/assessment-data-remover.ts, src/background/completed-test-step-telemetry-creator.ts, src/background/stores/visualization-scan-result-store.ts, src/background/telemetry/telemetry-event-handler.ts, src/common/configs/visualization-configuration-factory.ts, src/common/feature-flags.ts, src/common/store-proxy.ts, src/common/stores/base-client-stores-hub.ts, src/injected/selector-map-helper.ts, src/injected/visualization/svg-drawer.ts, src/injected/visualization/svg-solid-shadow-filter-factory.ts, src/reports/assessment-report-model-builder.ts, src/reports/components/formatted-date.tsx, src/tests/unit/common/typemoq-helper.ts, src/tests/unit/common/visualization-store-data-builder.ts, src/tests/unit/tests/DetailsView/components/assessment-visualization-enabled-toggle.test.tsx, src/tests/unit/tests/assessments/assessment-builder.test.tsx, src/tests/unit/tests/assessments/assessments-provider.test.ts, src/tests/unit/tests/background/stores/assessment-store.test.ts, src/tests/unit/tests/background/stores/visualization-store.test.ts, src/tests/unit/tests/background/telemetry/app-insights-telemetry-client.test.ts, src/tests/unit/tests/background/telemetry/telemetry-event-handler.test.ts, src/tests/unit/tests/common/configs/visualization-configuration-factory.test.ts, src/tests/unit/tests/injected/visualization/svg-solid-shadow-filter-factory.test.ts, src/tests/unit/tests/reports/components/inline-image.test.tsx
Update all usages of `import * as _ from 'lodash'` to explicitly import what we are actually using from lodash. This should impact the bundle size in a positive way as the former style ends up including all of `lodash` code, while the latter helps webpack with the tree shaking. I do not have numbers for this though.
=> refactor: update all lodash imports

src/common/browser-adapters/browser-adapter.ts, src/common/browser-adapters/chrome-adapter.ts
This was part of the permissions feature but we end up not using it.
=> refactor: remove requestPermissions

src/background/actions/assessment-actions.ts, src/background/actions/card-selection-actions.ts, src/background/actions/command-actions.ts, src/background/actions/content-actions.ts, src/background/actions/details-view-actions.ts, src/background/actions/dev-tools-actions.ts, src/background/actions/feature-flag-actions.ts, src/background/actions/inspect-actions.ts, src/background/actions/launch-panel-state-action.ts, src/background/actions/path-snippet-actions.ts, src/background/actions/preview-features-actions.ts, src/background/actions/scoping-actions.ts, src/background/actions/tab-actions.ts, src/background/actions/unified-scan-result-actions.ts, src/background/actions/user-configuration-actions.ts, src/background/actions/visualization-scan-result-actions.ts, src/tests/unit/common/store-tester.ts, src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts, src/tests/unit/tests/common/flux/action.test.ts
Normalize all imports from `common/flux/action` to be:
```typescript
import { Action } from 'common/flux/action';
```
=> refactor: normalize imports from common/flux/action

src/electron/main/main.ts, src/electron/views/index.html, src/tests/electron/tests/device-connection-dialog.test.ts
Just adding some more event handlers on window closing and trying to make sure that app quits completely. Also dereferencing `mainWindow` for better window management.
=> chore: better memory management with electron app

src/DetailsView/components/details-view-switcher-nav.ts, src/background/stores/visualization-store.ts, src/common/types/details-view-pivot-type.ts, src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts, src/tests/unit/tests/DetailsView/components/details-view-right-panel.test.tsx, src/tests/unit/tests/DetailsView/components/tab-info.test.tsx, src/tests/unit/tests/background/actions/action-creator.test.ts, src/tests/unit/tests/background/stores/assessment-store.test.ts, src/tests/unit/tests/background/stores/visualization-store.test.ts
`allTest` was associated with a view (on the details view) where we use to show info about each of the visualization we actually have on the ad hoc tools (so, automated checks, headings, landmarks, color and tab stops) but it got "remove" in favor of having just fast pass and assessment. Yet, the enum value persist on our code along side some small pieces of code to handle the value. Since we don't show that view on the details view anymore, it does not make sense to even have the enum value neither.
In this PR I removed all references to `allTest`, update a couple of pieces of logic for handling that value and update all the test to not reference it (I end up using either `fastPass` or `assessments` depending on the context)
=> refactor: remove allTests from DetailsViewPivotType enum

deploy/Gruntfile.js, electron-builder.yml, package.json
This PR introduces a `update-electron-config` grunt task and makes some minor configuration changes to electron-builder related to the task. The task's purpose is to set the electron product's version number and update URL prior to publishing. It will primarily be used in a build or release pipeline. 
=> feat(electron-update): electron publishing script + config update

prettier.config.js, src/DetailsView/components/details-view-right-panel.ts, src/DetailsView/components/details-view-switcher-nav.ts, src/DetailsView/components/left-nav/details-view-left-nav.tsx, src/DetailsView/components/test-status-choice-group.tsx, src/DetailsView/handlers/master-checkbox-config-provider.ts, src/scanner/axe-configurator.ts, src/scanner/axe-utils.ts, src/scanner/check-message-transformer.ts, src/scanner/custom-rules/css-content-rule.ts, src/scanner/custom-rules/css-positioning-rule.ts, src/scanner/custom-rules/cues-rule.ts, src/scanner/custom-rules/link-function.ts, src/scanner/custom-rules/link-purpose.ts, src/scanner/custom-rules/native-widgets-default.ts, src/scanner/custom-rules/text-contrast.ts, src/scanner/custom-rules/unique-landmark.ts, src/scanner/custom-rules/widget-function.ts, src/scanner/exposed-apis.ts, src/scanner/launcher.ts, src/scanner/message-decorator.ts, src/scanner/processor.ts, src/scanner/result-decorator.ts, src/scanner/role-utils.ts, src/scanner/rule-sifter.ts, src/tests/electron/jest.config.js
Update files under `src/types` and `src/scanner` to have new line width prettier setting. (moving from 140 to 100).
=> chore: update folders src/types and src/scanner for new line width

pipeline/electron/electron-update-config.yaml
A recent pr (#1805) added the `update-electron-config` grunt task. This PR puts it to use in the electron build pipeline.
=> feat(electron-update): Use update-electron-config task in electron build

src/tests/end-to-end/tests/target-page/tabstop.test.ts
Minor refactor to move repeated code into a function in our `tabstop.test.ts` end-to-end.
=> refactor: move repeated code in tabstop e2e to a new function

src/common/browser-adapters/browser-adapter.ts, src/common/browser-adapters/chrome-adapter.ts
Fairly self-explanatory: needed for the new design of the permissions UX.
=> feat(permissions): updated browser/chrome adapter for permissions related functionality

src/DetailsView/components/start-over-component-factory.tsx, src/common/components/cards/result-section.tsx, src/common/components/cards/rules-with-instances.tsx, src/tests/electron/setup/global-teardown.ts, src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts, src/tests/end-to-end/setup/global-teardown.ts, src/tests/end-to-end/test-resources/all-cross-origin-iframe.html, src/tests/end-to-end/tests/details-view/__snapshots__/cross-origin-iframe.test.ts.snap, src/tests/end-to-end/tests/details-view/cross-origin-iframe.test.ts, src/tests/miscellaneous/test-resource-server/resource-server.ts, src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-component-factory.test.tsx.snap, src/tests/unit/tests/common/components/cards/__snapshots__/result-section.test.tsx.snap, src/tests/unit/tests/common/components/cards/__snapshots__/rules-with-instances.test.tsx.snap, src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap
Adding e2e test to check we don't get results from scanning cross-origin iframe.
In order to do so, we need to spin two different local servers (the port being different make this localhost to be consider "cross-origin) and have a html page that links to a different localhost.
=> test: add e2e cross-origin iframe with no permissions test

src/injected/analyzers/analyzer-provider.ts, src/injected/analyzers/analyzer.ts, src/injected/analyzers/base-analyzer.ts, src/injected/analyzers/batched-rule-analyzer.ts, src/injected/analyzers/rule-analyzer.ts, src/injected/analyzers/tab-stops-analyzer.ts, src/injected/iframe-detector.ts, src/injected/main-window-initializer.ts, src/tests/unit/tests/background/actions/action-creator.test.ts, src/tests/unit/tests/background/stores/assessment-store.test.ts, src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts, src/tests/unit/tests/injected/analyzers/base-analyzer.test.ts, src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts, src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts, src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts, src/tests/unit/tests/injected/iframe-detector.test.ts
Adds detection of iframe to the analyzers and the messages they send when scans are completed.
=> feat(permissions): added iframe detection to scan completed messages

src/background/actions/global-action-hub.ts, src/background/actions/permissions-state-actions.ts, src/background/stores/global/global-store-hub.ts, src/background/stores/global/permissions-state-store.ts, src/common/stores/store-names.ts, src/common/types/store-data/permissions-state-store-data.ts, src/tests/unit/tests/background/actions/global-action-hub.test.ts, src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts, src/tests/unit/tests/background/stores/global/__snapshots__/permissions-state-store.test.ts.snap, src/tests/unit/tests/background/stores/global/global-store-hub.test.ts, src/tests/unit/tests/background/stores/global/permissions-state-store.test.ts
Created global PermissionsStateStore to store the extension permissions state -- a boolean for whether or not the user has granted permissions for all urls and all files (`*://*`)
=> feat(permissions): PermissionsStateStore for all url and file permissions

src/background/global-action-creators/permissions-state-action-creator.ts, src/background/global-context-factory.ts, src/common/messages.ts, src/tests/unit/tests/background/global-action-creators/permissions-state-action-creator.test.ts
Adds a PermissionsStateActionCreator and wires it up to the background page's actions
=> feat(permissions): Implement and wire up permissions state action creator

src/DetailsView/actions/details-view-action-message-creator.ts, src/DetailsView/handlers/allurls-permission-handler.ts, src/background/actions/action-payloads.ts, src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts, src/tests/unit/tests/DetailsView/components/__snapshots__/preview-features-container.test.tsx.snap, src/tests/unit/tests/DetailsView/components/preview-features-container.test.tsx, src/tests/unit/tests/DetailsView/handlers/allurls-permission-handler.test.ts
Introduces a class that will invoke the request for all url permissions.
=> feat(permissions): introduce all urls permission handler

src/DetailsView/components/iframe-warning.tsx, src/background/browser-permissions-tracker.ts, src/tests/end-to-end/common/browser-factory.ts, src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts, src/tests/end-to-end/tests/details-view/cross-origin-iframe.test.ts, src/tests/unit/tests/DetailsView/components/__snapshots__/iframe-warning.test.tsx.snap
Add end to end test to check for the presence/absence of the iframe detected warning banner.
=> test: e2e iframe warning banner

src/assessments/errors/test-steps/status-messages.tsx
Changed the description of Status messages because it was incorrect.
Old
New
- [NA] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [NA] (UI changes only) Verified usability with NVDA/JAWS
=> Fix: description in Status Messages

src/popup/components/ad-hoc-tools-panel.tsx, src/popup/components/diagnostic-view-toggle-factory.tsx, src/tests/unit/tests/popup/components/ad-hoc-tools-panel.test.tsx, src/tests/unit/tests/popup/components/diagnostic-view-toggle-factory.test.tsx
- Remove dead code
- Update import paths
=> refactor: minor clean up

prettier.config.js, src/Devtools/dev-tool-initializer.ts, src/Devtools/inspect-handler.ts, src/issue-filing/common/create-issue-details-builder.ts, src/issue-filing/common/issue-details-builder.ts, src/issue-filing/common/issue-filing-controller-impl.ts, src/issue-filing/common/issue-filing-url-string-utils.ts, src/issue-filing/components/issue-filing-choice-group.tsx, src/issue-filing/components/issue-filing-settings-container.tsx, src/issue-filing/rule-result-to-issue-filing-data.ts, src/issue-filing/services/azure-boards/azure-boards-issue-filing-service.tsx, src/issue-filing/services/azure-boards/azure-boards-settings-form.tsx, src/issue-filing/services/azure-boards/create-azure-boards-issue-filing-url.ts, src/issue-filing/services/github/create-github-issue-filing-url.ts, src/issue-filing/services/github/github-issue-filing-service.tsx, src/issue-filing/unified-result-to-issue-filing-data.ts
This PR changes the files under `src/Devtools` & `src/issue-filing` to comply with our new prettier config of 100 line width.
=> chore: change line width on Devtools and issue-filing

prettier.config.js, src/views/content/content-include.tsx, src/views/content/content-link.tsx, src/views/content/content-page.tsx, src/views/content/content-panel-button.tsx, src/views/content/content-panel.tsx, src/views/content/markup.tsx, src/views/content/markup/code-example.tsx, src/views/insights/dependencies.ts, src/views/insights/initializer.ts, src/views/insights/router.tsx
This PR changes the files under `src/views` to comply with our new prettier config of 100 line width.
=> chore: update line width for folder scr/views

package.json, src/common/components/cards/card-kebab-menu-button.scss, src/common/styles/default-theme-palette.ts, src/electron/views/automated-checks/components/command-bar.tsx, src/injected/styles/injected.scss, src/reports/package/root/package.json, src/tests/end-to-end/tests/common/__snapshots__/settings-drop-down.test.ts.snap, src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap, src/tests/end-to-end/tests/popup/__snapshots__/first-time-dialog.test.ts.snap, src/tests/end-to-end/tests/popup/__snapshots__/hamburger-menu.test.ts.snap, src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap, src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/command-bar.test.tsx.snap, yarn.lock
This PR is to update office fabric to version 7 and to fix any issues we may encounter after the update.
This PR also:
- fixes #777 
- fixes #1758
**NOTE** this PR is just a re-brand of an older PR (#1924). I had to create a new PR because the build on the old one got stock (never getting status back from ADO)
=> feat(office-fabric): update to office fabric 7

src/DetailsView/Styles/detailsview.scss, src/DetailsView/components/generic-panel.scss, src/DetailsView/components/generic-panel.tsx, src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/generic-panel.test.tsx.snap, src/tests/unit/tests/DetailsView/components/generic-panel.test.tsx
Update margins on the panel (through updating the `GenericPanel` component) to make the styles (specially the margins/paddings) match the ones we have before.
=> feat(office-fabric): udpate panel margins

src/reports/package/root/package.json
Bumping up the report package version from 0.1.0 to 1.0.0, before consuming in the samples repo.
=> chore: upgrading to report package to 1.0.0

prettier.config.js, src/common/components/collapsible-component.tsx, src/common/components/contrast-checker-app-links.tsx, src/common/components/copy-issue-details-button.tsx, src/common/components/external-link.tsx, src/common/components/fix-instruction-panel.tsx, src/common/components/fix-instruction-processor.tsx, src/common/components/header-icon.tsx, src/common/components/issue-filing-button.tsx, src/common/components/privacy-statement-text.tsx, src/common/components/selector-input-list.tsx, src/common/components/telemetry-notice.tsx, src/common/components/telemetry-permission-dialog.tsx, src/common/components/theme.tsx, src/common/components/toast.tsx, src/tests/end-to-end/tests/popup/__snapshots__/first-time-dialog.test.ts.snap, src/tests/unit/tests/common/components/__snapshots__/privacy-statement-text.test.tsx.snap
This PR changes files under folder `src/common/components/` to comply with our new prettier config of 100 line width.
=> chore: update line width for folder src/common/components

README.md
Since Microsoft Edge is officially released now, it makes sense for us to remove `Insider` from our Readme and to be specific that we are talking about the new Edge, added `(Chromium)` in the Readme.
=> chore: update readme to remove insider from Microsoft Edge and add (Chromium)

src/assessments/page/test-steps/general-navigation.tsx
Fixes #2037 
**Notes** this is a html structure change only, there is no visual change. The new list passes A11Y self-validation.
=> fix: list structure is incorrect

pipeline/unified/build-unsigned-release-packages.yaml, pipeline/unified/sign-release-packages-canary.yaml, pipeline/unified/sign-release-packages-insider-production.yaml
Updates the new unified release pipelines with pipeline dependencies based on the names as they appear in Azure DevOps
=> feat(unified-channels): Update new build triggers to match definition names in devops

src/background/stores/details-view-store.ts, src/tests/unit/tests/background/stores/details-view-store.test.ts
Doing some exploration for an upcoming feature, I found a couple of places with a type-less param.
This PR add the missing types and also update import paths.
=> clean-up: add missing type

pipeline/unified/unified-e2e-reliability.yaml
Moved the renamed file out of the electron folder and into the unified folder. 
=> feat(unified-channels): renamed electron-e2e-reliability to have unified-e2e-reliability

prettier.config.js, src/tests/unit/common/assessment-store-data-builder.ts, src/tests/unit/common/assessment-store-tester.ts, src/tests/unit/common/details-view-store-data-builder.ts, src/tests/unit/common/element-snapshot-formatter.test.ts, src/tests/unit/common/environment-info-provider.test.ts, src/tests/unit/common/rule-based-view-model-provider.test.ts, src/tests/unit/common/sample-test-data.ts, src/tests/unit/common/simulated-browser-adapter.ts, src/tests/unit/common/store-tester.ts, src/tests/unit/common/test-assessment-provider.tsx, src/tests/unit/common/visual-helper-toggle-config-builder.ts, src/tests/unit/common/visualization-scan-result-store-data-builder.ts, src/tests/unit/common/visualization-store-data-builder.ts
This PR changes files under `src/tests/unit/common` to comply with our new prettier config of 100 line width.
=> chore: line width for src/tests/unit/common folder

pipeline/scripts/update-electron-checksum.js
Before #2126, all of the `latest.yml` files we produced contained only a single file, so it was okay for our checksum-updating script to assume it only had to update `files[0]`. Now that we have a case where multiple files can be present, this PR makes that update script a little smarter about updating checksums on a per-file basis. 
Verified locally against a single- and multi- file latest.yml
=> fix: unified/mac: support signed build checksums for latest.yml with multiple files

src/DetailsView/Styles/detailsview.scss, src/DetailsView/components/preview-features-toggle-list.scss, src/DetailsView/components/preview-features-toggle-list.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/preview-features-toggle-list.test.tsx.snap, src/tests/unit/tests/DetailsView/components/preview-features-toggle-list.test.tsx
- normalize imports
- convert component to NamedFC
- use css module
- clean up tests
=> refactor: PreviewFeaturesToggleList to use css module

src/DetailsView/details-view-initializer.ts, src/common/components/header.tsx, src/tests/unit/tests/common/components/__snapshots__/header.test.tsx.snap, src/tests/unit/tests/common/components/header.test.tsx, src/views/insights/dependencies.ts
In preparation for sharing some key UI elements with the documentation, removed the hard dependency on the constant for `applicationTitle` in favor of a `deps` property
=> feat(docs): Added applicationTitle to deps for Header

src/common/components/header-icon.tsx
=> fix: remove console.log

Gruntfile.js, package.json, pipeline/build-package-report.yaml, pipeline/build-package-ui.yaml, pipeline/build-package.template.yaml, src/packages/accessibility-insights-ui/index.ts, src/packages/accessibility-insights-ui/root/README.md, src/packages/accessibility-insights-ui/root/package.json, src/packages/accessibility-insights-ui/ui-factory.tsx, src/packages/accessibility-insights-ui/ui.scss, src/tests/unit/tests/packages/accessibility-insights-ui/__snapshots__/ui-factory.test.tsx.snap, src/tests/unit/tests/packages/accessibility-insights-ui/index.test.ts, src/tests/unit/tests/packages/accessibility-insights-ui/ui-factory.test.tsx, src/views/content/markup.tsx, webpack.config.js
We require some components from the web repo to be shared with the docs repo. To facilitate this, this PR creates a package called `accessibility-insights-ui`. This shares a small number of key objects required by the docs repo and also a bundle of css for rendering these items properly.
=> feat(docs): Created accessibility-insights-ui package

pipeline/build-package.template.yaml
=> feat(docs): typo in yaml file

src/electron/views/device-connect-view/components/device-connect-connected-device.scss
**currently, small font size and color contrast issue**
**on this PR, size and color updated**
=> feat(android-settings): update spinner label style

src/packages/accessibility-insights-ui/root/package.json, src/packages/accessibility-insights-ui/ui.scss
I missed the outcome styles in the first update. It is causing a few very minor, but noticeable layout anomalies. This will fix them. 
=> feat(docs) Updated UI package CSS bundle to include missing styles

README.md
We just added support for runing code-cov bot on our PRs and CI builds so it makes sense to update our code coverage badge from Azure Dev Ops to codecov.
=> docs: update code coverage badge

src/reports/package/root/package.json
Updating report package version to release
=> chore: updating report package version

prettier.config.js, src/icons/brand/blue/brand-blue.tsx, src/icons/brand/white/brand-white.tsx
Just updating `prettier.config.js` and running `yarn format:fix`
=> chore: line width 100 for /src/icons/

src/common/components/gear-menu-button.scss
Added boxes to highlight the settings (aka 'gear') icon in the details view. This provides proper contrast.
**Regular Color Scheme**
Before: 
After: 
**High Contrast Color Scheme**
Before: 
After: 
=> feat(compliance-contrast): fixing background contrast around settings icon in details view 

src/tests/unit/tests/common/message-creators/user-config-message-creator.test.ts
Just `yarn format:fix` from master
=> chore: fix build break in master (silent merge conflict with prettier setting change)

src/reports/package/root/package.json
Updates the report package version to setup release.
=> feat(update-axe-core): update report version to 1.0.2

LICENSE
As per discussions offline, we do not need this line.
=> fix: license does not need to mention accessibility insights for web

src/DetailsView/details-view-renderer.tsx, src/tests/unit/tests/DetailsView/details-view-renderer.test.tsx
Make all `DetailsViewRenderer` constructor params to be 'private readonly' to avoid boilerplate code.
Update test imports.
=> refactor: details view renderer clean up

src/debug-tools/controllers/debug-tools-controller.ts, src/tests/unit/tests/debug-tools/controllers/debug-tools-controller.test.ts
Adding missing test for debug tools controller
=> test: add missing test for debug tools controller

src/DetailsView/Styles/detailsview.scss, src/DetailsView/components/assessment-view.scss, src/DetailsView/components/assessment-view.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-view.test.tsx.snap
Styles remain unchanged, as seen below.
Before:
After:
=> refactor: assessment view css

src/DetailsView/Styles/detailsview.scss, src/DetailsView/components/assessment-command-bar.tsx, src/DetailsView/components/automated-checks-command-bar.tsx, src/DetailsView/components/details-view-command-bar.scss, src/DetailsView/components/details-view-command-bar.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap
Removes some css as well that is no longer valid.
=> refactor: details view command bar css clean up

README.md
We don't list the canary / insider links anywhere yet. This PR includes them. See what it looks like [here](https://github.com/microsoft/accessibility-insights-web/blob/65ce5f4631a85ed859d50c4a030d57111b423703/README.md).
=> chore: update readme to include Accessibility Insights for Android canary/insider links

build.yaml
Following suggestions from **Issue with YAML pipeline triggers** incident, adding explicit triggers for both, CI and PR builds.
=> chore: add explicit trigger for ci and pr builds

prettier.config.js, src/tests/unit/tests/injected/adapters/scan-results-to-unified-results.test.ts, src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts, src/tests/unit/tests/injected/analyzers/base-analyzer.test.ts, src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts, src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts, src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts, src/tests/unit/tests/injected/analyzers/unified-result-sender.test.ts, src/tests/unit/tests/injected/components/command-bar.test.tsx, src/tests/unit/tests/injected/components/details-dialog.test.tsx, src/tests/unit/tests/injected/components/fix-instruction-panel.test.tsx, src/tests/unit/tests/injected/components/issue-details-navigation-controls.test.tsx, src/tests/unit/tests/injected/frameCommunicators/frame-communicator.test.ts, src/tests/unit/tests/injected/frameCommunicators/html-element-axe-results-helper.test.ts, src/tests/unit/tests/injected/frameCommunicators/window-message-handler.test.ts, src/tests/unit/tests/injected/frameCommunicators/window-message-marshaller.test.ts, src/tests/unit/tests/injected/visualization/drawer.test.ts, src/tests/unit/tests/injected/visualization/heading-formatter.test.ts
Remove all but one subfolders under tests/injected folder and then run `yarn format:fix`.
=> chore: line width for injected tests folder

src/reports/components/report-sections/footer-text.tsx, src/tests/unit/tests/reports/components/report-sections/__snapshots__/footer-text.test.tsx.snap, src/tests/unit/tests/reports/components/report-sections/footer-text.test.tsx
Noticed this in the last validation; minor change.
=> fix: 'Axe' to 'axe-core' in report footer

src/DetailsView/Styles/detailsview.scss, src/DetailsView/components/static-content-common.scss, src/DetailsView/components/static-content-details-view.tsx, src/DetailsView/components/target-page-changed-view.scss, src/DetailsView/components/target-page-changed-view.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/static-content-details-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-changed-view.test.tsx.snap
Just moving some css to smaller modules.
- [--] Addresses an existing issue: #0000
- [--] (UI changes only) Added screenshots/GIFs to description above
- [--] (UI changes only) Verified usability with NVDA/JAWS
=> refactor: clean up target page changed css

prettier.config.js, src/tests/unit/tests/injected/visualization/center-position-calculator.test.ts, src/tests/unit/tests/injected/visualization/drawer-utils-mock-builder.ts, src/tests/unit/tests/injected/visualization/drawer-utils.test.ts, src/tests/unit/tests/injected/visualization/drawer.test.ts, src/tests/unit/tests/injected/visualization/element-highlight.test.tsx, src/tests/unit/tests/injected/visualization/heading-formatter.test.ts, src/tests/unit/tests/injected/visualization/highlight-box.test.tsx, src/tests/unit/tests/injected/visualization/highlight-visualization.test.tsx, src/tests/unit/tests/injected/visualization/landmark-formatter.test.ts, src/tests/unit/tests/injected/visualization/non-text-component-formatter.test.ts, src/tests/unit/tests/injected/visualization/svg-drawer.test.ts, src/tests/unit/tests/injected/visualization/svg-shape-factory.test.ts, src/tests/unit/tests/injected/visualization/svg-solid-shadow-filter-factory.test.ts, src/tests/unit/tests/injected/visualization/tab-stops-formatter.test.ts
Remove `tests/injected/visualization` folder and then run `yarn format:fix`.
=> chore: line width for injected/visualization tests folder

package.json, yarn.lock
Update acorn to 7.1.1 and minimist to 1.2.2 to fix github security alerts.
=> chore: update acorn and minimist

prettier.config.js, src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts, src/tests/unit/tests/DetailsView/actions/issues-selection-factory.test.ts, src/tests/unit/tests/DetailsView/assessment-report-builder-test-helper.ts, src/tests/unit/tests/DetailsView/assessment-report-model-builder.test.tsx, src/tests/unit/tests/DetailsView/details-view-body.test.tsx, src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts, src/tests/unit/tests/DetailsView/details-view-container.test.tsx, src/tests/unit/tests/DetailsView/details-view-renderer.test.tsx, src/tests/unit/tests/DetailsView/document-title-updater.test.ts, src/tests/unit/tests/DetailsView/extensions/exclude-passing-instances-from-assessment-report.test.ts, src/tests/unit/tests/DetailsView/extensions/select-first-requirement-after-automated-checks.test.ts, src/tests/unit/tests/DetailsView/handlers/allurls-permission-handler.test.ts, src/tests/unit/tests/DetailsView/handlers/assessment-instance-table-handler.test.tsx, src/tests/unit/tests/DetailsView/handlers/details-view-toggle-click-handler-factory.test.ts, src/tests/unit/tests/DetailsView/handlers/get-document-title.test.ts, src/tests/unit/tests/DetailsView/handlers/master-check-box-config-handler.test.ts, src/tests/unit/tests/DetailsView/handlers/nav-link-handler.test.ts, src/tests/unit/tests/DetailsView/no-content-available-view-renderer.test.tsx, src/tests/unit/tests/DetailsView/store-mocks.ts
Update prettier config to reformat all but one subfolder under `src/tests/unit/tests/DetailsView`. Then, run `yarn format:fix`
=> chore: line width for src/tests/unit/tests/DetailsView

src/popup/components/popup-view.tsx
The original code worked just fine but it reads a little odd (specially for the `.pop()` call after the `reduce` code.
This is an attempt to make the code a little easier to read and remove the need for the comment.
=> feat(threat-model): improve how we process urlNotScannable message array

src/reports/components/report-sections/collapsible-script-provider.tsx, src/tests/unit/tests/reports/components/report-sections/__snapshots__/collapsible-script-provider.test.ts.snap, src/tests/unit/tests/reports/components/report-sections/collapsible-script-provider.test.ts
In #2399, code coverage was excluded for `addEventListenerForCollapsibleSection` in `collapsible-script-provider.tsx`. It was previously injecting code coverage functions that didn't work well with snapshot text representation. Since this is no longer an issue, `getDefaultAddListenerForCollapsibleSection` can be tested. This PR adds a snapshot test for `getDefaultAddListenerForCollapsibleSection`.
=> test: add snapshot test for getDefaultAddListenerForCollapsibleSection

src/background/actions/details-view-action-creator.ts
Currently, our `DetailsViewActionCreator` contains an specific function to open the settings panel. In order to facilitate future refactors to change how we open/close the other settings panels (PreviewFeatures, Issue Filing, etc), it would be nice to have a more generic way to open a side panel, thus, minimizing the amount of changes we need to make to "onboard" the other side panels.
=> refactor(side-panel): add generic onOpenSidePanel

src/background/stores/global/feature-flag-store.ts, src/background/stores/global/global-store-hub.ts, src/common/feature-flag-defaults-helper.ts, src/common/feature-flags.ts, src/electron/common/unified-feature-flags.ts, src/tests/unit/tests/DetailsView/details-view-body.test.tsx, src/tests/unit/tests/background/feature-flag-defaults-helper.test.ts, src/tests/unit/tests/background/feature-flags.test.ts, src/tests/unit/tests/background/stores/global/feature-flag-store.test.ts, src/tests/unit/tests/electron/common/unified-feature-flags.test.ts, src/tests/unit/tests/injected/dialog-renderer.test.tsx, src/tests/unit/tests/injected/drawing-controller.test.ts, src/tests/unit/tests/injected/drawing-initiator.test.ts, src/tests/unit/tests/injected/visualization/drawer.test.ts, src/tests/unit/tests/injected/visualization/single-target-drawer.test.ts, src/tests/unit/tests/injected/visualization/svg-drawer.test.ts
- Refactored FeatureFlagStore to remove hard dependencies on web feature flags
- Created classes/functions for unified feature flags (These are not yet used anywhere)
=> feat(android-report): create feature flag classes for electron

src/DetailsView/components/report-export-component-factory.tsx, src/DetailsView/components/report-export-component.tsx, src/electron/adapters/direct-action-message-dispatcher.ts, src/electron/views/automated-checks/automated-checks-view.tsx, src/electron/views/automated-checks/components/command-bar.tsx, src/electron/views/renderer-initializer.ts, src/electron/views/report/unified-report-section-factory.ts, src/electron/views/root-container/components/root-container.tsx, src/reports/package/accessibilityInsightsReport.d.ts, src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-component.test.tsx.snap, src/tests/unit/tests/DetailsView/components/report-export-component.test.tsx, src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap, src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx, src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/command-bar.test.tsx.snap, src/tests/unit/tests/electron/views/automated-checks/components/command-bar.test.tsx
The title generally covers the changes: we decided to do minimal changes to report to get it in the app first (behind a feature flag) and this makes that happen.
=> feat(android-report): uses the automated check report as is unified behind feature flag

docs/NOTICE.txt
This PR updates our NOTICE file per recent updates to what we list as "distributed" (in particular, #2511 fixed several cases where we were considering a non-distributed dev dependency as distributed, so this PR overall shrinks the NOTICE file substantially)
=> chore: update notice file per updated dependency listings

src/electron/common/unified-feature-flags.ts, src/tests/unit/tests/electron/common/unified-feature-flags.test.ts
had to recreate PR due to build issues with github
=> feat(android-report): enable android report feature flag

pipeline/unified/build-unsigned-release-packages.yaml, pipeline/unified/download-electron-mirror.yaml
Validation of #2536 before we merge it into master
=> Add Electron versions to environment variables

src/common/feature-flags.ts, src/tests/unit/tests/background/feature-flags.test.ts
=> feat(tablesRequirements): Add feature flag for upcoming tables requirements changes

src/assessments/semantics/assessment.tsx, src/assessments/semantics/test-steps/headers.tsx, src/assessments/semantics/test-steps/test-steps.ts, src/content/test/semantics/headers.tsx, src/content/test/semantics/index.ts, src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
Add Headers requirement content.
screenshot of the requirement (if wired up):
=> feat(tables-requirements): Add Headers requirement content

src/assessments/sequence/test-steps/layout-tables.tsx
- Change text to bring this requirement into alignment with other recent text changes
=> feat(tables-requirements): Update text of sequence > layout tables requirement

src/assessments/semantics/assessment.tsx, src/assessments/semantics/test-steps/table-semantics.tsx, src/assessments/semantics/test-steps/test-steps.ts, src/content/test/semantics/index.ts, src/content/test/semantics/table-semantics.tsx, src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
- Change the name of the requirement from "Data tables" to "Table semantics"
- Update text based on feature
=> Feat(tables-requirements): Update text for data tables

src/assessments/semantics/assessment.tsx, src/assessments/semantics/test-steps/headers-attribute.tsx, src/assessments/semantics/test-steps/test-steps.ts, src/content/test/semantics/headers-attribute.tsx, src/content/test/semantics/index.ts, src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
Add headers attribute requirement.
Screenshot:
=> feat(tables-requirements): Add headers attribute requirement

tools/get-change-log-for-release.js
This improves the `get-change-log-for-release` script to:
* Include PR number in a separate column
* Make PR and commit columns be excel-style hyperlinks (these copy/paste as links in onenote)
* Properly escape commit messages that include quotes
See 2.17.0 validation page for example output
=> tool: add PR/Commit links to get-change-log-for-release output

package.json
This fixes an issue where styles would be generated, get cleaned up and never generated again due to not using escape characters.
- [.] Ran `yarn fastpass`
- [.] Added/updated relevant unit test(s) (and ran `yarn test`)
- [.] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [.] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
=> chore: fix scss watch

src/assessments/semantics/assessment.tsx, src/content/test/semantics/headers.tsx, src/content/test/semantics/table-semantics.tsx, src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
Fixes some typos caught during 2.18.1 validation:
=> fix: typos in new table-requirement content

src/common/feature-flags.ts, src/tests/unit/tests/background/feature-flags.test.ts
Introduces feature flag for reflow UI features.
=> feat(nav-bar-content): add feature flag for reflow UI

src/DetailsView/components/assessment-view-update-handler.ts, src/tests/unit/tests/DetailsView/components/assessment-view-props-builder.tsx, src/tests/unit/tests/DetailsView/components/assessment-view-update-handler.test.ts, src/tests/unit/tests/DetailsView/components/assessment-view.test.tsx
Create a class that contains the update logic for AssessmentView (including toggling visual helpers, changing test steps, etc.)
=> feat(nav-bar-content): AssessmentViewUpdateHandler

src/DetailsView/components/getting-started-view.scss, src/DetailsView/components/getting-started-view.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/getting-started-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/getting-started-view.test.tsx
- Created a basic GettingStartedView component that renders the content passed to it via props
- Added relevant unit test and resulting snapshot
Below is a screenshot comparison of current Getting Started collapsible component and GettingStartedView:
**Screenshot of current Getting Started collapsible component in Headings test of Assessment**
**Screenshot of GettingStartedView in place of current component in Headings test of Assessment**
- Note: this PR is only for creating the component and does not replace the Getting Started section; the screenshots are for a quick comparison between the existing and proposed/potential UI
=> feat(nav-bar-content): create GettingStartedView

Dockerfile, docs/building-web.md, package.json, pipeline/install-node-prerequisites.yaml
Updates Node and Yarn versions we document/require/use in devops builds to their latest LTS versions
=> chore: update node/yarn to latest LTS versions

src/DetailsView/components/reflow-assessment-view.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/reflow-assessment-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/reflow-assessment-view.test.tsx
with logic to show the gettingstarted view when selected subview is not a requirement. Also added a test flie and appropriate snapshot
=> feat(nav-bar-content): added new reflow version of assessment-view 

src/DetailsView/actions/details-view-action-message-creator.ts, src/background/actions/action-payloads.ts, src/background/actions/assessment-action-creator.ts, src/background/actions/assessment-actions.ts, src/common/extension-telemetry-events.ts, src/common/messages.ts, src/common/telemetry-data-factory.ts, src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts, src/tests/unit/tests/background/actions/assessment-action-creator.test.ts, src/tests/unit/tests/common/telemetry-data-factory.test.ts
New actions, messages, and telemetry for selecting the "Getting started" page
=> feat(nav-bar-content): new actions/messages/telemetry for selectGettingStarted

src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-test-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/assessment-test-view.test.tsx
Updated the test cases to use `getElement()` instead of `debug()`
=> feat(nav-bar-content): update to the assessment-test-view.test

src/DetailsView/components/left-nav/assessment-left-nav.tsx, src/DetailsView/components/left-nav/nav-link-handler.ts, src/tests/unit/tests/DetailsView/handlers/nav-link-handler.test.ts
Adds functions to nav link handler to select getting started/requirements. Will have a future PR to utilize these.
=> feat(nav-bar-content): add functionality to navlinkhandler to select getting started + requirement

src/DetailsView/components/requirement-view-title.scss, src/DetailsView/components/requirement-view-title.tsx, src/DetailsView/components/requirement-view.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-view-title.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/requirement-view-title.test.tsx, src/tests/unit/tests/DetailsView/components/requirement-view.test.tsx
Created `RequirementViewTitle` component to be used in `RequirementView` from #2664.
=> feat(nav-bar-content): create RequirementViewTitle component

src/DetailsView/components/requirement-view.scss
- Removed line from GettingStartedView to match Figma design
- Added requirement-view.scss with similar styles
Before:
After:
=> feat(nav-bar-content): update styles for getting started view and requirement view

src/DetailsView/components/requirement-instructions.scss, src/DetailsView/components/requirement-instructions.tsx, src/DetailsView/components/requirement-view.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-instructions.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/requirement-instructions.test.tsx, src/tests/unit/tests/DetailsView/components/requirement-view.test.tsx
`RequirementInstructions` component for collapsible 'How to test' instructions in `RequirementView`
**Screenshot of Heading function requirement view with 'How to test' expanded:**
**Screenshot of Heading function requirement view with 'How to test' collapsed:**
=> feat(nav-bar-content): create RequirementInstructions component

src/electron/platform/android/rule-information-provider.ts, src/electron/platform/android/rule-information.ts, src/electron/platform/android/scan-results-to-unified-rules.ts, src/tests/unit/tests/electron/platform/android/__snapshots__/scan-results-to-unified-rules.test.ts.snap, src/tests/unit/tests/electron/platform/android/rule-information-provider.test.ts, src/tests/unit/tests/electron/platform/android/rule-information.test.ts, src/tests/unit/tests/electron/platform/android/scan-results-helpers.ts, src/tests/unit/tests/electron/platform/android/scan-results-to-unified-results.test.ts, src/tests/unit/tests/electron/platform/android/scan-results-to-unified-rules.test.ts
Adding rule link for each mobile rules.
screenshot:
=> feat(mobile-rules-guidance): add rule link

src/DetailsView/components/requirement-view.scss, src/DetailsView/components/requirement-view.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/requirement-view.test.tsx
- Add the visual helper toggle to `RequirementView`.
**Screenshot of visual helper toggle when there are no matching instances:**
**Screenshot of visual helper toggle when toggled on:**
=> feat(nav-bar-content): add visual helper toggle to requirement view

src/DetailsView/components/requirement-view.tsx, src/tests/unit/tests/DetailsView/components/requirement-view.test.tsx
Fixes build break in master ([example](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=9327&view=logs&j=a131156f-3b43-553f-e7ad-02c8341f7440&t=cceff10f-c32d-5fe7-922c-f93ce1740fe0&l=179))
=> chore: fix build break from cross-PR merge conflict

src/DetailsView/Styles/detailsview.scss, src/DetailsView/components/left-nav/getting-started-nav-link.scss, src/DetailsView/components/left-nav/getting-started-nav-link.tsx, src/DetailsView/details-view-body.tsx, src/common/styles/common.scss, src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/getting-started-nav-link.test.tsx.snap
Increased the width of the left-nav bar to approximately 250px when in the Reflow UI view
View when the feature flag is off:
View when the feature flag is on:
=> feat(nav-bar-content): nav-bar width increase for ReflowUI view

src/DetailsView/components/assessment-test-view.tsx, src/DetailsView/components/reflow-assessment-view.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-test-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/reflow-assessment-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/reflow-assessment-view.test.tsx
Render RequirementView instead of null in ReflowAssessmentView
Screenshot of ReflowAssessmentView with RequirementView for Heading function requirement
=> feat(nav-bar-content): add RequirementView to ReflowAssessmentView

src/DetailsView/Styles/detailsview.scss, src/DetailsView/components/getting-started-view.tsx, src/DetailsView/components/left-nav/getting-started-nav-link.scss, src/DetailsView/components/reflow-assessment-view.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/getting-started-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/reflow-assessment-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/getting-started-view.test.tsx, src/tests/unit/tests/DetailsView/components/reflow-assessment-view.test.tsx
=> feat(nav-bar-content): add test title to getting started + minor style changes

src/DetailsView/components/left-nav/left-nav-icon.tsx, src/DetailsView/components/left-nav/left-nav-link-builder.scss, src/DetailsView/components/left-nav/left-nav-link-builder.tsx, src/DetailsView/components/requirement-view.scss, src/DetailsView/components/requirement-view.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/left-nav-icon.test.tsx.snap, src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/left-nav-link-builder.test.tsx.snap, src/tests/unit/tests/DetailsView/components/left-nav/left-nav-icon.test.tsx
=> feat(nav-bar-content): smaller requirement icons in left nav and better margins

src/assessments/semantics/test-steps/table-semantics.tsx, src/assessments/sequence/test-steps/columns.tsx, src/content/test/semantics/table-semantics.tsx, src/content/test/sequence/columns.tsx, src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
Updates content for Sequence > Columns and Semantics > Table semantics per #2610
Note: This adds an extra "additional guidance" link for columns to the MDN multi-column layout guidance, will want to wait on confirmation in #2610 discussion that we want to keep this before merging
Screenshots of updated content:
**Sequence > Columns test steps:**
**Sequence > Columns info & examples:**
**Semantics > Table Semantics test steps:**
**Semantics > Table Semantics info & examples:**
=> fix: clarify text on Sequence > Columns and Semantics > Table semantics

src/common/components/left-nav-hamburger-button.scss, src/common/components/left-nav-hamburger-button.tsx, src/tests/unit/tests/common/components/__snapshots__/left-nav-hamburger-button.test.tsx.snap, src/tests/unit/tests/common/components/left-nav-hamburger-button.test.tsx
This PR adds the following:
- LeftNavHamburgerButton component that will be placed in the header bar when the width of the window is small
- Relevant unit test and snapshot
- CSS styles for LeftNavHamburgerButton
Note: will add the hamburger button to the header bar in a separate PR
Screenshots of how the hamburger menu _would_ appear when added to the header bar:
regular
regular with focus
regular with hover
high contrast
high contrast with focus
high contrast with hover
=> feat(nav-bar-functionality): create LeftNavHamburgerButton

src/DetailsView/components/interactive-header.tsx, src/common/components/header.tsx, src/common/components/left-nav-hamburger-button.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/interactive-header.test.tsx.snap, src/tests/unit/tests/common/components/__snapshots__/left-nav-hamburger-button.test.tsx.snap, src/tests/unit/tests/common/components/left-nav-hamburger-button.test.tsx
- Updated `Header` to take in the nav menu as an optional prop
- Updated `InteractiveHeader` to pass `LeftNavHamburgerButton` under a feature flag to `Header`
- Updated `LeftNavHamburgerButton` to use the selectedPivot prop to determine which aria label to use (different labels for Assessment and FastPass)
=> feat(nav-bar-functionality): add left nav hamburger menu to header

src/DetailsView/details-view-container.tsx, src/tests/unit/tests/DetailsView/__snapshots__/details-view-container.test.tsx.snap, src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts, src/tests/unit/tests/DetailsView/details-view-container.test.tsx
Removes any direct dependency on a store hub mock and tests that were doing too much. Simplified by just using direct mocks instead.
=> refactor: simplify tests for details view container

src/DetailsView/components/details-view-content.tsx, src/DetailsView/components/left-nav/fluent-side-nav.tsx, src/DetailsView/details-view-body.tsx, src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/fluent-side-nav.test.tsx.snap, src/tests/unit/tests/DetailsView/components/fluent-side-nav.test.tsx, src/tests/unit/tests/DetailsView/details-view-body.test.tsx
=> feat(nav-bar-functionality): wire up panel

src/DetailsView/components/details-view-content-with-local-state.tsx, src/DetailsView/components/details-view-content.tsx, src/DetailsView/components/interactive-header.tsx, src/DetailsView/components/left-nav/fluent-side-nav.tsx, src/common/components/expand-collapse-left-nav-hamburger-button.tsx, src/common/components/left-nav-hamburger-button.tsx, src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-content-with-local-state.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/interactive-header.test.tsx.snap, src/tests/unit/tests/DetailsView/components/details-view-content-with-local-state.test.tsx, src/tests/unit/tests/DetailsView/components/fluent-side-nav.test.tsx, src/tests/unit/tests/DetailsView/components/interactive-header.test.tsx, src/tests/unit/tests/common/components/__snapshots__/expand-collapse-left-nav-hamburger-button.test.tsx.snap, src/tests/unit/tests/common/components/__snapshots__/left-nav-hamburger-button.test.tsx.snap, src/tests/unit/tests/common/components/expand-collapse-left-nav-hamburger-button.test.tsx, src/tests/unit/tests/common/components/left-nav-hamburger-button.test.tsx
=> feat(nav-bar-functionality): wire up hamburger button with panel

src/background/actions/user-configuration-actions.ts, src/background/stores/global/user-configuration-store.ts, src/common/types/store-data/user-configuration-store.ts, src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap, src/tests/unit/tests/DetailsView/components/details-view-overlay/settings-panel/settings/issue-filing/issue-filing-settings.test.tsx, src/tests/unit/tests/DetailsView/details-view-container.test.tsx, src/tests/unit/tests/DetailsView/details-view-content.test.tsx, src/tests/unit/tests/background/get-persisted-data.test.ts, src/tests/unit/tests/background/keyboard-shortcut-handler.test.ts, src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts, src/tests/unit/tests/common/components/cards/card-kebab-menu-button.test.tsx, src/tests/unit/tests/popup/components/popup-view.test.tsx
=> feat(android-setup): add adb location to user config

src/electron/views/device-connect-view/components/android-setup/android-setup.scss, src/electron/views/device-connect-view/components/android-setup/detect-adb-step.tsx, src/electron/views/device-connect-view/device-connect-view.scss, src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/detect-adb-step.test.tsx.snap
Added the spinner for `detecting-adb` state per the Figma mock here: https://www.figma.com/file/Bugs8uNCHdCzOKzhq06nNK2o/Mobile-User-flow?node-id=1285%3A42078 
Image of how the dialog appears now with the changes from this PR:
=> feat(android-setup): detect-adb-step dialog implementation

src/electron/views/device-connect-view/components/android-setup/prompt-connect-to-device-step.tsx, src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/__snapshots__/prompt-connect-to-device-step.test.tsx.snap
Fix a merge conflict that occurred between #2821 and #2822. I hadn't realized that #2822 had already merged when I merged #2821.
=> feat(android-setup): Resolve merge conflict from renamed type

src/DetailsView/components/details-view-content-with-local-state.tsx, src/DetailsView/components/narrow-mode-detector.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-content-with-local-state.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/narrow-mode-detector.test.tsx.snap, src/tests/unit/tests/DetailsView/components/details-view-content-with-local-state.test.tsx, src/tests/unit/tests/DetailsView/components/narrow-mode-detector.test.tsx
avoid state update during rendering in narrow mode detector
=> fix: avoid state update during rendering in narrow mode detector 

src/DetailsView/components/left-nav/fluent-side-nav.scss
The purpose of this PR is to make sure that the header in the panel and the main header have the exact same height.
=> feat(nav-bar-functionality): Fix height of the header inside nav panel

src/common/components/left-nav-hamburger-button.tsx, src/tests/unit/tests/common/components/__snapshots__/left-nav-hamburger-button.test.tsx.snap
Added aria-expanded attribute to indicate if left nav panel is open (aria-expanded=true) or closed (aria-expanded=false).
=> feat(nav-bar-functionality): add aria-expanded attribute to left nav hamburger button

src/DetailsView/components/left-nav/details-view-left-nav.scss
=> fix: remove the space at the end of nav

docs/building-web.md
Added the yarn command that updates snapshots for a specific subset of tests, rather than updating all snapshots
=> chore: added yarn command to update individual tests to Web documentation

src/common/components/cards/card-kebab-menu-button.scss
Fixes a trusted tester bug.
before:
after:
=> feat(trusted-tester-bugs): fix more actions button under windows high contrast mode

src/DetailsView/components/test-step-view.scss
=> feat(trusted-tester-bugs): fix highlight box on info&examples link

src/tests/miscellaneous/mock-service-for-android/serve.js
I'm getting an error when I run **yarn serve:mock-service-for-android**. It's caused by not specifying the external requirement.
Before the fix:
```
>yarn serve:mock-service-for-android
yarn run v1.22.4
$ node ./src/tests/miscellaneous/mock-service-for-android/serve.js
src\tests\miscellaneous\mock-service-for-android\serve.js:5
startMockService(9051, path.join(__dirname, 'AccessibilityInsights'));
^
ReferenceError: path is not defined
at Object.<anonymous> (src\tests\miscellaneous\mock-service-for-android\serve.js:5:24)
at Module._compile (internal/modules/cjs/loader.js:1133:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
at Module.load (internal/modules/cjs/loader.js:977:32)
at Function.Module._load (internal/modules/cjs/loader.js:877:14)
at …
```
=> fix(android-setup): Fix error in mock-service-for-android

src/common/components/cards/needs-review-instances-section.tsx, src/tests/unit/tests/common/components/cards/__snapshots__/needs-review-instances-section.test.tsx.snap, src/tests/unit/tests/common/components/cards/needs-review-instances-section.test.tsx
This is a PR to add a component which will be used to show needs review results.  This component will be specified when the needs review test runs and allows for needs review to display information differently than is done for automated checks.
=> feat(needs-review): Component to show needs review results

src/common/components/cards/instance-details.tsx, src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap, src/tests/unit/tests/common/components/cards/instance-details.test.tsx, src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap
before the chante AT is reading as Table contains 0 rows and 0 columns, after the change it reads 3 rows and 2 columns:
=> feat(trusted-tester-bugs): fix the AT announcement of the card instance table

src/common/components/body-class-modifier.tsx, src/common/components/collapsible-component.tsx, src/common/components/fix-instruction-processor.tsx, tsconfig.strictNullChecks.json
These are all pretty straight forward.
=> Chore: Add null checks

src/DetailsView/components/adhoc-issues-test-view.tsx, src/DetailsView/components/details-list-issues-view.tsx, src/DetailsView/components/issues-table.tsx, src/DetailsView/components/test-view.ts, src/ad-hoc-visualizations/issues/visualization.tsx, src/ad-hoc-visualizations/needs-review/visualization.tsx, src/common/configs/assessment-visualization-configuration.ts, src/common/configs/visualization-configuration.ts, src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-issues-test-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/details-list-issues-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap, src/tests/unit/tests/DetailsView/components/adhoc-issues-test-view.test.tsx, src/tests/unit/tests/DetailsView/components/details-list-issues-view.test.tsx, src/tests/unit/tests/DetailsView/components/issues-table.test.tsx, src/tests/unit/tests/assessments/assessment-builder.test.tsx
Specifying a component in the visualization configuration for automated checks and needs review so that that specific component can be eventually rendered. No UI changes
=> feat(needs-review): Connecting visualization configs to instance sections

src/common/feature-flags.ts, src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts, src/tests/end-to-end/common/page-controllers/details-view-page.ts, src/tests/end-to-end/tests/details-view/headings.test.ts, src/tests/end-to-end/tests/details-view/landmarks.test.ts, src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap, src/tests/unit/tests/DetailsView/details-view-body.test.tsx, src/tests/unit/tests/background/feature-flags.test.ts
Turn on reflow feature flag and update e2e tests for new UI
=> feat(command-bar-reflow): turn on reflow feature flag

src/DetailsView/components/command-bar-buttons-menu.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/command-bar-buttons-menu.test.tsx.snap
Assign "button" role to "..." button to fix #3075 
=> fix: change ... button role to button

src/tests/unit/tests/electron/platform/android/mock-adb.test.ts
This was PR feedback from #3094, that I deferred for a separate PR because I had other work staged on that base.
=> feat(android-setup-e2e): Apply feedback deferred from PR #3094

src/DetailsView/components/nav-link-button.scss
=> fix: gets rid of horizontal scroll bar in left nav

src/assessments/contrast/test-steps/state-changes.tsx, src/assessments/contrast/test-steps/ui-components.tsx
Updates the text as described in #2809 
Image of the State Changes requirement text update:
Image of the UI Components requirement text update:
=> fix: Contrast test requirement text updates

src/common/components/cards/instance-details-footer.tsx, src/tests/unit/tests/common/components/cards/__snapshots__/instance-details-footer.test.tsx.snap
Please see bug #2774 for details.
=> fix: Update the names of buttons for individual failure instances

src/ad-hoc-visualizations/needs-review/visualization.tsx
Changing subtitle for Needs review, as per PM request. 
(Screenshot of Needs review test with new subtitle)
=> feat(needs-review): Making subtitle change

src/content/test/repetitive-content/bypass-blocks.tsx, src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
=> Fix misspelling

src/DetailsView/components/assessment-test-view.tsx, src/DetailsView/components/details-view-content-with-local-state.tsx, src/DetailsView/components/interactive-header.tsx, src/DetailsView/components/left-nav/assessment-left-nav.tsx, src/DetailsView/components/left-nav/details-view-left-nav.tsx, src/DetailsView/components/left-nav/get-left-nav-selected-key.ts, src/DetailsView/details-view-body.tsx, src/DetailsView/details-view-container.tsx, src/common/feature-flags.ts, src/debug-tools/components/debug-tools-view.tsx, src/tests/unit/tests/DetailsView/__snapshots__/details-view-body.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-test-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-content-with-local-state.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/interactive-header.test.tsx.snap, src/tests/unit/tests/DetailsView/components/details-view-content-with-local-state.test.tsx, src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/assessment-left-nav.test.tsx.snap, src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/details-view-left-nav.test.tsx.snap, src/tests/unit/tests/DetailsView/components/left-nav/assessment-left-nav.test.tsx, src/tests/unit/tests/DetailsView/components/left-nav/get-left-nav-selected-key.test.ts, src/tests/unit/tests/DetailsView/details-view-body.test.tsx, src/tests/unit/tests/DetailsView/details-view-container.test.tsx, src/tests/unit/tests/background/feature-flags.test.ts, src/tests/unit/tests/debug-tools/components/__snapshots__/debug-tools-view.test.tsx.snap, src/tests/unit/tests/debug-tools/components/debug-tools-view.test.tsx
This PR removes mention of the reflow feature flag. It does not remove ALL components that might have been shown as a result of the feature flag being disabled (for example: test step view will never be shown but is still in the code base). This will be covered in a future PR.
=> chore: removing any mention of the reflow feature flag and updating relevant controls

src/issue-filing/services/azure-boards/azure-boards-settings-form.tsx, src/issue-filing/services/github/github-issue-filing-service.tsx, src/tests/unit/tests/issue-filing/services/azure-boards/__snapshots__/azure-boards-settings-form.test.tsx.snap, src/tests/unit/tests/issue-filing/services/github/__snapshots__/github-issue-filing-service.test.tsx.snap
Updated the text in according to #2784 and updated the snapshots for their unit tests to account for the new text
New Github Label: 
New Azure DevOps Label:
Should be noted that this will affect the text in the web extension, since they share the same Issue Filing components.
=> fix: updated the text for the Issue Filing labels 

src/common/components/header.scss
=> fix: header has same height in panel and normally

package.json, pipeline/scripts/download-electron-mirror.js, yarn.lock
This PR updates electron to 8.4.1. The release notes for 8.4.1 are [here](https://www.electronjs.org/releases/stable?page=3#8.4.1), although this picks up all the other changes past 8.2.2 as well.
Sample builds [here](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=13560&view=results)
=> chore: update to electron 8.4.1

src/assessments/contrast/test-steps/state-changes.tsx
Earlier fix for #2809 was very slightly off
=> fix: wording slightly off in Contrast > State changes requirement desc

src/DetailsView/Styles/detailsview.scss, src/DetailsView/components/details-view-overlay/scoping-panel/scoping-container.scss, src/DetailsView/components/details-view-overlay/scoping-panel/scoping-container.tsx, src/common/components/selector-input-list.scss, src/common/components/selector-input-list.tsx, src/tests/unit/tests/DetailsView/components/details-view-overlay/scoping-panel/scoping-container.test.tsx, src/tests/unit/tests/common/components/selector-input-list.test.tsx
Before on left, after on right (should be same). And yes, the CSS is not ideal in master before this change but since it's behind a hidden feature flag, it's fine.
=> refactor: scoping container css module

src/scanner/rule-to-links-mappings.ts, src/tests/end-to-end/tests/details-view/headings.test.ts, src/tests/end-to-end/tests/details-view/reflow-ui.test.ts
Axe-core 4.0.1 has a false positive (documented at https://github.com/dequelabs/axe-core/issues/2459) that can trigger `link-name` errors on links that specify their text via the `target` attribute instead of the `aria-label` attribute. This is breaking our E2E tests and could expose users to false positives. To address these, we're temporarily classifying the `link-name` rule as a BestPractice and updating the E2E tests to expect the failures from axe-core.
We also explored using the `aria-label` attribute (augmenting or replacing the `target` attribute), but concluded that this was the better approach, on the assumption that the false positive would be fixed, hopefully soon.
- [blocked pending #3253] Added/updated relevant unit test(s) (and ran `yarn test`)
- [blocked pending #3253] …
=> feat(axe-core-4.0.1): Disable link-name rule (false positive)

src/DetailsView/details-view-initializer.ts, src/common/globalization.ts, src/content/test/language/language-of-parts.tsx, src/reports/components/assessment-report-body.tsx, src/reports/components/assessment-scan-details.tsx, src/reports/components/formatted-date.tsx, src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap, src/tests/unit/tests/reports/components/__snapshots__/assessment-report-body.test.tsx.snap, src/tests/unit/tests/reports/components/__snapshots__/assessment-scan-details.test.tsx.snap, src/tests/unit/tests/reports/components/__snapshots__/formatted-date.test.tsx.snap, src/tests/unit/tests/reports/components/assessment-scan-details.test.tsx, src/tests/unit/tests/reports/components/formatted-date.test.tsx
- Use the official name for the es-419 language code: Spanish (Latin American)
- Remove the first parameter to Date.toLocaleTimeString so that the default language format will be used
=> feat (compliance-web): Global readiness fixes

src/tests/end-to-end/test-resources/image/image-text.html, src/tests/end-to-end/test-resources/unicode-test.html
The file will generate an error when scanned with AI-Web. The error message will contain a 16-bit Unicode character. This shows that AI-Web is handling Unicode data input, transfer, and display properly. The errors can be used to generate a report where the Unicode characters should also be displayed properly.
=> feat(compliance-web): Add file to test Unicode chars in AI-Web

.eslintrc.js, src/DetailsView/components/issues-table-handler.ts, src/common/uid-generator.ts, src/scanner/exposed-apis.ts, src/scanner/processor.ts, src/tests/unit/tests/DetailsView/components/adhoc-issues-test-view.test.tsx
This PR is part of the process of enabling the full set of recommended eslint rules.
=> Chore: Add eslint rule: prefer-const

src/common/date-provider.ts, src/reports/components/report-sections/summary-report-details-section.scss, src/reports/components/report-sections/summary-report-details-section.tsx, src/reports/components/report-sections/summary-report-section-factory.tsx, src/reports/package/accessibilityInsightsReport.d.ts, src/reports/package/reporter-factory.ts, src/reports/package/summary-results-report.ts, src/reports/summary-report-html-generator.tsx, src/reports/summary-report.scss, src/tests/unit/common/date-provider.test.tsx, src/tests/unit/tests/reports/components/report-sections/__snapshots__/summary-report-details-section.test.tsx.snap, src/tests/unit/tests/reports/components/report-sections/summary-report-details-section.test.tsx, src/tests/unit/tests/reports/package/summary-results-report.test.ts, src/tests/unit/tests/reports/summary-report-html-generator.test.tsx
Create crawl summary report details section:
Target url link uses the same NewTabLinkWithConfirmationDialog component as automated checks reports
=> feat(cli-summary-report): Summary report details section

src/reports/package/root/package.json
Bump report package version to 2.1.0 to release summary report functionality
=> feat(cli-summary-report): bump report package version to 2.1.0

src/reports/components/outcome-summary-bar.scss, src/reports/components/report-head.tsx, src/reports/components/report-sections/automated-checks-report-section-factory.tsx, src/reports/components/summary-report-head.tsx, src/reports/package/reporter-factory.ts, src/tests/unit/tests/reports/components/__snapshots__/report-head.test.tsx.snap, src/tests/unit/tests/reports/components/__snapshots__/summary-report-head.test.tsx.snap, src/tests/unit/tests/reports/components/report-head.test.tsx, src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap
Minor tweaks to the head which mentioned web product.
Also, outcome summary bar which was validated to have no impact in assessment report but solves a minor reflow issue in reporter.
=> feat(cli-summary-report): fix up some formatting/styling for report

src/reports/package/root/package.json
=> feat(cli-summary-summary-report): bump reporter version to 2.1.1

src/reports/package/root/package.json
Just bumping minor version as only change is report footer fix.
=> feat(cli-summary-report): bump report package to 2.1.2

src/electron/common/unified-feature-flags.ts, src/tests/unit/tests/electron/common/unified-feature-flags.test.ts
- Created UnifiedFeatureFlag `leftNavBar` with false default value
- Updated corresponding unit test to include `leftNavBar`
=> feat(android-left-nav): add leftNavBar unified feature flag

package-lock.json, src/content/link.tsx, src/content/test/custom-widgets/expected-input.tsx, src/content/test/custom-widgets/instructions.tsx, src/content/test/headings/no-missing-headings.tsx, src/content/test/native-widgets/expected-input.tsx, src/content/test/native-widgets/instructions.tsx, src/content/test/semantics/table-headers.tsx, src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
Adding videos to info & examples. This are short videos from the Enable Channel that explain the impact of a certain requirement to users.
This adds additional resources for users in Assessment to understand Why it matters from a user's perspective.
**Headings**
**Native Widgets and Custom Widgets**
**Semantics**
- [ n/a] Addresses an existing issue: #0000 
- [ n/a] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x ] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [x ] (UI changes only) Added screenshots/GIFs to description above
- [ x] (UI changes only) Verified usability with NVDA/JAWS
=> chore: Adding new videos links to info&examples

.eslintrc.js, src/background/background-init.ts, src/common/flux/event-handler-list.ts, src/electron/views/renderer-initializer.ts, src/injected/scanner-utils.ts, src/issue-filing/common/markup/html-formatter.ts, src/popup/popup-initializer.ts, src/tests/electron/common/scan-for-accessibility-issues.ts, src/tests/end-to-end/common/page-controllers/background-page.ts, src/tests/end-to-end/common/scan-for-accessibility-issues.ts, src/tests/unit/tests/DetailsView/components/assessment-instance-details-column.test.tsx, src/tests/unit/tests/background/actions/action-creator.test.ts, src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts, src/types/common-types.ts
Changes should be pretty straight forward.
- no-irregular-whitespace (0)
- no-var (7)
- no-regex-spaces (1)
- no-extra-boolean-cast (1)
- prefer-spread (3)
Also fix null checks which appeared while addressing prefer-spread
=> Chore: Enable eslint rules

src/electron/views/automated-checks/components/command-bar.tsx, src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/command-bar.test.tsx.snap
When the `leftNavBar` feature flag is enabled, the Start over button appears to the right of the Export result button on the command bar. NVDA reads the components in the following order: Export result > Start over > Settings.
When the flag is disabled, the Start over button remains in its original position on the left side of the command bar. NVDA reads the components in the following order: Start over > Export result > Settings.
Screenshot of Start over button on the left side, with feature flag disabled (before)
Screenshot of Start over button on the right side, with feature flag enabled (after)
=> feat(android-left-nav): move unified command bar start over button

src/electron/views/automated-checks/automated-checks-view.scss, src/electron/views/automated-checks/automated-checks-view.tsx, src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
When the `leftNavBar` feature flag is enabled, the command bar stretches above the screenshot view. When it is disabled, the command bar remains the same. Verified that scrollbars and NVDA behavior are unaffected (finishes reading out the components in the command bar, then goes to the automated checks results/cards, then to the screenshot, and back to the command bar).
Screenshot of app with shorter command bar (before)
Screenshot of app with expanded command bar (after)
Screenshot of app with minimum window size and shorter command bar (before)
Screenshot of app with minimum window size and expanded command bar (after)
=> feat(android-left-nav): expand unified command bar

src/reports/package/accessibilityInsightsReport.d.ts, src/reports/package/reporter.ts, src/reports/package/summary-results-report.ts, src/tests/unit/tests/reports/package/reporter.test.ts, src/tests/unit/tests/reports/package/summary-results-report.test.ts
Add interface for combined report, assuming input data is already deduplicated by URL and grouped by rule
=> feat(combined-report-ui): add interface for combined report

src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap
Changes from #3479 and #3478 may have conflicted, the text updates weren't consistent, leading to CI failure [here](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=14754&view=logs&j=3613c2bd-8b62-5a70-8491-3e8459586450&t=d1343856-9cd9-5649-cdc6-81bc16053e6f). This PR reapplies the snapshot change from #3479.
=> test: update reporter snapshot to fix merge conflict

packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html
Update report e2e snapshot to fix CI build failures
=> fix: update report e2e snapshot

packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html, packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html
Update e2e report snapshots which are causing CI failures
=> fix: update report e2e snapshots

packages/report/package.json
bump report package version from 2.2.1 to 3.0.0 (includes the new combined report UI and a breaking change to the interface for summary reports)
=> feat(combined-report-ui): bump report package major version to 3

packages/report/package.json
Fixes a small bug that is preventing the report package typings file from being included when the package is published
=> feat(combined-report-ui): include typings in report package

docs/building-web.md
#3604
- [NA ] Ran `yarn fastpass`
- [ NA] Added/updated relevant unit test(s) (and ran `yarn test`)
- [ NA] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x ] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [ NA] (UI changes only) Added screenshots/GIFs to description above
- [ NA] (UI changes only) Verified usability with NVDA/JAWS
=> fix: broken link in building-web

src/tests/electron/tests/needs-review-view.test.ts
Very small change to add automated accessibility checks to the needs review page in results view.
=> feat(android-needs-review): Add e2e accessibility checks

packages/report/package.json
Minor version update for non-breaking update to axe-core 4.1.1 that adds support for new rules
=> feat(axe-core-4.1.1): bump report package minor version to 3.1.0

README.md
Per [the latest open source release guidance](https://docs.opensource.microsoft.com/content/releasing/index.html), readme files should include a Trademarks section.
=> chore(web-android-compliance): Add trademarks notice to README

src/assessments/contrast/test-steps/ui-components.tsx
update Contrast how to test exception text to address issue #3806
screenshot:
=> fix: update Contrast how to test exception text

src/assessments/contrast/test-steps/state-changes.tsx, src/assessments/contrast/test-steps/ui-components.tsx
Update Contrast > State changes exception text to address issue #3806
screenshot:
=> fix: update Contrast > State changes exception text

src/electron/platform/android/test-configs/automated-checks/test-config.tsx, src/electron/platform/android/test-configs/needs-review/test-config.tsx, src/electron/types/content-page-info.ts, src/electron/types/visual-helper-section.ts, src/electron/views/results/results-view.tsx, src/tests/unit/tests/electron/common/content-page-info-factory.test.tsx, src/tests/unit/tests/electron/views/results/__snapshots__/results-view.test.tsx.snap, src/tests/unit/tests/electron/views/results/results-view.test.tsx
=> refactor(focus-mvp-client): get visual helper section from test config

packages/report/package.json
Bumping report version to validate npm publishing
=> chore: bump report package to 4.0.1

src/DetailsView/components/export-dialog-with-local-state.tsx, src/background/stores/assessment-store.ts, src/common/state-dispatcher.ts, src/views/content/content-page.tsx
Resolve two warnings from the [list of warnings on lgtm.com](https://lgtm.com/projects/g/microsoft/accessibility-insights-web/?mode=list).
- [Ineffective parameter type](https://lgtm.com/rules/1505880476240/)
- [Useless assignment to property](https://lgtm.com/rules/1506738031393/)
- [Unused variable, import, function or class](https://lgtm.com/rules/1780092/)
- [Potentially inconsistent state update](https://lgtm.com/rules/1819283066/)
Clean up these warnings so we can increase codeql checks on our PR's
=> Chore: Fix issues causing lgtm warnings

CONTRIBUTING.md, README.md, build.yaml, docs/building-web.md, docs/git-branch-setup.md, packages/report/README.md, pipeline/build-reliability.yaml, pipeline/e2e-reliability.yaml, pipeline/unified/sign-release-packages.yaml, pipeline/unified/unified-e2e-reliability.yaml, src/packages/accessibility-insights-ui/root/README.md, src/tests/miscellaneous/mock-adb/README.md
Rename references from the master branch to the new main branch
It's the right thing to do.
=> Chore: Changes resulting from renaming master to main

package.json, src/tests/unit/tests/electron/platform/android/__snapshots__/mock-adb.test.ts.snap, yarn.lock
Updates service to use for tabstops test.
feature work.
=> feat(focus-mvp-android-device): update to use new android service 1.3.0

package.json, src/tests/unit/tests/electron/platform/android/__snapshots__/mock-adb.test.ts.snap, yarn.lock
Update for latest changes.
Feature work.
=> feat(focus-mvp-android-device): update android service to 1.3.1

src/Devtools/target-page-inspector.ts, src/assessments/adaptable-content/assessment.tsx, src/assessments/types/requirement.ts, src/background/browser-message-broadcaster-factory.ts, src/background/stores/dev-tools-store.ts, src/background/telemetry/console-telemetry-client.ts, src/background/telemetry/debug-tools-telemetry-client.ts, src/background/user-stored-data-cleaner.ts, src/common/components/body-class-modifier.tsx, src/common/components/copy-issue-details-button.tsx, src/common/styles/root-level-only/color-definitions.scss, src/common/styles/root-level-only/global-styles.scss
This PR fixes various typos and grammatical issues in code comments.
Observed several errors while reviewing the code.
Ran `git grep` to quickly find all comments, read relevant surrounding code to get context for any changes made to comments.
=> chore: Typo and grammatical fixes in comments

packages/report/package.json
Updates the version number in the report package in preparation for releasing support for the new rules for the service to consume
Keep rulesets in sync between web/service
#4155 covered the feature-level update, this just bumps the version number accordingly
=> feat(axe-core-4.2.0): bump report package version from 4.0.1 to 4.1.0

packages/report/package.json
Bump report package version from 4.1.0 to 4.1.1
This is only to test npm publishing and doesn't reflect any significant updates to the package
=> chore: bump report version

package.json, packages/report/package.json, src/injected/frameCommunicators/axe-frame-messenger.ts, src/packages/accessibility-insights-ui/root/package.json, src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap, yarn.lock
* Bumps axe-core to 4.2.1
* Updates corresponding snapshots
* Updates some related comments in axe-frame-messenger
* Bumps the report version to 4.1.2 so we can consume the update in service
Contains several important false positive fixes
[axe-core 4.2.1 release notes](https://github.com/dequelabs/axe-core/releases/tag/v4.2.1)
Contains no changes to rule inclusion/exclusion.
=> feat(axe-core-4.2.1): Update axe-core

src/packages/accessibility-insights-ui/root/package.json
Bump ui package from 0.1.1 to 0.1.2 for reflow style changes from #2845
Bumping version to release updated version of ui package for bug fix associated with reflow
=> chore: bump accessibility-insights-ui from 0.1.1 to 0.1.2 for bug fix

packages/ui/package.json
Similar to #3597, fixes a bug that is preventing the ui package css file from being included when the package is published
Include ui.css in the published package
Verified with `npm pack` that the `ui.css` file is included in the package
=> fix: include ui.css in ui package

src/background/stores/tab-store.ts, src/tests/end-to-end/common/page-controllers/nested-iframe-target-page.ts, tsconfig.strictNullChecks.json
This PR includes partial fixes for tab store (did not add to file as there are still errors I'm unsure how to fix) and fixes for a file in the e2e tests.
Part of strict null checks.
- [n/a] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
=> chore(strict-null): fixes in tab store and e2e test

packages/report/package.json
Bumping report version.
feature work.
axe-core has already been bumped.
=> feat(axe-core-4.3.2): bump report version due to axe-core update/release

yarn.lock
This addresses the dependabot security alert for @npmcli/git.
Addresses security alert
=> chore: Update @npmcli/git

pipeline/unified/unified-e2e-test-interactive.yaml, src/tests/electron/common/create-application.ts, src/tests/electron/tests/framework-no-codecs.test.ts, src/tests/miscellaneous/codecs/codecs-test.js
Right now release tests are failing because these tests are skipped until release so they were missed.
Updating calls to not throw errors during tests.
=> fix(framework-no-codecs.test.js): update codecs tests to use Page APIs

src/reports/assessment-json-export-generator.ts, src/reports/assessment-json-export-json-builder.ts, src/tests/unit/tests/reports/__snapshots__/assessment-json-export-json-builder.test.ts.snap, src/tests/unit/tests/reports/assessment-json-export-generator.test.tsx, src/tests/unit/tests/reports/assessment-json-export-json-builder.test.ts, src/tests/unit/tests/test-resources/reports/json-export-report-model-data.json
This adds all the logic for creating and exporting the JSON report.
Feature work
We will be wiring all of this up in a later PR.
=> feat(download-report-json): create JSON export builder

src/DetailsView/components/adhoc-tab-stops-test-view.scss, src/DetailsView/components/adhoc-tab-stops-test-view.tsx, src/DetailsView/components/tab-stops-failed-instance-section.scss, src/DetailsView/components/tab-stops/tab-stops-requirement-table.scss, src/DetailsView/components/tab-stops/tab-stops-requirements-table.tsx, src/DetailsView/tab-stops-minimal-requirement-header.scss, src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-tab-stops-test-view.test.tsx.snap, src/tests/unit/tests/DetailsView/components/adhoc-tab-stops-test-view.test.tsx, src/tests/unit/tests/DetailsView/components/tab-stops/__snapshots__/tab-stops-requirements-table.test.tsx.snap
title covers it.
feature work
Before changes:
What it looks like now with the adjustments
=> feat(tab-stops-details-view): fixing minor visual fit and finish items

src/DetailsView/components/details-view-command-bar.tsx, src/DetailsView/components/report-export-dialog-factory.tsx, src/DetailsView/components/should-show-report-export-button.ts, src/DetailsView/components/test-view-container.tsx, src/DetailsView/details-view-initializer.ts, src/ad-hoc-visualizations/tab-stops/visualization.tsx, src/common/configs/visualization-configuration.ts, src/common/feature-flags.ts, src/reports/components/report-sections/automated-checks-report-section-factory.tsx, src/reports/components/report-sections/axe-results-report-section-factory.tsx, src/reports/package/reporter-factory.ts, src/reports/report-generator.ts, src/tests/end-to-end/tests/details-view/fast-pass-report.test.ts, src/tests/end-to-end/tests/details-view/tabstops.test.ts, src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-dialog-factory.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/test-view-container.test.tsx.snap, src/tests/unit/tests/DetailsView/components/report-export-dialog-factory.test.tsx, src/tests/unit/tests/DetailsView/components/should-show-report-export-button.test.ts, src/tests/unit/tests/background/feature-flags.test.ts, src/tests/unit/tests/reports/report-generator.test.ts
This removes the feature flag, removes some unused code paths, and updates tests accordingly
feature work
=> feat(tabstops-report): Remove feature flag

packages/ui/package.json
Incrementing accessibility-insights-ui package version in preparation for release.
Updating UI package in association with ongoing web release.
There was a small CSS change in the package, so I've updated the patch version.
=> chore: Increment accessibility-insights-ui version

packages/report/package.json
Running the pipeline to validate tokens are rotated
=> chore: bump patch version for secrets rotation validation

package.json, yarn.lock
Upgrading plist to use versions >=3.0.5
Addresses an alert
An auto-generated PR was not available at this time
- [n/a] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
=> chore(deps): Use resolutions to upgrade plist dependency

package.json, pipeline/scripts/unified-mac-sign.js, yarn.lock
Removes the usage of globby since it's not doing anything special. Wrote something that works for us.
Removing a dependency that isn't necessary.
n/a
- [] Added/updated relevant unit test(s) (and ran `yarn test`)
- [] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
=> refactor: remove usage of globby (not needed)

packages/report/package.json
Bumping report package version to release new version of accessibility-insights-report that consumes axe-core 4.4.1
Updating to axe-core 4.4.1 that contains 17 false-positive fixes, 1 rule change and 1 general improvement
=> feat(axe-core-4.4): bump report package version for axe-core update

eslintrc.base.js, src/background/dev-tools-monitor.ts, src/background/tab-event-distributor.ts, src/background/target-page-controller.ts, src/background/telemetry/app-insights-telemetry-client.ts, src/background/telemetry/console-telemetry-client.ts, src/background/telemetry/debug-tools-telemetry-client.ts, src/background/telemetry/multiplexing-telemetry-client.ts, src/background/telemetry/telemetry-client.ts, src/background/telemetry/telemetry-event-handler.ts, src/tests/unit/tests/background/telemetry/app-insights-telemetry-client.test.ts, src/tests/unit/tests/background/telemetry/console-telemetry-client.test.ts, src/tests/unit/tests/background/telemetry/debug-tools-telemetry-client.test.ts, src/tests/unit/tests/background/telemetry/multiplexing-telemetry-client.test.ts, src/tests/unit/tests/background/telemetry/telemetry-event-handler.test.ts
Fixes or suppresses no-floating-promises issues in src/background and enables the eslint rule for that directory.
Continuing work from #5517
See #5517. This PR fixes 4 issues out of 22.
=> feat(mv3-part-4): Fix or suppress no-floating-promise issues in background directory

src/injected/all-frame-runner.ts, src/injected/analyzers/tab-stops-analyzer.ts, src/injected/analyzers/tab-stops-orchestrator.ts, src/injected/analyzers/tab-stops-requirement-result-processor.ts, src/injected/client-store-listener.ts, src/injected/drawing-controller.ts, src/injected/focus-change-handler.ts, src/injected/main-window-initializer.ts, src/injected/single-frame-tab-stop-listener.ts, src/injected/target-page-visualization-updater.ts, src/injected/visualization-state-change-handler.ts, src/injected/window-initializer.ts, src/tests/unit/tests/injected/all-frame-runner.test.ts, src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts, src/tests/unit/tests/injected/analyzers/tab-stops-orchestrator.test.ts, src/tests/unit/tests/injected/analyzers/tab-stops-requirement-result-processor.test.ts, src/tests/unit/tests/injected/focus-change-handler.test.ts, src/tests/unit/tests/injected/single-frame-tab-stop-listener.test.ts, src/tests/unit/tests/injected/target-page-visualization-updater.test.ts, src/tests/unit/tests/injected/visualization-state-change-handler.test.ts
Fix no-floating-promises issues around the tab stops visualizer and DrawingController.
Continuing work from #5517 and #5524
See #5517. This PR fixes 17 of the remaining 18 issues.
=> feat(mv3-part-4): Fix most no-floating-promises issues in injected directory

webpack.config.js
Configs have been made obsolete with esbuild work.
clean up
=> feat(esbuild): remove unused webpack configs

build.yaml
set maxWorkers to 2 for jest in our CI builds for faster CI builds.
CI builds should be faster.
Similar story to #5638. Seeing about a 20-25% decrease in CI build times (the unit-tests specifically are down about 40%-50% but other variables lead to us not seeing the same effect in our builds).
Info on Azure VMs was from here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#hardware.
**Note:** Another place this change might be helpful is the build package template. However, I did not include that in this PR since I've not tested it yet.
Some before builds:
https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=34739&view=results …
=> fix: set jest maxWorkers to 2 for CI builds

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html, packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html, packages/report-e2e-tests/src/examples/combined-results-with-baseline-aware-issues.snap.html, packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html, packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html, packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html, packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html, src/common/components/cards/card-kebab-menu-button.scss, src/common/components/cards/card-kebab-menu-button.tsx
This PR adds styling for the kebab menu icon in high contrast mode. The existing kebab menu has styles for the button but didn't set styles for the icon itself. This used the default color for the icon, causing it to not be visible in the Desert high contrast theme.
| Contrast Theme | Hover | Before | After | 
|-------------------|-------|-------|-------|
| Desert                |   🚫  | ![canary-desert](https://user-images.githubusercontent.com/3230904/175084397-cb283382-972c-4c87-b0bc-e67e07b44159.png) | ![dev-desert](https://user-images.githubusercontent.com/3230904/175091153-cb244404-486e-40e8-b794-12668a2e8b21.png) |
| Desert                |  ✅   |  ![canary-desert-hover](https://user-images.githubusercontent.com/3230904/175082630-49930034-e415-4fea-aa7d-89a872ef901b.png) | …
=> fix: ensure kebab actions menu is visible in high contrast mode

src/background/actions/command-actions.ts, src/background/global-action-creators/global-action-creator.ts, src/background/stores/global/command-store.ts, src/common/browser-adapters/commands-adapter.ts, src/common/browser-adapters/webextension-browser-adapter.ts, src/tests/unit/common/store-tester.ts, src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts
Convert the action in CommandActions from a SyncAction to an AsyncAction
Feature work
=> feat(mv3-part-5): convert CommandActions to use AsyncActions

src/background/actions/action-creator.ts, src/background/actions/card-selection-action-creator.ts, src/background/actions/card-selection-actions.ts, src/background/stores/card-selection-store.ts, src/electron/common/left-nav-item-factory.ts, src/electron/flux/action-creator/left-nav-action-creator.ts, src/tests/unit/tests/background/actions/action-creator.test.ts, src/tests/unit/tests/background/actions/card-selection-action-creator.test.ts, src/tests/unit/tests/electron/common/left-nav-item-factory.test.ts, src/tests/unit/tests/electron/flux/action-creator/left-nav-action-creator.test.ts
Convert SyncActions in CardSelectionActions to AsyncActions
Feature work
=> feat(mv3-part-5): convert CardSelectionActions to AsyncActions

src/background/actions/action-creator.ts, src/background/actions/details-view-action-creator.ts, src/background/actions/side-panel-actions.ts, src/background/stores/details-view-store.ts, src/tests/unit/tests/background/actions/action-creator.test.ts, src/tests/unit/tests/background/actions/details-view-action-creator.test.ts
Convert side panel actions from SyncAction to AsyncAction
Feature work
N/a
=> feat(mv3-part-5): Convert side panel actions to async

src/background/actions/user-configuration-actions.ts, src/background/global-action-creators/user-configuration-action-creator.ts, src/background/stores/global/user-configuration-store.ts, src/tests/unit/tests/background/global-action-creators/user-configuration-action-creator.test.ts
Convert UserConfigurationActions from SyncAction to AsyncAction
Feature work
N/a
=> feat(mv3-part-5): Convert UserConfigurationActions to async

src/background/actions/content-action-creator.ts, src/background/actions/content-actions.ts, src/background/stores/details-view-store.ts, src/tests/unit/tests/background/actions/content-action-creator.test.ts
Convert SyncActions in ContentActions to AsyncActions
Feature work
n/a
=> feat(mv3-part-5): Convert ContentActions to async

src/background/actions/action-creator.ts, src/background/actions/needs-review-card-selection-action-creator.ts, src/background/actions/needs-review-card-selection-actions.ts, src/background/stores/needs-review-card-selection-store.ts, src/tests/unit/tests/background/actions/needs-review-card-selection-action-creator.test.ts
Convert NeedsReviewCardSelectionActions from SyncAction to AsyncAction
Feature work
N/a
=> feat(mv3-part-5): Convert NeedsReviewCardSelectionActions to async

src/background/actions/feature-flag-actions.ts, src/background/feature-flags-controller.ts, src/background/global-action-creators/feature-flags-action-creator.ts, src/background/stores/global/feature-flag-store.ts, src/tests/end-to-end/common/page-controllers/background-page.ts, src/tests/unit/tests/background/feature-flags-controller.test.ts, src/tests/unit/tests/background/global-action-creators/feature-flags-action-creator.test.ts
Convert SyncActions in FeatureFlagActions to AsyncActions
Feature work
=> feat(mv3-part-5): Convert FeatureFlagActions to async

src/background/actions/scoping-actions.ts, src/background/global-action-creators/scoping-action-creator.ts, src/background/stores/global/scoping-store.ts, src/tests/unit/tests/background/global-action-creators/scoping-action-creator.test.ts
Convert ScopingActions from SyncAction to AsyncAction
Feature work
N/a
=> feat(mv3-part-5): Convert ScopingActions to async

src/background/actions/action-creator.ts, src/background/actions/visualization-actions.ts, src/background/stores/tab-store.ts, src/background/stores/visualization-scan-result-store.ts, src/background/stores/visualization-store.ts
Convert VisualizationActions from SyncAction to AsyncAction
Feature work
N/a
=> feat(mv3-part-5): Convert VisualizationActions to async

src/background/actions/action-creator.ts, src/background/actions/inspect-action-creator.ts, src/background/actions/inspect-actions.ts, src/background/stores/inspect-store.ts, src/tests/unit/tests/background/actions/inspect-action-creator.test.ts
Convert SyncActions in InspectActions to AsyncActions
Feature work
n/a
=> feat(mv3-part-5): Convert InspectActions to AsyncActions

src/common/telemetry/exception-telemetry-listener.ts, src/tests/unit/tests/common/telemetry/exception-telemetry-listener.test.ts
Fix bug in which exception telemetry listener swallows errors and unhandled rejections after reporting telemetry. This was caused by the way we were registering exception listeners. 
Fix bug from feature work.
Exception telemetry listener was originally added in https://github.com/microsoft/accessibility-insights-web/pull/5570 and https://github.com/microsoft/accessibility-insights-web/pull/5550.
=> feat(mv3-part5): Ensure exception telemetry listener does not swallow errors

package.json
Just adding a command to package.json
Quicker dev loop if you use watch locally.
=> chore: add a watch command for web mv3

src/debug-tools/action-creators/debug-tools-nav-action-creator.ts, src/debug-tools/actions/debug-tools-nav-actions.ts, src/debug-tools/components/debug-tools-nav.tsx, src/debug-tools/stores/debug-tools-nav-store.ts, src/tests/unit/tests/debug-tools/action-creators/debug-tools-nav-action-creator.test.ts
Convert DebugToolsNavActions from SyncAction to AsyncAction
Feature work
N/a
=> feat(mv3-part-5): Convert DebugToolsNavActions to async

src/background/actions/dev-tools-action-creator.ts, src/background/actions/dev-tools-actions.ts, src/background/dev-tools-monitor.ts, src/background/stores/dev-tools-store.ts, src/tests/unit/tests/background/actions/dev-tools-action-creator.test.ts, src/tests/unit/tests/background/dev-tools-monitor.test.ts
Title covers it.
Feature work.
=> feat(mv3-part5): devToolActions to use AsyncAction

src/background/actions/user-configuration-actions.ts, src/background/global-action-creators/user-configuration-action-creator.ts, src/background/stores/global/user-configuration-store.ts, src/tests/unit/tests/background/global-action-creators/user-configuration-action-creator.test.ts
Reverts #5894
Feature work
See #5901
=> feat(mv3-part-6): Make UserConfigurationActions async again

src/background/dev-tools-monitor.ts, src/tests/unit/tests/background/dev-tools-monitor.test.ts
Only mark a devtool as "closed" if we fail to reach it three times in a row.
Currently, in the background or service worker, each tab has a DevToolsMonitor that polls any open devtools until they fail to respond, and then marks them as closed in the DevToolStore. This means that, if the browser is running slowly and the devtool misses just one ping, the background will wrongly assume that devtool has closed. From a user perspective, this puts the extension in a state where clicking "inspect element" on the Automated Checks visualizer shows a message for the user to open a devtool, even though one is already open.
This PR makes devtool monitoring more failure-tolerant by requiring a devtool to fail three pings in a row before we mark it as closed.
n/a …
=> fix: make DevToolsMonitor more failure-tolerant

docs/building-web.md
Since we only currently support node v16, the README should reflect that requirement.
Clarifying the requirements for building AI Web
=> docs: fix recommended node version in building-web.md

packages/report/package.json
Bump the patch version to force a pipeline run
Routine validation step after secrets rotation
=> chore: Bump patch version to validate secrets

.eslintrc.js, tools/get-chrome-refresh-token.js
Adding script used for getting a chrome refresh token to the tools dir. This script is used in our secrets rotation process. 
Keep scripts related to this product in a central location
=> chore: Add script to get chrome refresh token to tools

build.yaml
CodeQL analysis is available through injection and this enables it through a flag.
Security requirement.
=> chore: enable CodeQL analysis in CI builds

src/common/feature-flags.ts, src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
Add Quick Assess feature flag to Preview features
Screenshot of Quick Assess feature flag in Preview features panel
=> feat(quick-assess): set Quick Assess as a preview feature

src/DetailsView/components/overview-content/overview-heading-intro-text.ts, src/DetailsView/components/quick-assess-to-assessment-dialog.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/quick-assess-to-assessment-dialog.test.tsx.snap
Fix capitalization of `Quick Assess` and `Assessment` in new components text
Ensure consistent capitalization
=> feat(quick-assess): fix Quick Assess capitalization

src/DetailsView/components/quick-assess-to-assessment-dialog.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/quick-assess-to-assessment-dialog.test.tsx.snap
This PR updates the title and button text in the QuickAssessToAssessmentDialog to capitalize "Assessment" for consistency
Similar to #6397 
=> feat(quick-assess): Update text capitalization in QuickAssessToAssessmentDialog

src/NOTICE.html
Updates generated NOTICE.html for 2.37.3 by:
* Starting from generated notice from private #20230208.2 CI build
* manually adding the one missing package from the build (http-cache-semantics 4.1.1)
compiance requirement
n/a
=> chore: update NOTICE.html for 2.37.3 release

packages/ui/package.json
Bumping minor version of the ui package from 0.2.1 to 0.3.0 in preparation for release
Keep in sync with recent Web release (2.37.3)
=> chore: bump ui package from 0.2.1 to 0.3.0 for release

src/common/feature-flags.ts, src/tests/unit/tests/background/feature-flags.test.ts
Create feature flag for working on an Automated checks experience for Assessment and Quick Assess that is similar to the Automated checks experience of FastPass
=> feat(automated-checks): add hidden feature flag for new Automated checks experience

packages/report/package.json
Bump the patch version to force a pipeline run
Routine validation step after secrets rotation
=> chore: Bump patch version to validate secret rotation

src/common/feature-flags.ts, src/tests/unit/tests/background/feature-flags.test.ts
Turn on Automated checks feature flag by default
=> feat(automated-checks): enable automated checks feature flag

packages/ui/package.json
Bumping minor version of the ui package from 0.3.0 to 0.4.0 in preparation for release
Keep in sync with upcoming Web 2.38.x release
=> chore: bump ui package from 0.3.0 to 0.4.0 for upcoming release

src/NOTICE.html
Similar to #6417, updating NOTICE file with generated notice from private build ([20230327.1]). However, there were no missing components mentioned.
Compliance
=> chore: update notice for release 2.38.0

src/DetailsView/components/details-view-content.tsx, src/DetailsView/details-view-initializer.ts, src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap, src/tests/unit/tests/DetailsView/details-view-content.test.tsx
Needs review card view data was not being calculated correctly, this fixes that. Also improves tests to catch this issue if it were to happen again. 
Feature work.
n/a
=> fix(automated-checks): needs review data missing in details view

packages/report/package.json
Routine version bump to validate rotated publishing token
Complete secrets rotation
=> chore: Bump report version to validate secret rotation

packages/report-e2e-tests/src/examples/axe-results-with-issues.snap.html, packages/report-e2e-tests/src/examples/axe-results-without-issues.snap.html, packages/report-e2e-tests/src/examples/combined-results-with-baseline-aware-issues.snap.html, packages/report-e2e-tests/src/examples/combined-results-with-issues.snap.html, packages/report-e2e-tests/src/examples/combined-results-without-issues.snap.html, packages/report-e2e-tests/src/examples/summary-scan-with-issues.snap.html, packages/report-e2e-tests/src/examples/summary-scan-without-issues.snap.html, src/common/components/cards/card-footer-instance-action-buttons.scss
Some HC issues with the kebab menu are called out in #6013. Basically, the kebab menu isn't obviously a button on hover because its appearance doesn't provide enough visual feedback. To fix this, we add a border around the button on hover. When #6013 was filed, the kebab icon color changed on hover, although sometimes the change was very subtle. A subsequent change apparently removed even that subtle change, completely removing any hover from the kebab menu.
Address #6013
State | Before change | After change
No HC mode, no hover | ![image](https://user-images.githubusercontent.com/45672944/234135324-0a1e9e7e-443f-478d-aa74-53e023c0abf2.png) | ![image](https://user-images.githubusercontent.com/45672944/234134248-cac03e00-84cb-4eb6-b093-c621b162e91d.png)
No HC mode, with …
=> fix: Add a border to kebab menu icon on hover

packages/report/package.json
Bump package version to validate that we've fixed the problem that prevented the ADO extension from consuming the previous version (see #6610)
Broken pipelines are bad
=> chore: Bump report package version

README.md
This PR updates the project readme to include a deprecation notice for the Android project, consistent with our intent to shut it down.
Part of [Feature 2044298](https://mseng.visualstudio.com/1ES/_workitems/edit/2044298) (internal access required to view).
=> feat(android-deprecation): Add deprecation notice to readme

packages/report/package.json
The report version was bumped according to what the previous axe-core update feature did but apparently pinning to the axe-core version isn't necessary or desirable so we will only make a minor version bump.
feature work
=> feat(axe-core-4.7): Update report version to be only a minor version change

packages/report/package.json
Bump the package version to validate secret rotation
Validate secret (had to rotate twice to an error)
=> chore: Bump package version to validate secret

pipeline/e2e-test-from-agent.yaml
A recent change (probably #6980) caused the reliability tests to fail completely on Windows and Mac systems. The error was as follows:
```
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     yarn playwright install                                             ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
```
This change simply adds `yarn playwright …
=> fix: Install playwright in reliability tests

src/injected/client-init.ts, tools/strict-null-checks/convert-to-exclude.js, tools/strict-null-checks/eligible-file-finder.js, tools/strict-null-checks/progress.js
This PR introduces a minor performance improvement by running the functions concurrently using `Promise.all`, which also enhances the efficient utilization of hardware resources.
This change addresses a performance enhancement to utilize concurrency and improve resource utilization.
N/A
- [n/a] Addresses an existing issue: N/A
- [n.a] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
=> chore: Optimizing Performance and Resource Utilization with Concurrent Function Execution

src/assessments/repetitive-content/test-steps/consistent-help.tsx, src/content/test/pointer-motion/target-size.tsx, src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap
This PR makes small tweaks to wording and adds in an additional note based on final copy of the documentation.
feature work
=> feat(wcag-2-2): Adjust wording in Target Size and Consistent Help requirements

packages/report/package.json
This is to validate the release secret update
Quarterly rotation; standard
=> Update report version to validate npm secret change

package.json, src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-content-with-local-state.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/export-dialog.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/export-dropdown.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/failure-instance-panel-control.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/failure-instance-panel-details.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/fluent-side-nav.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/generic-dialog.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/generic-panel.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/generic-toggle.test.tsx.snap, src/tests/unit/tests/DetailsView/components/details-view-content-with-local-state.test.tsx, src/tests/unit/tests/DetailsView/components/export-dialog.test.tsx, src/tests/unit/tests/DetailsView/components/export-dropdown.test.tsx, src/tests/unit/tests/DetailsView/components/failure-instance-panel-control.test.tsx, src/tests/unit/tests/DetailsView/components/failure-instance-panel-details.test.tsx, src/tests/unit/tests/DetailsView/components/fluent-side-nav.test.tsx, src/tests/unit/tests/DetailsView/components/generic-dialog.test.tsx, src/tests/unit/tests/DetailsView/components/generic-panel.test.tsx, src/tests/unit/tests/DetailsView/components/generic-toggle.test.tsx, yarn.lock
Enzyme replacement in test files.
enzyme replacement in files under /src/tests/unit/tests/DetailsView/components/
All changes are done in test files only and snapshots are updated.
details-view-command-bar.test.tsx: We will raise this file in part 3 feature PRs.
=> chore: Enzyme replacement in test files- PR 2 of 6 for part 2 of 3

src/tests/unit/tests/injected/__snapshots__/layered-details-dialog-component.test.tsx.snap, src/tests/unit/tests/injected/components/__snapshots__/command-bar.test.tsx.snap, src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap, src/tests/unit/tests/injected/components/__snapshots__/fix-instruction-panel.test.tsx.snap, src/tests/unit/tests/injected/components/__snapshots__/issue-details-navigation-controls.test.tsx.snap, src/tests/unit/tests/injected/components/command-bar.test.tsx, src/tests/unit/tests/injected/components/details-dialog.test.tsx, src/tests/unit/tests/injected/components/fix-instruction-panel.test.tsx, src/tests/unit/tests/injected/components/issue-details-navigation-controls.test.tsx, src/tests/unit/tests/injected/layered-details-dialog-component.test.tsx, src/tests/unit/tests/injected/visualization/__snapshots__/highlight-box.test.tsx.snap, src/tests/unit/tests/injected/visualization/highlight-box.test.tsx, src/tests/unit/tests/issue-filing/components/__snapshots__/issue-filing-option-choice-group.test.tsx.snap, src/tests/unit/tests/issue-filing/components/__snapshots__/issue-filing-settings-container.test.tsx.snap, src/tests/unit/tests/issue-filing/components/issue-filing-option-choice-group.test.tsx, src/tests/unit/tests/issue-filing/components/issue-filing-settings-container.test.tsx, src/tests/unit/tests/issue-filing/services/azure-boards/__snapshots__/azure-boards-settings-form.test.tsx.snap, src/tests/unit/tests/issue-filing/services/azure-boards/azure-boards-settings-form.test.tsx, src/tests/unit/tests/issue-filing/services/github/__snapshots__/github-issue-filing-service.test.tsx.snap, src/tests/unit/tests/issue-filing/services/github/github-issue-filing-service.test.tsx, src/tests/unit/tests/issue-filing/services/null-issue-filing-service/__snapshots__/null-issue-filing-service.test.tsx.snap, src/tests/unit/tests/issue-filing/services/null-issue-filing-service/null-issue-filing-service.test.tsx, src/tests/unit/tests/packages/accessibility-insights-ui/__snapshots__/ui-factory.test.tsx.snap, src/tests/unit/tests/packages/accessibility-insights-ui/ui-factory.test.tsx, src/tests/unit/tests/popup/components/__snapshots__/ad-hoc-tools-panel.test.tsx.snap, src/tests/unit/tests/popup/components/ad-hoc-tools-panel.test.tsx
Replacement of Enzyme in files under src/tests/unit/tests/
Existing UserStory : [User Story 2142858](https://dev.azure.com/mseng/1ES/_workitems/edit/2142858): Enzyme replacement in files under src/tests/unit/tests/injected
Replaced the use of Enzyme in the below files:
src/tests/unit/tests/injected/components/command-bar.test.tsx
src/tests/unit/tests/injected/components/fix-instruction-panel.test.tsx
src/tests/unit/tests/injected/components/issue-details-navigation-controls.test.tsx
src/tests/unit/tests/injected/layered-details-dialog-component.test.tsx
src/tests/unit/tests/issue-filing/components/issue-filing-option-choice-group.test.tsx
src/tests/unit/tests/issue-filing/components/issue-filing-settings-container.test.tsx
src/tests/unit/tests/issue-filing/services/azure-boards/azure-board …
=> chore: Enzyme replacement in test files- PR 6 of 6 for part 3 of 3

packages/report/package.json
Update package version for accessibility insights report for axe-core release. Please refer #7274
=> chore: update report package version for axe-core release

package.json, packages/report/package.json, src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap, src/tests/unit/tests/scanner/__snapshots__/get-rule-inclusions.test.ts.snap, yarn.lock
This PR upgrades axe-core to 4.10.2
Updating axe-core version from 4.9.1 to 4.10.2
=> chore: Update axe core version to 4.10.2

packages/report/package.json
Updating report package to new version as axe-core latest version is merged.
=> feat: Update report package to 5.2.0 as new version of axe-core is updated to latest version

src/DetailsView/components/details-view-command-bar.scss, src/DetailsView/components/details-view-command-bar.tsx, src/DetailsView/components/save-assessment-button.tsx, src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap, src/tests/unit/tests/DetailsView/components/__snapshots__/save-assessment-button.test.tsx.snap, src/tests/unit/tests/DetailsView/components/save-assessment-button.test.tsx
GitHub issue: https://github.com/microsoft/accessibility-insights-web/issues/7514
=> Solution for Button navigation inconsistent GitHub issue
