microsoft/accessibility-insights-web

src/assessments/images/test-steps/image-function.tsx
src/assessments/images/test-steps/images-of-text.tsx
src/assessments/images/test-steps/text-alternative.tsx
src/assessments/links/test-steps/link-function.tsx
src/assessments/links/test-steps/link-purpose.tsx
src/assessments/native-widgets/test-steps/widget-function.tsx
src/common/types/property-bag/iimage-function.d.ts
src/common/types/property-bag/iimage-of-text.d.ts
src/common/types/property-bag/ilink-function.d.ts
src/common/types/property-bag/ilink-purpose.d.ts
src/common/types/property-bag/itext-alternative.d.ts
src/common/types/property-bag/iwidget-function.d.ts

Removed the prefixed `I` from interface names that previously used `// tslint:disable-next-line:interface-name` to pass tslint checks.
Second part of refactoring for interface names

tslint remove disable interface name 2

---

tsconfig.json

Adds `forceConsistentCasingInFileNames` parameter in `tsconfig` to make sure the file name casing problems are caught during build times (at least for TS files).
Till the time we actually setup an Linux environment to run our checks and build checks, this will at least prevent any TS errors due to the casing errors in Linux. Let me know if this will work or not.

[Refactor] force case sensitive imports from tsconfig

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

While we have our code of conduct and contribution information in our README, GitHub's community profile doesn't detect it unless it's in a separate file (see [How to add Code of Conduct to repo](https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-manually), [How to add contribution guidelines](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors)).

Adding Code of Conduct and Contributing MD files

---

src/tests/end-to-end/common/browser.ts

Running `mpn run test:e2e` throws an error on *Settings Dropdown* e2e test. The error comes from a wrong casing on a file path.
**N/A**

Fix casing to fix e2e test on linux

---

src/tests/unit/tests/injected/visualization/drawer-utils.test.ts

🔧 drawer-util.test.ts to actually return proper element to fix lint error and also remove tslint:disable
Carry over work from #375

[Refactor] drawer util test to return proper element

---

src/assessments/common/property-bag-column-renderer.tsx
src/assessments/custom-widgets/test-steps/cues.tsx
src/assessments/custom-widgets/test-steps/design-pattern.tsx
src/assessments/custom-widgets/test-steps/instructions.tsx
src/assessments/custom-widgets/test-steps/keyboard-interaction.tsx
src/assessments/custom-widgets/test-steps/label.tsx
src/assessments/custom-widgets/test-steps/role-state-property.tsx
src/assessments/images/test-steps/image-function.tsx
src/assessments/images/test-steps/images-of-text.tsx
src/assessments/images/test-steps/text-alternative.tsx
src/assessments/links/test-steps/link-function.tsx
src/assessments/links/test-steps/link-purpose.tsx
src/assessments/native-widgets/test-steps/cues.tsx
src/assessments/native-widgets/test-steps/instructions.tsx
src/assessments/native-widgets/test-steps/label.tsx
src/assessments/native-widgets/test-steps/widget-function.tsx
src/assessments/text-legibility/test-steps/contrast.tsx

Replaced all instances of the hyphen character `'-'` in column default values with `'(no value)'`. Created a string constant for holding the default.
Tested with NVDA - reads "NO VALUE"
Tested with JAWS - reads "left paren - NO VALUE - right paren"

Changed default values in columns from hyphen to "(no value)" for better accessibility

---

src/tests/unit/common/visual-helper-toggle-config-builder.ts
src/tests/unit/common/visualization-toggle-props-builder.ts
src/tests/unit/tests/DetailsView/components/assessment-visualization-enabled-toggle.test.tsx
src/tests/unit/tests/DetailsView/components/restart-scan-visual-helper-toggle.test.tsx
src/tests/unit/tests/assessments/automated-checks/automated-checks-visualization-toggle.test.tsx

Wallaby complains with warnings when test files import other test files, since it causes it to double-run tests. This fixes the existing cases of these warnings by extracting the common test helpers into their own files.

Move common test helper code out of individual test files

---

src/DetailsView/Styles/detailsview.scss

Added background color to Failure Details. One-line change to CSS.
The change is subtle but was requested by design. I also revised the padding and margins to match the figma.

Changed failure details background color to $neutral-2

---

src/tests/unit/tests/background/__snapshots__/initial-assessment-store-data-generator.test.ts.snap
src/tests/unit/tests/background/initial-assessment-store-data-generator.test.ts

This cleans up the `initial-assessment-store-data-generator` tests to
* use more descriptive test names
* use current snapshotting practices
* use `.each` where appropriate
* make helper variable setup less verbose
* move setup data specific and relevant to individual test cases into those test cases
* use ManualTestStatus enums instead of magic integers
I'll be adding some new test cases as part of the #390 fixes and wanted to do that separately from refactoring the existing ones. Some of the cases reveal that the existing product logic is kind of questionable (eg, the allowances for null/undefined/{} data are not consistent between different properties), but I wanted to keep this PR strictly to refactoring the tests, and leave improving the actual generator logic for a separate PR.

Refactor initial assessment store data generator tests

---

src/DetailsView/components/left-nav/left-nav-link-builder.tsx
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/left-nav-link-builder.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx

instead of saying '14 images failed', now we say: 

BugFix - update the nav link tootip

---

webpack.config.js

- [n/a] Ran precheckin (`npm run precheckin`)
The source maps in the dev environment do not work due to a change made in chrome.
Issue discussing this on webpack: https://github.com/webpack/webpack/issues/8506
Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=919575
This will increase our dev deployment sizes but I think it is worth the benefit to be able to debug when needed in dev environment.
The specific option was chosen due to the webpack config documentation stating this:
> …

Fix source maps in dev tool by using eval-source-map option in webpack

---

src/DetailsView/Styles/detailsview.scss

With new chrome (73 & above) the details view page was behaving weird on scroll. Check the attached Gif for current behavior.
Fixed it by adding a max-height to the `issue-details-dialog-container`

fix vertical scroll on the assessment panel

---

src/tests/end-to-end/common/browser-factory.ts

Added '--no-sandbox' to chrome options. This will fix the issue we currently have, see http://chromedriver.chromium.org/help/chrome-doesn-t-start
However, I'm not sure if this introduces extra vulnerability into our e2e tests. 
Let me know your thoughts on this.

[BugFix] disable sandbox to avoid chromium crash when launch e2e test

---

src/DetailsView/reports/components/outcome.scss

make changes to the tag styling so that: 
1. The tag with the X needs to be the ****same size**** of the tag that has the number and
2. it has to have ****even spacing**** around the “x”

[bugfix] Fix the style for err tag

---

src/DetailsView/Styles/detailsview.scss

1) There should be a ****margin of 16px (at least)****, with all items aligned with one another on the right and left. The list of test items and the settings gear in the upper right appear to have the correct margins.
2) Command bar should be white with a ****1px box shadow on the bottom**** rgba (0,0,0,0.8)

BugFix: command bar styling refine

---

src/background/actions/action-creator.ts
src/common/message-creators/base-action-message-creator.ts
src/tests/unit/tests/background/actions/action-creator.test.ts

The double telemetry happen for `Message.Telemetry.Send` message. The reason simply being: both `GlobalActionCreator` and `ActionCreator` were registering a listener for this message (and of course, sending the telemetry on the listener).
This bug affected the following telemetry events:
- contentPageOpened
- contentHyperLinkOpened
- ExportResults (this is the one mentioned on the bug)
- DetailsViewOpened
- FileIssueClick
- IssuesDialogOpened
- CopyIssueDetails
- TutorialOpen
- PopupInitialized
- LaunchPanelOpen
I validated all this events to not be duplicated anymore.
**N/A**

Remove double register for SEND_TELEMETRY message

---

tslint.json

Remove `max-line-length: 140` rule from `tslint.json`
The basic idea of adding that rule is to make sure that we dont get lines of code which are above 140 but since we have already automated that process by `autoFormat` from `prettier` with `printWidth` as 140 and also we added a vscode ruler which marks our lines to be at 140 for visual guidance to contributors.
So, it makes sense to get rid of this rule from tslint file.
Let me know what you guys think.

[Cleanup - TSLint] Remove max length TSLint rule in favor of prettier

---

src/popup/scripts/components/telemetry-permission-dialog.tsx
src/tests/end-to-end/tests/popup/__snapshots__/first-time-dialog.test.ts.snap
src/tests/unit/tests/popup/scripts/components/__snapshots__/telemetry-permission-dialog.test.tsx.snap

The message has invalid HTML where a P tag is contained in another P tag. I changed the outermost P to a DIV. No user-perceivable change in screenshot.
Just markup and snapshots.

Changed container for telemetry message from P to DIV

---

src/assessments/assessment-builder.tsx
src/common/components/with-store-subscription.tsx
src/tests/unit/common/base-data-builder.ts
tslint.build-enforced.json
tslint.json

Removes remaning `no-typedef` lint errors
There are 2 peculiar cases in this PR:
- base-data-builder.ts : that class is abstract and has a function `with`, where if I specify `BaseDataBuilder<T>` as return type; a lot of other tests start to fail. So,
- First way of fixing is to keep the class abstract and specify `this` as return type
- Second is to make it a normal class and then add `BaseDataBuilder<T>` as its return type. This option builds and compiles the code at the moment but then with newer version of TS(3.3.3), gives an error.
I chose the first one as the simpler fix. Open to change if someone knows what is the significance of `abstract` in that class and is it safe to remove it.
- ~with-store-subscription.tsx: the function `withStoreSubscription` returns anonymous class which I …

[TSLint] Final no-typedef fixes

---

src/background/actions/action-creator.ts
src/tests/unit/tests/background/actions/action-creator.test.ts

removed telemetry events 'enable visual helper'
Confirmed with Fer,  this telemetry is misleading and we just want to get rid of it.

[Bug]remove telemetry for enable visual helper

---

.vscode/settings.json

Adding setting to ensure vscode is using typescript from node_modules not from global instalation.

Typescript version on vscode

---

src/tests/unit/common/is-function.ts
src/tests/unit/common/it-is-function.ts
src/tests/unit/tests/background/injector-controller.test.ts
src/tests/unit/tests/background/scanner-utility.test.ts
src/tests/unit/tests/common/components/toast.test.tsx
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
src/tests/unit/tests/injected/instance-visibility-checker.test.ts
src/tests/unit/tests/injected/scoping-listener.test.ts
src/tests/unit/tests/injected/visualization/drawer.test.ts
src/tests/unit/tests/popup/support-link-handler.test.ts

SDT build is flagging our mock setup for `setTimeout` because we're using `It.is(isFunction)` which has a return type of any making tslint to flag this uses. 
On this PR I'm adding a wrapper to check the `setTimeout` parameter is a function and make this wrapper to return type of `Function`.

tslint rule no-string-based-set-*

---

src/DetailsView/Styles/detailsview.scss

Bug fix for remaining fix on WI 1421040 where the settings gear drop down was not aligned to Start over button. Aligning that button.
Production:
With new change:

[Bug] update app bar styling and finish

---

src/common/indexedDB/idb.ts

Adds reference and a comment to why we are not able to use `idb-keyval` package and have to rely on the code rather than the package.
- [n/a] Ran precheckin (`npm run precheckin`)

add reference to the bug that prevents us from using idb-keyval package

---

src/bug-filing/bug-filing-service-provider-impl.ts
src/bug-filing/null-issue-filing-service/null-issue-filing-service.tsx
src/bug-filing/types/bug-filing-service.ts
src/tests/unit/tests/bug-filing/github/github-bug-filing-service.test.tsx
src/tests/unit/tests/bug-filing/null-issue-filing-service/__snapshots__/null-issue-filing-service.test.tsx.snap
src/tests/unit/tests/bug-filing/null-issue-filing-service/null-issue-filing-service.test.tsx

Introduce NullObject for our bug filing services
Small refactor to the provider to add a `register` public api.

Introduce null object for issue filing service

---

src/DetailsView/components/issue-filing-dialog.tsx
src/bug-filing/bug-filing-service-provider.ts
src/bug-filing/components/bug-filing-settings-container.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
src/tests/unit/tests/bug-filing/bug-filing-service-provider.test.ts
src/tests/unit/tests/bug-filing/components/__snapshots__/bug-filing-settings-container.test.tsx.snap
src/tests/unit/tests/bug-filing/components/bug-filing-settings-container.test.tsx

Title says it all. Two main changes here: bug filing setting container uses bug service provider to get all visible services (new change) and then using the container in the issue filing dialog.

BugFilingSettingContainer gets visible services + issue filing dialog uses bug filing setting container

---

src/injected/analyzers/base-analyzer.ts
src/tests/unit/tests/injected/analyzers/base-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts

Remove "duplicated" type for the messages we send to the background from the analyzers. Using `Message` from `src\common\message.ts` file.
Beside running **precheckin**, manually test all the adhoc tools are working. Also check automated checks, landmarks and headings on Assessment.
Related PR: #534

Using proper Message type

---

src/content/test/headings/guidance.tsx

In reference to #520; since that rule is a best practice. Removing the guidance for `only one h1 element`.

remove guidance for heading best practice rule

---

src/tests/unit/tests/DetailsView/components/bug-button.test.tsx
src/tests/unit/tests/DetailsView/components/details-view-right-panel.test.tsx
src/tests/unit/tests/DetailsView/components/issues-table-handler.test.tsx
src/tests/unit/tests/DetailsView/components/issues-table.test.tsx
src/tests/unit/tests/DetailsView/details-view-renderer.test.tsx
src/tests/unit/tests/DetailsView/reports/report-generator.test.ts
src/tests/unit/tests/assessments/assessment-builder.test.tsx
src/tests/unit/tests/background/completed-test-step-telemetry-creator.test.ts
src/tests/unit/tests/background/dev-tools-listener.test.ts
src/tests/unit/tests/background/feature-flags-controller.test.ts
src/tests/unit/tests/background/stores/assessment-store.test.ts
src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts
src/tests/unit/tests/background/tab-controller.test.ts
src/tests/unit/tests/background/telemetry/null-telemetry-client.test.ts
src/tests/unit/tests/bug-filing/components/bug-filing-option-choice-group.test.tsx
src/tests/unit/tests/common/components/visualization-toggle.test.tsx
src/tests/unit/tests/common/components/with-store-subscription.test.tsx
src/tests/unit/tests/common/file-issue-details-handler.test.ts
src/tests/unit/tests/injected/analyzer-controller.test.ts
src/tests/unit/tests/injected/details-dialog-handler.test.ts

Clean up unused variables/imports. General idea is finish the clean up and then enable `noUnusedParameters` & `noUnusedLocals`  options on tsconfig.json

Clean up unused variables/imports - Part 2

---

src/DetailsView/details-view-container.tsx
src/bug-filing/azure-devops/azure-devops-bug-filing-service.tsx
src/bug-filing/components/bug-filing-settings-container.tsx
src/bug-filing/github/github-bug-filing-service.tsx
src/bug-filing/null-issue-filing-service/null-issue-filing-service.tsx
src/bug-filing/types/bug-filing-service.ts
src/common/types/store-data/user-configuration-store.ts
src/injected/details-dialog-handler.ts
src/tests/unit/tests/DetailsView/details-view-container.test.tsx
src/tests/unit/tests/bug-filing/azure-devops/__snapshots__/azure-devops-bug-filing-service.test.tsx.snap
src/tests/unit/tests/bug-filing/azure-devops/azure-devops-bug-filing-service.test.tsx
src/tests/unit/tests/bug-filing/components/__snapshots__/bug-filing-settings-container.test.tsx.snap
src/tests/unit/tests/bug-filing/components/bug-filing-settings-container.test.tsx
src/tests/unit/tests/bug-filing/github/github-bug-filing-service.test.tsx
src/tests/unit/tests/bug-filing/null-issue-filing-service/null-issue-filing-service.test.tsx

Mainly about adding a new service option for azure dev ops. Also re-factoring to add a "get" API to services (and respective tests).
The properties for ADO are from the UI.

Added Azure DevOps bug filing service + minor refactors

---

src/background/message-distributor.ts
src/common/components/collapsible-component.tsx
src/common/components/file-issue-details-button.tsx
src/common/components/selector-input-list.tsx
src/common/file-issue-details-handler.ts
src/content/settings/improve-accessibility-insights.tsx
src/injected/components/fix-instruction-panel.tsx
src/injected/details-dialog-handler.ts
src/injected/element-finder-by-position.ts
src/injected/visualization/drawer-utils.ts
src/popup/components/header-contextual-menu.tsx
src/scanner/help-url-getter.ts
src/tests/unit/tests/DetailsView/components/assessment-instance-table.test.tsx
src/tests/unit/tests/DetailsView/components/assessment-table-column-config-handler.test.tsx
src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
src/tests/unit/tests/background/message-distributor.test.ts
src/tests/unit/tests/bug-filing/bug-filing-service-provider.test.ts
src/tests/unit/tests/common/components/issue-filing-button.test.tsx

Clean up unused variables/imports. General idea is finish the clean up and then enable `noUnusedParameters` & `noUnusedLocals`  options on tsconfig.json

Clean up unused variables/imports - Part 4

---

src/bug-filing/common/get-issue-details-markdown.ts
src/bug-filing/github/create-github-bug-filing-url.ts
src/tests/unit/tests/bug-filing/common/__snapshots__/get-issue-details-markdown.test.ts.snap
src/tests/unit/tests/bug-filing/common/get-issue-details-markdown.test.ts
src/tests/unit/tests/bug-filing/github/__snapshots__/create-github-bug-filing-url.test.ts.snap
src/tests/unit/tests/bug-filing/github/create-github-bug-filing-url.test.ts

The markdown we get from `buildGithubText` is not for github only, we are going to use the same markdown for Azure Boards.
In this PR:
- Extract `buildGithubText` to it's own file
- Add unit tests for the new function
- Update `src\bug-filing\github\create-github-bug-filing-url.ts` (and the related tests) to use the new function

[Refactor] Extract buildGithubText

---

src/injected/analyzer-controller.ts
src/injected/frame-url-message-dispatcher.ts
src/injected/main-window-initializer.ts
src/tests/unit/tests/DetailsView/components/assessment-view.test.tsx
src/tests/unit/tests/DetailsView/components/test-step-view.test.tsx
src/tests/unit/tests/injected/analyzer-controller.test.ts
src/tests/unit/tests/injected/frame-url-message-dispatcher.test.ts
tslint.json

Clean up unused variables/imports. General idea is finish the clean up and then enable `noUnusedParameters` & `noUnusedLocals`  options on tsconfig.json
At this point, we're able to temporary enable 'no-unused-variables' tslint rule. This rule is deprecated so the end goal is to enable tsc check (mentioned before) but adding this rule will prevent us from adding more unused variables/imports.

Clean up unused variables/imports - Part 5

---

src/bug-filing/azure-boards/azure-boards-settings-form.tsx
src/tests/unit/tests/bug-filing/azure-boards/__snapshots__/azure-boards-settings-form.test.tsx.snap

Remove default option for azure boards settings, so that the store state is consistent with UI.

[Bug Fix] Remove default option for azure boards settings

---

src/DetailsView/Styles/detailsview.scss

Fix the wrap for visual helper text to make it look as per design, especially for smaller screens.
Look at the attached screenshot for more.

add wrap for visual helper text as per design

---

src/injected/styles/injected.scss

Without this change, if a target page styles all `button`s with a border, it applies to our content-script placed dialog when it shouldn't. In the pathological case outlined by #578, where the target page specifies a `button:hover` style with a larger border than the non-hover case, this can cause jerky/flashing reflows of the dialog layout.
This change:
* Suppresses border styling from applying to the dialog's buttons
* Slightly increases the minimum width of the dialog (520px to 550px), to make it less likely to see this sort of reflow in the case that a target page happens to introduce some other type of small width bump
**before:**
**after:**

fix: prevent target page button:hover borders from applying to injected dialog

---

src/common/styles/colors.scss

Went through all of the design specs @cheade sent over and verified the color palettes match our CSS. secondary-text was the only one in use that mismatched (the other updates bring the code in line with the palette but are all for cases that are not used anywhere in the product right now).
**Before**:
**After** (marginally lighter):

fix: update secondary-text color to match design palette

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/issue-filing-dialog.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap

Dialog component from office fabric use title and subtext (props you pass) as the outer most container div aria labeled by and described by elements through their ids, which normally are generated by office fabric.
Dialog component let you override those ids (so you can have your own css for example).
When overriding the ids, the outer most container doesn't use them, it still use the auto-generated id, meaning, they are referencing an element that doesn't exist and thus axe throws 2 invalid aria attribute values for the dialog.
In order to fix this, I remove the overriding ids and update our css to find the title and text by already existing classes from office fabric.

Fix a11y issue on issue filing setting dialog

---

src/DetailsView/details-view-initializer.ts
src/common/message-creators/dropdown-action-message-creator.ts
src/popup/popup-initializer.ts
src/tests/unit/tests/common/message-creators/dropdown-action-message-creator.test.ts

Refactor ContentActionMessageCreator to use ActionMessageDispatcher
Some minor cleanup

[Refactor] DropdownActionMessageCreator to use ActionMessageDispatcher

---

src/DetailsView/Styles/detailsview.scss

Reduce padding top for help section on overview page. 
Doing this by removing `margin-block-start of 1em` that turns to be added 17px.

fix: reduce padding top for help section on overview page

---

src/tests/unit/tests/DetailsView/components/__snapshots__/restart-scan-visual-helper-toggle.test.tsx.snap
src/tests/unit/tests/DetailsView/components/restart-scan-visual-helper-toggle.test.tsx
src/tests/unit/tests/assessments/automated-checks/__snapshots__/automated-checks-visualization-toggle.test.tsx.snap
src/tests/unit/tests/assessments/automated-checks/automated-checks-visualization-toggle.test.tsx

Refactor some tests to rather match snapshots instead of checking for text of an element directly.

refactor: add snapshot testing to some visual helper toggle tests

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
src/assessments/custom-widgets/test-steps/cues.tsx
src/assessments/custom-widgets/test-steps/role-state-property.tsx
src/assessments/native-widgets/test-steps/cues.tsx
src/assessments/parsing/test-steps/parsing.tsx
src/assessments/repetitive-content/test-steps/consistent-identification.tsx
src/assessments/semantics/test-steps/data-tables.tsx
src/assessments/semantics/test-steps/emphasis.tsx
src/assessments/semantics/test-steps/letter-spacing.tsx
src/assessments/semantics/test-steps/lists.tsx
src/assessments/semantics/test-steps/quotes.tsx
src/assessments/sequence/test-steps/columns.tsx
src/assessments/sequence/test-steps/css-positioning.tsx
src/assessments/sequence/test-steps/layout-tables.tsx
src/assessments/text-legibility/test-steps/high-contrast-mode.tsx
src/assessments/text-legibility/test-steps/resize-text.tsx
src/common/constants/displayable-strings.ts
src/common/navigator-utils.ts
src/content/test/parsing/keyboard-bookmarklet-instructions.tsx
src/injected/components/details-dialog.tsx
src/tests/unit/tests/common/navigator-utils.test.ts
src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
src/tests/unit/tests/popup/components/__snapshots__/popup-view.test.tsx.snap

- Update references to Chrome in README, the bug report template, How to Test text, bookmarklet instructions, the details dialog, the file URL permission error,
bug descriptions, and export reports to reflect that our extension can run in Edge Insider as well as Chrome.

Update references to Chrome to reflect Edge Insider

---

src/assessments/text-legibility/test-steps/high-contrast-mode.tsx
src/common/navigator-utils.ts
src/content/test/parsing/keyboard-bookmarklet-instructions.tsx
src/tests/unit/tests/common/navigator-utils.test.ts

Following Microsoft brand guidance, change user-visible references to the browser from "Edge" to "Microsoft Edge"

Use "Microsoft Edge" not "Edge" in visible text

---

src/injected/main-window-initializer.ts
src/injected/target-page-action-message-creator.ts
src/tests/unit/tests/injected/target-page-action-message-creator.test.ts

- Updated `TargetPageActionMessageCreator` to use `ActionMessageDispatcher` instead of extending from `BaseActionMessageCreator`
- Added a unit test for `copyIssueDetailsClicked` in `target-page-action-message-creator.test.ts` to improve code coverage

[Refactor] TargetPageActionMessageCreator to use ActionMessageDispatcher

---

src/DetailsView/details-view-initializer.ts
src/common/message-creators/scoping-action-message-creator.ts
src/injected/main-window-initializer.ts
src/tests/unit/tests/common/message-creators/scoping-action-message-creator.test.ts

- Modified `ScopingActionMessageCreator` to use `ActionMessageDispatcher` instead of extending `BaseActionMessageCreator`
- Updated relevant unit tests

[Refactor] ScopingActionMessageCreator to use ActionMessageDispatcher

---

src/background/global-action-creators/global-action-creator.ts
src/background/global-action-creators/user-configuration-action-creator.ts
src/background/global-context-factory.ts
src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts
src/tests/unit/tests/background/global-action-creators/user-configuration-action-creator.test.ts

Move GlobalActionCreator to it's own folder.
Move all user configuration related code on the GlobalActionCreator to the new UserConfigurationActionCreator.

[Refactor] Move global action creator to it's own folder

---

src/common/components/issue-filing-button.tsx
src/common/message-creators/bug-action-message-creator.ts
src/common/telemetry-data-factory.ts
src/common/telemetry-events.ts
src/tests/unit/tests/common/message-creators/bug-action-message-creator.test.ts
src/tests/unit/tests/issue-filing/issue-filing-service-provider-impl.test.ts

Remove `FileIssueClickService`, using `string` instead. The main reason to do this is we are not getting any value from the custom type. Also, if we were to properly use it, every time someone adds a new issue filing service this will be one more place to change.
Also, add test to make sure the key that identify each issue filing service is unique.

Remove unneded type

---

src/DetailsView/components/issue-filing-dialog.tsx
src/background/actions/action-payloads.ts
src/background/background-init.ts
src/background/global-action-creators/issue-filing-action-creator.ts
src/background/global-context-factory.ts
src/common/components/issue-filing-button.tsx
src/common/message-creators/issue-filing-action-message-creator.ts
src/common/messages.ts
src/common/telemetry-data-factory.ts
src/issue-filing/common/issue-filing-controller-impl.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
src/tests/unit/tests/background/global-action-creators/issue-filing-action-creator.test.ts
src/tests/unit/tests/background/global-context-factory.test.ts
src/tests/unit/tests/common/components/__snapshots__/issue-filing-button.test.tsx.snap
src/tests/unit/tests/common/components/issue-filing-button.test.tsx
src/tests/unit/tests/common/message-creators/issue-filing-action-message-creator.test.ts
src/tests/unit/tests/common/telemetry-data-factory.test.ts
src/tests/unit/tests/issue-filing/common/issue-filing-controller-impl.test.ts

Refactor how we are handling 'file issue' button activation.
Currently, the button has a href property on it and also an onClick property (where we send telemetry).
Instead, the button should only send an action message to the background, which should send telemetry and handle the logic to file the issues against the proper service.
**Out of scope**
Cleaning up href usage on ActionAndCancelButtonsComponents, I'll have a separated PR for this clean up.

[Refactor] Issue filing handling

---

src/common/styles/colors.scss

Simply adding a variable in css for primary text in high contrast styles.
- [n/a] Ran precheckin (`npm run precheckin`)

Updated/added high contrast styling for primary text; fixes overview page high contrast issue

---

src/background/feature-flags-controller.ts
src/tests/unit/tests/background/feature-flags-controller.test.ts

Per user feedback, show feature flag values when enable/disable a feature instead of 'undefined'. Confirmed the UX with Fer.
Before:
After:

Show feature flag values when enable/disable feature

---

src/issue-filing/azure-boards/azure-boards-settings-form.tsx
src/tests/unit/tests/issue-filing/azure-boards/__snapshots__/azure-boards-settings-form.test.tsx.snap

Removed '(default)' to match the UX. Since currently, if the user has not set up issue filing service at all, we do not provide a default option. 
Before:
After:

Modify text on azure boards settings repro steps option

---

src/issue-filing/github/create-github-issue-filing-url.ts
src/issue-filing/github/github-url-rectifier.ts
src/tests/unit/tests/issue-filing/github/create-github-issue-filing-url.test.ts
src/tests/unit/tests/issue-filing/github/github-url-rectifier.test.ts

Re-adding some code to ensure the github url ends with `/issues`.
The main reason to do this is the difference in behaviors between the first and second versions of issue file: on the first version, we only ask the user to provider the repo url (without /issues) and we were appending the proper suffix, while the on second version we ask the user for the repo issues url (including /issues).
By updating the extension, and old version of the url will not work as of now. This small PR takes care of it while also supporting non-standard github urls (like in the case of github enterprise)
Original commit [here](https://github.com/Microsoft/accessibility-insights-web/pull/603/commits/f18746d82dba69727de966ee76d4db2567d2f779)

Add url rectifier to add /issues if the base url does not have it

---

src/DetailsView/components/switcher.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/switcher.test.tsx.snap
src/tests/unit/tests/DetailsView/components/switcher.test.tsx

Currently, the 'selected option' of the switcher does not change immediately after user input. It goes through our flux loop before updating the UI. This makes NVDA anoucing the option change incorrectly. 
Saved switcher state locally to fix the a11y issue.

[Bug Fix] Switcher change between Assessment and FastPass doesn't announce changes correctly

---

src/DetailsView/details-view-initializer.ts
src/common/message-creators/store-action-message-creator-factory.ts
src/common/message-creators/store-action-message-creator-impl.ts
src/injected/main-window-initializer.ts
src/popup/popup-initializer.ts
src/tests/unit/tests/common/message-creators/store-action-message-creator-factory.test.ts
src/tests/unit/tests/common/message-creators/store-action-message-creator.test.ts
src/views/insights/dependencies.ts

- StoreActionMessageCreatorImpl uses ActionMessageDispatcher instead of inheriting from BaseActionMessageCreator
- StoreActionMessageCreatorFactory functions updated to reflect changes in StoreActionMessageCreatorImpl constructor
- Various initializers updated to use the modified StoreActionMessageCreatorFactory and StoreActionMessageCreatorImpl constructors
- Updated relevant test cases

[Refactor] StoreActionMessageCreator to use ActionMessageDispatcher

---

src/background/background-init.ts
src/background/browser-adapter.ts
src/background/browser-adapters/storage-adapter.ts
src/background/global-context-factory.ts
src/background/install-data-generator.ts
src/background/stores/global/feature-flag-store.ts
src/background/stores/global/global-store-hub.ts
src/background/stores/global/launch-panel-store.ts
src/background/telemetry/telemetry-client-provider.ts
src/background/user-stored-data-cleaner.ts
src/tests/unit/tests/background/global-context-factory.test.ts
src/tests/unit/tests/background/install-data-generator.test.ts
src/tests/unit/tests/background/stores/global/feature-flag-store.test.ts
src/tests/unit/tests/background/stores/global/global-store-hub.test.ts
src/tests/unit/tests/background/stores/global/launch-panel-state-store.test.ts
src/tests/unit/tests/background/telemetry/telemetry-client-provider.test.ts
src/tests/unit/tests/background/user-stored-data-cleaner.test.ts

Currently, we use `BrowserAdapter` to encapsulate our access to the chrome API. Having the adapter is great as it place all `chrome.` calls in a single place. The down side of doing this is: our `BrowserAdapter` type expose 30 different functions. This means we have "user" classes that depend on `BrowesrAdapter` but hardly use 5 of this 30 functions. Additionally, by looking at who is using the adapter, how the adapter is being used and which underlying chrome API each function uses, is possible to see `BrowserAdapter` is not cohesive. In other words, `BrowserAdapter` breaks the [Interface Segregation Principle](https://hackernoon.com/interface-segregation-principle-bdf3f94f1d11).
This is a first step into breaking `BrowserAdapter` into smaller, more cohesive types. I started with the …

refactor: Introduce Storage Adapter

---

src/DetailsView/Styles/detailsview.scss

Fix the color-contrast issue on Visualization toggle state text when the toggle is in disabled state.

bug: fix color contrast a11y issue with disabled visualization toggle

---

src/background/background-init.ts
src/background/browser-adapter.ts
src/background/browser-adapters/commands-adapter.ts
src/background/chrome-command-handler.ts
src/background/global-action-creators/global-action-creator.ts
src/background/global-context-factory.ts
src/tests/unit/tests/background/chrome-command-handler.test.ts
src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts
src/tests/unit/tests/background/global-context-factory.test.ts

More breaking down `BrowserAdapter` type. In this PR:
- Introduce `CommandsAdapter` to wrap 2 commands related functions

refactor: introduce commands adapter

---

src/injected/analyzers/rule-analyzer.ts
src/injected/scanner-utils.ts
src/scanner/axe-options.ts
src/scanner/exposed-apis.ts
src/scanner/launcher.ts
src/scanner/scan-options.ts
src/scanner/scan-parameter-generator.ts
src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
src/tests/unit/tests/injected/scanner-utils.test.ts
src/tests/unit/tests/scanner/scan-parameter-generator.test.ts

Using madge, I found that our background files have quite a few circular dependencies. As such I'm removing a few in this PR.
Fix circular dependencies in our imports by extracting interfaces out to separate files.

refactor: Remove circular dependencies of imports relying on ScanOptions and AxeOptions

---

src/background/background-init.ts
src/background/chrome-command-handler.ts
src/common/url-validator.ts
src/popup/popup-init.ts
src/popup/target-tab-finder.ts
src/tests/unit/tests/background/chrome-command-handler.test.ts
src/tests/unit/tests/common/url-validator.test.ts
src/tests/unit/tests/popup/target-tab-finder.test.ts

Promote `browserAdapter` from function param to constructor param.
`browserAdapter` is a "precondition" for the `UrlValidator` to work and it should not be pass to the functions that use it as this reveals some implementation details the user class doesn't need to know. As a "precondition" it should be pass through the constructor as this more clearly inform how `browserAdapter` is actually being used inside `UrlValidator`

refactor: update url-validator constructor params

---

src/injected/layered-details-dialog-component.tsx
src/tests/unit/tests/injected/__snapshots__/layered-details-dialog-component.test.tsx.snap
src/tests/unit/tests/injected/layered-details-dialog-component.test.tsx

Refactor `LayeredDetailsDialogComponent`:
- Update test to use enzyme's `shallow` renderer function
- Update the component to be a `NamedSFC` instead of a `class` extending `React.Component`
- Update the component deps to be a type instead of an interface 

refactor: convert layered details dialog component to named sfc

---

src/background/issue-details-text-generator.ts
src/tests/unit/tests/background/issue-details-text-generator.test.ts

Remove text builder for git hub issues from old class (not really being used anymore)

refactor: remove git hub text generator

---

src/injected/details-dialog-handler.ts
src/injected/dialog-renderer.tsx
src/injected/visualization/drawer-provider.ts
src/injected/visualization/issues-formatter.ts
src/injected/window-initializer.ts
src/tests/unit/tests/injected/details-dialog-handler.test.ts
src/tests/unit/tests/injected/dialog-renderer.test.tsx
src/tests/unit/tests/injected/visualization/drawer-provider.test.ts
src/tests/unit/tests/injected/visualization/issues-formatter.test.ts

- Move `DetailsDialogHandler` instance creation closer to the composition root
- Change all the `DetailsDialog` mocks (used for testing `DetailsDialogHandler`) to be dynamic mocks and thus decoupling the test from its dependencies (I being doing some refactoring around the `DetailsDialog` and notice that some changes in this class break the tests for the handler too; this change on the mocks should break that dependency)

refactor: improve details dialog handler tests

---

src/DetailsView/components/issues-details-list.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/issues-details-list.test.tsx.snap
src/tests/unit/tests/DetailsView/components/issues-details-list.test.tsx

Update UI test to use snapshot test instead of "double accounting" test.
Some minor clean up on the tested class

refactor: update ui test to use snapshot

---

docs/git-branch-setup.md
src/assessments/custom-widgets/custom-widgets-column-renderer.tsx

Fixes typo as requested by #672 plus one extra typo spotted in `./docs/git-branch-setup.md`

Fix typo for #672 and fix typo in git-branch-setup.md

---

src/injected/components/details-dialog.tsx
src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
src/tests/unit/tests/injected/components/details-dialog.test.tsx

Currently, the issue details dialog doesn't show up if "Improve dialog styling" preview feature is enabled.
This PR fix the showing part.
Notes:
The dialog still have other issues but I'm not fixing those as part of this PR, only the showing part.
**Improved dialog styling = true**
**Improved dialog styling = false** (for comparison purposes only)

fix: issue details dialog on shadow dom

---

src/background/actions/scoping-panel-action-creator.ts
src/background/global-action-creators/global-action-creator.ts
src/background/global-action-creators/scoping-action-creator.ts
src/background/global-context-factory.ts
src/background/tab-context-factory.ts
src/tests/unit/tests/background/actions/scoping-panel-action-creator.test.ts
src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts
src/tests/unit/tests/background/global-action-creators/scoping-action-creator.test.ts

Move scoping related functionality out of the `GlobalActionCreator` and into the new `ScopingActionCreator`. Cleaning `GlobalActionCreator` so we get classes/objects that follow Single Responsibility Principle.

refactor: extract scoping action creator behavior

---

src/issue-filing/common/create-file-issue-handler.ts
src/issue-filing/common/issue-filing-controller-impl.ts
src/issue-filing/services/azure-boards/azure-boards-issue-filing-service.tsx
src/issue-filing/services/github/github-issue-filing-service.tsx
src/issue-filing/services/null-issue-filing-service/null-issue-filing-service.tsx
src/issue-filing/types/issue-filing-service.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
src/tests/unit/tests/DetailsView/components/settings-panel/settings/issue-filing/__snapshots__/issue-filing-settings.test.tsx.snap
src/tests/unit/tests/DetailsView/components/settings-panel/settings/issue-filing/issue-filing-settings.test.tsx
src/tests/unit/tests/common/components/issue-filing-button.test.tsx
src/tests/unit/tests/issue-filing/common/create-file-issue-handler.test.ts
src/tests/unit/tests/issue-filing/common/issue-filing-controller-impl.test.ts
src/tests/unit/tests/issue-filing/services/azure-boards/azure-boards-issue-filing-service.test.tsx
src/tests/unit/tests/issue-filing/services/github/__snapshots__/github-issue-filing-service.test.tsx.snap
src/tests/unit/tests/issue-filing/services/github/github-issue-filing-service.test.tsx
src/tests/unit/tests/issue-filing/services/null-issue-filing-service/null-issue-filing-service.test.tsx

As part of solving issue 588 (not linking so it doesn't get close automatically), I'm moving the responsibility of filing a bug from `IssueFilingControllerImpl` to each service. This way, we give each service the flexibility of filing issue as they need (as opposed to: each service file issues by generating a url which we -basically- use for an HTTP GET request). This way, we may be able to use HTTP POST request or not even HTTP request but system calls (like open notepad for example)

refactor: move file issue behavior to the service

---

yarn.lock

This is the result of running `yarn upgrade node-sass`. It fixes the `yarn audit` failure in node-sass -> ... -> node-tar path.
- **n/a** Addresses an existing issue
- **n/a** Added relevant unit test for your changes. (`npm run test`)
- **n/a** Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- **n/a** Ran precheckin (`npm run precheckin`)
- **n/a** (UI changes only) Added screenshots/GIFs to description above
- **n/a** (UI changes only) Verified usability with NVDA/JAWS

chore: fix yarn audit failures by upgrading node-sass to pull in node-tar@2.2.2

---

src/DetailsView/components/switcher.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/switcher.test.tsx.snap

- Changed ariaLabel in switcher to "select activity" instead of "select workflow"
- Updated corresponding snapshots

fix: updated aria label on switcher

---

src/DetailsView/components/switcher.tsx
src/tests/unit/tests/DetailsView/components/switcher.test.tsx

A change was made such that the state is being represented in the control instead of the props for the switcher. This was due to the nature of React Flux and how it works with accessibility concerns. However, a part was missed: when props are updated, the state should be updated (we have this in previous uses of the pattern). This is _that_ change.

fix: switcher state is updated correctly (on component did update)

---

src/DetailsView/components/static-content-details-view.tsx

There is a missing child deps type on `StaticContentDetailsViewDeps`.
This PR add the missing deps type.

refactor: add missing child deps type on parent deps type

---

src/common/components/header-icon.tsx
src/icons/brand/blue/brand-blue.tsx
src/tests/unit/tests/common/components/__snapshots__/header-icon.test.tsx.snap

We're currently using a `<img>` element with a `src` attribute and passing the path to the proper icon for the details view header icon (also on the insights guidance content).
We already have a white version of our heart as a react component (wrapping a svg version of the image).
On this PR:
- Add blue version of our heart
- Using both, blue and white, react components for the icons on the header
- there is no issue filed
- does not apply as it looks the same

refactor: header icon refactor

---

src/icons/brand/blue/brand-blue.tsx
src/icons/brand/white/brand-white.tsx

Explicitly making svg icons decorative images by adding role=image and aria-hidden=true
- not created

fix: make brand icons decorative images

---

src/common/feature-flags.ts
src/tests/unit/tests/background/feature-flags.test.ts

Add feature flag for the new automated checks report.
Notes: we do not intend to keep the new report behind a feature flag, the main purpose is to allow the feature crew to make incremental progress and check it to master without disrupting the current report. We'll remove the feature flag and the old report when we're done. This means, visible name and description of the feature flag does not need to be user-facing-perfect.

Add new feature flag for new automated checks report

---

src/ad-hoc-visualizations/color/visualization.tsx
src/ad-hoc-visualizations/headings/visualization.tsx
src/ad-hoc-visualizations/issues/visualization.tsx
src/ad-hoc-visualizations/landmarks/visualization.tsx
src/ad-hoc-visualizations/tab-stops/visualization.tsx
src/assessments/assessment-builder.tsx
src/assessments/keyboard-interaction/assessment.tsx
src/assessments/visible-focus-order/assessment.tsx
src/common/configs/assesssment-visualization-configuration.ts
src/common/configs/visualization-configuration.ts
src/tests/unit/tests/assessments/assessment-builder.test.tsx

This property is not being used anymore. It was abandoned in favor of `getAnalyzer` function and configuration per visualization/test

refactor: remove analyzerMessageType from VisualizationConfiguration

---

src/injected/styles/injected.scss

fabric.scss & Icons.Definition.scss adds font face defintions. We don't seem to be using them & the styling is not affected by removing these two files.
Updated playground extension with this change for validation

fix: prevent CSP errors in target page by removing fabric.scss dependency from injected content

---

src/tests/unit/tests/views/page/__snapshots__/page.test.tsx.snap
src/tests/unit/tests/views/page/page.test.tsx
src/views/page/page.tsx

We were getting the extension name from the config using the `extensionFullName` property, which is a different value per "environment". To solve this issue, I update the `Page` component to use the `title` const from `src\content\strings\application.ts`

fix: banner title

---

src/background/stores/dev-tools-store.ts
src/common/types/store-data/idev-tool-state.d.ts
src/tests/unit/tests/background/stores/dev-tools-store.test.ts
src/tests/unit/tests/injected/frame-url-search-initiator.test.ts

Make sure the state is always different (so we trigger the "emit change" on the store proxy side) by adding an auto increment count property to the dev tools store state.
- no UI/UX changes
- no UI/UX changes

fix: inspecting same element twice

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/Issues-details-pane.tsx
src/DetailsView/details-view-initializer.ts
src/injected/components/details-dialog.tsx
src/injected/components/fix-instruction-panel.tsx
src/injected/dialog-renderer.tsx
src/injected/fix-instruction-processor.tsx
src/injected/styles/injected.scss
src/tests/unit/tests/DetailsView/components/__snapshots__/issues-details-pane.test.tsx.snap
src/tests/unit/tests/injected/__snapshots__/fix-instruction-processor.test.tsx.snap
src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
src/tests/unit/tests/injected/components/__snapshots__/fix-instruction-panel.test.tsx.snap
src/tests/unit/tests/injected/components/fix-instruction-panel.test.tsx
src/tests/unit/tests/injected/fix-instruction-processor.test.tsx

Adding a fix instruction "decorator" so we can add a little color box when foreground/background colors are mentioned on the fix instructions.
There are some assumptions for the implemented behavior, check `src\tests\unit\tests\injected\fix-instruction-processor.test.tsx` for more details.
~~**Open question**: should I add a little border around the boxes?~~ Solved on the discussion below.
**On target page**
**On details view**

feat: add color box for color contrast fix instructions

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/outcome.scss
src/common/styles/colors.scss

Introducing new outcome badge styling according to the mock for the new report.
Fail count badge in new automated checks report:
in assessment overview:

feature: automated check report - new outcome badge

---

src/DetailsView/reports/components/report-sections/instance-details-group.tsx
src/DetailsView/reports/components/report-sections/instance-details.tsx
src/DetailsView/reports/components/report-sections/rule-details-group.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/instance-details-group.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/instance-details-group.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/instance-details.test.tsx

Using `AxeNodeResult` type to wire up instance details data on the report

using proper data for instance details

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/instance-list-group-header.tsx
src/DetailsView/reports/components/report-sections/details-section.tsx
src/DetailsView/reports/components/report-sections/result-section-title.tsx
src/DetailsView/reports/components/report-sections/result-section.tsx
src/DetailsView/reports/components/report-sections/rule-detail.tsx
src/DetailsView/reports/components/report-sections/rule-details-group.tsx
src/DetailsView/reports/components/report-sections/summary-section.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/instance-list-group-header.test.tsx.snap
src/tests/unit/tests/DetailsView/components/instance-list-group-header.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/details-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/result-section-title.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/result-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rule-detail.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rule-details-group.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/summary-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/rule-detail.test.tsx

Using heading levels 1 to 3 as follows:
- Automated checks result (the title just after the header) is H1
- All section titles (summary, scan details, failed instances, passed checks, not applicable checks) are H2
- Each rule group under failed instances is an H3 (so, **only** rules with failed instances is announced as a header, but **no** rule under passed and not applicable checks section is announce)
- Update some stylines (mostly margins)

Fix heading levels

---

src/DetailsView/reports/components/instance-list-group-header.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/instance-list-group-header.test.tsx.snap
src/tests/unit/tests/DetailsView/components/instance-list-group-header.test.tsx

Before:
We have two a11y issues in the new report currently: 
1. group header doesn't have a valid heading level;
2. rule link does not have a valid aria description.
This PR fixes both of them.
After:

Fix a11y issues in report

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/assessment-scan-details.scss
src/DetailsView/reports/components/assessment-scan-details.tsx
src/DetailsView/reports/components/report-head.tsx
src/DetailsView/reports/components/report-scan-details.tsx
src/DetailsView/reports/components/report-sections/details-section.tsx
src/tests/unit/tests/DetailsView/reports/components/__snapshots__/assessment-scan-details.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/__snapshots__/report-head.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/__snapshots__/report-scan-details.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/details-section.test.tsx.snap

Previously, line breaks in the descriptions included in the downloaded summaries of assessment/snapshot were collapsed. We added a CSS property to the HTML of the descriptions to ensure the line breaks were saved in downloads (property: `white-space`, value: `pre-wrap`). We also updated the following snapshots to reflect this change in unit tests:
`src/tests/unit/tests/DetailsView/reports/components/__snapshots__/assessment-scan-details.test.tsx.snap`
`src/tests/unit/tests/DetailsView/reports/components/__snapshots__/report-head.test.tsx.snap`
`src/tests/unit/tests/DetailsView/reports/components/__snapshots__/report-scan-details.test.tsx.snap`
Using NVDA the lines were separated when navigating with arrow keys.

Added line breaks to exported results descriptions

---

src/DetailsView/reports/components/report-sections/failed-instances-section.tsx
src/DetailsView/reports/components/report-sections/not-applicable-section.tsx
src/DetailsView/reports/components/report-sections/passed-checks-section.tsx
src/DetailsView/reports/components/report-sections/result-section.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/failed-instances-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/not-applicable-checks-sections.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/passed-checks-sections.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/failed-instances-section.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/result-section.test.tsx

We were using the rule count not the instances count. This PR fix this.

fix badge count for failed instances section

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/report-sections/outcome-summary-bar.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/outcome-summary-bar.test.tsx.snap

- Make the summary bar responsive by visually hiding the outcome text (failed, passed, not applicable)
- Use aria-label and aria-hidden to maintain accessible text for each outcome on both scenarios (responsive and normal mode).

responsive summary bar

---

src/DetailsView/reports/components/report-head-v2.tsx
src/tests/unit/tests/DetailsView/reports/components/__snapshots__/report-head-v2.test.tsx.snap

Fix extra special character on target page title for automated check report on edge

fix: extra special character on target page title for automated check report on edge

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/instance-details.scss

- Center rule name for failed instances (collapsed and expanded)
- Center rule name for passed/not applicable checks
**collapsed**
**expanded**
- css only change
- css only change
- css only change
- not affected

fix: center rule name

---

src/DetailsView/reports/automated-checks-report.scss
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/report-body.test.tsx.snap

make the report responsive according to Figma:
1. Add 16px margins to both side of the content when the screen is very narrow.
2. Fix the issue where white space is collapsed in the summary bar.

Overall responsive layout 

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/report-sections/failed-instances-section.tsx
src/DetailsView/reports/components/report-sections/no-failed-instances-congrats.tsx
src/DetailsView/reports/components/report-sections/result-section.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/failed-instances-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/no-failed-instances-congrats.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/result-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/no-failed-instances-congrats.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/result-section.test.tsx

This PR brings ADA back (if the website has no failures)

Ada congrats component

---

src/DetailsView/components/report-export-component.tsx
src/DetailsView/reports/components/report-head-v2.tsx
src/DetailsView/reports/components/report-sections/details-section.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/details-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/details-section.test.tsx

Adds code that makes the screen reader properly announce the text in the scan details section.
The way Its done is to add a `screen-reader-only` span with properly formatted text, the `css` for that `span` will hide it from user's viewport but the screen-reader will read it since I have put the `ids` of those 
`span` in the `td` of the actual content's `aria-labelledby`.
Also since, now we are using `description` at two places; change the logic a little bit to make the replacement work better.
No-change in what we show here.
```
Target Page: https://www.chicos.com/store/
Scan date: 2019-06-11 9:51 PM UTC
Comment: Test
```

fix: fix screen reader announcement of the details section content

---

src/DetailsView/reports/components/report-sections/instance-details-group.tsx
src/DetailsView/reports/components/report-sections/outcome-summary-bar.tsx
src/DetailsView/reports/components/report-sections/rule-details-group.tsx

Add key to components in groups properly.
No tests changed since keys does not render in dom.

Add key to components in groups properly

---

src/DetailsView/reports/automated-checks-report.scss

Fix failed instance section -> rule group height
**before**
**after**
- css only changes
- css only changes

fix height for each result section

---

src/DetailsView/reports/components/report-sections/failed-instances-section.tsx
src/DetailsView/reports/components/report-sections/report-body.tsx
src/DetailsView/reports/components/report-sections/report-section-factory.tsx
src/DetailsView/reports/components/report-sections/results-container.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/failed-instances-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/report-body.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/results-container.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/failed-instances-section.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/results-container.test.tsx

No new features. Just move the script tag some levels up on the dom hierarchy so we can re-use it on the passed/not applicable checks section to make them collapsible.
- no UI/UX changes
- no UI/UX changes

refactor: move script tag

---

src/DetailsView/components/overview-content/overview-content-container.tsx
src/scanner/rule-to-links-mappings.ts
src/tests/unit/tests/DetailsView/components/overview-content/__snapshots__/overview-content-container.test.tsx.snap
src/tests/unit/tests/DetailsView/components/overview-content/overview-content-container.test.tsx

This sets the correct mapping for WCAG 2.1 rules in automated checks, thus enabling them. It also adds a link to the overview section in assessments.

Enable WCAG 2.1 rules in Automated Checks

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/test-status-choice-group.scss
src/DetailsView/components/test-status-choice-group.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/test-status-choice-group.test.tsx.snap
src/tests/unit/tests/DetailsView/components/test-status-choice-group.test.tsx

Just moved styles from general details view scss file to module specific scss file.

refactor: created/moved module specific styles for test status choice group

---

src/DetailsView/reports/components/report-sections/collapsible-container.tsx
src/DetailsView/reports/components/report-sections/result-section-content.tsx
src/DetailsView/reports/components/report-sections/result-section-title.tsx
src/DetailsView/reports/components/report-sections/result-section.tsx
src/DetailsView/reports/components/report-sections/rule-details-group.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/collapsible-container.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/result-section-content.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/result-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rule-details-group.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/collapsible-container.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/result-section-content.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/result-section-title.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/result-section.test.tsx

This PR is in order to support making the pass/not applicable sections collapsible.
- On `ResultSection`, extract the content portion to it's own component
- Clean up how we handle heading level props on the `CollapsibleContainer`
- no UI changes
- no UI changes

refactor: small improvements on ResultSection

---

src/assessments/semantics/test-steps/css-content.tsx
src/content/test/semantics/css-content.tsx
src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap

This PR updates some text in our CSS content test to reduce potential confusion for the user. More info is in issue #697 

Updates to the semantic CSS content test

---

src/DetailsView/components/export-dialog.tsx
src/DetailsView/components/report-export-component.tsx
src/DetailsView/reports/components/report-sections/details-section.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-component.test.tsx.snap
src/tests/unit/tests/DetailsView/components/export-dialog.test.tsx
src/tests/unit/tests/DetailsView/components/report-export-component.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/details-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/details-section.test.tsx

This PR makes the comment section optional based on the value of the description. The way I have achieved this is by calling the report html generator on `Export` button click for Export Dialog box.
WIP: need some feedback on how to test the `export dialog for props calling`

fix: automated-checks-report; make comment section optional based on description entered

---

src/common/feature-flags.ts
src/tests/unit/tests/background/feature-flags.test.ts

enable new report ux by default

enable new report ux by default

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/report-sections/header-section.scss
src/DetailsView/reports/components/report-sections/header-section.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/header-section.test.tsx.snap

Move all header section style to it's own scss module
- no changes
- no changes

refactor: extract header section scss to proper module

---

src/DetailsView/reports/components/instance-details.scss

Adding styles to enable the color box on the how to fix instructions (think color contrast) on the new report.

feat: how to fix instruction color box on new report

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/report-sections/details-section.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/details-section.test.tsx.snap

New automated check report had a `NewTabLink` under `aria-hidden` `tr`. Making that link disabled fixed the problem.

fix: new automated-checks report; aria-hidden-focus issue.

---

src/DetailsView/reports/components/report-sections/outcome-summary-bar.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/outcome-summary-bar.test.tsx.snap

Currently, the summary bar content (count for failed/passed/not applicable) is not announced on Jaws. User cannot use the keyboard to get to that content.
NVDA announce it though.
This PR fix the summary bar to make it accessible on both, NVDA and Jaws.
- only snap shot files updated
- not applicable
- no changes on the visible UI
- test no changes on NVDA; test JAWS properly announce the content.

fix: make summary bar content accessible

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/report-sections/no-failed-instances-congrats.scss
src/DetailsView/reports/components/report-sections/no-failed-instances-congrats.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/no-failed-instances-congrats.test.tsx.snap

Move all no failed instances congrats component style to it's own scss module
- no changes
- no changes

refactor: extract NoFailedInstancesCongrats scss to its own module

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/report-sections/footer-section.scss
src/DetailsView/reports/components/report-sections/footer-section.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/footer-section.test.tsx.snap

Move all footer section style to it's own scss module
- no changes
- no changes

refactor: extract footer section scss to proper module

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/reports/components/report-sections/details-section.tsx
src/DetailsView/reports/components/report-sections/header-section.scss
src/DetailsView/reports/components/report-sections/header-section.tsx
src/common/components/guidance-tags.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/details-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/header-section.test.tsx.snap
src/tests/unit/tests/common/components/__snapshots__/guidance-tags.test.tsx.snap

Modular scss is not properly working on the report on the bundle versions of the extension. 
For now, let's roll back to "normal" scss.
We should have a second look onto how to make modular scss work on the reports too.

fix: new report styles on bundled extensions

---

src/assessments/automated-checks/build-test-steps-from-rules.tsx
src/tests/unit/tests/assessments/automated-checks/build-test-steps-from-rules.test.tsx

Fix label-content-name-mismatch failure on automated checks requirement rule link.

fix: a11y failure on see more info here link

---

src/DetailsView/reports/automated-checks-report.scss

Focus ring was missing on chrome. Removing all the custom `outline` styles for the button fix this.
Check on chrome, firefox and edge.
- css change only
- css change only
- no changes

fix: missing focus ring on collapse/expand button

---

src/background/browser-adapters/chrome-adapter.ts

We need to test this. This change could mean, if the page is still loading, we may inject it before it completes loading. You can use the latest playground extension to validate this. (Wait for few min to see the today's version in chrome store) I am meanwhile using that to validate on more sites.
I have validated this on https://codepen.io/dbjorge/pen/Kjpmja , slow loading pages. The user experience is same in the slow loading pages as well.
more info on the property can be found here - https://developer.chrome.com/extensions/content_scripts

fix: forcing to inject immediately when we try to inject files

---

src/content/test/semantics/data-tables.tsx
src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap

Making each tag on the list to be surrounded by `<Markup.Code>` to style it properly.
- no unit test for content

fix: properly style html tags on data tables content

---

src/DetailsView/reports/components/report-sections/details-section.scss
src/DetailsView/reports/components/report-sections/header-section.scss

Wrapping long urls on scan details section
Cutting text and adding ellipsis on target page url (this follows figma mock)
- css change only
- no changes

fix: url ellipse/wrapping

---

src/scanner/rule-to-links-mappings.ts

Setting this rule as best practice until we are confident in it's quality.

Disable label-content-name-mismatch rule for automated checks

---

src/DetailsView/reports/components/report-sections/footer-section.scss

Sets specific margins (like normal content-container) when not enough width on the view port.

Make the footer in the automated check report responsive

---

src/DetailsView/reports/components/report-sections/collapsible-result-section.tsx
src/DetailsView/reports/components/report-sections/not-applicable-checks-section.tsx
src/DetailsView/reports/components/report-sections/passed-checks-section.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/collapsible-result-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/not-applicable-checks-sections.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/passed-checks-sections.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/collapsible-result-section.test.tsx

fix duplicate id a11y failure on collapsible container

fix duplicate id a11y failure on collapsible container

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/report-sections/content-container.scss
src/DetailsView/reports/components/report-sections/content-container.tsx
src/DetailsView/reports/components/report-sections/footer-section.scss
src/DetailsView/reports/components/report-sections/results-container.scss
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/content-container.test.tsx.snap

Add separator line to the new report footer
- doesn't exist
- not changed

fix: add missing footer line to new automated checks report

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/general_question.md

Update Issue templates to have the helper text in each heading as a comment rather than proper text. This avoids the helper text to show up for things that was in the template for just help.
I noticed a lot of issues have extra wordings from the template directly, which is not required.
> No checklist item applicable for this PR.

chore: update issue templates

---

src/injected/components/details-dialog.tsx
src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap

It seems the recent OfficeFabric update #782 may have led to the UI issues described in #829 . I created this [codepen ](https://codepen.io/anon/pen/zVoLJv) to show that using a css class in `layerProps` to target buttons leads to different behavior in OF versions `6.142.0` and `6.189.4`. OF is now on major version 7.
I'm not sure if the PR change is the best way to address this issue; it aligns with the code in this component & unblocks the UI regression in production: https://github.com/microsoft/accessibility-insights-web/blob/9baf98a369968f5e59182c37ec6072e8702e1960/src/popup/components/telemetry-permission-dialog.tsx#L52
- [NA] Added relevant unit test for your changes. (`yarn test`)
- [NA] Verified code coverage for the changes made. Check coverage report at: …

Restore instance dialog UI by moving css class assignment

---

package.json
src/DetailsView/components/export-dialog.tsx
src/DetailsView/details-view-initializer.ts
src/common/blob-provider.ts
src/common/file-url-provider.ts
src/common/window-utils.ts
src/tests/unit/common/blob-provider.test.tsx
src/tests/unit/common/file-url-provider.test.tsx
src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
src/tests/unit/tests/DetailsView/components/export-dialog.test.tsx

A few organizational/specification changes for the increase in download size using blobs that I merged last week. First, giving more meaningful variable names (in blob-provider and window-utils). Second, abstracting the creation of a blob and extraction of a URL from that blob into a class named file-url-provider.
Mocked the action of this class for all Export Dialog tests.
Removed WindowUtils from deps of Export Dialog since their utility was now handled by the File URL Provider.

Blob storage edits

---

package.json
src/common/feature-flags.ts
src/tests/unit/tests/background/feature-flags.test.ts

Adds feature flag for enabling the more detailed version of manual failure instances. Will allow users to add the CSS selector (path) of a specific, failure-causing element. Will then automatically populate the code snippet associated with that path. This PR solely adds the feature flag itself.

Feature Flag for manual failure instance details

---

package.json
src/common/is-supported-browser.ts
src/popup/popup-init.ts
src/popup/popup-initializer.ts
src/tests/miscellaneous/user-agent-manual-tests/user-agent-server.js
src/tests/unit/tests/common/is-supported-browser.test.ts
src/tests/unit/tests/popup/popup-initializer.test.ts
yarn.lock

Updating ua-parser-js from 0.7.19 to 0.7.20 break our logic to not support Microsoft Edge (the old browser). The change they made is basically fixing how they where parsing the user agent on Edge Insider: on 0.7.19 they reported Edge Insider to be Chrome, while on 0.7.20 they corrected that and report it to be Edge.
Our logic was using the `.getBrowser().name` value from the UA Parser and check the name but now (on 0.7.20) both Edge and Edge Insider name is the same ('Edge') so we need to also check the engine name to run this validation.
In short:
- Extract supported browser logic to 'IsSupportedBrowser' type
- Update popup-init to use the new type instead of running the check itself
- Update ua-parse-js lib
Additionally, I added a small node script to spin up a localserver which respond …

refactor: update ua-parser-js + small refactor

---

src/injected/dialog-renderer.tsx
src/injected/visualization/element-highlight.tsx
src/injected/visualization/formatter.ts
src/injected/visualization/highlight-box.tsx
src/tests/unit/tests/injected/visualization/__snapshots__/element-highlight.test.tsx.snap
src/tests/unit/tests/injected/visualization/__snapshots__/highlight-box.test.tsx.snap
src/tests/unit/tests/injected/visualization/element-highlight.test.tsx
src/tests/unit/tests/injected/visualization/highlight-box.test.tsx

I would like to use more React components for our injected content scripts. As such, this is a start for that effort; **please refer to highlight-box-drawer.ts** to see the re-factor work done here. These components are not being used anywhere (future PR for that).

React-based visualization components for highlight drawer

---

src/background/background-init.ts
src/background/injector-controller.ts
src/background/injector/content-script-injector.ts
src/background/tab-context-factory.ts
src/common/promises/promise-factory.ts
src/tests/unit/tests/background/content-script-injector.test.ts
src/tests/unit/tests/background/tab-context-factory.test.ts
src/tests/unit/tests/common/promises/promise-factory.test.ts

This is part of #801: Use native async, await & promise but it doesn't complete it.
Refactor `ContentScriptInjector` to not use `Q`.
- Introduce `PromiseFactory`
- Implement `timeout` as a `Promise`-like API
- Update `ContentScriptInjector` to use `PromiseFactory` instead of `Q`
- Update the creator: `TabContextFactory` (remove global reference to Q and use constructor parameter to receive `PromiseFactory'
- Update user: `InjectorController`: grandfathered a tslint floating promise issue that showed up after the change to native promise (instead of `Q` promises)
**Notes**
There are more places where we're using `Q`. You can take this PR as a starting point and example for:
- How to refactor `Q.defer` uses
- How to replace `Q.timeout` uses
- How to test promise returning function without …

refactor: ContentScriptInjector without Q

---

src/background/injector/content-script-injector.ts
src/common/promises/promise-factory.ts
src/tests/unit/tests/background/content-script-injector.test.ts

Addressing some comments from PR #844
Out of scope for now:
- Refactor the `PromiseFactory` to be only a function for the timeout promise (waiting until we get rid of `Q` as some other functions may be added to the factory)
- Handling the floating promise that we grandfathered on the previous PR
- Changing the style of the test for the `PromiseFactory` as I would like more team members to look at it and give feedback.
- Waiting on the browser adapter injection API (we don't wait for the CSS right now. only for the javascript)

refactor: content script injector (comments from previous PR)

---

package.json
webpack.config.js
yarn.lock

Updating css-loader which is used on our build process (through webpack)
I tested locally 2 versions of our extension: dev and canary (to make sure dev & prod modes are working correctly)
- no changes
- no changes

chore: update css-loader

---

package.json
src/tests/unit/tests/DetailsView/components/failure-instance-panel-control.test.tsx
src/tests/unit/tests/DetailsView/components/start-over-dropdown.test.tsx
src/tests/unit/tests/DetailsView/components/switcher.test.tsx
src/tests/unit/tests/common/components/issue-filing-button.test.tsx
yarn.lock

Update @types/enzyme
Code changes are on tests where we use `wrapper.state()` to get specific properties from the state. Looks like enzyme make the types more strict, meaning you need to be more specific when using `shallow` and `mount` about the component type you're rendering so enzyme knows the props and state types and then let you access their internals.
- no changes
- no changes

chore: update @types/enzyme

---

src/DetailsView/reports/components/outcome-summary-bar.tsx
src/tests/unit/tests/DetailsView/reports/components/__snapshots__/outcome-summary-bar.test.tsx.snap

If the `countSuffix` property isn't provided (like in the FastPass report), concatenating a number with an `undefined` `countSuffix` results in `NaN`, leading to issue #852. This PR removes the concatenation and instead lets React render the undefined (no-op) value.

fix: remove NaN from fastpass report by removing concatenation in OutcomeSummaryBar

---

README.md

Update `Readme` to have a specific PS note linking to the issue that I created for running E2E on WSL.

chore: update readme for E2E behavior on WSL

---

src/DetailsView/details-view-container.tsx
src/DetailsView/details-view-renderer.tsx
src/tests/unit/tests/DetailsView/details-view-renderer.test.tsx

Found some unsued `dom: Document` property not being  used.
- no issue filed for this
- no changes
- no changes

refactor: remove some unused dom properties

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/report-sections/collapsible-container.tsx
src/DetailsView/reports/components/report-sections/collapsible-result-section.tsx
src/DetailsView/reports/components/report-sections/result-section-title.tsx
src/DetailsView/reports/components/report-sections/rule-detail.tsx
src/DetailsView/reports/components/report-sections/rules-only.tsx
src/DetailsView/reports/components/report-sections/rules-with-instances.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/collapsible-container.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/collapsible-result-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/result-section-title.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rule-detail.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rules-only.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rules-with-instances.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/collapsible-container.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/rule-detail.test.tsx

Fixing accessibility issues with rule details headers.
General strategy is as follow:
- use a visually hidden 'h' tag for the text
- we use a simpler text here: rule <rule name>, <count> failures/passes/not applicable
- visible to screen readers -> screen reader user can navigate to it with 'h' shortcut
- not actually visible on screen
- use a aria-hidden text for the title
- screen reader skip this on
- normally visible on screen
- move the original content of the header out of the header
- this includes:
- collapse/expand button control
- link to the rule (with text = rule name) 
- links to WCAG rules
- rule description
- failure count (this is hidden now as we are reading it as part of the header)
This way screen reader user can navigate to the headings either using 'h' shortcut or …

fix: duplicated header announcement on automated checks report

---

build.yaml
src/DetailsView/detailsView.html
src/manifest.json

Fix typo in a path for devtools.html in manifest.
This is an ongoing step to fix the crash issue in Linux.

fix: correct typos to make extension not crash on Linux

---

src/background/injector/content-script-injector.ts

Add comment to document the reason why we don't wait for css injection (by passing a `null` callback to the injection API).

doc: add comment to clarify null param decision

---

src/injected/visualization/center-position-calculator.ts
src/tests/unit/tests/injected/visualization/center-position-calculator.test.ts
src/tests/unit/tests/injected/visualization/drawer-utils-mock-builder.ts

Properly handling case of area not having coords.
Remove some `verifiable` calls on mocks that actually return something.

refactor: minor improvements on CenterPositionCalculator

---

src/DetailsView/Styles/detailsview.scss
src/common/styles/colors.scss
src/common/styles/common.scss
src/injected/styles/injected.scss
src/popup/Styles/popup.scss

The original color for $communication-primary was #0078D4, which failed color contrast when sitting on backgrounds darker than #FFFFFF. Updated our primary communication shade to #106EBE, and adjusted the darker shades to stay in line with the shading gradient. Adjusted a couple of places where elements were listed with #communiation-shade-10 as a temporary fix to the contrast issue, but should be $communication-primary.

Color changes to $communication-primary, shade-10, shade-20, shade-30

---

Gruntfile.js
build.yaml
package.json
pipeline/e2e-test.yaml

Our builds are currently building "all" which includes our electron "getting started" app.
Working on updating typescript to 3.5.x, I can see our build failing (logs [here](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=22980&view=logs)) due to `Fatal error: Missing required file extension/devBundle/background.bundle.js`
Not sure what the root cause of this is but it looks like calling `webpack` without the `config` or `config-name` param, which up to this moment was building all configs -dev, prod & electron- only builds `prod` config.
One way to address this is by calling `webpack` with an explicit config/config-name.
To summaries this PR includes:
- new grunt task to build only the web extension (no electron building on the new task)
- calling webpack …

building the web extension only

---

src/DetailsView/reports/components/report-sections/content-container.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/content-container.test.tsx.snap

Using a main landmark to wrap the main content of the report.
**Top view**
**Bottom view**

feat: use main instead of div for the main content section

---

src/common/icons/cancel-icon.tsx
src/common/icons/copy-icon.tsx
src/common/icons/file-html-icon.tsx
src/common/icons/lady-bug-solid-icon.tsx
src/content/test/images/guidance.tsx
src/content/test/images/image-function.tsx
src/icons/brand/blue/brand-blue.tsx
src/icons/brand/white/brand-white.tsx
src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap

We are using (on svg icons) and mentioning (on image related guidance content) `role='image'` but this is not correct, we need to use `role='img'`
- no changes
- will fix some "parsing" test issues (from the assessment)

fix: image role on svg and guidance content

---

src/DetailsView/components/assessment-instance-edit-and-remove-control.tsx
src/DetailsView/components/assessment-test-view.tsx
src/DetailsView/components/assessment-view.tsx
src/DetailsView/components/failure-instance-panel-control.tsx
src/DetailsView/components/failure-instance-panel-details.tsx
src/DetailsView/components/manual-test-step-view.tsx
src/DetailsView/components/test-step-view.tsx
src/DetailsView/handlers/assessment-instance-table-handler.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/failure-instance-panel-control.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/failure-instance-panel-details.test.tsx.snap
src/tests/unit/tests/DetailsView/components/assessment-instance-edit-and-remove-control.test.tsx
src/tests/unit/tests/DetailsView/components/assessment-test-view.test.tsx
src/tests/unit/tests/DetailsView/components/assessment-view.test.tsx
src/tests/unit/tests/DetailsView/components/failure-instance-panel-control.test.tsx
src/tests/unit/tests/DetailsView/components/failure-instance-panel-details.test.tsx
src/tests/unit/tests/DetailsView/components/manual-test-step-view.test.tsx
src/tests/unit/tests/DetailsView/handlers/assessment-instance-table-handler.test.tsx

Adding fields for the path/snippet in the Failure Instance Panel *only* when Manual Instance Detail Feature Flag is flipped to "on." Lots of edits to get the Feature Flag Store Data all the way to the Failure Instance Panel. 
Most test changes are to reflect this new prop added to the flow. One unit test added to Failure Instance Panel Test to check that UI reflects classic version when flag is off and new version when flag is on.
Finally added snippet and path to the state of Failure Instance Panel (where comment was/is as well).

Basic UI for Path/Snippet Addition to Failures

---

src/DetailsView/Styles/detailsview.scss

Increased CSS specificity of message bar icon rule so the "Target page is in a hidden state" icon changes color as expected when high contrast mode is applied.
(if you magnify, you might be able to see that the icon is there next to the text "The target page...", it's grey on the brown background)

fix: color of message bar icon in high contrast mode

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/report-sections/instance-details-group.tsx
src/DetailsView/reports/components/report-sections/rule-content.tsx
src/DetailsView/reports/components/report-sections/rule-resources.tsx
src/DetailsView/reports/components/report-sections/rules-with-instances.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/instance-details-group.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rule-content.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rule-resources.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rules-with-instances.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/instance-details-group.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/rule-content.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/rule-resources.test.tsx

Add new card for **rule resources** under failed instances section.
**Out of scope for this PR**: currently, the figma mocks do not show the "New for WCAG 2.1" badge. I'm talking with design on where to add this but for now, I'll leave it out of scope for this PR.
**"Normal"**
**Focus**
**Hover**
- after expanding the hidden content, user can normally navigate to the new card by pressing down arrow key. It will read the title, and then the links one by one

feat: add rule resources card

---

src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/report-sections/minimal-rule-detail.tsx
src/DetailsView/reports/components/report-sections/result-section-title.tsx
src/DetailsView/reports/report-html-generator-v2.tsx
src/icons/brand/white/brand-white.tsx
src/tests/unit/tests/DetailsView/reports/__snapshots__/report-html-generator-v2.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/minimal-rule-detail.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/result-section-title.test.tsx.snap

By running assessment -> parsing -> parsing, we got around 50~ (actual number varies base on the amount of failed rules on the target page).
Roughly, the errors were on 3 categories:
- block elements inside inline elements (think of `<span><div/></span>`, where `<div>` is a block element while `<span>` is an inline element, some more info [here](https://www.w3schools.com/htmL/html_blocks.asp))
- missing `<!DOCTYPE html>`
- `mask-type` attribute on one of our svg icon (have to use `style` to set the mask type on this one)
By swaping `<div>` with `<span>` I have to also adjust some styles and fix some minor issues (with the chevron on passed/not applicable checks h2 titles)
- not impacted

fix: parsing errors on automated checks report

---

.prettierignore

`yarn format` gives errors about not understanding .dockerignore/Dockerfile. `yarn format-check` shows error lines but still "succeeds" at the end. This suppresses the unrecognized file types from prettier.

chore: .prettierignore for .dockerignore and Dockerfile (no prettier support)

---

src/DetailsView/reports/components/report-sections/rule-content.tsx
src/DetailsView/reports/components/report-sections/rule-resources.tsx
src/common/components/guidance-tags.scss
src/common/components/guidance-tags.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/rule-resources.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/rule-resources.test.tsx
src/tests/unit/tests/common/components/__snapshots__/guidance-tags.test.tsx.snap

Adding "New for WCAG 2.1" badge on the new report
- Add the badge reusing existing component 
- Update existing component to use `<span>` instead of `<div>`
- Main reason for this is related to the Parsing test of our assessment. Basically, we should not use block elements (e.g `<div>`) inside inline elements (e.g. `<h1>`, `<span>`, `<button>`)
- Update styles for existing component to account for the `<div>` to `<span>` change
**New automated checks report**
**On assessment report** (fix the badge to be in the same line)
**On failure details** (not changed)
**On assessment details view** (not changed)

feat: add  new for wcag 2.1 badge on new report

---

src/DetailsView/reports/components/report-sections/details-section.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/details-section.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/report-sections/details-section.test.tsx

On the new automated checks report we have the target page link twice, one on the top level header of the report, where we use the target page name as the link text; and the second on the scan details section (right after the globe icon) where we use the url as the link text. 
This links are failing `assessment -> links -> link purpose` as they do not have the same **accessible name**.
**Edit:**
To fix this: 
- use `title` attribute on the anchor tag to match the one on the page header (basically the page title)
- update the hidden label to `"target page url"` to clarify what the value is (i.e. the url itself)
This two fixes are needed because we have to modes of operations here:
- **tab key navigation**: using the tab key, the user will navigate through interactive elements. The second …

fix: a11y issue on target page link

---

README.md
pipeline/e2e-test-from-agent.yaml

Before this change, the windows E2E test logs showed the following warning:
```
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
```
This addresses it in the CI build and also in our README suggested commands (I searched the codebase for uses of the string ` -- `)

chore: remove unnecessary -- args to "yarn run" to fix build warnings

---

src/DetailsView/reports/automated-checks-report.scss

Chevron is being cut off if there is not enough space on the window, e.g at 400% level zoom
Using minimum width attribute to fix it.
**100%**
**400%**
- not filed
- not affected
- not affected
- not affected

fix: chevron cut off

---

.dockerignore

Adds `test-results/` to `.dockerignore` to prevent pushing stale test results from old runs into the built container

test: prevent stale docker test results from being pushed into container

---

src/DetailsView/details-view-initializer.ts
src/DetailsView/reports/report-generator-provider.ts
src/common/feature-flags.ts
src/tests/unit/tests/DetailsView/reports/report-generator-provider.test.ts
src/tests/unit/tests/background/feature-flags.test.ts

Removing the "new automated checks report" feature flag as we're done with the feature now.
**Out of scope**: I'm not removing the old report dead code on this PR to keep it small and single scoped. I'll have a second PR to remove that dead code.

refactor: remove new report feature flag

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/DetailsView/components/left-nav/nav-link-handler.ts
src/common/dropdown-click-handler.ts
src/common/message-creators/content-action-message-creator.ts
src/common/message-creators/inspect-action-message-creator.ts
src/common/message-creators/scoping-action-message-creator.ts
src/injected/details-dialog-handler.ts
src/injected/target-page-action-message-creator.ts

Looking at the Typescript 3.5 update and webpack config changes it may need, I came across an compilation error where we are using React.<Mouse events> types without actually importing react on the file. I don't know why this is not happening right now with our current setup but using the experimental watch flag on one of the webpack plugins make this error appears.
Also, for sake of correctness, we should import anything we are using on each file.
- not impacted
- not impacted
- not impacted
- not impacted

refactor: add missing react imports

---

src/DetailsView/reports/automated-checks-report.scss

Fix link size on the **Resources for this rule** card in the automated checks report.
**After (fixed)**
**Before**
- not affected
- not affected

fix: link size is too big on resources for this rule card

---

src/tests/end-to-end/common/browser-factory.ts

According to [Puppeteer documentation for launch options](https://github.com/GoogleChrome/puppeteer/blob/v1.14.0/docs/api.md#puppeteerlaunchoptions), setting `defaultViewport` to `null` disables the default viewport size of 800x600. When the default viewport is disabled, the viewport size matches the browser size. This makes failture screenshots more meaningful when debugging flaky E2E tests because they will show more than the top left portion of the page that is being tested.

chore: disable Puppeteer default viewport to increase its size

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/reports/automated-checks-report.scss
src/DetailsView/reports/components/report-sections/header-section.scss
src/common/styles/common.scss

- Updating default links style to:
- have no underline normally
- have underline when hover
- Remove link style override on the automated checks report (so we pick up the default links style
- Update font color and weight for the header target page text on the automated checks report
**_Details view_**
**Target page url**
**Rule and WCAG links**
**_Automated checks report_**
**Header target page url**
**Scan details page url**
**Rule and WCAG links**
- found during insider validation
- no code changes
- no code changes
- not affected

fix: update links styles, match style on the report

---

build.yaml
pipeline/e2e-reliability.yaml

Since the recent change to run them in linux/windows, the e2e test suite has proven too flaky to use as a PR/CI gate. This change temporarily moves the flaky tests out of the required suite in `build.yaml` and into a 5x-per-environment run in a separate `e2e-reliability.yaml` instead, which will be set up to run as a non-required gate only in those PRs/branches working on e2e updates/fixes.
We'll be prioritizing improving the flakiness and getting the runs re-enabled as required checks as part of #867.
- [n/a] (UI changes only) Verified …

test: temporarily disable e2e tests from PR/CI gates until we can resolve flakiness

---

pipeline/e2e-reliability.yaml

We tried updating to the latest agent version to see if it had any impact on reducing page crash rates compared to the older agents. It didn't impact page crash rate, but it improved performance 5-10%, so we'll take it anyway as we continue to test other options for fixing the page crashes.

test: use latest windows hosted agent version in e2e-reliability runs

---

src/DetailsView/reports/components/outcome-summary-bar.tsx
src/DetailsView/reports/components/report-sections/minimal-rule-header.tsx
src/tests/unit/tests/DetailsView/reports/components/__snapshots__/outcome-summary-bar.test.tsx.snap
src/tests/unit/tests/DetailsView/reports/components/outcome-summary-bar.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/minimal-rule-header.test.tsx.snap

The icons where not under an `aria-hidden="true"` container and thus, were being flag on Assessment > Images > Image function.
We do have proper text/aria-labels for both icons (on the summary bar and on the collapse/expand rule header) so hiding the icons is enough to fix this issue.
- no changes
- AT still reads the information correctly

fix: Automated checks report: x icons are coded as no value

---

src/tests/end-to-end/common/generate-screenshot.ts
src/tests/end-to-end/common/page.ts

Previously, in our e2e action wrappers that used `screenshotOnError`, an error case that prevents both the original error and the screenshot-taking from working (eg, underlying browser/page closed prematurely) would only show an error text/stack for the takeScreenshot error, even though the original error is usually more valuable. This causes it to print both errors and use the original as the primary.
Replaces/builds on @Shobhit1 's #956 , since he's out today 

test: prevent errors in takeScreenshot from suppressing the error that motivated taking the screenshot

---

Dockerfile

[Cypress](https://www.cypress.io/) maintains [a set of Docker images](https://github.com/cypress-io/cypress-docker-images) that come with the necessary dependencies for running headful Chromium pre-installed. We can't use Cypress itself because of our need for multi-tab scenario validation, but their docker images save us having to do a long "apt-get" operation with each build and cut off about a minute from the linux e2e tests (which are the long pole for e2e-reliability runs right now).
- …

test: reduce docker build time by 1min by using cypress/base:10 image instead node:10

---

src/assessments/custom-widgets/custom-widgets-column-renderer.tsx
src/tests/unit/jest-setup.ts
src/tests/unit/tests/DetailsView/extensions/wait-for-all-requirements-to-complete.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/body-section.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/content-container.test.tsx
src/tests/unit/tests/DetailsView/reports/components/report-sections/results-container.test.tsx
src/tests/unit/tests/common/components/toast.test.tsx
src/tests/unit/tests/views/content/markup/code-example.test.tsx

Clean up/update/fix some unit tests to get rid of all of the console warning/errors messages we were getting from running our unit tests.
Catergories:
- office fabric icons not being registered 
- use `setIconOptions` from `'office-ui-fabric-react/lib/Styling'`
- Adding missing key property on elements that are part of an array (like when we map with a render function)
- Update usage of enzyme`isEmpty()` for `exists()`
- Use `Enzyme.mount` for testing a `componentDidUpdate` method that internally calls `forceUpdate()` (the component needs to be mounted in order to properly call `forceUpdate`, otherwise, you get a console error)
- not impacted
- not impacted

test: fix/remove console warning/errors from unit tests

---

src/popup/components/file-url-unsupported-message-panel.tsx
src/popup/components/popup-view.tsx
src/popup/main-renderer.tsx
src/popup/popup-initializer.ts
src/tests/unit/tests/popup/components/__snapshots__/file-url-unsupported-message-panel.test.tsx.snap
src/tests/unit/tests/popup/components/__snapshots__/popup-view.test.tsx.snap
src/tests/unit/tests/popup/components/file-url-unsupported-message-panel.test.tsx
src/tests/unit/tests/popup/components/popup-view.test.tsx
src/tests/unit/tests/popup/main-renderer.test.tsx

`PopupView` knows a lot of lower level details. In this PR I'm extracting one of those concerns out to a new component. 
- not affected
- not affected

refactor: extract file url unsupported message panel

---

src/tests/end-to-end/common/browser.ts
src/tests/end-to-end/common/page.ts

This PR addresses a recurring source of e2e test flakiness in scenarios like "open a panel then click a button in it", where if the panel opening has an animation, the button can move out from under the click coordinates during the attempt to click on it, resulting in the click not registering and the next step of the test timing out.
We considered/tried out several options for reducing this flakiness:
* Using cypress's strategy of waiting for elements being clicked to have a stable position. This is maybe the "best" solution in theory but we weren't able to come up with a stable implementation that wasn't itself flaky.
* Waiting for the element being clicked to be free of running animation/transition style properties. This doesn't work because other elements' animations (not necessarily …

test: improve click() reliability by disabling animations in pages under test

---

src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-changed-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/target-page-changed-view.test.tsx

Noticed a few different issues with `target-page-changed-view.test.tsx`:
* It was testing several cases that aren't allowed to occur in practice (title and toggleLabel are non-optional properties of DisplayableVisualizationTypeData)
* Its tests of subtitle differences were incomplete (the test cases included different subtitles, but didn't actually pass subtitle to the thing under test)
* The test's snapshot behavior wasn't consistent between node 10 and node 12 (the way the testCase objects serialized into test names differed on the 2 platforms)
This PR fixes all of these issues by partially rewriting the tests. This fixes the only case where our unit tests didn't work consistently in node 12. …

test: update target-page-changed-view test cases to match actual use cases

---

src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/common/notification-creator.ts
src/tests/unit/tests/common/notification-creator.test.ts

Makes the `BrowserAdapter.createNotification` wrapper a little thinner by moving the "our notifications are of the 'basic' type" logic out of the BrowserAdapter and into the NotificationCreator.

refactor: make BrowserAdapter.createNotification a thinner wrapper

---

src/background/background-init.ts
src/background/tab-context-broadcaster.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/tests/unit/tests/background/tab-context-broadcaster.test.ts
src/tests/unit/tests/popup/components/__snapshots__/popup-view.test.tsx.snap

Make BrowserAdapter slightly thinner by moving the multi-method coordination in BrowserAdapter.sendMessageToFramesAndTab out of the adapter and into its only consumer

refactor: move frames+tab coordination responsibility out of BrowserAdapter

---

src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/popup/components/file-url-unsupported-message-panel.tsx
src/tests/unit/tests/popup/components/__snapshots__/popup-view.test.tsx.snap
src/tests/unit/tests/popup/components/file-url-unsupported-message-panel.test.tsx

Moves the coordination responsibility out of BrowserAdapter.openManageExtensionPage into its only consumer and brings it under test.

refactor: move BrowserAdapter.openManageExtensionPage coordination into its only consumer

---

src/background/injector/content-script-injector.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/tests/unit/tests/background/content-script-injector.test.ts
src/tests/unit/tests/popup/components/__snapshots__/popup-view.test.tsx.snap

The BrowserAdapter css/js injection methods had some business logic in them that wasn't tested. This moves those methods to their only consumer (`ContentScriptInjector`), leaves thinner wrappers in BrowserAdapter/ChromeAdapter, and revamps the `ContentScriptInjector` tests to include tests of the moved logic (plus some other paths in the injector that weren't previously well tested)

refactor: move js/css injection logic out of BrowserAdapter and under test

---

pipeline/e2e-test-from-docker.yaml
pipeline/e2e-test-publish-results.yaml

Sets up the docker-specific parts of gathering failure screenshots to still execute when the tests fail.
Also updates the more general results publishing task to work consistently with them and not run if the pipeline is cancelled (that's the difference between `always()` and `succeededOrFailed()`.

test: run result publishing steps to even when previous steps failed

---

src/tests/end-to-end/common/page-controllers/page.ts

This addresses some flakiness related to animation timings:
* Increases scope of disableAnimations CSS
* Uses a less verbose means of applying the disable animations styles
* Adds a specific workaround to suppress pageerror events caused by https://github.com/OfficeDev/office-ui-fabric-react/issues/9715 (I thought this was being caused by the animation disabling at first, but it turns out to be unrelated; you can repro this even without applying disableAnimations)

test: improve e2e reliability around animation disablement events

---

src/tests/end-to-end/common/page-controllers/page.ts

e2e-reliability CI build for https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=27762 hit a failure where it tried to getOuterHTMLOfSelector against an element that wasn't yet present on the page. This PR makes that helper more reliable by having it wait for the element to exist on the page (with the normal timeout) prior to grabbing its snapshot.

test: waitForSelector before evaling against it in getOuterHTMLOfSelector

---

src/DetailsView/detailsView.html
src/Devtools/devtools.html
src/assessments/color/test-steps/flashing-text-example.html
src/background/background.html
src/insights.html
src/popup/popup.html
src/tests/end-to-end/test-resources/all.html
src/tests/end-to-end/test-resources/headings/all-level-headings.html
src/tests/end-to-end/test-resources/image/image-text.html
src/tests/end-to-end/test-resources/native-widgets/input-type-radio.html

In Firefox, HTML pages that don't have charsets specified explicitly cause console.errors. This fixes those errors by explicitly specifying the encoding we were previously using implicitly (utf-8).

chore: suppress character encoding console.errors

---

src/popup/Styles/popup.scss

For some time, the extension's popup window has used CSS that sets `body, html { height: 0px; }` as a workaround for a Chromium issue where, without that CSS, the popup window does not resize like it should when its content is zoomed in/out. It doesn't actually set the window height to 0; it forces it to dynamically fit the content.
(note that, due to a *separate* Chromium issue, you can't zoom in/out on the popup content directly; to observe this, you need to have the popup open while you're zooming in/out on a different extension page, like the details page)
In Firefox, the original workaround has the effect you would *actually* expect, and causes the popup window to be of 0 height, ie, invisible. Using `fit-content` instead of `0px` still achieves the desired dynamic zoom behavior in …

fix: avoid popup being invisible in Firefox

---

src/background/tab-controller.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/tests/unit/tests/background/tab-controller.test.ts
src/tests/unit/tests/popup/components/__snapshots__/popup-view.test.tsx.snap

Per both the [chrome.tabs docs](https://developer.chrome.com/extensions/tabs#method-getSelected) and [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/getSelected),
> `chrome.tabs.getSelected(integer windowId, function callback)`
> Deprecated since Chrome 33. Please use tabs.query {active: true}.
I hit this last week when experimenting with Firefox support; in Chrome, the deprecated API still works, but in Firefox, the API is not implemented. But regardless of when we get to Firefox support more broadly, it's good to stop using the deprecated thing.

chore: replace use of deprecated chrome.tabs.getSelected API

---

src/tests/end-to-end/common/page-controllers/page.ts

This PR addresses a class of e2e flakiness (#867) with the signature of "some button had been loaded into the DOM, but when we clicked on it, nothing happened". We were seeing this in about 5% of runs before this change. With this change, 135 runs never showed this class of issue (15x9: [1](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=28624) [2](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=28625) [3](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=28626) [4](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=28809) [5](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=28810) [6](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=288 …

test: add a workaround for various flaky e2e click operations

---

build.yaml
pipeline/electron-e2e-test.yaml
pipeline/electron/electron-e2e-publish-results.yaml
pipeline/electron/electron-e2e-test-interactive.yaml
pipeline/electron/electron-e2e-test-linux.yaml

PR #1001 added some electron e2e tests. This PR runs those tests on mac, linux, and windows as a part of the PR/CI builds. Since the linux agents appear to be non-interactive, we have to use xvfb to run tests on them.

Add cross platform electron e2e tests to PR build

---

src/DetailsView/components/failure-instance-panel-control.tsx
src/tests/unit/tests/DetailsView/components/failure-instance-panel-control.test.tsx

Clears the PathSnippet store *only* on the refresh of the Details View Page (not the Target Page) to follow the behavior of the comment in the Failure Instance Panel. We do this by clearing the store within the panel's ComponentDidMount in order to clear on the first render of the panel as it is inserted into the DOM. This means the PathSnippet store is cleared twice per panel usage (once on open and once on close) we decided to keep it this way in case we changed refresh behavior in the future/just to be safer.

clear path on refresh of detailsview

---

build.yaml
electron-builder.yml
package.json
pipeline/electron/distribute-electron.yaml

We build a mac executable in ADO and introduce an electron-builder YML file that allows us to specify the app directory and mac target. This also removes unnecessary files from the resulting application, so we're in the 100-200 MB range.
There are opportunities to share agents between different jobs - it seems it might be easier to do this after our web e2e tests are back in.

Build mac executables in ADO

---

src/injected/instance-visibility-checker.ts
src/tests/unit/tests/injected/instance-visibility-checker.test.ts

Fix `no-string-based-set-interval` tslint error from TSA.

fix: fix tslint warning for string based timeout in setInterval

---

package.json
webpack.config.js
yarn.lock

Replaces the minifier we're using on prod builds from `uglify-js` to `terser`.
Terser is a more updated replacement for UglifyJS. Webpack 4 switched to using it as the default minifier in Nov 2018 (https://github.com/webpack/webpack/pull/8392). The reasons we'd want to switch:
* Unblocks future updates to typescript output target; uglify only supports up to ES5 javascript, Terser supports more recent javascript as input
* Closer to the "normal" webpack happy path
* As of recently, [more widely used (with webpack)](https://www.npmtrends.com/uglifyjs-webpack-plugin-vs-terser-webpack-plugin)
It is essentially a drop in replacement; we expect no customer-visible changes as a result of this update.
- [n/a] Added relevant unit test for your …

chore: replace uglifyjs with terser for minifying prod builds

---

build.yaml
src/electron/main/main.ts

Before this change, the generated installer from electron-builder is unable to access `deviceConnectView.html`. The page loads when running `yarn start:electron` but not in the generated executable. Including `path.resolve` allows us to get the path relative to the module we're in. We may improve this / change webpack instead when we solidify release strategy but in the meantime this PR fixes the CI/CD executable.
Download and try resulting executable here: https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=30829&view=logs

Modify file path of HTML file used in electron-builder's generated exe

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/assessment-instance-details-column.tsx
src/DetailsView/components/assessment-table-column-config-handler.tsx
src/DetailsView/components/failure-instance-panel-control.tsx
src/DetailsView/components/failure-instance-panel-details.tsx
src/DetailsView/components/generic-panel.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/failure-instance-panel-control.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/failure-instance-panel-details.test.tsx.snap
src/tests/unit/tests/DetailsView/components/assessment-table-column-config-handler.test.tsx
src/tests/unit/tests/DetailsView/components/failure-instance-panel-control.test.tsx

CSS fixes to match Figma. Changes occur on the Failure Instance Panel as well as the list of Failure Instances that grows on the main page as you add new Failure Instances.
To Note:
-- Duplicated JS functions to set the style of two TextFields (Comment in FIPC and CSS Selector in FIPD)
-- Still working with Fer and Chelsea to decide if we want to change the wording on the Validate Selector button
-- Path Snippet Store changes are coming in separate PR
-- Changes on the screen where you click to open the panel (with the list of added failure instances) is NOT behind feature flag (approved by Fer as long as I implemented her thoughts correctly)
-- Footer should have a bar above it, but that's for a Panel and we use a GenericPanel (may be another Fabric version issue as well)
-- Can't add …

Adding CSS to Failure Instance Panel

---

src/issue-filing/services/azure-boards/azure-boards-issue-filing-settings.tsx
src/issue-filing/services/azure-boards/create-azure-boards-issue-filing-url.ts
src/tests/unit/tests/issue-filing/services/azure-boards/create-azure-boards-issue-filing-url.test.ts

When a user chooses the "Description" work item field in ADO bug filing, we should create an "issue" work item instead of a "bug" work item. This results from discussion in #1009.

Use issue instead of bug when description is chosen

---

src/DetailsView/details-view-renderer.tsx
src/common/document-manipulator.ts
src/injected/visualization/base-drawer.ts
src/injected/visualization/drawer-utils.ts
src/injected/visualization/highlight-box-drawer.ts
src/injected/visualization/svg-drawer.ts
src/popup/components/diagnostic-view-toggle-factory.tsx
src/popup/components/diagnostic-view-toggle.tsx
src/popup/incompatible-browser-renderer.tsx
src/popup/main-renderer.tsx
src/scanner/axe-options.ts
src/scanner/launcher.ts
src/scanner/scan-options.ts
src/scanner/scan-parameter-generator.ts
src/tests/unit/common/test-document-creator.ts
src/tests/unit/tests/DetailsView/details-view-renderer.test.tsx
src/tests/unit/tests/injected/visualization/drawer.test.ts
src/tests/unit/tests/injected/visualization/single-target-drawer.test.ts
src/tests/unit/tests/injected/visualization/svg-drawer.test.ts
src/tests/unit/tests/popup/incompatible-browser-renderer.test.tsx
src/tests/unit/tests/popup/main-renderer.test.tsx
src/views/insights/renderer.tsx

Updating from Typescript 2.9 to 3.5 results in a variety of errors that look like this:
```
ERROR in Q:/repos/accessibility-insights-web/src/common/document-manipulator.ts(4,42):
TS2304: Cannot find name 'NodeSelector'.
```
It looks like https://github.com/microsoft/TSJS-lib-generator/pull/647 was the point where it was removed, merged into a separate `ParentNode` interface. We considered using `ParentNode` instead here, but `Document` seemed closer to the intended usage in most cases and led to the tests working more similarly to the product code than anything else, so that's what I went with.
Replacing the usages with Document is a no-op in Typescript 2.9 (so nice to do as a separate PR, to make the eventual Typescript upgrade PR smaller). It also forces the affected tests to be a …

refactor: replace NodeSelector with Document in preparation for Typescript upgrade

---

Gruntfile.js
package.json
pipeline/build-all-job-per-environment.yaml
pipeline/build-reliability.yaml
src/common/html-element-utils.ts
src/injected/analyzer-state-update-handler.ts
src/injected/drawing-controller.ts
src/injected/frameCommunicators/frame-communicator.ts
src/injected/frameCommunicators/html-element-axe-results-helper.ts
src/injected/frameCommunicators/window-message-handler.ts
src/injected/tab-stops-listener.ts
src/tests/unit/common/html-collection-of-builder.ts
src/tests/unit/tests/DetailsView/components/failure-instance-panel-control.test.tsx
src/tests/unit/tests/common/html-element-utils.test.ts
src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
src/tests/unit/tests/injected/drawing-controller.test.ts
src/tests/unit/tests/injected/frameCommunicators/frame-communicator.test.ts
src/tests/unit/tests/injected/frameCommunicators/html-element-axe-results-helper.test.ts
src/tests/unit/tests/injected/frameCommunicators/window-message-handler.test.ts
src/tests/unit/tests/injected/visualization/highlight-visualization.test.tsx
src/tests/unit/tests/popup/components/__snapshots__/launch-panel-header.test.tsx.snap
src/views/content/content-page.tsx
tsconfig.json
yarn.lock

Updates typescript to the latest stable version.
The notable ancillary changes this required were:
* This update increased the amount of memory used by webpack-all to a tipping point where it began occasionally crashing without finishing. Uses `grunt-concurrent` to have build:all run 3 instances of webpack rather than 1 instance of webpack building 3 configs
* Document.getElementsByTagName was updated to return `HTMLCollectionOf<Element>` instead of `NodeListOf<Element>`; there was a cascading series of type and test updates in response to this
* `MessageEvent`s were generalized to allow events from more than just `Window`s as sources; updated `window-message-handler` with an `e.source as Window`, since it knows it will only register to receive messages from `Window`s.
* Removed a few …

chore: Update typescript to 3.5.3

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/failure-instance-panel-control.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/failure-instance-panel-control.test.tsx.snap
src/tests/unit/tests/DetailsView/components/failure-instance-panel-control.test.tsx

The default failure instance comment view in Canary was inadvertently touched in PR #1063 - this PR reverts some of those changes. We will reintroduce the styling updates so they are fully contained inside the feature-flag in a separate PR.
The side effect of this PR is that the feature-flag-on experience no longer has an absolute footer for the add/cancel buttons. We will re-add this soon.
Before:
After:
- [no] Addresses an existing issue: Fixes #0000

Updating CSS of instance failure details pane

---

Gruntfile.js
src/electron/device-connect-view/Styles/deviceconnectview.scss
src/electron/device-connect-view/components/window-footer.scss
src/electron/device-connect-view/components/window-footer.tsx
src/electron/device-connect-view/components/window-title.scss
src/electron/device-connect-view/components/window-title.tsx
src/electron/device-connect-view/device-connect-view-initializer.ts
src/electron/device-connect-view/device-connect-view-renderer.tsx
src/electron/device-connect-view/device-connect-view.scss
src/electron/device-connect-view/deviceConnectView.html
src/electron/main/main.ts
src/tests/electron/main.test.ts
src/tests/unit/electron/device-connect-view/components/__snapshots__/window-footer.test.tsx.snap
src/tests/unit/electron/device-connect-view/components/__snapshots__/window-title.test.tsx.snap
src/tests/unit/electron/device-connect-view/components/window-footer.test.tsx
src/tests/unit/electron/device-connect-view/components/window-title.test.tsx
src/tests/unit/electron/device-connect-view/device-connect-view-renderer.test.tsx

Currently, the electron app displays some placeholder text. This PR is the first step on the way towards the app actually resembling our design. It removes the default title bar and frame and adds a new logo, title, and cancel button.

Update electron device-connect-view title bar (and more)

---

package.json
src/tests/electron/common/element-identifiers/common-selectors.ts
src/tests/electron/main.test.ts
yarn.lock

Add an extra check to the the E2E tests for the electron API so far. We needed access to the WebdriverIO types (version 4.8.0), which undergird the spectron types. The changes to package.json and yarn.lock were both tool-driven in response to the following command:
yarn add webdriverio@4.8.0 -D

Add E2E code to check for cancel button

---

package.json
yarn.lock

Fix `cryptiles` and `hoek` security vulnerabilities by upgrading `webdriverio` to `^4.13.0`.
The change doesn't hurt us as the only place that package is used is `test:electron` and those test pass properly after upgrade too.

fix: fix security vulnerabilities by upgrading webdriverio package

---

src/DetailsView/Styles/detailsview.scss

Chrome injects default values for ```font-family``` and ```font-size``` at the ```body``` level (see #1080 for more info). In the Details View -> Assessment-> [any requirement], we are not overriding ```font-size``` so we're getting chrome's default value (```75%```). Instead, we should explicitly override ```font-size``` for the ```body```.
**before**
**after**
- does not affect code
- not affected

fix: body font-size set to 75%

---

src/DetailsView/details-view-initializer.ts
src/background/issue-details-text-generator.ts
src/injected/dialog-renderer.tsx
src/issue-filing/common/issue-filing-url-string-utils.ts
src/tests/unit/tests/background/issue-details-text-generator.test.ts
src/tests/unit/tests/issue-filing/common/issue-filing-url-string-utils.test.ts

- fix logic to get last part of the selector to consider iframes
- basically split the selector using ```';'```
- apply the original logic to the last element of the splited selector
- update the class that generate the text for the "copy issue details" button to use the ```IssueUrlCreationUtils.getSelectorLastPart```
- as a result of this, I was able to remove duplicated code

fix: issue title generated contains the whole path for elements in iframe

---

src/DetailsView/Styles/detailsview.scss
src/common/styles/common.scss

Second half of fixing #1088. A regression between chrome 75 and 76 broke the scrolling behavior of the assessment overview page, resulting in multiple redundant scrollbars and a malformed size on the left nav area. This addresses both issues.
This does *not* address the test details rows being misaligned; see separate PR #1096 for that.
Before:
After:

fix: prevent redundant assessment overview page scroll bars 

---

src/reports/components/assessment-summary-details.scss
src/reports/components/assessment-summary-details.tsx
src/tests/unit/tests/reports/components/__snapshots__/assessment-summary-details.test.tsx.snap

Fixes overview test summary alignment issue noted in #1088 caused by now having an odd number of tests in the table.
Also included:
* Increasing the column gap per @cheade 's recommendation (the columns were too close together at low widths and ended up overlapping a bit, see first "before" screenshot below)
* Adding a min-width for the individual rows (prevents the bad overflow at certain breakpoint widths, see second "before" screenshot below)
This does *not* fix the the excessive scrollbars/bad left test nav sizing also noted in #1088 (fixing that is proving much trickier; leaving it for a separate PR)
Before:
After:

fix: resolve alignment issues in assessment overview

---

src/background/issue-details-text-generator.ts
src/tests/unit/tests/background/issue-details-text-generator.test.ts

We should normalize `IssueDetailsTextGenerator` to use `IssueDetailsBuilder`, which is the generic issue details implementation we have for issue filing and it's being used for azure board and github, that way, we remove duplicated code and thus have only one place to change if we need to update issue details content.
Before actually doing that, this PR remove some other duplicated code:
- `getTitle`
- `standardizeTags`
It does so by using `IssueUrlCreationUtils` version of this functions.

refactor: use IssueUrlCreationUtils on IssueDetailsTextGenerator

---

src/tests/electron/common/element-identifiers/common-selectors.ts
src/tests/electron/main.test.ts

Add more useful E2E tests of the electron device connect dialog. Validates interaction of the controls while entering a port number

Add more E2E tests for device connect

---

src/DetailsView/Styles/detailsview.scss
src/common/styles/common.scss

This reverts commit 1ff86174ffc81f50483ad3805182e7e9befd77c3 to avoid #1112.
#1098 accidentally caused #1112 while fixing #1118. #1112 is a more impactful bug, so we're reverting the fix until Chromium 77 reaches stable, when we can un-revert it (since Chromium 77 incidentally fixes #1112).
- [n/a, see #1098] (UI changes only) Added screenshots/GIFs to description above
- [n/a, revert] (UI changes only) Verified usability with NVDA/JAWS

fix: revert #1098 to fix #1112

---

src/DetailsView/details-view-initializer.ts
src/background/issue-details-text-generator.ts
src/injected/dialog-renderer.tsx
src/issue-filing/common/create-issue-details-builder.ts
src/issue-filing/common/markup/html-formatter.ts
src/issue-filing/common/markup/markdown-formatter.ts
src/issue-filing/common/markup/markup-formatter.ts
src/issue-filing/common/markup/plain-text-formatter.ts
src/tests/unit/tests/background/issue-details-text-generator.test.ts
src/tests/unit/tests/issue-filing/common/__snapshots__/issue-details-builder.test.ts.snap
src/tests/unit/tests/issue-filing/common/issue-details-builder.test.ts
src/tests/unit/tests/issue-filing/common/markup/html-formatter.test.ts
src/tests/unit/tests/issue-filing/common/markup/markdown-formatter.test.ts
src/tests/unit/tests/issue-filing/common/markup/plain-text-formatter.test.ts

`IssueDetailsTextGenerator` is used on the "copy failure details" button but it has duplicated logic (that we have in a generic implementation under issue filing for git hub and azure boards).
This PR refactors `IssueDetailsTextGenerator` to use `IssueDetailsBuilder` instead of having it's own logic about the issue details content. In order to do that, I had to update `IssueDetailsBuilder` to account for some style differences between file a bug and copy failure details. I've also add a new markup formatter: plain text formatter.
After this refactor, the main section of the issue details will be hold on one place only: `IssueDetailsBuilder`
**Notes for the reviewer**
- It may be helpful to review commit per commit as the first 5 commits revolve around supporting the refactor on the …

refactor: IssueDetailsTextGenerator to use IssueDetailsBuilder

---

src/electron/device-connect-view/components/device-connect-body.tsx
src/electron/device-connect-view/components/device-connect-port-entry.tsx
src/tests/unit/electron/device-connect-view/components/__snapshots__/device-connect-body.test.tsx.snap
src/tests/unit/electron/device-connect-view/components/__snapshots__/device-connect-port-entry.test.tsx.snap
src/tests/unit/electron/device-connect-view/components/device-connect-body.test.tsx
src/tests/unit/electron/device-connect-view/components/device-connect-port-entry.test.tsx

Currently in the device connect screen, if a user enters a port, validates it, and then changes the port, the state remains unchanged. That behavior makes it seem like the user has validated their newly entered port, which is not the case. This PR updates the behavior such that whenever the user changes the port value, the state is restored to the original, pre-validation state. There are no actual UI/visual changes.
GIF of state change (same effect for connection success and failure):
- [-] Addresses an existing issue: Fixes #0000
- [-] (UI changes only) Added screenshots/GIFs to description above
- [-] (UI changes only) Verified usability with NVDA/JAWS

Revert device connect state if port number changes

---

src/injected/adapters/scan-results-to-unified-rules.ts
src/tests/unit/tests/injected/adapters/scan-results-to-unified-rules.test.ts

`scan-results-to-unified-rules` parses `scanResults` input and returns an array of `UnifiedRule`. We decided to get the rules from scan results, so the unified results, which are also generated from scan results, and unified rules will correspond to the same data.
*Note: We considered 2 approaches to check for duplicate rules in the results: using a Set of ruleIds or checking the UnifiedRule array directly, as rules are added to it. When run on inputs of 2,000 and 20,000 scan results, the implementation **with the Set** took 55ms and 501ms, respectively, while the implementation **without the Set** took 117ms and 3276ms, respectively. Since using the Set could save a significant amount of time, we decided to add the set back in exchange for the extra space complexity.* …

Introduce adapter for scan results to unified rules

---

src/assessments/contrast/assessment.tsx
src/assessments/contrast/test-steps/graphics.tsx
src/assessments/contrast/test-steps/test-steps.ts
src/assessments/images/test-steps/images-of-text.tsx
src/common/types/property-bag/meaningful-image.ts
src/content/test/contrast/graphics.tsx
src/content/test/contrast/index.ts
src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap

Adds the new Graphics requirement, using the existing visualizer rules for meaningful images.
Filled in the test content per the spec document, left the guidance content as a TODO placeholder since we don't have a written yet.

feat: add Graphics requirement to new Contrast assessment test

---

src/DetailsView/components/cards/collapsible-component-cards.scss
src/DetailsView/components/cards/collapsible-component-cards.tsx
src/DetailsView/components/cards/rules-with-instances-v2.scss
src/DetailsView/components/cards/rules-with-instances-v2.tsx
src/tests/unit/tests/DetailsView/components/cards/__snapshots__/rules-with-instances-v2.test.tsx.snap
src/tests/unit/tests/DetailsView/components/cards/rules-with-instances-v2.test.tsx
src/tests/unit/tests/common/components/__snapshots__/collapsible-component-cards.test.tsx.snap
src/tests/unit/tests/common/components/collapsible-component-cards.test.tsx

Re-uses the original collapsible component we have but modifies classes heavily based on the styles we are using in the report. As such, made sense to separate this out. Eventually, I can see the collapsible styles from details-view belonging to a component that wraps this component with the styles in it's own scss files.

feat: Introduce new collapsible component for cards UI

---

src/content/link.tsx
src/content/test/contrast/graphics.tsx
src/content/test/contrast/guidance.tsx
src/content/test/contrast/state-changes.tsx
src/content/test/contrast/ui-components.tsx
src/content/test/text-legibility/contrast.tsx
src/content/test/text-legibility/guidance.tsx
src/content/test/text-legibility/resize-text.tsx
src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap

Adds in the missing top-level Contrast test guidance and the Graphics requirement's info and examples content.
Also refactored the link to Presbyopia that was repeated in a bunch of spots.

feat: fill in remaining guidance content for Contrast test

---

package.json
src/tests/unit/tests/injected/visualization/drawer.test.ts
yarn.lock

- upgrade Typescript from 3.5.3 to 3.6.2
- make it happen by removing a function's type which was `typeof window.setTimeout`.

chore: upgrade ts from 3.5.3 to 3.6.2

---

src/DetailsView/details-view-initializer.ts

We were missing the tab id in our unified results store. This leads to problems where opening a new tab resets the existing store state. This PR adds the tab id to our store so that messages are appropriately scoped to their tabs. We should consider refactoring this in the future so that the tab id is not set separately from the constructor.
- [] Addresses an existing issue: Fixes #0000
- [] Added relevant unit test for your changes. (`yarn test`)
- [] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`

fix: set tabId of unified results store

---

src/DetailsView/components/cards/failed-instances-section-v2.tsx
src/common/rule-based-view-model-provider.ts
src/tests/unit/common/rule-based-view-model-provider.test.ts
src/tests/unit/tests/DetailsView/components/cards/__snapshots__/failed-instances-section-v2.test.tsx.snap
src/tests/unit/tests/DetailsView/components/cards/failed-instances-section-v2.test.tsx

Previously, we were treating the null scenario as the empty scenario and this was causing some issues in the UI.

feat: view model provider handles null case separately than empty/pass scenario

---

src/DetailsView/components/cards/failed-instances-section-v2.tsx
src/tests/unit/tests/DetailsView/components/cards/__snapshots__/failed-instances-section-v2.test.tsx.snap
src/tests/unit/tests/DetailsView/components/cards/failed-instances-section-v2.test.tsx

This PR updates the failure instance count so it includes the flattened list of results, not the number of rules.

Update failure count instance in cards UI so it includes number of elements instead of number of rules

---

src/assessments/custom-widgets/test-steps/expected-input.tsx
src/assessments/native-widgets/test-steps/autocomplete.tsx
src/assessments/native-widgets/test-steps/expected-input.tsx
src/assessments/text-legibility/test-steps/text-spacing.tsx
src/content/test/custom-widgets/expected-input.tsx
src/content/test/custom-widgets/index.ts
src/content/test/native-widgets/autocomplete.tsx
src/content/test/native-widgets/expected-input.tsx
src/content/test/native-widgets/index.ts
src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap

Fixes a variety of minor text issues caught during 2.9.0 validation (doing these in one batch to avoid having to spend a half hour waiting for snapshot updates)
* #1184: Text legibility -> Text spacing bookmarklet instructions unclear about how to drag link to bookmarks
* #1185: Autocomplete>more info and examples > example table extra line
* #1189: Label requirement name didnt got changed in info & examples section
* Item 1 from #1190: Autocomplete requirement has a couple text issues

fix: assorted minor text issues caught during 2.9.0 validation

---

src/DetailsView/components/failure-instance-panel-control.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/failure-instance-panel-control.test.tsx.snap

The mocks in #1167 show a placeholder for the comment textbox. This PR adds the placeholder.

Add placeholder to comment field in failure instance panel details

---

src/assessments/text-legibility/test-steps/text-spacing.tsx

removed the unnecessary line from the text spacing instructions; no longer tells users to change their zoom to 400%
Updated instructions pictured below: 
- N/A Added relevant unit test for your changes. (`yarn test`)
- N/A Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`

fix: removed the unnecessary line from the text spacing instructions

---

src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts
src/tests/unit/tests/background/telemetry/telemetry-state-listener.test.ts
src/tests/unit/tests/common/components/__snapshots__/guidance-tags.test.tsx.snap
src/tests/unit/tests/common/components/guidance-tags.test.tsx
src/tests/unit/tests/common/get-guidance-tags-from-guidance-links.test.ts
src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
src/tests/unit/tests/injected/components/__snapshots__/issue-details-navigation-controls.test.tsx.snap
src/tests/unit/tests/injected/components/details-dialog.test.tsx
src/tests/unit/tests/injected/components/issue-details-navigation-controls.test.tsx
src/tests/unit/tests/injected/layered-details-dialog-component.test.tsx
src/tests/unit/tests/issue-filing/common/__snapshots__/http-query-builder.test.ts.snap
src/tests/unit/tests/issue-filing/common/http-query-builder.test.ts
src/tests/unit/tests/issue-filing/services/azure-boards/azure-boards-issue-filing-service.test.tsx
src/tests/unit/tests/issue-filing/services/github/github-issue-filing-service.test.tsx
src/tests/unit/tests/issue-filing/services/null-issue-filing-service/null-issue-filing-service.test.tsx
src/tests/unit/tests/popup/target-tab-finder.test.ts
src/tests/unit/tests/scanner/custom-rules/css-content-rule.test.ts
src/tests/unit/tests/scanner/custom-rules/css-positioning-rule.test.ts

Some of the tests had a `snapshot` obsolete problem on my MacOS.
When trying to figure out the reason for that, i figured it out and @dbjorge confirmed, that it might be because of the usage of `%o` in the `test.each` statement rather than `%p`; which results in different snapshot value for different node version.
With this change; we make sure that the tests pass for users who are using node version higher than 10.16.3.
PS: `%p` also makes the snapshots more readable as it doesn't prints out the unwanted properties from the object as done by `%o`

chore: update tests to use %p rather than node version dependent %o

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/cards/collapsible-component-cards.scss
src/DetailsView/components/cards/collapsible-component-cards.tsx
src/DetailsView/components/cards/how-to-fix-card-row.scss
src/DetailsView/components/cards/result-section-title-v2.tsx
src/DetailsView/components/cards/result-section-title.scss
src/DetailsView/components/cards/result-section-v2.tsx
src/DetailsView/components/cards/result-section.scss
src/DetailsView/components/cards/rule-resources.scss
src/DetailsView/components/cards/rules-with-instances-v2.scss
src/common/styles/common.scss
src/tests/unit/tests/DetailsView/components/cards/__snapshots__/result-section-title-v2.test.tsx.snap
src/tests/unit/tests/DetailsView/components/cards/__snapshots__/result-section-v2.test.tsx.snap
src/tests/unit/tests/DetailsView/components/cards/result-section-title-v2.test.tsx
src/tests/unit/tests/common/components/__snapshots__/collapsible-component-cards.test.tsx.snap
src/tests/unit/tests/common/components/collapsible-component-cards.test.tsx
webpack.config.js

This adds css from either reports or modifies CSS in details view css to improve the cards UI.
Changes to details view were required in a few cases to adjust the margins correctly (and also to improve the UI otherwise).

Improved CSS for cards components

---

src/assessments/color/test-steps/use-of-color.tsx

I clarified the instructions for the Sensory test, Use of Color, per Lisa Louise's suggestion. 
The text now reads as:
- [N/A] Added relevant unit test for your changes. (`yarn test`)

clarified the Sensory Test, Use of Color instructions per Lisa Louise's suggestions

---

Gruntfile.js
src/DetailsView/bundled-details-view-styles.ts
src/DetailsView/components/cards/collapsible-component-cards.scss
src/DetailsView/components/cards/result-section-title-v2.tsx
src/DetailsView/components/cards/result-section-title.scss
src/reports/assessment-report-html-generator.tsx
src/reports/assessment-report.styles.ts
src/reports/automated-checks-report.scss
src/reports/components/report-head.tsx
src/reports/components/report-sections/collapsible-result-section.tsx
src/reports/components/report-sections/result-section.tsx
src/tests/unit/tests/DetailsView/components/cards/__snapshots__/result-section-title-v2.test.tsx.snap
src/tests/unit/tests/reports/assessment-report-html-generator.test.tsx
src/tests/unit/tests/reports/components/__snapshots__/report-head.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/collapsible-result-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/result-section.test.tsx.snap

We embed styles for report components. Previously, we had a specific "report-wide" css file we would embed for each report. However, ideally we'd like to be able to share components across reports and our normal UI, where we can use css-modules. This PR allows us to do that.
Effectively, we have to move embed styles to become a task that will happen after webpack has run so that we have the generated bundle css file. As a result, you'll see that embed styles now looks at the bundled folder and happens as a part of drop (before anything else; this part is open to changing to be honest). This also means that we have to modify our older scss file references slightly as the working directly changes to the bundled folder. We also need to copy these scss files to the extension folder so they …

use bundled details-view styles in reports

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/overview-content/help-links.scss
src/DetailsView/components/overview-content/help-links.tsx
src/DetailsView/components/overview-content/overview-content-container.scss
src/DetailsView/components/overview-content/overview-content-container.tsx
src/DetailsView/components/overview-content/overview-heading.scss
src/DetailsView/components/overview-content/overview-heading.tsx
src/DetailsView/components/overview-content/overview-help-section.scss
src/DetailsView/components/overview-content/overview-help-section.tsx
src/DetailsView/components/requirement-link.scss
src/DetailsView/components/requirement-link.tsx
src/DetailsView/components/target-page-closed-view.scss
src/DetailsView/components/target-page-closed-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-link.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-closed-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/overview-content/__snapshots__/help-links.test.tsx.snap
src/tests/unit/tests/DetailsView/components/overview-content/__snapshots__/overview-content-container.test.tsx.snap
src/tests/unit/tests/DetailsView/components/overview-content/__snapshots__/overview-heading.test.tsx.snap
src/tests/unit/tests/DetailsView/components/overview-content/__snapshots__/overview-help-section.test.tsx.snap
src/tests/unit/tests/DetailsView/components/overview-content/help-links.test.tsx
src/tests/unit/tests/DetailsView/components/overview-content/overview-heading.test.tsx
src/tests/unit/tests/DetailsView/components/overview-content/overview-help-section.test.tsx
src/tests/unit/tests/DetailsView/components/target-page-closed-view.test.tsx

The commits do a good job of telling the general update in this PR. I've created css modules for:
- requirement link
- target page closed view
- overview components (help, heading, etc)
and additionally improve the css a bit for target page closed view (screenshot added) and removing some dead css which was not being used. I also updated to only have snapshot tests to align with our current testing methodology.
Updated view of the target paged closed view:

chore: Clean detailsview.scss by moving component css to modules + remove some dead styles

---

src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/end-to-end/common/page-controllers/details-view-page.ts

This PR' is part of PRs which try to reduce some of the inconsistency that we are getting with our e2e reliability build.
PR tries to improve e2e reliability by waiting for selector (checked=true) when we are trying to toggle high contrast on.
This test was chosen because the high contrast mode validation selector (`body.high-contrast-theme`) was not being found during a lot of test failures (as per ADO test analytics). This changes makes sure that we look for that selector only after toggle is checked to true.

test: Part - 2 high contrast e2e - wait for toggle state to be changed to checked before proceeding further when toggling high contrast mode

---

src/electron/device-connect-view/components/device-connect-port-entry.tsx
src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/device-connect-port-entry.test.tsx.snap
src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/electron-external-link.test.tsx.snap
src/tests/unit/tests/electron/device-connect-view/components/device-connect-port-entry.test.tsx
src/tests/unit/tests/electron/device-connect-view/components/electron-external-link.test.tsx

While looking at the electron app code to get familiar before starting a new feature, @JGibson2019 and I did some small clean up refactoring on components and tests.
One thing that caught our attention: `DeviceConnectPortEntry` uses an `async` `onClick` function for the primary `Button` it uses. I think this is the first time I see and async onClick function on our code base. Looking at the tests, we found a call to `setInmediate`. Again, this was odd as is the first time I see this on our code base. Playing around with the test code, we figure out this two things were related (async onClick function and setInmediate on the test). Because the onClick function is async, you need to wait (somehow) for it to finish before asserting on the tests (e.g calling `verifyAll` on a mock) but enzyme …

refactor: minor clean up on components/tests

---

src/electron/device-connect-view/components/device-connect-header.tsx
src/electron/device-connect-view/components/electron-external-link.tsx
src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/device-connect-header.test.tsx.snap
src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/electron-external-link.test.tsx.snap
src/tests/unit/tests/electron/device-connect-view/components/electron-external-link.test.tsx

Updated `ElectronExternalLinkProps` to contain 'children' property instead of 'text' so its usage is similar to that of `NewTabLink`. This is one of the steps to allow for the reuse of the `TelementryPermissionDialog`, which contains the `telemetryPopupNotice` that uses `NewTabLink`. Will update `telemetryPopupNotice` to be able to use `NewTabLink` or `ElectronExternalLink` in a future PR.

refactor: electron external link props

---

src/common/components/new-tab-link.tsx
src/tests/unit/tests/common/components/__snapshots__/new-tab-link.test.tsx.snap
src/tests/unit/tests/common/components/new-tab-link.test.tsx

Make our `NewTabLink` component a `NamedSFC`.

refactor: convert NewTabLink to a NamedSFC

---

src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-dropdown.test.tsx.snap
src/tests/unit/tests/DetailsView/components/details-view-dropdown.test.tsx

We have some warnings showing up on our unit test runs. Some of them are around react deprecated notices:
In this case, we're not explicitly using `componentWillMount` but I noticed that updating the test to use snapshot fix the warning.
- not affected
- not affected

refactor: use snapshot to test component render

---

src/tests/unit/tests/DetailsView/components/switcher.test.tsx

Switcher test (`src\tests\unit\tests\DetailsView\components\switcher.test.tsx`) is showing warnings (while running the unit tests): **componentWillRecieveProps has been renamed...**
The warning mention to update `DropdownBase` which is on the office fabric side (one more reason to update our office ui fabric version) but we can fix this warning by not `mount`ing the tested component. Instead, we can use `shallow` which will not call to the base component.
- not affected
- not affected
- not affected

refactor: use shallow to fix react warning

---

src/background/actions/action-creator.ts
src/background/actions/assessment-action-creator.ts
src/background/actions/content-action-creator.ts
src/background/actions/details-view-action-creator.ts
src/background/actions/dev-tools-action-creator.ts
src/background/actions/inspect-action-creator.ts
src/background/actions/path-snippet-action-creator.ts
src/background/actions/scoping-panel-action-creator.ts
src/background/actions/tab-action-creator.ts
src/background/actions/unified-scan-result-action-creator.ts
src/background/global-context-factory.ts
src/background/tab-context-factory.ts
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/actions/assessment-action-creator.test.ts
src/tests/unit/tests/background/actions/content-panel-action-creator.test.ts
src/tests/unit/tests/background/actions/details-view-action-creator.test.ts
src/tests/unit/tests/background/actions/dev-tools-action-creator.test.ts
src/tests/unit/tests/background/actions/inspect-action-creator.test.ts
src/tests/unit/tests/background/actions/path-snippet-action-creator.test.ts
src/tests/unit/tests/background/actions/scoping-panel-action-creator.test.ts
src/tests/unit/tests/background/actions/tab-action-creator.test.ts
src/tests/unit/tests/background/actions/unified-scan-result-action-creator.test.ts
src/tests/unit/tests/background/global-action-creators/action-creator-test-helpers.ts
src/tests/unit/tests/background/global-action-creators/feature-flags-action-creator.test.ts
src/tests/unit/tests/background/global-action-creators/scoping-action-creator.test.ts
src/tests/unit/tests/background/global-action-creators/user-configuration-action-creator.test.ts

While working on implementing the flux architecture for the electron app, I found we should be able to reuse the background-side action creators from the browser extension, but in order to do so, it is needed that all action creators are "created equal" (in the sense of using the `Interpreter` to register callbacks for messages instead of directly using `registerTypeToPayloadCallback` to do so).
This PR update all action creators (and tests) to use `Interpreter` directly.
- not affected
- not affected

refactor: using Interpreter across all action creators

---

Gruntfile.js

`yarn build` failed when being run from a file path where a folder had a space in it. Wrapping path.resolve() calls in Gruntfile tasks with double quotes to prevent the issue.

refactor: Wrapping the output of path.resolve in Gruntfile with double quotes.

---

src/background/actions/content-action-creator.ts
src/background/actions/dev-tools-action-creator.ts
src/background/actions/tab-action-creator.ts
src/background/interpreter.ts
src/common/message.ts
src/tests/unit/tests/background/interpreter.test.ts

_**Note**: This is part of the Telemetry Opt-In feature for electron AI_
Make `PayloadCallback` type use a template type for the `payload` parameter. This way we have type info when calling `RegisterTypeToPayloadCallback` (usually on the action creators).
This is part of a bigger refactor where we're trying to make the action message creator and action creator to have the same public API, this way we can use one or the other on the view. The use case for this is the telemetry opt in dialog, which is currently being use on the popup and we want to reuse on the electron app.
- not affected
- not affected

refactor: Make PayloadCallback a more strict type

---

src/background/background-init.ts
src/background/get-persisted-data.ts
src/common/constants.ts
src/common/indexedDB/get-indexeddb-store.ts
src/common/indexedDB/indexedDB.ts
src/electron/device-connect-view/device-connect-view-initializer.ts
src/tests/unit/tests/background/get-persisted-data.test.ts

Create UserConfigStore in device-connect-view-initializer.ts for electron initialization with UserConfig persisted data.

feature: create UserConfigStore in electron view initializer

---

src/background/actions/user-configuration-actions.ts
src/background/global-action-creators/registrar/register-user-configuration-message-callbacks.ts
src/background/global-action-creators/user-configuration-action-creator.ts
src/background/global-context-factory.ts
src/background/stores/global/user-configuration-store.ts
src/common/components/telemetry-permission-dialog.tsx
src/tests/unit/tests/background/global-action-creators/user-configuration-action-creator.test.ts
src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts
src/tests/unit/tests/common/components/telemetry-permission-dialog.test.tsx

Introduce `SetTelemetryStateMessageCreator` (implicitly implemented by `UserConfigMessageCreator` and `UserConfigurationActionCreator`) in order to be able to re-use `TelemetryPermissionDialog` on the electron app.
- not affected
- not affected

refactor: update TelemetryPermissionDialog to be used on electron app

---

src/common/components/enable-telemetry-setting-description.tsx
src/common/components/privacy-statement-text.tsx
src/common/components/telemetry-permission-dialog.tsx
src/content/settings/improve-accessibility-insights.tsx
src/tests/unit/tests/common/components/__snapshots__/enable-telemetry-setting-description.test.tsx.snap
src/tests/unit/tests/common/components/__snapshots__/privacy-statement-text.test.tsx.snap
src/tests/unit/tests/common/components/__snapshots__/telemetry-permission-dialog.test.tsx.snap
src/tests/unit/tests/common/components/enable-telemetry-setting-description.test.tsx
src/tests/unit/tests/common/components/privacy-statement-text.test.tsx
src/tests/unit/tests/common/components/telemetry-permission-dialog.test.tsx

- Updated `PrivacyStatementText` and `PrivacyStatementPopupText` to be components that use `PrivacyStatementTextProps` and moved them to a new file `privacy-statement-text.tsx` from `improve-accessibility-insights`, so they can be reused in `TelemetryPermissionDialog` for web and electron
- Updated files where `PrivacyStatementText` and `PrivacyStatementPopupText` are used
- Updated relevant tests and snapshots

refactor: telemetry permission privacy statement text

---

package.json

This PR adds a `test:electron` step to `yarn precheckin` script in our `package.json`. This is to ensure that when developers run `precheckin` they can replicate all the checks that a normal `PR build/check` will have on github/azure-devops.
The build step; `build:all` is already validating build for electron.

chore: add test:electron step to yarn precheckin

---

src/electron/device-connect-view/components/device-connect-header.tsx
src/electron/device-connect-view/components/electron-link.tsx
src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/device-connect-header.test.tsx.snap
src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/electron-link.test.tsx.snap
src/tests/unit/tests/electron/device-connect-view/components/electron-link.test.tsx

While working on #1258 I found out we do not have a suitable candidate for the `LinkComponent` dependency of the telemetry opt in. The plan was to reuse `ElectronExternalLink` but this component expect a `shell` prop (which comes from the electron api).
This PR adds a wrapper component around the `ElectronExternalLink` so we don't need to pass the `shell` prop and we can use it for the `LinkComponent` dependency.
- not affected
- not affected

refactor: wrap ElectronExternalLink to not need shell prop

---

src/electron/device-connect-view/components/device-connect-view-container.tsx
src/electron/device-connect-view/components/telemetry-permission-dialog.scss
src/electron/device-connect-view/device-connect-view-initializer.ts
src/electron/device-connect-view/device-connect-view.scss
src/electron/main/main.ts
src/tests/electron/main.test.ts
src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/device-connect-view-container.test.tsx.snap
src/tests/unit/tests/electron/device-connect-view/components/device-connect-view-container.test.tsx
src/tests/unit/tests/electron/device-connect-view/device-connect-view-renderer.test.tsx

Wire up store, actions and action creator and render the telemetry opt in dialog base on user configuration from the persisted local storage.
- [] (UI changes only) Added screenshots/GIFs to description above
- [] (UI changes only) Verified usability with NVDA/JAWS

feat: wiring up telemetry opt in dialog

---

src/background/background-init.ts
src/background/telemetry/telemetry-client-provider.ts
src/tests/unit/tests/background/telemetry/telemetry-client-provider.test.ts

Currently, `getTelemetryClient` receives `userData: LocalStorageData` as it's first parameter. `LocalStorageData` includes feature flags, launch panel settings and installation data (among others) but `getTelemetryClient` only uses installation data, hence, it violates ISP.
Additionally, we would like to reuse `getTelemetryClient` on AI-mobile too, but right now, there is no need for launch panel settings or feature flag data.
This PR, update `getTelemetryClient` to use `InstallationData` directly making it abide ISP and to be more easy to reuse on AI-mobile.
- not affected
- not affected

refactor: telemetry client provider refactor

---

src/background/feature-flag-checker.ts
src/background/telemetry/telemetry-logger.ts
src/electron/common/rigged-feature-flag-checker.ts
src/tests/unit/tests/background/telemetry/telemetry-logger.test.ts
src/tests/unit/tests/electron/common/rigged-feature-flag-checker.test.ts

As part of reusing the Telemetry Opt In dialog from AI-Web on AI-Android, we need to reuse `TelemetryLogger`.
Currently, the logic of the logger is based on the `FeatureFlagController` (basically, log only when `logTelemetryToConsole` feature flag is on)
At this point, AI-Mobile doesn't have feature flags implemented.
In this PR we are:
- creating a type/interface for use in the `TelemetryLogger`
- creating a "fake" feature flag checker to be used on AI-Android.
- not affected
- not affected

refactor: introduce feature flag checker

---

src/background/telemetry/null-telemetry-client.ts
src/background/telemetry/telemetry-client-provider.ts
src/tests/unit/tests/background/telemetry/null-telemetry-client.test.ts

Currently, `AppInsightsTelemetryClient` takes in an instance of `ApplicationTelemetryDataFactory` as part of its constructor. `ApplicationTelemetryDataFactory` has data specific to the application, such as version, build, and installation ID. Refactoring `NullTelemetryClient` to also take in an instance of `ApplicationTelemetryDataFactory`, since the information provided by it could still be useful.

refactor: NullTelemetryClient to use ApplicationTelemetryDataFactory

---

src/background/background-init.ts
src/background/telemetry/application-telemetry-data-factory.ts
src/background/telemetry/telemetry-client-provider.ts
src/tests/unit/tests/background/telemetry/application-telemetry-data-factory.test.ts
src/tests/unit/tests/background/telemetry/telemetry-client-provider.test.ts

Currently, `ApplicationTelemetryDataFactory` has a couple of issues:
- it uses `title` as a hard dependency for the `applicationName` property. This means we cannot easily reuse this class on AI-Android, where the current value of `title` doesn't work (as it is `"Accessibility Insights for Web"`... note the **Web** in it)
- it expect an instance of a helper class to get the app version... since the app version doesn't change dynamically while running the app (extension or electron) we can change the param to be the version directly
- same goes for the build param
- not affected
- not affected

refactor: ApplicationTelemetryDataFactory

---

package.json
src/content/adhoc/color/guidance.tsx
src/content/link.tsx
src/scanner/axe-options.ts
src/scanner/rule-to-links-mappings.ts
src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap
src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
yarn.lock

This PR consumes axe-core 3.3.2 and includes:
- updates to rule-to-WCAG mappings, including `scrollable-region-focusable` and `label-content-name-mismatch` as `BestPractice` so they aren't run in the standard set
- an update to our `restoreScroll` option type, which [worked internally](https://github.com/dequelabs/axe-core/commit/d55f3cda4598320f8ee496684a01f8b9e1598f8d?short_path=8be2f64#diff-8be2f642524623d5012c7b2cf4fa4eb9) but wasn't included in axe.d.ts [until now](https://github.com/dequelabs/axe-core/pull/1697/files)
- updated launchpad & guidance snapshot
- update to color guidance to include interactive link to improve keyboard accessibility
example new rule result:
updated use-of-color guidance to include WCAG link:

Update to axe-core 3.3.2

---

src/electron/device-connect-view/components/device-connect-body.tsx
src/electron/device-connect-view/components/device-connect-port-entry.tsx
src/electron/device-connect-view/components/device-connect-view-container.tsx
src/electron/device-connect-view/device-connect-view-initializer.ts
src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/device-connect-body.test.tsx.snap
src/tests/unit/tests/electron/device-connect-view/components/__snapshots__/device-connect-view-container.test.tsx.snap
src/tests/unit/tests/electron/device-connect-view/components/device-connect-body.test.tsx
src/tests/unit/tests/electron/device-connect-view/components/device-connect-port-entry.test.tsx

As part of 'User Story 1604607: [4] add new telemetry event: validate port', we need to pass an action creator to 'DeviceConnectPortEntry' but right now we have not set up `deps` pattern into this component.
As part of this PR:
- Introduce `deps` into `DeviceConnectPortEntry`
- Pull up `fetchScanResults` dependency to the composition root and pass it down through the deps
- not affected
- not affected

refactor: introduce deps pattern into DeviceConnectPortEntry

---

src/common/extension-telemetry-events.ts
src/electron/adapters/electron-storage-adapter.ts
src/electron/common/electron-telemetry-events.ts
src/electron/device-connect-view/components/device-connect-port-entry.tsx
src/electron/device-connect-view/device-connect-view-initializer.ts
src/electron/flux/action-creator/device-connect-action-creator.ts
src/tests/unit/tests/electron/device-connect-view/components/device-connect-port-entry.test.tsx
src/tests/unit/tests/electron/flux/action-creator/device-connect-action-creator.test.ts

When the user clicks the "Validate port" button and if the user opt in to the telemetry, we'll be sending a `'VALIDATE_PORT'` telemetry event.
**Notes**
`applicationBuild` is properly set during the release process, that's why in the screenshot is `"unknownBuild"` which is a default value defined on `src\common\configuration\configuration-defaults.ts`, `telemetryBuildName` property.

feat: validate port telemetry event

---

src/DetailsView/components/cards/instance-details-v2.tsx
src/DetailsView/components/cards/rule-content-v2.tsx
src/reports/components/report-sections/collapsible-result-section.tsx
src/reports/components/report-sections/not-applicable-checks-section.tsx
src/reports/components/report-sections/passed-checks-section.tsx
src/reports/components/report-sections/report-section-factory.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/collapsible-result-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/not-applicable-checks-sections.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/passed-checks-sections.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/collapsible-result-section.test.tsx
src/tests/unit/tests/reports/components/report-sections/not-applicable-checks-sections.test.tsx
src/tests/unit/tests/reports/components/report-sections/passed-checks-sections.test.tsx

This change removes any use of the collapsible-container in our code-base by using the specified collapsible control in the report factory (which uses a new report specific collapsible control).

refactor: use collapsible control specified in report factory in all cases in report

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/failure-instance-panel-control.tsx
src/DetailsView/components/failure-instance-panel-details.tsx
src/DetailsView/components/failure-instance-panel.scss
src/reports/automated-checks-report.scss
src/tests/unit/tests/DetailsView/components/__snapshots__/failure-instance-panel-control.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/failure-instance-panel-details.test.tsx.snap

This moves the css for failure instance panel to it's own scss file and starts using it via css modules in the panel.
Also removed some more dead css.

refactor: updated failure instance panel styles to be utilized via css modules + remove dead css

---

README.md

Our readme has a line of text that asks user to install `yarn` if they dont already have yarn. Updating the hyperlink in that text to take user to installation page on the `yarn` website and not the `yarn` homepage.
This is better suited with the context with which we want the user to go to the `yarn` homepage.

chore: update readme to point to yarn installation page

---

src/DetailsView/Styles/detailsview.scss
src/popup/Styles/popup.scss

This was my process for finding dead css:
1) Search for the class name across our file base: if it only appears in the scss files, it's highly unlikely to be used.
2) Remove these styles.
3) Locally build the app and try to find these classes in html; if none were found, then we can be fairly certain this is dead css.
For certain scenarios, I did not do step 3 as components being referred to were quite clearly no longer being used (for example, lots of styles in popup refer to a getting started dialog which no longer exists).
I've added a gif for sanity-check reasons of me going through the popup and details view; feel free to check this out and check for yourself. 😄 
- [n/a] …

chore: clean up dead CSS in detailsview.scss and popup.scss

---

src/injected/styles/injected.scss

Same process as before:
Search for the class name across our file base: if it only appears in the scss files, it's highly unlikely to be used.
Remove these styles.
Locally build the app and try to find these classes in html; if none were found, then we can be fairly certain this is dead css.

chore: removed dead styles in injected.scss

---

src/injected/styles/injected.scss

In a previous PR I removed float:right from the shadow dom dialog per the suggestion of VSCode; it said it would not be applied. It was wrong! Instead, it was the display property that would not be applied! As such I removed display:inline and re-added float:right.

refactor: re-added float right style to the shadow dom dialog close button

---

package.json
src/common/components/theme.tsx
src/views/content/guidance-title.tsx
src/views/content/markup.tsx
yarn.lock

Dependabot suggested updating [@types/react-helmet](https://www.npmjs.com/package/@types/react-helmet) to 5.0.11, but their [PR 38557](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38557) to remove the default export broke our imports. ([We're not the only ones broken.](https://dependabot.com/compatibility-score/?dependency-name=@types/react-helmet&package-manager=npm_and_yarn&previous-version=5.0.10&new-version=5.0.11)). This change updates our imports to work with the change.

build(deps-dev): bump @types/react-helmet from 5.0.10 to 5.0.11 and fix imports

---

Gruntfile.js
package.json

We added a watch command for electron. We are going to move electron out of the watch command in a later PR. 
- [N/A] Added relevant unit test for your changes. (`yarn test`)
- [N/A] Ran precheckin (`yarn precheckin`)

Added electron to watch command

---

.dependabot/config.yml
.prettierignore
copyright-header.config.json

Adds a dependabot config file ([reference docs](https://dependabot.com/docs/config-file/)) to ignore office fabric major version bumps, per #1302.
I've verified that the config file passes [dependabot's config file validator](https://dependabot.com/docs/config-file/validator/)

add dependabot config that ignores OF >=7 updates

---

src/DetailsView/components/start-over-dropdown.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-dropdown.test.tsx.snap

For visual users, adds a standard ChevronDown menu icon to our "start over" dropdown menu button per @cheade's suggestion in #1316 
For SR users, updates the button's aria-label to make the button read as `start over menu button`, rather than the current `start over button`.
Office Fabric would normally add the chevron implicitly for `ActionButton`s with menus attached, but we're using some custom handling to attach the menu to the button rather than using `menuProps`, so we're instead setting the icon explicitly.
This is using Office Fabric's default styling and attributes for the chevron icon. I verified that:
* The chevron is not announced to screen readers (has `role=presentation` and `aria-hidden=true`)
* The chevron's contrast ratio is 3.69 (meets the 3.0 requirement for non-text …

fix: make it clear that the "start over" button will open a dropdown menu

---

src/DetailsView/Styles/detailsview.scss
src/common/styles/common.scss

Addresses #1118 and #1289.
Verified behavior in Chrome 77 (stable) and 79 (dev). Screenshots below are all on 77.
Verified that this doesn't re-introduce #1112 on Chrome 77 or 79.
**Before**
**After**
**Before**
**After**

fix: prevent double-scrollbars in various details view pages

---

src/DetailsView/Styles/detailsview.scss

Resolving @peterdur's post-merge comment in #1334
Removes a malformated/unnecessary width style (it has no effect because `$detailsViewLeftNavWidth` isn't propertly enclosed in a `#{}` block, but the style doesn't make any difference anyway)

chore: remove unnecessary/malformatted style from .left-nav

---

src/electron/device-connect-view/device-connect-view.scss
src/electron/device-disconnected-popup/device-disconnected-popup.scss
src/electron/device-disconnected-popup/device-disconnected-popup.tsx
src/electron/device-disconnected-popup/status-caution-icon.tsx
src/tests/unit/electron/device-disconnected-popup/__snapshots__/device-disconnected-popup.test.tsx.snap
src/tests/unit/electron/device-disconnected-popup/device-disconnected-popup.test.tsx

Add the new "Device disconnected" popup.
**Notes:**
- The "MY DEVICE" text is only for the screenshot purpose as that text is a prop that should come from the renderer and it should match the actual device name we get from the service.
**Out of scope:**
- actually render the dialog is not part of this PR as we still don't have the view that will use it.

feat: device disconnected popup

---

src/electron/platform/android/rule-information-provider.ts
src/electron/platform/android/rule-information.ts
src/electron/platform/android/scan-results-to-unified-results.ts
src/electron/platform/android/scan-results-to-unified-rules.ts
src/electron/platform/android/scan-results.ts
src/tests/unit/tests/electron/platform/android/__snapshots__/rule-information-provider.test.ts.snap
src/tests/unit/tests/electron/platform/android/__snapshots__/scan-results-to-unified-results.test.ts.snap
src/tests/unit/tests/electron/platform/android/__snapshots__/scan-results-to-unified-rules.test.ts.snap
src/tests/unit/tests/electron/platform/android/rule-information-provider.test.ts
src/tests/unit/tests/electron/platform/android/rule-information.test.ts
src/tests/unit/tests/electron/platform/android/scan-results-helpers.ts
src/tests/unit/tests/electron/platform/android/scan-results-to-unified-results.test.ts
src/tests/unit/tests/electron/platform/android/scan-results-to-unified-rules.test.ts
src/tests/unit/tests/electron/platform/android/scan-results.test.ts

Convert android results to unified rule format. Includes only the conversion code, with none of the plumbing of data in or data out.

Convert android results to unified rule format

---

src/injected/client-view-controller.ts
src/injected/main-window-initializer.ts
src/injected/selector-map-helper.ts
src/tests/unit/tests/injected/client-view-controller.test.ts
src/tests/unit/tests/injected/selector-map-helper.test.ts

I'm trying to limit the places where we directly depend on the stores; it seemed like a good idea to do so here as well since this is only used by the client view controller, which has access to state data that it can pass through.
I also re-factored some of the tests, removing duplicate code.

refactor: selector map helper to not directly depend on assessment/scan result store

---

src/electron/automated-checks/components/automated-checks-command-bar.scss
src/electron/automated-checks/components/automated-checks-command-bar.tsx
src/tests/unit/tests/electron/automated-checks/components/__snapshots__/automated-checks-command-bar.test.tsx.snap
src/tests/unit/tests/electron/automated-checks/components/automated-checks-command-bar.test.tsx

The ongoing automated checks results from Android feature calls for the addition of a command bar that will ultimately look like this:
For now, the only command with an actual purpose is the rescan button. We could add the rest now, but they will not do anything until future features are complete.
We don't yet have the UI to house this bar, so for now it is just waiting to be used.
- [-] Addresses an existing issue: Fixes #0000
- [-] (UI changes only) Added screenshots/GIFs to description above
- [-] (UI changes only) Verified usability with NVDA/JAWS

Add automated checks command bar

---

src/background/actions/action-payloads.ts
src/background/stores/unified-scan-result-store.ts
src/common/environment-info-provider.ts
src/common/types/store-data/unified-data-interface.ts
src/injected/analyzers/unified-result-sender.ts
src/injected/main-window-initializer.ts
src/tests/unit/common/environment-info-provider.test.ts
src/tests/unit/tests/background/actions/unified-scan-result-action-creator.test.ts
src/tests/unit/tests/background/stores/unified-scan-result-store.test.ts
src/tests/unit/tests/injected/analyzers/unified-result-sender.test.ts

- Added a `getToolData()` function to `EnvironmentDataProvider` because `EnvironmentDataProvider` already has all the environment data needed to populate and return a ToolData object.
- Added `toolInfo` property to `UnifiedScanCompletedPayload` to send tool data to the `UnifiedScanResultStore` as part of the payload in `UnifiedResultSender`
- Created `ApplicationProperties` interface in `unified-data-interface.ts` to be able to specify application data, which is different from scan engine data, as part of the ToolData
- Updated relevant tests

add tool info to unified scan result store

---

.vscode/settings.json

Using:
```json
"typescript.preferences.importModuleSpecifier": "non-relative",
```
on `.vscode/settings.json` file to make it easier to move to non-relative import paths

chore: using non-relative imports for typescript code

---

src/electron/platform/android/rule-information-provider.ts
src/tests/unit/tests/electron/platform/android/__snapshots__/rule-information-provider.test.ts.snap
src/tests/unit/tests/electron/platform/android/__snapshots__/scan-results-to-unified-results.test.ts.snap

The cards feature calls for certain portions of the text to be rendered in a style similar to markdown's backtick styling (example: "Set the `isImportantForAccessibility` attribute to false"), but we currently have no way to apply intra-string styling. We discussed various options, including what the web UI currently does for Axe-core results. This PR takes the approach of treating the styling as "hints" that are specified by the data provider (in this case, the converter), and those get applied (as appropriate) at the data consumer (in this case, the cards UI). In essence, the data provider is using the property bag to specify input parameters to the consumer, and the consumer owns the actual application of the parameters. This puts the authoring into one place, and the consuming into …

Add 'formatAsCode' property to HowToFix property bag, update tests

---

src/DetailsView/components/Issues-details-pane.tsx
src/DetailsView/details-view-initializer.ts
src/background/issue-details-text-generator.ts
src/common/components/copy-issue-details-button.tsx
src/common/types/create-issue-details-text-data.ts
src/injected/components/command-bar.tsx
src/injected/dialog-renderer.tsx
src/issue-filing/common/create-issue-details-builder.ts
src/issue-filing/common/issue-filing-url-string-utils.ts
src/issue-filing/rule-result-to-issue-filing-data.ts
src/issue-filing/services/azure-boards/create-azure-boards-issue-filing-url.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/issues-details-pane.test.tsx.snap
src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
src/tests/unit/tests/DetailsView/components/issues-details-pane.test.tsx
src/tests/unit/tests/background/issue-details-text-generator.test.ts
src/tests/unit/tests/common/components/copy-issue-details-button.test.tsx
src/tests/unit/tests/common/components/issue-filing-button.test.tsx
src/tests/unit/tests/common/message-creators/issue-filing-action-message-creator.test.ts
src/tests/unit/tests/injected/components/__snapshots__/command-bar.test.tsx.snap
src/tests/unit/tests/injected/components/command-bar.test.tsx
src/tests/unit/tests/issue-filing/common/__snapshots__/issue-details-builder.test.ts.snap
src/tests/unit/tests/issue-filing/common/create-file-issue-handler.test.ts
src/tests/unit/tests/issue-filing/common/issue-details-builder.test.ts
src/tests/unit/tests/issue-filing/common/issue-filing-controller-impl.test.ts
src/tests/unit/tests/issue-filing/common/issue-filing-url-string-utils.test.ts
src/tests/unit/tests/issue-filing/rule-result-to-issue-filing-data.test.ts
src/tests/unit/tests/issue-filing/services/azure-boards/create-azure-boards-issue-filing-url.test.ts

This PR follows up from #1351 . The current issue filing implementation assumes the issue-details type contains axe-core result data. This needs to change if we want to reuse the plumbing for the upcoming platform-agnostic data.
- `CreateIssueDetailsTextData` only holds the fields issue filing needs to create a bug, no more or less
- Each consumer of issue filing will convert their data-type (axe-core data or unified-data) to `CreateIssueDetailsTextData` (the cards UI will soon need to do this with unified-data)

Refactor issue filing to enable multiple result data types

---

src/injected/client-view-controller.ts
src/injected/is-visualization-enabled.ts
src/injected/target-page-visualization-updater.ts
src/injected/visualization-needs-update.ts
src/injected/visualization-state-change-handler.ts
src/tests/unit/tests/injected/is-visualization-enabled.test.ts
src/tests/unit/tests/injected/target-page-visualization-updater.test.ts
src/tests/unit/tests/injected/visualization-needs-update.test.ts
src/tests/unit/tests/injected/visualization-state-change-handler.test.ts

This PR breaks apart the client view controller into another 4 pieces and they are as such:
1. Function isVisualizationEnabled: determine's whether a visualization is enabled or disabled based on the data provided.
2. Function visualizationNeedsUpdate: determine whether a visualization needs to be updated based on data provided.
3. Object VisualizationUpdateChangeHandler: this is the callback that listens to the store hub changes and calls the update visualization callback on all visualization types provided.
4. Object TargetPageVisualizationUpdater: for a visualization, this will update the visualization's state in the target page.
After this PR is complete, I will make a change to start relying on these new classes and remove the client-view-controller.
- [n/a] Addresses an existing …

refactor: create new classes with smaller scope in responsibilities to eventually replace client-view-controller

---

src/background/stores/card-selection-store.ts
src/common/types/store-data/card-selection-store-data.ts
src/tests/unit/tests/background/stores/card-selection-store.test.ts

- Refactor the store to use a dictionary of rule ids and result instance ids as the keys, rather than using arrays with the ids as fields. This makes it more efficient in code to locate a given rule or card to be expanded or selected.
- Implement the scanCompleted, toggleExpandCollapseRule, and collapseAllRules functions
- create unit tests for the above three functions
The toggleCardSelection function remains undone only to make this PR slightly smaller.

Refactor CardSelectionStore interface and add unit tests

---

.vscode/settings.json

Updating imports (the ones that "make sense") to use non-relative paths on files under the electron folder.

refactor: using non-relative imports for typescript code

---

src/common/types/store-data/unified-data-interface.ts
src/injected/adapters/scan-results-to-unified-results.ts
src/issue-filing/unified-result-to-issue-filing-data.ts
src/tests/unit/tests/injected/adapters/__snapshots__/scan-results-to-unified-results.test.ts.snap
src/tests/unit/tests/injected/adapters/scan-results-to-unified-results.test.ts
src/tests/unit/tests/issue-filing/unified-result-to-issue-filing-data.test.ts

- Modified ``UnifiedResult`` data type to have strongly typed properties, currently they are optional since we need to change the data converter in Android as well. Eventually they will all be required properties.
- Add converter to convert unified data to issue filing text create data.
- Add unit tests.

Add strongly typed properties in Unified Result

---

.vscode/settings.json

Update typescript sdk path in vscode settings because the way its currently mentioned; it doesn't find that path on MacOS.

chore: update typescript sdk path in vscode settings

---

src/common/components/cards/instance-details.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap
src/tests/unit/tests/common/components/cards/instance-details.test.tsx

Bug fix: handle when property config for a prop does not exist

Bug fix: handle when property config for a prop does not exist

---

src/electron/views/device-connect-view/components/device-connect-view-container.tsx
src/electron/views/device-connect-view/device-connect-view-initializer.ts
src/electron/views/device-connect-view/device-connect-view-renderer.tsx
src/electron/views/root-container/components/root-container.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-view-container.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/device-connect-view-container.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/device-connect-view-renderer.test.tsx
src/tests/unit/tests/electron/views/root-container/components/__snapshots__/root-container.test.tsx.snap
src/tests/unit/tests/electron/views/root-container/components/root-container.test.tsx

Created root container, that will be used to render the proper view based on route id; connected it to the device connect view initializer

Root container renderer

---

src/common/types/store-data/unified-data-interface.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/cards-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/details-list-issues-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/failed-instances-section.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/instance-details-group.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/result-section-content.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/rules-with-instances.test.tsx.snap
src/tests/unit/tests/common/components/cards/instance-details.test.tsx
src/tests/unit/tests/common/components/cards/sample-view-model-data.ts
src/tests/unit/tests/reports/components/report-sections/__snapshots__/report-body.test.tsx.snap

Updated the strongly-typed properties in `identifiers` of UnifiedResult (added in #1377) from optional to required. 

Set strongly typed 'identifiers' properties in UnifiedResult as required

---

src/common/components/cards/card-kebab-menu-button.scss
src/common/components/cards/card-kebab-menu-button.tsx
src/common/components/cards/instance-details-footer.scss
src/common/components/cards/instance-details-footer.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/card-kebab-menu-button.test.tsx.snap

* Refactors `card-footer.scss` into separate `instance-details-footer.scss` and `card-kebab-menu-button.scss` to match the separation of the corresponding tsx files
* Adds a distinguishing className to the kebab menu
* Uses that to style the icons it contains as $primary-text per the feature mockup

feat(card-buttons): make color of menu item icons match text per mockups

---

src/electron/main/main.ts

Adding proper handling of DEV_MODE enviroment variable on the electron app

fix: Use DEV_MODE env variable to enable dev mode

---

src/common/components/cards/card-kebab-menu-button.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/card-kebab-menu-button.test.tsx.snap
src/tests/unit/tests/common/components/cards/card-kebab-menu-button.test.tsx

- When copy failed, show toast with text: Failed to copy Failure details. Please try again.
- Removed Contextual Menu and used menu props on action button component as a part of this PR, so that we do not have to handle the state of the contextual menu.
- Updated snapshots and unit tests.

Handle copy failure

---

src/electron/platform/android/rule-information-provider.ts
src/electron/platform/android/rule-information.ts
src/electron/platform/android/scan-results-to-unified-results.ts
src/tests/unit/tests/electron/platform/android/__snapshots__/rule-information-provider.test.ts.snap
src/tests/unit/tests/electron/platform/android/__snapshots__/scan-results-to-unified-results.test.ts.snap
src/tests/unit/tests/electron/platform/android/rule-information-provider.test.ts
src/tests/unit/tests/electron/platform/android/rule-information.test.ts

Updated the android results to unified results converter to populate UnifiedResolution with getUnifiedResolution, instead of saving two versions of the how to fix text (in 'how-to-fix' unformattedText and in howToFixSummary). 
Main changes are that the howToFixString function has been removed, as it is not needed, and unformattedText in the InstancePropertyBag is now called howToFixSummary to match the UnifiedResolution type.

remove redundant 'how to fix' from android converter

---

src/common/extension-telemetry-events.ts
src/common/stores/store-names.ts
src/electron/common/electron-telemetry-events.ts
src/electron/flux/action-creator/scan-action-creator.ts
src/electron/flux/action/device-action-payloads.ts
src/electron/flux/action/device-actions.ts
src/electron/flux/action/scan-actions.ts
src/electron/flux/store/device-store.ts
src/electron/flux/store/scan-store.ts
src/electron/flux/types/scan-status.ts
src/electron/flux/types/scan-store-data.ts
src/electron/platform/android/scan-controller.ts
src/tests/unit/tests/electron/flux/action-creator/device-connect-action-creator.test.ts
src/tests/unit/tests/electron/flux/action-creator/scan-action-creator.test.ts
src/tests/unit/tests/electron/flux/action-creator/scan-result-example.ts
src/tests/unit/tests/electron/flux/store/__snapshots__/scan-store.test.ts.snap
src/tests/unit/tests/electron/flux/store/device-store.test.ts
src/tests/unit/tests/electron/flux/store/scan-store.test.ts
src/tests/unit/tests/electron/platform/android/scan-controller.test.ts

We need a way to start/re-start a scan. In  this PR:
- add scan actions
- add scan store
- add scan action creator
How of scope for this PR:
- convert and send the results to `UnifiedScanResultStore`
- hook up the new classes.

feat: add scan action creator

---

src/common/components/cards/instance-details-footer.scss
src/common/components/cards/instance-details.tsx
src/reports/components/instance-details.scss
src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap

Fixes the border/shadow between the new card footer and the rest of the card to make the whole card have one cohesive border/shadow, per UI mockups.
Did this by adding a wrapping div to contain the card+footer together, moving the border/shadow styling from the table to there, removing the redundant styling in the table+footer, and setting the table+footer to inherit the appropriate border-radius parts from the container.
Verified that the card's shadow looks valid in both report and fastpass.
Before:
After:

fix(card-buttons): clean up border/shadow behavior of cards around new footer

---

src/content/strings/application.ts
src/electron/common/application-properties-provider.ts
src/electron/platform/android/scan-controller.ts
src/electron/platform/android/scan-results.ts
src/electron/platform/android/unified-result-builder.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/common/application-properties-provider.test.ts
src/tests/unit/tests/electron/flux/action-creator/scan-result-example.ts
src/tests/unit/tests/electron/platform/android/__snapshots__/unified-result-builder.test.ts.snap
src/tests/unit/tests/electron/platform/android/scan-controller.test.ts
src/tests/unit/tests/electron/platform/android/scan-results-helpers.ts
src/tests/unit/tests/electron/platform/android/scan-results.test.ts
src/tests/unit/tests/electron/platform/android/unified-result-builder.test.ts

- expose `axeVersion` from `ScanResults` class to be used on the unified scan completed payload
- introduce UnifiedScanCompletedPayloadBuilder to convert scan results to proper payload
- introduce application properties getter
- on `ScanController`, when the scan succeed, converting the scan results and invoking the unified scan completed action
- not affected
- not affected

feat(android-cards-view): convert scan results and invoke unified scan complete action

---

src/common/components/cards/card-kebab-menu-button.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/card-kebab-menu-button.test.tsx.snap
src/tests/unit/tests/common/components/cards/card-kebab-menu-button.test.tsx

Updates the `card-kebab-menu-button` to respect the same `cardInteractionSupport` dep the card itself is using, in preparation for the android selection feature's requirement to only show the user-config-agnostic menu items for the time being.
Here's what it looks like (with a temporary change to cause details-view-initializer to pass `cardInteractionSupport: onlyUserConfigAgnosticCardInteractionsSupported`, to emulate what electron will be doing):

feat(card-buttons): set up card action menu to only show the supported items

---

src/DetailsView/details-view-container.tsx
src/DetailsView/details-view-main-content.tsx
src/tests/unit/tests/DetailsView/details-view-container.test.tsx

This PR removes an unused `unifiedResults` prop. The prop being used instead is `ruleResultsByStatus`.

chore: remove unused prop in details-view

---

src/electron/views/automated-checks/components/title-bar.scss
src/electron/views/automated-checks/components/title-bar.tsx
src/electron/views/device-connect-view/components/window-title.scss
src/electron/views/device-connect-view/components/window-title.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/title-bar.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/title-bar.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/window-title.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/window-title.test.tsx

This PR refactors WindowTitle to support adding actionable icons.
Also, adds title to automated check view title bar.
Using flex to simplify styling
moved padding inside rather than on container. This way, the icons will have more hover space
Moving Window-title outside device-connect-view will be in a later pr

refactored to create a common window title & added title for electron

---

src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/renderer-initializer.ts
src/electron/views/root-container/components/root-container.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
src/tests/unit/tests/electron/views/root-container/components/__snapshots__/root-container.test.tsx.snap
src/tests/unit/tests/electron/views/root-container/components/root-container.test.tsx

This PR hooks up the use of the `ScanActionCreator` to start scanning when we render `AutomatedChecksView`
- not affected
- not affected

feat(android-cards-view): starting scan on automated checks first render

---

src/DetailsView/components/issue-filing-dialog.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap

The dev console in the details view currently spews a few warning about use of the deprecated className prop of the Dialog component (it's been replaced with `modalProps.className`). This fixes the warnings.
Verified that this has no impact on the final rendered dialog.
- [no] Addresses an existing issue:

fix: avoid console.warning about deprecated use of Dialog className prop

---

src/common/components/cards/card-kebab-menu-button.scss
src/common/components/cards/card-kebab-menu-button.tsx
src/common/fabric-icons.ts
src/common/icons/more-actions-menu-icon.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/card-kebab-menu-button.test.tsx.snap

Updates the more actions card menu to use the icon from the mocks, rather than office fabric's close-ish one.
Left is as-implemented, right is expectation from the mock

feat(card-buttons): add real "more actions" icon from mocks

---

src/DetailsView/components/cards-view.tsx
src/DetailsView/components/details-list-issues-view.tsx
src/DetailsView/components/issues-table.tsx
src/DetailsView/components/test-view-container.tsx
src/DetailsView/details-view-main-content.tsx
src/common/components/cards/failed-instances-section.tsx
src/common/components/cards/instance-details-group.tsx
src/common/components/cards/result-section-content.tsx
src/common/components/cards/rule-content.tsx
src/common/components/cards/rules-with-instances.tsx
src/common/rule-based-view-model-provider.ts
src/common/types/store-data/unified-data-interface.ts
src/reports/components/report-sections/report-section-factory.tsx
src/reports/report-generator.ts
src/reports/report-html-generator.tsx
src/tests/unit/common/rule-based-view-model-provider.test.ts
src/tests/unit/tests/DetailsView/details-view-container.test.tsx
src/tests/unit/tests/common/components/cards/instance-details-group.test.tsx
src/tests/unit/tests/common/components/cards/result-section-content.test.tsx
src/tests/unit/tests/common/components/cards/sample-view-model-data.ts

As discussed today offline with Wahaj, `UnifiedStatusResults` and `UnifiedRuleResult` interfaces were placed in `failed-instances-section.tsx`. Moving them over to `unified-data-interface.ts`.

refactor: move UnifiedStatusResults and UnifiedRuleResult interfaces to another file

---

src/DetailsView/components/cards-view.tsx
src/DetailsView/components/details-list-issues-view.tsx
src/DetailsView/components/issues-table.tsx
src/DetailsView/components/test-view-container.tsx
src/DetailsView/details-view-main-content.tsx
src/common/components/cards/failed-instances-section.tsx
src/common/components/cards/instance-details-group.tsx
src/common/components/cards/result-section-content.tsx
src/common/components/cards/rule-content.tsx
src/common/components/cards/rules-with-instances.tsx
src/common/rule-based-view-model-provider.ts
src/common/types/store-data/card-view-model.ts
src/common/types/store-data/unified-data-interface.ts
src/reports/components/report-sections/report-section-factory.tsx
src/reports/report-generator.ts
src/reports/report-html-generator.tsx
src/tests/unit/common/rule-based-view-model-provider.test.ts
src/tests/unit/tests/DetailsView/details-view-container.test.tsx
src/tests/unit/tests/common/components/cards/instance-details-group.test.tsx
src/tests/unit/tests/common/components/cards/result-section-content.test.tsx
src/tests/unit/tests/common/components/cards/sample-view-model-data.ts

This moves interfaces/types that are really only for the cards view to a separate place for them specifically.

refactor: renamed and moved view model to separate files for cards

---

src/common/components/cards/card-kebab-menu-button.scss
src/common/components/cards/card-kebab-menu-button.tsx
src/common/styles/colors.scss
src/tests/unit/tests/common/components/cards/__snapshots__/card-kebab-menu-button.test.tsx.snap

- Update the background color of the contextual menu to match the mock.
- Update the background color of the menu button on hover to match the mock.
- Update the background color of the menu button on pressed to match the mock.
- Give the contextual menu a 4px border radius.
- Update the box shadow of the menu to match the mock.
Figma - hovered and pressed:
Screenshot of the change:
hover:
pressed:

Contextual menu fit and finish

---

src/electron/views/device-connect-view/components/device-connect-connected-device.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-connected-device.test.tsx.snap

By using `role` and `aria-live` we can make the screen reader announce the device connection status.
- [] (UI changes only) Added screenshots/GIFs to description above

fix: announcing device connection status

---

src/common/components/cards/card-kebab-menu-button.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/card-kebab-menu-button.test.tsx.snap

Fixes an issue where the file issue dialog opening would cause the action menu button to shift to the middle of the card.

fix(card-buttons): prevent "more actions" button shifting left when file issue dialog is open

---

src/common/components/toast.tsx
src/tests/unit/tests/common/components/__snapshots__/copy-issue-details-button.test.tsx.snap
src/tests/unit/tests/common/components/__snapshots__/toast.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/card-kebab-menu-button.test.tsx.snap

This PR ensures that the toast notification our copy failure details button/menu item uses is announced as a live region and stays on the screen for a reasonably readable amount of time (6s instead of 1s).
We're still discussing whether this is actually enough of a change (in particular, if/how [WCAG SC 2.2.1: Timing Adjustable](https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable.html) applies), but this is a pretty clear improvement over the old behavior so putting it in while we discuss further.
- [n/a (no visible change)] (UI changes only) Added screenshots/GIFs to description above

fix(card-buttons): improve accessibility of toast notifications (greater timeout, live region)

---

src/electron/platform/android/rule-information-provider.ts
src/electron/platform/android/rule-information.ts
src/electron/platform/android/scan-results-to-unified-results.ts
src/electron/platform/android/scan-results-to-unified-rules.ts
src/tests/unit/tests/electron/platform/android/__snapshots__/rule-information-provider.test.ts.snap
src/tests/unit/tests/electron/platform/android/__snapshots__/scan-results-to-unified-rules.test.ts.snap
src/tests/unit/tests/electron/platform/android/rule-information-provider.test.ts
src/tests/unit/tests/electron/platform/android/rule-information.test.ts
src/tests/unit/tests/electron/platform/android/scan-results-helpers.ts
src/tests/unit/tests/electron/platform/android/scan-results-to-unified-results.test.ts
src/tests/unit/tests/electron/platform/android/scan-results-to-unified-rules.test.ts

We want to exclude ColorContrast results where the confidence is anything but **High**. To enable this, we're adding a filter method on the RuleInformation class, then calling it on each result to determine if that result should be filtered out. Adding filters to other rules will only require changing the RuleInformationProvider.

feat(android-cards-view): Add per-result filtering for ColorContrast rule

---

src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/device-disconnected-popup/device-disconnected-popup.tsx
src/electron/views/root-container/components/root-container.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
src/tests/unit/tests/electron/views/device-disconnected-popup/__snapshots__/device-disconnected-popup.test.tsx.snap
src/tests/unit/tests/electron/views/root-container/components/__snapshots__/root-container.test.tsx.snap

Wiring up the "Device disconnected" popup. When the user reaches the "Automated checks" view, we should the "scanning" spinner, if the scan failes, we'll be showing this popup that let's the user rescan the same device or navigate back to input a different port number.
**Notes for the reviews**
- This is only a wiring up PR, the dialog was already there
- The only exception to the previous point is: I made the device name a bold text to make it easier to catch
- There is a flickering on the window when navigating back to the port entry view. I had left that out of the scope of this PR as it touches a different piece of code and technically speaking, that bug was already there.
- [] (UI changes only) Added screenshots/GIFs to description above
- [] (UI changes only) Verified usability with …

feat(android-cards-view): wire up device disconnected popup

---

src/DetailsView/components/issue-filing-dialog.tsx
src/common/message-creators/user-config-message-creator.ts
src/issue-filing/components/issue-filing-choice-group.tsx
src/issue-filing/components/issue-filing-settings-container.tsx
src/issue-filing/services/azure-boards/azure-boards-settings-form.tsx
src/issue-filing/services/github/github-issue-filing-service.tsx
src/issue-filing/types/settings-form-props.ts
src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
src/tests/unit/tests/common/message-creators/user-config-message-creator.test.ts
src/tests/unit/tests/issue-filing/components/issue-filing-option-choice-group.test.tsx
src/tests/unit/tests/issue-filing/services/azure-boards/azure-boards-settings-form.test.tsx
src/tests/unit/tests/issue-filing/services/github/github-issue-filing-service.test.tsx

We'll be using `CardsView` component on AI-Android. Deed down the `CardsViewDeps`, we're going to use the `UserConfigMessageCreator` issue filining-related functions so we need the **Message Creator** API to match that of the **Action Creator** so we can use them indistinctly on the UI.
**NOTES**
This are the componets use (directly) by `CardsView` that have the `UserCOnfigMessageCreator` as a dep:
- `IssueFilingDialog` uses `saveIssueFilingSettings`
- `IssueFilingSettingsContainer` uses `setIssueFilingService` and `setIssueFilingServiceProperty`
- not affected
- not affected

refactor: user config message creator refactor signatures

---

src/electron/flux/action-creator/window-frame-action-creator.ts
src/electron/flux/action-creator/window-state-action-creator.ts
src/electron/flux/action/window-frame-actions-payloads.ts
src/electron/flux/action/window-frame-actions.ts
src/electron/flux/store/window-state-store.ts
src/electron/flux/types/window-state-store-data.ts
src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/automated-checks/components/title-bar.tsx
src/electron/views/device-connect-view/components/device-connect-footer.tsx
src/electron/views/renderer-initializer.ts
src/electron/views/root-container/components/root-container.tsx
src/electron/views/root-container/root-container-renderer.tsx
src/electron/window-frame-listener.ts
src/electron/window-frame-updater.ts
src/tests/electron/window-frame-listener.test.ts
src/tests/electron/window-frame-updater.test.ts
src/tests/unit/tests/electron/flux/action-creator/window-frame-action-creator.test.ts
src/tests/unit/tests/electron/flux/action-creator/window-state-action-creator.test.ts
src/tests/unit/tests/electron/flux/store/__snapshots__/window-state-store.test.ts.snap
src/tests/unit/tests/electron/flux/store/window-state-store.test.ts
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
src/tests/unit/tests/electron/views/automated-checks/components/title-bar.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/device-connect-footer.test.tsx
src/tests/unit/tests/electron/views/root-container/components/__snapshots__/root-container.test.tsx.snap
src/tests/unit/tests/electron/views/root-container/components/root-container.test.tsx
src/tests/unit/tests/electron/views/root-container/root-container-renderer.test.tsx

WindowFrameUpdater => responsible for performing window operations via actions.
WindowFrameListener => listens to window state & updates store via action
Main changes are in WindowFrameUpdater, WindowFrameListener, TitleBar & RootContainerRenderer, WindowStateStore
(Other files were modified due to this refactoring + delegating action creators)

Manage Window State changes

---

src/reports/components/report-sections/collapsible-script-provider.tsx
src/tests/unit/tests/reports/components/report-sections/collapsible-script-provider.test.ts

Previously, in the generated reports using the new cards UI, the rule groups were incorrectly collapsing if any content underneath them was clicked, rather than only collapsing when the headers were clicked. This fixes the location of the onClick handler to prevent this behavior.

fix(report-cards): prevent clicks on card content from collapsing rule groups

---

src/reports/assessment-report-html-generator.tsx
src/reports/components/report-head.tsx
src/tests/unit/tests/reports/assessment-report-html-generator.test.tsx
src/tests/unit/tests/reports/components/__snapshots__/report-head.test.tsx.snap

2-byte characters are garbled on the Assessment Report.
This PR adds encoding settings and set a DOCTYPE to the report.

Add encoding setting on the Assessment Report and set DOCTYPE

---

src/electron/views/device-connect-view/components/device-connect-port-entry.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-port-entry.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/device-connect-port-entry.test.tsx

users can now hit the "Enter" key and validate the port number. This PR also updated device connect port entry test and snapshots

added text field validation via Enter key

---

build.yaml

The linux electron-distributable step in CI is failing because of https://github.com/electron-userland/electron-builder/issues/4318. This PR temporarily disables the Linux build.

Disable linux electron build

---

src/common/components/cards/card-kebab-menu-button.scss
src/common/styles/colors.scss

Have run the UX flow with Fer and confirmed this is what we want. 
This PR only includes the contextual menu control.
normal:
hover:
expand:
select a menu item:
When color contrast is off, nothing changes:

contextual menu - high contrast mode

---

src/electron/flux/types/window-state-store-data.ts
src/electron/main/main.ts
src/electron/platform-info.ts
src/electron/views/automated-checks/components/title-bar.tsx
src/electron/views/device-connect-view/components/device-connect-view-container.tsx
src/electron/views/device-connect-view/components/window-title.scss
src/electron/views/device-connect-view/components/window-title.tsx
src/electron/views/renderer-initializer.ts
src/electron/views/root-container/components/root-container.tsx
src/electron/window-frame-listener.ts
src/electron/window-frame-updater.ts
src/tests/electron/window-frame-listener.test.ts
src/tests/electron/window-frame-updater.test.ts
src/tests/unit/tests/electron/flux/store/window-state-store.test.ts
src/tests/unit/tests/electron/platform-info.test.ts
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/title-bar.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/title-bar.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-view-container.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/window-title.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/device-connect-view-container.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/window-title.test.tsx

- As part of this PR, we handle mac os separately. If mac, we use window frame with titlebar style set to hidden. This adds 3 icons to top left corner of window. So, we need to add some padding to the title bar to cover this icons. Also, we remove the title bar if the window is in full screen mode.
- For windows & mac, we show the minimize, close & maximize icons on the right side.
- As part of this change, we have also made changes to only listen to maximize, unmaximize, enter-full-screen & leave-full-screen. We don't have to listen to minimize action, since we don't change state based on whether the window is minimized or not.
**Device connect view:**
**Results view in maximized mode:**
**Results view in full screen view**

adding title bar support for mac

---

src/DetailsView/details-view-container.tsx
src/DetailsView/details-view-initializer.ts
src/background/actions/card-selection-action-creator.ts
src/background/actions/card-selection-actions.ts
src/background/stores/card-selection-store.ts
src/common/rule-based-view-model-provider.ts
src/tests/unit/tests/DetailsView/details-view-container.test.tsx
src/tests/unit/tests/DetailsView/store-mocks.ts

Link details-view-initializer with card selection store.

feat(card-selection): pass card selection store to details view initializer

---

src/DetailsView/components/target-page-closed-view.scss
src/DetailsView/components/target-page-closed-view.tsx
src/DetailsView/details-view-container.tsx
src/tests/unit/tests/DetailsView/__snapshots__/details-view-container.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-closed-view.test.tsx.snap

Fixes weird scrollbar behavior in "No content available" screen by removing a bunch of unnecessary code in that path.
Verified how the whole page reads in JAWS

fix: prevent weird scrollbars in "No content available" page

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/details-view-body.tsx
src/DetailsView/details-view-container.tsx
src/tests/unit/tests/DetailsView/details-view-body.test.tsx
src/tests/unit/tests/DetailsView/details-view-container.test.tsx

`DetailsViewMainContent` was named misleadingly; it actually contained several elements besides the main landmark. This PR renames it and its surrounding styles/etc to `DetailsViewBody`, gives it responsibility for its own wrapper div (moved from the parent `DetailsViewContainer`), and moves its layout styles to be controlled by CSS rather than essentially being inlined (via `.table` and similar).
There are no visual changes as part of this PR.
- [n/a, no visual change] (UI changes only) Added screenshots/GIFs to description above

refactor: simplify and improve names around `DetailsViewMainContent`

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/details-view-container.tsx
src/tests/unit/tests/DetailsView/__snapshots__/details-view-container.test.tsx.snap
src/tests/unit/tests/DetailsView/details-view-container.test.tsx

The details view container currently adds a `<div className="table column-layout main-wrapper">` div near the root level. `main-wrapper` is never used in our css, and `table column-layout` is better represented as applying styles to a more logically-named class (so the CSS can have layout responsibility, rather than essentially using inline styles here).
This removes the unnecessary layer of div as well as the `.table` classes from `detailsview.scss` (this was the last spot they were used - there is a separate `.table` style in `content.scss` that is a little more reasonble, which I haven't modified in this PR.
Verified that there are no visual changes as a result of this change. In particular, verified the following details view scenarios:
* FastPass (both left nav tabs)
* Assessement …

refactor: remove unnecessary details view div/styles

---

src/DetailsView/Styles/detailsview.scss

I looked through `popup.scss`, `injected.scss`, `detailsview.scss`, and `content.scss` for class names that had styles but were never used in the application. I did this by starting from the results of the following powershell function (uses [ripgrep](https://github.com/BurntSushi/ripgrep)):
```powershell
function findUnusedStyles($file) {
$styleNames = type $file | `
sls '\.([a-zA-Z\-_][\w\d\-_]*)[ {]' | `
% { $_.Matches[0].Groups[1].Value } | `
select -unique | `
sort;
$unusedStyles = $styleNames | `
where { $_ -notmatch 'ms-' } | `
where { 0 -eq @(rg -g '!$file' $_).Count };
return $unusedStyles;
}
```
...and then additionally double checking with vs code's find-all for every class I removed.
There weren't any results except for in `detailsview.scss`.
Did a sanity check over the app …

refactor: remove unused detailsview.scss classes

---

src/reports/assessment-report-html-generator.tsx
src/tests/unit/tests/reports/assessment-report-html-generator.test.tsx

The change #1450 introduced DOCTYPE in the assessment HTML report. We should have it, but it leads to icon mangling as described in #1470 - this PR reverts the DOCTYPE changes for now so master is unblocked.

fix: remove doctype from assessment report to fix icon regression

---

src/electron/views/automated-checks/automated-checks-view.scss
src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/automated-checks/components/command-bar.scss
src/electron/views/automated-checks/components/command-bar.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/command-bar.test.tsx.snap

Mostly, add margins/paddings values on the automated checks view main content and the command bar.
- not affected

feat(android-cards-view): update styles for automated checks view

---

src/common/components/toast.tsx
src/tests/unit/tests/common/components/__snapshots__/toast.test.tsx.snap
src/tests/unit/tests/common/components/toast.test.tsx

- Fix a11y issue on toast by adding ``https://github.com/microsoft/accessibility-insights-web/pull/1479`` back.
- add proper snapshot testing.
- verified that the toast message is read out by AT.

Fix a11y issue on toast and add proper test

---

src/electron/views/automated-checks/automated-checks-view.scss
src/electron/views/device-connect-view/components/device-connect-view-container.tsx
src/electron/views/device-connect-view/device-connect-view.scss
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-view-container.test.tsx.snap

- Maintained the drag functionality of device-connect-view (e.g. user cannot select the text but can drag the window around the screen)
- Added "-webkit-app-region: no-drag" to the automatedChecks view so that users can select text and items within the container
- [N/A] Added relevant unit test for your changes. (`yarn test`)

Root Container views drag and no-drag implementation

---

src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/automated-checks/components/command-bar.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
src/tests/unit/tests/electron/views/automated-checks/components/command-bar.test.tsx

Currently, the rescan button (on the automated checks view) just "reset the connection". This PR fixes the button on click function so the proper action creator's scan function is called. Additionally, there are some improvements on automated checks view tests.

feat(android-cards-view): fix rescan button

---

src/common/components/cards/get-labelled-string-property-card-row.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/get-labelled-string-property-card-row.test.tsx.snap
src/tests/unit/tests/common/components/cards/get-labelled-string-property-card-row.test.tsx

For AI-Android, if a result instance have empty `text` or empty `contentDescription` we need to not render that card row on the UI.
In order to do so, I'm updating `GetLabelledStringPropertyCardRow` to handle this case.

feat(android-cards-view): LabelledStringPropertyCardRow null handling

---

src/common/components/cards/class-name-card-row.ts
src/common/components/cards/content-description-card-row.ts
src/common/components/cards/text-card-row.ts
src/common/configs/unified-result-property-configurations.tsx
src/electron/views/device-connect-view/device-connect-view.scss
src/tests/unit/tests/common/components/cards/__snapshots__/class-name-card-row.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/content-description-card-row.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/text-card-row.test.tsx.snap
src/tests/unit/tests/common/components/cards/class-name-card-row.test.tsx
src/tests/unit/tests/common/components/cards/content-description-card-row.test.tsx
src/tests/unit/tests/common/components/cards/text-card-row.test.tsx

Add card row components for:
- className
- contentDescription
- text
This are all axe-android specific and text only properties we need to render on the `CardView`.
Update the card row configuration file to include this new card row componets too.
**Out of scope for this PR**
- We need to handle `contentDescription` and `text` being null by not rendering that row on the `CardView`. I'll work on that on a different PR.
- I think we should refactor this to separate browser extension specific from android specific card rows configuration but I'll left that to be done after a proper discussion with the team
**"normal" size screen**
**small screens**

feat(android-cards-view): className, contentDescription, text card row components

---

src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/device-connect-view/device-connect-view.scss
src/electron/views/renderer-initializer.ts
src/electron/views/root-container/components/root-container.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
src/tests/unit/tests/electron/views/root-container/components/__snapshots__/root-container.test.tsx.snap
src/tests/unit/tests/electron/views/root-container/components/root-container.test.tsx

Wiring up `CardsView` on ai-android.
**Notes**
I'm purposfully creating the `CardsViewDeps` as a separated object so we know which dependencies are needed from `CardsView` (or child components). I left some comments, on some properties, specially on issue filing related deps. I want the clean up part of the deps to be on a separated PR so we can more thoroughly check what we actually need and what we don't
**Out of Scope**
I only added `CardRow` components for the most simple values, basically of type string. That is: `text`, `className` and `componentDescription`. There is another PR to take care of `howToFix` (#1489)

feat(android-cards-view): wire up CardsView

---

src/common/components/toast.scss
src/common/components/toast.tsx
src/tests/unit/tests/common/components/__snapshots__/toast.test.tsx.snap

Fixes a regression introduced by our recent toast aria-live changes where its container div causes an undesired layout change in the injected target page dialog.
Before:
After:

fix: prevent injected dialog buttons wrapping from new Toast layout

---

src/electron/views/automated-checks/components/command-bar.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
src/tests/unit/tests/electron/views/automated-checks/components/command-bar.test.tsx

Fixing the `onClick` for the "Rescan" button on the automated checks view's command bar.
- [] (UI changes only) Verified usability with NVDA/JAWS

feat(android-cards-view): fix rescan button onClick

---

src/common/components/cards/card-kebab-menu-button.tsx
src/common/components/copy-issue-details-button.tsx
src/common/navigator-utils.ts
src/injected/dialog-renderer.tsx
src/injected/visualization/drawer-provider.ts
src/injected/visualization/issues-formatter.ts
src/injected/window-initializer.ts
src/tests/unit/tests/common/navigator-utils.test.ts
src/tests/unit/tests/injected/dialog-renderer.test.tsx
src/tests/unit/tests/injected/visualization/drawer-provider.test.ts
src/tests/unit/tests/injected/visualization/issues-formatter.test.ts

* Adds `console.error` logging with the full error message on copy failure, for diagnosability
* Wires up `NavigatorUtils` in the target page to the dialog renderer (it was missing before)

fix: make "copy failure details" button in target page dialog work again

---

src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/automated-checks/components/command-bar.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/command-bar.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/command-bar.test.tsx

We don't want to send scan http request to the axe-android service, nor we have an explicit queue for handling this scenario. So, the desired behavior is to disable the "Rescan" button while we're scanning. 
This PR adds such behavior.

feat(android-cards-view): disable rescan button while scanning

---

src/tests/unit/tests/DetailsView/details-view-container.test.tsx

An earlier refactor PR renamed `DetailsViewMainContent` to `DetailsViewBody`, but missed updating this associated test helper method.

refactor: rename buildDetailsViewMainContent -> ...Body

---

src/DetailsView/details-view-container.tsx
src/DetailsView/details-view-initializer.ts
src/common/get-card-selection-view-data.ts
src/common/rule-based-view-model-provider.ts
src/common/types/store-data/card-view-model.ts
src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/renderer-initializer.ts
src/electron/views/root-container/components/root-container.tsx
src/tests/unit/common/__snapshots__/rule-based-view-model-provider.test.ts.snap
src/tests/unit/common/rule-based-view-model-provider.test.ts
src/tests/unit/tests/DetailsView/details-view-container.test.tsx
src/tests/unit/tests/common/components/cards/sample-view-model-data.ts
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx

This change adds the data from the CardSelectionStore into the cards view model. The store data is first transformed into data relevant to the view model by a call to getCardSelectionViewData. The CardSelectionViewData is then passed to getUnifiedRuleResults where it is assigned to newly added fields in the view model data. The data can now be consumed by the details view.

feat(card-selection): add code to propogate the CardSelectionStoreData to the card view model

---

src/electron/platform/android/rule-information-provider.ts
src/tests/unit/tests/electron/platform/android/rule-information-provider.test.ts

We discovered that the Axe service has changed the format of the data in the TouchSizeWcag rule result. The new format looks wrong, so we're extracting the dimensions directly from the bounding rectangle. This should work in both old and new versions of the service.

Extract dimensions from bounding rectangle

---

src/common/components/cards/card-kebab-menu-button.scss

This fixes a release-build-specific css issue (#1509) caused by the use of an office fabric style selector which was not qualified with `:global()`. This PR fixes the issue by avoiding the use of the fabric classname entirely.

fix(card-buttons): avoid misalignment of more actions button in release builds

---

src/electron/views/automated-checks/components/command-bar.scss
src/electron/views/automated-checks/components/command-bar.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/command-bar.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/command-bar.test.tsx

We need to have the rescan button push to the right side of the "command bar" (on LTR mode).
In the near future, we'll have buttons close to the left and others close to the right (when we add "undock screenshot" button).
Additionally, our current command bar is a custom component which doesn't handle this behavior.
In this PR:
- Using office ui fabric's CommandBar to implement our custom command bar
- Put the Rescan button on the "farItems" prop so it shows up on the right side of the command bar (on LTR mode)
- Update styles of the command bar so it matches our figma mocks
**default state**
**hover over state**
**mouse down state**
**focused state**
**disabled state**
**NOTES**
- I check the command bar accessibility with both JAWS and NVDA, it works properly altough the are differences …

feat(android-cards-view): update command bar

---

src/injected/components/issue-details-navigation-controls.tsx
src/injected/styles/injected.scss
src/tests/unit/tests/injected/components/__snapshots__/issue-details-navigation-controls.test.tsx.snap

Fixes the misalignment issues in the target dialog nav footer by simplifying the footer layout and avoiding the use of fabric implementation details (which happened to change from under us unnoticed in a past fabric update).
Before:
After:
(Note: ignore the appearance of the button backgrounds before hover being white; this is a licecap issue, they show as the expected gray in that state in reality...)

fix(target-dialog): fix misalignments in dialog nav footer (and simplify footer layout/css)

---

src/tests/end-to-end/common/test-resources.ts
src/tests/end-to-end/setup/global-setup.ts
src/tests/end-to-end/setup/global-teardown.ts
src/tests/end-to-end/setup/test-resource-server-config.ts
src/tests/miscellaneous/test-resource-server/resource-server-config.ts
src/tests/miscellaneous/test-resource-server/resource-server.ts

In order to write new e2e test for the electron app, specifically, for the automated checks view, we need a way to "mock" axe-android calls and results. We are going to use a similar approach as `yarn with:mock-axe-andoid`, whichs spins up a local static file server to respond with a result file (in the future, we may need to get more sofisticated and have different results file for different scenarios but for now, one file should do).
For this to work properly, we need to generalize how we are spinning that resouces server. Adding a config type seems to fit this nicely as it allows to pack the port and the path we're currently passing ti the resource server under browser extension e2e scenario.

refactor: move resource server code

---

src/DetailsView/components/cards-view.tsx
src/common/components/cards/failed-instances-section.tsx
src/common/components/cards/result-section-title.tsx
src/common/components/cards/result-section.tsx
src/reports/components/report-sections/automated-checks-report-section-factory.tsx
src/reports/components/report-sections/report-section-factory.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/cards-view.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/failed-instances-section.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/result-section-title.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/result-section.test.tsx.snap
src/tests/unit/tests/common/components/cards/failed-instances-section.test.tsx
src/tests/unit/tests/common/components/cards/result-section-title.test.tsx
src/tests/unit/tests/common/components/cards/result-section.test.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/report-body.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/report-body.test.tsx

Our current failure details list (using Office UI Fabric' DetailsList) includes an AT alert. When the scan is finished and there are failures, AT announce: "X failures detected". Our current `CardsView` does not have this alert.
In this PR:
- Add the alert on the `CardsView`, i.e. on the details view.
- Make sure the automated checks report does not have the alert (as the report is an static document)
- there is no issue filed against GitHub
- not affected
- NVDA/JAWS under Windows 10, no VoiceOver

fix: add failures detected AT announcement on CardsView

---

src/common/components/cards/card-kebab-menu-button.tsx
src/common/components/cards/instance-details-footer.tsx
src/common/components/cards/instance-details.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/card-kebab-menu-button.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap
src/tests/unit/tests/common/components/cards/card-kebab-menu-button.test.tsx

After discussion with Rob, Fer & Wahaj, we decided to add some explicit text to be announced on card focus and kebab menu focus.
For card:
`html card  row  not selected` 
For Kebab Menu:
`More Actions html html-has-lang
menu button  collapsed  subMenu`

feat(card-selection): add accessibility announcements for cards selection 

---

src/tests/electron/common/create-application.ts
src/tests/electron/common/dismiss-telemetry-opt-in-dialog.ts
src/tests/electron/tests/main.test.ts

In order to reuse some of the current helper code for our AI-Android e2e test, I'm moving this function to their own files.

refactor: move/extract android e2e test resusable helpers

---

src/common/components/cards/instance-details.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap

After offline discussion with @RobGallo . Fixed the menu action button aria label to be something like 
`More Actions for card .bnp_hfly_collapse_close in rule image-alt button menu`.

fix: update aria label for kebab menu action button

---

src/common/components/cards/collapsible-component-cards.scss
src/common/components/cards/instance-details.tsx
src/common/components/cards/rule-resources.scss
src/reports/components/instance-details.scss
src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap
src/tests/unit/tests/common/components/cards/instance-details.test.tsx

Adds a class for the table container for instance details card and uses outline instead of border.

feat: use outline instead of border for showing selection state in UI

---

src/tests/electron/common/element-identifiers/automated-checks-view-selectors.ts
src/tests/electron/jest.config.js
src/tests/electron/setup/global-setup.ts
src/tests/electron/setup/global-teardown.ts
src/tests/electron/setup/test-resource-server-config.ts
src/tests/electron/setup/timeouts.ts
src/tests/electron/tests/automated-checks.view.test.ts
src/tests/miscellaneous/test-resource-server/resource-server-config.ts
src/tests/miscellaneous/test-resource-server/resource-server.ts

Adding e2e test for electron app, automated checks view. Since the `CardsView` component is shared between browser extension and the electron app, and we have since some breaking changes between both, it's a good idea to move forward and add this e2e tests even if they are not in it's final form (of considering the comments from #1533)

test: add e2e test for automated checks view

---

src/common/components/cards/card-kebab-menu-button.tsx
src/common/components/copy-issue-details-button.tsx
src/injected/frameCommunicators/frame-communicator.ts
src/injected/window-initializer.ts
src/tests/unit/tests/injected/frameCommunicators/frame-communicator.test.ts

Found some `Deps` types not following our deps pattern and declaring `windowUtils: WindowUtils` prop when not directly using it.
Found a class that receives an instance of `WindowUtils` but never using it.
Clean those two cases on this PR.

refactor: clean up window-utils usages

---

src/reports/components/report-sections/no-failed-instances-congrats.scss

Reduce text size in the "no failures" message in cards UI. Use 16px instead of 48px for the "Congratulations" text, and 14px instead of 40px for the "No failed automation checks were found" message.
Before change:
After change:

feat: Reduce text size in the "no failures" message in cards UI.

---

src/electron/views/screenshot/screenshot-view-model.ts

Small PR introducing the ViewModel type for the android screenshot component. Specific info is subject to change later, this is the minimum data that I think would be necessary given the current feature mockups.
Discussed offline with @waabid / @smoralesd about what the best folder layout might be for the view/viewmodel/viewmodelprovider; we agreed that it made the most sense to co-locate them all under `/electron/views/screenshot/` because they're so coupled to one another, regardless of the provider not technically being a view.
- [n/a, bag of data only] Added relevant unit test for your changes. (`yarn test`)
- [n/a, bag of data only] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage` …

feat(and-screenshot): add ScreenshotViewModel type

---

src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/renderer-initializer.ts
src/electron/views/screenshot/screenshot-view-model-provider.ts
src/electron/views/screenshot/screenshot-view-model.ts
src/tests/unit/tests/electron/views/screenshot/screenshot-view-model-provider.test.ts

Implements a `ScreenshotViewModelProvider` to convert from inputs of the form `AutomatedChecksView` already has to inputs in the format we expect `ScreenshotView` and its children to need. Wires it up as a dep to `AutomatedChecksView`, which will be using it to create the `ScreenshotViewModel` that its future child `ScreenshotView` will be accepting as a prop.
Out of scope:
* Wiring up `AutomatedChecksView` to invoke and pass down the provider (1628927)
* Wiring up the `deviceName` input (requires separate changes to UnifiedScanResultStoreData, 1639043)

feat(and-screenshot): create a ScreenshotViewModelProvider

---

src/DetailsView/components/command-bars.tsx
src/DetailsView/components/details-view-switcher-nav.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/command-bars.test.tsx.snap
src/tests/unit/tests/DetailsView/components/command-bars.test.tsx

This is the first step towards having a consistent header in all views. The next step will be to update the implementation of the buttons to match the new context (there are separate user stories for this work). This removes the BasicCommandBar construct since it's no longer referenced.
Screenshots (only difference was changing the __universalCardsUI__ flag:

feat: Optionally show start over and export buttons on command bar

---

build.yaml
pipeline/electron/distribute-electron.yaml
pipeline/electron/product-build.yaml

This PR updates the sample electron YAML to use a valid job name. It also refactors the distribute-electron.yaml to pull node-prereqs out. This way the node-prereqs only happen once per job. After this PR is in, development on this YAML will occur on a branch on the main repo to enable better/more frequent iteration.

chore: fix invalid job name in sample electron yaml & refactor to avoid duplicate node-prereq

---

build.yaml
pipeline/electron/product-build.yaml

This PR moves all platform-specific electron installers to a separate build. This keeps the CI lightweight and removes some flakiness inherent in electron-builder. 

refactor: move platform electron installers to separate build

---

src/background/tab-controller.ts
src/tests/unit/tests/background/tab-controller.test.ts

We don't really care for all tab changes; only ones that affect the URL (although I can see us caring for title at some point as well). As a result, we shouldn't fire tab update actions until we see this.
The result is we do not throw data away after scroll events cause tab update events (for loading, for example).
- [] Ran precheckin (`yarn precheckin`)

feat: tab controller only fires tab update actions when URL has changed

---

src/tests/end-to-end/common/scan-for-accessibility-issues.ts

Updates the way our e2e tests invoke axe-core to include WCAG 2.1 rules (they were previously only including WCAG 2.0 rules).
Electron e2e tests already include these tags.

test: expand web e2e a11y tests to include rule tags wcag21a/wcag21aa

---

src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/screenshot/screenshot-view.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
src/tests/unit/tests/electron/views/screenshot/screenshot-view.test.tsx

Wires up the `AutomatedChecksView` to invoke its `ScreenshotViewModelProvider` dep and pass the resulting `ScreenshotViewModel` to the `ScreenshotView`.
This involved some refactoring of the `AutomatedChecksView` to enable re-using common "highlighted result uid" data between the cards and screenshot views.
While I was adding the unit test expectations to verify the data passed to/from the provider, I also updated the unit test to add the missing similar verifications of the interactions with the cards view providers.

feat(and-screenshot): inject ScreenshotViewModel into the ScreenshotView

---

src/DetailsView/Styles/detailsview.scss

Modified width attribute for drop down title. Fixes issue #1219. There is a known issue where after the function is applied the drop down box shifts down outside of the title header. This will be addressed in a later PR.
Before Any Changes:
After Changes but Letter Space Function not Applied::
Letter Spacing Function Applied:

fix: drop down arrow overlapping text

---

webpack.config.js

`injected` css and js was not being used for electron but was still being generated. This was a leftover from when we tried to run `electron` with a target page and wanted to inject css and js on a target page. This is no longer the case and this can be safely removed.

chore: remove injected css and js from bundle for electron

---

electron-builder.yml

Currently, `electron-builder` is trying to sign the distributable when we run `yarn dist:electron` on a macOS and trying to find an identity. This PR forces it to not try to auto-discover apple developer certificate.

feat(electron-release): skip macOS code signing

---

src/common/components/cards/failed-instances-section.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/failed-instances-section.test.tsx.snap
src/tests/unit/tests/common/components/cards/failed-instances-section.test.tsx

The view model has the option be null when generated. This was missed in the re-factor.

fix: properly null check the view model in failed instances section

---

electron-builder.yml

The Windows installer we are exploring (NSIS) allows a one-click silent experience upon first install or an assisted experience. The assisted experience seems more guided & accessible to me - the user can choose whether they want to install it per-user / per-system and Narrator reads the content out. This PR changes the experimental installer to an assisted experience.
https://www.electron.build/configuration/nsis

feat(releases): switch to assisted installer experience

---

targets.config.js

We are generating `preview` drop using our `targets.config.js` but we dont publish this and never use it. So removing this to avoid even generating this.

chore: remove preview build from drop

---

src/DetailsView/components/adhoc-issues-test-view.tsx
src/DetailsView/components/adhoc-static-test-view.tsx
src/DetailsView/components/target-page-changed-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-static-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-changed-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/target-page-changed-view.test.tsx

The changes to the header bar require we change the message in the target page changed dialog (based on whether the feature flag is enabled).

feat: target page changed message is different when cards UI is enabled

---

src/background/injector-controller.ts
src/background/injector/content-script-injector.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/tests/unit/tests/background/content-script-injector.test.ts
src/tests/unit/tests/background/injector-controller.test.ts

As part of the permissions works, I'd like to convert `executeScriptInTab` and `insertCSSInTab` from using callbacks to use promises. This will help on how we handle permissions when injecting in a future PR.
As a note: we already converted `getUserData`, `setUserData` and `removeUserData` (all part of `StorageAdpater` type) successfully in the past.

refactor: promisify inject api calls

---

src/assessments/custom-widgets/test-steps/expected-input.tsx
src/assessments/custom-widgets/test-steps/instructions.tsx
src/assessments/custom-widgets/test-steps/keyboard-interaction.tsx
src/assessments/custom-widgets/test-steps/role-state-property.tsx

Some of the requirements in custom widgets did not display the custom name. A wrong property was being referenced causing this issue.

fix: Accessible name missing in certain custom widget requirement result instances

---

src/common/get-card-selection-view-data.ts
src/tests/unit/common/rule-based-view-model-provider.test.ts
src/tests/unit/tests/common/get-card-selection-view-data.test.ts

The intent of the change is that when the visual helper is disabled, no cards are selected and no instances are highlighted. Rule expansion should remain unchanged.
Note: the change to rule-based-view-model-provider.test.ts was only to add the visualHelperEnabled field because the code in rule-based-view-model-provider.ts only returns true for this field... for now... watch this space.

feat(consistent-cards-UI): Update card selection view data with visual helper

---

pipeline/electron/distribute-electron.yaml

This PR maps the environment variables ELECTRON_MIRROR and ELECTRON_CUSTOM_DIR to the create-electron-distributables step so that [electron-download](https://www.npmjs.com/package/electron-download) / electron-builder can use them. This allows us to run the pipelines with electron from a given URL.

feat(releases): map env variables in YAML to enable electron-mirror 

---

src/DetailsView/details-view-initializer.ts
src/background/actions/card-selection-action-creator.ts
src/common/components/cards/collapsible-component-cards.tsx
src/common/components/cards/instance-details.tsx
src/common/extension-telemetry-events.ts
src/common/message-creators/card-selection-message-creator.ts
src/tests/unit/tests/background/actions/card-selection-action-creator.test.ts
src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap
src/tests/unit/tests/common/components/cards/collapsible-component-cards.test.tsx
src/tests/unit/tests/common/components/cards/instance-details.test.tsx
src/tests/unit/tests/common/message-creators/card-selection-message-creator.test.ts

The card selection message creator was missing the telemetry necessary in the payload to fire telemetry for events. This adds that in addition to publishing telemetry for the new actions (expand/collapse all rules, toggleVisualHelper). Further, it back-fills a missing test for onRuleExpansionToggle.

feat: add telemetry to action/action messages for cards related UI

---

src/background/stores/card-selection-store.ts
src/tests/unit/tests/background/stores/card-selection-store.test.ts

Currently, the ```visualHelperEnabled``` state is always false and as such, the right items are not highlighted on a scan. Modified this to set the state to true when a scan is completed, making sure the right items are highlighted.

feat(consistend-cards-ui): enable the visual helper in card selection store when scan is completed

---

src/tests/unit/common/__snapshots__/rule-based-view-model-provider.test.ts.snap
src/tests/unit/common/rule-based-view-model-provider.test.ts

If you look at rule-based-view-model-provider.test.ts before this change, you will see that only three of a possible 8 test scenarios were being tested.
Admittedly, some test scenarios were unexpected, such as
{ isExpanded: false, isSelected: true, isHighlighted: false },
because this possibility __should__ never be produced by getCardSelectionViewData.
However, valid test scenarios such as
{ isExpanded: true, isSelected: false, isHighlighted: true },
and
{ isExpanded: false, isSelected: false, isHighlighted: false }
were never tested.
I Assert that unit tests are not just for testing the things we expect, but also for testing the things we don' t expect. Therefore, I have added code to create all the possible input scenarios.
Furthermore, I have added the 8 possible scenarios for when …

refactor: Add all possible scenarios to rule based view model provider unit tests

---

src/common/components/cards/rules-with-instances.scss
src/reports/automated-checks-report.scss

I noticed the text would look odd when there was limited space for the cards, so I've left-aligned the text.
Also removed some dead css in automated-check-report.scss
Before:
After:

fix: improve styling in cards + remove unnecessary css

---

src/common/components/cards/rules-with-instances.scss
src/reports/components/report-sections/minimal-rule-header.scss
src/reports/components/report-sections/minimal-rule-header.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/minimal-rule-header.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/minimal-rule-header.test.tsx

As per a comment in the previous PR, the text for the rule should not go under the outcome chip. This modifies the component to make that happen. Gif below of how it looks:

fix: match cards title to mocks

---

src/DetailsView/components/issues-table.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap

This moves show failures and export results under the feature flag so it is no longer shown when cards UI is enabled.

feat(consistent-cards-ui): move show failures and export results under the flagged component in Issues Table

---

src/background/actions/action-creator.ts
src/background/actions/action-hub.ts
src/background/actions/injection-action-creator.ts
src/background/actions/injection-actions.ts
src/background/actions/visualization-actions.ts
src/background/stores/tab-context-store-hub.ts
src/background/stores/visualization-store.ts
src/background/tab-context-factory.ts
src/tests/unit/common/visualization-store-data-builder.ts
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/actions/action-hub.test.ts
src/tests/unit/tests/background/actions/injection-action-creator.test.ts
src/tests/unit/tests/background/stores/visualization-store.test.ts

As part of the browser extension permissions effort, we need a to make some changes on how and when we inject our scripts into the target page.
In this refactor, the injection related code is move out of the `ActionCreator` into a more specific action creator. A new `InjectionActions` class has been created and all related classes (`VisualizationStore` is notable here) have been updated.

refactor: introduce injection action creator

---

src/icons/brand/blue/brand-blue.tsx
src/icons/brand/white/brand-white.tsx

When validating the and-screenshot feature against the AI4Web parsing test, there was some noise from the validator because our brand-images use SVG `<stop>` elements without an `offset` attribute. MDN suggests that this is supposed to be fine (they default to 0, which is what we want), but since adding the attributes is harmless anyway, I thought it would be nice to reduce the noise we see from the validator.
No UI change.

chore: remove noise during Parsing test by adding offset attrs to <stop> SVG elements

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts

We have a way to handle this message in the action creator per my last PR and now this is adding it to the details view to be able to fire that message (linked up by Dave later).

feat(consistent-cards-ui): added action message function for rescan visualization

---

src/common/components/cards/rules-with-instances.scss

This change enables rule header text to break within words if necessary, consistent with how the text within the cards already works. This fixes some rendering-off-the-side issues in electron at 400% zoom + 1280px width.

feat(and-screenshot): add break-all to rule headers to improve rendering at 400% zoom

---

src/common/styles/colors.scss
src/electron/views/screenshot/screenshot.scss

We were concerned that our screenshot might qualify as a "diagram" for the purposes of the WCAG 2.1 Graphic Contrast requirement, so we wanted to add a 3:1 contrast border on it. Note I'm using `outline` rather than `border` here to avoid pushing the image coordinates relative to the highlight boxes.
Before:
After:
Before:
After:

feat(and-screenshot): add a 3:1 contrast border for the screenshot image

---

src/tests/electron/tests/automated-checks-view.test.ts

This PR attempts to resolve the e2e_linux_electron failure seen in [this build](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=48934). The test failed because on initial load of the automated checks view, it found 0 rule groups rather than the expected set; I think the issue is that it's only waiting for the root container to exist, rather than waiting for its contents, so this PR updates the tests to more consistently wait for an indication that the contents have rendered (by waiting for the screenshot view, which only shows up after scanning is complete). …

test: electron e2e reliability: wait for screenshot view before querying its descendents

---

src/DetailsView/components/issues-table.tsx
src/DetailsView/components/report-export-component-factory.tsx
src/reports/report-generator.ts
src/tests/unit/tests/DetailsView/components/report-export-component-factory.test.tsx
src/tests/unit/tests/reports/report-generator.test.ts

As called out in #1676, `generateFastPassAutomatedCheckReport` should be named `generateFastPassAutomatedChecksReport` for consistency. This makes that change.

refactor: Rename generateFastPassAutomatedCheckReport

---

src/tests/electron/tests/automated-checks-view.test.ts

Slight refactoring of `automated-checks-view.test.ts` to remove a helper function that was just passing through its parameters; I think just constructing the `PositionStyles` in place is no more verbose and is a little more clear about which numbers are which.

refactor: remove unnecessary helper in automated-checks-view.test

---

src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts

add requestPermissions API to browser/chrome adapter

feat(permission): add requestPermissions API to browser/chrome adapter

---

src/background/background-init.ts
src/background/target-page-controller.ts
src/tests/unit/tests/background/target-page-controller.test.ts

The `TabController` is actually concerned with a target page tab (there is a `DetailsViewController` where a details view also lives on a tab, but is not handled by the `TabController`).
Hopefully, the new name makes more sense than the old one.

refactor: rename tab-controller

---

src/DetailsView/components/report-export-component-factory.tsx
src/DetailsView/components/start-over-component-factory.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-component-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-component-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/report-export-component-factory.test.tsx
src/tests/unit/tests/DetailsView/components/start-over-component-factory.test.tsx

[This commit](https://github.com/microsoft/accessibility-insights-web/pull/1676/commits/5ff9521421d1a7010aa7b861b4ffe96652a3e5c8) prematurely removed the ability to control the new command bar via feature flag. This PR reverts that commit.

feat(consistent-cards-ui): Restore feature flag control of command bar items

---

src/background/actions/tab-action-creator.ts
src/background/actions/tab-actions.ts
src/background/stores/inspect-store.ts
src/background/stores/tab-store.ts
src/background/stores/visualization-scan-result-store.ts
src/background/stores/visualization-store.ts
src/background/target-page-controller.ts
src/common/messages.ts
src/tests/unit/tests/background/actions/tab-action-creator.test.ts
src/tests/unit/tests/background/inspect-store.test.ts
src/tests/unit/tests/background/stores/tab-store.test.ts
src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
src/tests/unit/tests/background/stores/visualization-store.test.ts
src/tests/unit/tests/background/target-page-controller.test.ts

While @smoralesd and I were looking over the tab change/update machinery, we found ourselves frequently confused by the difference between `Tab.Change` and `Tab.Update` messages. This PR updates them (and associated helpers/actions) to more accurately reflect their purpose.

refactor: rename Tab.Update and Tab.Change messages to be distinguishable

---

src/common/uid-generator.ts
src/electron/flux/action-creator/device-connect-action-creator.ts
src/electron/platform/android/fetch-scan-results.ts
src/electron/platform/android/scan-controller.ts
src/electron/platform/android/scan-results-to-unified-results.ts
src/electron/platform/android/scan-results-to-unified-rules.ts
src/electron/platform/android/unified-result-builder.ts
src/electron/views/renderer-initializer.ts
src/injected/adapters/scan-results-to-unified-results.ts
src/injected/analyzers/unified-result-sender.ts
src/tests/unit/tests/electron/flux/action-creator/device-connect-action-creator.test.ts
src/tests/unit/tests/electron/platform/android/fetch-scan-results.test.ts
src/tests/unit/tests/electron/platform/android/scan-controller.test.ts
src/tests/unit/tests/electron/platform/android/unified-result-builder.test.ts

This comes from our last engineering discussion.
Renaming:
- `UUIGeneratorType` to `UUIDGenerator`
- `FetchScanRestulsType` to `ScanResultsFetcher`

refactor: renaming types using type as a suffix

---

src/DetailsView/components/no-displayable-preview-features-message.tsx
src/DetailsView/components/preview-features-container.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/preview-features-container.test.tsx.snap
src/tests/unit/tests/DetailsView/components/preview-features-container.test.tsx

Minor improvemns around `PreviewFeaturesContainer` component:
- Convert component to be a `NamedFC`
- Convert `NoDisplayableFeatureFlagMessage` to be a `NamedFC` (helps with the testing)
- Convert `PreviewFeaturesContainer` test to use snapshot testing

refactor: preview features container

---

src/common/components/cards/instance-details-footer.scss
src/common/components/cards/rule-resources.scss
src/common/styles/colors.scss
src/reports/components/instance-details.scss

Note: Recreated the PR to see if the checks would run this time.
This fixes the styling for cards UI, according to the the mock, for high contrast. Note: this makes a minor modification to the styling in cards UI when not in high-contrast but it's negligible.
Mock:
Gif:
Updated with the footer border as well:

fix: high contrast styling for cards UI

---

Dockerfile
src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/end-to-end/common/page-controllers/details-view-page.ts
src/tests/end-to-end/common/timeouts.ts

One of the most common timeout issue in our e2e was in settings-panel & high-contrast e2e tests where the `keyPress('escape')` was not getting registered properly and so I changed that event with pressing the cross button on the settings panel to exit it. This should hopefully fix that timeout error on settings panel tests.
Also added `--no-cache` to `yarn:dev` in our docker to avoid a dev build cache system which I was hitting regularly in my local build.

fix: minor changes to improve stability for e2e tests

---

src/DetailsView/components/start-over-component-factory.tsx
src/DetailsView/components/target-page-changed-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-component-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-changed-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/start-over-component-factory.test.tsx
src/tests/unit/tests/DetailsView/components/target-page-changed-view.test.tsx

Currently, when the Cards UI is enabled (this is by default on master right now), the **Start over** button dissapear and the **Show failures** toggle shows up again when the user changes the target page url.
The expected behavior is: only the **Start over** button should be used when the Cards UI is enabled.
**Notes**
It may be easier to review this commit by commit.
**Before: with the bug**
**After: bug fixed**

fix: start over-toogle on fast pass

---

src/DetailsView/components/issues-table.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap

**Show failures** toggle disappear when it's toggle off. 
This happens under the old UI (the one that uses the details list)
**Before: toggle disappear**
**After: fixed**

fix: disappearing "show failures" toggle under fast pass

---

src/background/background-init.ts
src/background/global-context-factory.ts
src/background/global-context.ts
src/background/user-configuration-controller.ts
src/common/insights-window-extensions.ts
src/tests/end-to-end/common/browser-factory.ts
src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/end-to-end/common/page-controllers/background-page.ts
src/tests/end-to-end/common/page-controllers/details-view-page.ts
src/tests/end-to-end/tests/details-view/settings-panel.test.ts
src/tests/unit/tests/background/user-configuration-controller.test.ts

This PR introduces a new controller on the background page console similar to the existing `window.insightsFeatureFlags` controller named `window.insightsUserConfiguration`. We want this primarily so that e2e tests can be updated to use it rather than UI to do most user configuration tasks (particularly, dismissing the initial telemetry prompt and setting high contrast mode), since the current strategy of setting high contrast mode via the UI has the following repercussions:
* causes issues for the upcoming permission changes (many tests attempt to toggle details view settings from states that will soon be "tab closed" pages)
* takes a lot of unnecessary time
* causes a lot of unnecessary instability
This PR introduces the new controller, updates existing browser setup to use it for …

test: add background page window.insightsUserConfiguration controller for E2Es to use

---

src/DetailsView/components/issues-table.tsx
src/DetailsView/components/report-export-component-factory.tsx
src/reports/components/report-sections/full-rule-header.tsx
src/reports/components/report-sections/not-applicable-checks-section.tsx
src/reports/components/report-sections/passed-checks-section.tsx
src/reports/components/report-sections/report-section-factory.tsx
src/reports/components/report-sections/rules-only.tsx
src/reports/components/report-sections/summary-section.tsx
src/reports/report-generator.ts
src/reports/report-html-generator.tsx
src/tests/unit/tests/DetailsView/components/report-export-component-factory.test.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/not-applicable-checks-sections.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/passed-checks-sections.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/rules-only.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/summary-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/full-rule-header.test.tsx
src/tests/unit/tests/reports/components/report-sections/not-applicable-checks-sections.test.tsx
src/tests/unit/tests/reports/components/report-sections/passed-checks-sections.test.tsx
src/tests/unit/tests/reports/components/report-sections/rules-only.test.tsx
src/tests/unit/tests/reports/components/report-sections/summary-section.test.tsx
src/tests/unit/tests/reports/report-generator.test.ts
src/tests/unit/tests/reports/report-html-generator.test.tsx

Current `ReportHtmlGenerator.generateHtml` expect a `scanResult: ScanResults` and a `cardsViewData: CardsViewModel` parameters.
Both `scanResult` and `cardsViewData` have analogous information (rule results, passes, fails, etc) so technically speaking we don't need both.
In this PR I'm removing the old `scanResult` in favor on using the `cardsViewData` only.
Checked the report works properly with both the old details list and the new cards UI.

refactor: automated checks report does not uses ScanResults

---

.vscode/settings.json

Now that we've decided on 100col as our new limit, adding a new 100-col ruler to our workspace vscode settings (leaving the 140col as well until we finish updating existing code)

chore: add 100-column ruler to vscode project settings

---

src/tests/end-to-end/common/element-identifiers/target-page-selectors.ts
src/tests/end-to-end/common/page-controllers/page.ts
src/tests/end-to-end/common/page-controllers/target-page.ts
src/tests/end-to-end/tests/popup/adhoc-panel.test.ts
src/tests/end-to-end/tests/target-page/issue-dialog.test.ts
src/tests/end-to-end/tests/target-page/tabstop.test.ts
src/tests/end-to-end/tests/target-page/visualization-boxes.test.ts

This PR aims to improve an e2e reliability issue that already existed but was exacerbated by #1717 (see [motivating failure](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=51673)), where the tabstop tests attempt to interact with the tab stop visualization on the target page before they verify that the target page visualizations are in a ready state. With this PR:
* The test now waits for the injected shadow root to be present on the target page before attempting to issue "Tab" keystrokes
* The test's expectations about the resulting tab stop visualizations are now in the form of "expect visualization to reach target state within timeout", rather than "expect visualization state to be X right now"
Cleans up a little page controller method naming nearby as well. …

test: add readiness checks to target page e2es before interacting with visualizations

---

src/DetailsView/components/issues-table.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap
src/tests/unit/tests/DetailsView/components/issues-table.test.tsx

Using the cards ui feature flag to make the text different when the automated checks are disabled.
**Fix for cards ui**
**Not changed for details list**

fix: "turn on automated checks" text is outdated

---

src/tests/common/element-snapshot-formatter.ts
src/tests/end-to-end/common/page-controllers/target-page.ts
src/tests/end-to-end/tests/common/settings-drop-down.test.ts
src/tests/end-to-end/tests/content/guidance-content.test.ts
src/tests/end-to-end/tests/details-view/preview-features.test.ts
src/tests/end-to-end/tests/popup/first-time-dialog.test.ts
src/tests/end-to-end/tests/popup/hamburger-menu.test.ts
src/tests/end-to-end/tests/popup/launchpad.test.ts
src/tests/unit/tests/reports/package/integration.test.ts

Now that we are consuming element-snapshot-formatter in both unit and e2e tests it seemed right to move it to a common directory for shared code for any kind of test. 
- [n/a] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). Check workflow guide at: `<rootDir>/docs/workflow.md`

refactor: Moved element-snapshot-formatter to common directory for all tests

---

src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/common/notification-creator.ts
src/tests/unit/tests/common/notification-creator.test.ts

In this case, promisifying `createNotification`.

refactor: promisify create notification

---

src/DetailsView/components/action-and-cancel-buttons-component.tsx
src/DetailsView/components/failure-instance-panel-control.tsx
src/DetailsView/components/no-content-available.tsx
src/DetailsView/components/overview-content/help-links.tsx
src/DetailsView/components/overview-content/overview-content-container.tsx
src/DetailsView/components/overview-content/overview-heading.tsx
src/DetailsView/components/overview-content/overview-help-section.tsx
src/DetailsView/components/requirement-link.tsx
src/DetailsView/components/test-status-choice-group.tsx
src/common/components/cards/card-kebab-menu-button.tsx
src/common/components/cards/how-to-fix-card-row.tsx
src/common/components/cards/instance-details-footer.tsx
src/common/components/cards/instance-details-group.tsx
src/common/components/cards/result-section-title.tsx
src/common/components/cards/result-section.tsx
src/common/components/cards/rule-resources.tsx
src/common/components/cards/rules-with-instances.tsx
src/common/components/scanning-spinner/scanning-spinner.tsx
src/common/components/toast.tsx
src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/automated-checks/components/command-bar.tsx
src/electron/views/automated-checks/components/title-bar.tsx
src/electron/views/device-connect-view/components/device-connect-body.tsx
src/electron/views/device-connect-view/components/device-connect-footer.tsx
src/electron/views/device-connect-view/components/device-connect-header.tsx
src/electron/views/device-connect-view/components/device-connect-port-entry.tsx
src/electron/views/device-connect-view/components/window-title.tsx
src/electron/views/device-disconnected-popup/device-disconnected-popup.tsx
src/reports/components/report-sections/footer-section.tsx
src/reports/components/report-sections/no-failed-instances-congrats.tsx

Per today's Engineering Discussion, updating all imports of css modules to use `import * as styles from './this-component.scss'`
Intentionally leaves out-of-scope any secondary updates of import ordering/grouping.

chore: update all uses of css modules to use import * as styles

---

src/assessments/headings/test-steps/heading-level.tsx

- In Assessment > Headings > Heading level: added a space between a word that has Markup.Emphasis and a word without any styling
Before:
After:

fix: minor typo in Headings test of Assessments

---

src/background/tab-context-broadcaster.ts
src/background/tab-context-factory.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/common/message-creators/remote-action-message-dispatcher.ts
src/common/state-dispatcher.ts
src/tests/unit/tests/background/global-context-factory.test.ts
src/tests/unit/tests/background/tab-context-broadcaster.test.ts
src/tests/unit/tests/background/tab-context-factory.test.ts
src/tests/unit/tests/background/target-page-controller.test.ts
src/tests/unit/tests/common/message-creators/remote-action-message-dispatcher.test.ts
src/tests/unit/tests/common/state-dispatcher.test.ts

Continues promisifying our assorted browserAdapter APIs

refactor: promisify browserAdapter sendMessageTo* APIs

---

src/reports/components/report-sections/rules-only.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/rules-only.test.tsx.snap
src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap

We are hardcoding a class name for `RulesOnly` component. This works fine on "dev" mode builds but breaks on "production" mode builds. The main reason is: on production mode, we add a hash as a suffix to all class names (to avoid name collision) while on dev mode we don't change the class names at all.
Using the class name from the corresponding scss.d.ts file fix this issue

fix: use class name from scss.d file

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/details-view-command-bar.scss
src/DetailsView/components/details-view-command-bar.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap

Previously, the start over and export results button text would wrap. This is not necessary, so this PR makes sure they don't.
Before:
After:

fix: the command bar buttons don't wrap their text when window size is decreased

---

src/electron/main/main.ts

This PR fixes a small issue where `autoUpdate` was not getting called even once when the window was loaded and this would have created a situation where the autoupdate is just called after the user has spent an hour on the app, which is not what we want.
After this change, the check for update will be called once when the main window is loaded and that function also sets up an 1 hour recurring check

feat(electron-update): call autoupdate after mainwindow is loaded

---

src/DetailsView/details-view-initializer.ts

The card selection store in details view relies on a store proxy. The store proxy relies on having a tab Id to filter to messages that it receives (since the details view is simply a page with a tabId in a parameter inside the URL). The issue was that the store is receiving messages but was never setup with any tabId.
This seems to indicate a future re-factoring that would reduce these kind of issues: necessitate a tabId on creation and in the scenarios where we don't need it (the target page) we can specifically pass null. At least visually, we do not have to go searching in different places to "initialize" something. …

fix: card view state is reset after link is clicked

---

src/DetailsView/details-view-initializer.ts
src/common/store-proxy.ts
src/popup/popup-initializer.ts
src/tests/unit/tests/common/store-proxy.test.ts

As per my previous PR, I feel like this PR will reduce future issues arising when creating new stores and using them in details/pop-up/etc views.

refactor: store proxy takes in tabId via constructor

---

src/DetailsView/components/switcher.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/switcher.test.tsx.snap
src/tests/unit/tests/DetailsView/components/switcher.test.tsx

Currently the `Switcher` uses a `div` inside of an `span`. We do control the inner `div` but the `span` comes from the `Dropdown` component of **Office Fabric** so the direct way to solve this is to change the `div` into a `span`. Also, by doing this, there is no need to change css.
I updated the tests and added some missing ones.
**Notes**
There should be not visible changes on the UI for this PR.

fix: parsing error on the switcher

---

pipeline/electron/distribute-publish-electron-linux.yaml
pipeline/electron/distribute-sign-publish-electron-mac.yaml
pipeline/electron/distribute-sign-publish-electron-windows.yaml
pipeline/electron/prepare-publish-artifact.yaml

Currently, we publish an artifact for the electron build that includes both the packed and unpacked versions of the product for each platform. This is useful for testing purposes, but we only need the packed version for the actual release process. This PR adds a build step that copies only the files we need to release into a separate directory for use in the release pipeline. The artifact is then published as usual.

feat(electron-update): Add task to prepare & publish electron artifact

---

src/electron/views/device-connect-view/send-app-initialized-telemetry.ts
src/electron/views/renderer-initializer.ts
src/electron/window-management/platform-info.ts
src/tests/unit/tests/electron/views/device-connect-view/send-app-initialized-telemetry.test.ts
src/tests/unit/tests/electron/window-management/platform-info.test.ts

Part of the electron-update feature is a requirement to send platformInfo in our telemetry. I changed our initialization telemetry event to include `os` as a property with `currentProcess` from node.
I didn't use `process` directly and added `getOSName` a function in our `PlatformInfo` class because the other `getOs` function returned from an enum, which essentially is a number.

feat(electron-update): send osName from platform as part of telemetry

---

src/background/actions/action-creator.ts
src/background/actions/content-action-creator.ts
src/background/actions/details-view-action-creator.ts
src/background/actions/scoping-panel-action-creator.ts
src/background/details-view-controller.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/actions/content-action-creator.test.ts
src/tests/unit/tests/background/actions/details-view-action-creator.test.ts
src/tests/unit/tests/background/actions/scoping-panel-action-creator.test.ts
src/tests/unit/tests/background/details-view-controller.test.ts

In this case, promisifying `createTabInNewWindow`.

refactor: promisify create tab new window

---

src/tests/end-to-end/common/element-identifiers/popup-page-element-identifiers.ts
src/tests/end-to-end/common/page-controllers/page.ts
src/tests/end-to-end/common/page-controllers/popup-page.ts
src/tests/end-to-end/tests/popup/adhoc-panel.test.ts

We have some flakyness on our e2e test for the ad hoc tools panel. Specifically:
```node
TimeoutError: waiting for selector ".ad-hoc-tools-panel" failed: timeout 5000ms exceeded
129 |     public async waitForSelector(selector: string, options?: Puppeteer.WaitForSelectorOptions): Promise<Puppeteer.ElementHandle<Element>> {
130 |         return await this.screenshotOnError(
> 131 |             async () => await this.underlyingPage.waitForSelector(selector, { timeout: DEFAULT_PAGE_ELEMENT_WAIT_TIMEOUT_MS, ...options }),
|                                                   ^
132 |         );
133 |     }
134 | 
```
Build reference [here](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=53956) (look for attempt #1)
This PR is an attempt to fix this by changing clicking …

test: adhoc panel timeout flakyness fix

---

src/background/target-page-controller.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/tests/unit/common/simulated-browser-adapter.ts
src/tests/unit/tests/background/target-page-controller.test.ts

In this case, promisifying `getAllWindows`.

refactor: promisify get all windows

---

src/common/types/store-data/visualization-scan-result-data.ts

Small refactor inlining an unnecessary generic interface in visualization-scan-result-data

refactor: remove unnecessary interface from visualization-scan-result-data

---

pipeline/electron/electron-e2e-job-per-environment.yaml
pipeline/electron/electron-e2e-reliability.yaml

To keep our end-to-end reliable in long term, it is a good idea that we create a reliability build for electron end to end as we keep adding more tests and code to our electron code base.
On similar footprint as our current e2e-reliability build pipeline, adding this new electron-e2e-reliability build with a little different trigger point.

chore: introduce electron e2e reliability build similar to e2e-reliability

---

src/injected/components/details-dialog.tsx
src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap

Narrator is not reading the labels for the Rule Name and Success Criterion in the Details Dialog when you click a failure instance, as pictured below
Screen Reader Experience Summary
For example’s sake, say the rule name is aria-required-attr. The AT behavior for the “Rule Name” and “Success Criteria” cases are identical; for brevity, I’m only using the Rule Name case for the examples of what the AT reads out:
For Rule Name Case
**What was read before the PR**
1. Narrator:
1. Tab: reads “link aria-required-attr"
2.  Scan Mode: “Heading level 3 Rule Name link aria-required-attr”
2. NVDA:
1. Tab: “aria-required-attr link”
2. Scan Mode: “Heading level 3 rule name link aria-required-attr”
3. JAWS
1. Tab: “link aria-required-attr”
2. Scan Mode: “Heading level 3 Rule Name link …

fix: Narrator not reading details dialog label

---

src/background/actions/action-payloads.ts
src/background/stores/assessment-store.ts
src/background/stores/unified-scan-result-store.ts
src/common/types/scan-incomplete-warnings.ts
src/common/types/store-data/assessment-result-data.ts
src/common/types/store-data/unified-data-interface.ts
src/injected/analyzers/analyzer-provider.ts
src/injected/analyzers/analyzer.ts
src/injected/analyzers/base-analyzer.ts
src/injected/analyzers/batched-rule-analyzer.ts
src/injected/analyzers/rule-analyzer.ts
src/injected/analyzers/tab-stops-analyzer.ts
src/injected/main-window-initializer.ts
src/injected/scan-incomplete-warning-detector.ts
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/stores/assessment-store.test.ts
src/tests/unit/tests/background/stores/unified-scan-result-store.test.ts
src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts
src/tests/unit/tests/injected/analyzers/base-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
src/tests/unit/tests/injected/scan-incomplete-warning-detector.test.ts

This PR:
* Adds `scanIncompleteWarnings` data to the assessment and unified result stores
* Adds a new `ScanIncompleteWarningDetector` to handle populating the new data
* Updates the previously-done analyzer piping to pipe around the new `ScanIncompleteWarningDetector` instead of an `IframeDetector`
* Initializes the new detector in `main-window-initializer`
Out of scope (separate PRs):
* Wiring up the data from the permissions store @lisli1 sent out for PR recently to the new detector
* Consuming the new data in the new UI component @waabid has out for draft PR
- [0/a] (UI changes only) Verified usability with NVDA/JAWS

feat(permissions): add ScanIncompleteWarning data into result stores

---

electron-builder.yml

This PR updates the electron-builder YAML config in two ways:
1. The version number is removed from the packaged file. This never needed to be there in the first place and will improve how the application name displays in linux.
2. The publisher name is set for Windows. This needs to match the name on the signing cert.

chore: Update electron-builder config

---

electron-builder.yml

PR #1859 removed "setup" from the windows electron package name in addition to the version number. Based on (this issue)[https://github.com/electron-userland/electron-builder/issues/4312#issuecomment-559171985], that was a mistake--updates stopped installing on Windows. This restores setup to the package name on Windows.

chore: restore setup to windows package name

---

src/background/actions/action-payloads.ts
src/electron/platform/android/unified-result-builder.ts
src/injected/analyzers/unified-result-sender.ts
src/injected/main-window-initializer.ts
src/tests/unit/tests/background/actions/unified-scan-result-action-creator.test.ts
src/tests/unit/tests/electron/platform/android/__snapshots__/unified-result-builder.test.ts.snap
src/tests/unit/tests/electron/platform/android/scan-controller.test.ts
src/tests/unit/tests/injected/analyzers/unified-result-sender.test.ts

This PR wires up data into `UnifiedScanCompletePayload`s for the new `scanIncompleteWarnings` property. In android, we unconditionally pass an empty list, and in web, we delegate to the same previously-added `ScanIncompleteWarningDetector` previously added to populate assessment data. 

feat(permissions): pipe scan incomplete warnings to unified result scan payloads

---

src/DetailsView/components/settings-panel/settings/issue-filing/issue-filing-settings.tsx
src/issue-filing/components/issue-filing-settings-container.tsx
src/tests/unit/tests/DetailsView/components/settings-panel/settings/issue-filing/__snapshots__/issue-filing-settings.test.tsx.snap
src/tests/unit/tests/issue-filing/components/__snapshots__/issue-filing-settings-container.test.tsx.snap

The Issue Filing label was not read by NVDA/Narrator, so users were not told the context of the radio buttons/options; they simply heard "Github" or "Azure Boards". With the changes in this PR, users will now hear "Issue Filing" before they are read the options.

fix: Issue Filing label not being read in the Settings Pane

---

src/DetailsView/components/no-content-available.tsx
src/manifest.json
src/tests/unit/tests/DetailsView/components/__snapshots__/no-content-available.test.tsx.snap

In order to release all the fixes and new features we haven't yet, we are changing the permissions back (remove `"activeTab"` and re-add the original permissions). We are going to release and wait the 5 to 7 business days it takes for our extension to go through the review process.
We are not changing the logic we already have to show the **No content available** message on the details view; that'll be a "preview" of how our extension will work once we finally change to make full use of "activeTab" + optional all-url, all-files permissions.
I also update the **No content available" text to make it more clear how to "reactivate" our extension on existing details view tab.

fix: adding all-url,all-file permissions back

---

src/tests/end-to-end/tests/details-view/cross-origin-iframe.test.ts

Re-adding **all-origin** permissions break an e2e test which assumes **activeTab**-like permissions.
This PR mark the test as skip (for now).

test: skip activeTab only test

---

src/electron/views/device-connect-view/device-connect-view.scss
src/electron/views/root-container/components/root-container.scss

A recent change in scss file caused the interactive elements on the telemetry dialog in the electron product to stop accepting mouse interaction. This happens because `-webkit-app-region: no-drag` was not set on those elements. Even though the telemetry dialog is a child of the device connect view, it actually renders as a sibling. This PR moves the `-webkit-app-region: no-drag` properties for buttons and inputs out to apply globally so that we don't have to worry about similar problems in the future.
Before:
After: …

fix: move interactive no-drag styles to electron root

---

src/tests/electron/common/view-controllers/app-controller.ts

An earlier PR added a "resize to minimum supported dimensions" operation to the setup of the electron E2E view controllers. Unfortunately, this introduced a source of flakiness (#1846), and attempts to update the resize behavior to avoid the flakiness have proven unsuccessful and hit their timebox (#1862), so reverting the changes until such time as they can be restored without affecting PR/CI builds

test: revert flaky resize operation from electron e2es

---

src/manifest.json
src/tests/end-to-end/tests/details-view/cross-origin-iframe.test.ts

Changing permissions back to use `activeTab`. Additionally, re-enabling a cross-origin e2e test that was broken because of having all-origin permissions.

feat(permissions): restore activeTab. re-enable related e2e test

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/DetailsView/components/start-over-dropdown.tsx
src/background/actions/action-creator.ts
src/background/actions/assessment-action-creator.ts
src/common/messages.ts
src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
src/tests/unit/tests/DetailsView/components/start-over-dropdown.test.tsx
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/actions/assessment-action-creator.test.ts

The start over operation operates for a test and not for a requirement. As such, I've removed that as a parameter from the function call (and renamed the function to startOverTest, since that is more appropriate).

refactor: removed parameter for requirement for startOverTest (not used)

---

src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts

Found a couple of functions we're not actually using anywhere. Removing said functions from both, type and class.

refactor: remove unused browser-adapter functions

---

src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/common/url-validator.ts
src/tests/unit/tests/common/url-validator.test.ts

In this case, promisifying `isAllowedFileSchemeAccess`.

refactor: promisify is allowed file scheme access

---

src/injected/client-store-listener.ts
src/injected/main-window-initializer.ts
src/injected/scan-incomplete-warning-detector.ts
src/tests/unit/tests/injected/scan-incomplete-warning-detector.test.ts

This PR initializes a store proxy for the new permissions state store in the injected page and hooks it up to the scan incomplete warning detector.

feat(permissions): wire permissions store to scan incomplete warning detector

---

src/background/actions/unified-scan-result-action-creator.ts
src/background/tab-context-factory.ts
src/common/extension-telemetry-events.ts
src/injected/analyzers/unified-result-sender.ts
src/tests/unit/tests/background/actions/unified-scan-result-action-creator.test.ts
src/tests/unit/tests/injected/analyzers/unified-result-sender.test.ts

Sending new telemetry event when we detect there are iframes in the target page and the extension has no all-origin permissions.
Decided to send the telemetry event as part of the scan complete message on the unified result side.
Still debating if sending the whole `'scanIncompleteWarnings'` array make sense or if we need to convert it or even discard it. Sending the warnings array (which is easier I think) coverts the scenario of having more than one type of warning while scanning, so if we add a new one, we don't need to change the telemetry part.

feat(permissions): send telemetry for iframe + no permissions

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/DetailsView/components/iframe-warning.tsx
src/DetailsView/components/scan-incomplete-warning.tsx
src/DetailsView/components/warning-configuration.tsx
src/DetailsView/handlers/allurls-permission-handler.ts
src/tests/unit/tests/DetailsView/components/__snapshots__/iframe-warning.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/scan-incomplete-warning.test.tsx.snap
src/tests/unit/tests/DetailsView/components/iframe-warning.test.tsx
src/tests/unit/tests/DetailsView/components/scan-incomplete-warning.test.tsx
src/tests/unit/tests/DetailsView/handlers/allurls-permission-handler.test.ts

This creates different warning configurations for assessment and fastpass (to be used by switcher nav in the future). The different warning configurations can specify what is shown in the message bar per the different views (necessary for different behavior between the two views).

feat(permissions): created different scan incomplete messages for assessment/fastpass

---

src/common/components/gear-options-button-component.scss

The gear-button class name is not being modified by css modules and hence needs the global qualifier.

fix: gear button's top margin

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/background/actions/permissions-state-actions.ts
src/background/browser-permissions-tracker.ts
src/background/global-action-creators/permissions-state-action-creator.ts
src/background/global-context-factory.ts
src/background/stores/global/permissions-state-store.ts
src/common/extension-telemetry-events.ts
src/common/telemetry-data-factory.ts
src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
src/tests/unit/tests/background/browser-permissions-tracker.test.ts
src/tests/unit/tests/background/global-action-creators/permissions-state-action-creator.test.ts
src/tests/unit/tests/background/stores/global/permissions-state-store.test.ts
src/tests/unit/tests/common/telemetry-data-factory.test.ts

This adds telemetry for when the setPermission action is called; since this requires a change in payload, there's lots to change. Additionally, we're currently **not** sending telemetry for when **the user changes their permissions from the settings**. If this needs to change, doing so would be easy.

feat(permissions): add telemetry to set permission payload for url permissions

---

src/DetailsView/components/iframe-warning.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/iframe-warning.test.tsx.snap

feat(permissions): remove extra space in iframe warning

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/background/actions/action-payloads.ts
src/background/browser-permissions-tracker.ts
src/background/stores/global/permissions-state-store.ts
src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
src/tests/unit/tests/background/browser-permissions-tracker.test.ts
src/tests/unit/tests/background/global-action-creators/permissions-state-action-creator.test.ts
src/tests/unit/tests/background/stores/global/permissions-state-store.test.ts

While working on adding e2e test for the permissions feature (and debugging a nasty issue) I got confused by the 2 names we have for the same value, one on the payload side, one on the state side.
This PR normalize the names so they are both the same. I chose the name from the state as it seems a better one.

refactor: rename payload property to match state property

---

src/background/background-init.ts
src/background/browser-message-broadcaster-factory.ts
src/background/chrome-command-handler.ts
src/background/target-page-controller.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/popup/target-tab-finder.ts
src/tests/unit/common/simulated-browser-adapter.ts
src/tests/unit/tests/background/browser-message-broadcaster-factory.test.ts
src/tests/unit/tests/background/chrome-command-handler.test.ts
src/tests/unit/tests/background/target-page-controller.test.ts
src/tests/unit/tests/popup/target-tab-finder.test.ts

In this case, promisifying `tabsQuery`.

refactor: promisify tabs query

---

src/background/actions/action-creator.ts
src/background/actions/inspect-action-creator.ts
src/background/actions/tab-action-creator.ts
src/background/details-view-controller.ts
src/background/tab-context-factory.ts
src/background/target-tab-controller.ts
src/common/browser-adapters/browser-adapter.ts
src/common/browser-adapters/chrome-adapter.ts
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/actions/inspect-action-creator.test.ts
src/tests/unit/tests/background/actions/tab-action-creator.test.ts
src/tests/unit/tests/background/details-view-controller.test.ts
src/tests/unit/tests/background/target-tab-controller.test.ts

In this case, promisifying `switchToTab`.
`switchToTab` actually have a little logic inside (so not strictly an adapter function): 1) set the tab to active; 2) set the window to focused. Simple enough but doesn't really match the Adapter Pattern. As a future work (so out of scope for this PR) we may want to extract that bit of logic to, says, `TabSwitcher` class (or plainly a function).

refactor: promisify switch to tab

---

src/DetailsView/extensions/wait-for-all-requirements-to-complete.tsx
src/tests/unit/tests/DetailsView/extensions/__snapshots__/wait-for-all-requirements-to-complete.test.tsx.snap
src/tests/unit/tests/DetailsView/extensions/wait-for-all-requirements-to-complete.test.tsx

Currently, Assessment -> Automated checks shows a "scanning" spinner while we run axe. We are using Office Fabric `<Spinner>` which does not get properly announce (it does not get announced at all).
In this PR, we are switching to use `<ScanningSpinner>` to get a proper announcement. This is the same component we are already using in the new cards UI (so it's already being use on electron app and fast pass -> automated checks)

fix: scanning spinner is not announced on assessment's automated checks

---

src/popup/components/launch-panel-header.tsx
src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
src/tests/unit/tests/popup/components/__snapshots__/launch-panel-header.test.tsx.snap
src/tests/unit/tests/popup/components/launch-panel-header.test.tsx

Originally (like eons ago) we had a **feedback** option on the popup's hamburger menu. The aria label of that button mentions this but since the option has been long gone, this PR update the label.

fix: popup hamburger menu aria label

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/generic-panel.tsx
src/DetailsView/components/settings-panel/settings-panel.scss
src/DetailsView/components/settings-panel/settings-panel.tsx
src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/unit/tests/DetailsView/components/settings-panel/__snapshots__/settings-panel.test.tsx.snap
src/tests/unit/tests/DetailsView/components/settings-panel/settings-panel.test.tsx

Fix by adding top padding (same value as current bottom padding)
Also convert the settings panel to use css-module.
**before**
**after**

fix: telemetry settings toggle focus ring cut-off

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/target-change-dialog.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/target-change-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/target-change-dialog.test.tsx

Currently on the **Assessment in progress** dialog, we show 2 buttons: 1) **Continue previous**; and 2) **Start new** but we are using `float: right` in order to align the items to the right end. This make for a reverse tabbing order (even though, we are not using `tabIndex`).
In this PR, the buttons order on the html structure are trued-up and then aligned to the right end using **css flex box**.

fix: assessment in progress dialog buttons have reverse tab order

---

src/background/stores/assessment-store.ts
src/tests/unit/tests/background/stores/__snapshots__/assessment-store.test.ts.snap
src/tests/unit/tests/background/stores/assessment-store.test.ts

We have some missing tests for the assessment store, This PR add those tests and gets the coverage to 99.52% (statements)

test: increase coverage for assessment store

---

src/common/components/cards/fix-instruction-color-box.scss

The styling being removed is not being referenced anywhere else, so it is safe to remove.

fix: css styling for color-contrast how to fix instructions

---

src/popup/Styles/popup.scss

Fix the high contrast mode colors for the popup gear and hamburger menu icons and their contextual menu icons too.
I decided to not use any custom colors (i.e. use office fabric colors directly) for 2 reasons: 1) simplify (by removing custom styles from our code base) and; 2) match what we're doing with the gear icon on the details view (which have no custom color already)
**Gear & Hamburger menu buttons**
_before_
_after_
**Hamburger contextual menu icons**
_before_
_after_

fix: high contrast menu icons fix

---

prettier.config.js
src/injected/visualization/base-drawer.ts
src/injected/visualization/center-position-calculator.ts
src/injected/visualization/custom-widgets-formatter.ts
src/injected/visualization/drawer-utils.ts
src/injected/visualization/element-highlight.tsx
src/injected/visualization/failure-instance-formatter.ts
src/injected/visualization/frame-formatter.ts
src/injected/visualization/heading-formatter.ts
src/injected/visualization/highlight-box-drawer.ts
src/injected/visualization/highlight-box-formatter.ts
src/injected/visualization/highlight-visualization.tsx
src/injected/visualization/issues-formatter.ts
src/injected/visualization/landmark-formatter.ts
src/injected/visualization/non-text-component-formatter.ts
src/injected/visualization/single-target-drawer.ts
src/injected/visualization/svg-drawer.ts
src/injected/visualization/svg-shape-factory.ts
src/injected/visualization/svg-solid-shadow-filter-factory.ts
src/injected/visualization/tab-stops-formatter.ts

This PR add the following folders to the line width override:
- `src/injected/visualization/**/*`
The reset of the `src/injected` folder will be done in a separated PR to keep the PRs size small.

chore: update line width for most folders under scr/injected/visualization

---

electron-builder.yml

This PR updates electron-builder.yml to achieve effects listed [here](https://www.electron.build/configuration/nsis#custom-nsis-script). The installer now deletes app data upon uninstall (addressing #1868) and removes the per-machine/per-user option. We don't plan to support per-machine installs - these require elevation and aren't updating correctly in electron-builder.
One side effect of this change is that the confirmation screen post-install goes away. This is due to the default options in electron-builder. To bring this back, we may need a custom NSIS script. This will be moved into a separate issue.

fix: remove electron per-machine installer option & old data on uninstall

---

prettier.config.js
src/DetailsView/Styles/detailsview.scss
src/DetailsView/actions/details-view-action-message-creator.ts
src/DetailsView/actions/issues-selection-factory.ts
src/DetailsView/details-view-body.tsx
src/DetailsView/details-view-container.tsx
src/DetailsView/details-view-initializer.ts
src/DetailsView/detailsView.html
src/DetailsView/document-title-updater.ts
src/DetailsView/extensions/assessment-report-extension-point.ts
src/DetailsView/extensions/details-view-extension-point.ts
src/DetailsView/extensions/select-first-requirement-after-automated-checks.ts
src/DetailsView/extensions/wait-for-all-requirements-to-complete.tsx
src/DetailsView/handlers/allurls-permission-handler.ts
src/DetailsView/handlers/assessment-instance-table-handler.tsx
src/DetailsView/handlers/details-view-toggle-click-handler-factory.ts
src/DetailsView/handlers/get-document-title.ts
src/DetailsView/handlers/master-checkbox-config-provider.ts
src/DetailsView/handlers/preview-feature-flags-handler.ts

This PR changes the files under `src/DetailsView` to comply with our new prettier config of 100 line width.
Left out of this PR in order to keep it small: `src/DetailsView/components`. This folder will be gradually added in subsequent PR's

chore: update line width for folder scr/DetailsView (partial update)

---

src/DetailsView/Styles/detailsview.scss

Update background color for Fast Pass > Automated checks view.
The color change:
- only affect the right side section (not the nav)
- only affects Fast Pass> Automated checks, not other views (Tab Stops nor Assessments)

fix: automated checks background color

---

src/popup/Styles/popup.scss
src/popup/components/diagnostic-view-toggle.scss
src/popup/components/diagnostic-view-toggle.tsx
src/tests/unit/tests/popup/components/__snapshots__/diagnostic-view-toggle.test.tsx.snap
src/tests/unit/tests/popup/components/diagnostic-view-toggle.test.tsx

Currently, the composition between the ad-hoc tools panel and the 5 different diagnostic view toggles is based on office ui fabric react grid. This make for a lot of boiler plate `<div>` elements, which contains `ms-Grid`-related classes. This are the classes you need to use if you want to use OF grid but that's not really necessary as we can use css grid and move more of the layout details to scss.
As part of this PR:
- convert `DiagnosticViewToggle` to use css-module
- convert `DiagnosticViewToggle` to use css grid
- update snapshots
I tried to make the styles to match the original layout as much as I could but there may be small differences.

refactor: use css grid to layout diagnostic view toggle

---

.dependabot/config.yml

Now that we updated office fabric to version 7, we want dependabot to create PR's to update office fabric.
We'll still may want to manually validate those PRs but it's nice to have dependabot checking for new versions and creating the resulting PRs.

feat(office-fabric): update dependabot config

---

src/popup/Styles/popup.scss
src/popup/components/header.scss
src/popup/components/header.tsx
src/popup/components/launch-panel-header.scss
src/popup/components/launch-panel-header.tsx
src/tests/common/element-snapshot-formatter.ts
src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
src/tests/unit/tests/popup/components/__snapshots__/header.test.tsx.snap
src/tests/unit/tests/popup/components/__snapshots__/launch-panel-header.test.tsx.snap
src/tests/unit/tests/popup/components/header.test.tsx

Currently, the popup header component is using office fabric grid, which is base on adding classes to `<div>`/`<span>` elements.
This PR changes that to use css grid, which simplify the component code as it moves the layout "logic" to the scss files.
There should be no differences in how the UI is presented (either to the AT -there is a H1 on the header- or visually)

refactor: popup header to use css grid

---

src/DetailsView/components/target-change-dialog.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/target-change-dialog.test.tsx.snap

After updating to office fabric 7, the **Assessment in progress** dialog got a layout-changing behavior when the user hover over the second target page link (this user story has more details 1663263).
This happen because we're mixing inline and block elements inside the dialog content. In order to fix this, I forced the `<Link>` component to render as an anchor tag (which is an inline type of element).

feat(office-fabric): udpate tooltip host content

---

pipeline/electron/distribute-publish-electron-linux.yaml
pipeline/electron/distribute-sign-publish-electron-mac.yaml
pipeline/electron/distribute-sign-publish-electron-windows.yaml
pipeline/electron/download-electron-mirror.yaml

This PR renames the environment variables in the electron build from ELECTRON_MIRROR and ELECTRON_CUSTOM_DIR to ELECTRON_MIRROR_VAR and ELECTRON_CUSTOM_DIR_VAR. This helps ensure that only certain tasks are affected by the mirror variables. Previously, if the variable was non-secret and thus available to the pipeline, unrelated tasks (such as yarn install) were affected by the variable names due to name collisions (e.g. electron-chromedriver installation also respects ELECTRON_MIRROR). The associated build vars will be renamed upon completion of this PR.

chore: refactor environment variables in electron build

---

src/DetailsView/components/switcher.scss

Looks like in Office Fabric 7 they change the way they "draw" the focus ring.
When the dropdown gets focus there is an `::after` element getting added to the dom. It's this element the one that gets the visible focus ring but we were adding the styles on a different place.
This PR moves the original styles to the proper selector so we can get the proper focus ring.
**Notes** there are no actual visible changes from this css update.

feat(office-fabric): restore activity switcher focus ring

---

src/electron/views/index.html

This PR adds an application insights URL to the CSP to enable telemetry in the electron product. The telemetry error was masked by / confused with https://github.com/microsoft/accessibility-insights-web/issues/1758. That issue tracked the web product - an OfficeFabric empty "JavaScript:url" was being flagged. In electron the error `renderer.bundle.js:14000 Refused to load the script 'https://az416426.vo.msecnd.net/scripts/a/ai.0.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.` appears in the built product.
Apologies this isn't in my fork - I had a branch on the main repo for build changes and forgot to move back in between.

fix: whitelist application insights telemetry endpoint in CSP

---

src/tests/common/element-snapshot-formatter.ts
src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
src/tests/unit/common/__snapshots__/element-snapshot-formatter.test.ts.snap
src/tests/unit/common/element-snapshot-formatter.test.ts
src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap

**NOTE** this is a second attempt to fix the element snapshot formatter logic. Original PR (#1981) has been abandoned.
While reviewing #1979, @dbjorge notice we are not properly handling a class attribute with more than one class value inside of it, like in this real case: `ms-Panel-headerText header-text--0nPhV headerText-000`.
The expected result from the example above is for the formater/normalizer to change `header-text--0nPhV` into `header-text--{{CSS_MODULE_HASH}}`. The position of the class name value should not matter; the same goes for the amount of class names the class attribute has.
Because we're using regex to do the replacement, I added unit tests for those functions (that way it was easier to found which of the functions was broken) and then updated the logic of the broken …

fix: element snapshot formatter does not handle more than one class name value

---

src/background/browser-message-broadcaster-factory.ts
src/tests/unit/tests/background/browser-message-broadcaster-factory.test.ts

Currently, we are flooding the `background.html` console with errors from sending messages to tabs we have not yet injected our content scripts.
This make it really hard to see anything else on the console (including telemetry being log to the console).
In order to avoid this, filtering out the known error message we get on this scenario.

fix: flooding error on background console

---

src/DetailsView/Styles/detailsview.scss

After updating to office fabric 7, the instance-visibility-button color became blue, so we changed it back to black.
Before fix:
After fix:

feat(office-fabric): change the checkbox color to black instead of the blue (default)

---

src/electron/platform/android/rule-information-provider.ts
src/tests/unit/tests/electron/platform/android/__snapshots__/rule-information-provider.test.ts.snap

According to #1994, the text on `how to fix` info for `TouchSizeWcag` needs a change in the minwidth size recommended from 48dp to 44dp.
Making that change.

fix: simple typo information on the TouchSizeWcag rule for minwidth and minheight

---

src/DetailsView/components/issues-table.tsx
src/DetailsView/components/switcher.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/switcher.test.tsx.snap
src/tests/unit/tests/DetailsView/components/issues-table.test.tsx

Several pieces of information to explain this change, bear with me:
The switcher AT announcement includes:
- tab-navigating to the dropdown.
- use arrow keys to change selection (with the dropdown to expand)
- expand the dropdown and use arrow keys to navigate the options.
Currently on **AI-Web prod 2.13.1** ATs announce the switcher **good enough** (there is just so much we can do to provide good aria values, after that, it's up to each AT to use that information and there are small and big differences between them.)
Currently on master, we have lost the proper announcement of the selection changes (by using arrow keys without expanding the dropdown). This is due to what we render for each option. We are using a wrapper `<span>` element so we can have icon + text. This wrapper has …

feat(office-fabric): fix switcher at announcement

---

Gruntfile.js
electron-builder.yml
src/electron/electron-builder/electron-builder.template.yaml
targets.config.js

This PR is part 1 of a series of PRs that will be updating the build machinery for our unified/electron/android releases to allow for multiple channels. This PR implements new behavior that will be used by unsigned release builds in future PRs:
```sh
yarn build:electron:all --unified-version=1.2.3 --app-insights-instrumentation-key=key`
```
This will produce a directory structure like the following:
```
drop/
electron/
electron/
<unchanged; leaving rename of this to unified-dev for separate PR>
unified-canary/
packed/
Accessibility Insights for Android - Canary setup.exe
<or dmg/AppImage, depending on the build agent platform>
latest.yml
unified-insider/
packed/
Accessibility Insights for Android - Insider setup.exe
latest.yml
unified-production/
packed/
Accessibility Insights for Android …
```

feat(unified-channels): Add grunt machinery for per-channel unified pkgs

---

package.json

Minor change, no functional impact; just cleans up formatting of package.json scripts

chore: fix alphabetization of run scripts in package.json

---

src/background/target-page-controller.ts
src/tests/unit/tests/background/target-page-controller.test.ts

Currently on prod 2.13.1 (and master) the extension is sending a telemetry event every time the user navigates any tab to a different url. The original purpose of the telemetry event was to gather data to understand how often do our users reuse a tab they where scanning but the implementation did not account for this last part, i.e. we're not checking if the tab url change was trigger on a tab the user was actually scanning.
This missing check makes the extension to spam this event and we have seen an huge spike on telemetry events which may make us hit a limit on the amount of events/data we can send to app insights per unit of time.
Given the 2 paragraphs bellow, we are removing this event temporarily until we: 1) decide we actually need it; and 2) design a way to do this properly (i.e. …

fix: tab url change spamming telemetry event

---

src/reports/package/reporter-factory.ts
src/reports/package/root/package.json
src/scanner/exposed-apis.ts
src/scanner/result-decorator.ts
src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap
src/tests/unit/tests/scanner/result-decorator.test.ts

This PR fixes a bug in html report generation using the npm report package. The WCAG links were missing.
(ruleToLinkConfiguration in resultDecorator object was undefined when using it in report package)
Added react-helmet as a dependency for report package, since this change made the output js file to take dependency on react-helmet.

fix: fixing missing wcag links in generated report via report package

---

package.json

Currently, running `yarn fastpass` is failing for `format:check` command with:
```
[error] Unable to read file: <some scss.d.ts file path here>
[error] ENOENT: no such file or directory, open <some scss.d.ts file path here>
```
This seems related to the recent addition of `scss:clean` command to the `fastpass` one after the `--parallel` flag, which cause the cleaning task to run in parallel with the checking task.
Making the clean step run before all the check tasks fix the issue.

chore: make scss:clean run before the checks

---

src/DetailsView/components/target-change-dialog.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/target-change-dialog.test.tsx.snap

Currently on master, the **Assessment in progress** dialog contains the following tabbable elements:
1. old target page link
1. new target page link
1. continue previous button
1. start new button
The second item in the list, new target page link, is not reachable using only tabs navigation.
This PR fix this by explicitly adding `tabIndex={0}` to the link properties.

fix: assessment in progress dialog, new target page link not tab navigable

---

prettier.config.js
src/common/components/cards/card-kebab-menu-button.tsx
src/common/components/cards/collapsible-component-cards.scss
src/common/components/cards/collapsible-component-cards.tsx
src/common/components/cards/failed-instances-section.tsx
src/common/components/cards/how-to-fix-android-card-row.tsx
src/common/components/cards/how-to-fix-card-row.tsx
src/common/components/cards/instance-details-footer.tsx
src/common/components/cards/instance-details-group.tsx
src/common/components/cards/instance-details.tsx
src/common/components/cards/result-section-content.tsx
src/common/components/cards/result-section-title.tsx
src/common/components/cards/result-section.tsx
src/common/components/cards/rule-resources.tsx
src/common/components/cards/rules-with-instances.tsx
src/common/components/cards/simple-card-row.tsx

This PR changes files under folder `src/common/components/cards` to comply with our new prettier config of 100 line width.

chore: update line width for folder src/common/components/cards

---

src/DetailsView/Styles/detailsview.scss
src/assessments/assessment-default-message-generator.scss
src/assessments/assessment-default-message-generator.tsx
src/tests/unit/tests/assessments/assessment-default-message-generator.test.tsx

- refactor assessment-default-message-generator to use css module
- remove now-dead css code from `detailsview.css`
**Notes** no changes on the UI or accessibility view.

refactor: assessment-default-message-generator uses css module

---

deploy/Gruntfile.js

While investigating longer-than-usual update times of our canary extension on the chrome web store, I noticed that our release do not log the version we're using when uploading to the store. 
This makes it harder to track which release run was the one that actually upload an updated version of the extension last, basically because our release does not fail if the store respond with an error, as in the case of uploading a new version while the extension is under "pending review"; in that case, we get this message:
```bash
Error on uploading (open) with message "Application error (6): hbcplehnakffdldhldncjlnbpfgogbem pending review so can't be edited". Raw response: {"kind":"chromewebstore#item","uploadState":"FAILURE","itemError":[{"error_code":"CLIENT_ERROR","error_detail":"Application …
```

chore: log version when publishing ai-web

---

src/background/telemetry/app-insights-telemetry-client.ts
src/tests/unit/tests/background/telemetry/app-insights-telemetry-client.test.ts

Application Insights logs [operation name](https://docs.microsoft.com/en-us/azure/azure-monitor/app/data-model-context#operation-name) which can include user paths. We don't need this information and would rather not have user paths in our telemetry, so this PR overwrites it to an empty string. This follows the example [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#telemetrycontext).

fix: remove operation.name from telemetry

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/left-nav/left-nav-icon.tsx
src/DetailsView/components/left-nav/overview-left-nav-link.tsx
src/DetailsView/components/left-nav/test-view-left-nav-link.tsx
src/DetailsView/components/requirement-link.tsx
src/injected/components/details-dialog.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-link.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/assessment-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/left-nav-icon.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/overview-left-nav-link.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/test-view-left-nav-link.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/visualization-based-left-nav.test.tsx.snap
src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap

This fixes the last subitem of #1801, where our left nav items were failing the WCAG 4.1.1 parsing test due to us nesting `<div>`-based content for our left nav items inside of span/button elements. The outer `<span>` is controlled by office fabric in this case, so this updates all the inner elements to use `<span>` rather than `<div>`. This was a noop in most cases since almost all of the nav item content rendered inline/with overridden display styles anyway.
The sole exception was the overview button's layout where it has the label on one line then the percentage complete on the next line, which relied on the implicit block display; the style update in `detailsview.scss` is there to prevent this impact.
There is no visual or AT change as part of this update. After this update, the only …

fix: avoid invalid div/span nesting in left nav items

---

src/DetailsView/details-view-initializer.ts
src/common/components/cards/collapsible-component-cards.tsx
src/common/components/cards/rules-with-instances.tsx
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/common/components/cards/collapsible-component-cards.test.tsx
src/types/set-focus-visibility.ts

There is something about how Office Fabric handle focus visibility state when the user interacts with the webpage. There seems to be some rules around how to change that state base on the type of element and the type of interaction (basically, keyboard vs mouse).
In our case, when the user uses the keyboard to collapse/expand the rule header group, office fabric simply set the focus visibility state to hidden.
On the other hand, Office Fabric expose a `setFocusVisibility` utility function we can call to force the state. 
**Note** The report is not affected by this bug (only AI-Web and AI-Android). The main reason is the report is mostly static html, so there is no office fabric javascript running on the report.

fix: rule group header loses focus indicator while using AT

---

src/common/styles/colors.scss

This PR darkens the text secondary color as requested in issue #2064 
example:

fix: darken text secondary color

---

targets.config.js

Updating the targets.config info on app ID and update URL to match how we've set up the publishing azure blob storage. Note, this intentionally sets canary up to use a new app ID and publish URL vs the "old" infrastructure's canary build

feat(unified-channels): update unified app IDs and publish URLs to match reality

---

copyright-header.config.json
electron-builder.yml
src/electron/resources/installer.nsh

This PR helps with #1974 by leveraging a custom nsis installer script. Dan found this approch / references: 
- https://www.electron.build/configuration/nsis#custom-nsis-script
- https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/nsis/multiUserUi.nsh#L39
We had switched to the one-click installer to remove the per-user / per-machine configuration screen from the installer. This also removed the confirmation dialog as a side-effect. This installer script allows us to switch back to the assisted installer while avoiding the per-user / per-machine configuration screen.
With this PR the installer looks like:
- license agreement
- installing progress
- confirmation screen with checkbox to run the app

fix: bring back confirmation dialog for unified electron client

---

src/DetailsView/components/failure-instance-panel-control.tsx
src/DetailsView/components/generic-panel.tsx
src/DetailsView/components/preview-features-panel.tsx
src/DetailsView/components/scoping-panel.tsx
src/DetailsView/components/settings-panel/settings-panel.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/failure-instance-panel-control.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/generic-panel.test.tsx.snap
src/tests/unit/tests/DetailsView/components/generic-panel.test.tsx
src/tests/unit/tests/DetailsView/components/preview-features-panel.test.tsx
src/tests/unit/tests/DetailsView/components/scoping-panel.test.tsx
src/tests/unit/tests/DetailsView/components/settings-panel/__snapshots__/settings-panel.test.tsx.snap

Doing some exploratory work to bring the settings panel to AI-Android, I found it would be useful to make the `<GenericPanel>` to accept all the properties from **Office Fabric** `<Panel>` and only have default values for some properties. This makes `<GenericPanel>` closer to **open/close** principle. 
**NOTE** there is a `prop` renaming so it could be easier to review this PR commit by commit.

refactor: generic panel more open/close-ish

---

src/electron/views/automated-checks/components/title-bar.scss

Currently on master, AI-Android does not seem to have a title on the window bar when the user navigate to the automated checks result view.
On this PR, we use `$always-white` for the window bar title text color only (the device port entry view is not affected).
**Out of scope**
I'm guessing we may need to adjust this when we work on bringing high contrast theme but since I don't have details on the color palette and so, I'm leaving that for the future feature crew to do
**No title text on master**
**Fixed**

fix: window bar title text color

---

.prettierignore

We recently added a new type of file to the repo (a `.nsh` file for customizing how unified's nsis installer works), which prettier doesn't understand how to format. This causes a spurious `[error]` line of stdout during `yarn format:check`.
This PR updates `.prettierignore` to ignore `.nsh` files to avoid the spurious error.

chore: avoid spurious prettier error with .nsh files

---

src/electron/electron-builder/electron-builder.template.yaml

This PR includes two changes to the unified electron client installer:
- restore a confirmation dialog (this was already done in #2060 but the changes weren't brought over to the **template** file)
- reduce the installer size by removing the 'packed' folder from the asar archive. Because we provide a custom output path, the intermediate files are created in a new folder called 'packed'. electron-builder has no way to understand whether 'packed' should be included or not in the asar archive. We exclude it via the file glob (see https://www.electron.build/configuration/contents#files) so that our asar archive only includes source code.

feat(release-channels): reduce installer size and add confirmation dialog

---

prettier.config.js
src/tests/end-to-end/common/browser-factory.ts
src/tests/end-to-end/common/browser.ts
src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/end-to-end/common/manifest-overide.ts
src/tests/end-to-end/common/page-controllers/details-view-page.ts
src/tests/end-to-end/common/page-controllers/page.ts
src/tests/end-to-end/common/page-controllers/target-page.ts
src/tests/end-to-end/common/prepare-test-result-file-path.ts
src/tests/end-to-end/common/scan-for-accessibility-issues.ts
src/tests/end-to-end/common/screenshot-on-error.ts
src/tests/end-to-end/common/with-tracing.ts
src/tests/end-to-end/jest.config.js
src/tests/end-to-end/test-resources/all-cross-origin-iframe.html
src/tests/end-to-end/test-resources/all.html
src/tests/end-to-end/test-resources/native-widgets/input-type-radio.html
src/tests/end-to-end/tests/common/settings-drop-down.test.ts
src/tests/end-to-end/tests/content/guidance-content.test.ts
src/tests/end-to-end/tests/details-view/cross-origin-iframe.test.ts
src/tests/end-to-end/tests/details-view/headings.test.ts
src/tests/end-to-end/tests/details-view/overview.test.ts
src/tests/end-to-end/tests/details-view/preview-features.test.ts
src/tests/end-to-end/tests/details-view/settings-panel.test.ts
src/tests/end-to-end/tests/popup/adhoc-panel.test.ts
src/tests/end-to-end/tests/popup/first-time-dialog.test.ts
src/tests/end-to-end/tests/popup/hamburger-menu.test.ts
src/tests/end-to-end/tests/popup/launchpad.test.ts
src/tests/end-to-end/tests/target-page/issue-dialog.test.ts
src/tests/end-to-end/tests/target-page/tabstop.test.ts
src/tests/end-to-end/tests/target-page/visualization-boxes.test.ts

This PR changes files under `src/tests/end-to-end` to comply with our new prettier config of 100 line width.

chore: line width for src/tests/end-to-end folder

---

src/electron/adapters/null-store-action-message-creator.ts
src/electron/views/renderer-initializer.ts
src/electron/views/root-container/components/root-container.tsx
src/electron/views/root-container/root-container-renderer.tsx
src/tests/unit/tests/electron/views/root-container/components/__snapshots__/root-container.test.tsx.snap
src/tests/unit/tests/electron/views/root-container/components/root-container.test.tsx
src/tests/unit/tests/electron/views/root-container/root-container-renderer.test.tsx

Currently, AI-Web follows a pattern of wrapped the highest level component using `withStoreSubscription`. This way, all the store listening and reacting to updates is encapsulated on one component, leaving the high-level component free to take care of other responsibilities.
On AI-Android, this is not the case, as `<RootContainer>` explicitly handles listening to the stores (through an stores hub instance, but still).
On this PR: refactoring `<RootContainer>` to  use `withStoreSubscription` and get rid of all the store-listening-and-updating logic. This change will make all **"containers"** to be more alike and also -I think- it will help to enabling high contrast theme on AI-Android.
**NOTES** no UI/UX changes from this PR

refactor: root-container to use withStoreSubscription

---

src/DetailsView/components/generic-toggle.scss
src/DetailsView/components/generic-toggle.tsx
src/DetailsView/components/settings-panel/settings-panel.scss
src/common/styles/common.scss
src/tests/unit/tests/DetailsView/components/__snapshots__/generic-toggle.test.tsx.snap
src/tests/unit/tests/DetailsView/components/generic-toggle.test.tsx

Convert `<GenericToggle>` to use css module.
This will help to have the correct stylings on both **AI-Web** and **AI-Android** (the latter will come up as part as an upcoming feature to bring the settings panel to AI-Android).
Additionally, fixed the description text color which was missed from a previous CSS-Module refactor on the `<SettingsPanel>` 
**Wrong color (on prod 2.14.1)**
**Fixed color**

refactor: generic toggle to use css module

---

pipeline/unified/channel/sign-release-package-linux.yaml

The previous PR #2113 replaced spaces w/ underscores in the Linux installer name. The signing task still references the old name. This PR updates the reference so it is correct.

fix: unblock linux signing by fixing AppImage name reference

---

src/electron/views/screenshot/screenshot-view.scss

fix: unified screenshot view not being fully visible at small heights

---

src/electron/electron-builder/electron-builder.template.yaml

This change is an attempt to work around https://github.com/electron-userland/electron-builder/issues/2199, where mac auto-update doesn't work if you produce only a .dmg file without a corresponding .zip file, even if the user installs using the .dmg file. Our signing pattern, artifact publishing patterns, and blob release patterns are all already dmg/zip agnostic, so I think no changes are required to cause the new zip file to be signed/released alongside the dmg.
- [n/a] (UI changes only) …

feat(unified-channels): fix mac auto-update by building a zip side-by-side with dmg

---

src/electron/views/root-container/components/root-container.scss

This PR updates fonts in the unified client to match the default fonts in the Chrome extension.

fix: add default font-family to unified root container

---

.prettierignore

We recently added a new type of image file to the repo (`.icns`, a mac-specific icon format). This PR updates our `.prettierignore` to avoid complaining about not knowing how to parse those during `yarn fastpass`

chore: make prettier ignore icns image format

---

prettier.config.js
src/tests/unit/tests/scanner/axe-configurator.test.ts
src/tests/unit/tests/scanner/axe-response-handler.test.ts
src/tests/unit/tests/scanner/axe-rule-overrides.test.ts
src/tests/unit/tests/scanner/axe-utils.test.ts
src/tests/unit/tests/scanner/custom-rules/autocomplete-rule.test.ts
src/tests/unit/tests/scanner/custom-rules/css-content-rule.test.ts
src/tests/unit/tests/scanner/custom-rules/css-positioning-rule.test.ts
src/tests/unit/tests/scanner/custom-rules/cues-rule.test.ts
src/tests/unit/tests/scanner/custom-rules/frame-title.test.ts
src/tests/unit/tests/scanner/custom-rules/heading-rule.test.ts
src/tests/unit/tests/scanner/custom-rules/image-rule.test.ts
src/tests/unit/tests/scanner/custom-rules/link-function.test.ts
src/tests/unit/tests/scanner/custom-rules/link-purpose.test.ts
src/tests/unit/tests/scanner/custom-rules/native-widgets-default.test.ts
src/tests/unit/tests/scanner/custom-rules/text-alternative.test.ts
src/tests/unit/tests/scanner/custom-rules/text-contrast.test.ts
src/tests/unit/tests/scanner/custom-rules/unique-landmark-check.test.ts
src/tests/unit/tests/scanner/custom-rules/unique-landmark.test.ts
src/tests/unit/tests/scanner/custom-rules/widget-function.test.ts
src/tests/unit/tests/scanner/helpers.ts
src/tests/unit/tests/scanner/launcher.test.ts
src/tests/unit/tests/scanner/message-decorator.test.ts
src/tests/unit/tests/scanner/processor.test.ts
src/tests/unit/tests/scanner/result-decorator.test.ts
src/tests/unit/tests/scanner/scan-parameter-generator.test.ts

Add `src/tests/unit/tests/scanner` folder to prettier override for the line width value.

chore: line width for src/tests/unit/tests/scanner folder

---

package.json

Obsoleted by changes to how unified release channels work

chore: remove obsolete pack:electron run script

---

src/common/components/hamburger-menu-button.tsx
src/common/fabric-icons.ts
src/tests/end-to-end/tests/popup/__snapshots__/hamburger-menu.test.ts.snap
src/tests/unit/tests/common/components/__snapshots__/hamburger-menu-button.test.tsx.snap

This PR adds an icon in the hamburger menu for keyboard shortcuts.

fix: add keyboard shortcut icon to hamburger menu

---

src/DetailsView/components/settings-panel/settings/settings-provider-impl.ts
src/DetailsView/components/settings-panel/settings/telemetry/telemetry-settings.tsx
src/content/settings/improve-accessibility-insights.tsx
src/electron/settings/unified-settings-provider.ts
src/tests/unit/tests/DetailsView/components/settings-panel/settings/telemetry/__snapshots__/telemetry-settings.test.tsx.snap
src/tests/unit/tests/DetailsView/components/settings-panel/settings/telemetry/telemetry-settings.test.tsx

Currently, the telemetry opt-in settings on android is being reuse from ai-web and thus the product name is wrong (it shows **Accessibility Insights for Web** even on AI-Android).
In this PR, allow for the telemetry settings component be created with a different product name so it can be properly reused on AI-web and AI-Android.

feat(android-settings): telemetry settings product name

---

deploy/package.json

This dep was a leftover from when we were using `deploy/package.json` for unified packaging/release steps; now that we aren't doing that anymore, it can be removed.

chore: remove unnecessary electron-builder dep from deploy/package.json

---

Gruntfile.js
package.json
pipeline/scripts/update-latest-yml.js
pipeline/scripts/zip-mac-folder.js
pipeline/unified/channel/sign-release-package-linux.yaml
pipeline/unified/channel/sign-release-package-mac.yaml
pipeline/unified/channel/sign-release-package-windows.yaml
pipeline/unified/channel/sign-release-package.yaml
pipeline/unified/sign-release-packages-canary.yaml
src/electron/electron-builder/electron-builder.template.yaml
yarn.lock

This PR enables updates for the macOS electron product. High level changes include:
- we add a zip file target because of https://github.com/electron-userland/electron-builder/issues/4230
- we create the zip file ourselves because of https://github.com/electron-userland/electron-builder/issues/3534#issuecomment-446257579
- we update latest.yml to reflect the new zip file in the artifact

fix: enable updates on mac for the unified client

---

src/tests/unit/tests/views/content/__snapshots__/content-view.test.tsx.snap
src/tests/unit/tests/views/content/__snapshots__/content.test.tsx.snap
src/tests/unit/tests/views/content/content-view.test.tsx
src/tests/unit/tests/views/content/content.test.tsx
src/views/content/content-view.tsx
src/views/content/content.tsx

Decoupled `ContentView` from `Content`.
The `Content` component both converts a content reference into it's content and also renders that content. Now it just converts the content reference and uses a new shared `ContentView` component.
Now the newly decoupled `ContentView` component can be shared with the docs repo for reuse.

feat(docs): Decoupled ContentView from Content.

---

src/electron/views/device-connect-view/components/device-connect-port-entry.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-port-entry.test.tsx.snap

Fixes WI # 1676700 by updating the placeholder text. 
Check NVDA/JAWS doesn't read the placeholder if the user input a port number and make the AT to "read the input control" again.

fix: device port placeholder text

---

src/DetailsView/details-view-initializer.ts
src/common/components/header.tsx
src/content/strings/text-content.ts
src/tests/unit/tests/common/components/__snapshots__/header.test.tsx.snap
src/tests/unit/tests/common/components/header.test.tsx
src/tests/unit/tests/content/index.test.tsx
src/tests/unit/tests/views/content/__snapshots__/content-view.test.tsx.snap
src/tests/unit/tests/views/content/__snapshots__/markup.test.tsx.snap
src/tests/unit/tests/views/content/content-include.test.tsx
src/tests/unit/tests/views/content/content-panel.test.tsx
src/tests/unit/tests/views/content/content-view.test.tsx
src/tests/unit/tests/views/content/markup.test.tsx
src/views/content/markup.tsx
src/views/insights/dependencies.ts

Another refactor to support sharing UI components into the docs repo.
There is another reference to a hard-coded constant in the Markup classes. It uses `productName` which is identical to `applicationTitle`. Changed to use the `applicationTitle` found in `deps` to abstract.

feat(docs): Changed productName to use deps.applicationTitle

---

src/common/components/header-icon.tsx
src/electron/views/automated-checks/components/title-bar.tsx
src/electron/views/device-connect-view/components/device-connect-view-container.tsx
src/tests/unit/tests/common/components/__snapshots__/header-icon.test.tsx.snap
src/tests/unit/tests/common/components/header-icon.test.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/title-bar.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/title-bar.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-view-container.test.tsx.snap

Update the icon we use on the window title bar to have high contrast styles.
**Device port - high contrast theme**
**Device port - default theme**
**Automated checks - high contrast theme**
**Automated checks - default theme**
**Notes**
- This only change the icon, no the title text (which explains why you can't see the title text in one of the screenshots)
- Currently on master, there is no way to set high contrast mode on, I have this on a local branch but I'm not adding those changes to this PR as the changes are a hacky way to have high contrast setting to show up.
- The red line on the screenshots are not part of the actual UI; they are there to highlight the impacted portion of the UI

feat(android-settings): window title bar icon high contrast theme

---

src/common/styles/colors.scss
src/reports/components/outcome.scss

Currently on master, out outcome chip is using `color: $neutral-90`, which is defined as `$neutral-90: var(--neutral-90)`. 
The issues with this is `--neutral-90` is not actually defined. 
The normal behavior of CSS custom properties (more info [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)) make the outcome chip to set the color by using one of  it's ancestors color value, which mask the fact that `--neutral-90` is not defined. 
Another issues with this is: for some reason, on AI-Android the outcome chip does not react to high contrast mode being turned on (probably because there is no ancestor that set the color value following high contrast mode).
On this PR:
- I used `$primary-text` value to set the outcome chip color. This matches what we …

feat(android-settings): fix outcome chip color to respect high contrast theme

---

src/electron/views/automated-checks/components/title-bar.scss

Fix the text color for the window title text under automated checks.
**loos like not text, it's actually the same color as the background color**
**fixed**

feat(android-settings): window title text color respects high contrast mode

---

src/electron/views/common/window-title/window-title.scss

Fix the window control buttons by using a high theme dependent color (`$neutral-0`), instead of a fixed one (`$always-white`).
**Window NOT maximized**
**Window maximized**

feat(android-settings): window control buttons respect high contrast mode

---

src/popup/Styles/popup.scss
src/popup/components/ad-hoc-tools-panel.scss
src/popup/components/ad-hoc-tools-panel.tsx
src/tests/unit/tests/popup/components/__snapshots__/ad-hoc-tools-panel.test.tsx.snap
src/tests/unit/tests/popup/components/ad-hoc-tools-panel.test.tsx

Currently, the ad hoc tools panel is using `ms-Grid` styles to layout the toggles. This put a lot of knowledge about layout on the component. Also, using `ms-Grid` is not that great, specially compared to using CSS Grid.
In this PR: refactor the component to use CSS Grid instead.
**NOTE** there are no visible UI changes.

refactor: ad hoc tools panel to use CSS Grid

---

src/common/components/cards/result-section-title.scss

Make the text color of **Failed instances** to respect high contrast mode on the cards ui.
**Incorrect high contrast color**
**Fixed high contrast color**

feat(android-settings): Failed instance title text respect high contrast

---

src/common/styles/colors.scss
src/electron/views/automated-checks/components/command-bar.scss

Update start over buttons styles on default and high contrast themes.
**default theme - default state**
**default theme - hover state**
**high contrast theme - default state**
**high contrast theme - hover state**

feat(android-settings) : update start over button styles

---

src/common/components/cards/collapsible-component-cards.scss

Currently, hovering over a rule group on AI-Android makes the description to change text color to something closer to black, which makes it unreadable. This is due to a `color: unset;` value we are setting specifically for the hover state plus some missing color value on the parent/ancestor of this element (color is an inheritable property, `color: unset;` makes css to look up to the parent of an element and up the hierarchy until it finds a color or uses a default value).
In this PR: using an explicit color for the hover state which fixes AI-Android and leaves AI-Web and the report with the same, original behavior.
**Current master**
ImageViewName rule hovered over, where the description is not visible due to the text using black.

fix rule description hover state text color on high contrast

---

src/DetailsView/details-view-initializer.ts
src/common/components/theme.tsx
src/electron/settings/unified-settings-provider.ts
src/electron/views/renderer-initializer.ts
src/electron/views/root-container/root-container-renderer.tsx
src/popup/popup-initializer.ts
src/tests/unit/tests/common/components/__snapshots__/theme.test.tsx.snap
src/tests/unit/tests/common/components/theme.test.tsx
src/tests/unit/tests/electron/views/root-container/root-container-renderer.test.tsx
src/views/insights/dependencies.ts

* Adds `<Theme>` to the unified `RootContainerRenderer` to implement it
* Updates `<Theme>` to use the new `BodyClassModifier` so it can live side-by-side with `PlatformBodyClassModifier`
* Updates the other initializers that transitively use `<Theme>` to pass down its new `DocumentManipulator` dep
No UI changes in web (verified that high contrast toggle still works in popup/details/content views).
Out of scope:
* high contrast styling
* Adding setting to the settings panel (waiting til styles are more complete)

feat(android-settings): add theme support to unified root container

---

src/electron/views/device-connect-view/device-connect-view.scss

Currently, we don't have a body color value on AI-Android. This makes the color value to be black (the default value). This default value does not change when we enable high contrast mode which make the text practically invisible against the black background.
This is easily fixed by adding a explicit color value for the body. Using `$primary-text` for this.
**Bug: text is invisible on device port entry view when high contrast mode is enabled**
**Fixed: device port entry view shows white text**

feat(android-settings): add body color value

---

src/electron/views/automated-checks/components/command-bar.scss

There is an "extra" hover state style that make the start over button to respond oddly to the user hovering over the text and not the icon.
Removing the extra style fix the issue.

feat(android-settings): remove hover state style that's not needed

---

src/electron/views/device-connect-view/device-connect-view.scss

It looks like using `body` as a selector is not enough to beat office fabric `ms-Fabric` selector, which make the body color to not respect high contrast theme.
Using `body.ms-Fabric` is more specific than what we currently have and it fix the text color issue on AI-Android.

feat(android-settings): using a more specific selector to set body color

---

src/common/components/theme.tsx
src/tests/unit/tests/common/components/theme.test.tsx

Today, `<Theme>` only invokes office fabric's `loadTheme` in `componentDidUpdate`; this is fine in web because it always updates soon after loading due to the store proxy not receiving info until after first mount, but in unified, it has the true store data during mount and so won't necessarily receive an initial update notification on first run. This updates it to perform an initial `loadTheme` during mount, in addition to on updates.

feat(android-settings): update Theme to call loadTheme on mount

---

src/electron/views/device-connect-view/components/device-connect-connected-device.scss
src/electron/views/device-connect-view/components/device-connect-connected-device.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-connected-device.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/device-connect-connected-device.test.tsx

Update the spinner text color to work on both, the default and the high contrast theme.
I use the opportunity to update how we import styles definition files (`*.scss.d.ts` files) to match our current choice to do so.
**default theme**
**high contrast theme**

feat(android-settings): fix connecting to device spinner text color

---

src/electron/adapters/electron-storage-adapter.ts
src/tests/unit/tests/electron/adapters/electron-storage-adapter.test.ts

Currently, our `ElectronStorageAdapter`, which implements the `StorageAdapter` interface and serves as a "double" of our `ChromeAdapter` (around accessing local storage) wraps any object we want to store around a single key: `installationData`. 
We are only using the `ElectronStorageAdapter` to store `installationData` so the issue mention above cause the storage to write something like this:
```js
{
installationData: {
installationData: {
month: 1,
year: 2020,
installationId: <guid>
}
}
}
```
Notice the duplicated `installationData` key on the object.
This causes our `InstallDataGenerator` to always generate a new `installationId` (basically, because is checking for an existing `installationId` at the "wrong" level of the object.
This PR fixes this issue by properly and directly using …

fix: true-up electron-storage-adapter

---

src/electron/views/device-connect-view/components/electron-external-link.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/electron-external-link.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/electron-external-link.test.tsx

Office Fabric `<Link>` component uses a native `<button>` element when there is no `href` prop pass to it.
We are using the `<Link>` component but we can't pass the `href` because we want AI-Android to use the native, OS default browser to open the link. This works by us passing a `onClick` function that wraps the `shell` object from `electron` to call into the OS to open the link.
Due to the previously exposed, it's kind of hard to use Office Fabric component **and** get a `<a>` element, so instead. Thus, the approach taken on this PR is to force the `<Link>` to use `role='link'`.

fix: how do I connect my device? link role

---

src/common/styles/colors.scss
src/electron/views/device-connect-view/components/device-connect-header.scss

Add new color for link on AI-Android. Use it on the _How do I connect to my device?_ link.
**default theme**
**high contrast theme**

feat(android-settings): How do I connect high contrast color

---

src/electron/views/automated-checks/components/command-bar.scss

AI-Android command bar menu item were missing the proper color for the active and active+hover state.
This PR adds those missing selector using the existing color.

feat(android-settings): fix command bar menu item active state color

---

src/background/stores/global/user-configuration-store.ts
src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts

This is a follow up of #2199. 
The previous approach allows us to change the behavior of `getState` when building instances of any store. The **any** store part is the critical part here. We do want to make our states immutable and we have #2228 to track that work but following the original approach cause a series of issues on AI-Web so instead of opening the door and facilitate this change on any and all the stores, we'd like to take a safer approach and update only the offending store (on AI-Android, that would be `UserConfigurationStore` where the `enableHighContrast` flag is store).

feat(android-settings): cloneDeep on UserConfigurationStore

---

src/common/uid-generator.ts

After we updated uuid from v3.x to v7.x we started to get a warning message about how we are importing from the library.
```console
(node:26968) DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid/blob/master/README.md#upgrading-from-v3x-of-this-module for more information.
```
On this PR:
- update how we import so we don't get the warning.

refactor: clean up import from uuid

---

src/common/styles/common.scss
src/common/styles/default-theme-palette.ts
src/common/styles/high-contrast-theme-palette.ts

Previously, in high contrast mode, we were using our default "primary theme color" for primary button colors, which in high contrast mode is `#0078d4` and looks like this (with a 4:1 contrast ratio against the near-black text/background):
With this change, we now use our high contrast palette's "selected items/checkboxes/toggles" color (`#38A9FF`) instead, which has a 7.141:1 ratio against the background/text:
This PR removes a style in web's `common.scss` that already overrode the default office fabric value, but did so in a way that did not meet contrast requirements, such that web's dialogs use the same high-contrast palette; this gets an early start on one of the requirements in feature 1559424
- [n/a] Verified code …

fix: use 7:1 contrast ratio for primary button background in high-contrast mode

---

src/electron/views/screenshot/screenshot-view.tsx
src/electron/views/screenshot/screenshot.scss
src/electron/views/screenshot/screenshot.tsx
src/tests/unit/tests/electron/views/screenshot/__snapshots__/screenshot-view.test.tsx.snap
src/tests/unit/tests/electron/views/screenshot/__snapshots__/screenshot.test.tsx.snap

This PR moves the artificial `tabIndex=0` we use to enable keyboard-only scrolling of the screenshot view panel in unified from the header to the image itself, per discussion/trusted tester feedback in 1676714. Since the default focus ring on the image itself is invisible, it also gives a custom focus style that is based on the focus style of selected cards in the cards view (per discussion with Fer).

fix: unified: move focusability from screenshot view header to image

---

src/electron/views/automated-checks/components/command-bar.scss
src/electron/views/automated-checks/components/command-bar.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/command-bar.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/command-bar.test.tsx

Currently, we are using `<CommandBar>` from Office Fabric on the Automated Checks View to show the start over button and the settings gear. The component has some accessibility issues capture on [OF#11832](https://github.com/OfficeDev/office-ui-fabric-react/issues/11832). 
I fiddle around a little bit with the `<CommandBar>` and the `<FocusZone>` components to see if we could get a walk-around and still use the Office Fabric component but I didn't find anything promising and already hit my time box.
So instead, we are falling back to the approach we have on AI-Web with the export report and start over buttons: basically, the buttons live inside a simple `<div>` and the user can tab between them normally. There is no special announcement from the AT (like amount of items in the "command …

feat(android-settings): update command bar to fix a11y issues

---

src/electron/views/device-connect-view/components/device-connect-port-entry.scss
src/electron/views/device-connect-view/components/device-connect-port-entry.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-port-entry.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/device-connect-port-entry.test.tsx

This fixes an accessibility issue we had where users with screen readers would not be made aware of the port numbers limit. This adds a description to the text field highlighting the limit.

fix: add a description to mention port number requirements

---

src/common/styles/high-contrast-theme-palette.ts
src/electron/views/device-connect-view/components/device-connect-body.tsx
src/electron/views/device-connect-view/components/device-connect-header.scss
src/electron/views/device-connect-view/components/device-connect-header.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-body.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/device-connect-header.test.tsx

Currently, to render the **How do I connect to my device?** link, we directly use `<ElectronLink>` component, while for the links on the settings panel, we pass a dependency called `LinkComponent`. Now, `<ElectronLink>` can (and is) be passed as the instance for the dep `LinkComponent` but we should have only one way to do this so, defaulting to use the dep instead of have a hard dependency on `<ElectronLink>` (this helps with open/close principle).
Additionally, we have override the css styles for the link and now the **How do I connect to my device?** link looks different from the ones on the **Settings Panel**. 
In this PR, we make both links look the same (using the **Settings Panel** as the style we want to use). I'm following the **Basic buttons** style guideline from figma, …

feat(android-settings): update how do I connect link colors

---

src/common/styles/high-contrast-theme-palette.ts

We are updating the primary button color for the active state so it does pass color contrast. 
This affect primary buttons on AI-Android and AI-Web. The difference is not easy to "see" but running the self validation find the color does pass color contrast.
**enabled, primary button on active state**

feat(android-settings): update primary button active state color

---

src/background/actions/action-creator.ts
src/background/tab-context-factory.ts
src/tests/unit/tests/background/actions/action-creator.test.ts

Just found a `describe.only` on our `action-creator.test.ts`.
On this PR:
- remove stray `.only`
- remove default value for `logger` param and update only call to the constructor

test: re-enable some action creator tests

---

src/electron/views/automated-checks/components/title-bar.scss
src/electron/views/automated-checks/components/title-bar.tsx
src/electron/views/common/window-title/window-title.tsx
src/electron/views/device-connect-view/components/device-connect-body.scss
src/electron/views/device-connect-view/components/device-connect-connected-device.tsx
src/electron/views/device-connect-view/components/device-connect-header.scss
src/electron/views/device-connect-view/components/device-connect-header.tsx
src/electron/views/device-connect-view/components/device-connect-port-entry.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/title-bar.test.tsx.snap
src/tests/unit/tests/electron/views/common/window-title/__snapshots__/window-title.test.tsx.snap
src/tests/unit/tests/electron/views/common/window-title/window-title.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-connected-device.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-header.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-port-entry.test.tsx.snap

Per @ferBonnin , we think the window title is not supposed to be a heading (it should be in a `<header>`/banner landmark, as it already is, but not be an actual `<h1>`; that should be the element in the page.
This required:
* updating the title bar component to pass through a className that was previously inferring information owned by the window title component
* updating the device connect view to bump its in-page heading levels (h2 -> h1 and h3->h2) to ensure page still has an h1
Out of scope:
* Making the port entry label a label instead of a heading at all (will be covered in later a11y fix)
Should be no visual changes as part of this PR.

fix: unified: make window title a non-heading

---

src/debug-tools/components/stores-tree.tsx
src/tests/unit/tests/debug-tools/components/__snapshots__/stores-tree.test.tsx.snap
src/tests/unit/tests/debug-tools/components/stores-tree.test.tsx

As part of adding the debug page, we missing adding some tests on the new code.
This PR add the missing tests for the `<StoresTree>` component, covering 100%.

test: add missing tests for StoresTree

---

src/electron/views/automated-checks/components/command-bar.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/command-bar.test.tsx.snap

This PR updates the newly redone unified command bar to be a "region" landmark named "command bar", per the figma (`<section>` elements are the semantic HTML equivalent for the `region` role). We think eventually a "menubar" role would be more appropriate, using this as a stopgap while we wait for https://github.com/OfficeDev/office-ui-fabric-react/issues/11832
No visible UI changes. Verified reading behavior in JAWS (it makes the region navigable with "r").

feat(android-settings): make unified command bar a region landmark

---

src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/automated-checks/components/title-bar.tsx
src/electron/views/common/window-title/window-title.tsx
src/electron/views/device-connect-view/components/device-connect-view-container.tsx
src/tests/electron/tests/automated-checks-view.test.ts
src/tests/electron/tests/device-connection-dialog.test.ts
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/title-bar.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/title-bar.test.tsx
src/tests/unit/tests/electron/views/common/window-title/__snapshots__/window-title.test.tsx.snap
src/tests/unit/tests/electron/views/common/window-title/window-title.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-view-container.test.tsx.snap

This PR updates unified page `<title>`s (which are used by Electron to inform the OS about window titles, eg, for the purposes of alt-tab/win-tab/taskbar UI) to adhere to [WCAG SC 2.4.2](https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html) by using titles that communicate individual pages' purpose (in our case, using titles that include the terms "Connect to your Android device" or "Automated checks" per-view).
Windows win-tab UI with this change:

fix: unified: page-specific window titles

---

src/electron/views/screenshot/screenshot-view.scss

I don't fully understand why this happening but it seems like when the visualizations are not present, the height of the screenshot view extends for as long as the screenshot itself. Setting a max-value on that to be 100% leads to the appropriate behavior.
¯\\\_(ツ)\_/¯
Here's a gif of the fixed behavior:

fix: disabling visual helper toggle causes scrollbar issue

---

src/common/styles/high-contrast-theme-palette.ts

Previously, enabled toggles in high-contrast mode used our default `themePrimary` color from our office fabric palette, which is a 4.5:1 contrast blue in high contrast mode:
This overrides the semantic color used by enabled toggles (and shared by other types of enabled form components [checkboxes, option groups, sliders] that we would also want affected similarly) to be the 7:1 blue specified by our high contrast palette mock instead:

fix: use 7:1 contrast blue for neutral color of enabled toggles in high contrast mode

---

src/electron/views/device-connect-view/components/device-connect-connected-device.scss
src/electron/views/device-connect-view/components/device-connect-connected-device.tsx
src/electron/views/device-connect-view/components/device-connect-port-entry.scss
src/electron/views/device-connect-view/components/device-connect-port-entry.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-connected-device.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-port-entry.test.tsx.snap
src/tests/unit/tests/electron/views/device-connect-view/components/device-connect-port-entry.test.tsx

Changing the current `<h2>` to only be `<div>` as per bug 1676767.
Additionally, update the input to use `aria-labelledby` associated with the `<div>` containing the text `"Android device port number"`. This way, both the visual label and what the AT announce as the label match and we don't have duplication.
AT announcement when tabbing to the input field
| AT | Announcement |
| :-- | :---------------- |
| NVDA | Android device port number edit the port number must be a number between 0 and 65535 EX: 12345 blank |
| JAWS | Android device port number edit EX: 12345 the port number must be a number between 0 and 65535 type and text |
| Narrator | Android device port number edit space |
**Note** there are not visual UI changes

fix: device port label and headers

---

src/DetailsView/components/assessment-instance-table.tsx
src/DetailsView/components/start-over-component-factory.tsx
src/common/components/controls/insights-command-button.scss
src/common/components/controls/insights-command-button.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-instance-table.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-component-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/assessment-instance-table.test.tsx
src/tests/unit/tests/common/components/controls/__snapshots__/insights-command-button.test.tsx.snap
src/tests/unit/tests/common/components/controls/insights-command-button.test.tsx

This PR introduces a new `InsightsCommandButton` control to match the "Command button" in our [style figma](https://www.figma.com/file/Wj4Ggf6GGQBQkiDIaHfXRX2B/Accessibility-Insights%3A-Styles?node-id=1%3A27). I gave it a new `controls` folder because I expect it to be reasonable to use a similar structure for the other controls present in that Figma that we want to enforce specific insights styles for.
#757 only calls out the "Pass unmarked instances" button as failing contrast requirements in the disabled state; I audited all the other places we use `<ActionButton>`s for other cases with disable states and found that the same issue also applies to the FastPass start over button while a scan is in progress, so I fixed it while I was here.
For the initial PR, I kept its usage targeted to …

feat(compliance-contrast): use 3:1 contrast text for disabled command buttons in high contrast

---

src/DetailsView/components/assessment-instance-table.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-instance-table.test.tsx.snap
src/tests/unit/tests/DetailsView/components/assessment-instance-table.test.tsx

Followup to comment from #2273 suggesting redoing AssessmentInstanceTable tests in terms of `enzyme`. I ended up basically doing a complete rewrite.

chore: modernize AssessmentInstanceTable unit tests

---

src/DetailsView/components/switcher.scss
src/DetailsView/components/switcher.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/switcher.test.tsx.snap

Update the switcher styles so:
- we solve the color contrast issues between the dropdown background color and the surrounding background color by making both background colors the same and adding a permanent border with enough contrast against the background color
- update the assessment icon to match the mock
- update the focus ring indicator to match the new focus ring design from the mocks
**Note** the screenshots were taken at 110% zoom
**default state**
**focus state**
**expanded state**
**default state**
**focus state**
**expanded state**

feat(compliance-contrast): update switcher

---

prettier.config.js
src/tests/unit/tests/debug-tools/action-creators/debug-tools-action-creator.test.ts
src/tests/unit/tests/debug-tools/components/stores-tree.test.tsx

Add `src/tests/unit/tests/debug-tools` folder to prettier override for the line width value.

chore: line width for src/tests/unit/tests/debug-tools folder

---

prettier.config.js
src/tests/unit/tests/views/content/content-link.test.tsx
src/tests/unit/tests/views/content/content-page.test.tsx
src/tests/unit/tests/views/content/content-panel.test.tsx
src/tests/unit/tests/views/content/content.test.tsx
src/tests/unit/tests/views/content/markup.test.tsx
src/tests/unit/tests/views/content/markup/code-example.test.tsx
src/tests/unit/tests/views/insights/dependencies.test.ts
src/tests/unit/tests/views/insights/renderer.test.tsx

Add ` src/tests/unit/tests/views` folder to prettier override for the line width value.

chore: line width for src/tests/unit/tests/views folder

---

src/electron/views/renderer-initializer.ts
src/tests/electron/common/view-controllers/app-controller.ts

Same as we have on AI-Web, adding an instance of the `UserConfigurationController` under `window.insightsUserConfiguration` so we can set up high contrast mode programatically on our e2e tests.

feat(android-settings): add user configuration controller to window on AI-Android

---

prettier.config.js
src/tests/unit/tests/reports/assessment-report-html-generator.test.tsx
src/tests/unit/tests/reports/components/assessment-report-assessment-list.test.tsx
src/tests/unit/tests/reports/components/assessment-report-body.test.tsx
src/tests/unit/tests/reports/components/assessment-report-footer.test.tsx
src/tests/unit/tests/reports/components/assessment-report-step-header.test.tsx
src/tests/unit/tests/reports/components/assessment-report-summary.test.tsx
src/tests/unit/tests/reports/components/assessment-report.test.tsx
src/tests/unit/tests/reports/components/assessment-scan-details.test.tsx
src/tests/unit/tests/reports/components/assessment-summary-details.test.tsx
src/tests/unit/tests/reports/components/inline-image.test.tsx
src/tests/unit/tests/reports/components/outcome-icon.test.tsx
src/tests/unit/tests/reports/components/outcome-summary-bar.test.tsx
src/tests/unit/tests/reports/components/report-sections/collapsible-result-section.test.tsx
src/tests/unit/tests/reports/components/report-sections/collapsible-script-provider.test.ts
src/tests/unit/tests/reports/components/report-sections/details-section.test.tsx
src/tests/unit/tests/reports/components/report-sections/full-rule-header.test.tsx
src/tests/unit/tests/reports/components/report-sections/minimal-rule-header.test.tsx
src/tests/unit/tests/reports/components/report-sections/no-failed-instances-congrats.test.tsx
src/tests/unit/tests/reports/components/report-sections/not-applicable-checks-sections.test.tsx
src/tests/unit/tests/reports/components/report-sections/passed-checks-sections.test.tsx
src/tests/unit/tests/reports/components/report-sections/report-body.test.tsx
src/tests/unit/tests/reports/components/report-sections/results-container.test.tsx
src/tests/unit/tests/reports/components/report-sections/rules-only.test.tsx
src/tests/unit/tests/reports/components/report-sections/summary-section.test.tsx
src/tests/unit/tests/reports/components/requirement-outcome-type.test.ts
src/tests/unit/tests/reports/get-assessment-summary-model.test.ts
src/tests/unit/tests/reports/report-generator.test.ts
src/tests/unit/tests/reports/report-html-generator.test.tsx

Add ` src/tests/unit/tests/report` folder to prettier override for the line width value.

chore: line width for src/tests/unit/tests/report folder

---

src/electron/views/renderer-initializer.ts
src/tests/electron/common/view-controllers/app-controller.ts
src/tests/electron/setup/timeouts.ts
src/tests/electron/tests/automated-checks-view.test.ts
src/tests/electron/tests/device-connection-dialog.test.ts

- Update `AppController` to allow the tests to set and wait for high contrast mode
- Update both, device connect view and automated checks view a11y test to include both, default theme and high contrast theme, scans.

feat(android-settings): update e2e a11y test to include high contrast mode

---

src/assessments/text-legibility/test-steps/high-contrast-mode.tsx

Text updates to test 17 requirement 1 per discussion in #2266 ([comment 1](https://github.com/microsoft/accessibility-insights-web/issues/2266#issuecomment-593714619), [comment 2](https://github.com/microsoft/accessibility-insights-web/issues/2266#issuecomment-593718212))
Before on left, after on right:

fix: outdated "how to test" text for High contrast mode requirement

---

src/background/actions/action-payloads.ts
src/background/actions/user-configuration-actions.ts
src/background/global-action-creators/registrar/register-user-configuration-message-callbacks.ts
src/background/global-action-creators/user-configuration-action-creator.ts
src/background/stores/global/user-configuration-store.ts
src/common/message-creators/user-config-message-creator.ts
src/common/messages.ts
src/common/types/store-data/user-configuration-store.ts
src/electron/main/native-high-contrast-mode-listener.ts
src/tests/unit/tests/DetailsView/components/details-view-overlay/settings-panel/settings/issue-filing/issue-filing-settings.test.tsx
src/tests/unit/tests/DetailsView/details-view-container.test.tsx
src/tests/unit/tests/background/get-persisted-data.test.ts
src/tests/unit/tests/background/global-action-creators/user-configuration-action-creator.test.ts
src/tests/unit/tests/background/keyboard-shortcut-handler.test.ts
src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts
src/tests/unit/tests/common/components/cards/card-kebab-menu-button.test.tsx
src/tests/unit/tests/common/message-creators/user-config-message-creator.test.ts
src/tests/unit/tests/electron/main/native-high-contrast-mode-listener.test.ts
src/tests/unit/tests/popup/components/popup-view.test.tsx

Before this PR, the interaction between the user and system high contrast states was that the native state overwrote the app setting on app startup and whenever the system state was toggled, and the user setting in our settings panel was strictly transient, forgotten with each new app launch.
With this PR, we now remember the last high contrast mode setting the user selected in the app across system high contrast mode switches. We still switch to high contrast mode if the system switches to that mode or if the app is started with the system in high contrast mode, but now if you switch the system out of high contrast mode (or start the app with the system not in high contrast mode), we will remember whatever setting you previously had set in the Settings panel and return to it.
In …

feat(android-settings): make app HC setting persist across system HC toggling

---

src/scanner/rule-to-links-mappings.ts

The 'label-content-name-mismatch' rule is experimental for axe-core, as such setting it to best practice for us.

fix: set label-content-name-mismatch to best practice as it's experimental

---

.dependabot/config.yml
package.json
src/packages/accessibility-insights-ui/root/package.json
src/reports/package/root/package.json
yarn.lock

This reverts back to fabric version 7.98.0 to avoid a regression in 7.98.1 (https://github.com/OfficeDev/office-ui-fabric-react/issues/12195)
Before revert (see the close icon on the panel):
After revert:

fix: revert office fabric to 7.98.0 to fix content panel close button position

---

prettier.config.js
src/tests/unit/tests/issue-filing/common/create-file-issue-handler.test.ts
src/tests/unit/tests/issue-filing/common/http-query-builder.test.ts
src/tests/unit/tests/issue-filing/common/issue-details-builder.test.ts
src/tests/unit/tests/issue-filing/common/issue-filing-controller-impl.test.ts
src/tests/unit/tests/issue-filing/common/markup/plain-text-formatter.test.ts
src/tests/unit/tests/issue-filing/common/markup/truncate-snippet.test.ts
src/tests/unit/tests/issue-filing/components/issue-filing-option-choice-group.test.tsx
src/tests/unit/tests/issue-filing/components/issue-filing-settings-container.test.tsx
src/tests/unit/tests/issue-filing/issue-filing-service-provider.test.ts
src/tests/unit/tests/issue-filing/services/azure-boards/azure-boards-issue-filing-service.test.tsx
src/tests/unit/tests/issue-filing/services/azure-boards/azure-boards-settings-form.test.tsx
src/tests/unit/tests/issue-filing/services/azure-boards/create-azure-boards-issue-filing-url.test.ts
src/tests/unit/tests/issue-filing/services/github/create-github-issue-filing-url.test.ts
src/tests/unit/tests/issue-filing/services/github/github-issue-filing-service.test.tsx
src/tests/unit/tests/issue-filing/unified-result-to-issue-filing-data.test.ts

Add ` src/tests/unit/tests/issue-filing` folder to prettier override for the line width value.

chore: line width for src/tests/unit/tests/issue-filing folder

---

src/electron/views/automated-checks/components/command-bar.tsx
src/tests/electron/common/element-identifiers/automated-checks-view-selectors.ts
src/tests/electron/common/scan-for-accessibility-issues.ts
src/tests/electron/common/view-controllers/automated-checks-view-controller.ts
src/tests/electron/common/view-controllers/view-controller.ts
src/tests/electron/tests/unified-settings-panel.test.ts
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/command-bar.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/command-bar.test.tsx

Adding e2e test for the settings panel on AI-Android, including accessibility issues scan in default and high contrast theme.
The general strategy was to bring the same scenarios on the settings panel e2e test from AI-Web but translated to AI-Android.
**Note**
We have the idea to update the app controller to use the user config controller instead of hitting buttons in the UI for dismissing the first time telemetry dialog. This will lead to some changes to other e2e as well as adding a couple more e2e test. I left that for follow up PR to keep this one smaller.

feat(android-settings): add e2e tests for the settings panel

---

src/tests/common/get-automation-id-selector.ts
src/tests/electron/common/element-identifiers/automated-checks-view-selectors.ts
src/tests/electron/common/element-identifiers/device-connection-dialog-selectors.ts
src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
src/tests/unit/tests/DetailsView/components/assessment-instance-table.test.tsx
src/tests/unit/tests/electron/views/automated-checks/components/command-bar.test.tsx
src/tests/unit/tests/electron/views/device-connect-view/components/device-connect-port-entry.test.tsx

Currently, we have some tests (unit and e2e) that have selectors using `[data-automation-id="..."]` as a hardcoded value which may induce errors on either side, the test and the prod code.
We already have a function to generate this selector base on the id value but it's local to the file we are declaring it.
In this PR:
- Extract `getAutomationIdSelector` function to it's own file
- Update all e2e test that use this type of selector
- Update a few unit test that also use this pattern.

refactor: using getAutomationIdSelector from unique source

---

src/reports/components/instance-details.scss

Fix work break on Automated Check View Cards UI on AI-Android.

fix: Electron app > How to fix - Text should not break in the middle of a word

---

src/DetailsView/components/details-view-overlay/settings-panel/settings-panel.scss
src/DetailsView/components/generic-panel.scss
src/DetailsView/components/generic-panel.tsx
src/DetailsView/components/generic-toggle.scss
src/DetailsView/components/no-displayable-preview-features-message.scss
src/common/styles/fonts.scss
src/electron/views/automated-checks/components/header-section.scss
src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/generic-panel.test.tsx.snap

We noticed in #2256 that at some point we'd taken office fabric updates that changed how our "generic panels" render (this include our settings panel, preview features panel, "add failure instance details" panel, and the hidden-feature-flagged scoping panel).
This PR covers updates per discussion with @ichelsea and @ferBonnin bringing our panel styling up to date with standard office fabric layouts and our current typography codex.
Setting as "2 reviewers required" because I want one engineering signoff and one signoff from @ichelsea
(all screenshots below use the same window size for both; the panels are intentionally thinner in the after versions)
Before left / after right: Settings panel 100% zoom
Before left / after right: Settings panel 200% zoom
Before left / after right: Preview …

fix: fit-and-finish for settings/preview/failure instance panels

---

src/DetailsView/components/iframe-warning.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/iframe-warning.test.tsx.snap

Fixes the link to point to the right page/anchor link

fix: iframe warning "learn more" not pointing to correct FAQ entry

---

src/common/components/telemetry-permission-dialog.tsx
src/tests/end-to-end/tests/popup/__snapshots__/first-time-dialog.test.ts.snap
src/tests/unit/tests/common/components/__snapshots__/telemetry-permission-dialog.test.tsx.snap

This PR removes a title ID attribute for the telemetry permission dialog. I was unable to find any usages of this id, and its inclusion leads to an invalid aria label, as described in #2316. 
This is the first of a few PRs in this area; I'd like to run accessibility tests on this dialog in our e2e tests, and that requires a little refactoring.

fix: remove unnecessary telemetry dialog id attribute

---

src/DetailsView/details-view-container.tsx
src/DetailsView/details-view-initializer.ts
src/DetailsView/details-view-renderer.tsx
src/tests/unit/tests/DetailsView/__snapshots__/details-view-container.test.tsx.snap
src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts
src/tests/unit/tests/DetailsView/details-view-container.test.tsx
src/tests/unit/tests/DetailsView/details-view-renderer.test.tsx

Currently, the `DetailsViewContainerProps` contains props that are actually deps. This make the testing and refactoring (in general of `DetailsViewContainer` and related component children) harder than it should be.
In this PR: moving all props that are deps to the deps prop.
**Notes** 
- this refactor will in time help solving #2324
- there is a lot of more clean up we could do, but right now seems like a rabbit hole, or something I would like to iron out by chunks

refactor: clean up details view container props/deps

---

src/electron/flux/action-creator/scan-action-creator.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/electron/flux/action-creator/scan-action-creator.test.ts
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap

Invoking `resetConnection` action fixes this issues.

fix: connected device info still present even if device disconnected (unified) 

---

src/tests/unit/tests/background/actions/action-creator.test.ts

We need an instance of `ActionHub` to run the tests for the `ActionCreator`. We are creating that instance manually, assigning each property with a mock or a null value. This force use to update this test every time we add a new "actions" property to the `ActionHub` even if that new property does not affect the `ActionCreator` test.
By using casting (as in `as ActionHub`) we can avoid this, remove the null properties and only assign mocks to what we actually need on the test.

refactor: action hub dependency on action-creator test

---

src/electron/platform/android/device-config-fetcher.ts
src/electron/platform/android/device-config.ts
src/tests/unit/tests/electron/flux/action-creator/device-connect-action-creator.test.ts
src/tests/unit/tests/electron/platform/android/device-config.test.ts
src/tests/unit/tests/electron/platform/android/fetch-device-config.test.ts

- Simplify testing by using `it.each` and lodash `set` function to make custom `rawData` objects
- Take advantage of typescript optional chaining to get rid of the try-catch blocks
**Note** I ended up explicitly returning `null` on both of the getters as the default case. Not doing so causes the getter to return `undefined` instead of null and I'm not sure I want to just "break" the current contract. But I can see it that we want that instead.

refactor: device config and tests

---

src/electron/views/device-connect-view/device-connect-view.scss

Currently the text in unified/electron dialogs does not change color in when high contrast mode is enabled. Two examples include the telemetry permissions dialog and the device disconnected dialog. These render in a layer inside body and adjacent to #root-container. 
This PR includes one approach to fix this by targeting all .ms-Fabric descendants of body in addition to body itself. It feels a bit odd to me that a change in device-connect-view.scss would affect the device disconnected popup - would like to better understand what approach is best.

fix: handle 'color' attribute for dialogs in HC mode

---

src/DetailsView/components/interactive-header.tsx
src/DetailsView/details-view-container.tsx
src/common/components/gear-menu-button.tsx
src/popup/components/launch-panel-header.tsx
src/tests/unit/tests/DetailsView/__snapshots__/details-view-container.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/interactive-header.test.tsx.snap
src/tests/unit/tests/DetailsView/components/interactive-header.test.tsx
src/tests/unit/tests/DetailsView/details-view-container.test.tsx
src/tests/unit/tests/common/components/gear-menu-button.test.tsx
src/tests/unit/tests/popup/components/__snapshots__/launch-panel-header.test.tsx.snap

Move the `GearMenuButton` deps to the proper place.
**Note** this PR is part of the effort to address #2324

refactor: true up gear menu button deps

---

deploy/Gruntfile.js

Similar to #2058, this PR fails the grunt task if the webstore publish fails. A recent error we saw in our publish step results from this [line](https://github.com/c301/grunt-webstore-upload/blob/c62cce2191cd8717de08ba670bbc4c1be2dbbc61/tasks/webstore_upload.js#L651) - however, the library does not call the `onError` callback in this case. Instead, we wait for the upload result [here](https://github.com/c301/grunt-webstore-upload/blob/c62cce2191cd8717de08ba670bbc4c1be2dbbc61/tasks/webstore_upload.js#L374) and fail the task ourselves if needed. To test this, I added the grunt options `fakeUpload` / `fakeBadPublish`, and manually removed some required checks for appId / other options I didn't have set up locally.

chore: fail the grunt publish task if it resolves with 'BadUploadResult'

---

src/DetailsView/Styles/detailsview.scss
src/DetailsView/components/test-step-view.scss
src/DetailsView/components/test-step-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/test-step-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/test-step-view.test.tsx

Removes some dead css and _starts_ the process for more work in this component.
The reason I did not continue and do more was due to conflicts with detailsview.scss that would require me to use more !important styles. I want to look into how I can just not use those styles from detailsview.scss instead.
CSS remains unchanged:

refactor: start cleaning up css for test step view

---

src/DetailsView/Styles/detailsview.scss

None of these classes were found in the repo.
The one related to landmarks does exist but only in content, which has its own styles elsewhere.

refactor: removes dead css related to old visualization guidance

---

src/debug-tools/components/debug-tools-view.tsx
src/debug-tools/components/stores-tree.tsx
src/debug-tools/initializer/debug-tools-init.tsx
src/tests/unit/tests/debug-tools/components/__snapshots__/debug-tools-view.test.tsx.snap
src/tests/unit/tests/debug-tools/components/__snapshots__/stores-tree.test.tsx.snap
src/tests/unit/tests/debug-tools/components/debug-tools-view.test.tsx
src/tests/unit/tests/debug-tools/components/stores-tree.test.tsx

Currently, the main react component in the debug tools is in charge off listening to the stores and re-render when there are updates. 
This PR refactors this behavior by leveraging `WithStoreSubscription` and adding a new component in charge of being the top-level container component.
**Notes** there are no actual changes on the UI/UX

refactor: debug tools to use WithStoreSubscription

---

package.json
tools/get-change-log-for-release.js
yarn.lock

Add a small js script to generate a csv file with the changes between to commits/tags.
There are two ways to use it:
```bash
node ./tools/get-change-log-for-release.js [options]
```
or
```bash
yarn change-log [options]
```
And this are the `[options]`
```bash
Usage: get-change-log-for-release [options]
Options:
-f, --from <commit_hash or tag>  Starting point to get the logs. Required.
-t, --to <commit_hash or tag>    Ending point to get the logs. Required.
-o, --output <output_path>       Path to the output file. Default: change-log.<from>-<to>.csv
-h, --help                       output usage information
```
Here's a snip of the resulting csv file:
```csv
tester,verified,dev,commit,change,group,version,date
,,"dependabot-preview[bot]","356652a","chore(deps-dev): bump @types/chrome from …
```

tool: script to generate change log for release

---

Gruntfile.js
src/debug-tools/components/debug-tools-view.tsx
src/debug-tools/debug-tools.html
src/debug-tools/debug-tools.scss
src/debug-tools/initializer/debug-tools-init.tsx
src/tests/unit/tests/debug-tools/components/__snapshots__/debug-tools-view.test.tsx.snap

Add the extension header to the debug tools page. Also, remove body margins.

tools: add header to debug tools page

---

pipeline/scripts/print-file-hash-info.js
pipeline/unified/build-unsigned-release-packages.yaml

Sometimes to investigate failures in the canary signing step, it's helpful to know the sha256 of each file we submit to the service. This PR logs the hashes during the build.

chore: log file hashes in unified canary pipeline to help debug signing

---

src/popup/components/popup-view.tsx
src/tests/unit/tests/popup/components/__snapshots__/popup-view.test.tsx.snap
src/tests/unit/tests/popup/components/popup-view.test.tsx

As part of our threat model follow up, we need to handle our usages of `dangerouslySetInnerHtml`. That means remove them or somehow account for them (in the sense of: let's not add more usages and make it clear where and why we are using it).
In this case, it was possible to remove the usage of `dangerouslySetInnerHtml` and replace it with "normal" react code.
**Note** there is no actual change on the UI/UX

feat(threat-model): remove usage of dangerouslySetInnerHtml on popup view

---

src/reports/assessment-report-html-generator.tsx
src/reports/components/report-head.tsx
src/reports/components/report-sections/results-container.tsx
src/tests/unit/tests/reports/assessment-report-html-generator.test.tsx
tslint.json

As part of our threat model follow up, we need to handle our usages of `dangerouslySetInnerHtml`. That means remove them or somehow account for them (in the sense of: let's not add more usages and make it clear where and why we are using it).
There is a microsoft contrib tslint rule to catch uses of `dangerouslySetInnerHtml`. In this PR I'm enabling that and grandfathering the current usages of this property through our code.
I do thing there is more we can do to actually remove this usages, so we can either have this PR as a backup plan, or we can go ahead (so we have the tslint rule and no more usages are introduce) and fix what we can later (still during this feature).
**Note** this PR will fail tslint check as it depends on another PR where I was able to remove one of the usages.

feat(threat-model): enable tslint rule for no dangerous html property

---

src/Devtools/dev-tool-init.ts
src/Devtools/dev-tool-initializer.ts
src/Devtools/inspect-handler.ts
src/Devtools/target-page-inspector.ts
src/background/dev-tools-chrome-adapter.ts
src/tests/unit/mock-helpers/dev-tools-chrome-adapter-mock.ts
src/tests/unit/tests/DevTools/inspect-handler.test.ts
src/tests/unit/tests/DevTools/target-page-inspector.test.ts

As part of our threat model follow up we need to assess our usage of javascript `eval`(which we don't have any and we do have a tslint rule to catch this). While looking at our code base, I found we are using `chrome.devtools.inspectedWindow.eval` (this allow the user to inspect an element we marked as failing an automated check, directly from the target page's details dialog).
While we are using this `eval` API only to call `inspect`, we are implementing this in a way we can pass any script to `eval` (not only `inspect`) which is not necessary and also a opens the door for some security risks.
In this PR:
- Change the API so the user cannot pass just any script; the new API is specific for inspect, the user can pass a selector
- Run some basic sanitization on the input (the selector) as …

feat(threat-model): introduce target page inspector

---

src/DetailsView/components/base-visual-helper-toggle.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/restart-scan-visual-helper-toggle.test.tsx.snap
src/tests/unit/tests/assessments/automated-checks/__snapshots__/automated-checks-visualization-toggle.test.tsx.snap

Per #682, the proposed resolution to make the Visual Helper toggles read more pleasantly for AT users was:
> After discussion with @ferBonnin ; the want from this issue is that whenever the visual helper is disabled; AT should not be reading the state of it. 
> It should just say for example: 
> ```
> Visual Helper
> No matching/failing instances were found
> ```
This PR achieves that by `aria-hidden`ing the toggle and its on/off label using a new wrapping `<div>` when the toggle is disabled. The new wrapper element is required because Office Fabric only applies `aria-hidden` props passed to a `Toggle` to the actual `<button>` element representing the toggle, not to the On/Off label, and we want it applied to both.
Verified that the desired reading occurs in NVDA and JAWS, verified no …

fix: disabled visual helper toggles read confusingly for AT users

---

src/DetailsView/Styles/detailsview.scss
src/tests/end-to-end/test-resources/clean.html

The left-padding we were adding to our "target page hidden" message bar was interacting poorly with the container for the main panel, causing the size of the whole panel to over-expand by the padding amount. This resolves that issue by replacing the padding on the message bar with some margin in the content of the message bar.
This PR also includes a new "clean.html" test page with no automated checks faliures that I used to test the change.
Before:
After (same size/zoom):

fix: avoid extra horizontal scroll bar in fastpass automated checks "no failures" view

---

src/assessments/contrast/test-steps/state-changes.tsx

Add note on Contrast > State changes > How to test according to #2406

fix: Text change in Contrast > State changes > How to test

---

src/reports/components/assessment-report-footer.tsx
src/tests/unit/tests/reports/components/__snapshots__/assessment-report-footer.test.tsx.snap

This is a sister change to #2348, updating the assessment report similarly to how it updated the FastPass report (changing how we refer to the axe-core version that generated the report from "Axe 1.2.3" to "axe-core 1.2.3").

fix: update wording in assessment report footer from Axe to axe-core to match FastPass's

---

src/background/actions/action-creator.ts
src/background/actions/details-view-action-creator.ts
src/background/actions/preview-features-actions.ts
src/background/stores/details-view-store.ts
src/background/stores/side-panel.ts
src/tests/unit/tests/background/actions/action-creator.test.ts
src/tests/unit/tests/background/actions/details-view-action-creator.test.ts
src/tests/unit/tests/background/stores/details-view-store.test.ts

Following up from previews PRs (#2313, #2420), updating how we handle opening the preview feature panel to use the new side panel logic.
Out of scope:
- updating other panels to use the side panel logic (content panel, add failure instance, etc)
- updating how we close side panel
Those will come on future PRs

refactor(side-panel): open preview feature panel as side panel

---

src/background/actions/details-view-action-creator.ts
src/background/actions/scoping-actions.ts
src/background/actions/scoping-panel-action-creator.ts
src/background/stores/details-view-store.ts
src/background/stores/side-panel.ts
src/background/tab-context-factory.ts
src/tests/unit/tests/background/actions/details-view-action-creator.test.ts
src/tests/unit/tests/background/actions/scoping-panel-action-creator.test.ts
src/tests/unit/tests/background/stores/details-view-store.test.ts

Following up from previews PRs (#2313, #2420, #2424), updating how we handle opening the scoping panel to use the new side panel logic.
Out of scope:
- updating other panels to use the side panel logic (content panel, add failure instance, etc)
- updating how we close side panel
Those will come on future PRs

refactor(side-panel): open scoping panel as a side panel

---

package.json
yarn.lock

The version of `dot-prop` used by default in the latest version of `react-devtools` is the subject of prototype pollution vulnerability CVE-2020-8116; this isn't a particularly high risk for us because we only have react-devtools set up for use in connecting from a local dev environment to a local dev environment, but this PR remediates the component governance warning.
Verified that devtools still works fine with the dependency forcibly updated

chore: update transitive dot-prop dependency introduced with react-devtools

---

src/common/styles/high-contrast-theme-palette.ts

High contrast
- Changed `themePrimary` in `high-contrast-theme-palette.ts` from #0078d4 to #2b88d8 to increase contrast ratio on *Export result*, *Start over*, *How to test*, *Info & examples*, and *Add a failure instance* buttons, as suggested in #2405
Default
- No change for default theme because the buttons had the expected colors/ratio
Screenshots (before)
Screenshots (after)

fix: color contrast on button text in high contrast mode

---

src/common/html-element-utils.ts
src/injected/details-dialog-handler.ts
src/injected/visualization/center-position-calculator.ts
src/injected/visualization/highlight-box-drawer.ts
src/injected/visualization/highlight-visualization.tsx
src/injected/visualization/root-container-creator.ts
src/injected/visualization/svg-drawer.ts
src/tests/unit/tests/common/html-element-utils.test.ts
src/tests/unit/tests/injected/details-dialog-handler.test.ts
src/tests/unit/tests/injected/visualization/center-position-calculator.test.ts
src/tests/unit/tests/injected/visualization/highlight-visualization.test.tsx
src/tests/unit/tests/injected/visualization/root-container-creator.test.ts

This is an alternative to the PR (#2373) that using the html element. This is safer than querying for the body selector as it [also includes frameset elements](https://developer.mozilla.org/en-US/docs/Web/API/Document/body).
- [] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`

fix: using document.body instead of querying for body selector

---

src/electron/common/unified-feature-flags.ts
src/tests/unit/tests/electron/common/unified-feature-flags.test.ts

Add `exportReport` feature flag to hide the new export report functionality on AI-Android.

feat(android-report): add exportReport feature flag for unified

---

src/background/actions/details-view-action-creator.ts
src/background/actions/details-view-actions.ts
src/background/actions/side-panel-actions.ts
src/background/stores/details-view-store.ts
src/tests/unit/tests/background/actions/details-view-action-creator.test.ts
src/tests/unit/tests/background/stores/details-view-store.test.ts

Following up from previews PRs (#2313, #2420, #2424, #2427), updating how we handle closing the settings panel to use the new side panel logic.
Out of scope:
- updating other panels to use the side panel logic (content panel, add failure instance, etc)
Those will come on future PRs

refactor(side-panel): close settings panel as a side panel

---

src/background/background-init.ts
src/background/telemetry/debug-tools-telemetry-client.ts
src/background/telemetry/telemetry-client-provider.ts
src/common/constants/connection-names.ts
src/debug-tools/controllers/telemetry-listener.ts
src/debug-tools/initializer/debug-tools-init.tsx
src/electron/views/renderer-initializer.ts
src/tests/unit/tests/background/telemetry/debug-tools-telemetry-client.test.ts
src/tests/unit/tests/background/telemetry/telemetry-client-provider.test.ts
src/tests/unit/tests/debug-tools/controllers/telemetry-listener.test.ts

This PR introduces most (maybe all) of the piping needed to send and consume telemetry events on the debug tools.
The implementation relies on chrome API's that allows us to more explicitly establish a communication channel between different context (in this case, the background and the debug tools page). This allow for more fine-grained control.
There is no UI being added on this PR so to keep it more or less simple. The way to check it is working is to open the debug tools tab and inspect the page; the console will show all the telemetry events being trigger by the extension.

tools: add debug tools telemetry client and listener

---

src/DetailsView/components/report-export-component-factory.tsx
src/DetailsView/details-view-container.tsx
src/DetailsView/details-view-initializer.ts
src/common/types/store-data/scan-meta-data.ts
src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/automated-checks/components/command-bar.tsx
src/electron/views/renderer-initializer.ts
src/reports/package/axe-results-report.ts
src/reports/package/reporter-factory.ts
src/reports/report-generator.ts
src/reports/report-html-generator.tsx
src/tests/unit/tests/DetailsView/components/report-export-component-factory.test.tsx
src/tests/unit/tests/DetailsView/details-view-container.test.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/command-bar.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/command-bar.test.tsx
src/tests/unit/tests/reports/package/axe-results-report.test.ts
src/tests/unit/tests/reports/report-generator.test.ts
src/tests/unit/tests/reports/report-html-generator.test.tsx

This ensures that toolData is used from the unified scan result store instead of whichever environment the current running code is in.

refactor(android-report): get ToolData from scan instead of environment when generating report

---

src/electron/views/report/unified-report-section-factory.ts
src/electron/views/root-container/components/root-container.scss
src/reports/components/report-sections/footer-text-for-unified.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/footer-text-for-unified.test.tsx.snap

Minor changes to:
1. Make the report scrollable in android.
2. Remove the Not Applicable rules component
3. Modify the text in footer to use tool data scan engine name.
Screenshot:

fix(android-report): minor style fix + minor text change to footer text

---

src/debug-tools/debug-tools.scss

Adding the missing `color-definitions.scss` import to `debug-tools.scss` to fix some stylings on the debug tools page.
**Before**
**After**
**Notes**
There is still not full support for high contrast mode on the debug tools, so with this change, the heart icon will change accordingly to high contrast, but the background will stay the same.

tools: import missing color-definitions

---

src/electron/views/report/unified-report-section-factory.ts
src/reports/components/report-sections/automated-checks-report-section-factory.tsx
src/reports/components/report-sections/summary-section.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/summary-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/summary-section.test.tsx

Simply made the outcome types a prop on the summary section as is and made two versions of the component used by the different reports.
Screenshot (left: web, right: unified)

feat(android-report): created/re-factored summary section for unified report

---

src/content/test/headings/guidance.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

Remove the `WCAG 1.3.1` link from headings guidance.

fix: remove wcag link and replace it with best practice in headings assessment guidance

---

src/electron/views/renderer-global-styles.scss

feat(android-report): match export report dialog width to with web (25%)

---

src/electron/views/root-container/components/root-container.scss
src/reports/components/report-sections/summary-section.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/summary-section.test.tsx.snap

feat(android-report): fixed body color and summary section ordering

---

src/tests/electron/tests/first-time-dialog.test.ts

This PR follows up on #2327 by adding an a11y end-to-end test for the first-time-dialog in unified. It's helpful to have the e2e test for both web & unified because of layering scenarios that don't show up in the web test, such as the issue in https://github.com/microsoft/accessibility-insights-web/issues/2316
alternative implementations:
- fully fold the `first-time-dialog` into `DeviceConnectionDialogController` by adding an explicit `dismissTelemetryDialog()` method. Remove the existing `suppressFirstTimeDialog` flag in `createApplication`. This would collapse this new e2e test file with the existing `device-connection-dialog` tests, reducing the number of times we need to restart the app
- move `this.waitForSelector(CommonSelectors.rootContainer)` into `AppController` and similarly …

chore: add first-time-dialog test for electron

---

src/reports/components/report-sections/full-rule-header.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/full-rule-header.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/full-rule-header.test.tsx
src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap

A couple changes:
1. Rules are not rendered as links when there is no url in passed/not-applicable section.
2. Rules that do not have guidance will not have empty parenthesis where that guidance link would go.
These changes apply to Web and the not applicable section as well. However, since we do not show that yet and both changes will not realistically be shown in Web, it doesn't "really" apply, if that makes sense. As in, no user should see them but since they are shared components, they changes are there.
Before on the left, After on the right:

feat(android-report): minor improvements to passed section

---

src/common/components/cards/result-section-title.scss

This doesn't fix all the alignment issues (and that's tough to do due to this being rendered differently in each scenario) but it does improve the situation quite a bit.
Automated Checks in Web Before vs After (left to right):
Automated Checks Report in Web Before vs After
Automated Checks in Unified Before vs After:
Automated Checks Report in Unified Before vs After:

fix: improvement to alignment w/ outcome chip in reports result title section.

---

src/tests/electron/tests/automated-checks-view.test.ts
src/tests/electron/tests/device-connection-dialog.test.ts
src/tests/electron/tests/unified-settings-panel.test.ts

This PR removes `dialog = null` setters in our e2e tests. While the electron BrowserWindow should be set to null upon close per docs [here](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#event-closed), it doesn't seem clear that this is related. In this PR check, the electron-e2e-reliability build had 3 (out of 18) failures that seemed to match existing e2e flakiness symptoms.

test: try removing null setters in e2e test cleanup

---

src/tests/electron/common/view-controllers/app-controller.ts

This attempts to fix a unified e2e reliability issue of the form ([example](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=74210&view=ms.vss-test-web.build-test-results-tab&runId=2247790&resultId=100021&paneView=debug)):
```
Error: An error occurred while executing user supplied JavaScript.
at executeAsync(<Function>, "window.insightsUserConfiguration.setHighContrastMode(false)", , "require") - D:\a\1\s\node_modules\spectron\lib\api.js:393:17
```
This happens inconsistently and I don't have a local repro to verify exactly what the exception is, but my suspicion is that it might be invoking this bit of script before the insightsUserConfiguration controller is initialized, so this updates the code to wait for it like we already do for `setTelemetryState`.
- [n/a] …

test: update setHighContrastMode to wait for userConfig controller

---

src/background/actions/popup-action-creator.ts
src/background/background-init.ts
src/background/keyboard-shortcut-handler.ts
src/background/tab-context-factory.ts
src/background/usage-logger.ts
src/common/date-provider.ts
src/electron/views/renderer-initializer.ts
src/tests/unit/common/date-provider.test.tsx
src/tests/unit/tests/background/actions/popup-action-creator.test.ts
src/tests/unit/tests/background/keyboard-shortcut-handler.test.ts
src/tests/unit/tests/background/tab-context-factory.test.ts
src/tests/unit/tests/background/usage-logger.test.ts

This is an initial iteration of #2375 that sets the last-used-time. The intent is to set this data often enough to capture meaningful usage (e.g. popup opened, keyboard shortcuts). This excludes approaches that run in background-init.ts (background script also runs upon install & updates).

feat(usage-data): record initial usage data upon extension entry points

---

src/DetailsView/components/export-dialog.tsx
src/common/feature-flags.ts
src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/export-dialog.test.tsx.snap
src/tests/unit/tests/DetailsView/components/export-dialog.test.tsx
src/tests/unit/tests/background/feature-flags.test.ts
src/tests/unit/tests/electron/common/unified-feature-flags.test.ts

The feature flag on web to enable exporting to CodePen currently has the same name as the feature flag to enable the export report button in electron. As a result, turning on this feature flag in electron automatically also enables exporting to CodePen, which we do not want. This PR renames the CodePen feature flag from exportReport to exportReportOptions

refactor: rename exportReport feature flag

---

src/tests/electron/common/view-controllers/automated-checks-view-controller.ts
src/tests/electron/common/view-controllers/view-controller.ts

This PR attempts to fix the following class of unified e2e flakiness ([example](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=74651&view=logs&j=5ca0a2fb-3894-5dc8-ae91-49e140341ffc&t=e3a7ed4b-97f0-5ad9-e559-3ac0c9f4f59d)):
```
FAIL electron tests src/tests/electron/tests/unified-settings-panel.test.ts (30.64s)
● Console
console.log src/tests/end-to-end/common/screenshot-on-error.ts:14
Screenshot file is located at: /Users/runner/runners/2.166.3/work/1/s/test-results/e2e/failure-screenshots/1ba4b7a7-6b32-4d89-a963-0ce7e0d3d78b.png
● AutomatedChecksView -> Settings Panel › High Contrast Mode toggle › should apply the appropriate CSS style when High Contrast Mode setting is toggled
element click intercepted: Element <button id="enable-high-contrast-mode" …
```

test(unified): attempted fix for unified-settings-panel test mispositioned click

---

src/debug-tools/components/telemetry-viewer/telemetry-common-fields.scss
src/debug-tools/components/telemetry-viewer/telemetry-common-fields.tsx
src/debug-tools/components/telemetry-viewer/telemetry-messages-list.tsx
src/debug-tools/components/telemetry-viewer/telemetry-viewer.tsx
src/debug-tools/controllers/telemetry-listener.ts
src/debug-tools/initializer/debug-tools-init.tsx
src/tests/unit/tests/debug-tools/components/telemetry-viewer/__snapshots__/telemetry-common-fields.test.tsx.snap
src/tests/unit/tests/debug-tools/components/telemetry-viewer/__snapshots__/telemetry-messages-list.test.tsx.snap
src/tests/unit/tests/debug-tools/components/telemetry-viewer/__snapshots__/telemetry-viewer.test.tsx.snap
src/tests/unit/tests/debug-tools/components/telemetry-viewer/telemetry-common-fields.test.tsx
src/tests/unit/tests/debug-tools/components/telemetry-viewer/telemetry-messages-list.test.tsx
src/tests/unit/tests/debug-tools/components/telemetry-viewer/telemetry-viewer.test.tsx
src/tests/unit/tests/debug-tools/controllers/telemetry-listener.test.ts

Adding a new section (not hook up yet though) to be able to visualize telemetry events from the extension, displaying them on a list (`<DetailsList>` to be more precise).
**no telemetry messages yet**
**telemetry message on a list**
**Future work**
- There is a missing styling on the content border. I think we do have a small (5px maybe) border around the content (except for the header itself). I'd like to adjust that styling as part of a future hook up PR
- Hook up the view into the debug tools container so it actually shows up. I didn't want to include that part in this PR as it will introduce a new UI piece (probably a nav bar so the user can navigate between the different sections)
- Filtering events
- Better visualization for custom properties
- Start/stop registering events: …

tools: telemetry viewer

---

webpack.config.js

This PR fixes a very subtle but very serious issue in our webpack module resolution config.
Background: when you run `yarn install`, it uses an algorithm similar to the following to populate `/node_modules`:
* Scan the full dependency tree, downloading all required versions of all packages to a local cache (outside of `/node_modules`)
* For each direct dependency, put the directly dependent version in `/node_modules/package-name/`
* For each transitive dependency not already in `/node_modules/transitive-dep`, use an implementation-defined algorithm to pick one version of the transitive dependency (chosen by some combination of "most frequently used" and "used closest to the root of the dependency tree), and put that version in `/node_modules/transitive-dep`
* For each version-dep pair not …

chore: fix webpack transitive dependency resolution

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts

simply sets the right content panel to be overview when starting over the entire assessment.

fix: go to overview when restarting assessment

---

src/DetailsView/components/details-view-command-bar.tsx
src/DetailsView/components/report-export-component-factory.tsx
src/DetailsView/details-view-body.tsx
src/DetailsView/details-view-container.tsx
src/common/types/store-data/scan-meta-data.ts
src/electron/views/automated-checks/automated-checks-view.tsx
src/electron/views/automated-checks/components/command-bar.tsx
src/electron/views/report/unified-details-section.tsx
src/reports/components/report-sections/details-section.tsx
src/reports/components/report-sections/footer-text-props.ts
src/reports/components/report-sections/make-details-section-fc.tsx
src/reports/components/report-sections/report-section-factory.tsx
src/reports/package/axe-results-report.ts
src/reports/report-generator.ts
src/reports/report-html-generator.tsx
src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
src/tests/unit/tests/DetailsView/components/report-export-component-factory.test.tsx
src/tests/unit/tests/DetailsView/details-view-body.test.tsx
src/tests/unit/tests/DetailsView/details-view-container.test.tsx
src/tests/unit/tests/electron/report/unified-details-section.test.tsx
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/electron/views/automated-checks/components/command-bar.test.tsx
src/tests/unit/tests/reports/components/report-sections/details-section.test.tsx
src/tests/unit/tests/reports/components/report-sections/footer-text-for-unified.test.tsx
src/tests/unit/tests/reports/components/report-sections/footer-text.test.tsx
src/tests/unit/tests/reports/components/report-sections/make-details-section-fc.test.tsx
src/tests/unit/tests/reports/package/footer-text-for-service.test.tsx
src/tests/unit/tests/reports/report-generator.test.ts
src/tests/unit/tests/reports/report-html-generator.test.tsx

some props have a property called scanMetaData, while some capitalize it as scanMetadata. This will standardize all variables with this name to scanMetadata.

chore: capitalize ScanMetadata consistently

---

pipeline/unified/build-unsigned-release-packages.yaml
pipeline/unified/download-electron-mirror.yaml

This replaces the `ELECTRON_MIRROR_VAR` and `ELECTRON_CUSTOM_DIR_VAR` environment variables with `ELECTRON_701_MIRROR_VAR` and `ELECTRON_701_CUSTOM_DIR_VA`R, respectively. We're doing this to allow the build pipeline to support concurrent versions of Electron as we migrate to 8.x. A similar strategy will be applied to future version migrations.
Note that `ELECTRON_MIRROR` and `ELECTRON_CUSTOM_DIR` are intentionally _not_ changed, since these are the names of the data passed to the build tools.
Unsigned build 2020.422.21 has been queued to validate that the correct version of Electron is getting picked up by the build pipeline.
- [ n/a ] Added/updated relevant unit test(s) (and ran `yarn test`)

feat(Electron 8.x upgrade): Include electron version in build pipeline variable names

---

src/scanner/custom-rule-configurations.ts
src/scanner/custom-rules/header-rule.ts
src/tests/unit/tests/scanner/custom-rules/header-rule.test.ts

Add rule to collect table headers. Not being used right now.

feat(tables-requirements): Add rule to collect table headers

---

README.md
pipeline/build-reliability.yaml
pipeline/e2e-reliability.yaml
pipeline/unified/unified-e2e-reliability.yaml

This PR sets up the repo for migrating our public PR/CI builds from https://dev.azure.com/ms to https://dev.azure.com/accessibility-insights
Right now, the builds have been set up to run in both; we'll be turning off the /ms/ ones once we've merged this PR and updated the repo branch policies.
* Updates CI build badge on README
* Updates reliability builds to run on a nightly schedule instead of continuously with merges to master (at least until our support request to add additional parallel job capacity for our public projects in accessibility-insights goes through, but maybe we'll keep it like this)
- [n/a] (UI …

chore: migrate public builds to accessibility-insights devops org

---

src/reports/components/report-sections/automated-checks-header-section.tsx
src/reports/components/report-sections/automated-checks-report-section-factory.tsx
src/reports/components/report-sections/report-section-factory.tsx
src/reports/report-html-generator.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/automated-checks-header-section.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/automated-checks-header-section.test.tsx
src/tests/unit/tests/reports/report-html-generator.test.tsx

- Create a wrapper around HeaderSection that takes scanMetadata instead of targetAppInfo (AutomatedChecksHeaderSection)
- Use AutomatedChecksHeaderSection in automated checks report
- Remove targetAppInfo from SectionProps

refactor: use scanMetadata in HeaderSection for automated checks report

---

src/electron/views/renderer-global-styles.scss

Sets a min width to match web. Looks like this:

fix(android-report): sets minimum width for export dialog to 320px

---

pipeline/unified/sign-release-packages.yaml

This will fix the issue of having a manually triggered pipeline for insider and production where we don't have control over what is getting signed. Will update the releases to use this pipeline after this is merged and delete the old pipelines in a separate PR.

fix: sign code for all release channels in one pipeline

---

build.yaml

This switches the conditional for when our PR/CI builds run CG/Notice generation to allow us to avoid running it in the public devops instance (where CG is not enabled) and instead run it only in the private instance using a build variable I've just added to the private CI build.
Addresses [this public CI build failure](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=8287&view=logs&j=a131156f-3b43-553f-e7ad-02c8341f7440&t=b775a80b-db19-5e1f-518a-020944e6f74d) …

chore(build-break): switch condition for CG/Notice gen to variable-based

---

src/common/feature-flags.ts
src/tests/unit/tests/background/feature-flags.test.ts

This reverts commit 6387f77452bb689852fa0bfacdbd6b409d1aad60.
It turns out we don't actually need the feature flag for this feature because each change to the content is atomic, meaning users will never encounter work that isn't complete.

feat(tablesRequirements): Revert Add feature flag for upcoming tables requirements changes (#2542)

---

.vscode/settings.json

Updates our project VS Code EOL setting to match prettier config, to avoid issues where "format on save" does the wrong thing by default on windows machines.

chore: set default vscode eol to match prettier settings

---

src/DetailsView/components/export-dialog.scss
src/DetailsView/components/export-dialog.tsx
src/electron/views/renderer-global-styles.scss
src/tests/unit/tests/DetailsView/components/__snapshots__/export-dialog.test.tsx.snap

Increases the size of the export dialog scale factor (while setting a max-width that might make sense).
Note: moved to using css modules after realizing the telemetry dialog was effected by the changes. I checked to see what styles were being applied with the override css class and realized it was about the same as what I was already doing. Hence, it made sense to reduce an instance of that and move to css modules here.
Gif of what that looks like:
Here it is in Web:

fix: resize for export dialog in android

---

src/assessments/semantics/test-steps/headers-attribute.tsx
src/assessments/semantics/test-steps/headers.tsx
src/assessments/semantics/test-steps/table-semantics.tsx
src/content/test/semantics/headers-attribute.tsx
src/content/test/semantics/headers.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

Addressed the following feedbacks from PMs:
- Inconsistent styling of code snippets in Requirements list
- Table semantics 
Steps 2a and 2b should have the same text as in the Headers requirement
Steps 4a and 4b have some missing spaces between words
In steps 4a and 4b, recommend italicizing "must not be" and "must be"
- Headers
Inconsistent styling of code snippets in first sentence
Missing "a" and "b" under steps 2 and 3
In steps 3a and 3b, recommend italicizing "must be" and "must not be"
Updated screenshot:

feat(tables-requirements): Fit and finish

---

src/content/test/multimedia/captions.tsx
src/content/test/native-widgets/cues.tsx
src/content/test/pointer-motion/pointer-cancellation.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

During the review of #2572, I noticed a few places where there were unnecessary `{' '}`s lingering. This PR removes them.
Verified that there are no visual/reading changes to the affected content.

chore: fix a few unnecessary spacings in info and examples content

---

src/assessments/semantics/test-steps/table-semantics.tsx

There's a space missing between "or" and "`role="none"`" in table semantics how to fix 4.b.:
**before**
**after**

fix: missing space in table semantics how to test text

---

src/assessments/semantics/test-steps/css-content.tsx
src/assessments/semantics/test-steps/headers-attribute.tsx
src/content/test/semantics/headers.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

Addresses issues from #2583
1. Fixes CSS content styling of `:before` and `:after` selectors:
**before (left) vs after (right)**:
2. Fixes styling on `<th>` in description of pass example in Headers info and examples
**before (left) vs after (right)**:
3. Fixes styling on `id` attribute in Header attributes how to fix text:
**before (left) vs after (right)**:

fix: minor styling issues in semantics requirements

---

src/content/test/semantics/headers-attribute.tsx
src/content/test/semantics/headers.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

This fixes a silent merge conflict between the feature work adding the new header/header attributes requirements and #2572
Verified that no other infoAndExamples content is affected similarly.
I'd like to add a test case to prevent this class of issue, but scoping that to a later PR to unblock respinning 2.18.1
**before (left) vs after (right):**

fix: new Headers and Header attributes reqs not using new panel titles

---

src/content/test/semantics/guidance.tsx
src/content/test/semantics/table-semantics.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

We had a link in 2 places of the form:
```tsx
<Markup.HyperLink href="https://www.w3.org/TR/wai-aria-practices-1.1/">
Intentionally Hiding Semantics with the Presentation Role
</Markup.HyperLink>
```
...linking to the top-level document instead of the specific section labeled by the link text. This fixes both spots where we have a link of that format to use the anchor to the specific indicated section.

fix: add anchor to aria practices presentation_role links

---

src/DetailsView/components/assessment-view.tsx
src/DetailsView/details-view-initializer.ts
src/DetailsView/extensions/details-view-extension-point.ts
src/tests/unit/tests/DetailsView/components/assessment-view-props-builder.tsx
src/tests/unit/tests/DetailsView/components/assessment-view.test.tsx

Refactor AssessmentView to use AssessmentViewUpdateHandler instead of handling update logic itself

feat(nav-bar-cont): use AssessmentViewUpdateHandler

---

src/electron/views/automated-checks/automated-checks-view.scss

The update to electron 8.x (#2575) introduced a style regression described in issue #2590. This PR includes a fix.
See screenshots of scrollbar behavior:

fix: scrollbar in unified product

---

src/electron/main/main.ts

Electron's openDevTools has issues when running inside an elevated command prompt. This is discussed at https://github.com/electron/electron/issues/20069. The fix is to call setDevToolsWebContents, as called out in https://github.com/electron/electron/issues/20069#issuecomment-586642795 (and several subsequent comments indicate that this worked for them, as well). We don't bother to wait for the main window to report ready. but it doesn't seem to do any harm.
Tested by running with `DEV_MODE=true` from both elevated and non-elevated command prompts. Before the change, devTools opened only from the non-elevated command prompt. After the change, devTools open from both.

fix: Allow DEV_MODE to work from elevated command prompt

---

build.yaml
pipeline/build-all-job-per-environment.yaml
pipeline/build-package.template.yaml
pipeline/e2e-job-per-environment.yaml
pipeline/unified/build-unsigned-release-packages.yaml
pipeline/unified/channel/sign-release-package-linux.yaml
pipeline/unified/channel/sign-release-package-mac.yaml
pipeline/unified/channel/sign-release-package-windows.yaml
pipeline/unified/unified-e2e-job-per-environment.yaml

Our mac and linux build agents were both outdated, and our windows images were inconsistent (sometimes specifying the auto-updating latest image, sometimes the pinned version like we use elsewhere). This updates all build agents in all yaml pipeline definitions to use a pinned version corresponding to the latest available vmImage (per [DevOps docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops))

chore: update build agents to latest hosted vmImages

---

src/reports/assessment-report.scss

Improve formatting of instances added manually/copied from the Nu HTML checker by adding the white-space: pre-line
Before:
After:
I believe this could be further enhanced, but that would be a larger task since the class modified here is used throughout the report and not just the "Parse" section as described in the 

feat(line-breaks): Improve formatting of instances added manually

---

src/DetailsView/components/base-left-nav.tsx
src/DetailsView/components/left-nav/assessment-left-nav.tsx
src/DetailsView/components/left-nav/details-view-left-nav.tsx
src/DetailsView/components/left-nav/left-nav-link-builder.tsx
src/DetailsView/components/left-nav/overview-left-nav-link.tsx
src/DetailsView/components/left-nav/visualization-based-left-nav.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/base-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/base-left-nav.test.tsx
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/assessment-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/details-view-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/left-nav-link-builder.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/visualization-based-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/assessment-left-nav.test.tsx
src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx
src/tests/unit/tests/DetailsView/components/left-nav/visualization-based-left-nav.test.tsx

This PR does two things:
1. Adds a feature flag to assessment left nav for the reflow UI (currently will only show Overview link).
2. Refactors the renderIcon link responsibility to the nav-link-builder. This will be leveraged in a future PR where the types of links being built dictate how the icon is rendered (and not on a assessment vs fastpass level, as it is now).

feat(nav-bar-content): re-factored nav link building + added feature flag

---

pipeline/unified/channel/sign-release-package-linux.yaml

Signing pipeline is currently failing because the rename command is not installed by default on the new ubuntu vm images

fix: install rename in linux signing pipeline

---

pipeline/unified/download-electron-mirror.yaml

The code in `download-electron-mirror.js` used a different var name than what we passed in: https://github.com/microsoft/accessibility-insights-web/blob/8449c2d84b00b8323ee49835b0a4e2b882fd2d8a/pipeline/scripts/download-electron-mirror.js#L20
This was fine because the pipeline had both pairs, but they should match up so we can remove the extra pair in the pipeline. This will leave us with just 1 pair (except for during an upgrde, where we'll temporarily have the old and new vars defined).
The most recent update to @electron/get provides a custom URL resolution function, so I have a separate branch trying to leverage that to simplify this further.

fix: link the versioned electron vars to the pipeline

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/background/actions/action-payloads.ts
src/background/actions/assessment-action-creator.ts
src/background/actions/assessment-actions.ts
src/background/stores/assessment-store.ts
src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
src/tests/unit/tests/background/actions/assessment-action-creator.test.ts
src/tests/unit/tests/background/stores/assessment-store.test.ts

Renaming methods to select test sub view where necessary: basically in the action and action creator. We will have a future PR that will have separate calls for selectRequirement and selectGettingStarted that will eventually funnel into the selectSubview action.

refactor(left-nav-content): rename some cases of select test-step/requirement to select test subview

---

webpack.config.js

This PR updates our webpack config per the suggestion in https://github.com/webpack-contrib/mini-css-extract-plugin/issues/138 to remove all the spam from `mini-css-extract-plugin` that webpack's compilation error output would otherwise be wedged before.
Note, this doesn't resolve the excessively verbose scss output *before* the webpack step (out of scope for this PR, snipped from example output below)
Example output of a `yarn build` with an artificial compilation error:
**before** (note the ERROR output buried in the middle)
```
> yarn build
yarn run v1.22.4
$ grunt
Running "clean:intermediates" (clean) task
>> 1 path cleaned.
Running "exec:generate-scss-typings" (exec) task
Found 107 files. Generating type definitions...
[GENERATED TYPES] …
```

chore: suppress mini-css-extract-plugin noise from yarn build output

---

src/tests/unit/tests/injected/analyzers/base-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/batched-rule-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
src/tests/unit/tests/injected/frameCommunicators/frame-communicator.test.ts

`jest-circus` 26 includes a breaking change that disallows test cases from trying to mix patterns and by simultaneously accepting a done parameter and returning a promise (it only supports one or the other at a time).
This PR fixes the cases where we were doing this (via extraneous async keywords, in all cases), unblocking #2622 ([build with corresponding failures](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=8802&view=ms.vss-test-web.build-test-results-tab)).
Also cleaned up some minor naming issues I noticed while making the changes.

chore: avoid tests using both async and done (breaks in jest-circus 26)

---

src/reports/package/reporter-factory.ts

If we call reporterFactory() multiple times, office fabric gives the below warning in console:
_Some icons were re-registered. Applications should only call registerIcons for any given icon once. Redefining what an icon is may have unintended consequences. Duplicates include:
add, back, calculatorAddition, cancel, cat, checkBox, checkMark, chevronDown, chevronDownMed, chevronRight (+ 40 more)_

fix: should not initialize fabric icons more than once

---

src/DetailsView/components/assessment-test-view.tsx
src/DetailsView/components/reflow-assessment-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/reflow-assessment-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/reflow-assessment-view.test.tsx

Updated AssessmentTestView so it shows the reflow-assessment-view component when the reflowUI flag is enabled. Updated the related test. 

feat(nav-bar-content): Putting Reflow Assessment View behind a feature flag

---

src/content/link.tsx
src/electron/platform/android/rule-information-provider.ts
src/electron/platform/android/rule-information.ts
src/electron/platform/android/scan-results-to-unified-rules.ts
src/tests/unit/tests/electron/platform/android/__snapshots__/scan-results-to-unified-rules.test.ts.snap
src/tests/unit/tests/electron/platform/android/rule-information.test.ts
src/tests/unit/tests/electron/platform/android/scan-results-helpers.ts
src/tests/unit/tests/electron/platform/android/scan-results-to-unified-results.test.ts
src/tests/unit/tests/electron/platform/android/scan-results-to-unified-rules.test.ts

Since the rule link is still not available yet, so only the wcag links would be added as of this PR. Confirmed with Fer that this is ok.
screenshot for the new rule UI:

feat(mobile-rule-guidance): Add wcag guidance links

---

src/DetailsView/components/assessment-view-update-handler.ts
src/DetailsView/components/assessment-view.tsx
src/tests/unit/tests/DetailsView/components/assessment-view-update-handler.test.ts

Make AssessmentViewUpdateHandler only depend on the props and deps that it uses, instead of taking in all of AssessmentViewProps (especially since the new AssessmentView will likely have different props)

feat(nav-bar-content): Narrow down props used by AssessmentViewUpdateHandler

---

src/assessments/pointer-motion/assessment.tsx

Clarify that it's not just touch or motion, but that pointer includes all forms of pointers (mouse, touch, stylus)

fix: text change to pointer/motion short description (not just *touch* or motion)

---

src/assessments/text-legibility/test-steps/reflow.tsx
src/content/test/text-legibility/reflow.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

Normatively, 1.4.10 is scoped to all content, not just text. While the principal concern of the SC is indeed text, it applies in equal measure to other types of content/mixed content.
Admittedly, the normative wording is a bit wooly/omits certain extra scenarios (i.e. that the primary concern is that blocks of text are legible without tow-dimensional scrolling, rather than an outright
ban on two-dimensional scrolling ... see for instance https://github.com/w3c/wcag/issues/668), but one things it does not do is explicitly limit this to just the text portion of content.
> Success Criterion 1.4.10 Reflow (Level AA): *Content* can be presented without loss of information or functionality [...]
(emphasis on "Content", not "Text" or "Text content") …

fix: 1.4.10 Reflow is not solely about text

---

src/assessments/color/test-steps/auditory-cues.tsx
src/content/test/sensory/guidance.tsx
src/tests/end-to-end/tests/content/__snapshots__/guidance-content.test.ts.snap

WCAG 2.1 1.3.3. is only scope to *instructions* that describe other things based on sensory characteristics. The use of audio alone as a cue is not a failure of 1.3.3, but of 1.1.1. Audio-only cues are
non-text content (and time-based media, though relatively short ones). This may not be immediately clear/obvious from the normative wording of the SC (nor the current normative definition of "non-text content"
which gives only visual examples), but referring to 1.1.1 Understanding https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html see example 8:
> An e-learning application
>
> An e-learning application uses sound effects to indicate whether or not the answers are correct. The chime sound indicates that the answer is correct and the beep sound indicates that the answer is …

fix: auditory cues to convey information are WCAG 1.1.1 not 1.3.3

---

Dockerfile
package.json
pipeline/e2e-reliability.yaml

Cypress hasn't released a 12.16.3 image yet; downgrading our Dockerfile base to use the most recent available node LTS version, updating our package.json engine requirements to allow the looser version, and updating our e2e-reliability config to trigger automatically for future Dockerfile changes to avoid this class of regression in future version updates.
Should fix issues seen in, for example, this [web-e2e-reliability build](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=9045&view=results) from #2654 …

chore: fix web-e2e-reliability linux failures in fetching cypress/base:12.16.3 base image

---

src/DetailsView/components/assessment-test-view.tsx
src/DetailsView/components/reflow-assessment-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/reflow-assessment-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/reflow-assessment-view.test.tsx

Hook up the update handler to the new ReflowAssessmentView (enables updates from changing target page, scanning pages, enabling visual helpers, etc.)

feat(nav-bar-content): use AssessmentViewUpdateHandler in ReflowAssessmentView

---

src/DetailsView/components/left-nav/assessment-left-nav.tsx
src/DetailsView/components/left-nav/getting-started-nav-link.tsx
src/DetailsView/components/left-nav/left-nav-link-builder.tsx
src/common/types/store-data/assessment-result-data.ts
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/assessment-left-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/getting-started-nav-link.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/left-nav-link-builder.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/assessment-left-nav.test.tsx
src/tests/unit/tests/DetailsView/components/left-nav/getting-started-nav-link.test.tsx
src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx

This creates a new "duplicate" function on the left nav link builder to create the links for reflow (links now have tests, requirements, and getting started).
Ideally, I'd like to re-factor the left nav link builder but felt that the old link building didn't require it (i.e. fastpass) but this does. Additionally, I don't know how much I want to break up the responsibility of creating the link objects themselves: it's largely just composition and there are few branches of logic. I'd like to move out some of inner small components to separate modules though, as they allow for their own logic/have own responsibility.

feat(nav-bar-content): create new links for reflow left nav

---

src/DetailsView/components/assessment-test-view.tsx
src/DetailsView/components/assessment-view-update-handler.ts
src/DetailsView/components/assessment-view.tsx
src/DetailsView/components/reflow-assessment-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/assessment-view-props-builder.tsx
src/tests/unit/tests/DetailsView/components/assessment-view-update-handler.test.ts

The isEnabled property on Assessment view is a little ambiguous as to what it refers to. This PR will rename it to selectedRequirementIsEnabled so it's somewhat clearer.

refactor: rename isEnabled

---

src/tests/unit/common/test-assessment-provider.tsx

Our `test-assessment-provider` helper was still including a property (`defaultInstanceStatus`) in test AssessmentData which was removed in the production type some time ago and is no longer used. This removes the obsolete property.

chore: remove obsolete property from test assessment data provider

---

src/DetailsView/components/assessment-test-view.tsx
src/DetailsView/components/assessment-view-update-handler.ts
src/DetailsView/components/assessment-view.tsx
src/DetailsView/components/reflow-assessment-view.tsx
src/DetailsView/components/test-step-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/reflow-assessment-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/test-step-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/assessment-view-update-handler.test.ts
src/tests/unit/tests/DetailsView/components/assessment-view.test.tsx
src/tests/unit/tests/DetailsView/components/reflow-assessment-view.test.tsx
src/tests/unit/tests/DetailsView/components/test-step-view.test.tsx

Move UpdateHandler to TestStepView and remove it from AssessmentView and ReflowAssessmentView. This fixes errors that are currently thrown when trying to navigate the new reflow nav (the update handler attempts to enable or disable relevant visual helpers on the getting started view).

feat(nav-bar-content): handle getting started in AssessmentViewUpdateHandler

---

src/DetailsView/components/left-nav/getting-started-nav-link.scss
src/DetailsView/components/left-nav/getting-started-nav-link.tsx
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/getting-started-nav-link.test.tsx.snap

added an scss file for the getting-started-nav-link so that the "Getting Started" navigation link shares the same padding as the requirements.
Image of the change: 

feat (nav-bar-content): getting-started-nav-link padding update

---

src/DetailsView/components/left-nav/requirement-table-section.tsx
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/requirement-table-section.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/requirement-table-section.test.tsx

Refactors `renderTable` in test-step-view to a separate component for the new reflow UI.

feat(nav-bar-content): adding requirement table section

---

src/DetailsView/components/left-nav/assessment-left-nav.tsx
src/DetailsView/components/left-nav/left-nav-link-builder.tsx
src/DetailsView/components/left-nav/nav-link-handler.ts
src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/left-nav-link-builder.test.tsx.snap
src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx
src/tests/unit/tests/DetailsView/handlers/nav-link-handler.test.ts

This enables us to generate keys for the purpose of left nav selection orthogonally from selecting a requirement/getting-started.

feat(nav-bar-content): nav link handler uses requirement key explicitly

---

src/DetailsView/components/assessment-test-view.tsx
src/DetailsView/components/assessment-view-update-handler.ts
src/DetailsView/components/assessment-view.tsx
src/DetailsView/components/reflow-assessment-view.tsx
src/DetailsView/components/test-step-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-test-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/assessment-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/reflow-assessment-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/test-step-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/assessment-view-update-handler.test.ts
src/tests/unit/tests/DetailsView/components/assessment-view.test.tsx
src/tests/unit/tests/DetailsView/components/reflow-assessment-view.test.tsx
src/tests/unit/tests/DetailsView/components/test-step-view.test.tsx

This reverts 63145e4, which introduced #2695. Details from Dan: 
> automated checks only indirectly renders the TestStepView via src\DetailsView\extensions\wait-for-all-requirements-to-complete.tsx; the test step view doesn't get mounted until after all the requirements complete, but the logic to start the visualizer was moved to the mount phase of the TestStepView"
This impacts the under-feature-flag reflow work, but is not intended to have other side effects

fix: revert 63145e4 to fix stuck assessment > automated checks scanning

---

.prettierignore

The recently added unified codec test added an mp3 file to the repo, and `yarn fastpass` shows some noise when Prettier tries to analyze it:
```
[format:check   ] [error] No parser could be inferred for file: src\tests\miscellaneous\codecs\codecs-test.mp3
```
This update causes prettier to ignore the binary file.

chore: fix error noise in yarn format from prettier + mp3 file

---

src/DetailsView/components/requirement-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/requirement-view.test.tsx

Also adds the update handler to the requirementView; like the test step view.

feat(nav-bar-content): add table section to requirements view

---

src/DetailsView/components/reflow-assessment-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/reflow-assessment-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/reflow-assessment-view.test.tsx

Remove update-handler from ReflowAssessmentView (to be added back later in RequirementView). This will fix the errors on Getting Started that were reintroduced by the revert in #2698.

feat(nav-bar-content): remove update-handler from ReflowAssessmentView

---

src/DetailsView/components/reflow-assessment-view.tsx
src/background/actions/assessment-action-creator.ts
src/tests/unit/tests/DetailsView/components/reflow-assessment-view.test.tsx
src/tests/unit/tests/background/actions/assessment-action-creator.test.ts

small refactor of using the same const for getting started subview instead of inline strings.

refactor(nav-bar-content): use const getting started string

---

src/electron/platform/android/rule-information-provider.ts

FIx the mapppings of two mobile rules.

fix: wcag mappings

---

src/DetailsView/components/getting-started-view.scss
src/DetailsView/components/getting-started-view.tsx
src/DetailsView/components/reflow-assessment-view.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/getting-started-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/reflow-assessment-view.test.tsx.snap
src/tests/unit/tests/DetailsView/components/getting-started-view.test.tsx
src/tests/unit/tests/DetailsView/components/reflow-assessment-view.test.tsx

- Added guidance icon to title in GettingStartedView
- Added GettingStartedView styles
Screenshot of Getting Started view for Headings test

feat(nav-bar-content): add guidance icon to getting started view

---

src/injected/components/command-bar.tsx
src/tests/unit/tests/injected/components/__snapshots__/command-bar.test.tsx.snap

Addresses accessibility issue 1720062, noting that NVDA/Narrator don't announce the error message we show when you try to use the target page dialog's Inspect HTML button without dev tools open ("To use the Inspect HTML button, first open the developer tools (F12).").
Just adds `role="alert"` to the container for the message.
No visual change. Verified that it didn't read it before and does read it after in both NVDA and Narrator.

fix: missing AT announcement for error when using Inspect HTML without dev tools open

---

src/DetailsView/components/report-export-component.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-component.test.tsx.snap
src/tests/unit/tests/DetailsView/components/report-export-component.test.tsx

This PR fixes an issue where special characters were being double-escaped in our export results dialog's description text field; before, entering a &, <, > character would cause it to re-escape the & as an HTML entity with every new keystroke.
The escaping here is unnecessary; both the fabric `TextField` that's rendering the dialog's text and also the `htmlGenerator` we pass the description to already handle unescaped special characters correctly (via passing them to React to render). This PR removed it and updates unit tests to pin the new behavior.
**Before**:
**After**:

fix: avoid over-escaping special characters in Export Results dialog

---

src/background/global-context-factory.ts
src/issue-filing/common/create-file-issue-handler.ts
src/issue-filing/common/issue-filing-controller-impl.ts
src/issue-filing/types/issue-filing-service.ts
src/tests/unit/tests/issue-filing/common/create-file-issue-handler.test.ts
src/tests/unit/tests/issue-filing/common/issue-filing-controller-impl.test.ts

In preparation for issue filing in the unified client, we need to remove the issue filing dependence on the web-only `BrowserAdapter`. This PR accomplishes that by creating `OpenIssueLink` and using it in place of `BrowserAdapter.createActiveTab`. There should be no impact on functionality. A future PR will use this to enable issue filing on the unified side.

feat(android-bug-filing): Introduce OpenIssueLink to remove BrowserAdapter from createFileIssueHandler

---

src/DetailsView/components/issue-filing-dialog.tsx
src/DetailsView/details-view-initializer.ts
src/background/actions/action-payloads.ts
src/background/global-action-creators/issue-filing-action-creator.ts
src/background/global-context-factory.ts
src/background/issue-details-text-generator.ts
src/common/components/cards/card-kebab-menu-button.tsx
src/common/components/copy-issue-details-button.tsx
src/common/components/issue-filing-button.tsx
src/common/message-creators/issue-filing-action-message-creator.ts
src/electron/views/automated-checks/automated-checks-view.tsx
src/injected/dialog-renderer.tsx
src/issue-filing/common/issue-filing-controller-impl.ts
src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
src/tests/unit/tests/background/global-action-creators/issue-filing-action-creator.test.ts
src/tests/unit/tests/background/issue-details-text-generator.test.ts
src/tests/unit/tests/common/components/cards/card-kebab-menu-button.test.tsx
src/tests/unit/tests/common/components/copy-issue-details-button.test.tsx
src/tests/unit/tests/common/components/issue-filing-button.test.tsx
src/tests/unit/tests/common/message-creators/issue-filing-action-message-creator.test.ts
src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
src/tests/unit/tests/issue-filing/common/issue-filing-controller-impl.test.ts

Currently, issue filing `ToolData` is set during initialization. This works for the web product, but the unified product's `ToolData` is not fully generated until a scan has been run (because it needs info from the android device). This PR refactors issue filing to get `ToolData` passed in along with other issue data at the moment an issue is filed. It should have no impact on functionality. A future PR will put it to use in the unified product. 

feat(android-bug-filing): Get ToolData at moment issue is filed rather than initialization

---

src/electron/views/automated-checks/components/command-bar.scss
src/electron/views/automated-checks/components/command-bar.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/command-bar.test.tsx.snap

Currently, some of the button appearances in the command bar of the electron app are inconsistent:
The icon for start over is black like the text, but the icon for export report is blue. In web, all button text is black and icons are blue in the default state. Per a conversation with Fer, these buttons should match the web stylings.
The different stylings also causes some issues in high contrast mode, as described in #2545. In addition to the text color not changing when hovering, buttons also appear whited out in the active state:
To fix this, this pr will remove our custom styles from the command bar buttons and use the default office fabric styles like we currently do in web. As a result, all button icons will be blue:
Hover and active states will appear the same (below shows the …

fix: make electron command bar button stylings match web

---

src/common/components/visualization-toggle.tsx
src/tests/unit/tests/common/components/__snapshots__/visualization-toggle.test.tsx.snap
src/tests/unit/tests/common/components/visualization-toggle.test.tsx

Added logic to visualization-toggle to set the ariaLabel to have the same value as the label displayed on the visualization toggle. Previously, we always set the aria-label value to the visualization name; having parity between the visually rendered label and ariaLabel makes the most sense. If no label is present in the toggle props, the aria-label value will default to the visualization name.
Tested the changes using the repro steps in the Trusted Tester bug; used NVDA and Narrator in Edge Insider
Before changes in this PR:
- displayed label: "Show tab stops"
- aria-label: "Tab stops" (since that's the visualization name)
After this PR:
- displayed label: "Show tab stops"
- aria-label: "Show tab stops" 

fix: updated Tab Stops toggle aria-label to match the visually displayed label

---

src/common/components/header.scss
src/reports/components/new-tab-link-confirmation-dialog.tsx
src/reports/components/report-sections/collapsible-script-provider.tsx
src/reports/components/report-sections/header-section.scss
src/tests/unit/tests/reports/components/new-tab-link-confirmation-dialog.test.tsx
src/tests/unit/tests/reports/components/report-sections/__snapshots__/collapsible-script-provider.test.ts.snap
src/tests/unit/tests/reports/components/report-sections/collapsible-script-provider.test.ts
src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap

This is a partial fix for #1875. It fixes two issues:
* Our logo had an explicit `height` CSS property but only an implied `width` property, which IE misinterprets as "100%" instead of "scaled down by the same factor as the height". This caused the logo to take up the entire screen width and push the "Accessibility Insights for Web" text completely off-screen. We fix this by providing a `width` as well as a `height` (the logo image is a square, so we just use the same dimension as the height).
* The scripts we injected failed to run in IE because they were defined in terms of arrow-functions, which IE does not support. Updating the source of the injected functions to use `function() {}` style instead of `() => {}` style fixes the issue and makes expand/collapse behavior and our target …

fix: improve compatibility of fastpass exported reports with IE

---

src/common/components/fix-instruction-processor.tsx
src/tests/unit/tests/common/components/cards/__snapshots__/how-to-fix-card-row.test.tsx.snap
src/tests/unit/tests/common/components/cards/__snapshots__/rules-with-instances.test.tsx.snap
src/tests/unit/tests/reports/components/report-sections/__snapshots__/report-body.test.tsx.snap

Firefox's `RegExp` implementation doesn't support named capture groups ([bugzilla 1362154](https://bugzilla.mozilla.org/show_bug.cgi?id=1362154)). This updates the one place we currently use them to use an index-based capture group instead. No impact on Chromium.
- [n/a (existing test already covers implementation)] Added/updated relevant unit test(s) (and ran `yarn test`)

fix(firefox-compat): avoid RegExp named captures

---

src/background/extension-details-view-controller.ts
src/debug-tools/controllers/debug-tools-controller.ts
src/tests/unit/tests/background/extension-details-view-controller.test.ts

Firefox and Chromium have different behavior when the webextension `windows.create()` API is invoked with a relative URL; Chromium resolves the relative URL relative to the root of the webextension, where Firefox resolves it relative to the path containing the invoking page. In practice, this means that Firefox tries to open DetailsView/debug pages as `moz-extension://extensionid/background/debug-tools/debug-tools.html` (note the extra `/background/` in there).
This resolves the firefox issue without impacting the chromium behavior by updating the cases that use relative URLs to instead use document-root-relative URLs, which both engines resolve as relative to the extension origin.
The combination of this, #2744, and #2745, and using Firefox 77 (beta) is enough to get a details view to …

fix(firefox-compat): avoid relative paths from background windows.create()

---

src/DetailsView/components/details-view-command-bar.scss
src/DetailsView/components/report-export-component.tsx
src/DetailsView/components/start-over-dropdown.tsx
src/common/components/controls/insights-command-button.scss
src/common/components/controls/insights-command-button.tsx
src/electron/views/automated-checks/components/command-bar.scss
src/electron/views/automated-checks/components/command-bar.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-component-factory.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-component.test.tsx.snap
src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-dropdown.test.tsx.snap
src/tests/unit/tests/DetailsView/components/report-export-component.test.tsx
src/tests/unit/tests/DetailsView/components/start-over-dropdown.test.tsx
src/tests/unit/tests/common/components/controls/__snapshots__/insights-command-button.test.tsx.snap
src/tests/unit/tests/common/components/controls/insights-command-button.test.tsx
src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/command-bar.test.tsx.snap

Currently, when a button in the command bar is in the active state, the button text is the primary text color, and the icon is very dark blue. Usually the text and icon colors are very close, but in high contrast mode, the icon color does not have sufficient contrast with the background:
Changes in this pr:
- For InsightsCommandButton, change the icon style in active state to match text color (for all command bar buttons in web and electron)
- Consistently use InsightsCommandButton instead of Action Button in the command bar (this also adds the same high contrast mode styling to electron that we have in web for the start over button while the scan is in progress)
Active start over button with new styling:
This doesn't change the default or hover states.
- [n/a] (UI changes only) Verified …

fix: Command button icon color in active state

---

src/DetailsView/actions/details-view-action-message-creator.ts
src/DetailsView/components/left-nav/assessment-left-nav.tsx
src/DetailsView/components/left-nav/details-view-left-nav.tsx
src/DetailsView/components/left-nav/left-nav-link-builder.tsx
src/DetailsView/components/left-nav/nav-link-handler.ts
src/background/actions/action-payloads.ts
src/background/actions/assessment-action-creator.ts
src/background/actions/assessment-actions.ts
src/background/stores/assessment-store.ts
src/common/messages.ts
src/common/types/store-data/assessment-result-data.ts
src/tests/unit/common/assessment-store-data-builder.ts
src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
src/tests/unit/tests/DetailsView/components/left-nav/assessment-left-nav.test.tsx
src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx
src/tests/unit/tests/DetailsView/handlers/nav-link-handler.test.ts
src/tests/unit/tests/background/actions/assessment-action-creator.test.ts
src/tests/unit/tests/background/stores/assessment-store.test.ts

When the test's heading nav link is clicked, store that test as the currently expanded test in AssessmentStore and toggle the expanded state of the nav link. All links will start as collapsed by default.
Styling to highlight the expanded portion of the nav will be added in a later PR.

feat(nav-bar-functionality): Store expanded nav state in AssessmentStore and toggle nav link expansion state

---

src/DetailsView/components/left-nav/fluent-side-nav.scss
src/DetailsView/components/left-nav/fluent-side-nav.tsx
src/DetailsView/details-view-body.tsx
src/tests/unit/tests/DetailsView/components/__snapshots__/fluent-side-nav.test.tsx.snap
src/tests/unit/tests/DetailsView/components/fluent-side-nav.test.tsx
src/tests/unit/tests/DetailsView/details-view-body.test.tsx

Adding the left panel that contains the nav component. (It is not wired up yet).
The same nav component will have two instances in the dom, and the media query will control which one to show.
Screenshot:

feat(nav-bar-functionality): create side nav
